// Weetjes — fun facts per world, read by the guide. The arrays are aligned
// across languages (same fact at the same index), so a fact's id is
// `${world}-${index}` and "discovered" progress carries over when the language
// changes. Keep them short, true, cheerful and child-safe.
window.KWIZILLO_FACTS={
  nl:{
    ruimte:[
      {e:'☀️',t:'De zon is zo groot dat er meer dan een miljoen aardes in passen.'},
      {e:'🌙',t:'Op de maan weeg je zes keer minder dan op aarde. Daar kun je enorm hoog springen!'},
      {e:'🪐',t:'Een dag op Venus duurt langer dan een heel jaar op Venus. Venus draait heel langzaam om zijn as.'},
      {e:'🔇',t:'In de ruimte is het helemaal stil. Er is geen lucht, en zonder lucht kan geluid nergens doorheen.'},
      {e:'🧑‍🚀',t:'Astronauten worden in de ruimte een paar centimeter langer, omdat hun rug niet meer wordt samengedrukt.'},
      {e:'💡',t:'Het licht van de zon doet er ruim acht minuten over om bij de aarde te komen. Je ziet de zon dus altijd zoals hij acht minuten geleden was.'},
      {e:'🟠',t:'Jupiter is zo groot dat alle andere planeten van ons zonnestelsel er samen in zouden passen.'},
      {e:'🔴',t:'Op Mars staat de hoogste berg van ons zonnestelsel: Olympus Mons, bijna drie keer zo hoog als de Mount Everest.'},
      {e:'🛁',t:'Saturnus is zo licht dat hij zou blijven drijven als je een badkuip vond die groot genoeg was.'},
      {e:'👣',t:'De voetstappen van de astronauten op de maan blijven miljoenen jaren staan. Er is geen wind om ze uit te wissen.'},
      {e:'🚀',t:'Een ruimtepak is eigenlijk een piepklein ruimteschip: het heeft zijn eigen lucht, verwarming, water en radio.'},
      {e:'🌅',t:'Het ruimtestation ISS vliegt zo snel rond de aarde dat de astronauten zestien keer per dag de zon zien opkomen.'},
      {e:'💨',t:'Op Neptunus waait de hardste wind van alle planeten: meer dan tweeduizend kilometer per uur.'},
      {e:'✨',t:'Sommige sterren die je ’s nachts ziet, staan zo ver weg dat hun licht al duizenden jaren onderweg is.'},
      {e:'🌍',t:'De aarde draait als een tol. Bij de evenaar draai je met meer dan zestienhonderd kilometer per uur mee, zonder dat je er iets van voelt.'},
      {e:'🌌',t:'Onze melkweg heeft meer dan honderd miljard sterren. Als je ze één per seconde telt, ben je meer dan drieduizend jaar bezig.'}
    ],
    dieren:[
      {e:'🐙',t:'Een octopus heeft drie harten en blauw bloed.'},
      {e:'🐘',t:'Olifanten zijn de enige landdieren die niet kunnen springen.'},
      {e:'🐦',t:'De kolibrie is de enige vogel die achteruit kan vliegen.'},
      {e:'🐋',t:'De blauwe vinvis is het grootste dier dat ooit heeft geleefd. Zijn hart is zo groot als een kleine auto.'},
      {e:'🦋',t:'Vlinders proeven met hun poten. Zo weten ze meteen of een blad lekker is.'},
      {e:'🦥',t:'Een luiaard beweegt zo langzaam dat er algen op zijn vacht groeien. Daardoor wordt hij een beetje groen.'},
      {e:'🦦',t:'Zeeotters houden elkaars poten vast als ze slapen, zodat ze niet van elkaar wegdrijven.'},
      {e:'🦎',t:'Een kameleon verandert vooral van kleur om te laten zien hoe hij zich voelt, niet alleen om zich te verstoppen.'},
      {e:'🐄',t:'Koeien hebben beste vriendinnen en vinden het niet fijn als ze uit elkaar worden gehaald.'},
      {e:'🪳',t:'Een kakkerlak kan een week zonder hoofd leven. Hij ademt namelijk door gaatjes in zijn lijf.'},
      {e:'🐧',t:'Sommige pinguïns geven elkaar een mooi steentje cadeau. Zo laten ze zien dat ze elkaar lief vinden.'},
      {e:'🦒',t:'Een giraf heeft precies evenveel nekwervels als jij: zeven. Alleen zijn die van hem véél langer.'},
      {e:'🐶',t:'Honden ruiken wel tienduizend keer beter dan mensen. Daarom kunnen ze zelfs een verstopt koekje vinden.'},
      {e:'🐜',t:'Een mier kan wel vijftig keer haar eigen gewicht dragen. Dat is alsof jij een auto optilt.'},
      {e:'🐬',t:'Dolfijnen slapen met één helft van hun hersenen tegelijk. De andere helft blijft wakker om te ademen en op te letten.'},
      {e:'🐢',t:'Sommige reuzenschildpadden worden meer dan honderd jaar oud. Jonathan, de oudste, is al meer dan honderdnegentig.'}
    ],
    aarde:[
      {e:'🌍',t:'De aarde is niet helemaal rond. Bij de evenaar is ze een klein beetje dikker, omdat ze zo snel draait.'},
      {e:'💧',t:'Meer dan zeventig procent van de aarde is bedekt met water. Daarom noemen we haar ook wel de blauwe planeet.'},
      {e:'⚡',t:'Bliksem is wel vijf keer heter dan het oppervlak van de zon, maar duurt maar een fractie van een seconde.'},
      {e:'🏞️',t:'De Nijl is de langste rivier van de wereld: ruim zesduizend zeshonderd kilometer lang.'},
      {e:'🧊',t:'Op Antarctica ligt zo veel ijs dat de zee wel zestig meter zou stijgen als het allemaal zou smelten.'},
      {e:'🔥',t:'Diep onder je voeten is het gloeiend heet. Het binnenste van de aarde is ongeveer net zo heet als het oppervlak van de zon.'},
      {e:'🌈',t:'Een regenboog is eigenlijk een hele cirkel. Vanaf de grond zie je alleen de bovenste helft.'},
      {e:'🏔️',t:'De Mount Everest groeit elk jaar een paar millimeter, omdat twee stukken aardkorst tegen elkaar duwen.'},
      {e:'❄️',t:'Elke sneeuwvlok heeft zes punten, en geen twee sneeuwvlokken zijn precies hetzelfde.'},
      {e:'🌊',t:'Het diepste punt van de oceaan is bijna elf kilometer diep. De Mount Everest zou er helemaal in verdwijnen.'},
      {e:'🏜️',t:'Een woestijn hoeft niet heet te zijn. Antarctica is de grootste woestijn ter wereld, omdat er bijna nooit regen of sneeuw valt.'},
      {e:'🦛',t:'Duizenden jaren geleden was de Sahara groen, met meren, gras en zelfs nijlpaarden.'},
      {e:'☄️',t:'Elke dag valt er ruimtestof op de aarde: bij elkaar tientallen tonnen, meestal zo klein dat je het niet ziet.'},
      {e:'🌋',t:'De meeste vulkanen op aarde zie je nooit: ze liggen diep onder water op de zeebodem.'},
      {e:'🪨',t:'De oudste stenen op aarde zijn ongeveer vier miljard jaar oud, bijna zo oud als de aarde zelf.'},
      {e:'🌳',t:'Bomen in een bos zijn onder de grond met elkaar verbonden door schimmeldraden. Daardoor kunnen ze water en voedsel delen.'}
    ],
    geschiedenis:[
      {e:'🔺',t:'De grote piramide van Gizeh was bijna vierduizend jaar lang het hoogste gebouw van de wereld.'},
      {e:'🧺',t:'De Romeinen wasten hun kleren met urine. Daar zit een stof in die vlekken weghaalt.'},
      {e:'🎲',t:'In het oude Egypte speelden kinderen al bordspellen. Senet is meer dan vijfduizend jaar oud.'},
      {e:'⛑️',t:'Vikingen hadden geen hoorns op hun helmen. Dat is pas veel later verzonnen voor toneelstukken.'},
      {e:'🧱',t:'De Chinese Muur is zo lang dat je er maanden over zou doen om hem helemaal te lopen.'},
      {e:'👑',t:'Cleopatra leefde dichter bij onze tijd dan bij de bouw van de grote piramide.'},
      {e:'🏛️',t:'De eerste Olympische Spelen waren bijna tweeduizend achthonderd jaar geleden in Griekenland. Er was maar één wedstrijd: hardlopen.'},
      {e:'🍞',t:'In de middeleeuwen aten mensen vaak van een dikke snee oud brood in plaats van een bord. Na het eten gaf je het brood aan de armen of de hond.'},
      {e:'🪶',t:'Vroeger schreef je met een ganzenveer en inkt. Een fout kraste je weg met een klein mesje.'},
      {e:'🛡️',t:'Het harnas van een ridder woog wel twintig tot dertig kilo. Toch kon een ridder ermee rennen en op zijn paard klimmen.'},
      {e:'✈️',t:'De eerste vlucht van de gebroeders Wright duurde maar twaalf seconden. Toch veranderde die de wereld.'},
      {e:'🌾',t:'Nederlanders maalden vroeger met windmolens het water uit meren. Zo ontstond nieuw land: de polders.'},
      {e:'🏠',t:'Rijke Romeinen hadden al vloerverwarming. Onder de vloer stroomde warme lucht van een vuur.'},
      {e:'🍅',t:'Ketchup werd bijna tweehonderd jaar geleden in Amerika als medicijn verkocht.'},
      {e:'🏺',t:'Farao Toetanchamon werd koning van Egypte toen hij ongeveer negen jaar oud was.'},
      {e:'📷',t:'De allereerste foto werd bijna tweehonderd jaar geleden gemaakt. Je moest er uren voor stilstaan.'}
    ],
    wetenschap:[
      {e:'🍯',t:'Honing bederft nooit. In oude Egyptische graven is honing gevonden die na duizenden jaren nog eetbaar was.'},
      {e:'🦴',t:'Een volwassene heeft ongeveer tweehonderdzes botten. Een baby heeft er meer dan tweehonderdzeventig, die later aan elkaar groeien.'},
      {e:'💡',t:'Licht is het snelste wat er bestaat: driehonderdduizend kilometer in één seconde. Zeven keer rond de aarde, in een tel.'},
      {e:'🧊',t:'IJs drijft omdat bevroren water lichter is dan vloeibaar water. Daarom bevriest een meer van boven naar beneden, en blijven de vissen warm.'},
      {e:'🧠',t:'Je hersenen zijn maar twee procent van je gewicht, maar gebruiken twintig procent van al je energie.'},
      {e:'🔊',t:'Geluid gaat door water ruim vier keer sneller dan door lucht. Walvissen horen elkaar honderden kilometers ver.'},
      {e:'🧬',t:'In bijna elke cel van je lichaam zit DNA. Als je het DNA van één cel uitrolt, is het ongeveer twee meter lang.'},
      {e:'🧭',t:'Een kompas wijst naar het noorden omdat de aarde zelf een reusachtige magneet is.'},
      {e:'❤️',t:'Je hart klopt ongeveer honderdduizend keer per dag, zonder dat je er ooit aan hoeft te denken.'},
      {e:'🪟',t:'Glas is gemaakt van zand. Als zand zo heet wordt dat het smelt en dan afkoelt, wordt het doorzichtig.'},
      {e:'💎',t:'Een diamant en het grafiet in je potlood zijn gemaakt van precies hetzelfde spul: koolstof. Alleen de bouwstenen zijn anders gestapeld.'},
      {e:'🌊',t:'Ongeveer de helft van alle zuurstof die je inademt komt uit de oceaan, gemaakt door piepkleine algen.'},
      {e:'💧',t:'In één druppel water zitten meer watermoleculen dan er sterren zijn in de hele melkweg.'},
      {e:'🎈',t:'Warme lucht stijgt op. Daarom gaat een luchtballon omhoog zodra de brander de lucht in de ballon verwarmt.'},
      {e:'🧴',t:'Je huid vernieuwt zichzelf helemaal. Ongeveer elke maand heb je een nieuwe buitenste huidlaag.'},
      {e:'🚢',t:'Een schip van staal blijft drijven omdat het vol lucht zit en meer water wegduwt dan het zelf weegt.'}
    ],
    mysterie:[
      {e:'🗿',t:'Niemand weet precies hoe de stenen van Stonehenge zijn vervoerd. Sommige komen van meer dan tweehonderd kilometer ver.'},
      {e:'🔺',t:'In de Bermudadriehoek verdwijnen niet meer schepen dan ergens anders op zee. Het mysterie zit vooral in de spannende verhalen.'},
      {e:'📜',t:'Het Voynich-manuscript is een boek van zeshonderd jaar oud, vol tekeningen en letters die nog niemand heeft kunnen lezen.'},
      {e:'🦅',t:'De Nazca-lijnen in Peru zijn reusachtige tekeningen van dieren in de woestijn. Je ziet ze alleen goed vanuit de lucht.'},
      {e:'🌊',t:'Meer dan tachtig procent van de oceaan is nog nooit door mensen verkend. We weten meer over de maan dan over de diepzee.'},
      {e:'✨',t:'Er zijn baaien waar het water ’s nachts blauw oplicht als je erin beweegt, door piepkleine lichtgevende wezentjes.'},
      {e:'💤',t:'Wetenschappers weten nog steeds niet precies waarom we dromen.'},
      {e:'🏜️',t:'Sommige zandduinen zingen: als het zand naar beneden glijdt, klinkt er een diep brommend geluid.'},
      {e:'🗿',t:'Op Paaseiland staan bijna duizend stenen reuzen. Hoe ze precies werden verplaatst, is nog altijd een raadsel.'},
      {e:'🪨',t:'In Death Valley bewegen stenen vanzelf over de woestijnbodem en laten sporen achter. Pas in 2014 bleek dat dun ijs en wind ze duwen.'},
      {e:'🪞',t:'Een spiegel wisselt links en rechts niet echt om. Hij draait voor en achter om, en daardoor lijkt het zo.'},
      {e:'0️⃣',t:'Het cijfer nul is ongeveer veertienhonderd jaar geleden in India uitgevonden. Daarvoor was er geen teken voor “niets”.'},
      {e:'🧩',t:'Raadsel: wat wordt natter naarmate het droogt? Een handdoek!'},
      {e:'🗺️',t:'Raadsel: wat heeft steden maar geen huizen, bossen maar geen bomen, en water maar geen vissen? Een landkaart!'},
      {e:'🌐',t:'De aarde bromt. Onze planeet maakt steeds een heel zacht, heel laag geluid dat mensen niet kunnen horen.'},
      {e:'🌌',t:'Het noorderlicht ontstaat als piepkleine deeltjes van de zon hoog boven de polen tegen de lucht botsen en die laten gloeien.'}
    ]
  },
  en:{
    ruimte:[
      {e:'☀️',t:'The Sun is so big that more than a million Earths would fit inside it.'},
      {e:'🌙',t:'On the Moon you weigh six times less than on Earth. You could jump incredibly high!'},
      {e:'🪐',t:'A day on Venus lasts longer than a whole year on Venus. Venus spins very, very slowly.'},
      {e:'🔇',t:'Space is completely silent. There is no air, and without air sound has nothing to travel through.'},
      {e:'🧑‍🚀',t:'Astronauts grow a few centimetres taller in space, because their spine is no longer squashed together.'},
      {e:'💡',t:'Sunlight takes just over eight minutes to reach Earth. You always see the Sun as it was eight minutes ago.'},
      {e:'🟠',t:'Jupiter is so big that all the other planets of our solar system would fit inside it together.'},
      {e:'🔴',t:'Mars has the tallest mountain in our solar system: Olympus Mons, almost three times as high as Mount Everest.'},
      {e:'🛁',t:'Saturn is so light that it would float if you could find a bathtub big enough.'},
      {e:'👣',t:'The astronauts’ footprints on the Moon will stay for millions of years. There is no wind to blow them away.'},
      {e:'🚀',t:'A spacesuit is really a tiny spaceship: it has its own air, heating, water and radio.'},
      {e:'🌅',t:'The space station ISS flies around Earth so fast that the astronauts see the Sun rise sixteen times a day.'},
      {e:'💨',t:'Neptune has the strongest winds of all the planets: more than two thousand kilometres per hour.'},
      {e:'✨',t:'Some stars you see at night are so far away that their light has been travelling for thousands of years.'},
      {e:'🌍',t:'Earth spins like a top. At the equator you move along at more than sixteen hundred kilometres per hour, and you never feel a thing.'},
      {e:'🌌',t:'Our Milky Way has more than a hundred billion stars. Counting one per second, you would need more than three thousand years.'}
    ],
    dieren:[
      {e:'🐙',t:'An octopus has three hearts and blue blood.'},
      {e:'🐘',t:'Elephants are the only land animals that cannot jump.'},
      {e:'🐦',t:'The hummingbird is the only bird that can fly backwards.'},
      {e:'🐋',t:'The blue whale is the biggest animal that has ever lived. Its heart is as big as a small car.'},
      {e:'🦋',t:'Butterflies taste with their feet. That is how they know right away whether a leaf is tasty.'},
      {e:'🦥',t:'A sloth moves so slowly that algae grow on its fur. That makes it look a little green.'},
      {e:'🦦',t:'Sea otters hold each other’s paws while they sleep, so they do not drift apart.'},
      {e:'🦎',t:'A chameleon changes colour mostly to show how it feels, not just to hide.'},
      {e:'🐄',t:'Cows have best friends and get upset when they are separated.'},
      {e:'🪳',t:'A cockroach can live for a week without its head. It breathes through little holes in its body.'},
      {e:'🐧',t:'Some penguins give each other a pretty pebble as a present. It is their way of saying “I like you”.'},
      {e:'🦒',t:'A giraffe has exactly as many neck bones as you: seven. Its bones are just much, much longer.'},
      {e:'🐶',t:'Dogs can smell about ten thousand times better than people. That is how they find a hidden biscuit.'},
      {e:'🐜',t:'An ant can carry fifty times its own weight. That is like you lifting a car.'},
      {e:'🐬',t:'Dolphins sleep with one half of their brain at a time. The other half stays awake to breathe and keep watch.'},
      {e:'🐢',t:'Some giant tortoises live for more than a hundred years. Jonathan, the oldest, is over a hundred and ninety.'}
    ],
    aarde:[
      {e:'🌍',t:'Earth is not perfectly round. It is a little fatter at the equator because it spins so fast.'},
      {e:'💧',t:'More than seventy percent of Earth is covered with water. That is why we call it the blue planet.'},
      {e:'⚡',t:'Lightning is five times hotter than the surface of the Sun, but it lasts only a tiny fraction of a second.'},
      {e:'🏞️',t:'The Nile is the longest river in the world: more than six thousand six hundred kilometres long.'},
      {e:'🧊',t:'Antarctica holds so much ice that the sea would rise about sixty metres if it all melted.'},
      {e:'🔥',t:'Deep under your feet it is glowing hot. The centre of the Earth is about as hot as the surface of the Sun.'},
      {e:'🌈',t:'A rainbow is really a full circle. From the ground you only see the top half.'},
      {e:'🏔️',t:'Mount Everest grows a few millimetres every year, because two pieces of Earth’s crust keep pushing against each other.'},
      {e:'❄️',t:'Every snowflake has six points, and no two snowflakes are exactly the same.'},
      {e:'🌊',t:'The deepest point of the ocean is almost eleven kilometres down. Mount Everest would disappear inside it completely.'},
      {e:'🏜️',t:'A desert does not have to be hot. Antarctica is the biggest desert in the world, because it almost never rains or snows there.'},
      {e:'🦛',t:'Thousands of years ago the Sahara was green, with lakes, grass and even hippos.'},
      {e:'☄️',t:'Space dust falls on Earth every day: tens of tonnes of it, mostly so tiny you never see it.'},
      {e:'🌋',t:'Most volcanoes on Earth are never seen: they lie deep under water on the ocean floor.'},
      {e:'🪨',t:'The oldest rocks on Earth are about four billion years old, almost as old as the Earth itself.'},
      {e:'🌳',t:'Trees in a forest are connected underground by threads of fungus. That lets them share water and food.'}
    ],
    geschiedenis:[
      {e:'🔺',t:'The Great Pyramid of Giza was the tallest building in the world for almost four thousand years.'},
      {e:'🧺',t:'The Romans washed their clothes with urine. It contains a substance that gets stains out.'},
      {e:'🎲',t:'Children in ancient Egypt already played board games. Senet is more than five thousand years old.'},
      {e:'⛑️',t:'Vikings did not have horns on their helmets. That was made up much later for plays and operas.'},
      {e:'🧱',t:'The Great Wall of China is so long that walking all of it would take months.'},
      {e:'👑',t:'Cleopatra lived closer to our time than to the building of the Great Pyramid.'},
      {e:'🏛️',t:'The first Olympic Games were held almost two thousand eight hundred years ago in Greece. There was just one event: a running race.'},
      {e:'🍞',t:'In the Middle Ages people often ate off a thick slice of old bread instead of a plate. Afterwards the bread went to the poor or the dog.'},
      {e:'🪶',t:'Long ago people wrote with a goose feather and ink. A mistake was scraped away with a little knife.'},
      {e:'🛡️',t:'A knight’s armour weighed twenty to thirty kilos. Even so, a knight could run and climb onto his horse in it.'},
      {e:'✈️',t:'The Wright brothers’ first flight lasted only twelve seconds. It still changed the world.'},
      {e:'🌾',t:'The Dutch used windmills to pump the water out of lakes. That is how new land was made: the polders.'},
      {e:'🏠',t:'Rich Romans already had underfloor heating. Warm air from a fire flowed under the floor.'},
      {e:'🍅',t:'Almost two hundred years ago ketchup was sold in America as a medicine.'},
      {e:'🏺',t:'Pharaoh Tutankhamun became king of Egypt when he was about nine years old.'},
      {e:'📷',t:'The very first photograph was taken almost two hundred years ago. You had to stand still for hours.'}
    ],
    wetenschap:[
      {e:'🍯',t:'Honey never goes bad. Honey found in ancient Egyptian tombs was still edible after thousands of years.'},
      {e:'🦴',t:'An adult has about two hundred and six bones. A baby has more than two hundred and seventy, which later grow together.'},
      {e:'💡',t:'Light is the fastest thing there is: three hundred thousand kilometres in one second. Seven times around the Earth in a blink.'},
      {e:'🧊',t:'Ice floats because frozen water is lighter than liquid water. That is why a lake freezes from the top down, and the fish stay warm.'},
      {e:'🧠',t:'Your brain is only two percent of your weight, but it uses twenty percent of all your energy.'},
      {e:'🔊',t:'Sound travels through water more than four times faster than through air. Whales can hear each other hundreds of kilometres away.'},
      {e:'🧬',t:'Almost every cell in your body holds DNA. Unrolled, the DNA of one cell is about two metres long.'},
      {e:'🧭',t:'A compass points north because the Earth itself is a giant magnet.'},
      {e:'❤️',t:'Your heart beats about a hundred thousand times a day, and you never have to think about it.'},
      {e:'🪟',t:'Glass is made from sand. When sand gets so hot that it melts and then cools down, it becomes see-through.'},
      {e:'💎',t:'A diamond and the graphite in your pencil are made of exactly the same stuff: carbon. Only the building blocks are stacked differently.'},
      {e:'🌊',t:'About half of all the oxygen you breathe comes from the ocean, made by tiny algae.'},
      {e:'💧',t:'One drop of water holds more water molecules than there are stars in the whole Milky Way.'},
      {e:'🎈',t:'Warm air rises. That is why a hot-air balloon goes up as soon as the burner heats the air inside it.'},
      {e:'🧴',t:'Your skin renews itself completely. About every month you have a brand-new outer layer of skin.'},
      {e:'🚢',t:'A steel ship floats because it is full of air and pushes away more water than it weighs.'}
    ],
    mysterie:[
      {e:'🗿',t:'Nobody knows exactly how the stones of Stonehenge were moved. Some came from more than two hundred kilometres away.'},
      {e:'🔺',t:'No more ships disappear in the Bermuda Triangle than anywhere else at sea. The mystery is mostly in the exciting stories.'},
      {e:'📜',t:'The Voynich manuscript is a six-hundred-year-old book full of drawings and letters that nobody has ever been able to read.'},
      {e:'🦅',t:'The Nazca lines in Peru are gigantic drawings of animals in the desert. You can only see them properly from the sky.'},
      {e:'🌊',t:'More than eighty percent of the ocean has never been explored by people. We know more about the Moon than about the deep sea.'},
      {e:'✨',t:'There are bays where the water glows blue at night when you move through it, thanks to tiny glowing creatures.'},
      {e:'💤',t:'Scientists still do not know exactly why we dream.'},
      {e:'🏜️',t:'Some sand dunes sing: when the sand slides down, it makes a deep humming sound.'},
      {e:'🗿',t:'Easter Island has almost a thousand stone giants. How exactly they were moved is still a riddle.'},
      {e:'🪨',t:'In Death Valley rocks move across the desert floor by themselves and leave trails. Only in 2014 did scientists find out that thin ice and wind push them.'},
      {e:'🪞',t:'A mirror does not really swap left and right. It swaps front and back, and that is what makes it look that way.'},
      {e:'0️⃣',t:'The number zero was invented in India about fourteen hundred years ago. Before that there was no sign for “nothing”.'},
      {e:'🧩',t:'Riddle: what gets wetter the more it dries? A towel!'},
      {e:'🗺️',t:'Riddle: what has cities but no houses, forests but no trees, and water but no fish? A map!'},
      {e:'🌐',t:'The Earth hums. Our planet constantly makes a very soft, very low sound that people cannot hear.'},
      {e:'🌌',t:'The northern lights appear when tiny particles from the Sun crash into the air high above the poles and make it glow.'}
    ]
  },
  de:{
    ruimte:[
      {e:'☀️',t:'Die Sonne ist so groß, dass mehr als eine Million Erden hineinpassen würden.'},
      {e:'🌙',t:'Auf dem Mond wiegst du sechs Mal weniger als auf der Erde. Du könntest unglaublich hoch springen!'},
      {e:'🪐',t:'Ein Tag auf der Venus dauert länger als ein ganzes Jahr auf der Venus. Die Venus dreht sich sehr, sehr langsam.'},
      {e:'🔇',t:'Im Weltall ist es völlig still. Es gibt keine Luft, und ohne Luft hat Schall nichts, worin er sich bewegen kann.'},
      {e:'🧑‍🚀',t:'Astronauten werden im Weltall ein paar Zentimeter größer, weil ihre Wirbelsäule nicht mehr zusammengedrückt wird.'},
      {e:'💡',t:'Sonnenlicht braucht gut acht Minuten bis zur Erde. Du siehst die Sonne immer so, wie sie vor acht Minuten war.'},
      {e:'🟠',t:'Jupiter ist so groß, dass alle anderen Planeten unseres Sonnensystems zusammen hineinpassen würden.'},
      {e:'🔴',t:'Auf dem Mars steht der höchste Berg unseres Sonnensystems: der Olympus Mons, fast drei Mal so hoch wie der Mount Everest.'},
      {e:'🛁',t:'Saturn ist so leicht, dass er schwimmen würde, wenn du eine Badewanne finden könntest, die groß genug ist.'},
      {e:'👣',t:'Die Fußspuren der Astronauten auf dem Mond bleiben Millionen Jahre. Es gibt keinen Wind, der sie wegweht.'},
      {e:'🚀',t:'Ein Raumanzug ist eigentlich ein winziges Raumschiff: er hat eigene Luft, Heizung, Wasser und Funk.'},
      {e:'🌅',t:'Die Raumstation ISS fliegt so schnell um die Erde, dass die Astronauten sechzehn Mal am Tag die Sonne aufgehen sehen.'},
      {e:'💨',t:'Auf Neptun weht der stärkste Wind von allen Planeten: mehr als zweitausend Kilometer pro Stunde.'},
      {e:'✨',t:'Manche Sterne, die du nachts siehst, sind so weit weg, dass ihr Licht schon Tausende Jahre unterwegs ist.'},
      {e:'🌍',t:'Die Erde dreht sich wie ein Kreisel. Am Äquator fliegst du mit mehr als sechzehnhundert Kilometern pro Stunde mit, und du merkst nichts davon.'},
      {e:'🌌',t:'Unsere Milchstraße hat mehr als hundert Milliarden Sterne. Würdest du einen pro Sekunde zählen, bräuchtest du über dreitausend Jahre.'}
    ],
    dieren:[
      {e:'🐙',t:'Eine Krake hat drei Herzen und blaues Blut.'},
      {e:'🐘',t:'Elefanten sind die einzigen Landtiere, die nicht springen können.'},
      {e:'🐦',t:'Der Kolibri ist der einzige Vogel, der rückwärts fliegen kann.'},
      {e:'🐋',t:'Der Blauwal ist das größte Tier, das je gelebt hat. Sein Herz ist so groß wie ein kleines Auto.'},
      {e:'🦋',t:'Schmetterlinge schmecken mit den Füßen. So wissen sie sofort, ob ein Blatt lecker ist.'},
      {e:'🦥',t:'Ein Faultier bewegt sich so langsam, dass Algen in seinem Fell wachsen. Dadurch sieht es etwas grün aus.'},
      {e:'🦦',t:'Seeotter halten sich beim Schlafen an den Pfoten, damit sie nicht auseinandertreiben.'},
      {e:'🦎',t:'Ein Chamäleon wechselt die Farbe vor allem, um zu zeigen, wie es sich fühlt, nicht nur zum Verstecken.'},
      {e:'🐄',t:'Kühe haben beste Freundinnen und werden traurig, wenn man sie trennt.'},
      {e:'🪳',t:'Eine Kakerlake kann eine Woche ohne Kopf leben. Sie atmet durch kleine Löcher in ihrem Körper.'},
      {e:'🐧',t:'Manche Pinguine schenken sich einen schönen Kieselstein. Das ist ihre Art zu sagen: „Ich mag dich“.'},
      {e:'🦒',t:'Eine Giraffe hat genauso viele Halswirbel wie du: sieben. Ihre Knochen sind nur viel, viel länger.'},
      {e:'🐶',t:'Hunde riechen etwa zehntausend Mal besser als Menschen. So finden sie einen versteckten Keks.'},
      {e:'🐜',t:'Eine Ameise kann fünfzig Mal ihr eigenes Gewicht tragen. Das ist, als würdest du ein Auto heben.'},
      {e:'🐬',t:'Delfine schlafen mit einer Hirnhälfte auf einmal. Die andere bleibt wach, um zu atmen und aufzupassen.'},
      {e:'🐢',t:'Manche Riesenschildkröten leben mehr als hundert Jahre. Jonathan, die älteste, ist über hundertneunzig.'}
    ],
    aarde:[
      {e:'🌍',t:'Die Erde ist nicht perfekt rund. Am Äquator ist sie etwas dicker, weil sie sich so schnell dreht.'},
      {e:'💧',t:'Mehr als siebzig Prozent der Erde sind mit Wasser bedeckt. Darum nennen wir sie den blauen Planeten.'},
      {e:'⚡',t:'Ein Blitz ist fünf Mal heißer als die Oberfläche der Sonne, dauert aber nur einen winzigen Bruchteil einer Sekunde.'},
      {e:'🏞️',t:'Der Nil ist der längste Fluss der Welt: mehr als sechstausendsechshundert Kilometer lang.'},
      {e:'🧊',t:'In der Antarktis liegt so viel Eis, dass das Meer etwa sechzig Meter steigen würde, wenn alles schmelzen würde.'},
      {e:'🔥',t:'Tief unter deinen Füßen ist es glühend heiß. Der Erdkern ist etwa so heiß wie die Oberfläche der Sonne.'},
      {e:'🌈',t:'Ein Regenbogen ist eigentlich ein ganzer Kreis. Vom Boden siehst du nur die obere Hälfte.'},
      {e:'🏔️',t:'Der Mount Everest wächst jedes Jahr ein paar Millimeter, weil zwei Teile der Erdkruste weiter gegeneinander drücken.'},
      {e:'❄️',t:'Jede Schneeflocke hat sechs Spitzen, und keine zwei Schneeflocken sind genau gleich.'},
      {e:'🌊',t:'Die tiefste Stelle im Ozean liegt fast elf Kilometer unten. Der Mount Everest würde darin völlig verschwinden.'},
      {e:'🏜️',t:'Eine Wüste muss nicht heiß sein. Die Antarktis ist die größte Wüste der Welt, weil es dort fast nie regnet oder schneit.'},
      {e:'🦛',t:'Vor Tausenden Jahren war die Sahara grün, mit Seen, Gras und sogar Flusspferden.'},
      {e:'☄️',t:'Jeden Tag fällt Weltraumstaub auf die Erde: Dutzende Tonnen, meistens so winzig, dass du ihn nie siehst.'},
      {e:'🌋',t:'Die meisten Vulkane der Erde sieht niemand: sie liegen tief unter Wasser auf dem Meeresboden.'},
      {e:'🪨',t:'Die ältesten Steine der Erde sind etwa vier Milliarden Jahre alt, fast so alt wie die Erde selbst.'},
      {e:'🌳',t:'Bäume in einem Wald sind unter der Erde durch Pilzfäden verbunden. So können sie Wasser und Nahrung teilen.'}
    ],
    geschiedenis:[
      {e:'🔺',t:'Die Große Pyramide von Gizeh war fast viertausend Jahre lang das höchste Gebäude der Welt.'},
      {e:'🧺',t:'Die Römer waschten ihre Kleidung mit Urin. Darin steckt ein Stoff, der Flecken herausholt.'},
      {e:'🎲',t:'Kinder im alten Ägypten spielten schon Brettspiele. Senet ist mehr als fünftausend Jahre alt.'},
      {e:'⛑️',t:'Wikinger hatten keine Hörner an den Helmen. Das wurde viel später für Theater und Opern erfunden.'},
      {e:'🧱',t:'Die Chinesische Mauer ist so lang, dass man Monate bräuchte, um sie ganz abzulaufen.'},
      {e:'👑',t:'Kleopatra lebte näher an unserer Zeit als am Bau der Großen Pyramide.'},
      {e:'🏛️',t:'Die ersten Olympischen Spiele waren vor fast zweitausendachthundert Jahren in Griechenland. Es gab nur eine Sportart: einen Wettlauf.'},
      {e:'🍞',t:'Im Mittelalter aßen die Leute oft von einer dicken Scheibe altem Brot statt von einem Teller. Danach bekam das Brot der Arme oder der Hund.'},
      {e:'🪶',t:'Früher schrieb man mit einer Gänsefeder und Tinte. Einen Fehler kratzte man mit einem kleinen Messer weg.'},
      {e:'🛡️',t:'Eine Ritterrüstung wog zwanzig bis dreißig Kilo. Trotzdem konnte ein Ritter darin laufen und auf sein Pferd steigen.'},
      {e:'✈️',t:'Der erste Flug der Brüder Wright dauerte nur zwölf Sekunden. Er veränderte trotzdem die Welt.'},
      {e:'🌾',t:'Die Niederländer pumpten mit Windmühlen das Wasser aus Seen. So entstand neues Land: die Polder.'},
      {e:'🏠',t:'Reiche Römer hatten schon eine Fußbodenheizung. Warme Luft von einem Feuer strömte unter dem Boden durch.'},
      {e:'🍅',t:'Vor fast zweihundert Jahren wurde Ketchup in Amerika als Medizin verkauft.'},
      {e:'🏺',t:'Pharao Tutanchamun wurde König von Ägypten, als er etwa neun Jahre alt war.'},
      {e:'📷',t:'Das allererste Foto wurde vor fast zweihundert Jahren gemacht. Du musstest stundenlang still stehen.'}
    ],
    wetenschap:[
      {e:'🍯',t:'Honig wird nie schlecht. Honig aus altägyptischen Gräbern war nach Tausenden Jahren noch essbar.'},
      {e:'🦴',t:'Ein Erwachsener hat etwa zweihundertsechs Knochen. Ein Baby hat mehr als zweihundertsiebzig, die später zusammenwachsen.'},
      {e:'💡',t:'Licht ist das Schnellste, was es gibt: dreihunderttausend Kilometer in einer Sekunde. Sieben Mal um die Erde in einem Wimpernschlag.'},
      {e:'🧊',t:'Eis schwimmt, weil gefrorenes Wasser leichter ist als flüssiges. Darum friert ein See von oben zu, und die Fische bleiben warm.'},
      {e:'🧠',t:'Dein Gehirn ist nur zwei Prozent deines Gewichts, verbraucht aber zwanzig Prozent deiner Energie.'},
      {e:'🔊',t:'Schall bewegt sich im Wasser mehr als vier Mal schneller als in der Luft. Wale hören sich Hunderte Kilometer weit.'},
      {e:'🧬',t:'Fast jede Zelle in deinem Körper enthält DNA. Ausgerollt ist die DNA einer Zelle etwa zwei Meter lang.'},
      {e:'🧭',t:'Ein Kompass zeigt nach Norden, weil die Erde selbst ein riesiger Magnet ist.'},
      {e:'❤️',t:'Dein Herz schlägt etwa hunderttausend Mal am Tag, und du musst nie daran denken.'},
      {e:'🪟',t:'Glas wird aus Sand gemacht. Wenn Sand so heiß wird, dass er schmilzt, und dann abkühlt, wird er durchsichtig.'},
      {e:'💎',t:'Ein Diamant und das Graphit in deinem Bleistift bestehen aus genau demselben Stoff: Kohlenstoff. Nur die Bausteine sind anders gestapelt.'},
      {e:'🌊',t:'Etwa die Hälfte des Sauerstoffs, den du atmest, kommt aus dem Ozean und wird von winzigen Algen gemacht.'},
      {e:'💧',t:'In einem Wassertropfen sind mehr Wassermoleküle als es Sterne in der ganzen Milchstraße gibt.'},
      {e:'🎈',t:'Warme Luft steigt nach oben. Darum steigt ein Heißluftballon, sobald der Brenner die Luft darin erwärmt.'},
      {e:'🧴',t:'Deine Haut erneuert sich ganz. Etwa jeden Monat hast du eine brandneue äußere Hautschicht.'},
      {e:'🚢',t:'Ein Stahlschiff schwimmt, weil es voller Luft ist und mehr Wasser verdrängt, als es wiegt.'}
    ],
    mysterie:[
      {e:'🗿',t:'Niemand weiß genau, wie die Steine von Stonehenge bewegt wurden. Manche kamen von mehr als zweihundert Kilometern weit.'},
      {e:'🔺',t:'Im Bermudadreieck verschwinden nicht mehr Schiffe als anderswo auf dem Meer. Das Geheimnis steckt vor allem in den spannenden Geschichten.'},
      {e:'📜',t:'Das Voynich-Manuskript ist ein sechshundert Jahre altes Buch voller Zeichnungen und Buchstaben, die niemand lesen kann.'},
      {e:'🦅',t:'Die Nazca-Linien in Peru sind riesige Tierzeichnungen in der Wüste. Richtig sehen kann man sie nur vom Himmel aus.'},
      {e:'🌊',t:'Mehr als achtzig Prozent des Ozeans hat noch niemand erforscht. Wir wissen mehr über den Mond als über die Tiefsee.'},
      {e:'✨',t:'Es gibt Buchten, in denen das Wasser nachts blau leuchtet, wenn du dich darin bewegst, dank winziger leuchtender Lebewesen.'},
      {e:'💤',t:'Forscher wissen bis heute nicht genau, warum wir träumen.'},
      {e:'🏜️',t:'Manche Sanddünen singen: wenn der Sand hinunterrutscht, entsteht ein tiefes Brummen.'},
      {e:'🗿',t:'Auf der Osterinsel stehen fast tausend Steinriesen. Wie genau sie bewegt wurden, ist noch ein Rätsel.'},
      {e:'🪨',t:'Im Death Valley wandern Steine von selbst über den Wüstenboden und hinterlassen Spuren. Erst 2014 fanden Forscher heraus, dass dünnes Eis und Wind sie schieben.'},
      {e:'🪞',t:'Ein Spiegel tauscht nicht wirklich links und rechts. Er tauscht vorn und hinten, und das sieht dann so aus.'},
      {e:'0️⃣',t:'Die Zahl Null wurde vor etwa vierzehnhundert Jahren in Indien erfunden. Vorher gab es kein Zeichen für „nichts“.'},
      {e:'🧩',t:'Rätsel: Was wird nasser, je mehr es trocknet? Ein Handtuch!'},
      {e:'🗺️',t:'Rätsel: Was hat Städte ohne Häuser, Wälder ohne Bäume und Wasser ohne Fische? Eine Landkarte!'},
      {e:'🌐',t:'Die Erde brummt. Unser Planet macht ständig einen sehr leisen, sehr tiefen Ton, den Menschen nicht hören können.'},
      {e:'🌌',t:'Das Nordlicht entsteht, wenn winzige Teilchen von der Sonne hoch über den Polen in die Luft krachen und sie zum Leuchten bringen.'}
    ]
  },
  fr:{
    ruimte:[
      {e:'☀️',t:'Le Soleil est si grand que plus d’un million de Terres tiendraient dedans.'},
      {e:'🌙',t:'Sur la Lune tu pèses six fois moins que sur la Terre. Tu pourrais sauter incroyablement haut !'},
      {e:'🪐',t:'Un jour sur Vénus dure plus longtemps qu’une année entière sur Vénus. Vénus tourne très, très lentement.'},
      {e:'🔇',t:'L’espace est complètement silencieux. Il n’y a pas d’air, et sans air le son n’a rien pour voyager.'},
      {e:'🧑‍🚀',t:'Les astronautes grandissent de quelques centimètres dans l’espace, parce que leur colonne vertébrale n’est plus tassée.'},
      {e:'💡',t:'La lumière du Soleil met un peu plus de huit minutes à atteindre la Terre. Tu vois toujours le Soleil tel qu’il était il y a huit minutes.'},
      {e:'🟠',t:'Jupiter est si grande que toutes les autres planètes de notre système solaire tiendraient dedans ensemble.'},
      {e:'🔴',t:'Mars possède la plus haute montagne du système solaire : Olympus Mons, presque trois fois l’Everest.'},
      {e:'🛁',t:'Saturne est si légère qu’elle flotterait si tu trouvais une baignoire assez grande.'},
      {e:'👣',t:'Les traces de pas des astronautes sur la Lune resteront des millions d’années. Il n’y a pas de vent pour les effacer.'},
      {e:'🚀',t:'Une combinaison spatiale est en fait un minuscule vaisseau : elle a son air, son chauffage, son eau et sa radio.'},
      {e:'🌅',t:'La station spatiale ISS tourne si vite autour de la Terre que les astronautes voient le Soleil se lever seize fois par jour.'},
      {e:'💨',t:'Neptune a les vents les plus forts de toutes les planètes : plus de deux mille kilomètres par heure.'},
      {e:'✨',t:'Certaines étoiles que tu vois la nuit sont si loin que leur lumière voyage depuis des milliers d’années.'},
      {e:'🌍',t:'La Terre tourne comme une toupie. À l’équateur tu files à plus de mille six cents kilomètres par heure sans rien sentir.'},
      {e:'🌌',t:'Notre Voie lactée compte plus de cent milliards d’étoiles. En en comptant une par seconde, il te faudrait plus de trois mille ans.'}
    ],
    dieren:[
      {e:'🐙',t:'Une pieuvre a trois cœurs et du sang bleu.'},
      {e:'🐘',t:'Les éléphants sont les seuls animaux terrestres qui ne peuvent pas sauter.'},
      {e:'🐦',t:'Le colibri est le seul oiseau capable de voler en arrière.'},
      {e:'🐋',t:'La baleine bleue est le plus grand animal qui ait jamais vécu. Son cœur est aussi gros qu’une petite voiture.'},
      {e:'🦋',t:'Les papillons goûtent avec leurs pattes. Ils savent tout de suite si une feuille est bonne.'},
      {e:'🦥',t:'Un paresseux bouge si lentement que des algues poussent dans son pelage. Cela lui donne un air un peu vert.'},
      {e:'🦦',t:'Les loutres de mer se tiennent par la patte pendant leur sommeil, pour ne pas dériver chacune de son côté.'},
      {e:'🦎',t:'Un caméléon change surtout de couleur pour montrer ce qu’il ressent, pas seulement pour se cacher.'},
      {e:'🐄',t:'Les vaches ont des meilleures amies et deviennent tristes quand on les sépare.'},
      {e:'🪳',t:'Un cafard peut vivre une semaine sans sa tête. Il respire par de petits trous dans son corps.'},
      {e:'🐧',t:'Certains manchots s’offrent un joli caillou. C’est leur façon de dire « je t’aime bien ».'},
      {e:'🦒',t:'Une girafe a exactement autant de vertèbres au cou que toi : sept. Ses os sont juste beaucoup plus longs.'},
      {e:'🐶',t:'Les chiens sentent environ dix mille fois mieux que les humains. C’est ainsi qu’ils trouvent un biscuit caché.'},
      {e:'🐜',t:'Une fourmi peut porter cinquante fois son propre poids. C’est comme si tu soulevais une voiture.'},
      {e:'🐬',t:'Les dauphins dorment d’une moitié de cerveau à la fois. L’autre reste éveillée pour respirer et surveiller.'},
      {e:'🐢',t:'Certaines tortues géantes vivent plus de cent ans. Jonathan, la plus vieille, a plus de cent quatre-vingt-dix ans.'}
    ],
    aarde:[
      {e:'🌍',t:'La Terre n’est pas parfaitement ronde. Elle est un peu plus large à l’équateur parce qu’elle tourne très vite.'},
      {e:'💧',t:'Plus de soixante-dix pour cent de la Terre est couverte d’eau. C’est pour cela qu’on l’appelle la planète bleue.'},
      {e:'⚡',t:'Un éclair est cinq fois plus chaud que la surface du Soleil, mais il ne dure qu’une fraction de seconde.'},
      {e:'🏞️',t:'Le Nil est le plus long fleuve du monde : plus de six mille six cents kilomètres.'},
      {e:'🧊',t:'L’Antarctique contient tant de glace que la mer monterait d’environ soixante mètres si tout fondait.'},
      {e:'🔥',t:'Sous tes pieds, tout au fond, il fait brûlant. Le centre de la Terre est presque aussi chaud que la surface du Soleil.'},
      {e:'🌈',t:'Un arc-en-ciel est en fait un cercle complet. Depuis le sol tu n’en vois que la moitié du haut.'},
      {e:'🏔️',t:'L’Everest grandit de quelques millimètres chaque année, parce que deux morceaux de croûte terrestre se poussent encore.'},
      {e:'❄️',t:'Chaque flocon de neige a six branches, et deux flocons ne sont jamais exactement pareils.'},
      {e:'🌊',t:'Le point le plus profond de l’océan est à presque onze kilomètres. L’Everest y disparaîtrait entièrement.'},
      {e:'🏜️',t:'Un désert n’est pas forcément chaud. L’Antarctique est le plus grand désert du monde, car il n’y pleut et n’y neige presque jamais.'},
      {e:'🦛',t:'Il y a des milliers d’années, le Sahara était vert, avec des lacs, de l’herbe et même des hippopotames.'},
      {e:'☄️',t:'De la poussière de l’espace tombe chaque jour sur la Terre : des dizaines de tonnes, le plus souvent invisibles.'},
      {e:'🌋',t:'La plupart des volcans de la Terre, personne ne les voit : ils sont tout au fond des océans.'},
      {e:'🪨',t:'Les plus vieilles roches de la Terre ont environ quatre milliards d’années, presque l’âge de la Terre elle-même.'},
      {e:'🌳',t:'Les arbres d’une forêt sont reliés sous terre par des fils de champignons. Cela leur permet de partager eau et nourriture.'}
    ],
    geschiedenis:[
      {e:'🔺',t:'La grande pyramide de Gizeh a été le plus haut bâtiment du monde pendant presque quatre mille ans.'},
      {e:'🧺',t:'Les Romains lavaient leurs vêtements avec de l’urine. Elle contient une substance qui enlève les taches.'},
      {e:'🎲',t:'Les enfants de l’Égypte ancienne jouaient déjà à des jeux de plateau. Le senet a plus de cinq mille ans.'},
      {e:'⛑️',t:'Les Vikings n’avaient pas de cornes sur leurs casques. Cela a été inventé bien plus tard pour le théâtre et l’opéra.'},
      {e:'🧱',t:'La Grande Muraille de Chine est si longue qu’il faudrait des mois pour la parcourir entièrement.'},
      {e:'👑',t:'Cléopâtre a vécu plus près de notre époque que de la construction de la grande pyramide.'},
      {e:'🏛️',t:'Les premiers Jeux olympiques ont eu lieu il y a presque deux mille huit cents ans en Grèce. Il n’y avait qu’une épreuve : une course.'},
      {e:'🍞',t:'Au Moyen Âge, les gens mangeaient souvent sur une épaisse tranche de pain rassis au lieu d’une assiette. Ensuite le pain allait aux pauvres ou au chien.'},
      {e:'🪶',t:'Autrefois on écrivait avec une plume d’oie et de l’encre. On grattait une erreur avec un petit couteau.'},
      {e:'🛡️',t:'Une armure de chevalier pesait vingt à trente kilos. Malgré cela, un chevalier pouvait courir et monter à cheval avec.'},
      {e:'✈️',t:'Le premier vol des frères Wright n’a duré que douze secondes. Il a quand même changé le monde.'},
      {e:'🌾',t:'Les Néerlandais pompaient l’eau des lacs avec des moulins à vent. C’est ainsi qu’est née une terre nouvelle : les polders.'},
      {e:'🏠',t:'Les riches Romains avaient déjà un chauffage par le sol. L’air chaud d’un foyer circulait sous le plancher.'},
      {e:'🍅',t:'Il y a presque deux cents ans, le ketchup était vendu en Amérique comme un médicament.'},
      {e:'🏺',t:'Le pharaon Toutânkhamon est devenu roi d’Égypte vers l’âge de neuf ans.'},
      {e:'📷',t:'La toute première photographie a été prise il y a presque deux cents ans. Il fallait rester immobile pendant des heures.'}
    ],
    wetenschap:[
      {e:'🍯',t:'Le miel ne s’abîme jamais. Du miel trouvé dans des tombes égyptiennes était encore mangeable après des milliers d’années.'},
      {e:'🦴',t:'Un adulte a environ deux cent six os. Un bébé en a plus de deux cent soixante-dix, qui se soudent ensuite.'},
      {e:'💡',t:'La lumière est ce qu’il y a de plus rapide : trois cent mille kilomètres en une seconde. Sept fois le tour de la Terre en un clin d’œil.'},
      {e:'🧊',t:'La glace flotte parce que l’eau gelée est plus légère que l’eau liquide. C’est pour cela qu’un lac gèle par le haut et que les poissons restent au chaud.'},
      {e:'🧠',t:'Ton cerveau ne fait que deux pour cent de ton poids, mais il utilise vingt pour cent de ton énergie.'},
      {e:'🔊',t:'Le son voyage plus de quatre fois plus vite dans l’eau que dans l’air. Les baleines s’entendent à des centaines de kilomètres.'},
      {e:'🧬',t:'Presque chaque cellule de ton corps contient de l’ADN. Déroulé, l’ADN d’une cellule mesure environ deux mètres.'},
      {e:'🧭',t:'Une boussole indique le nord parce que la Terre elle-même est un aimant géant.'},
      {e:'❤️',t:'Ton cœur bat environ cent mille fois par jour, et tu n’as jamais besoin d’y penser.'},
      {e:'🪟',t:'Le verre est fait de sable. Quand le sable devient si chaud qu’il fond, puis refroidit, il devient transparent.'},
      {e:'💎',t:'Un diamant et le graphite de ton crayon sont faits exactement de la même chose : du carbone. Seuls les blocs sont empilés autrement.'},
      {e:'🌊',t:'Environ la moitié de l’oxygène que tu respires vient de l’océan, fabriqué par de minuscules algues.'},
      {e:'💧',t:'Une goutte d’eau contient plus de molécules d’eau qu’il n’y a d’étoiles dans toute la Voie lactée.'},
      {e:'🎈',t:'L’air chaud monte. C’est pour cela qu’une montgolfière s’élève dès que le brûleur chauffe l’air à l’intérieur.'},
      {e:'🧴',t:'Ta peau se renouvelle entièrement. Environ chaque mois tu as une toute nouvelle couche de peau à l’extérieur.'},
      {e:'🚢',t:'Un navire en acier flotte parce qu’il est plein d’air et qu’il repousse plus d’eau qu’il ne pèse.'}
    ],
    mysterie:[
      {e:'🗿',t:'Personne ne sait exactement comment les pierres de Stonehenge ont été déplacées. Certaines venaient de plus de deux cents kilomètres.'},
      {e:'🔺',t:'Il ne disparaît pas plus de navires dans le triangle des Bermudes qu’ailleurs en mer. Le mystère tient surtout aux belles histoires.'},
      {e:'📜',t:'Le manuscrit de Voynich est un livre de six cents ans rempli de dessins et de lettres que personne n’a jamais pu lire.'},
      {e:'🦅',t:'Les lignes de Nazca au Pérou sont d’immenses dessins d’animaux dans le désert. On ne les voit bien que du ciel.'},
      {e:'🌊',t:'Plus de quatre-vingts pour cent de l’océan n’a jamais été exploré. Nous connaissons mieux la Lune que les grands fonds.'},
      {e:'✨',t:'Il existe des baies où l’eau brille en bleu la nuit quand tu bouges dedans, grâce à de minuscules êtres lumineux.'},
      {e:'💤',t:'Les scientifiques ne savent toujours pas exactement pourquoi nous rêvons.'},
      {e:'🏜️',t:'Certaines dunes de sable chantent : quand le sable glisse vers le bas, on entend un profond bourdonnement.'},
      {e:'🗿',t:'L’île de Pâques compte près de mille géants de pierre. Comment ils ont été déplacés reste une énigme.'},
      {e:'🪨',t:'Dans la Vallée de la Mort, des pierres se déplacent toutes seules sur le sol et laissent des traces. Ce n’est qu’en 2014 que des scientifiques ont compris que la fine glace et le vent les poussent.'},
      {e:'🪞',t:'Un miroir n’échange pas vraiment la gauche et la droite. Il échange l’avant et l’arrière, et c’est ce qui donne cette impression.'},
      {e:'0️⃣',t:'Le chiffre zéro a été inventé en Inde il y a environ mille quatre cents ans. Avant cela, il n’existait aucun signe pour « rien ».'},
      {e:'🧩',t:'Énigme : qu’est-ce qui devient plus mouillé en séchant ? Une serviette !'},
      {e:'🗺️',t:'Énigme : qu’est-ce qui a des villes sans maisons, des forêts sans arbres et de l’eau sans poissons ? Une carte !'},
      {e:'🌐',t:'La Terre bourdonne. Notre planète émet en permanence un son très doux et très grave que les humains n’entendent pas.'},
      {e:'🌌',t:'Les aurores boréales apparaissent quand de minuscules particules du Soleil percutent l’air très haut au-dessus des pôles et le font briller.'}
    ]
  },
  pt:{
    ruimte:[
      {e:'☀️',t:'O Sol é tão grande que mais de um milhão de Terras caberiam dentro dele.'},
      {e:'🌙',t:'Na Lua você pesa seis vezes menos do que na Terra. Dá para pular altíssimo!'},
      {e:'🪐',t:'Um dia em Vênus dura mais do que um ano inteiro em Vênus. Vênus gira muito, muito devagar.'},
      {e:'🔇',t:'No espaço é silêncio total. Não há ar, e sem ar o som não tem por onde viajar.'},
      {e:'🧑‍🚀',t:'Os astronautas ficam alguns centímetros mais altos no espaço, porque a coluna deles não fica mais comprimida.'},
      {e:'💡',t:'A luz do Sol leva pouco mais de oito minutos para chegar à Terra. Você sempre vê o Sol como ele era oito minutos atrás.'},
      {e:'🟠',t:'Júpiter é tão grande que todos os outros planetas do nosso sistema solar caberiam dentro dele juntos.'},
      {e:'🔴',t:'Em Marte fica a montanha mais alta do sistema solar: o Monte Olimpo, quase três vezes mais alto que o Everest.'},
      {e:'🛁',t:'Saturno é tão leve que flutuaria se você encontrasse uma banheira grande o bastante.'},
      {e:'👣',t:'As pegadas dos astronautas na Lua vão durar milhões de anos. Lá não há vento para apagá-las.'},
      {e:'🚀',t:'Um traje espacial é uma nave espacial em miniatura: tem ar, aquecimento, água e rádio próprios.'},
      {e:'🌅',t:'A estação espacial ISS gira em volta da Terra tão rápido que os astronautas veem o Sol nascer dezesseis vezes por dia.'},
      {e:'💨',t:'Netuno tem os ventos mais fortes de todos os planetas: mais de dois mil quilômetros por hora.'},
      {e:'✨',t:'Algumas estrelas que você vê à noite estão tão longe que a luz delas viaja há milhares de anos.'},
      {e:'🌍',t:'A Terra gira como um pião. No equador você viaja a mais de mil e seiscentos quilômetros por hora sem sentir nada.'},
      {e:'🌌',t:'A nossa Via Láctea tem mais de cem bilhões de estrelas. Contando uma por segundo, você levaria mais de três mil anos.'}
    ],
    dieren:[
      {e:'🐙',t:'O polvo tem três corações e sangue azul.'},
      {e:'🐘',t:'Os elefantes são os únicos animais terrestres que não conseguem pular.'},
      {e:'🐦',t:'O beija-flor é a única ave que consegue voar para trás.'},
      {e:'🐋',t:'A baleia-azul é o maior animal que já existiu. O coração dela é do tamanho de um carro pequeno.'},
      {e:'🦋',t:'As borboletas sentem o gosto com as patas. Assim sabem na hora se uma folha é gostosa.'},
      {e:'🦥',t:'O bicho-preguiça se move tão devagar que crescem algas no pelo dele. Por isso ele fica um pouco verde.'},
      {e:'🦦',t:'As lontras-marinhas dão as patas umas às outras enquanto dormem, para não se afastarem boiando.'},
      {e:'🦎',t:'O camaleão muda de cor principalmente para mostrar como se sente, e não só para se esconder.'},
      {e:'🐄',t:'As vacas têm melhores amigas e ficam tristes quando são separadas.'},
      {e:'🪳',t:'Uma barata pode viver uma semana sem cabeça. Ela respira por furinhos no corpo.'},
      {e:'🐧',t:'Alguns pinguins dão uma pedrinha bonita de presente um ao outro. É o jeito deles de dizer “gosto de você”.'},
      {e:'🦒',t:'A girafa tem exatamente o mesmo número de ossos no pescoço que você: sete. Só que os dela são muito, muito mais longos.'},
      {e:'🐶',t:'Os cães sentem cheiros cerca de dez mil vezes melhor do que as pessoas. Por isso acham até um biscoito escondido.'},
      {e:'🐜',t:'Uma formiga carrega cinquenta vezes o próprio peso. É como se você levantasse um carro.'},
      {e:'🐬',t:'Os golfinhos dormem com uma metade do cérebro de cada vez. A outra metade fica acordada para respirar e vigiar.'},
      {e:'🐢',t:'Algumas tartarugas gigantes vivem mais de cem anos. Jonathan, a mais velha, tem mais de cento e noventa.'}
    ],
    aarde:[
      {e:'🌍',t:'A Terra não é perfeitamente redonda. Ela é um pouquinho mais gorda no equador porque gira muito rápido.'},
      {e:'💧',t:'Mais de setenta por cento da Terra é coberta de água. Por isso a chamamos de planeta azul.'},
      {e:'⚡',t:'Um raio é cinco vezes mais quente que a superfície do Sol, mas dura só uma fração de segundo.'},
      {e:'🏞️',t:'O Nilo é o rio mais longo do mundo: mais de seis mil e seiscentos quilômetros.'},
      {e:'🧊',t:'A Antártida tem tanto gelo que o mar subiria uns sessenta metros se ele derretesse todo.'},
      {e:'🔥',t:'Bem embaixo dos seus pés está pegando fogo. O centro da Terra é quase tão quente quanto a superfície do Sol.'},
      {e:'🌈',t:'O arco-íris na verdade é um círculo inteiro. Do chão você só vê a metade de cima.'},
      {e:'🏔️',t:'O Monte Everest cresce alguns milímetros por ano, porque dois pedaços da crosta terrestre ficam se empurrando.'},
      {e:'❄️',t:'Todo floco de neve tem seis pontas, e não existem dois flocos exatamente iguais.'},
      {e:'🌊',t:'O ponto mais fundo do oceano tem quase onze quilômetros. O Everest desapareceria lá dentro por completo.'},
      {e:'🏜️',t:'Um deserto não precisa ser quente. A Antártida é o maior deserto do mundo, porque quase nunca chove ou neva lá.'},
      {e:'🦛',t:'Milhares de anos atrás o Saara era verde, com lagos, grama e até hipopótamos.'},
      {e:'☄️',t:'Todo dia cai poeira do espaço na Terra: dezenas de toneladas, quase sempre tão pequena que ninguém vê.'},
      {e:'🌋',t:'A maioria dos vulcões da Terra ninguém vê: eles ficam no fundo do mar.'},
      {e:'🪨',t:'As rochas mais antigas da Terra têm cerca de quatro bilhões de anos, quase a idade da própria Terra.'},
      {e:'🌳',t:'As árvores de uma floresta estão ligadas embaixo da terra por fios de fungos. Assim elas dividem água e comida.'}
    ],
    geschiedenis:[
      {e:'🔺',t:'A Grande Pirâmide de Gizé foi o prédio mais alto do mundo por quase quatro mil anos.'},
      {e:'🧺',t:'Os romanos lavavam as roupas com urina. Ela tem uma substância que tira manchas.'},
      {e:'🎲',t:'As crianças do Egito antigo já jogavam jogos de tabuleiro. O senet tem mais de cinco mil anos.'},
      {e:'⛑️',t:'Os vikings não tinham chifres nos capacetes. Isso foi inventado muito depois, para peças de teatro.'},
      {e:'🧱',t:'A Muralha da China é tão comprida que levaria meses para percorrê-la toda a pé.'},
      {e:'👑',t:'Cleópatra viveu mais perto do nosso tempo do que da construção da Grande Pirâmide.'},
      {e:'🏛️',t:'Os primeiros Jogos Olímpicos aconteceram há quase dois mil e oitocentos anos na Grécia. Só tinha uma prova: a corrida.'},
      {e:'🍞',t:'Na Idade Média as pessoas comiam sobre uma fatia grossa de pão velho em vez de um prato. Depois o pão ia para os pobres ou para o cachorro.'},
      {e:'🪶',t:'Antigamente se escrevia com pena de ganso e tinta. Um erro era raspado com uma faquinha.'},
      {e:'🛡️',t:'A armadura de um cavaleiro pesava de vinte a trinta quilos. Mesmo assim ele conseguia correr e subir no cavalo.'},
      {e:'✈️',t:'O primeiro voo dos irmãos Wright durou só doze segundos. E mesmo assim mudou o mundo.'},
      {e:'🌾',t:'Os holandeses usavam moinhos de vento para tirar a água dos lagos. Assim nasceu terra nova: os pôlderes.'},
      {e:'🏠',t:'Os romanos ricos já tinham piso aquecido. Ar quente de uma fogueira passava por baixo do chão.'},
      {e:'🍅',t:'Há quase duzentos anos o ketchup era vendido nos Estados Unidos como remédio.'},
      {e:'🏺',t:'O faraó Tutancâmon virou rei do Egito com mais ou menos nove anos de idade.'},
      {e:'📷',t:'A primeira fotografia de todas foi tirada há quase duzentos anos. Era preciso ficar parado por horas.'}
    ],
    wetenschap:[
      {e:'🍯',t:'O mel nunca estraga. Em túmulos do Egito antigo acharam mel que ainda dava para comer depois de milhares de anos.'},
      {e:'🦴',t:'Um adulto tem cerca de duzentos e seis ossos. Um bebê tem mais de duzentos e setenta, que depois se juntam.'},
      {e:'💡',t:'A luz é a coisa mais rápida que existe: trezentos mil quilômetros em um segundo. Sete voltas na Terra num piscar de olhos.'},
      {e:'🧊',t:'O gelo flutua porque a água congelada é mais leve que a água líquida. Por isso um lago congela de cima para baixo, e os peixes ficam quentinhos.'},
      {e:'🧠',t:'Seu cérebro é só dois por cento do seu peso, mas usa vinte por cento de toda a sua energia.'},
      {e:'🔊',t:'O som viaja na água mais de quatro vezes mais rápido do que no ar. As baleias se ouvem a centenas de quilômetros.'},
      {e:'🧬',t:'Quase toda célula do seu corpo tem DNA. Desenrolado, o DNA de uma célula só tem cerca de dois metros.'},
      {e:'🧭',t:'A bússola aponta para o norte porque a própria Terra é um ímã gigante.'},
      {e:'❤️',t:'Seu coração bate cerca de cem mil vezes por dia, sem que você precise pensar nisso.'},
      {e:'🪟',t:'O vidro é feito de areia. Quando a areia esquenta tanto que derrete e depois esfria, fica transparente.'},
      {e:'💎',t:'O diamante e o grafite do seu lápis são feitos exatamente da mesma coisa: carbono. Só as pecinhas estão empilhadas de um jeito diferente.'},
      {e:'🌊',t:'Cerca de metade de todo o oxigênio que você respira vem do oceano, feito por algas minúsculas.'},
      {e:'💧',t:'Uma gota de água tem mais moléculas de água do que estrelas na Via Láctea inteira.'},
      {e:'🎈',t:'O ar quente sobe. Por isso o balão sobe assim que o queimador esquenta o ar dentro dele.'},
      {e:'🧴',t:'Sua pele se renova por completo. Mais ou menos a cada mês você tem uma camada de pele novinha por fora.'},
      {e:'🚢',t:'Um navio de aço flutua porque está cheio de ar e empurra mais água do que o próprio peso.'}
    ],
    mysterie:[
      {e:'🗿',t:'Ninguém sabe ao certo como as pedras de Stonehenge foram transportadas. Algumas vieram de mais de duzentos quilômetros de distância.'},
      {e:'🔺',t:'No Triângulo das Bermudas não somem mais navios do que em qualquer outro lugar do mar. O mistério está mais nas histórias emocionantes.'},
      {e:'📜',t:'O manuscrito Voynich é um livro de seiscentos anos cheio de desenhos e letras que ninguém nunca conseguiu ler.'},
      {e:'🦅',t:'As linhas de Nazca, no Peru, são desenhos gigantes de animais no deserto. Só dá para vê-los direito do céu.'},
      {e:'🌊',t:'Mais de oitenta por cento do oceano nunca foi explorado por pessoas. Sabemos mais sobre a Lua do que sobre o fundo do mar.'},
      {e:'✨',t:'Existem baías onde a água brilha em azul à noite quando você se mexe nela, graças a seres minúsculos que dão luz.'},
      {e:'💤',t:'Os cientistas ainda não sabem exatamente por que sonhamos.'},
      {e:'🏜️',t:'Algumas dunas de areia cantam: quando a areia escorrega para baixo, sai um som grave de zumbido.'},
      {e:'🗿',t:'A Ilha de Páscoa tem quase mil gigantes de pedra. Como exatamente foram movidos ainda é um enigma.'},
      {e:'🪨',t:'No Vale da Morte há pedras que se movem sozinhas pelo deserto e deixam rastros. Só em 2014 descobriram que gelo fino e vento as empurram.'},
      {e:'🪞',t:'O espelho não troca de verdade a esquerda pela direita. Ele troca a frente pelo fundo, e é isso que dá essa impressão.'},
      {e:'0️⃣',t:'O número zero foi inventado na Índia há cerca de mil e quatrocentos anos. Antes não havia sinal para “nada”.'},
      {e:'🧩',t:'Adivinha: o que fica mais molhado quanto mais seca? A toalha!'},
      {e:'🗺️',t:'Adivinha: o que tem cidades mas não tem casas, florestas mas não tem árvores, e água mas não tem peixes? Um mapa!'},
      {e:'🌐',t:'A Terra zumbe. Nosso planeta faz o tempo todo um som muito baixinho e grave que as pessoas não conseguem ouvir.'},
      {e:'🌌',t:'A aurora boreal aparece quando partículas minúsculas do Sol batem no ar bem acima dos polos e o fazem brilhar.'}
    ]
  }
};
