// Generated by tools/guide-talks.js — lip-synced clips per guide, language and line.
window.KWIZILLO_GUIDE_TALKS={"milo":{"nl":{"name":{"pose":"talk","mp4":"assets/milo/talk/nl/name.mp4","webm":"assets/milo/talk/nl/name.webm"}}}};
