(()=>{
  const K=window.KWIZILLO_M1=window.KWIZILLO_M1||{};
  K.app=document.getElementById('app');K.core=window.KWIZILLO_CORE;K.questions=window.KWIZILLO_QUESTIONS||[];K.topics=window.KWIZILLO_TOPICS||{};K.config=window.KWIZILLO_CONFIG||{};
  K.MASTER={home:'assets/home.png',ruimte:'assets/world_space.png',geschiedenis:'assets/world_history.png',wetenschap:'assets/world_science.png',mysterie:'assets/world_mystery.png',dieren:'assets/world_animals.png',aarde:'assets/world_earth.png',achievements:'assets/achievements.png',collection:'assets/collection.png',stats:'assets/stats.png',parent:'assets/parent.png',result:'assets/result.png'};
  K.MOTION={home:'https://d8j0ntlcm91z4.cloudfront.net/user_2yYu0y6DQa27eWwkUPG52d9yApj/hf_20260911_210153_bf123057-1f86-48e5-aac9-10efd794746a.mp4',ruimte:'https://d8j0ntlcm91z4.cloudfront.net/user_2yYu0y6DQa27eWwkUPG52d9yApj/hf_20260911_205120_165df461-61b6-421b-9717-ea92deb8fe91.mp4',mysterie:'https://d8j0ntlcm91z4.cloudfront.net/user_2yYu0y6DQa27eWwkUPG52d9yApj/hf_20260911_210153_3a36c872-6cf6-4e2e-9eaa-1623dd0835a7.mp4'};
  K.TOPIC_KEYS={ruimte:['zonnestelsel','sterren_planeten','astronauten','raket_avontuur'],geschiedenis:['egyptenaren','ridders_kastelen','romeinen','ontdekkingsreizigers'],wetenschap:['slimme_proefjes','lichaam','uitvindingen','natuur_energie'],mysterie:['raadsels','verborgen_schatten','natuurmysteries','speurtocht'],dieren:['snelle_dieren','baby_dieren','waterdieren','jungle'],aarde:['continenten_landen','weer_klimaat','oceanen_natuur','kaarten_navigatie']};
  const KEY='kwizillo-v4-state';const initial={coins:245,streak:7,level:5,xp:320,voice:'Milo',soundOn:true,musicOn:true,sfxVolume:.72,musicVolume:.24,musicTrack:'magical',timeLimitOn:true,timeLimit:45,group:5,answered:0,correct:0,quizzesPlayed:0,lastWorld:'ruimte'};K.state=Object.assign({},initial,JSON.parse(localStorage.getItem(KEY)||'{}'));K.save=()=>localStorage.setItem(KEY,JSON.stringify(K.state));K.currentWorld=K.state.lastWorld||'ruimte';K.quiz=null;K.lastView='home';

  const paths={tap:'assets/audio/tap.wav',good:'assets/audio/correct.wav',bad:'assets/audio/wrong.wav',reward:'assets/audio/reward.wav',world:'assets/audio/world.wav'};const tracks={magical:{id:'magical',label:'Magisch',icon:'✨',src:'assets/audio/music_magical_loop.wav'},adventure:{id:'adventure',label:'Avontuur',icon:'🧭',src:'assets/audio/music_adventure_loop.wav'},space:{id:'space',label:'Ruimte',icon:'🚀',src:'assets/audio/music_space_loop.wav'},calm:{id:'calm',label:'Rustig',icon:'🌙',src:'assets/audio/music_calm_loop.wav'}};const preload={};Object.entries(paths).forEach(([k,s])=>{const a=new Audio(s);a.preload='auto';preload[k]=a});let ctx=null,master=null,src=null,srcGain=null,currentId=null,ducked=false;const buffers=new Map();
  function ensure(){if(!ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;ctx=new C();master=ctx.createGain();master.connect(ctx.destination);master.gain.value=0}return ctx}function wanted(){return K.state.musicOn===false?0:Math.max(0,Math.min(1,Number(K.state.musicVolume??.24)))*(ducked?.34:1)}function ramp(sec=.18){if(!ctx||!master)return;const n=ctx.currentTime;master.gain.cancelScheduledValues(n);master.gain.setValueAtTime(master.gain.value,n);master.gain.linearRampToValueAtTime(wanted(),n+sec)}async function load(id){const t=tracks[id]||tracks.magical;if(buffers.has(t.id))return buffers.get(t.id);const c=ensure();if(!c)return null;const r=await fetch(t.src);const b=await c.decodeAudioData((await r.arrayBuffer()).slice(0));buffers.set(t.id,b);return b}async function start(id=K.state.musicTrack||'magical',cross=.35){const c=ensure();if(!c)return;if(c.state==='suspended')await c.resume().catch(()=>{});const t=tracks[id]||tracks.magical,b=await load(t.id),n=c.currentTime,s=c.createBufferSource(),g=c.createGain();s.buffer=b;s.loop=true;s.loopStart=0;s.loopEnd=b.duration;g.gain.setValueAtTime(0,n);s.connect(g);g.connect(master);s.start(n);g.gain.linearRampToValueAtTime(1,n+cross);const os=src,og=srcGain;src=s;srcGain=g;currentId=t.id;K.state.musicTrack=t.id;K.save();if(os&&og){try{og.gain.linearRampToValueAtTime(0,n+cross);os.stop(n+cross+.05)}catch(e){}}ramp(.15)}async function unlock(){const c=ensure();if(!c)return;if(c.state==='suspended')await c.resume().catch(()=>{});if(K.state.musicOn!==false&&!src)await start().catch(()=>{});else ramp(.1)}function play(kind='tap'){if(K.state.soundOn===false)return;try{const a=(preload[kind]||preload.tap).cloneNode();a.volume=Math.max(0,Math.min(1,Number(K.state.sfxVolume??.72)))*(kind==='tap'?.42:.68);a.play().catch(()=>{})}catch(e){}}async function setMusic(on){K.state.musicOn=!!on;K.save();await unlock().catch(()=>{});if(on){if(!src)await start().catch(()=>{});ramp()}else ramp()}function setSfx(on){K.state.soundOn=!!on;K.save();if(on)play('good')}function setSfxVolume(v){K.state.sfxVolume=Math.max(0,Math.min(1,Number(v)));K.save()}function setMusicVolume(v){K.state.musicVolume=Math.max(0,Math.min(1,Number(v)));K.save();ramp(.08)}async function setTrack(id){if(!tracks[id])return;K.state.musicTrack=id;K.save();await unlock();if(K.state.musicOn!==false)await start(id,.45)}function duck(on){ducked=!!on;ramp(on?.1:.25)}document.addEventListener('pointerdown',unlock,{once:true,capture:true});K.audio={tracks,play,unlock,start,setMusic,setSfx,setSfxVolume,setMusicVolume,setTrack,duck,get currentId(){return currentId}};

  let abort=null,voiceCtx=null,voiceSource=null,voiceUrl=null;const gate=K.core.createCancellationGate();
  function ensureVoiceCtx(){if(!voiceCtx){const C=window.AudioContext||window.webkitAudioContext;if(C)voiceCtx=new C()}return voiceCtx}
  async function fetchVoiceBlob(text,signal){const r=await fetch(K.config.elevenLabsProxyUrl||'/api/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,voice:K.state.voice}),signal});if(!r.ok)throw new Error(`TTS ${r.status}`);return r.blob()}
  async function playVoiceBlob(blob,token){if(!gate.isCurrent(token))return false;const c=ensureVoiceCtx();if(c){if(c.state==='suspended')await c.resume().catch(()=>{});if(!gate.isCurrent(token))return false;const data=await blob.arrayBuffer();if(!gate.isCurrent(token))return false;const buffer=await c.decodeAudioData(data.slice(0));if(!gate.isCurrent(token))return false;return new Promise(resolve=>{const source=c.createBufferSource(),gain=c.createGain(),compressor=c.createDynamicsCompressor();voiceSource=source;source.buffer=buffer;gain.gain.value=K.state.voice==='Luna'?1.32:1.0;compressor.threshold.value=-14;compressor.knee.value=18;compressor.ratio.value=3;compressor.attack.value=.003;compressor.release.value=.18;source.connect(gain);gain.connect(compressor);compressor.connect(c.destination);source.onended=()=>{if(voiceSource===source)voiceSource=null;resolve(gate.isCurrent(token))};try{source.start()}catch(e){resolve(false)}})}
    return new Promise(resolve=>{const url=URL.createObjectURL(blob),a=new Audio(url);voiceUrl=url;a.volume=1;a.onended=()=>{URL.revokeObjectURL(url);if(voiceUrl===url)voiceUrl=null;resolve(gate.isCurrent(token))};a.onerror=()=>{URL.revokeObjectURL(url);resolve(false)};a.play().catch(()=>resolve(false))})
  }
  K.stopSpeech=()=>{gate.cancel();K.audio.duck(false);try{abort?.abort()}catch(e){}abort=null;try{if(voiceSource){voiceSource.onended=null;voiceSource.stop();voiceSource.disconnect();voiceSource=null}}catch(e){}if(voiceUrl){try{URL.revokeObjectURL(voiceUrl)}catch(e){}voiceUrl=null}try{speechSynthesis?.cancel()}catch(e){}try{K.clearSpeechHighlight?.()}catch(e){}};
  K.speakSequence=async(segments,{onSegment,onDone}={})=>{segments=(segments||[]).filter(s=>s&&s.text);if(!segments.length||K.state.voice==='Stil')return;K.stopSpeech();const token=gate.begin();abort=new AbortController();const signal=abort.signal;K.audio.duck(true);const requests=segments.map(s=>fetchVoiceBlob(s.text,signal).then(blob=>({ok:true,blob})).catch(error=>({ok:false,error})));try{for(let i=0;i<segments.length;i++){const result=await requests[i];if(!gate.isCurrent(token))return;if(!result.ok)throw result.error;try{onSegment?.(segments[i],i)}catch(e){}const finished=await playVoiceBlob(result.blob,token);if(!finished||!gate.isCurrent(token))return}try{onDone?.()}catch(e){}}catch(e){if(e?.name!=='AbortError'&&gate.isCurrent(token))console.warn('Kwizillo TTS:',e?.message||e)}finally{if(gate.isCurrent(token)){K.audio.duck(false);abort=null}}};
  K.speak=text=>K.speakSequence([{kind:'speech',text}]);

  K.frame=html=>{K.stopSpeech();K.app.innerHTML=`<section class="game-frame ${new URLSearchParams(location.search).has('debug')?'debug':''}">${html}</section>`;return K.app.firstElementChild};K.toast=text=>{const f=K.app.querySelector('.game-frame');if(!f)return;const t=document.createElement('div');t.className='toast';t.textContent=text;f.appendChild(t);setTimeout(()=>t.remove(),2200)};K.sfx=(k='tap')=>K.audio.play(k);
})();