(() => {
  // Generated by tools/content-build.cjs from content/. Do not edit by hand:
  // change the question in content/<world>/<topic>.json and run the tool again.
  // Rows continue after the twenty a topic already has, and each one states its
  // own difficulty in the seventh field.
  window.KWIZILLO_MORE_PT = {
    ruimte: {
      zonnestelsel: [
        ['Que estrela está no centro do sistema solar?','O Sol',['A estrela polar','Sírio','A Lua'],'Vês-la todos os dias quando fica claro.','O Sol é a estrela à volta da qual giram os planetas.','O Sol é tão grande que caberiam mais de um milhão de Terras.',1],
        ['O que gira à volta do Sol?','Os planetas',['Só a Lua','Todas as estrelas','Nada'],'A nossa Terra é um deles.','Os oito planetas giram numa órbita à volta do Sol.','Cometas e asteroides também giram, em voltas muito mais longas.',1],
        ['Que planeta vem depois da Terra, mais longe do Sol?','Marte',['Vénus','Mercúrio','A Lua'],'É o planeta com a cor de ferrugem.','Depois da Terra vem Marte, mais longe do Sol.','Marte tem cerca de metade do tamanho da Terra.',1],
        ['Porque fica escuro à noite?','Porque a Terra roda',['Porque o Sol se apaga','Porque a Lua o come','Porque passa uma nuvem'],'O Sol continua a brilhar.','A Terra roda e o teu lugar deixa de olhar para o Sol por um tempo.','A Terra dá uma volta completa em vinte e quatro horas.',1],
        ['Qual dos oito planetas é o mais pequeno?','Mercúrio',['Marte','Vénus','A Terra'],'É também o mais perto do Sol.','Mercúrio é o planeta mais pequeno do sistema solar.','Ali faz um frio gelado de noite e um calor abrasador de dia.',1],
        ['Quanto tempo leva a Terra a dar uma volta ao Sol?','Cerca de um ano',['Um mês','Uma semana','Um dia'],'Tanto como entre dois aniversários.','A Terra leva cerca de 365 dias a dar uma volta ao Sol.','De quatro em quatro anos juntamos um dia: é um ano bissexto.',2],
        ['O que é Plutão desde 2006?','Um planeta anão',['Uma lua','Um cometa','Uma estrela'],'É pequeno de mais para um planeta normal.','Desde 2006 Plutão chama-se planeta anão.','Há mais: Ceres, Éris e Makemake também são.',2],
        ['Que dois planetas são feitos sobretudo de gás?','Júpiter e Saturno',['Terra e Marte','Mercúrio e Vénus','Marte e Vénus'],'São os dois maiores.','Júpiter e Saturno são gigantes gasosos: não darias um passo neles.','Lá no fundo o gás é apertado até parecer líquido.',2],
        ['Porque escurece às vezes a meio do dia?','A Lua tapa o Sol',['O Sol apaga-se um pouco','A Terra pára de rodar','O Sol cai atrás dos montes'],'Algo se mete entre ti e o Sol.','A Lua passa mesmo entre o Sol e a Terra e a luz baixa.','Nunca olhes para o Sol sem óculos especiais, nem num eclipse.',2],
        ['Onde consegues saltar mais alto?','Na Lua',['Na Terra','No fundo do mar','Num avião'],'Ali a gravidade puxa muito mais devagar.','A Lua puxa-te muito menos, por isso saltas seis vezes mais alto.','Os astronautas da Apollo andavam aos saltinhos porque andar não dava.',2],
        ['Que idade tem o nosso sistema solar?','4,6 mil milhões de anos',['1 milhão de anos','100 milhões de anos','500 mil milhões de anos'],'Muito mais velho do que os dinossauros, que já são antiquíssimos.','O Sol e os planetas nasceram de uma nuvem de gás e poeira.','Os pedaços mais antigos que temos caíram aqui como meteoritos.',3],
        ['Que lua de Júpiter está cheia de vulcões?','Io',['Europa','Ganimedes','Calisto'],'É a mais perto de Júpiter, que a amassa.','Io tem mais vulcões do que qualquer outro sítio do sistema solar.','Júpiter amassa-a tanto que a lua derrete por dentro.',3],
        ['De que são feitos os anéis de Saturno?','De gelo e rocha',['De gás e vapor','De poeira e nuvens','De água líquida'],'Pensa em milhares de milhões de bolas de neve.','Os anéis são milhares de milhões de pedaços de gelo e rocha.','Têm milhares de quilómetros de largura e dez metros de espessura.',3],
        ['Que planeta tem o vento mais forte?','Neptuno',['A Terra','Marte','Mercúrio'],'Quanto mais longe do Sol, mais frio e doido é o tempo.','Em Neptuno o vento sopra a quase 2000 quilómetros por hora.','A tempestade mais rápida da Terra não chega a um quarto disso.',3],
        ['Como se chama o maior vulcão do sistema solar?','Olympus Mons',['O Evereste','O Vesúvio','O Mauna Kea'],'Não fica na Terra, mas no planeta vermelho.','O Olympus Mons em Marte é quase três vezes mais alto que o Evereste.','É largo como a França: lá em cima nem verias a subida.',3],
        ['Em que planeta um dia dura mais do que um ano?','Vénus',['Mercúrio','Marte','Urano'],'Este planeta roda devagarinho sobre si mesmo.','Vénus roda uma vez em 243 dias e dá a volta ao Sol em 225.','Vénus também roda ao contrário: ali o Sol nasce a oeste.',4],
        ['Que sonda saiu primeiro do sistema solar?','Voyager 1',['Hubble','Cassini','Apollo 11'],'Partiu em 1977 e ainda voa.','Em 2012 a Voyager 1 chegou primeiro ao espaço entre as estrelas.','Leva um disco de ouro com música e saudações da Terra.',4],
        ['Quanto do peso do sistema solar está no Sol?','Mais de 99 por cento',['Cerca de metade','Cerca de um décimo','Menos de 1 por cento'],'Quase tudo, e os planetas são o resto.','O Sol pesa tanto que todos os planetas juntos não chegam a um por cento.','É mesmo por isso que os planetas continuam a girar à volta dele.',4],
        ['Que planeta foi calculado antes de ser visto?','Neptuno',['Urano','Saturno','Plutão'],'Os astrónomos viam algo a puxar Urano.','Em 1846 calcularam onde devia estar, e estava lá mesmo.','O telescópio encontrou-o nessa mesma noite, quase no ponto previsto.',4],
        ['Como se chama a casca de gelos à volta do sistema?','A nuvem de Oort',['A cintura de Kuiper','A cintura de asteroides','A Via Láctea'],'Tem o nome de um astrónomo neerlandês.','A nuvem de Oort é uma esfera de pedaços de gelo, para lá de tudo.','É de lá que vêm os cometas que passam uma vez em mil anos.',4]
      ]
    }
  };
})();
