(() => {
  // Italian bank. Same worlds, topics, order and therefore the same question ids
  // as the other banks, so progress, cards and the per-question illustrations
  // survive a language switch.
  const defs = {
    ruimte: {
      zonnestelsel: [
        ["Quale pianeta è più vicino al Sole?","Mercurio",["Venere","Marte","la Terra"],"È il pianeta più piccolo e sta tutto davanti.","Mercurio è il pianeta più vicino al Sole.","Un anno su Mercurio dura solo 88 giorni terrestri."],
        ["Quale pianeta è il nostro pianeta di casa?","la Terra",["Venere","Marte","Giove"],"Qui vivono persone, animali e piante.","Noi viviamo sulla Terra.","Circa il 71% della Terra è coperto d’acqua."],
        ["Quale pianeta è conosciuto come il pianeta rosso?","Marte",["Venere","Saturno","Nettuno"],"Il suo suolo contiene molto ossido di ferro.","Marte è chiamato il pianeta rosso.","Marte ha due piccole lune: Fobos e Deimos."],
        ["Quale pianeta ha gli anelli più famosi?","Saturno",["la Terra","Mercurio","Marte"],"È un grande gigante gassoso.","Saturno ha un sistema di anelli spettacolare.","Gli anelli sono fatti soprattutto di ghiaccio e roccia."],
        ["Qual è il pianeta più grande del nostro sistema solare?","Giove",["Marte","Venere","la Terra"],"Ha la famosa Grande Macchia Rossa.","Giove è il pianeta più grande.","Dentro Giove ci starebbero più di mille Terre."],
        ["Quale pianeta è il più lontano dal Sole?","Nettuno",["Giove","la Terra","Venere"],"È un gigante di ghiaccio azzurro e lontano.","Nettuno è il pianeta più lontano dal Sole.","Un anno su Nettuno dura circa 165 anni terrestri."],
        ["Quale pianeta si trova tra Venere e Marte?","la Terra",["Mercurio","Giove","Saturno"],"È il nostro pianeta.","L’ordine è Venere, Terra, Marte.","La Terra è il terzo pianeta dal Sole."],
        ["Che cosa gira intorno alla Terra?","la Luna",["Giove","il Sole","Marte"],"La vedi spesso nel cielo di notte.","La Luna gira intorno alla Terra.","La Luna impiega circa 27 giorni per un giro."],
        ["Quanti pianeti ha il nostro sistema solare?","8",["7","9","10"],"Oggi Plutone conta come pianeta nano.","Il nostro sistema solare ha otto pianeti.","Dal 2006 Plutone è classificato come pianeta nano."],
        ["Quale pianeta è famoso per il suo forte colore azzurro?","Nettuno",["Mercurio","Marte","Venere"],"È un lontano gigante di ghiaccio.","Nettuno appare azzurro intenso.","Il metano nella sua atmosfera rinforza il colore azzurro."]
      ],
      sterren_planeten: [
        ["Che cos’è il Sole?","Una stella",["Un pianeta","Una luna","Una cometa"],"Fa da solo la sua luce e il suo calore.","Il Sole è una stella.","La luce del Sole impiega circa 8 minuti ad arrivare sulla Terra."],
        ["Di che cosa è fatta soprattutto una stella?","Di gas caldissimo e plasma",["Di roccia fredda","Di una luna","Di una nuvola"],"Le stelle brillano da sole.","Le stelle sono fatte di gas estremamente caldo e plasma.","Il nostro Sole è una stella di taglia media."],
        ["Che cos’è una galassia?","Un gruppo enorme di stelle",["Un pianeta","Un telescopio","Una nuvola sulla Terra"],"La Via Lattea è una di queste.","Una galassia contiene moltissime stelle.","La Via Lattea ha centinaia di miliardi di stelle."],
        ["Come si chiama la nostra galassia?","La Via Lattea",["Andromeda","Orione","Saturno"],"A volte vedi una striscia chiara in un cielo scuro.","Il nostro sistema solare si trova nella Via Lattea.","La Via Lattea è una galassia a spirale."],
        ["Che cos’è una supernova?","Un’enorme esplosione di una stella",["Una luna nuova","Un lancio di razzo","Un acquazzone"],"Succede alla fine della vita di alcune stelle.","Una supernova è un’esplosione gigantesca di una stella.","Un’esplosione così può brillare fortissimo per un breve periodo."],
        ["Di che colore sono di solito le stelle più calde?","Azzurre",["Rosse","Marroni","Verdi"],"Pensa alla fiamma più calda di un fornello a gas.","Le stelle molto calde appaiono spesso azzurrine.","Le stelle rosse sono di solito più fredde di quelle azzurre."],
        ["Che cos’è un esopianeta?","Un pianeta che gira intorno a un’altra stella",["Una luna della Terra","Una cometa","Un satellite"],"Non gira intorno al nostro Sole.","Un esopianeta gira intorno a una stella diversa dal Sole.","Sono già stati scoperti migliaia di esopianeti."],
        ["Che cos’è un buco nero?","Una zona con una gravità fortissima",["Un pianeta scuro","Una nuvola","Un motore di razzo"],"Nemmeno la luce ne esce facilmente.","Un buco nero ha una gravità fortissima.","Molti buchi neri nascono da stelle molto pesanti."],
        ["Quale stella è la più vicina alla Terra?","Il Sole",["Sirio","la stella Polare","Betelgeuse"],"La vedi tutti i giorni.","Il Sole è la nostra stella più vicina.","La stella successiva è molto più lontana."],
        ["Perché sembra che le stelle brillino tremolando?","Per l’atmosfera",["Perché si accendono e si spengono","Per le loro lune","Perché girano"],"La loro luce si piega passando tra gli strati d’aria.","L’atmosfera fa tremolare un po’ la luce delle stelle.","I pianeti di solito tremolano meno delle stelle."]
      ],
      astronauten: [
        ["Come si chiama chi viaggia nello spazio?","Astronauta",["Archeologo","Sommozzatore","Capitano"],"Questa persona indossa spesso una tuta spaziale.","Un astronauta viaggia e lavora nello spazio.","Gli astronauti si allenano spesso per anni."],
        ["Perché gli astronauti indossano la tuta spaziale fuori dalla navicella?","Per avere aria e protezione",["Per il caldo","Per la velocità","Come divisa"],"Nello spazio non si può respirare così.","Una tuta spaziale fornisce ossigeno e protezione.","Protegge anche dalle temperature estreme."],
        ["Che cosa sentono spesso gli astronauti in una stazione spaziale?","L’assenza di peso",["Pioggia forte","Vento forte","Terremoti"],"Sembra che galleggino.","In orbita gli astronauti vivono in microgravità.","Tutto va fissato, altrimenti vola via."],
        ["Dove dormono di solito gli astronauti nella stazione spaziale?","In sacchi a pelo fissati",["In letti normali","In amache fuori","Per terra"],"Altrimenti volerebbero via.","Gli astronauti dormono in sacchi a pelo fissati alla parete.","In microgravità non c’è un vero sopra o sotto."],
        ["Perché gli astronauti si allenano sott’acqua?","Per imitare l’assenza di peso",["Per nuotare più veloci","Per cercare acqua lunare","Per rilassarsi"],"Sott’acqua puoi provare i movimenti in galleggiamento.","L’allenamento sott’acqua serve a provare le passeggiate spaziali.","In grandi vasche ci sono a volte modelli della stazione."],
        ["Che cos’è una passeggiata spaziale?","Un lavoro fuori dal veicolo spaziale",["Camminare sulla Terra","Correre dentro un razzo","Passeggiare in un museo"],"L’astronauta resta collegato con sistemi di sicurezza.","Una passeggiata spaziale si chiama anche EVA.","L’astronauta indossa una tuta spaziale completa."],
        ["Che cosa succede ai muscoli dopo tanto tempo senza peso?","Possono indebolirsi",["Diventano d’acciaio","Spariscono subito","Crescono sempre più in fretta"],"Per questo gli astronauti si allenano molto.","Senza allenamento muscoli e ossa si indeboliscono.","Gli astronauti si allenano ogni giorno sulla ISS."],
        ["Che cosa mangiano gli astronauti nello spazio?","Cibo confezionato in modo speciale",["Pillole","Gelato","Niente"],"Deve essere sicuro in microgravità.","Gli astronauti mangiano cibo confezionato in modo speciale.","Le briciole sono un problema perché svolazzano."],
        ["Che cos’è la ISS?","Una stazione spaziale internazionale",["Un pianeta","Un motore di razzo","Una base lunare"],"Gira intorno alla Terra.","La ISS è una grande stazione spaziale in orbita intorno alla Terra.","Ci lavorano insieme astronauti di vari paesi."],
        ["Perché un astronauta deve agganciarsi mentre lavora?","Per non volare via",["Per avere più gravità","Contro la pioggia","Per andare più veloce"],"In microgravità continui a muoverti facilmente.","Agganciarsi evita di andare alla deriva senza controllo.","Anche gli attrezzi vengono assicurati."]
      ],
      raket_avontuur: [
        ["A che cosa serve un motore di razzo?","A creare la spinta",["A stampare foto","A fare ossigeno","A contare le stelle"],"Spinge gas caldi all’indietro.","Un motore di razzo dà la spinta.","Per azione e reazione il razzo va dall’altra parte."],
        ["Perché un razzo ha bisogno di tanto carburante?","Per sfuggire alla gravità",["Per l’illuminazione","Per l’aria condizionata","Per la radio"],"Il decollo richiede un’enormità di energia.","Un lancio richiede quantità enormi di energia.","Al decollo la maggior parte di un razzo può essere carburante."],
        ["Che cosa succede al decollo?","Il razzo sale",["Il razzo atterra","Il motore si spegne sempre","La Luna si avvicina"],"È il momento della partenza.","Il decollo è il momento in cui il razzo lascia il suolo.","I primi secondi sono tecnicamente molto importanti."],
        ["Perché alcuni razzi hanno più stadi?","Per lasciare cadere le parti vuote",["Per avere più finestrini","Per avere le cuccette","Per i colori"],"Così il razzo porta meno massa.","Un razzo lascia cadere uno stadio quando il carburante è finito.","Così accelerare dopo diventa più efficiente."],
        ["Che cos’è una rampa di lancio?","Il posto da cui parte un razzo",["Un satellite","Un rover lunare","Un sedile della cabina"],"Lì il razzo sta prima della partenza.","Una rampa di lancio sostiene il razzo prima del volo.","Ci sono grandi impianti per carburante, raffreddamento e sicurezza."],
        ["Che cos’è un satellite?","Un oggetto che gira intorno a un altro oggetto",["Un’esplosione di stella","Un motore di razzo","Un telescopio"],"Anche la Luna è in fondo un satellite naturale.","I satelliti girano intorno a un pianeta o a un altro corpo.","I satelliti artificiali aiutano nella navigazione e nella comunicazione."],
        ["Perché la punta di un razzo è affusolata?","Per ridurre la resistenza dell’aria",["Per pesare di più","Per raccogliere più pioggia","Per il colore"],"Una forma liscia attraversa l’aria più facilmente.","Una forma affusolata riduce la resistenza dell’aria.","Fuori dall’atmosfera la resistenza dell’aria quasi sparisce."],
        ["Che cos’è una capsula?","Una parte dove possono viaggiare persone o carico",["Una galassia","Una luna","Un carburante"],"Sta spesso in cima al razzo.","Una capsula spaziale porta persone o carico.","Alcune capsule tornano con i paracadute."],
        ["Che cosa aiuta una capsula ad atterrare in sicurezza?","I paracadute",["Le stelle","Le eruzioni solari","Gli asteroidi"],"Frenano la discesa.","I paracadute rallentano una capsula che rientra.","Alcuni veicoli atterrano anche con i motori."],
        ["Che cos’è un’orbita intorno alla Terra?","Una traiettoria in cui cadi di continuo intorno alla Terra",["Una strada dritta verso il Sole","Un tunnel","Una nuvola"],"Velocità e gravità si bilanciano.","Un satellite in orbita cade di continuo intorno alla Terra.","Per questo non precipita."]
      ]
    },
    geschiedenis: {
      egyptenaren: [
        ["Perché sono state costruite tante piramidi?","Come tombe",["Come scuole","Come mercati","Come porti"],"Pensa ai faraoni e alla loro sepoltura.","Molte piramidi erano tombe di faraoni.","La grande piramide di Giza ha migliaia di anni."],
        ["Come si chiamava un sovrano dell’antico Egitto?","Faraone",["Senatore","Cavaliere","Vichingo"],"Stava in cima alla società.","Un sovrano egizio si chiamava faraone.","Alcuni faraoni erano considerati divini."],
        ["Quale fiume era molto importante per l’Egitto?","Il Nilo",["Il Reno","Il Rio delle Amazzoni","Il Danubio"],"Attraversa il paese e rende fertile la terra.","Il Nilo era essenziale per l’agricoltura e i trasporti.","Le piene annuali portavano limo fertile."],
        ["Come si chiama la scrittura egizia fatta di segni e immagini?","Geroglifici",["Latino","Rune","Codice morse"],"Li vedi su templi e tombe.","I geroglifici erano una scrittura egizia importante.","Quella scrittura usava centinaia di segni."],
        ["Che cos’è una mummia?","Un corpo conservato",["Una moneta d’oro","Un tempio","Una barca"],"Il corpo veniva trattato in modo speciale dopo la morte.","Gli egizi facevano le mummie per conservare i corpi.","Il procedimento poteva durare molte settimane."],
        ["Su che cosa scrivevano spesso gli egizi?","Sul papiro",["Sulla plastica","Sul cemento","Sull’alluminio"],"Si faceva con una pianta del Nilo.","Il papiro veniva usato come materiale per scrivere.","Dalla parola papiro vengono «paper» in inglese e «papier» in francese."],
        ["Che cos’era la Sfinge di Giza?","Una statua con corpo di leone e testa umana",["Una piramide","Una nave","Una corona"],"Sta vicino alle piramidi.","La grande Sfinge è un’enorme statua di pietra.","La Sfinge è stata scolpita nel calcare."],
        ["A che cosa serviva l’irrigazione agli egizi?","A bagnare i campi",["A dipingere le piramidi","A scrivere","A fare monete"],"L’acqua del Nilo doveva arrivare ai campi.","L’irrigazione aiutava l’agricoltura.","Canali e vasche distribuivano l’acqua nei campi."],
        ["Quali animali erano spesso considerati speciali in Egitto?","I gatti",["Gli orsi polari","I pinguini","I canguri"],"Compaiono molto nell’arte e nella religione.","I gatti avevano un posto speciale nell’antico Egitto.","La dea Bastet era spesso raffigurata come gatta."],
        ["Che cosa facevano gli scribi nell’antico Egitto?","Tenevano testi e registri",["Facevano volare le piramidi","Addestravano cavalieri","Costruivano stelle"],"Scrivere era un’abilità importante.","Gli scribi tenevano i registri e seguivano le tasse.","Non tutti sapevano leggere e scrivere."]
      ],
      ridders_kastelen: [
        ["Che cosa indossava spesso un cavaliere per proteggersi?","Un’armatura",["Una tuta spaziale","Un accappatoio","Una muta da sub"],"Era di metallo.","L’armatura proteggeva il corpo.","Un’armatura completa aveva moltissimi pezzi."],
        ["Dove abitava spesso un signore potente?","In un castello",["In un razzo","In una piramide","In un igloo"],"L’edificio aveva muri spessi.","I castelli erano abitazioni e luoghi di difesa.","Molti castelli avevano torri e mura."],
        ["Che cos’è un fossato?","Un canale d’acqua intorno a un castello",["Una camera da letto","Una piazza del mercato","Un forno"],"Teneva lontani i visitatori indesiderati.","Il fossato rendeva il castello difficile da raggiungere.","Non tutti i fossati avevano sempre acqua."],
        ["Che cos’è un ponte levatoio?","Un ponte che si può alzare",["Una scala segreta","Una bandiera","Una torre"],"Stava spesso all’ingresso.","Un ponte levatoio poteva bloccare l’ingresso.","Spesso era unito a una porta fortificata."],
        ["Che cosa succedeva in un torneo di cavalieri?","I cavalieri gareggiavano in prove",["Si costruivano piramidi","Si navigava verso l’America","Si costruivano telescopi"],"Pensa all'equitazione e all'abilità.","I tornei erano gare per cavalieri.","I tornei attiravano pubblico da ogni parte, con musica e feste."],
        ["Che cos’è uno scudo?","Protezione del cavaliere",["Uno strumento musicale","Una mappa","Una tazza"],"I cavalieri lo portavano spesso a un braccio.","Il cavaliere teneva lo scudo davanti a sé per proteggersi.","Sugli scudi c'erano spesso i colori e i simboli della famiglia."],
        ["Chi di solito non viveva stabilmente in un castello?","Tutti i contadini della zona",["Il signore del castello","I soldati","I servitori"],"Molta gente viveva nei villaggi intorno.","La maggior parte dei contadini viveva fuori dal castello.","In caso di pericolo a volte potevano rifugiarsi lì."],
        ["Perché i castelli avevano muri spessi?","Per difendersi",["Per avere internet più veloce","Per il caldo","Per decorazione"],"Dovevano essere forti e robusti.","Muri di pietra spessi rendevano i castelli più forti.","Alcuni muri dei castelli erano spessi più di quattro metri."],
        ["Che cosa faceva spesso uno scudiero?","Aiutava un cavaliere e imparava",["Seppelliva un faraone","Pilotava un razzo","Costruiva un tempio"],"A volte si preparava a diventare cavaliere.","Uno scudiero aiutava un cavaliere e imparava il mestiere.","Non tutti gli scudieri diventavano cavalieri."],
        ["Che cos’era una fortezza?","Un luogo fortificato in cui vivere",["Una galassia","Una nave","Una materia scolastica"],"La parola si usa spesso per i castelli.","Una fortezza era un luogo fortificato.","Le fortezze stavano spesso in punti strategici."]
      ],
      romeinen: [
        ["Chi ha costruito il Colosseo?","I romani",["I vichinghi","I maya","Gli egizi"],"Si trova a Roma.","Il Colosseo è stato costruito dai romani.","Poteva contenere decine di migliaia di spettatori."],
        ["Che cos’era un acquedotto?","Una costruzione per portare l’acqua",["Un elmo da cavaliere","Un tempio per le barche","Una moneta"],"Portava l’acqua nelle città.","Gli acquedotti romani portavano l’acqua per lunghe distanze.","Alcuni acquedotti si vedono ancora oggi."],
        ["Che lingua parlavano molti romani?","Il latino",["L’olandese","Il giapponese","L’arabo"],"Molte parole italiane vengono da lì.","Il latino era una lingua importante nell’Impero romano.","L’italiano, lo spagnolo e il francese vengono dal latino."],
        ["Che cos’era una legione?","Un grande gruppo di soldati romani",["Un mercato","Delle terme","Una nave"],"Faceva parte dell’esercito.","Una legione era una grande unità dell’esercito.","I soldati romani si allenavano duramente."],
        ["Che cos’era un foro in una città romana?","Una piazza centrale",["Una prigione","Una fattoria","Un porto"],"Lì si andava per il commercio e il governo.","Il foro era un centro importante della città.","Lì c’erano spesso templi ed edifici pubblici."],
        ["A che cosa servivano le terme romane?","A lavarsi e a incontrarsi",["A costruire razzi","A conservare il grano","Ad addestrare cavalli"],"Lì ci si incontrava anche per chiacchierare.","Le terme erano luoghi d’incontro importanti.","Alcune avevano bagni caldi e freddi."],
        ["Che cosa indossava spesso un soldato romano?","Un elmo e uno scudo",["Una tuta spaziale","Un cappello da cowboy","Una muta da sub"],"Doveva proteggere la testa e il corpo.","I soldati romani portavano un elmo, un grande scudo e sandali robusti.","Il loro equipaggiamento è cambiato nei secoli."],
        ["Che cosa significa «Impero romano»?","Un grande territorio governato da Roma",["La città di Roma","Una piramide","Un ordine cavalleresco"],"Si estendeva su gran parte dell’Europa.","L’Impero romano era vastissimo.","Al suo massimo circondava tutto il Mediterraneo."],
        ["Che cosa usavano i romani per i lunghi viaggi via terra?","Una grande rete di strade",["I fiumi","Le mongolfiere","I treni"],"Molte strade erano molto solide.","I romani costruirono una grande rete di strade.","Alcune strade di oggi seguono antiche vie romane."],
        ["Che cos’era un senatore a Roma?","Una carica importante",["Un fornaio","Un faraone","Un cavaliere"],"Aveva un ruolo politico.","I senatori avevano influenza sul governo.","Il Senato romano è durato secoli."]
      ],
      ontdekkingsreizigers: [
        ["Che cosa faceva un esploratore?","Esplorava territori nuovi",["Costruiva pianeti","Inventava l’elettricità","Sorvegliava piramidi"],"Pensa ai lunghi viaggi.","Gli esploratori viaggiavano verso regioni sconosciute.","I loro viaggi cambiarono mappe e commerci."],
        ["A che cosa serviva la bussola ai marinai?","A trovare la direzione",["A cucinare","A scrivere","A misurare la profondità"],"L’ago punta più o meno a nord.","Una bussola aiuta nella navigazione.","Rese più sicuri i lunghi viaggi in mare."],
        ["Che cos’è una carta nautica?","Una mappa per navigare in mare",["Un quadro","Uno stemma da cavaliere","Una costellazione"],"Le navi la usavano per tracciare la rotta.","Le carte nautiche mostrano coste, pericoli e rotte.","Le navi moderne usano spesso carte digitali."],
        ["Perché le stelle erano utili ai marinai?","Aiutavano a capire la posizione",["Per attirare i pesci","Per fare vento","Per scaldare l’acqua"],"Soprattutto di notte davano la direzione.","Le stelle potevano aiutare nella navigazione.","La stella Polare era importante nell’emisfero nord."],
        ["Che cos’era una caravella?","Un tipo di veliero",["Delle terme romane","Un castello","Un tempio"],"Si usava per i lunghi viaggi.","Le caravelle erano velieri agili.","Ebbero un ruolo nei viaggi di scoperta europei."],
        ["Perché gli esploratori portavano provviste?","Perché i viaggi potevano durare a lungo",["Perché in mare c’erano negozi","Per decorazione","Per costruire stelle"],"In mare non si poteva andare a fare la spesa.","Cibo e acqua erano fondamentali nei lunghi viaggi.","Le carenze e le malattie erano rischi seri."],
        ["Che cos’è la navigazione?","Capire dove sei e dove stai andando",["Dipingere una nave","Imparare una lingua","Costruire un mercato"],"Bussola e mappe aiutano.","Navigare significa pianificare e seguire una rotta.","Il GPS è una forma moderna di navigazione."],
        ["Qual era un grande pericolo nei lunghi viaggi per mare?","Le tempeste e le malattie",["I semafori","La neve nel deserto","I satelliti"],"I viaggi duravano a volte mesi.","Tempeste, malattie e mancanza di cibo erano pericolose.","Lo scorbuto veniva dalla lunga mancanza di vitamina C."],
        ["Perché si cercavano nuove rotte verso l’Asia?","Per il commercio di merci preziose",["Per sciare","Per i dinosauri","Per i viaggi spaziali"],"Le spezie valevano moltissimo.","Il commercio spinse molti viaggi di scoperta.","Le spezie potevano costare carissime in Europa."],
        ["Che cosa facevano i cartografi dopo i nuovi viaggi?","Miglioravano le loro mappe",["Alzavano piramidi","Spostavano stelle","Cambiavano l’ora"],"Si aggiungevano nuove conoscenze.","I racconti di viaggio rendevano le mappe più precise.","Le mappe sono diventate più dettagliate nei secoli."]
      ]
    },
    wetenschap: {
      slimme_proefjes: [
        ["Che cosa succede spesso quando mescoli bicarbonato e aceto?","Si formano bollicine di gas",["Si ghiaccia subito","Diventa metallo","Non succede niente"],"Vedi tanta schiuma.","La reazione produce tra l’altro anidride carbonica.","Quel gas può gonfiare un palloncino, per esempio."],
        ["Perché in alcuni esperimenti si mettono gli occhiali protettivi?","Per proteggere gli occhi",["Per sentire meglio","Per correre più veloce","Per il colore"],"Alcune sostanze possono schizzare.","Gli occhiali protettivi proteggono gli occhi.","Lavorare in sicurezza fa parte della scienza."],
        ["Che cos’è un’ipotesi?","Un’aspettativa che si può mettere alla prova",["Un fatto già dimostrato","Uno strumento di misura","Un liquido"],"Decidi prima che cosa ti aspetti.","Un’ipotesi è una previsione che puoi verificare.","Dopo un esperimento può essere confermata oppure no."],
        ["In un esperimento corretto, che cosa va tenuto il più uguale possibile?","Le altre condizioni",["Il risultato","La domanda","Il tuo nome"],"Cambi una cosa sola per volta.","Tenere uguali le condizioni rende l’esperimento più corretto.","Così capisci meglio che cosa ha causato un effetto."],
        ["Con che cosa misuri con precisione un volume di liquido?","Con un cilindro graduato",["Con una lente d’ingrandimento","Con una bussola","Con un cronometro"],"Ha le tacche sul lato.","Un cilindro graduato misura il volume.","Il volume si misura spesso in millilitri."],
        ["Che cosa fa un termometro in un esperimento?","Misura la temperatura",["Misura il tempo","Misura il peso","Fa luce"],"Con quello misuri caldo o freddo.","Un termometro misura la temperatura.","Da noi si misura spesso in gradi Celsius."],
        ["Perché scrivi i risultati di un esperimento?","Per poterli confrontare",["Per dimenticarli","Per pulire il vetro","Per decorare"],"Gli scienziati annotano le loro misure.","Annotare i risultati aiuta ad analizzarli e a ripetere la prova.","La buona scienza deve poter essere controllata."],
        ["Che cosa succede al ghiaccio quando lo scaldi?","Si scioglie",["Diventa pietra","Sparisce di colpo","Diventa più pesante"],"L’acqua solida diventa liquida.","Il ghiaccio si scioglie e diventa acqua.","A pressione normale il ghiaccio si scioglie intorno a 0 °C."],
        ["Che cosa ti serve per fare un’ombra?","Una fonte di luce e un oggetto",["Del suono","Dell’acqua","Del vento"],"L’oggetto ferma la luce.","Un’ombra nasce quando la luce viene fermata.","La sua grandezza cambia con la distanza dalla fonte di luce."],
        ["Che cos’è sciogliersi, come lo zucchero nell’acqua?","La sostanza si distribuisce nel liquido",["La sostanza lascia il mondo","La sostanza diventa fuoco","Il liquido ghiaccia"],"Non vedi più i granelli separati.","Le particelle sciolte si distribuiscono nel liquido.","Facendo evaporare l’acqua spesso riprendi lo zucchero."]
      ],
      lichaam: [
        ["Quale organo pompa il sangue nel tuo corpo?","Il cuore",["I polmoni","Lo stomaco","Il cervello"],"Lo senti battere.","Il cuore pompa il sangue in tutto il corpo.","Il tuo cuore batte circa centomila volte al giorno."],
        ["Con che cosa respiri soprattutto?","Con i polmoni",["Con i reni","Con lo stomaco","Con le ossa"],"Stanno dentro il torace.","I polmoni prendono l’ossigeno.","Di solito hai due polmoni."],
        ["Quale organo ti aiuta a pensare?","Il cervello",["Il fegato","Il cuore","L’intestino"],"Sta dentro il cranio.","Il cervello elabora le informazioni e comanda molte funzioni del corpo.","Lì lavorano insieme miliardi di cellule nervose."],
        ["Che cosa porta in giro il sangue nel tuo corpo?","Ossigeno e sostanze nutritive",["Aria","Ossa","Calore"],"Il sangue scorre nei vasi sanguigni.","Il sangue trasporta tra l’altro ossigeno e sostanze nutritive.","I globuli rossi aiutano a portare l’ossigeno."],
        ["Dove comincia già la digestione del cibo?","In bocca",["Nel piede","Nel polmone","Nell’orecchio"],"Mastichi il cibo in pezzetti.","La digestione comincia in bocca.","La saliva contiene sostanze che aiutano a scomporre il cibo."],
        ["Che cosa proteggono le tue costole?","Il cuore e i polmoni",["I tuoi piedi","I tuoi denti","Le tue dita"],"Formano una gabbia intorno al torace.","Le costole proteggono organi importanti.","La maggior parte delle persone ha 12 paia di costole."],
        ["Oltre a sostenere, a che cosa servono le ossa?","A proteggere e a muoversi",["Al colore","Al sonno","Alla temperatura"],"I muscoli tirano le ossa.","Le ossa danno sostegno e protezione e aiutano a muoversi.","Nel midollo osseo si formano le cellule del sangue."],
        ["Che cosa fanno i muscoli?","Si contraggono e creano il movimento",["Fanno solo sangue","Digeriscono il cibo","Vedono la luce"],"I muscoli lavorano spesso insieme alle ossa.","I muscoli possono contrarsi e così creare movimento.","Il tuo corpo ha centinaia di muscoli."],
        ["Che cos’è la pelle?","L’organo più grande del tuo corpo",["Un osso","Un muscolo","Un vaso sanguigno"],"Copre tutto il tuo corpo.","La pelle protegge il corpo.","La pelle aiuta anche a regolare la temperatura."],
        ["Quale senso usi con le orecchie?","L’udito",["Il gusto","L’olfatto","La vista"],"Percepisci le onde sonore.","Con le orecchie percepisci i suoni.","Il tuo orecchio interno aiuta anche l’equilibrio."]
      ],
      uitvindingen: [
        ["Con che cosa puoi guardare cose piccolissime?","Con un microscopio",["Con un telescopio","Con una bussola","Con un barometro"],"Pensa alle cellule e ai batteri.","Un microscopio ingrandisce gli oggetti piccoli.","I microscopi moderni ingrandiscono moltissimo."],
        ["Con che cosa guardi stelle e pianeti lontani?","Con un telescopio",["Con un microscopio","Con un termometro","Con una calamita"],"Rende più visibili gli oggetti lontani.","Un telescopio raccoglie la luce degli oggetti lontani.","Ci sono telescopi sulla Terra e nello spazio."],
        ["Quale invenzione ha reso molto più veloce copiare i libri?","La stampa",["La bussola","Il fischio a vapore","La torcia"],"Si poteva stampare con lettere mobili.","La stampa ha permesso di fare libri in gran quantità.","Così il sapere si è diffuso più in fretta."],
        ["A che cosa serve una pila?","A immagazzinare e fornire energia elettrica",["A misurare il vento","A bollire l’acqua senza energia","A fare stelle"],"La trovi in tanti apparecchi.","Una pila fornisce energia elettrica.","Le batterie ricaricabili si possono riusare."],
        ["Che cosa fa una calamita?","Può attirare certi metalli",["Fa sempre luce","Ghiaccia l’acqua","Ferma il tempo"],"Il ferro reagisce bene.","Le calamite esercitano forze sui materiali magnetici.","Una calamita ha un polo nord e un polo sud."],
        ["Che cosa produce un pannello solare?","Elettricità dalla luce",["Pioggia dalle nuvole","Benzina dall’aria","Suono dalle pietre"],"Il Sole dà l’energia.","Le celle solari trasformano la luce in elettricità.","I pannelli solari non hanno parti in movimento."],
        ["Che cosa fa un motore?","Trasforma l’energia in movimento",["Fa i colori","Ghiaccia l’acqua","Legge la carta"],"Auto e macchine usano motori.","Un motore trasforma l’energia in movimento.","Esistono motori elettrici e a combustione."],
        ["Perché il telefono è stata un’invenzione importante?","Le persone potevano parlarsi a distanza",["Le persone potevano volare","Le persone potevano fermare il tempo","Le persone potevano vivere senza corrente"],"Il suono veniva mandato lontano.","Il telefono ha cambiato molto la comunicazione.","Oggi i cellulari uniscono tante funzioni."],
        ["Che cosa fa soprattutto un computer?","Elabora informazioni",["Fa musica","Dà luce","Depura l’acqua"],"Esegue istruzioni.","I computer elaborano dati seguendo programmi.","Anche uno smartwatch contiene un computer."],
        ["Quale invenzione usa le onde radio per trovare la posizione?","Il GPS",["La calamita","Il microscopio","Lo stetoscopio"],"I satelliti aiutano a capire dove sei.","Il GPS usa i segnali dei satelliti.","Il tuo telefono usa il GPS per navigare."]
      ],
      natuur_energie: [
        ["Quale fonte di energia usa l’aria in movimento?","L’energia eolica",["L’energia solare","Il gas naturale","L’energia nucleare"],"Le pale eoliche girano grazie a lei.","Le pale eoliche trasformano il vento in elettricità.","Le turbine grandi possono servire tante case."],
        ["Quale fonte di energia usa la luce del Sole?","L’energia solare",["Il carbone","Il petrolio","Il gas naturale"],"I pannelli raccolgono la luce.","I pannelli solari trasformano la luce in elettricità.","Il Sole dà molta più energia di quanta ne usiamo nel mondo."],
        ["Che cos’è l’energia rinnovabile?","Energia da fonti che si rigenerano sempre",["Energia che non si usa mai","Benzina","Carbone"],"Pensa al Sole e al vento.","Le fonti rinnovabili non si esauriscono in fretta.","Anche l’energia dell’acqua e quella geotermica possono essere rinnovabili."],
        ["Che cosa fa una turbina eolica?","Trasforma il vento in elettricità",["Fa la pioggia","Produce benzina","Spinge le nuvole"],"Le pale girano nel vento.","Un generatore dentro la turbina produce elettricità.","Le turbine eoliche stanno sulla terra e in mare."],
        ["Quale sostanza si libera bruciando i combustibili fossili?","L’anidride carbonica",["L’ossigeno","L’oro","L’elio"],"È un gas serra.","Bruciare petrolio, gas e carbone libera CO₂.","Più CO₂ rafforza l’effetto serra."],
        ["Perché isoliamo le case?","Per trattenere meglio il calore dentro o fuori",["Per rendere più pesanti le finestre","Per fare acqua","Per rafforzare il wifi"],"Un buon isolamento fa risparmiare energia.","L’isolamento riduce la perdita di calore.","Tetto, muri e pavimenti si possono isolare tutti."],
        ["Che cos’è l’energia idroelettrica?","Energia dall’acqua che scorre o che cade",["Energia dalla sabbia","Energia dal fumo","Energia dalla plastica"],"Una diga e un fiume possono far girare le turbine.","L’energia idroelettrica usa il movimento dell’acqua.","Nel mondo è una fonte rinnovabile importante."],
        ["Che cos’è risparmiare energia?","Usare meno energia per lo stesso risultato",["Accendere più lampade","Finestre aperte e riscaldamento acceso","Lasciare gli apparecchi accesi"],"Gli apparecchi efficienti aiutano.","Risparmiare energia riduce i consumi.","Le lampade LED consumano meno delle vecchie lampadine."],
        ["Che cosa fa la batteria di un’auto elettrica?","Immagazzina energia elettrica",["Fa la benzina","Misura il vento","Raffredda l’acqua"],"Alimenta il motore elettrico.","La batteria immagazzina energia per viaggiare.","Frenando a volte si recupera un po’ di energia."],
        ["Quale lampada di solito consuma meno?","La lampada LED",["La lampadina a filamento","La candela","La lampada alogena"],"Consuma meno corrente.","L’illuminazione LED consuma pochissimo.","Le lampade LED durano anche più a lungo."]
      ]
    },
    mysterie: {
      raadsels: [
        ["Ho tasti bianchi e neri e faccio musica. Chi sono?","Un pianoforte",["Una porta","Un forziere","Una bicicletta"],"Mi suoni con le dita.","Un pianoforte ha tasti che premi.","Un pianoforte può avere più di ottanta tasti."],
        ["Più asciugo, più divento bagnato. Chi sono?","Un asciugamano",["Un ombrello","Il Sole","Una spugna"],"Mi usi dopo il bagno.","Un asciugamano si bagna mentre ti asciuga.","Gli asciugamani assorbono l’acqua con le loro fibre."],
        ["Che cosa ha un collo ma non ha la testa?","Una bottiglia",["Un gatto","Una persona","Un gufo"],"Da lì puoi bere.","Una bottiglia ha un collo.","Le bottiglie sono di vetro o di plastica."],
        ["Che cosa ha i denti ma non può mordere?","Un pettine",["Uno squalo","Un cane","Un leone"],"Lo usi per i capelli.","Un pettine ha i denti ma non la bocca.","I pettini esistono da migliaia di anni."],
        ["Che cosa cresce sempre e non torna mai indietro?","La tua età",["Un ascensore","Una palla","Un uccello"],"Ogni anno diventa più grande.","La tua età aumenta man mano che cresci.","Al tuo compleanno si aggiunge un anno."],
        ["Ho le lancette ma non ho le mani. Chi sono?","Un orologio",["Un robot","Una persona","Una scimmia"],"Le mie lancette indicano qualcosa.","Un orologio a lancette ha un quadrante e le lancette.","Le lancette segnano ore, minuti e a volte secondi."],
        ["Che cosa puoi rompere senza toccarlo?","Una promessa",["Una pietra","Un bicchiere","Un ramo"],"Riguarda la fiducia.","Una promessa si può rompere senza toccare niente.","Gli indovinelli giocano spesso sui doppi sensi."],
        ["Ho una cruna ma non ci vedo. Chi sono?","Un ago",["Un gufo","Una persona","Una macchina fotografica"],"Dalla mia cruna passa il filo.","Un ago ha una cruna per il filo.","La cruna sta di solito a un’estremità."],
        ["Che cosa diventa più grande più gli togli?","Un buco",["Una montagna","Una scatola","Un libro"],"Pensa a scavare.","Più togli da un buco, più il buco diventa grande.","È un classico indovinello di logica."],
        ["Che cosa corre senza avere gambe?","L’acqua",["Un cane","Una persona","Un cavallo"],"Corre nei fiumi.","L’acqua può correre senza gambe.","Gli indovinelli di parole giocano con più significati."]
      ],
      verborgen_schatten: [
        ["Con che cosa apri un forziere chiuso a chiave?","Con una chiave",["Con una piuma","Con una mappa","Con una lente d’ingrandimento"],"Entra in una serratura.","Con la chiave giusta apri la serratura.","Le serrature esistono da migliaia di anni."],
        ["Che cosa c’è spesso su una mappa del tesoro?","Una X sul punto",["Un semaforo","Un codice a barre","Un termometro"],"La X segna il punto.","Una X segna spesso il posto del tesoro.","Lo si conosce soprattutto dalle storie di pirati."],
        ["A che cosa serve una bussola in una caccia al tesoro?","A trovare la direzione",["A pesare l’oro","A fare la pioggia","A scavare buche"],"L’ago ti aiuta a trovare il nord.","Una bussola aiuta nella navigazione.","Una bussola normale reagisce al campo magnetico della Terra."],
        ["Che cos’è uno scomparto segreto?","Uno spazio nascosto dentro un oggetto",["Una piazza aperta","Una nuvola","Una legenda di mappa"],"Non si vede subito.","In uno scomparto segreto si possono nascondere delle cose.","I mobili antichi avevano a volte cassetti segreti."],
        ["Che cos’è un indizio?","Un’informazione che ti avvicina alla soluzione",["Sempre la risposta finale","Un errore","Una decorazione"],"Un detective li cerca.","Gli indizi aiutano a risolvere un mistero.","Un buon indizio dà qualcosa senza svelare tutto."],
        ["Perché a volte numeri i tuoi indizi?","Per tenerli in ordine",["Per renderli più pesanti","Per nasconderli","Per cambiare i colori"],"Così ti confondi di meno.","Numerare aiuta a mettere in ordine.","I detective ordinano le prove per vedere i collegamenti."],
        ["Quale posto ha senso per un tesoro nascosto in una storia?","Sotto una pietra segnata",["In mezzo a un tavolo affollato","Su un cartello stradale","Dentro una nuvola"],"Deve stare fuori vista.","Nelle storie i tesori sono nascosti in luoghi segreti.","Le storie di tesori usano simboli riconoscibili."],
        ["Che cos’è un codice?","Un sistema per mostrare un’informazione in forma nascosta",["Un tipo di frutta","Uno strumento musicale","Una nuvola"],"Devi decifrarlo.","Un codice può nascondere un’informazione.","La crittografia è la scienza dei messaggi segreti."],
        ["Che cosa significa decifrare?","Rendere comprensibile un codice",["Seppellire qualcosa","Bruciare una mappa","Copiare una chiave"],"Cerchi il significato dietro i segni.","Decifrare vuol dire leggere un’informazione in codice.","Alcuni codici usano numeri o simboli."],
        ["Perché una mappa del tesoro dovrebbe avere una legenda?","Per spiegare i simboli",["Per rendere la mappa più pesante","Per fare rumore","Per renderla impermeabile"],"La legenda ti dice che cosa significano i segni.","Le legende delle mappe spiegano i simboli.","Anche le mappe normali hanno una legenda."]
      ],
      natuurmysteries: [
        ["Perché un bruco diventa una farfalla?","Per la metamorfosi",["Per il magnetismo","Per i fulmini","Per il gelo"],"L’animale cambia in varie fasi di vita.","Le farfalle passano attraverso una metamorfosi.","Dall’uovo si passa per bruco e crisalide fino alla farfalla."],
        ["Perché a volte vediamo un arcobaleno?","La luce si piega e si divide nelle gocce d’acqua",["Le nuvole si colorano","Il Sole lampeggia","La Luna lo dipinge"],"Sole e pioggia lavorano insieme.","Le gocce d’acqua piegano e riflettono la luce.","Un arcobaleno appare dalla parte opposta al Sole."],
        ["Perché una lucciola brilla?","Per la bioluminescenza",["Per una pila","Perché conserva la luce del Sole","Per delle calamite"],"Fa la luce dentro il proprio corpo.","La bioluminescenza è luce che nasce da una reazione chimica.","Anche alcuni animali marini sanno fare la luce."],
        ["Perché i fenicotteri sono rosa?","Per i pigmenti del loro cibo",["Perché nascono dipinti","Solo per la luce del Sole","Per l’acqua fredda"],"Nel loro cibo ci sono pigmenti.","I carotenoidi del cibo colorano di rosa le piume.","I fenicotteri giovani sono molto più grigi."],
        ["Perché i giovani boccioli di girasole seguono spesso il Sole?","Per l’eliotropismo",["Per la forza del vento","Per il magnetismo","Per la pioggia"],"Reagiscono alla luce.","I girasoli giovani possono seguire il Sole.","I fiori adulti guardano soprattutto verso est."],
        ["Perché certi animali hanno una mimetizzazione?","Per farsi notare meno",["Per crescere più in fretta","Per cantare più forte","Per fare più calore"],"Colore e disegno somigliano all’ambiente.","La mimetizzazione aiuta a cacciare o a nascondersi.","La seppia cambia aspetto velocissimamente."],
        ["Che cosa provoca soprattutto le maree?","La gravità della Luna",["Le pale eoliche","I vulcani","Le nuvole"],"La Luna tira l’acqua del mare.","La Luna è una causa importante delle maree.","Anche il Sole influisce sulle maree."],
        ["Perché i fiocchi di neve hanno spesso sei punte?","Per il modo in cui le molecole d’acqua formano i cristalli",["Per le pale eoliche","Per gli uccelli","Per la sabbia"],"Il ghiaccio forma uno schema di cristallo fisso.","La struttura del ghiaccio porta spesso a una simmetria a sei.","Non esistono due fiocchi grandi esattamente uguali."],
        ["Perché di giorno il cielo è di solito azzurro?","La luce azzurra viene diffusa di più",["Perché l’oceano dipinge il cielo","Per gli alberi","Solo per le nuvole"],"La luce del Sole contiene più colori.","L’atmosfera diffonde molto la luce azzurra a onda corta.","Al tramonto vediamo più rosso e arancione."],
        ["Perché i gechi riescono a salire sui muri?","Milioni di peluzzi sulle dita",["Ventose con la colla","Calamite","Elettricità"],"Le loro dita toccano la superficie in moltissimi punti.","Strutture microscopiche danno moltissima presa.","Quelle forze si chiamano forze di van der Waals."]
      ],
      speurtocht: [
        ["A che cosa serve una mappa del percorso?","A seguire la strada",["A mangiare un puzzle","A misurare il tempo","A fare rumore"],"La mappa mostra dove devi andare.","Una mappa del percorso aiuta nella navigazione.","I simboli possono segnare i punti importanti."],
        ["Che cos’è un punto di passaggio?","Un punto stabilito lungo un percorso",["Una password segreta","Un tipo di animale","Una moneta"],"Puoi dirigerti verso di lui.","I punti di passaggio segnano luoghi lungo un percorso.","I navigatori GPS li usano spesso."],
        ["Quale attrezzo ti aiuta a vedere meglio i piccoli indizi?","Una lente d’ingrandimento",["Un martello","Un cucchiaio","Un ombrello"],"Rende più grandi i dettagli.","Una lente d’ingrandimento ingrandisce i piccoli dettagli.","Una lente curva devia i raggi di luce."],
        ["Un’impronta è soprattutto una…","Traccia",["Pianeta","Strumento","Colore"],"Un detective le cerca.","Un’impronta può essere una traccia.","Le tracce possono dire chi è passato da un posto."],
        ["Perché guardi bene intorno durante una caccia al tesoro?","Gli indizi possono essere nascosti",["Per fermare il tempo","Per fare la pioggia","Per crescere più in fretta"],"Non è tutto in mezzo al sentiero.","Osservare bene è importante in una ricerca.","Le belle cacce uniscono guardare, pensare e muoversi."],
        ["Che cosa vuol dire «gira a sinistra» in un percorso?","Girare verso il lato sinistro",["Andare dritto","Tornare a casa","Salire"],"Pensa alla tua mano sinistra.","Girare a sinistra vuol dire andare verso sinistra.","Le parole di direzione sono importanti nella navigazione."],
        ["Che cos’è una coordinata?","Un modo per indicare un luogo preciso",["Un tipo di chiave","Una traccia di animale","Un premio"],"Mappe e GPS le usano.","Le coordinate descrivono una posizione.","La latitudine e la longitudine sono esempi."],
        ["Che cosa fai quando due indizi si contraddicono?","Li controlli di nuovo",["Ne scegli uno a caso","Butti via tutto","Strappi la mappa"],"Forse hai letto male qualcosa.","Controllare aiuta a trovare gli errori.","Chi cerca bene verifica le proprie informazioni."],
        ["Perché è utile cercare in gruppo?","Si possono unire idee e osservazioni",["Perché uno può non fare niente","Per nascondere indizi","Per fermare il tempo"],"Due paia di occhi vedono di più.","Lavorare insieme può risolvere i problemi più in fretta.","Le squadre spesso si dividono i compiti."],
        ["A che cosa serve l’ultimo indizio?","A portarti all’ultimo posto",["A rimandarti alla domanda 1","A creare un nuovo mondo","A cancellare il percorso"],"Ti porta alla soluzione.","L’ultimo indizio porta di solito al traguardo o al tesoro.","Una bella caccia costruisce passo dopo passo verso la fine."]
      ]
    },
    dieren: {
      snelle_dieren: [
        ["Quale animale terrestre è il più veloce?","Il ghepardo",["L’elefante","Il panda","L’ippopotamo"],"È un felino snello e maculato.","Il ghepardo è l’animale terrestre più veloce.","In uno scatto breve può superare i 90 km/h."],
        ["Quale uccello nuota più veloce?", "Il pinguino", ["Il cigno", "L’anatra", "Il gabbiano"], "Non sa volare, ma nuota benissimo.", "Un pinguino papua supera i trenta chilometri orari sott’acqua.", "Le sue penne si sovrappongono come tegole, così l’acqua non passa."],
        ["Quale uccello è famoso per le picchiate velocissime?","Il falco pellegrino",["Il pinguino","La gallina","Lo struzzo"],"Caccia dall’alto.","Il falco pellegrino è uno degli animali più veloci.","In picchiata può superare i 300 km/h."],
        ["Perché un pesce veloce ha il corpo affusolato?","Per avere meno resistenza",["Per pesare di più","Per cantare più forte","Per prendere più aria"],"Una forma liscia taglia meglio l’acqua.","La forma affusolata riduce la resistenza dell’acqua.","Anche i delfini hanno una forma affusolata."],
        ["Chi corre più veloce: un cavallo o una tartaruga?","Il cavallo",["La tartaruga","Uguale","Nessuno dei due"],"Ha zampe lunghe e forti.","Un cavallo è molto più veloce di una tartaruga.","Al galoppo i cavalli raggiungono alte velocità."],
        ["Perché le gazzelle hanno le zampe lunghe?","Per correre e saltare veloci",["Per nuotare","Per scavare","Per volare"],"Vivono in pianure aperte.","Le zampe lunghe aiutano le gazzelle a fuggire in fretta.","La velocità le aiuta a sfuggire ai predatori."],
        ["Quale squalo è noto come nuotatore veloce?","Lo squalo mako",["Lo squalo balena","Il cavalluccio marino","Il pesce leone"],"Ha il corpo affusolato.","Gli squali mako sono tra gli squali più veloci.","Cacciano pesci veloci."],
        ["Che cosa aiuta uno struzzo a correre veloce?","Zampe lunghe e forti",["Ali per volare","Una vescica natatoria","Artigli per arrampicarsi"],"Non sa volare.","Gli struzzi sono corridori velocissimi.","Corrono a decine di chilometri all’ora."],
        ["Perché la velocità è utile alle prede?","Per scappare",["Per far crescere gli alberi","Per fare freddo","Per dormire"],"I predatori cercano di prenderle.","La velocità può migliorare le loro possibilità di sopravvivere.","Alcune prede fanno anche curve strettissime."],
        ["Perché la velocità è utile ai predatori?","Per catturare le prede",["Per innaffiare le piante","Per colorare le piume","Per costruire nidi"],"Una caccia è spesso brevissima.","La velocità aiuta durante l’inseguimento.","Non tutti i predatori usano la velocità; alcuni stanno in agguato."]
      ],
      baby_dieren: [
        ["Come si chiama un cane appena nato?","Cucciolo",["Vitello","Puledro","Pulcino"],"La parola comincia con cu.","Un cane giovane si chiama cucciolo.","I cuccioli nascono ciechi e sordi."],
        ["Come si chiama un gatto appena nato?","Gattino",["Puledro","Agnello","Vitello"],"È un gatto giovane.","Un gatto giovane si chiama gattino.","I gattini dormono moltissimo."],
        ["Come si chiama un cavallo giovane?","Puledro",["Cucciolo","Pulcino","Leoncino"],"Si alza in piedi in fretta.","Un cavallo giovane si chiama puledro.","I puledri provano ad alzarsi subito dopo la nascita."],
        ["Come si chiama una pecora giovane?","Agnello",["Vitello","Cucciolo","Gattino"],"Se ne vedono tanti in primavera.","Una pecora giovane si chiama agnello.","Gli agnelli bevono il latte della mamma."],
        ["Come si chiama una mucca appena nata?","Vitello",["Puledro","Agnello","Pulcino"],"Anche un elefante giovane si chiama così.","Una mucca giovane si chiama vitello.","All’inizio i vitelli bevono latte."],
        ["Come si chiama una gallina appena nata?","Pulcino",["Leoncino","Cucciolo","Agnello"],"Esce da un uovo.","Una gallina appena nata si chiama pulcino.","I pulcini pigolano già prima di uscire dall’uovo."],
        ["Come si chiama un leone giovane?","Leoncino",["Puledro","Vitello","Gattino"],"Anche i lupi giovani hanno il loro nome.","Un leone giovane è un leoncino.","I leoncini restano a lungo con il gruppo."],
        ["Che cosa bevono per primo tanti cuccioli di mammifero?","Il latte",["Acqua salata","Benzina","Limonata"],"Lo fa la loro mamma.","I mammiferi nutrono i piccoli con il latte.","È una caratteristica importante dei mammiferi."],
        ["Perché tanti cuccioli restano vicino alla mamma?","Per protezione e cibo",["Per volare più veloci","Per arrampicarsi sugli alberi","Per fare freddo"],"Hanno ancora molto da imparare.","I genitori spesso proteggono e nutrono i piccoli.","Quanto dura questa cura cambia molto da specie a specie."],
        ["Quale cucciolo esce da un uovo?","Il pulcino",["Il cucciolo di cane","Il vitello","Il puledro"],"Pensa a una gallina.","Un pulcino esce da un uovo.","Anche rettili, pesci e tanti altri animali fanno le uova."]
      ],
      waterdieren: [
        ["Quale mammifero vive nel mare e respira aria?","Il delfino",["Il tonno","Lo squalo","La medusa"],"Deve salire spesso.","I delfini sono mammiferi e respirano con i polmoni.","Usano uno sfiatatoio in cima alla testa."],
        ["Quale animale ha otto braccia?","Il polpo",["Lo squalo","Il delfino","Il granchio"],"Si nasconde benissimo.","Un polpo ha otto braccia.","I polpi sono molluschi molto intelligenti."],
        ["Quale animale marino è l’animale più grande della Terra?","La balenottera azzurra",["Lo squalo bianco","Il delfino","L’orca"],"È una balena enorme.","La balenottera azzurra è l’animale più grande che si conosca.","Può superare i 25 metri di lunghezza."],
        ["Come respirano la maggior parte dei pesci?","Con le branchie",["Con i polmoni","Con la pelle","Con le piume"],"Prendono l’ossigeno dall’acqua.","Le branchie prendono l’ossigeno dall’acqua.","L’acqua scorre lungo le lamelle branchiali."],
        ["Che cosa aiuta i pesci a dirigersi e a nuotare?","Le pinne",["Le ali","Le zampe","I peli"],"Stanno sul dorso, sulla pancia e sulla coda.","Le pinne aiutano nel movimento e nell’equilibrio.","La pinna caudale dà spesso molta spinta."],
        ["Quale animale può vivere nel mare e sulla terra?","La tartaruga marina",["Il tonno","La medusa","Il cavalluccio marino"],"Va a terra per deporre le uova.","Le tartarughe marine vivono nel mare ma depongono le uova a terra.","Le femmine tornano spesso alla spiaggia dove sono nate."],
        ["Che cos’è in realtà il corallo?","Una colonia di piccoli animali",["Una pianta","Una pietra","Un pesce"],"Forma le barriere.","I coralli sono fatti di moltissimi piccoli polipi.","Le barriere coralline sono habitat importanti."],
        ["Perché le balene salgono in superficie?","Per respirare",["Per lavarsi le branchie","Per dormire sulla spiaggia","Per cucinare"],"Sono mammiferi.","Le balene respirano aria con i polmoni.","Respirano dai loro sfiatatoi."],
        ["Quale animale ha un guscio duro e cammina di lato?","Il granchio",["Il delfino","La medusa","Il calamaro"],"Se ne vedono tanti sulle spiagge.","I granchi hanno uno scheletro esterno duro.","Molti granchi si muovono facilmente di lato."],
        ["Perché un corpo affusolato è utile nell’acqua?","Riduce la resistenza",["Fa più rumore","Rende l’animale più pesante","Scalda l’acqua"],"Gli animali scivolano meglio nell’acqua.","La forma affusolata aiuta a nuotare con meno fatica.","Delfini e squali ne sono begli esempi."]
      ],
      jungle: [
        ["Quale animale si dondola spesso tra gli alberi?","La scimmia",["L’elefante","Il pinguino","La zebra"],"Si arrampica sui rami.","Molte specie di scimmie vivono sugli alberi.","Alcune scimmie usano la coda come presa in più."],
        ["Quale animale ha un grande becco colorato?","Il tucano",["La tigre","Il gorilla","Il coccodrillo"],"È un uccello tropicale.","I tucani hanno becchi spettacolari.","Il loro becco è sorprendentemente leggero."],
        ["Quale grande animale vive nelle foreste tropicali e mangia tante piante?","Il gorilla",["Il pinguino","Il cammello","L’orso polare"],"È una scimmia antropomorfa.","I gorilla vivono nelle foreste africane.","Mangiano soprattutto piante."],
        ["Perché tanti animali della giungla hanno una mimetizzazione?","Per farsi notare meno",["Per cantare più forte","Per fare più pioggia","Per crescere più in fretta"],"I disegni somigliano a foglie e ombre.","La mimetizzazione aiuta gli animali a cacciare o a nascondersi.","Le macchie di molti giaguari imitano le ombre."],
        ["Quale grande felino vive nelle giungle delle Americhe?","Il giaguaro",["Il leone","Il leopardo delle nevi","La lince"],"Ha rosette sul mantello.","I giaguari vivono in parti dell’America centrale e del Sud.","Nuotano sorprendentemente bene."],
        ["Perché gli alberi della foresta pluviale sono così importanti?","Danno cibo e spazio per vivere",["Non fanno ossigeno","Fermano tutta la pioggia","Sono solo decorativi"],"Tanti animali vivono in strati diversi di alberi.","Gli alberi della foresta pluviale formano habitat complessi.","Alcuni animali non scendono quasi mai a terra."],
        ["Quale rettile può cambiare colore?","Il camaleonte",["La tartaruga","Il coccodrillo","Il serpente"],"Usa il colore anche per comunicare.","I camaleonti possono cambiare il loro disegno di colore.","Il cambio di colore aiuta con la temperatura e con i segnali."],
        ["Che cos’è una foresta pluviale?","Una foresta calda con moltissima pioggia",["Un deserto ghiacciato","Una prateria senza alberi","Un mare"],"È ricchissima di specie.","Le foreste pluviali tropicali ricevono moltissima pioggia.","Sono tra gli ambienti più ricchi di specie del pianeta."],
        ["Perché le scimmie urlatrici gridano così forte?","Per comunicare con il loro gruppo",["Per fare la pioggia","Per spingere gli alberi","Per nuotare"],"Il loro grido arriva lontano nella foresta.","Le scimmie urlatrici comunicano con grida fortissime.","Una struttura della gola ingrandita amplifica il grido."],
        ["Quale animale cattura insetti con una lingua lunga?","Il camaleonte",["L’elefante","Il gorilla","Il tucano"],"La lingua scatta fuori velocissima.","I camaleonti catturano le prede con la loro lingua lunga.","La lingua può accelerare moltissimo."]
      ]
    },
    aarde: {
      continenten_landen: [
        ["In quale continente si trovano i Paesi Bassi?","In Europa",["In Africa","In Asia","In Sud America"],"Pensa ai paesi vicini.","I Paesi Bassi si trovano in Europa.","L’Europa è uno dei sette continenti."],
        ["Qual è il continente più grande?","L’Asia",["L’Europa","L’Africa","L’Australia"],"Lì ci sono la Cina e l’India.","L’Asia è il continente più grande.","In Asia vive più della metà delle persone del mondo."],
        ["In quale continente si trova il Brasile?","In Sud America",["In Africa","In Europa","In Asia"],"Pensa al Rio delle Amazzoni.","Il Brasile si trova in Sud America.","Il Brasile è il paese più grande del Sud America."],
        ["In quale continente si trova gran parte dell’Egitto?","In Africa",["In Europa","In Asia","In Nord America"],"Il Nilo lo attraversa.","L’Egitto si trova in gran parte in Africa.","La penisola del Sinai appartiene geograficamente all’Asia."],
        ["Qual è la capitale della Francia?","Parigi",["Roma","Madrid","Berlino"],"Lì c’è la torre Eiffel.","Parigi è la capitale della Francia.","La Senna attraversa Parigi."],
        ["Qual è la capitale dell’Italia?","Roma",["Milano","Venezia","Napoli"],"Lì c’è il Colosseo.","Roma è la capitale dell’Italia.","La Città del Vaticano si trova dentro Roma."],
        ["Quale paese ha la forma di uno stivale?","L’Italia",["Il Portogallo","La Norvegia","La Polonia"],"Guarda il sud dell’Europa.","L’Italia sembra uno stivale.","La Sicilia sta vicino alla punta."],
        ["Quale oceano si trova tra l’Europa e l’America?","L’oceano Atlantico",["L’oceano Pacifico","L’oceano Indiano","L’oceano Artico"],"Le navi lo attraversano.","L’oceano Atlantico si trova tra Europa, Africa e America.","È il secondo oceano più grande."],
        ["Quale continente si trova al Polo Sud?","L’Antartide",["L’Europa","L’Africa","L’Asia"],"È coperto di ghiaccio.","L’Antartide circonda il Polo Sud.","È il continente più freddo."],
        ["Quale paese si trova direttamente a est dei Paesi Bassi?","La Germania",["La Spagna","L’Irlanda","L’Italia"],"È un paese vicino.","La Germania confina con i Paesi Bassi.","I Paesi Bassi confinano anche con il Belgio."]
      ],
      weer_klimaat: [
        ["Che cosa misura un termometro?","La temperatura",["La direzione del vento","La quantità di pioggia","La pressione dell’aria"],"Caldo o freddo.","Un termometro misura la temperatura.","Usiamo spesso i gradi Celsius."],
        ["Che cosa sono le precipitazioni?","Acqua che cade dal cielo",["Il vento","La luce del Sole","La nebbia"],"La pioggia e la neve sono esempi.","Le precipitazioni possono essere pioggia, neve o grandine.","Nascono dall’acqua contenuta nelle nuvole."],
        ["Che cos’è il vento?","Aria in movimento",["Acqua in movimento","Sabbia calda","Una nuvola"],"Lo senti ma non lo vedi.","Il vento è aria che si muove.","Le differenze di pressione creano gran parte del vento."],
        ["Perché si forma spesso la nebbia?","Il vapore acqueo si condensa vicino al suolo",["Per le stelle","Per la sabbia","Per le calamite"],"Si vede peggio.","La nebbia è fatta di goccioline piccolissime d’acqua nell’aria.","La nebbia è in realtà una nuvola a livello del suolo."],
        ["Che cos’è il clima?","Il tempo medio su tanti anni",["Il tempo di oggi","Un temporale","Un pluviometro"],"Si parla di anni, non di un giorno.","Il clima descrive il tempo tipico su un periodo lungo.","Il tempo può cambiare molto da un giorno all’altro."],
        ["Che cosa provoca un fulmine?","Una scarica elettrica",["Una stella cadente","Un aereo","Un arcobaleno"],"Succede spesso con le nuvole temporalesche.","Un fulmine è un’enorme scarica elettrica.","L’aria intorno diventa caldissima."],
        ["Perché senti il tuono dopo il fulmine?","La luce è più veloce del suono",["Il tuono comincia dopo","Le nuvole aspettano","Il Sole ferma il suono"],"Prima vedi il lampo.","La luce ti raggiunge molto prima del suono.","La differenza di tempo aiuta a capire quanto è lontano il temporale."],
        ["Quale nuvola accompagna spesso i forti acquazzoni e i temporali?","Il cumulonembo",["Il cirro","La nebbia","Nessuna nuvola"],"Può diventare altissima.","I cumulonembi possono portare i temporali.","In cima hanno spesso la forma di un’incudine."],
        ["Che cos’è un’ondata di calore?","Un periodo di caldo insolito",["Una nevicata improvvisa","Un terremoto","Un’onda alta in mare"],"Dura più giorni.","Un’ondata di calore è un lungo periodo di tempo molto caldo.","Le definizioni cambiano da paese a paese."],
        ["Che cos’è il gelo?","Una temperatura sotto lo zero",["Un vento forte","Una pioggia fortissima","Una nebbia fitta"],"Allora l’acqua può ghiacciare.","Con il gelo la temperatura scende intorno o sotto 0 °C.","La brina si forma quando il vapore acqueo ghiaccia."]
      ],
      oceanen_natuur: [
        ["Che cosa copre la maggior parte della Terra?","L’acqua",["Il deserto","La foresta","Il ghiaccio"],"Gli oceani occupano uno spazio enorme.","Circa il 71% della Terra è coperto d’acqua.","La maggior parte è acqua di mare salata."],
        ["Quale oceano è il più grande?","L’oceano Pacifico",["L’oceano Atlantico","L’oceano Indiano","L’oceano Artico"],"Si trova tra l’Asia e l’America.","Il Pacifico è l’oceano più grande.","Copre circa un terzo della superficie della Terra."],
        ["Come si chiama la roccia fusa che esce da un vulcano?","Lava",["Magma","Argilla","Sabbia"],"Fuori dalla Terra la chiamiamo così.","In superficie la roccia fusa si chiama lava.","Nel sottosuolo la chiamiamo magma."],
        ["Che cos’è un’isola?","Una terra circondata tutt’intorno dall’acqua",["Una nuvola alta","Un fiume","Un deserto"],"Devi attraversare l’acqua per arrivarci.","Un’isola è circondata d’acqua da tutti i lati.","La Groenlandia è l’isola più grande che non sia un continente."],
        ["Che cos’è una catena montuosa?","Una serie di montagne",["Un fiume largo","Un mare","Un gruppo di isole"],"Le Alpi sono una di queste.","Una catena montuosa è fatta di montagne collegate.","Nell’Himalaya ci sono le montagne più alte della Terra."],
        ["Che cos’è la foce di un fiume?","Il punto dove il fiume finisce",["La sorgente del fiume","La cima di una montagna","Un deserto"],"Il fiume sfocia spesso in un mare o in un lago.","La foce è la fine di un fiume.","Alcuni fiumi formano un delta alla foce."],
        ["Che cos’è un deserto?","Una zona con pochissime precipitazioni",["Sempre una spiaggia calda","Una foresta pluviale","Un oceano"],"Non tutti i deserti sono caldi.","I deserti ricevono pochissime precipitazioni.","Tecnicamente anche l’Antartide è un deserto."],
        ["Che cos’è un ghiacciaio?","Una massa di ghiaccio che si muove lentamente",["Una nuvola","Un fiume di lava","Una duna di sabbia"],"Si forma dalla neve compressa.","I ghiacciai si muovono lentamente per il loro stesso peso.","Modellano valli e paesaggi."],
        ["Che cos’è l’erosione?","Il consumo e il trasporto di roccia e terreno",["Alberi che crescono","Stelle che nascono","Aria che ghiaccia"],"Acqua e vento possono causarla.","L’erosione cambia i paesaggi.","I fiumi possono scavare valli profonde."],
        ["Che cos’è un delta?","Una zona in cui un fiume si divide alla foce",["Una cima di montagna","Una corrente marina","Una nuvola"],"Lì può esserci terra fertile.","Un delta si forma con i sedimenti depositati.","Il delta del Nilo è un esempio famoso."]
      ],
      kaarten_navigatie: [
        ["Che cosa mostra una rosa dei venti?","Le direzioni",["La temperatura","L’altezza","I fusi orari"],"Nord, est, sud e ovest.","Una rosa dei venti mostra le direzioni.","Le mappe usano spesso N, E, S e O."],
        ["A che cosa serve la legenda di una mappa?","A spiegare i simboli",["A decorare la mappa","A misurare le distanze","A fare vento"],"Colori e segni prendono un significato.","La legenda spiega i simboli della mappa.","Una linea blu può essere un fiume, per esempio."],
        ["Che cos’è la scala di una mappa?","Il rapporto tra la distanza sulla mappa e quella vera",["Uno strumento musicale","Un misuratore di temperatura","Un codice di colori"],"1 cm può voler dire 1 km, per esempio.","La scala rende comprensibili le distanze della mappa.","Una scala grande mostra di solito più dettagli."],
        ["Che cosa sono le coordinate?","Numeri o valori che indicano un luogo",["Un tipo di nuvola","Una moneta","Un fiume"],"Il GPS le usa.","Le coordinate descrivono una posizione.","La latitudine e la longitudine sono coordinate note."],
        ["Quale direzione è opposta al nord?","Il sud",["L’est","L’ovest","Il nordest"],"Pensa alla rosa dei venti.","Il sud è opposto al nord.","Est e ovest formano un angolo retto con nord e sud."],
        ["Quale direzione hai alla tua destra se guardi a nord?","L’est",["L’ovest","Il sud","Il nord"],"Su tante mappe il nord è in alto.","Con il nord in alto, l’est è a destra.","Per questo l’ovest è a sinistra su quella mappa."],
        ["Che cos’è una mappa topografica?","Una mappa con informazioni sul terreno e sulle altezze",["Una mappa delle stelle","Un menu","Una linea del tempo"],"Può avere le curve di livello.","Le mappe topografiche mostrano il paesaggio e l’altezza.","Gli escursionisti le usano spesso."],
        ["Che cos’è il GPS?","Un sistema di satelliti per trovare la posizione",["Un tipo di nuvola","Un vulcano","Una bussola senza satelliti"],"Il tuo telefono può usarlo.","Il GPS usa i segnali dei satelliti per capire dove sei.","Servono più satelliti per una posizione precisa."],
        ["Perché sulle mappe il nord è spesso in alto?","È un’abitudine molto diffusa",["Perché il nord è più in alto","Perché il Sole sta sempre lì","Perché i fiumi vanno lì"],"È una convenzione, non una legge di natura.","Molte mappe moderne mettono il nord in alto.","Le mappe antiche a volte erano orientate diversamente."],
        ["Che cos’è un itinerario?","Un percorso pianificato dalla partenza all’arrivo",["Una nuvola di pioggia","Una montagna","Un confine"],"La navigazione ti aiuta a seguirlo.","Un itinerario descrive come andare da A a B.","Le mappe digitali calcolano gli itinerari da sole."]
      ]
    }
  };

  window.KWIZILLO_QUESTIONS_IT = window.KWIZILLO_BUILD_BANK(defs, window.KWIZILLO_EXTRA_IT||{}, window.KWIZILLO_MORE_IT||{});
})();
