(() => {
  // Advanced set (Dutch): ten harder questions per topic, ids 11-20, for
  // levels 3-6. Same row shape as questions.js:
  // [prompt, answer, [wrong, wrong, wrong], hint, explanation, fact]
  // Merged into the bank by KWIZILLO_BUILD_BANK in questions.js.
  window.KWIZILLO_EXTRA_NL = {
    ruimte: {
      zonnestelsel: [
        ['Welke planeet heeft de meeste bekende manen?','Saturnus',['Mars','Aarde','Venus'],'Deze gasreus heeft er meer dan honderd.','Saturnus heeft de meeste bekende manen, meer dan 140.','Zijn grootste maan, Titan, is groter dan de planeet Mercurius.'],
        ['Welke planeet draait als enige "op zijn zij"?','Uranus',['Jupiter','Mars','Neptunus'],'Zijn as ligt bijna plat.','Uranus draait met een as die bijna 98 graden gekanteld is.','Daardoor duurt een winter op de polen van Uranus ruim 20 jaar.'],
        ['Hoe heet de gordel van rotsblokken tussen Mars en Jupiter?','De asteroïdengordel',['De Kuipergordel','De Melkweg','De maanring'],'Er zweven miljoenen rotsen.','Tussen Mars en Jupiter ligt de asteroïdengordel.','Het grootste object erin, Ceres, is een dwergplaneet.'],
        ['Welke planeet is het heetst?','Venus',['Mercurius','Mars','Jupiter'],'Niet de planeet die het dichtst bij de zon staat.','Venus is heter dan Mercurius door zijn dikke atmosfeer die warmte vasthoudt.','Op Venus is het ongeveer 465 graden, heet genoeg om lood te smelten.'],
        ['Hoe heet de grote rode storm op Jupiter?','De Grote Rode Vlek',['Het Rode Oog','De Vuurring','De Stormkrater'],'Hij is groter dan de aarde.','De Grote Rode Vlek is een enorme storm die al eeuwen woedt.','De storm is groter dan onze hele planeet.'],
        ['Hoe lang doet het licht van de zon erover om de aarde te bereiken?','Ongeveer 8 minuten',['1 seconde','1 uur','1 dag'],'Langer dan een seconde, korter dan een uur.','Zonlicht reist ongeveer 150 miljoen kilometer in ruim 8 minuten.','Als de zon nu uitging, zouden we dat pas na 8 minuten merken.'],
        ['Hoe noem je een steen uit de ruimte die de grond raakt?','Een meteoriet',['Een komeet','Een planetoïde','Een satelliet'],'Een vallende ster die niet helemaal verbrandt.','Een meteoriet is een ruimtesteen die de aarde bereikt.','De meeste ruimtestenen verbranden als lichtstreep in de lucht.'],
        ['Hoe lang duurt een jaar op Mars?','Ongeveer 687 dagen',['365 dagen','88 dagen','30 dagen'],'Mars staat verder van de zon dan de aarde.','Mars doet er bijna twee aardse jaren over om rond de zon te gaan.','Een dag op Mars duurt maar iets langer dan een aardse dag.'],
        ['Welke planeet is zo licht dat hij op water zou drijven?','Saturnus',['Jupiter','Aarde','Mercurius'],'De planeet met de ringen.','Saturnus is minder dicht dan water, dus in theorie zou hij drijven.','Je zou wel een badkuip nodig hebben die groter is dan de aarde.'],
        ['Waar ligt Pluto?','In de Kuipergordel',['Tussen Mars en Jupiter','Naast Venus','In de Melkweg-kern'],'Voorbij Neptunus.','Pluto is een dwergplaneet in de Kuipergordel, ver voorbij Neptunus.','Een jaar op Pluto duurt 248 aardse jaren.']
      ],
      sterren_planeten: [
        ['Hoe heet het sterrenstelsel dat het dichtst bij de Melkweg staat?','Andromeda',['Orion','Sirius','Cassiopeia'],'Het is met het blote oog te zien als vaag vlekje.','Andromeda is het dichtstbijzijnde grote sterrenstelsel.','Over ongeveer 4 miljard jaar botsen Andromeda en de Melkweg.'],
        ['Welke kleur heeft de heetste ster?','Blauw',['Rood','Geel','Oranje'],'Het tegenovergestelde van wat een kraan je leert.','Blauwe sterren zijn het heetst, rode sterren het koelst.','Onze zon is een gele ster met een gemiddelde temperatuur.'],
        ['Wat is een lichtjaar?','Een afstand',['Een tijd','Een gewicht','Een temperatuur'],'Het gaat over hoe ver, niet hoe lang.','Een lichtjaar is de afstand die licht in één jaar aflegt.','Dat is ongeveer 9,5 biljoen kilometer.'],
        ['Hoe heet de helderste ster aan de nachthemel?','Sirius',['Poolster','Betelgeuze','Vega'],'Hij hoort bij het sterrenbeeld Grote Hond.','Sirius is de helderste ster die we \'s nachts zien.','Sirius staat "maar" 8,6 lichtjaar van ons vandaan.'],
        ['Wat ontstaat als een zware ster aan het eind van zijn leven ontploft?','Een supernova',['Een komeet','Een planeet','Een regenboog'],'Een enorme explosie.','Een supernova is de explosie van een zware ster.','Zo\'n explosie kan even feller schijnen dan een heel sterrenstelsel.'],
        ['Wat is een zwart gat?','Een plek waar zelfs licht niet uit kan',['Een gat in de maan','Een donkere wolk','Een uitgedoofde planeet'],'Niets komt eruit, zelfs licht niet.','Een zwart gat heeft zo\'n sterke zwaartekracht dat licht er niet uit kan.','In het midden van de Melkweg zit een superzwaar zwart gat.'],
        ['Naar welke ster wijst het Noorden?','De Poolster',['Sirius','De zon','Betelgeuze'],'Zeelieden gebruikten hem om te navigeren.','De Poolster staat bijna precies boven de noordpool.','De Poolster lijkt stil te staan terwijl de andere sterren eromheen draaien.'],
        ['Hoe heet een planeet die om een andere ster draait?','Een exoplaneet',['Een dwergplaneet','Een maan','Een asteroïde'],'"Exo" betekent buiten.','Een exoplaneet draait om een andere ster dan de zon.','Er zijn al meer dan vijfduizend exoplaneten ontdekt.'],
        ['Wat is een rode reus?','Een oude, opgezwollen ster',['Een jonge ster','Een grote planeet','Een rode komeet'],'Onze zon wordt er ooit een.','Een rode reus is een ster die aan het eind van zijn leven enorm opzwelt.','Als de zon een rode reus wordt, slokt hij misschien de aarde op.'],
        ['Uit welk gas bestaat de zon vooral?','Waterstof',['Zuurstof','Stikstof','Koolstofdioxide'],'Het lichtste element.','De zon bestaat vooral uit waterstof, dat ze omzet in helium.','Elke seconde zet de zon 600 miljoen ton waterstof om.']
      ],
      astronauten: [
        ['Wie was de eerste mens in de ruimte?','Joeri Gagarin',['Neil Armstrong','Buzz Aldrin','André Kuipers'],'Een Rus, in 1961.','Joeri Gagarin vloog in 1961 als eerste mens rond de aarde.','Zijn vlucht duurde maar 108 minuten.'],
        ['Wie was de eerste vrouw in de ruimte?','Valentina Teresjkova',['Sally Ride','Mae Jemison','Samantha Cristoforetti'],'Een Russin, in 1963.','Valentina Teresjkova vloog in 1963 als eerste vrouw de ruimte in.','Ze draaide 48 keer om de aarde.'],
        ['Hoe lang doen astronauten er ongeveer over om het ISS te bereiken?','Ongeveer 6 uur',['6 minuten','6 dagen','6 weken'],'Korter dan een dag.','Een snelle vlucht naar het ISS duurt een paar uur.','Het ISS vliegt met 28.000 kilometer per uur.'],
        ['Waarom drijven astronauten in het ISS?','Ze vallen voortdurend om de aarde heen',['Er is geen zwaartekracht','De lucht duwt ze omhoog','Ze dragen magneten'],'De zwaartekracht is er wel degelijk.','Het ISS valt steeds om de aarde heen, en alles erin valt mee: dat voelt als zweven.','De zwaartekracht op de hoogte van het ISS is nog 90% van die op de grond.'],
        ['Hoe slapen astronauten in het ISS?','In een slaapzak die vastzit aan de wand',['In een gewoon bed','Op de vloer','In een hangmat'],'Anders zweven ze weg.','Astronauten ritsen zich in een slaapzak die aan de wand hangt.','Ze zien in 24 uur zestien keer de zon opkomen.'],
        ['Welke Nederlander verbleef als eerste lange tijd in het ISS?','André Kuipers',['Wubbo Ockels','Lodewijk van den Berg','Bas Lansdorp'],'Hij was er in 2012 een half jaar.','André Kuipers woonde in 2011-2012 zes maanden in het ISS.','Hij was de tweede Nederlandse astronaut; Wubbo Ockels was de eerste.'],
        ['Wat gebeurt er met de spieren van een astronaut na maanden zweven?','Ze worden zwakker',['Ze worden sterker','Ze veranderen niet','Ze worden langer'],'Ze hoeven niets te dragen.','Zonder zwaartekracht hoeven spieren en botten niet te werken en worden ze zwakker.','Daarom sporten astronauten elke dag ongeveer twee uur.'],
        ['Hoeveel mensen hebben op de maan gelopen?','12',['2','6','24'],'Zes landingen met telkens twee mensen.','Tussen 1969 en 1972 liepen twaalf astronauten op de maan.','Alle twaalf waren Amerikanen van het Apollo-programma.'],
        ['Hoe heet het ruimteprogramma waarmee mensen terugkeren naar de maan?','Artemis',['Apollo','Sojoez','Voyager'],'Vernoemd naar de tweelingzus van Apollo.','Artemis is het programma dat mensen weer naar de maan brengt.','Bij Artemis moet de eerste vrouw op de maan landen.'],
        ['Waarom is de ruimtehelm van binnen spiegelend goud?','Om fel zonlicht tegen te houden',['Voor de mooie kleur','Om warm te blijven','Om beter te kunnen praten'],'Zonder atmosfeer is de zon verblindend.','Het gouden vizier werkt als een zonnebril tegen het scherpe zonlicht.','Goud houdt ook onzichtbare infraroodstraling tegen.']
      ],
      raket_avontuur: [
        ['Hoe snel moet een raket gaan om in een baan om de aarde te komen?','Ongeveer 28.000 km per uur',['100 km per uur','1.000 km per uur','1 miljoen km per uur'],'Bijna acht kilometer per seconde.','Om in een baan te blijven moet je zo\'n 28.000 kilometer per uur gaan.','Dat is 25 keer sneller dan een straaljager.'],
        ['Wat is een herbruikbare raket?','Een raket die na de lancering weer landt',['Een raket van papier','Een raket zonder motor','Een raket die je opvouwt'],'Hij komt terug om nog een keer te vliegen.','Herbruikbare raketten landen weer op de grond of op een schip en vliegen opnieuw.','Zo wordt ruimtevaart een stuk goedkoper.'],
        ['Waarom worden raketten in trappen gebouwd?','Om lege tanks onderweg af te werpen',['Om mooier te zijn','Om langzamer te gaan','Om geluid te dempen'],'Lichter worden helpt bij het versnellen.','Een raket laat lege trappen los zodat hij lichter wordt.','De Saturnus V had drie trappen.'],
        ['Welke raket bracht de eerste mensen naar de maan?','Saturnus V',['Falcon 9','Ariane 5','Sojoez'],'De grootste raket van zijn tijd.','De Saturnus V bracht de Apollo-astronauten naar de maan.','Hij was 111 meter hoog, hoger dan de Dom van Utrecht.'],
        ['Hoe heet de plek in Frans-Guyana waar Europese raketten opstijgen?','Kourou',['Cape Canaveral','Baikonoer','Noordwijk'],'Het ligt vlak bij de evenaar in Zuid-Amerika.','Vanuit Kourou lanceert Europa zijn Ariane-raketten.','Bij de evenaar helpt de draaiing van de aarde de raket een extra zetje geven.'],
        ['Wat is een sonde?','Een onbemand ruimtevaartuig',['Een soort raketbrandstof','Een ruimtepak','Een lanceertoren'],'Er zit niemand in.','Een sonde is een ruimtevaartuig zonder mensen dat onderzoek doet.','Voyager 1 is de verste sonde: hij verliet ons zonnestelsel.'],
        ['Welke sonde landde in 2021 met een helikopter op Mars?','Perseverance',['Curiosity','Hubble','Cassini'],'De helikopter heette Ingenuity.','Perseverance bracht de kleine helikopter Ingenuity mee naar Mars.','Ingenuity maakte de allereerste vlucht op een andere planeet.'],
        ['Hoe heet de kracht die een raket omhoog duwt?','Stuwkracht',['Zwaartekracht','Wrijving','Magnetisme'],'De motor duwt gas naar beneden.','De motor stoot gas naar achteren en duwt de raket zo vooruit: stuwkracht.','Dat is de derde wet van Newton: actie is reactie.'],
        ['Waarom heeft een ruimtecapsule een hitteschild nodig bij terugkeer?','De lucht schuurt hem gloeiend heet',['Om er mooi uit te zien','Tegen de kou','Tegen regen'],'De lucht remt met enorme snelheid.','Bij terugkeer schuurt de capsule zo hard langs de lucht dat hij duizenden graden heet wordt.','Het schild wordt heter dan lava.'],
        ['Hoe heet de ruimtetelescoop die in 2021 werd gelanceerd?','James Webb',['Hubble','Kepler','Galileo'],'Hij kijkt in infrarood licht.','De James Webb-telescoop ziet verder dan ooit het heelal in.','Zijn gouden spiegel is 6,5 meter breed.']
      ]
    },
    geschiedenis: {
      egyptenaren: [
        ['Hoe heet het schrift met tekens en plaatjes van de oude Egyptenaren?','Hiërogliefen',['Runen','Spijkerschrift','Het alfabet'],'Elk teken is een tekening.','Hiërogliefen zijn de tekens van het oude Egyptische schrift.','Er waren meer dan zevenhonderd verschillende tekens.'],
        ['Welke steen hielp om hiërogliefen te ontcijferen?','De steen van Rosetta',['De maansteen','De piramidesteen','De Nijlsteen'],'Dezelfde tekst stond er in drie schriften op.','Op de steen van Rosetta staat een tekst in hiërogliefen, Demotisch en Grieks.','Jean-François Champollion kraakte het schrift in 1822.'],
        ['Waarom mummificeerden de Egyptenaren hun doden?','Voor het leven na de dood',['Om ze warm te houden','Als straf','Om ze te verkopen'],'Het lichaam moest bewaard blijven.','De Egyptenaren geloofden dat het lichaam nodig was in het hiernamaals.','Het mummificeren duurde ongeveer zeventig dagen.'],
        ['Hoe heet de beroemde jonge farao van wie het graf vol schatten werd gevonden?','Toetanchamon',['Ramses','Cleopatra','Cheops'],'Zijn gouden masker is wereldberoemd.','Het graf van Toetanchamon werd in 1922 bijna ongeschonden gevonden.','Hij werd farao toen hij ongeveer negen jaar oud was.'],
        ['Welke rivier liet elk jaar vruchtbare modder achter?','De Nijl',['De Eufraat','De Tigris','De Rijn'],'De langste rivier van Afrika.','De jaarlijkse overstroming van de Nijl maakte de akkers vruchtbaar.','Zonder de Nijl zou Egypte helemaal woestijn zijn.'],
        ['Hoe heet het beeld met een leeuwenlichaam en een mensenhoofd bij de piramiden?','De Sfinx',['Anubis','De Obelisk','De Kolos'],'Hij bewaakt de piramiden van Gizeh.','De Sfinx is een reusachtig beeld met een leeuwenlichaam en een mensenhoofd.','Hij is 73 meter lang en 20 meter hoog.'],
        ['Welke god had de kop van een jakhals?','Anubis',['Ra','Horus','Osiris'],'Hij hoorde bij het mummificeren.','Anubis, de god met de jakhalskop, waakte over de doden.','Priesters droegen een Anubis-masker tijdens de balseming.'],
        ['Waarop schreven de Egyptenaren?','Papyrus',['Papier','Perkament','Kleitabletten'],'Gemaakt van een rietplant uit de Nijl.','Papyrus werd gemaakt van de stengels van de papyrusplant.','Ons woord "papier" komt van papyrus.'],
        ['Welk dier was heilig in het oude Egypte?','De kat',['De hond','Het paard','De kip'],'Er zijn zelfs kattenmummies gevonden.','Katten werden vereerd; ze beschermden het graan tegen muizen.','Wie een kat doodde, kon zwaar gestraft worden.'],
        ['Hoe heet de laatste farao van Egypte?','Cleopatra',['Nefertiti','Hatsjepsoet','Toetanchamon'],'Een koningin die met de Romeinen te maken kreeg.','Cleopatra VII was de laatste heerser van het oude Egypte.','Na haar dood werd Egypte een provincie van Rome.']
      ],
      ridders_kastelen: [
        ['Hoe heette de jongen die een ridder in opleiding was?','Een schildknaap',['Een page','Een graaf','Een monnik'],'Hij droeg het schild van zijn ridder.','Een schildknaap hielp een ridder en leerde zelf vechten.','Rond zijn 21e kon een schildknaap tot ridder geslagen worden.'],
        ['Hoe heet het steekspel waarbij ridders met lansen op elkaar afreden?','Een toernooi',['Een slag','Een kruistocht','Een parade'],'Het was een sport én een oefening.','Bij een toernooi reden ridders met lansen op elkaar in.','Het lansgevecht heette een steekspel of joute.'],
        ['Hoe heet de gracht met water rond een kasteel?','Een slotgracht',['Een sloot','Een kanaal','Een vijver'],'Hij maakte aanvallen moeilijk.','Een slotgracht rond het kasteel hield vijanden op afstand.','Vaak kon de brug over de gracht omhoog: de ophaalbrug.'],
        ['Hoe heet de hoogste, sterkste toren van een middeleeuws kasteel?','De donjon',['De minaret','De kerktoren','De vuurtoren'],'Daar trok men zich terug bij een aanval.','De donjon was de laatste schuilplaats als de rest van het kasteel viel.','Het woord komt uit het Frans; in het Engels heet hij "keep".'],
        ['Hoe heet het hemd van duizenden metalen ringetjes dat ridders droegen?','Een maliënkolder',['Een harnas','Een tabberd','Een kuras'],'Duizenden ringetjes aan elkaar.','Een maliënkolder is een hemd van in elkaar gehaakte metalen ringen.','Zo\'n hemd kon wel tien kilo wegen.'],
        ['Welk wapen slingerde grote stenen tegen kasteelmuren?','Een katapult',['Een kanon','Een kruisboog','Een hellebaard'],'Geen buskruit, wel een hefboom.','Met een katapult of blijde werden stenen over of tegen de muren geslingerd.','Soms werden er zelfs dode dieren mee over de muur gegooid.'],
        ['Waarvoor dienden de smalle spleten in kasteelmuren?','Om pijlen door te schieten',['Om naar buiten te kijken','Voor frisse lucht','Voor de post'],'Van binnen breed, van buiten smal.','Schietgaten waren van buiten heel smal, zodat vijanden er moeilijk in konden schieten.','Ze heten ook wel schietspleten.'],
        ['Wat is een wapenschild?','Een teken waaraan je een ridder herkent',['Een schild van hout','Een soort helm','Een zwaardhouder'],'Elke familie had een eigen tekening.','Aan het wapenschild kon je zien bij welke familie een ridder hoorde.','De leer van wapenschilden heet heraldiek.'],
        ['Hoe heet de erecode waaraan een ridder zich moest houden?','De riddercode',['De schoolregels','Het wetboek','De kaart'],'Dapper, eerlijk en beschermend.','De riddercode zei dat een ridder dapper, trouw en hoffelijk moest zijn.','Het Franse woord ervoor is "chevalerie".'],
        ['Welke ziekte doodde in de middeleeuwen een derde van Europa?','De pest',['De griep','Mazelen','Koorts'],'Ook wel de Zwarte Dood genoemd.','De pest sloeg rond 1350 toe en doodde miljoenen mensen.','Ze werd verspreid door vlooien op ratten.']
      ],
      romeinen: [
        ['Hoe heet het grote stadion in Rome waar gladiatoren vochten?','Het Colosseum',['Het Pantheon','Het Forum','De Arena van Nîmes'],'Er pasten 50.000 mensen in.','In het Colosseum keken Romeinen naar gladiatorengevechten.','Het gebouw is bijna tweeduizend jaar oud en staat er nog.'],
        ['Hoe heet de lange muur die de Romeinen in Engeland bouwden?','De Muur van Hadrianus',['De Chinese Muur','De Berlijnse Muur','De Limes'],'Genoemd naar een keizer.','De Muur van Hadrianus beschermde de noordgrens van Romeins Britannië.','Hij is 117 kilometer lang.'],
        ['Hoe heette de Romeinse grens langs de Rijn in Nederland?','De Limes',['De Vaart','De Waterlinie','De Hollandse Lijn'],'Het woord betekent "grens".','De Limes liep langs de Rijn dwars door Nederland.','De Limes staat op de Werelderfgoedlijst.'],
        ['Hoe brachten de Romeinen water naar hun steden?','Met aquaducten',['Met tankwagens','Met regentonnen','Met putten'],'Een soort waterbrug.','Aquaducten voerden water over grote afstanden naar de stad.','Het Pont du Gard in Frankrijk is een beroemd aquaduct.'],
        ['Welke stad werd in het jaar 79 bedolven onder as van de Vesuvius?','Pompeï',['Rome','Athene','Carthago'],'De stad werd pas eeuwen later teruggevonden.','Pompeï verdween onder meters as toen de Vesuvius uitbarstte.','Door de as bleven huizen, brood en zelfs mensen bewaard.'],
        ['Welke Romein werd op 15 maart vermoord in de senaat?','Julius Caesar',['Nero','Augustus','Hadrianus'],'Zijn vriend Brutus deed mee.','Julius Caesar werd in 44 voor Christus door senatoren doodgestoken.','De maand juli is naar hem genoemd.'],
        ['Welke Romeinse cijfers staan voor 50?','L',['C','X','D'],'Niet X en niet C.','In Romeinse cijfers is L vijftig, C honderd en D vijfhonderd.','Het jaar 2026 schrijf je als MMXXVI.'],
        ['Welke taal spraken de Romeinen?','Latijn',['Grieks','Italiaans','Frans'],'Veel Nederlandse woorden komen ervan.','De Romeinen spraken Latijn.','Frans, Spaans en Italiaans zijn uit het Latijn ontstaan.'],
        ['Hoe heette de Romeinse legereenheid van ongeveer 5.000 soldaten?','Een legioen',['Een peloton','Een cohort','Een garde'],'Ze werden legionairs genoemd.','Een legioen was een leger van ongeveer vijfduizend goed getrainde soldaten.','Een legionair moest wel dertig kilometer per dag kunnen lopen met bepakking.'],
        ['Welke Romeinse stad in Nederland heette Ulpia Noviomagus?','Nijmegen',['Utrecht','Maastricht','Leiden'],'De oudste stad van Nederland.','Nijmegen was de Romeinse stad Ulpia Noviomagus.','Nijmegen vierde in 2005 zijn 2000-jarig bestaan.']
      ],
      ontdekkingsreizigers: [
        ['Wie voer in 1492 naar Amerika?','Christoffel Columbus',['Marco Polo','James Cook','Vasco da Gama'],'Hij dacht dat hij in Indië was.','Columbus stak in 1492 de Atlantische Oceaan over.','Hij noemde de bewoners "indianen" omdat hij dacht in Indië te zijn.'],
        ['Wiens expeditie voer als eerste rond de wereld?','Ferdinand Magellaan',['Columbus','Abel Tasman','Willem Barentsz'],'Hij haalde het einde zelf niet.','De vloot van Magellaan voer als eerste helemaal rond de wereld.','Van de 270 bemanningsleden kwamen er maar 18 terug.'],
        ['Welke Nederlander overwinterde op Nova Zembla?','Willem Barentsz',['Abel Tasman','Piet Hein','Michiel de Ruyter'],'Hij zocht een noordelijke route naar Azië.','Barentsz en zijn mannen zaten in 1596 een winter vast in het Behouden Huys.','De Barentszzee is naar hem genoemd.'],
        ['Naar wie is Tasmanië genoemd?','Abel Tasman',['Marco Polo','James Cook','Willem Barentsz'],'Een Nederlandse zeevaarder.','Abel Tasman ontdekte in 1642 het eiland dat nu Tasmanië heet.','Hij zag ook als eerste Europeaan Nieuw-Zeeland.'],
        ['Welke Venetiaan reisde in de middeleeuwen naar China?','Marco Polo',['Columbus','Magellaan','Cook'],'Hij schreef een beroemd reisboek.','Marco Polo reisde over de Zijderoute naar het hof van Koeblai Khan.','Zijn boek maakte Europeanen nieuwsgierig naar Azië.'],
        ['Wie bereikte in 1911 als eerste de Zuidpool?','Roald Amundsen',['Robert Scott','Ernest Shackleton','Edmund Hillary'],'Een Noor met sledehonden.','Amundsen bereikte de Zuidpool op 14 december 1911.','Zijn concurrent Scott kwam vijf weken later aan.'],
        ['Wie stonden in 1953 als eersten op de Mount Everest?','Edmund Hillary en Tenzing Norgay',['Amundsen en Scott','Columbus en Magellaan','Armstrong en Aldrin'],'Een Nieuw-Zeelander en een sherpa.','Hillary en Norgay bereikten in 1953 de top van de Everest.','De Everest is 8.849 meter hoog.'],
        ['Welk instrument gebruikten zeevaarders om hun positie aan de sterren te meten?','Een sextant',['Een verrekijker','Een barometer','Een stopwatch'],'Je meet de hoek tussen een ster en de horizon.','Met een sextant meet je hoe hoog een ster of de zon staat.','Daarmee kon je uitrekenen op welke breedtegraad je was.'],
        ['Welke ziekte kregen zeelieden door gebrek aan vitamine C?','Scheurbuik',['De pest','Griep','Malaria'],'Citroenen hielpen ertegen.','Scheurbuik ontstaat door een tekort aan vitamine C.','Britse zeelieden kregen citroensap en werden daarom "limeys" genoemd.'],
        ['Welke zeeroute zocht Vasco da Gama naar India?','Rond Afrika',['Over de Noordpool','Door het Panamakanaal','Over land'],'Langs Kaap de Goede Hoop.','Vasco da Gama voer in 1498 rond Afrika naar India.','Zo hoefden specerijen niet meer over land te komen.']
      ]
    },
    wetenschap: {
      slimme_proefjes: [
        ['Wat gebeurt er als je bakpoeder en azijn mengt?','Het gaat bruisen door koolstofdioxide',['Het wordt ijs','Het gaat gloeien','Er gebeurt niets'],'Er ontstaat een gas.','Bakpoeder en azijn reageren en maken koolstofdioxidegas.','Met deze reactie kun je een vulkaan nabootsen.'],
        ['Waarom drijft een ei in zout water maar zinkt het in gewoon water?','Zout water is zwaarder',['Het ei wordt lichter','Zout maakt gaatjes','Het ei wordt groter'],'Het gaat om dichtheid.','Zout maakt water dichter, waardoor het ei omhoog wordt geduwd.','In de Dode Zee blijf je door het zout vanzelf drijven.'],
        ['Wat bewijst het proefje met een kaars onder een glas?','Vuur heeft zuurstof nodig',['Vuur heeft water nodig','Glas brandt','Kaarsen doven vanzelf'],'De vlam gaat uit als de lucht op is.','Onder het glas raakt de zuurstof op en dooft de kaars.','Daarom kun je een vlam smoren met een deksel.'],
        ['Hoe maak je een regenboog met een glas water?','Laat zonlicht door het water breken',['Roer heel snel','Voeg zout toe','Verwarm het water'],'Water werkt als een prisma.','Water breekt wit licht in alle kleuren van de regenboog.','Een echte regenboog ontstaat door miljoenen regendruppels.'],
        ['Waarom plakt een ballon aan de muur nadat je hem over je haar wrijft?','Door statische elektriciteit',['Door lijm','Door warmte','Door lucht'],'Kleine deeltjes verplaatsen zich.','Wrijven laadt de ballon op met elektriciteit die de muur aantrekt.','Bliksem is dezelfde soort elektriciteit, maar dan enorm groot.'],
        ['Wat is een hypothese?','Een slimme voorspelling die je test',['Een bewezen feit','Een fout','Een meetlint'],'Je doet hem vóór het proefje.','Een hypothese is wat je denkt dat er gaat gebeuren, en dat test je.','Wetenschappers beginnen elk onderzoek met een hypothese.'],
        ['Waarom smelt ijs sneller als je er zout op strooit?','Zout verlaagt het smeltpunt',['Zout is warm','Zout is zwaar','Zout trekt zon aan'],'Daarom strooien we op de weg.','Zout zorgt dat water pas bij een lagere temperatuur bevriest.','Strooiwagens gebruiken daarom zout tegen gladheid.'],
        ['Wat gebeurt er met het volume van water als het bevriest?','Het wordt groter',['Het wordt kleiner','Het blijft gelijk','Het verdwijnt'],'Daarom barsten flessen in de vriezer.','Bevroren water neemt meer ruimte in dan vloeibaar water.','Daarom drijft ijs op water.'],
        ['Waarom zie je de bliksem eerder dan je de donder hoort?','Licht is sneller dan geluid',['Geluid is sneller','Donder komt van ver','Je ogen zijn sneller'],'Tel de seconden om de afstand te schatten.','Licht reist bijna direct, geluid doet er per kilometer drie seconden over.','Elke drie seconden tussen flits en knal is ongeveer een kilometer.'],
        ['Wat maak je met een gemagnetiseerde naald die op water drijft?','Een zelfgemaakt kompas',['Een thermometer','Een weegschaal','Een lamp'],'De naald draait naar het noorden.','Een gemagnetiseerde naald op water draait naar het noorden.','Zo werkten de allereerste kompassen.']
      ],
      lichaam: [
        ['Hoeveel botten heeft een volwassen mens?','206',['100','350','500'],'Een baby heeft er meer.','Een volwassene heeft 206 botten.','Baby\'s hebben ongeveer 300 botjes die later aan elkaar groeien.'],
        ['Welk orgaan zuivert je bloed en maakt urine?','De nieren',['De longen','De lever','De maag'],'Je hebt er twee.','De nieren filteren afvalstoffen uit je bloed.','Ze filteren elke dag zo\'n 180 liter bloed.'],
        ['Hoe heet het grootste orgaan van je lichaam?','De huid',['Het hart','De lever','De hersenen'],'Het zit aan de buitenkant.','De huid is het grootste orgaan van je lichaam.','Bij een volwassene weegt de huid ongeveer 4 kilo.'],
        ['Hoe vaak klopt je hart ongeveer per dag?','Ongeveer 100.000 keer',['1.000 keer','10.000 keer','1 miljoen keer'],'Zo\'n zeventig keer per minuut.','Je hart klopt ongeveer honderdduizend keer per dag.','In een mensenleven is dat meer dan 2,5 miljard keer.'],
        ['Welk deel van je bloed vecht tegen ziektes?','Witte bloedcellen',['Rode bloedcellen','Bloedplaatjes','Plasma'],'Niet de cellen die zuurstof dragen.','Witte bloedcellen sporen ziekteverwekkers op en ruimen ze op.','Een druppel bloed bevat duizenden witte bloedcellen.'],
        ['Hoe heet de spier onder je longen waarmee je ademt?','Het middenrif',['De biceps','De kuitspier','De buikspier'],'Als hij samentrekt, stroomt lucht naar binnen.','Het middenrif beweegt op en neer om je longen te vullen en te legen.','De hik is een kramp van het middenrif.'],
        ['Hoeveel tanden en kiezen heeft een volwassene?','32',['20','24','40'],'Inclusief de verstandskiezen.','Een volwassene heeft 32 tanden en kiezen.','Een melkgebit telt maar 20 tandjes.'],
        ['Welk deel van je hersenen regelt je evenwicht?','De kleine hersenen',['De grote hersenen','De hersenstam','Het ruggenmerg'],'Ze zitten achter en onder.','De kleine hersenen sturen je evenwicht en soepele bewegingen.','Ze zijn maar 10% van je hersenen, maar bevatten de helft van de zenuwcellen.'],
        ['Hoe lang is je dunne darm ongeveer?','Ongeveer 6 meter',['50 centimeter','1 meter','20 meter'],'Langer dan jij bent.','De dunne darm is bij een volwassene zo\'n zes meter lang.','Opgevouwen past hij toch in je buik.'],
        ['Wat is DNA?','De code met de bouwtekening van je lichaam',['Een soort bloed','Een vitamine','Een spier'],'Het zit in elke cel.','DNA bevat de instructies voor hoe je lichaam groeit en werkt.','Al het DNA uit één cel is uitgerold ongeveer twee meter lang.']
      ],
      uitvindingen: [
        ['Wie vond de telefoon uit?','Alexander Graham Bell',['Thomas Edison','Nikola Tesla','Guglielmo Marconi'],'Hij belde in 1876 zijn assistent.','Bell kreeg in 1876 het patent op de telefoon.','Zijn eerste woorden door de telefoon waren: "Mr. Watson, kom hier."'],
        ['Wie vond de boekdrukkunst met losse letters uit in Europa?','Johannes Gutenberg',['Leonardo da Vinci','Isaac Newton','Galileo'],'Zijn beroemdste drukwerk is een bijbel.','Gutenberg drukte rond 1450 boeken met losse metalen letters.','Daarvoor werd elk boek met de hand overgeschreven.'],
        ['Wie ontdekte penicilline?','Alexander Fleming',['Louis Pasteur','Marie Curie','Charles Darwin'],'Hij zag schimmel op een vergeten schaaltje.','Fleming ontdekte in 1928 dat een schimmel bacteriën doodde.','Penicilline was het eerste antibioticum en redde miljoenen levens.'],
        ['Wie ontdekte radioactiviteit en won twee Nobelprijzen?','Marie Curie',['Isaac Newton','Albert Einstein','Ada Lovelace'],'De eerste vrouw met een Nobelprijs.','Marie Curie onderzocht radioactiviteit en ontdekte radium en polonium.','Haar notitieboeken zijn nog steeds radioactief.'],
        ['Welke uitvinding van Willem Einthoven meet je hartslag?','De elektrocardiograaf',['De röntgenfoto','De stethoscoop','De thermometer'],'Een Nederlander won er de Nobelprijs mee.','Einthoven vond het apparaat uit dat de elektriciteit van je hart tekent: het ECG.','Zijn eerste apparaat woog 270 kilo.'],
        ['Wie wordt gezien als de eerste computerprogrammeur?','Ada Lovelace',['Bill Gates','Alan Turing','Steve Jobs'],'Een vrouw uit de 19e eeuw.','Ada Lovelace schreef in 1843 het eerste programma voor een rekenmachine.','Een programmeertaal heet naar haar: Ada.'],
        ['Welke Nederlander maakte de eerste microscoop waarmee bacteriën te zien waren?','Antoni van Leeuwenhoek',['Christiaan Huygens','Willem Einthoven','Hendrik Lorentz'],'Een lakenhandelaar uit Delft.','Van Leeuwenhoek zag als eerste bacteriën door zijn zelfgemaakte lensjes.','Hij noemde ze "kleine diertjes".'],
        ['Wie bedacht het wereldwijde web (www)?','Tim Berners-Lee',['Mark Zuckerberg','Elon Musk','Steve Jobs'],'Hij werkte bij CERN.','Tim Berners-Lee bedacht in 1989 het world wide web.','Hij gaf zijn uitvinding gratis aan de wereld.'],
        ['Welke Nederlander vond de slingerklok uit?','Christiaan Huygens',['Antoni van Leeuwenhoek','Simon Stevin','Cornelis Drebbel'],'Hij ontdekte ook de maan Titan.','Huygens bouwde in 1656 de eerste nauwkeurige slingerklok.','Zijn klok liep maar tien seconden per dag verkeerd.'],
        ['Wat vonden de gebroeders Wright uit?','Het eerste motorvliegtuig',['De auto','De stoomtrein','De helikopter'],'Hun eerste vlucht duurde 12 seconden.','De gebroeders Wright vlogen in 1903 als eersten met een motorvliegtuig.','De eerste vlucht was korter dan de spanwijdte van een Boeing 747.']
      ],
      natuur_energie: [
        ['Hoe heet het proces waarmee planten van zonlicht voedsel maken?','Fotosynthese',['Verbranding','Verdamping','Ademhaling'],'"Foto" betekent licht.','Bij fotosynthese maken planten suiker uit licht, water en koolstofdioxide.','Als bijproduct maken ze de zuurstof die wij inademen.'],
        ['Welke energiebron gebruikt de warmte uit de aarde?','Geothermie',['Zonne-energie','Windenergie','Kernenergie'],'"Geo" betekent aarde.','Geothermische energie haalt warmte diep uit de grond.','IJsland verwarmt bijna alle huizen met aardwarmte.'],
        ['Wat is het broeikaseffect?','Gassen houden warmte vast in de atmosfeer',['De zon wordt heter','Kassen maken warmte','De aarde krimpt'],'Zonder zou het op aarde ijskoud zijn.','Broeikasgassen zoals CO₂ houden warmte vast, als glas in een kas.','Te veel broeikasgas maakt de aarde warmer dan goed is.'],
        ['Waar komt de energie in een windmolen oorspronkelijk vandaan?','Van de zon',['Van de maan','Uit de grond','Uit de zee'],'De zon verwarmt lucht en die gaat bewegen.','Wind ontstaat doordat de zon de lucht ongelijk verwarmt.','Wind is dus eigenlijk een vorm van zonne-energie.'],
        ['Hoe heet het gas dat planten inademen en wij uitademen?','Koolstofdioxide',['Zuurstof','Helium','Waterstof'],'De scheikundige naam is CO₂.','Planten nemen koolstofdioxide op en geven zuurstof af.','Een grote boom neemt per jaar tientallen kilo\'s CO₂ op.'],
        ['Wat is een zonnecel?','Een plaatje dat licht in stroom omzet',['Een spiegel','Een batterij','Een lamp'],'Hij zit op daken.','Een zonnecel zet licht direct om in elektriciteit.','De eerste zonnecellen werden gebruikt op satellieten.'],
        ['Hoe heet stroom die gemaakt wordt met vallend water?','Waterkracht',['Kernenergie','Biogas','Aardgas'],'Vallend water drijft een turbine aan.','Bij waterkracht laat men water door een turbine vallen om stroom te maken.','Noorwegen haalt bijna al zijn stroom uit waterkracht.'],
        ['Wat is biogas?','Gas uit rottend plantenafval en mest',['Gas uit de grond','Gas uit de zee','Gas uit de lucht'],'Het komt van bacteriën.','Bacteriën maken biogas uit mest en groenafval.','Op sommige boerderijen rijden de trekkers op biogas.'],
        ['Welke energiebron raakt op?','Aardolie',['Wind','Zon','Getijden'],'Het is een fossiele brandstof.','Aardolie is in miljoenen jaren ontstaan en groeit niet terug.','Wind, zon en water raken nooit op: die zijn hernieuwbaar.'],
        ['Wat is een voedselketen?','Wie wat eet in de natuur',['Een winkelketen','Een ketting van planten','Een recept'],'Gras, konijn, vos.','Een voedselketen laat zien hoe energie van plant naar dier naar dier gaat.','Bovenaan staan roofdieren; onderaan bijna altijd planten.']
      ]
    },
    mysterie: {
      raadsels: [
        ['Ik heb steden maar geen huizen, bossen maar geen bomen, water maar geen vissen. Wat ben ik?','Een landkaart',['Een boek','Een droom','Een spiegel'],'Je vouwt me open om de weg te vinden.','Een kaart toont steden, bossen en water zonder dat ze echt zijn.','De oudste bekende kaart is een kleitablet van 4.500 jaar oud.'],
        ['Wat wordt groter naarmate je er meer van weghaalt?','Een gat',['Een berg','Een muur','Een taart'],'Graven maakt het erger.','Hoe meer je weggraaft, hoe groter het gat.','De diepste door mensen gegraven put is ruim 12 kilometer diep.'],
        ['Wat heeft een nek maar geen hoofd?','Een fles',['Een giraffe','Een trui','Een gitaar'],'Je giet eruit.','Een fles heeft een hals, maar geen hoofd.','Een gitaar heeft trouwens ook een hals — én een kop.'],
        ['Welke maand heeft 28 dagen?','Alle maanden',['Februari','April','Alleen februari en april'],'Denk niet te snel.','Elke maand heeft minstens 28 dagen.','Februari is de enige maand die soms precies 28 dagen heeft.'],
        ['Wat gaat de wereld rond maar blijft in een hoekje?','Een postzegel',['De wind','De maan','Een vlieg'],'Hij zit op een envelop.','Een postzegel reist mee met de brief, maar zit altijd in de hoek.','De eerste postzegel ter wereld is de Britse Penny Black uit 1840.'],
        ['Ik spreek zonder mond en hoor zonder oren. Wat ben ik?','Een echo',['Een radio','Een hond','Een schaduw'],'Je hoort me in de bergen.','Een echo kaatst je stem terug alsof iemand antwoordt.','Een echo ontstaat als geluid tegen een harde muur botst.'],
        ['Hoe kan het dat een man al 40 dagen niet slaapt en toch niet moe is?','Hij slaapt \'s nachts',['Hij drinkt koffie','Hij is een robot','Het is niet mogelijk'],'Lees goed: dagen.','Hij slaapt gewoon \'s nachts — overdag slaapt hij niet.','Een mens kan zonder slaap hooguit een paar dagen goed functioneren.'],
        ['Wat is licht als een veer, maar zelfs de sterkste mens kan het niet lang vasthouden?','Je adem',['Een ballon','Een gedachte','Een sneeuwvlok'],'Je doet het steeds opnieuw.','Adem weegt bijna niets, maar niemand kan hem lang inhouden.','Het record adem inhouden is meer dan 24 minuten, na het inademen van pure zuurstof.'],
        ['Hoeveel maanden hebben 31 dagen?','7',['5','6','8'],'Tel ze op je knokkels.','Januari, maart, mei, juli, augustus, oktober en december.','Met je knokkels kun je het onthouden: elke knokkel is een lange maand.'],
        ['Wat heeft één oog maar kan niet zien?','Een naald',['Een piraat','Een cycloop','Een aardappel'],'Je haalt er een draad door.','Het gat in een naald heet het oog.','Aardappels hebben "ogen", maar dat zijn er meestal meer dan één.']
      ],
      verborgen_schatten: [
        ['Waar ligt het beroemde graf van Toetanchamon?','In de Vallei der Koningen',['In een piramide','In Rome','Onder de Sfinx'],'Bij Luxor in Egypte.','Toetanchamons graf ligt in de Vallei der Koningen bij Luxor.','Howard Carter zocht er vijf jaar naar.'],
        ['Hoe heet de verzonken stad uit de verhalen van Plato?','Atlantis',['Troje','Pompeï','El Dorado'],'Hij zou in één nacht in zee zijn verdwenen.','Atlantis is een legendarische stad die in de zee verdween.','Niemand heeft ooit bewijs gevonden dat Atlantis echt bestond.'],
        ['Wat zochten Spaanse ontdekkers in de "stad van goud"?','El Dorado',['Atlantis','Camelot','Babylon'],'In Zuid-Amerika.','El Dorado was een legendarische gouden stad in Zuid-Amerika.','De legende begon met een koning die zich met goudstof bedekte.'],
        ['Welke schat werd in 1985 op de zeebodem gevonden?','Het wrak van de Titanic',['De Ark van Noach','Het Gouden Kalf','De schat van Piet Hein'],'Een beroemd gezonken schip.','Het wrak van de Titanic werd in 1985 op bijna 4 kilometer diepte gevonden.','De Titanic zonk in 1912 na een botsing met een ijsberg.'],
        ['Welke Nederlandse admiraal veroverde in 1628 de Spaanse zilvervloot?','Piet Hein',['Michiel de Ruyter','Maarten Tromp','Willem Barentsz'],'Er is een liedje over.','Piet Hein veroverde de zilvervloot vol Zuid-Amerikaans zilver.','De buit was zo groot dat de VOC-aandeelhouders 50% winst kregen.'],
        ['Hoe heet het bergterras in Peru dat lang verborgen bleef in de jungle?','Machu Picchu',['Chichén Itzá','Petra','Angkor Wat'],'Gebouwd door de Inca\'s.','Machu Picchu is een Incastad hoog in de Andes, herontdekt in 1911.','De stenen passen zo precies dat er geen mes tussen past.'],
        ['Wat is het Terracottaleger?','Duizenden beelden van soldaten uit klei',['Een echt leger','Een schat van goud','Een bibliotheek'],'Gevonden bij het graf van een Chinese keizer.','Het Terracottaleger bewaakt het graf van de eerste keizer van China.','Elke soldaat heeft een ander gezicht.'],
        ['Wat is een tijdcapsule?','Een doos met spullen voor mensen in de toekomst',['Een klok','Een ruimteschip','Een oude kist met goud'],'Je begraaft hem nu, iemand opent hem later.','In een tijdcapsule stop je dingen die mensen over jaren mogen openen.','In Oslo ligt een capsule die pas in 2112 open mag.'],
        ['Hoe heet de rotsstad in Jordanië die in de rotsen is uitgehakt?','Petra',['Machu Picchu','Pompeï','Carthago'],'Bekend uit een Indiana Jones-film.','Petra is een stad die de Nabateeërs in roze rotsen uithakten.','De stad was eeuwenlang vergeten en werd in 1812 herontdekt.'],
        ['Welke metaaldetector-vondst is een Angelsaksische schat vol goud uit Engeland?','De Staffordshire Hoard',['De Kroonjuwelen','De Rosettasteen','Het Gouden Vlies'],'Gevonden op een akker in 2009.','De Staffordshire Hoard is de grootste Angelsaksische goudschat ooit gevonden.','Hij werd door een hobbyist met een metaaldetector gevonden.']
      ],
      natuurmysteries: [
        ['Hoe weten trekvogels waar ze heen moeten?','Met het magnetisch veld, de zon en sterren',['Ze volgen auto\'s','Ze raden het','Ze vliegen altijd rechtdoor'],'Ze hebben een ingebouwd kompas.','Trekvogels voelen het aardmagnetisch veld en gebruiken zon en sterren.','De noordse stern vliegt elk jaar van pool naar pool: 70.000 kilometer.'],
        ['Wat is het noorderlicht?','Deeltjes van de zon die in de lucht oplichten',['Vuurwerk','Een spiegeling van ijs','Bliksem'],'Je ziet het vooral bij de polen.','Zonnedeeltjes botsen op de atmosfeer en laten de lucht groen en paars gloeien.','Op de zuidpool heet hetzelfde verschijnsel zuiderlicht.'],
        ['Waarom lichten sommige zeedieren op in het donker?','Bioluminescentie',['Ze weerkaatsen de maan','Ze zijn radioactief','Ze eten lampjes'],'Ze maken zelf licht.','Bioluminescentie is licht dat dieren zelf maken met stoffen in hun lichaam.','Negentig procent van de dieren in de diepzee kan licht maken.'],
        ['Wat zijn de "bewegende stenen" van Death Valley?','De wind schuift ze over dun ijs',['Levende stenen','Stenen met motortjes','Een optische illusie'],'Het raadsel is in 2014 opgelost.','Dun ijs en wind schuiven de stenen langzaam over de woestijnvloer.','Sommige stenen laten sporen van honderden meters achter.'],
        ['Hoe kunnen vleermuizen in het donker vliegen?','Met echolocatie',['Ze hebben nachtogen','Ze onthouden alles','Ze volgen de maan'],'Ze roepen en luisteren naar de echo.','Vleermuizen sturen geluidjes uit en horen aan de echo waar alles is.','Dolfijnen gebruiken onder water dezelfde truc.'],
        ['Wat is een fata morgana?','Een luchtspiegeling',['Een tovenaar','Een storm','Een soort wolk'],'Je ziet water dat er niet is.','Warme lucht buigt licht, waardoor je verre dingen of "water" ziet.','Boven een heet wegdek zie je vaak zo\'n nep-plas.'],
        ['Waarom is de zee soms rood?','Door een bloei van kleine algen',['Door bloed','Door roest','Door de zonsondergang'],'Kleine organismen in enorme aantallen.','Bij een "rode vloed" kleuren miljarden algen het water rood.','Sommige van die algen zijn giftig voor vissen.'],
        ['Hoe kunnen zalmen hun geboorterivier terugvinden?','Aan de geur van het water',['Met een kaart','Ze volgen andere vissen','Ze zwemmen willekeurig'],'Hun neus onthoudt de rivier.','Zalmen ruiken het water van de rivier waar ze geboren zijn.','Ze zwemmen soms duizenden kilometers terug.'],
        ['Wat zijn kogelbliksems?','Zeldzame lichtbollen tijdens onweer',['Hagelstenen','Sterren','Vuurwerk'],'Wetenschappers snappen ze nog niet helemaal.','Kogelbliksems zijn zwevende lichtbollen die soms bij onweer worden gezien.','Ze worden al eeuwen beschreven, maar zijn zelden gefilmd.'],
        ['Waarom staan honderden hectaren bomen in Siberië plat sinds 1908?','Een ontploffing van een ruimtesteen in de lucht',['Een orkaan','Een vulkaan','Houthakkers'],'De Toengoeska-gebeurtenis.','In 1908 ontplofte een meteoroïde boven Siberië en blies 80 miljoen bomen om.','Er is nooit een krater gevonden.']
      ],
      speurtocht: [
        ['Wat is een alibi?','Bewijs dat je ergens anders was',['Een vingerafdruk','Een vermomming','Een geheime code'],'"Ik was thuis, mijn buurman zag me."','Een alibi bewijst dat een verdachte niet op de plek van het misdrijf kon zijn.','Het woord is Latijn voor "ergens anders".'],
        ['Waarom zijn vingerafdrukken zo nuttig voor speurders?','Elke mens heeft unieke vingerafdrukken',['Ze zijn altijd zichtbaar','Ze ruiken','Ze veranderen elke dag'],'Zelfs tweelingen verschillen.','Geen twee mensen hebben dezelfde vingerafdruk.','Koala\'s hebben vingerafdrukken die bijna niet van mensen te onderscheiden zijn.'],
        ['Hoe heet de beroemde speurder met een pijp en een vergrootglas?','Sherlock Holmes',['Hercule Poirot','Miss Marple','James Bond'],'Zijn vriend heet Watson.','Sherlock Holmes is de speurder uit de boeken van Arthur Conan Doyle.','Hij woonde op Baker Street 221B in Londen.'],
        ['Wat is morsecode?','Een code van korte en lange signalen',['Een geheime taal van spionnen','Een soort schrift met plaatjes','Een spel'],'Punt-punt-punt, streep-streep-streep.','Morse zet letters om in korte en lange piepjes of lichtflitsen.','SOS is in morse drie kort, drie lang, drie kort.'],
        ['Wat is een cryptogram?','Een geheime boodschap in code',['Een soort kaart','Een gestolen schat','Een oud gebouw'],'Je moet hem ontcijferen.','Een cryptogram is een tekst die in een geheime code geschreven is.','Julius Caesar schoof letters in het alfabet op om berichten geheim te houden.'],
        ['Welke hond helpt speurders om mensen op te sporen aan hun geur?','Een speurhond',['Een herdershond','Een sledehond','Een blindengeleidehond'],'Zijn neus is duizenden keren beter dan die van jou.','Speurhonden volgen een geurspoor dat mensen achterlaten.','Een hond heeft zo\'n 300 miljoen geurcellen; een mens maar 6 miljoen.'],
        ['Wat is een sporenonderzoek?','Kleine aanwijzingen verzamelen op een plek',['Een wedstrijd hardlopen','Een zoekactie in een bos','Het bouwen van een spoor'],'Haren, vezels, voetstappen.','Bij sporenonderzoek zoeken speurders naar haren, vezels en afdrukken.','Zelfs stofdeeltjes kunnen verraden waar iemand is geweest.'],
        ['Waarmee kun je onzichtbare inkt van citroensap zichtbaar maken?','Warmte',['Water','Zout','Koud licht'],'Houd het papier bij een lamp.','Citroensap wordt bruin als je het papier voorzichtig verwarmt.','Spionnen gebruikten deze truc al honderden jaren geleden.'],
        ['Wat is een Caesar-code?','Elke letter schuift een vast aantal plaatsen op',['Een code van cijfers','Een code van kleuren','Een code van plaatjes'],'A wordt D, B wordt E.','Bij de Caesar-code vervang je elke letter door een letter verderop in het alfabet.','Met een verschuiving van 13 heet de code ROT13.'],
        ['Hoe heet een geheim teken dat je met een spiegel kunt lezen?','Spiegelschrift',['Braille','Morse','Geheimschrift'],'Leonardo da Vinci schreef zo.','Spiegelschrift is achterstevoren geschreven en leesbaar in een spiegel.','Leonardo da Vinci vulde duizenden pagina\'s in spiegelschrift.']
      ]
    },
    dieren: {
      snelle_dieren: [
        ['Welk dier duikt met meer dan 300 km per uur?','De slechtvalk',['De arend','De cheeta','De zwaluw'],'Een roofvogel in duikvlucht.','De slechtvalk is in duikvlucht het snelste dier op aarde.','Hij haalt meer dan 320 kilometer per uur.'],
        ['Wat is de snelste vis?','De zeilvis',['De haai','De tonijn','De zalm'],'Hij heeft een grote rugvin als een zeil.','De zeilvis zwemt met ruim 100 kilometer per uur.','Hij vouwt zijn zeil in als hij sprint.'],
        ['Welk insect is het snelste?','De paardenhorzel',['De vlinder','De mier','Het lieveheersbeestje'],'Een grote vlieg.','Sommige horzels halen 145 kilometer per uur.','Libellen zijn met 55 kilometer per uur ook snelle vliegers.'],
        ['Waarom kan een cheeta zijn topsnelheid maar kort volhouden?','Zijn lichaam wordt te heet',['Zijn poten breken','Hij wordt bang','Hij vergeet waar hij heen gaat'],'Na 30 seconden is het klaar.','Een cheeta raakt oververhit en moet na een korte sprint stoppen.','Hij haalt 0 tot 100 kilometer per uur in drie seconden.'],
        ['Welk landdier op twee poten is het snelst?','De struisvogel',['De kangoeroe','De mens','De kip'],'Hij kan niet vliegen.','De struisvogel rent 70 kilometer per uur.','Eén stap van een struisvogel is wel vijf meter lang.'],
        ['Welk dier is het snelst over lange afstanden?','De gaffelantilope',['De cheeta','Het paard','De hond'],'Uit Noord-Amerika, en hij houdt het lang vol.','De gaffelantilope kan kilometers lang 60 kilometer per uur rennen.','Waarschijnlijk vluchtte hij vroeger voor een uitgestorven Amerikaanse cheeta.'],
        ['Hoe snel loopt een mens op topsnelheid?','Ongeveer 45 km per uur',['15 km per uur','70 km per uur','100 km per uur'],'Usain Bolt.','De snelste sprinters halen even bijna 45 kilometer per uur.','Usain Bolt liep de 100 meter in 9,58 seconden.'],
        ['Welk zoogdier vliegt het snelst?','De Braziliaanse bulldogvleermuis',['De vliegende eekhoorn','De vleerhond','De kolibrie'],'Geen vogel, wel vleugels.','Deze vleermuis haalt in rechte vlucht 160 kilometer per uur.','Ze leven in kolonies van miljoenen dieren.'],
        ['Welke vogel slaat 80 keer per seconde met zijn vleugels?','De kolibrie',['De mus','De duif','De zwaluw'],'Hij kan stil in de lucht hangen.','Kolibries bewegen hun vleugels zo snel dat je ze niet ziet.','Ze zijn de enige vogels die achteruit kunnen vliegen.'],
        ['Welke slang is het snelst?','De zwarte mamba',['De python','De cobra','De adder'],'Uit Afrika, en ook heel giftig.','De zwarte mamba beweegt met 20 kilometer per uur.','Zijn naam komt van de zwarte binnenkant van zijn bek.']
      ],
      baby_dieren: [
        ['Hoe lang is een olifant zwanger?','Ongeveer 22 maanden',['9 maanden','3 maanden','5 jaar'],'Bijna twee jaar.','Een olifant draagt haar jong bijna twee jaar.','Een pasgeboren olifantje weegt al 100 kilo.'],
        ['Hoe groot is een pasgeboren kangoeroe?','Zo groot als een boon',['Zo groot als een kat','Zo groot als een hond','Zo groot als een muis'],'Hij kruipt zelf naar de buidel.','Een baby-kangoeroe is bij de geboorte maar twee centimeter.','Hij groeit maandenlang verder in de buidel van zijn moeder.'],
        ['Welk dier legt eieren maar geeft toch melk?','Het vogelbekdier',['De kip','De kat','De slang'],'Een zoogdier met een snavel.','Het vogelbekdier legt eieren en voedt zijn jongen met melk.','Het is een van de weinige giftige zoogdieren.'],
        ['Hoe heet een jonge zwaan?','Een zwanenkuiken',['Een lelijk eendje','Een kuiken','Een jonge gans'],'Grijs en pluizig.','Jonge zwanen zijn grijs en worden pas later wit.','Het sprookje "Het lelijke eendje" gaat over een jonge zwaan.'],
        ['Welk vaderdier draagt de eieren in zijn buidel tot ze uitkomen?','Het zeepaardje',['De pinguïn','De kikker','De haai'],'De mannetjes worden "zwanger".','Bij zeepaardjes legt het vrouwtje de eieren in de buidel van het mannetje.','Een mannetje kan wel duizend jongen tegelijk krijgen.'],
        ['Hoe houdt een keizerspinguïn zijn ei warm?','Op zijn voeten onder een huidplooi',['In een nest van gras','Onder een steen','In het water'],'Op het ijs is een nest onmogelijk.','De vader balanceert het ei op zijn voeten en bedekt het met een warme huidplooi.','Hij eet twee maanden niets tijdens het broeden.'],
        ['Hoe heet een jong hert?','Een kalf',['Een lammetje','Een veulen','Een big'],'Net als bij een koe.','Een jong hert heet een kalf.','Reekalfjes hebben witte stippen die ze in het bos onzichtbaar maken.'],
        ['Hoe lang blijft een orang-oetanjong bij zijn moeder?','Ongeveer 7 jaar',['1 maand','1 jaar','20 jaar'],'Langer dan bijna elk ander dier.','Jonge orang-oetans leren jarenlang van hun moeder in het bos.','De naam orang-oetan betekent "bosmens".'],
        ['Hoeveel jongen krijgt een muis per keer ongeveer?','5 tot 8',['1','2','30'],'Meer dan een paar.','Een muis krijgt meestal een nest van vijf tot acht jongen.','Ze kan wel tien keer per jaar jongen krijgen.'],
        ['Welk baby-dier heet een pup en groeit op in het water?','Een zeehond',['Een pinguïn','Een dolfijn','Een otter'],'Hij heeft eerst een witte vacht.','Jonge zeehonden heten pups en hebben in het begin een witte vacht.','Op de Waddenzee worden elk jaar zeehondenpups geboren.']
      ],
      waterdieren: [
        ['Welk dier is het grootste dat ooit op aarde heeft geleefd?','De blauwe vinvis',['De T. rex','De mammoet','De walvishaai'],'Hij leeft nu nog.','De blauwe vinvis is groter dan elke dinosaurus ooit was.','Zijn hart is zo groot als een kleine auto.'],
        ['Hoeveel harten heeft een octopus?','3',['1','2','8'],'Meer dan één.','Een octopus heeft drie harten en blauw bloed.','Twee harten pompen naar de kieuwen, één naar de rest van het lichaam.'],
        ['Hoe diep kan een potvis duiken?','Meer dan 2 kilometer',['20 meter','200 meter','20 kilometer'],'Hij jaagt op reuzeninktvissen in het donker.','Potvissen duiken meer dan twee kilometer diep.','Ze kunnen bijna anderhalf uur onder water blijven.'],
        ['Wat is een koraalrif?','Een bouwwerk van miljoenen kleine dieren',['Een rots','Een soort zeewier','Een berg zand'],'Koralen zijn levende dieren.','Een rif wordt gebouwd door koraalpoliepen die een kalkskelet maken.','Het Groot Barrièrerif is vanuit de ruimte te zien.'],
        ['Welke vis kan naar buiten kijken met beide ogen aan één kant?','De platvis',['De haai','De zalm','De paling'],'Hij ligt plat op de bodem.','Bij een platvis als de schol verhuist één oog naar de andere kant.','Jonge platvissen zwemmen nog rechtop, met een oog aan elke kant.'],
        ['Hoe heet een groep dolfijnen?','Een school',['Een kudde','Een zwerm','Een troep'],'Net als bij vissen.','Dolfijnen leven in groepen die een school heten.','Ze roepen elkaar met een eigen fluitje, een soort naam.'],
        ['Welk zeedier kan elektrische schokken geven?','De sidderrog',['De kwal','De zeester','De krab'],'Een platte vis met stroom.','De sidderrog geeft schokken tot 200 volt om prooien te verdoven.','De Romeinen gebruikten sidderroggen tegen hoofdpijn.'],
        ['Waarom zwemmen haaien altijd door?','Anders krijgen ze geen zuurstof',['Ze kunnen niet stoppen','Ze zijn bang','Ze zoeken altijd eten'],'Water moet langs hun kieuwen stromen.','Veel haaien moeten blijven zwemmen om water langs hun kieuwen te sturen.','Haaien bestaan al langer dan bomen: 400 miljoen jaar.'],
        ['Wat is plankton?','Piepkleine zwevende planten en dieren',['Een soort zand','Groot zeewier','Een kwal'],'Walvissen eten er tonnen van.','Plankton bestaat uit minuscule organismen die met de stroming meedrijven.','Plankton maakt meer dan de helft van de zuurstof op aarde.'],
        ['Welk dier verandert van kleur en vorm om zich te verstoppen?','De inktvis',['De dolfijn','De zeehond','De tonijn'],'Hij kan eruitzien als steen of wier.','Inktvissen veranderen in een oogwenk van kleur en huidstructuur.','De mimic octopus doet zelfs andere dieren na.']
      ],
      jungle: [
        ['Hoe heet de dikste laag bladeren hoog in het regenwoud?','Het bladerdak',['De bosbodem','De onderlaag','De struiklaag'],'Daar leeft het meeste.','Het bladerdak of kronendak is de laag waar de meeste junglebewoners leven.','Sommige dieren komen nooit op de grond.'],
        ['Welk regenwoud is het grootste ter wereld?','Het Amazonewoud',['Het Congowoud','Het woud van Borneo','Het Zwarte Woud'],'In Zuid-Amerika.','Het Amazonewoud ligt in negen landen en is groter dan heel West-Europa.','Er stroomt een rivier doorheen die het meeste water van alle rivieren voert.'],
        ['Welke aap is de grootste?','De gorilla',['De chimpansee','De orang-oetan','De baviaan'],'Een mannetje weegt 200 kilo.','De gorilla is de grootste mensaap.','Ondanks zijn kracht eet hij bijna alleen planten.'],
        ['Welke vogel kan mensen nadoen en leeft in de jungle?','De papegaai',['De toekan','De kolibrie','De uil'],'Hij praat je na.','Papegaaien kunnen geluiden en woorden nadoen.','De grijze roodstaartpapegaai Alex kende meer dan honderd woorden.'],
        ['Welk dier beweegt zo langzaam dat er algen op zijn vacht groeien?','De luiaard',['De schildpad','De slak','De koala'],'Hij hangt de hele dag.','Een luiaard beweegt zo traag dat zijn vacht groen wordt van de algen.','Hij komt maar één keer per week uit de boom om te poepen.'],
        ['Welke kikker waarschuwt met felle kleuren dat hij giftig is?','De pijlgifkikker',['De boomkikker','De pad','De brulkikker'],'Fel geel, blauw of rood.','Pijlgifkikkers zijn felgekleurd om roofdieren te waarschuwen.','Jagers smeerden het gif vroeger op hun blaaspijlpijlen.'],
        ['Hoe heet de grootste slang van Zuid-Amerika?','De anaconda',['De python','De cobra','De boa'],'Hij leeft in moerassen.','De anaconda is de zwaarste slang ter wereld en woont in het water.','Hij kan wel 200 kilo wegen.'],
        ['Welke grote kat leeft in de Zuid-Amerikaanse jungle?','De jaguar',['De leeuw','De tijger','Het luipaard'],'Hij houdt van zwemmen.','De jaguar is de grootste kat van Zuid-Amerika.','Zijn beet is zo sterk dat hij schildpadschilden kraakt.'],
        ['Waarom is het regenwoud belangrijk voor de hele aarde?','Het maakt zuurstof en slaat CO₂ op',['Het maakt regen voor Nederland','Het is een groot park','Er wonen veel mensen'],'Het wordt de longen van de aarde genoemd.','De bomen van het regenwoud nemen CO₂ op en geven zuurstof af.','Elke seconde verdwijnt er ergens een stuk regenwoud zo groot als een voetbalveld.'],
        ['Welke mier bouwt met bladeren een schimmeltuin?','De bladsnijdersmier',['De rode bosmier','De vuurmier','De legermier'],'Ze eten de bladeren niet zelf.','Bladsnijdersmieren kweken schimmels op stukjes blad en eten de schimmel.','Een kolonie kan miljoenen mieren tellen.']
      ]
    },
    aarde: {
      continenten_landen: [
        ['Welk land heeft de meeste inwoners?','India',['China','Verenigde Staten','Indonesië'],'Sinds 2023 niet meer China.','India heeft sinds 2023 meer inwoners dan China: ruim 1,4 miljard.','Ongeveer één op de zes mensen op aarde woont in India.'],
        ['Welk land is het grootste in oppervlakte?','Rusland',['Canada','China','Brazilië'],'Het strekt zich uit over elf tijdzones.','Rusland is met 17 miljoen vierkante kilometer het grootste land.','Het is bijna twee keer zo groot als Canada.'],
        ['Welk land is het kleinste ter wereld?','Vaticaanstad',['Monaco','Luxemburg','Malta'],'Het ligt midden in Rome.','Vaticaanstad is nog geen halve vierkante kilometer groot.','Er wonen minder dan duizend mensen.'],
        ['Op welk continent ligt de Sahara?','Afrika',['Azië','Australië','Zuid-Amerika'],'De grootste hete woestijn.','De Sahara ligt in het noorden van Afrika.','Hij is bijna zo groot als de Verenigde Staten.'],
        ['Welke stad is de hoofdstad van Australië?','Canberra',['Sydney','Melbourne','Perth'],'Niet de grootste stad.','Canberra werd speciaal gebouwd als hoofdstad tussen Sydney en Melbourne.','De stad werd in 1913 ontworpen door een Amerikaans echtpaar.'],
        ['Welk gebergte scheidt Europa van Azië?','De Oeral',['De Alpen','De Himalaya','De Andes'],'Het ligt in Rusland.','De Oeral wordt gezien als de grens tussen Europa en Azië.','De bergen zijn ruim 2.500 kilometer lang.'],
        ['Welk land heeft de meeste buurlanden?','China',['Rusland','Brazilië','Duitsland'],'Veertien stuks.','China grenst aan veertien landen.','Rusland grenst aan evenveel landen, maar China wordt meestal als eerste genoemd.'],
        ['In welk werelddeel ligt Suriname?','Zuid-Amerika',['Afrika','Azië','Midden-Amerika'],'Er wordt Nederlands gesproken.','Suriname ligt aan de noordkust van Zuid-Amerika.','Het was tot 1975 een Nederlandse kolonie.'],
        ['Welke twee landen delen de langste grens ter wereld?','Canada en de Verenigde Staten',['Rusland en China','Brazilië en Argentinië','India en China'],'Bijna 9.000 kilometer.','De grens tussen Canada en de VS is de langste landsgrens.','Een groot deel loopt kaarsrecht langs de 49e breedtegraad.'],
        ['Welk land ligt op twee continenten?','Turkije',['Spanje','Mexico','Japan'],'Istanbul ligt op allebei.','Turkije ligt deels in Europa en deels in Azië.','De Bosporusbrug verbindt de twee continenten in Istanbul.']
      ],
      weer_klimaat: [
        ['Hoe meet je luchtdruk?','Met een barometer',['Met een thermometer','Met een windmeter','Met een regenmeter'],'Hoge druk betekent meestal mooi weer.','Een barometer meet de druk van de lucht.','Dalende druk kondigt vaak regen aan.'],
        ['Hoe ontstaat hagel?','IJs dat in een onweerswolk op en neer waait',['Sneeuw die bevriest','Regen die op de grond bevriest','IJs dat van bergen waait'],'Ze groeien laagje voor laagje.','In een onweerswolk vriest water in lagen aan tot een hagelsteen.','De grootste hagelsteen ooit was zo groot als een grapefruit.'],
        ['Wat is het verschil tussen weer en klimaat?','Weer is nu, klimaat is het gemiddelde over jaren',['Weer is warm, klimaat is koud','Er is geen verschil','Klimaat is alleen bij de evenaar'],'Vandaag regent het, maar Nederland heeft een gematigd klimaat.','Weer is wat je vandaag ziet; klimaat is het gemiddelde weer over dertig jaar.','Klimaatzones lopen van tropisch tot polair.'],
        ['Hoe heet een enorme draaiende storm boven een warme oceaan?','Een orkaan',['Een tornado','Een moesson','Een stofstorm'],'In Azië heet hij tyfoon.','Orkanen ontstaan boven warm zeewater en draaien om een rustig "oog".','Orkanen krijgen om beurten een mannen- en vrouwennaam.'],
        ['Welke wolk brengt onweer?','De cumulonimbus',['De cirrus','De stratus','De cumulus'],'Een torenhoge aambeeldwolk.','De cumulonimbus is een reusachtige wolk die onweer, hagel en windstoten brengt.','Zo\'n wolk kan 15 kilometer hoog worden.'],
        ['Wat is El Niño?','Warm oceaanwater dat het weer wereldwijd verandert',['Een orkaan','Een wind uit de Sahara','Een koude winter'],'Het is Spaans voor "het jongetje".','El Niño maakt het water bij Zuid-Amerika warmer en verstoort het weer op aarde.','In El Niño-jaren regent het in Peru en is het droog in Australië.'],
        ['Op welke temperatuur bevriest water in graden Fahrenheit?','32 graden',['0 graden','100 graden','-32 graden'],'Amerikanen gebruiken deze schaal.','In Fahrenheit bevriest water bij 32 graden en kookt het bij 212.','In Celsius is dat 0 en 100 graden.'],
        ['Hoe heet de laag in de atmosfeer waar al het weer plaatsvindt?','De troposfeer',['De stratosfeer','De ozonlaag','De ionosfeer'],'De onderste laag.','Bijna alle wolken en al het weer zitten in de troposfeer.','Vliegtuigen vliegen boven de wolken, aan de bovenkant ervan.'],
        ['Wat meet de schaal van Beaufort?','Windkracht',['Temperatuur','Regen','Aardbevingen'],'Van 0 tot 12.','De schaal van Beaufort geeft de kracht van de wind aan.','Windkracht 12 is een orkaan.'],
        ['Waarom is het aan de kust vaak winderiger dan in het binnenland?','Land en zee warmen ongelijk op',['De zee blaast','Er zijn geen huizen','De zon schijnt harder'],'Zeewind.','Overdag warmt land sneller op dan zee, en die temperatuurverschillen maken wind.','Daarom waait er op een warme dag vaak een frisse zeebries.']
      ],
      oceanen_natuur: [
        ['Wat is de diepste plek van de oceaan?','De Marianentrog',['De Noordzee','De Golf van Mexico','Het Kanaal'],'Bijna 11 kilometer diep.','De Marianentrog in de Stille Oceaan is bijna 11 kilometer diep.','Als je de Mount Everest erin zet, steekt hij nog niet boven water uit.'],
        ['Welke oceaan is het grootst?','De Stille Oceaan',['De Atlantische Oceaan','De Indische Oceaan','De Noordelijke IJszee'],'Hij bedekt een derde van de aarde.','De Stille Oceaan is groter dan alle landen bij elkaar.','Magellaan noemde hem "stil" omdat het weer rustig was toen hij hem overstak.'],
        ['Wat veroorzaakt een tsunami?','Een aardbeving onder de zee',['Harde wind','De maan','Regen'],'De zeebodem verschuift.','Een tsunami ontstaat als de zeebodem plotseling beweegt, meestal door een aardbeving.','Op open zee is een tsunami laag en snel: tot 800 kilometer per uur.'],
        ['Hoe heet de warme zeestroom die Europa mild houdt?','De Golfstroom',['De Humboldtstroom','De Noordzeestroom','De Kaapstroom'],'Hij begint bij de Golf van Mexico.','De Golfstroom voert warm water naar Europa.','Zonder de Golfstroom zou Nederland winters hebben als Canada.'],
        ['Waarom is de zee zout?','Rivieren brengen zout van het land naar zee',['Vissen maken zout','Het regent zout','De zon maakt zout'],'Het zout komt uit stenen.','Regen spoelt zout uit gesteente en rivieren brengen het naar zee.','Als al het zeezout op het land lag, was het een laag van 150 meter dik.'],
        ['Wat is eb en vloed?','Het stijgen en dalen van de zee door de maan',['Golven door wind','Stromingen door vissen','Regen op zee'],'Twee keer per dag.','De zwaartekracht van de maan trekt aan het water en maakt getijden.','Bij het Canadese Bay of Fundy is het verschil 16 meter.'],
        ['Hoeveel procent van de oceaan is verkend?','Ongeveer 25 procent',['Bijna 100 procent','Ongeveer 75 procent','Ongeveer 50 procent'],'We kennen de maan beter.','Ruim driekwart van de zeebodem is nog nooit in detail in kaart gebracht.','Er zijn meer mensen op de maan geweest dan op de bodem van de Marianentrog.'],
        ['Wat is een atol?','Een ringvormig koraaleiland',['Een vulkaan','Een ijsberg','Een zandbank'],'Met een lagune in het midden.','Een atol is een ring van koraal rond een lagune, vaak op een gezonken vulkaan.','De Malediven bestaan uit bijna 1.200 atol-eilandjes.'],
        ['Wat is een mangrove?','Een bos dat met zijn wortels in zout water staat',['Een soort koraal','Een zeewier','Een strand'],'Bomen in de zee.','Mangrovebomen groeien aan tropische kusten in zout water.','Ze beschermen de kust tegen golven en zijn kraamkamers voor vissen.'],
        ['Hoe heet het grote gebied plastic afval in de Stille Oceaan?','De plasticsoep',['Het plasticstrand','De afvalberg','De vuilniszee'],'Zo groot als Frankrijk, Spanje en Duitsland samen.','In de Stille Oceaan drijft een enorme wolk plastic afval.','De Nederlander Boyan Slat bedacht een systeem om het op te ruimen.']
      ],
      kaarten_navigatie: [
        ['Hoeveel satellieten gebruikt je telefoon minstens om je plek met GPS te bepalen?','4',['1','2','10'],'Meer dan drie.','Met signalen van minstens vier satellieten berekent GPS waar je bent.','Er cirkelen ongeveer dertig GPS-satellieten om de aarde.'],
        ['Hoe heet de lijn van pool naar pool waar de tijd begint?','De nulmeridiaan',['De evenaar','De datumgrens','De keerkring'],'Hij loopt door Greenwich.','De nulmeridiaan loopt door Greenwich bij Londen en is nul graden lengte.','Aan de andere kant van de aarde ligt de datumgrens.'],
        ['Wat geven hoogtelijnen op een kaart aan?','Hoe hoog en steil het land is',['Wegen','Rivieren','Grenzen'],'Dicht bij elkaar betekent steil.','Hoogtelijnen verbinden punten op dezelfde hoogte.','Hoe dichter de lijnen op elkaar, hoe steiler de helling.'],
        ['Wat betekent een schaal van 1:100.000?','1 cm op de kaart is 1 km in het echt',['1 cm is 1 meter','1 cm is 100 meter','1 cm is 100 km'],'Reken om: 100.000 centimeter.','Bij schaal 1:100.000 is één centimeter op de kaart een kilometer in het echt.','Wandelkaarten zijn vaak 1:25.000: één centimeter is 250 meter.'],
        ['Hoeveel graden zijn er tussen noord en oost op een kompas?','90',['45','180','360'],'Een kwart van de cirkel.','Noord is 0 graden, oost 90, zuid 180 en west 270.','Een hele cirkel is 360 graden.'],
        ['Hoe heet een kaart die de hele aarde als bol laat zien?','Een globe',['Een atlas','Een plattegrond','Een panorama'],'Hij draait.','Een globe is een model van de aarde als bol.','Een platte kaart maakt Groenland altijd te groot; een globe niet.'],
        ['Welke kant wijst een kompasnaald naar in werkelijkheid?','Naar de magnetische noordpool',['Naar de geografische noordpool','Naar de zon','Naar het zuiden'],'Die ligt niet precies op de pool.','De naald wijst naar de magnetische noordpool, die een stuk van de echte pool af ligt.','De magnetische pool verplaatst zich zo\'n 50 kilometer per jaar.'],
        ['Hoe heet het systeem met kaarten in lagen op een computer?','GIS',['GPS','USB','GSM'],'Geografisch Informatie Systeem.','Met GIS leg je kaartlagen over elkaar, zoals wegen, water en bebouwing.','Gemeenten gebruiken GIS om te plannen waar nieuwe huizen komen.'],
        ['Waarom lijkt Groenland op veel kaarten zo groot als Afrika?','Door de Mercatorprojectie',['Het is echt zo groot','Kaartenmakers vergissen zich','Door het ijs'],'Een platte kaart rekt de polen uit.','De Mercatorkaart maakt gebieden bij de polen veel groter dan ze zijn.','Afrika is in werkelijkheid veertien keer groter dan Groenland.'],
        ['Hoe heet de horizontale lijn op 0 graden breedte?','De evenaar',['De nulmeridiaan','De poolcirkel','De keerkring'],'Hij verdeelt de aarde in noord en zuid.','De evenaar ligt precies tussen de polen op nul graden breedte.','Bij de evenaar is de aarde iets dikker dan bij de polen.']
      ]
    }
  };
})();
