(() => {
  // Generated by tools/content-build.cjs from content/. Do not edit by hand:
  // change the question in content/<world>/<topic>.json and run the tool again.
  // Rows continue after the twenty a topic already has, and each one states its
  // own difficulty in the seventh field.
  window.KWIZILLO_MORE_IT = {
    ruimte: {
      zonnestelsel: [
        ['Quale stella sta al centro del sistema solare?','Il Sole',['La stella polare','Sirio','La Luna'],'La vedi ogni giorno quando fa chiaro.','Il Sole è la stella attorno a cui girano tutti i pianeti.','Il Sole è così grande che ci starebbero un milione di Terre.',1],
        ['Che cosa gira attorno al Sole?','I pianeti',['Solo la Luna','Tutte le stelle','Niente'],'Anche la nostra Terra.','Tutti e otto i pianeti girano su un\'orbita attorno al Sole.','Anche comete e asteroidi girano, ma su giri molto più lunghi.',1],
        ['Quale pianeta viene dopo la Terra, più lontano dal Sole?','Marte',['Venere','Mercurio','La Luna'],'È il pianeta color ruggine.','Dopo la Terra viene Marte, più lontano dal Sole.','Marte è grande circa la metà della Terra.',1],
        ['Perché di notte fa buio?','Perché la Terra gira',['Perché il Sole si spegne','Perché la Luna lo mangia','Perché passa una nuvola'],'Il Sole continua a splendere.','La Terra gira e il tuo posto guarda per un po\' dall\'altra parte.','La Terra fa un giro completo in ventiquattro ore.',1],
        ['Quale degli otto pianeti è il più piccolo?','Mercurio',['Marte','Venere','La Terra'],'È anche il più vicino al Sole.','Mercurio è il pianeta più piccolo del sistema solare.','Lì di notte si gela e di giorno si brucia.',1],
        ['Quanto impiega la Terra a girare attorno al Sole?','Circa un anno',['Un mese','Una settimana','Un giorno'],'Proprio il tempo fra due compleanni.','La Terra impiega circa 365 giorni per un giro attorno al Sole.','Ogni quattro anni aggiungiamo un giorno: è l\'anno bisestile.',2],
        ['Che cos\'è Plutone dal 2006?','Un pianeta nano',['Una luna','Una cometa','Una stella'],'È troppo piccolo per essere un pianeta vero.','Dal 2006 Plutone è chiamato pianeta nano.','Ce ne sono altri: anche Cerere, Eris e Makemake.',2],
        ['Quali due pianeti sono fatti soprattutto di gas?','Giove e Saturno',['Terra e Marte','Mercurio e Venere','Marte e Venere'],'Sono i due più grandi.','Giove e Saturno sono giganti gassosi: non ci si può stare in piedi.','Nel profondo quei gas sono schiacciati fino a sembrare liquidi.',2],
        ['Perché a volte si fa buio in pieno giorno?','La Luna copre il Sole',['Il Sole si spegne un po\'','La Terra smette di girare','Il Sole cade dietro i monti'],'Qualcosa si mette fra te e il Sole.','La Luna passa proprio fra il Sole e la Terra e la luce cala.','Non guardare mai il Sole senza occhiali speciali, neanche in eclissi.',2],
        ['Dove puoi saltare più in alto?','Sulla Luna',['Sulla Terra','In fondo al mare','In aereo'],'Lì la gravità tira molto più piano.','La Luna ti attira molto meno, così salti sei volte più in alto.','Gli astronauti dell\'Apollo saltellavano perché camminare non andava.',2],
        ['Quanti anni ha il nostro sistema solare?','Circa 4,6 miliardi di anni',['Circa 1 milione di anni','Circa 100 milioni di anni','Circa 500 miliardi di anni'],'Molto più vecchio dei dinosauri, che sono già antichissimi.','Il Sole e i pianeti sono nati da una nube di gas e polvere.','I pezzi più antichi che ne abbiamo sono caduti qui come meteoriti.',3],
        ['Quale luna di Giove è piena di vulcani?','Io',['Europa','Ganimede','Callisto'],'È la più vicina a Giove, che la impasta.','Io ha più vulcani di qualsiasi altro posto del sistema solare.','Giove la impasta così forte che la luna si scioglie dentro.',3],
        ['Di che cosa sono fatti gli anelli di Saturno?','Di ghiaccio e roccia',['Di gas e vapore','Di polvere e nuvole','Di acqua liquida'],'Pensa a miliardi di palle di neve in fila.','Gli anelli sono miliardi di pezzi di ghiaccio e roccia.','Sono larghi migliaia di chilometri ma spessi spesso dieci metri.',3],
        ['Quale pianeta ha il vento più forte?','Nettuno',['La Terra','Marte','Mercurio'],'Più ci si allontana dal Sole, più il tempo è freddo e pazzo.','Su Nettuno il vento soffia a quasi 2000 chilometri all\'ora.','La tempesta più veloce sulla Terra non arriva a un quarto.',3],
        ['Come si chiama il vulcano più grande del sistema solare?','Olympus Mons',['L\'Everest','Il Vesuvio','Il Mauna Kea'],'Non è sulla Terra, ma sul pianeta rosso.','L\'Olympus Mons su Marte è alto quasi tre volte l\'Everest.','È largo quanto la Francia: sopra non vedresti nemmeno la salita.',3],
        ['Su quale pianeta un giorno dura più di un anno?','Venere',['Mercurio','Marte','Urano'],'Questo pianeta gira lentissimo su sé stesso.','Venere gira una volta in 243 giorni e fa il giro del Sole in 225.','Venere gira anche al contrario: lì il Sole sorge a ovest.',4],
        ['Quale sonda è uscita per prima dal sistema solare?','Voyager 1',['Hubble','Cassini','Apollo 11'],'È partita nel 1977 e vola ancora.','Nel 2012 Voyager 1 è arrivata per prima nello spazio fra le stelle.','Porta un disco d\'oro con musica e saluti dalla Terra.',4],
        ['Quanta parte del peso del sistema solare sta nel Sole?','Più del 99 per cento',['Circa la metà','Circa un decimo','Meno dell\'1 per cento'],'Quasi tutto, e i pianeti sono il resto.','Il Sole è così pesante che tutti i pianeti insieme non fanno un per cento.','Proprio per questo i pianeti continuano a girargli intorno.',4],
        ['Quale pianeta è stato prima calcolato e poi visto?','Nettuno',['Urano','Saturno','Plutone'],'Gli astronomi vedevano qualcosa tirare Urano.','Nel 1846 calcolarono dove doveva stare, ed era lì.','Il telescopio lo trovò quella notte stessa, quasi nel punto previsto.',4],
        ['Come si chiama il guscio di ghiacci attorno al sistema?','La nube di Oort',['La fascia di Kuiper','La fascia di asteroidi','La Via Lattea'],'Porta il nome di un astronomo olandese.','La nube di Oort è una sfera di pezzi di ghiaccio, oltre ogni pianeta.','Da lì arrivano le comete che passano una volta ogni mille anni.',4]
      ]
    }
  };
})();
