(() => {
  // German bank. Same worlds, topics, order and therefore the same question ids
  // as the Dutch, English and Portuguese banks, so progress, cards and the
  // per-question illustrations survive a language switch.
  const defs = {
    ruimte: {
      zonnestelsel: [
        ["Welcher Planet ist der Sonne am nächsten?","Merkur",["Venus","Mars","Erde"],"Er ist der kleinste Planet und steht ganz vorne.","Merkur ist der Sonne am nächsten.","Ein Jahr auf Merkur dauert nur 88 Erdtage."],
        ["Welcher Planet ist unser Heimatplanet?","Erde",["Venus","Mars","Jupiter"],"Hier leben Menschen, Tiere und Pflanzen.","Wir leben auf der Erde.","Etwa 71% der Erde sind von Wasser bedeckt."],
        ["Welcher Planet ist als der rote Planet bekannt?","Mars",["Venus","Saturn","Neptun"],"Sein Boden enthält viel Eisenoxid.","Der Mars wird der rote Planet genannt.","Der Mars hat zwei kleine Monde: Phobos und Deimos."],
        ["Welcher Planet hat die berühmtesten Ringe?","Saturn",["Erde","Merkur","Mars"],"Er ist ein großer Gasriese.","Saturn hat ein auffälliges Ringsystem.","Die Ringe bestehen vor allem aus Eis und Gestein."],
        ["Welcher Planet ist der größte in unserem Sonnensystem?","Jupiter",["Mars","Venus","Erde"],"Er hat den berühmten Großen Roten Fleck.","Jupiter ist der größte Planet.","In Jupiter würden mehr als tausend Erden passen."],
        ["Welcher Planet ist am weitesten von der Sonne entfernt?","Neptun",["Jupiter","Erde","Venus"],"Er ist ein ferner blauer Eisriese.","Neptun ist der Planet, der am weitesten von der Sonne entfernt ist.","Ein Jahr auf Neptun dauert etwa 165 Erdjahre."],
        ["Welcher Planet liegt zwischen Venus und Mars?","Erde",["Merkur","Jupiter","Saturn"],"Es ist unser eigener Planet.","Die Reihenfolge ist Venus, Erde, Mars.","Die Erde ist der dritte Planet von der Sonne aus."],
        ["Was dreht sich um die Erde?","Der Mond",["Jupiter","Die Sonne","Mars"],"Du siehst ihn oft am Nachthimmel.","Der Mond dreht sich um die Erde.","Der Mond braucht für eine Runde etwa 27 Tage."],
        ["Wie viele Planeten hat unser Sonnensystem?","8",["7","9","10"],"Pluto zählt heute als Zwergplanet.","Unser Sonnensystem hat acht Planeten.","Seit 2006 gilt Pluto als Zwergplanet."],
        ["Welcher Planet ist für seine kräftige blaue Farbe berühmt?","Neptun",["Merkur","Mars","Venus"],"Er ist ein ferner Eisriese.","Neptun sieht tiefblau aus.","Methan in seiner Atmosphäre verstärkt die blaue Farbe."]
      ],
      sterren_planeten: [
        ["Was ist die Sonne?","Ein Stern",["Ein Planet","Ein Mond","Ein Komet"],"Sie macht ihr eigenes Licht und ihre Wärme.","Die Sonne ist ein Stern.","Sonnenlicht braucht etwa 8 Minuten bis zur Erde."],
        ["Woraus besteht ein Stern vor allem?","Aus heißem Gas und Plasma",["Aus kaltem Gestein","Aus einem Mond","Aus einer Wolke"],"Sterne leuchten selbst.","Sterne bestehen aus extrem heißem Gas und Plasma.","Unsere Sonne ist ein mittelgroßer Stern."],
        ["Was ist eine Galaxie?","Eine riesige Gruppe von Sternen",["Ein Planet","Ein Teleskop","Eine Wolke auf der Erde"],"Die Milchstraße ist eine davon.","Eine Galaxie enthält sehr viele Sterne.","Die Milchstraße hat Hunderte Milliarden Sterne."],
        ["Wie heißt unsere Galaxie?","Die Milchstraße",["Andromeda","Orion","Saturn"],"Manchmal siehst du ein blasses Band am dunklen Himmel.","Unser Sonnensystem liegt in der Milchstraße.","Die Milchstraße ist eine Spiralgalaxie."],
        ["Was ist eine Supernova?","Eine gewaltige Sternexplosion",["Ein Neumond","Ein Raketenstart","Ein Regenschauer"],"Sie passiert am Ende des Lebens mancher Sterne.","Eine Supernova ist eine gewaltige Explosion eines Sterns.","So eine Explosion kann kurz extrem hell leuchten."],
        ["Welche Farbe haben die heißesten Sterne meistens?","Blau",["Rot","Braun","Grün"],"Blaues Licht gehört zu sehr hohen Temperaturen.","Sehr heiße Sterne sehen oft bläulich aus.","Rote Sterne sind meist kühler als blaue."],
        ["Was ist ein Exoplanet?","Ein Planet bei einem anderen Stern",["Ein Mond der Erde","Ein Komet","Ein Satellit"],"Er dreht sich nicht um unsere Sonne.","Ein Exoplanet kreist um einen anderen Stern als die Sonne.","Inzwischen wurden Tausende Exoplaneten entdeckt."],
        ["Was ist ein schwarzes Loch?","Ein Gebiet mit extrem starker Schwerkraft",["Ein dunkler Planet","Eine Wolke","Ein Raketenmotor"],"Selbst Licht kann kaum entkommen.","Ein schwarzes Loch hat extrem starke Schwerkraft.","Viele schwarze Löcher entstehen aus schweren Sternen."],
        ["Welcher Stern ist der Erde am nächsten?","Die Sonne",["Sirius","Polarstern","Beteigeuze"],"Du siehst ihn jeden Tag.","Die Sonne ist unser nächster Stern.","Der nächste Stern danach ist viel weiter weg."],
        ["Warum scheinen Sterne zu funkeln?","Wegen der Atmosphäre",["Weil sie blinken","Wegen ihrer Monde","Weil sie sich drehen"],"Ihr Licht wird unterwegs durch Luftschichten gebogen.","Die Atmosphäre lässt Sternenlicht ein wenig zittern.","Planeten funkeln meist weniger als Sterne."]
      ],
      astronauten: [
        ["Wie nennt man jemanden, der ins Weltall reist?","Astronaut",["Archäologe","Taucher","Kapitän"],"Diese Person trägt oft einen Raumanzug.","Ein Astronaut reist und arbeitet im Weltall.","Astronauten trainieren oft jahrelang."],
        ["Warum tragen Astronauten außerhalb des Raumschiffs einen Raumanzug?","Für Luft und Schutz",["Für Wärme","Für Geschwindigkeit","Als Uniform"],"Im Weltall kann man nicht einfach atmen.","Ein Raumanzug liefert Sauerstoff und Schutz.","Ein Raumanzug schützt auch vor extremen Temperaturen."],
        ["Was spüren Astronauten in einer Raumstation oft?","Schwerelosigkeit",["Starken Regen","Starken Wind","Erdbeben"],"Sie scheinen zu schweben.","In einer Umlaufbahn erleben Astronauten Mikrogravitation.","Alles muss festgemacht werden, damit es nicht wegschwebt."],
        ["Wo schlafen Astronauten in der Raumstation meistens?","In festgemachten Schlafsäcken",["In normalen Betten","In Hängematten draußen","Auf dem Boden"],"Sonst würden sie wegschweben.","Astronauten schlafen oft in festgemachten Schlafsäcken.","In Mikrogravitation gibt es kein echtes Oben oder Unten."],
        ["Warum trainieren Astronauten unter Wasser?","Um Schwerelosigkeit nachzuahmen",["Um schneller zu schwimmen","Um Mondwasser zu suchen","Zur Entspannung"],"Unter Wasser kann man schwebende Bewegungen üben.","Unterwassertraining hilft, Weltraumspaziergänge zu üben.","In großen Becken stehen manchmal Modelle von Stationsteilen."],
        ["Was ist ein Weltraumspaziergang?","Arbeit außerhalb eines Raumfahrzeugs",["Laufen auf der Erde","Rennen in einer Rakete","Ein Museumsbesuch"],"Der Astronaut bleibt mit Sicherheitssystemen verbunden.","Ein Weltraumspaziergang heißt auch EVA.","Dabei tragen Astronauten einen vollständigen Raumanzug."],
        ["Was passiert mit Muskeln bei langer Schwerelosigkeit?","Sie können schwächer werden",["Sie werden zu Stahl","Sie verschwinden sofort","Sie wachsen immer schneller"],"Darum trainieren Astronauten viel.","Ohne Training können Muskeln und Knochen schwächer werden.","Astronauten trainieren jeden Tag auf der ISS."],
        ["Was essen Astronauten im Weltall?","Besonders verpacktes Essen",["Pillen","Eis","Nichts"],"Es muss in Mikrogravitation sicher sein.","Astronauten essen besonders verpacktes Essen.","Krümel sind schwierig, weil sie herumschweben können."],
        ["Was ist die ISS?","Eine internationale Raumstation",["Ein Planet","Ein Raketenmotor","Eine Mondbasis"],"Sie kreist um die Erde.","Die ISS ist eine große Raumstation in einer Umlaufbahn um die Erde.","Dort arbeiten Astronauten aus verschiedenen Ländern zusammen."],
        ["Warum muss sich ein Astronaut bei der Arbeit festmachen?","Damit er nicht wegschwebt",["Für extra Schwerkraft","Gegen Regen","Für Geschwindigkeit"],"In Mikrogravitation bewegt man sich leicht weiter.","Ein Seil verhindert, dass jemand unkontrolliert wegtreibt.","Auch Werkzeug wird meist gesichert."]
      ],
      raket_avontuur: [
        ["Wozu dient ein Raketenmotor?","Um Schub zu erzeugen",["Um Fotos zu drucken","Um Sauerstoff zu machen","Um Sterne zu zählen"],"Er stößt heiße Gase nach hinten.","Ein Raketenmotor sorgt für Schub.","Durch Wirkung und Gegenwirkung fliegt die Rakete in die andere Richtung."],
        ["Warum braucht eine Rakete so viel Treibstoff?","Um der Schwerkraft zu entkommen",["Für die Beleuchtung","Für die Klimaanlage","Für das Radio"],"Der Start kostet enorm viel Energie.","Ein Start braucht riesige Mengen Energie.","Beim Start kann der größte Teil einer Rakete Treibstoff sein."],
        ["Was passiert beim Start?","Die Rakete steigt auf",["Die Rakete landet","Der Motor stoppt immer","Der Mond kommt näher"],"Das ist der Moment des Abflugs.","Der Start ist der Moment, in dem die Rakete den Boden verlässt.","Die ersten Sekunden sind technisch sehr wichtig."],
        ["Warum haben manche Raketen mehrere Stufen?","Um leere Teile abzuwerfen",["Für extra Fenster","Für Schlafplätze","Für Farben"],"So schleppt die Rakete weniger Masse mit.","Raketen können Stufen abwerfen, wenn ihr Treibstoff leer ist.","So wird das weitere Beschleunigen sparsamer."],
        ["Was ist eine Startrampe?","Der Platz, von dem eine Rakete abfliegt",["Ein Satellit","Ein Mondfahrzeug","Ein Sitz im Cockpit"],"Dort steht die Rakete vor dem Start.","Eine Startrampe trägt die Rakete vor dem Flug.","Dort gibt es große Anlagen für Treibstoff, Kühlung und Sicherheit."],
        ["Was ist ein Satellit?","Ein Objekt, das um ein anderes Objekt kreist",["Eine Sternexplosion","Ein Raketenmotor","Ein Teleskop"],"Der Mond ist im Grunde auch ein natürlicher Satellit.","Satelliten kreisen um einen Planeten oder einen anderen Körper.","Künstliche Satelliten helfen bei Navigation und Kommunikation."],
        ["Warum ist die Spitze einer Rakete stromlinienförmig?","Um den Luftwiderstand zu verringern",["Um schwerer zu sein","Um mehr Regen zu fangen","Wegen der Farbe"],"Eine glatte Form bewegt sich leichter durch Luft.","Eine stromlinienförmige Spitze verringert den Luftwiderstand.","Außerhalb der Atmosphäre gibt es fast keinen Luftwiderstand mehr."],
        ["Was ist eine Kapsel?","Ein Teil, in dem Menschen oder Fracht reisen können",["Eine Galaxie","Ein Mond","Ein Treibstoff"],"Sie sitzt oft oben auf der Rakete.","Eine Raumkapsel bringt Menschen oder Fracht mit.","Manche Kapseln kommen mit Fallschirmen zurück."],
        ["Was hilft einer Kapsel, sicher zu landen?","Fallschirme",["Sterne","Sonnenstürme","Asteroiden"],"Sie bremsen den Fall.","Fallschirme bremsen eine zurückkehrende Kapsel.","Manche Fahrzeuge landen auch mit Motoren."],
        ["Was ist eine Umlaufbahn um die Erde?","Eine Bahn, auf der man ständig um die Erde fällt",["Eine gerade Straße zur Sonne","Ein Tunnel","Eine Wolke"],"Geschwindigkeit und Schwerkraft sind im Gleichgewicht.","Ein Satellit in der Umlaufbahn fällt immer weiter um die Erde.","Darum stürzt er nicht einfach hinunter."]
      ]
    },
    geschiedenis: {
      egyptenaren: [
        ["Wofür wurden viele Pyramiden gebaut?","Als Grabmäler",["Als Schulen","Als Märkte","Als Häfen"],"Denk an Pharaonen und ihre Bestattung.","Viele Pyramiden waren Grabmäler für Pharaonen.","Die Große Pyramide von Gizeh ist Tausende Jahre alt."],
        ["Wie nannte man einen Herrscher im alten Ägypten?","Pharao",["Senator","Ritter","Wikinger"],"Er stand an der Spitze der Gesellschaft.","Ein ägyptischer Herrscher wurde Pharao genannt.","Manche Pharaonen galten als göttlich."],
        ["Welcher Fluss war für Ägypten sehr wichtig?","Der Nil",["Der Rhein","Der Amazonas","Die Donau"],"Er fließt durch das Land und macht den Boden fruchtbar.","Der Nil war wichtig für Landwirtschaft und Transport.","Jährliche Überschwemmungen brachten fruchtbaren Schlamm."],
        ["Wie heißt die ägyptische Schrift mit Zeichen und Bildern?","Hieroglyphen",["Latein","Runen","Morsezeichen"],"Du siehst sie auf Tempeln und in Gräbern.","Hieroglyphen waren eine wichtige ägyptische Schrift.","Die Schrift benutzte Hunderte Zeichen."],
        ["Was ist eine Mumie?","Ein haltbar gemachter Körper",["Eine Goldmünze","Ein Tempel","Ein Boot"],"Der Körper wurde nach dem Tod besonders behandelt.","Die Ägypter machten Mumien, um Körper zu erhalten.","Der Vorgang konnte viele Wochen dauern."],
        ["Worauf schrieben die Ägypter oft?","Auf Papyrus",["Auf Plastik","Auf Beton","Auf Aluminium"],"Es wurde aus einer Pflanze am Nil gemacht.","Papyrus wurde als Schreibmaterial benutzt.","Unser Wort Papier ist mit Papyrus verwandt."],
        ["Was war die Sphinx von Gizeh?","Eine Statue mit Löwenkörper und Menschenkopf",["Eine Pyramide","Ein Schiff","Eine Krone"],"Sie steht nahe bei den Pyramiden.","Die Große Sphinx ist eine riesige Steinstatue.","Die Sphinx wurde aus Kalkstein gehauen."],
        ["Wofür nutzten die Ägypter Bewässerung?","Um ihre Felder zu wässern",["Um Pyramiden zu malen","Um zu schreiben","Um Münzen zu machen"],"Wasser aus dem Nil musste zu den Feldern kommen.","Bewässerung half der Landwirtschaft.","Kanäle und Becken verteilten das Wasser über die Felder."],
        ["Welche Tiere galten in Ägypten oft als besonders?","Katzen",["Eisbären","Pinguine","Kängurus"],"Sie kommen in Kunst und Religion viel vor.","Katzen hatten im alten Ägypten einen besonderen Platz.","Die Göttin Bastet wurde oft als Katze dargestellt."],
        ["Was machten Schreiber im alten Ägypten?","Texte und Aufzeichnungen führen",["Pyramiden fliegen","Ritter ausbilden","Sterne machen"],"Schreiben war eine wichtige Fähigkeit.","Schreiber führten Aufzeichnungen und verfolgten Steuern.","Nicht jeder konnte lesen und schreiben."]
      ],
      ridders_kastelen: [
        ["Was trug ein Ritter oft zum Schutz?","Eine Rüstung",["Einen Raumanzug","Einen Bademantel","Einen Taucheranzug"],"Sie war aus Metall.","Eine Rüstung schützte den Körper.","Eine vollständige Rüstung hatte viele einzelne Teile."],
        ["Wo wohnte ein mächtiger Herr oft?","In einer Burg",["In einer Rakete","In einer Pyramide","In einem Iglu"],"Das Gebäude hatte dicke Mauern.","Burgen waren Wohnorte und Verteidigungsanlagen.","Viele Burgen hatten Türme und Mauern."],
        ["Was ist ein Burggraben?","Ein Wassergraben um eine Burg",["Ein Schlafzimmer","Ein Marktplatz","Eine Waffenkammer"],"Er machte Angriffe schwieriger.","Ein Burggraben half bei der Verteidigung.","Nicht jeder Graben hatte immer Wasser."],
        ["Was ist eine Zugbrücke?","Eine Brücke, die man hochziehen kann",["Eine geheime Treppe","Eine Fahne","Ein Turm"],"Sie war oft am Eingang.","Eine Zugbrücke konnte den Weg hinein versperren.","Oft war sie mit einem Tor verbunden."],
        ["Was passierte bei einem Ritterturnier?","Ritter traten in Wettkämpfen an",["Man baute Pyramiden","Man segelte nach Amerika","Man baute Teleskope"],"Denk an das Lanzenstechen.","Turniere waren Wettkämpfe für Ritter.","Das Lanzenstechen war ein spektakuläres Ereignis."],
        ["Was ist ein Schild?","Ein Schutz gegen Angriffe",["Ein Musikinstrument","Eine Landkarte","Ein Trinkbecher"],"Ritter trugen es oft an einem Arm.","Ein Schild schützt gegen Waffen.","Auf Schilden waren oft Zeichen oder Wappen."],
        ["Wer wohnte meistens nicht dauerhaft in einer Burg?","Alle Bauern aus der Gegend",["Der Burgherr","Soldaten","Diener"],"Viele Menschen wohnten in Dörfern um die Burg.","Die meisten Bauern wohnten außerhalb der Burg.","Bei Gefahr konnten sie dort manchmal Schutz finden."],
        ["Warum hatten Burgen dicke Mauern?","Zur Verteidigung",["Für schnelleres Internet","Für Wärme","Als Schmuck"],"Sie mussten Angriffen widerstehen.","Dicke Steinmauern machten Burgen stärker.","Später machten Kanonen viele Mauern viel weniger nützlich."],
        ["Was machte ein Knappe oft?","Einem Ritter helfen und lernen",["Einen Pharao begraben","Eine Rakete fliegen","Einen Tempel bauen"],"Manchmal bereitete er sich auf den Ritterschlag vor.","Ein Knappe half einem Ritter und lernte Fertigkeiten.","Nicht jeder Knappe wurde später Ritter."],
        ["Was war eine Festung?","Ein befestigter Ort zum Wohnen",["Eine Galaxie","Ein Schiff","Ein Schulfach"],"Das Wort wird oft für Burgen benutzt.","Eine Festung war ein befestigter Ort.","Festungen standen oft an wichtigen Stellen."]
      ],
      romeinen: [
        ["Wer baute das Kolosseum?","Die Römer",["Die Wikinger","Die Maya","Die Ägypter"],"Es steht in Rom.","Das Kolosseum wurde von den Römern gebaut.","Es hatte Platz für Zehntausende Zuschauer."],
        ["Was war ein Aquädukt?","Ein Bauwerk, um Wasser zu leiten",["Ein Ritterhelm","Ein Tempel für Boote","Eine Münze"],"Es brachte Wasser in die Städte.","Römische Aquädukte leiteten Wasser über weite Strecken.","Manche Aquädukte sind heute noch zu sehen."],
        ["Welche Sprache sprachen viele Römer?","Latein",["Niederländisch","Japanisch","Arabisch"],"Viele europäische Wörter kommen daher.","Latein war eine wichtige Sprache im Römischen Reich.","Französisch, Spanisch und Italienisch sind romanische Sprachen."],
        ["Was war eine Legion?","Eine große Gruppe römischer Soldaten",["Ein Markt","Ein Badehaus","Ein Schiff"],"Sie war ein Teil des Heeres.","Eine Legion war eine große Heereseinheit.","Römische Soldaten trainierten streng."],
        ["Was war ein Forum in einer römischen Stadt?","Ein zentraler Platz",["Ein Gefängnis","Ein Bauernhof","Ein Hafen"],"Dort kamen Menschen für Handel und Regierung zusammen.","Das Forum war ein wichtiger Stadtmittelpunkt.","Oft standen dort Tempel und öffentliche Gebäude."],
        ["Wofür waren römische Badehäuser da?","Zum Waschen und Treffen",["Zum Raketenbauen","Zum Lagern von Getreide","Zum Trainieren von Pferden"],"Dort kamen Menschen auch gesellig zusammen.","Badeanlagen waren wichtige Treffpunkte.","Manche hatten warme und kalte Bäder."],
        ["Was trug ein römischer Soldat oft?","Einen Helm und einen Schild",["Einen Raumanzug","Einen Cowboyhut","Einen Taucheranzug"],"Er musste sich im Kampf schützen.","Römische Soldaten nutzten Helme, Schilde und Waffen.","Ihre Ausrüstung änderte sich über die Jahrhunderte."],
        ["Was bedeutet „Römisches Reich“?","Ein großes Gebiet, das von Rom aus regiert wurde",["Die Stadt Rom","Eine Pyramide","Ein Ritterorden"],"Es reichte über große Teile Europas.","Das Römische Reich war sehr weitläufig.","In seiner Blütezeit umfasste es die Länder rund ums Mittelmeer."],
        ["Was nutzten die Römer für weite Wege über Land?","Ein großes Straßennetz",["Flüsse","Heißluftballons","Züge"],"Viele Straßen waren solide gebaut.","Die Römer bauten ein großes Straßennetz.","Manche heutigen Straßen folgen alten römischen Wegen."],
        ["Was war ein Senator in Rom?","Ein wichtiger Amtsträger",["Immer ein Gladiator","Ein Pharao","Ein Ritter"],"Er hatte eine politische Rolle.","Senatoren hatten Einfluss auf die Regierung.","Der römische Senat bestand über Jahrhunderte."]
      ],
      ontdekkingsreizigers: [
        ["Was machte ein Entdecker?","Neue Gebiete erforschen",["Planeten bauen","Strom erfinden","Pyramiden bewachen"],"Denk an lange Reisen.","Entdecker reisten in unbekannte Gegenden.","Ihre Reisen veränderten Karten und Handel."],
        ["Wofür nutzten Seeleute einen Kompass?","Um die Richtung zu finden",["Um zu kochen","Um zu schreiben","Um die Tiefe zu messen"],"Die Nadel zeigt etwa nach Norden.","Ein Kompass hilft bei der Navigation.","Er machte lange Seereisen zuverlässiger."],
        ["Was ist eine Seekarte?","Eine Karte für die Fahrt auf dem Meer",["Ein Gemälde","Ein Ritterwappen","Ein Sternbild"],"Schiffe planten damit ihre Route.","Seekarten zeigen Küsten, Gefahren und Routen.","Moderne Schiffe nutzen oft digitale Karten."],
        ["Warum waren Sterne für Seeleute nützlich?","Sie helfen, die Position zu bestimmen",["Um Fische anzulocken","Um Wind zu machen","Um Wasser zu wärmen"],"Besonders nachts gaben sie die Richtung.","Sterne konnten bei der Navigation helfen.","Der Polarstern war auf der Nordhalbkugel wichtig."],
        ["Was war eine Karavelle?","Eine Art Segelschiff",["Ein römisches Bad","Eine Burg","Ein Tempel"],"Sie wurde für lange Reisen benutzt.","Karavellen waren wendige Segelschiffe.","Sie spielten bei den europäischen Entdeckungsreisen eine Rolle."],
        ["Warum nahmen Entdecker Vorräte mit?","Weil Reisen lange dauern konnten",["Weil es auf dem Meer Läden gab","Als Schmuck","Um Sterne zu bauen"],"Auf dem Meer konnte man nicht einfach einkaufen.","Essen und Wasser waren auf langen Reisen entscheidend.","Mangel und Krankheit waren ernste Gefahren."],
        ["Was ist Navigation?","Herausfinden, wo du bist und wohin du fährst",["Ein Schiff anmalen","Eine Sprache lernen","Einen Markt bauen"],"Kompass und Karten helfen dabei.","Navigation heißt, eine Route zu planen und zu halten.","GPS ist eine moderne Form der Navigation."],
        ["Was war eine große Gefahr auf langen Seereisen?","Stürme und Krankheiten",["Verkehrsampeln","Schnee in der Wüste","Satelliten"],"Reisen dauerten manchmal Monate.","Stürme, Krankheit und Essensmangel waren gefährlich.","Skorbut kam von langem Mangel an Vitamin C."],
        ["Warum suchte man neue Wege nach Asien?","Für den Handel mit wertvollen Waren",["Zum Skifahren","Für Dinosaurier","Für die Raumfahrt"],"Gewürze waren extrem wertvoll.","Handel trieb viele Entdeckungsreisen an.","Gewürze konnten in Europa sehr teuer sein."],
        ["Was machten Kartenmacher nach neuen Reisen?","Ihre Karten verbessern",["Pyramiden aufrichten","Sterne verschieben","Die Zeit ändern"],"Neues Wissen kam hinzu.","Reiseberichte machten Karten genauer.","Karten wurden über die Jahrhunderte immer genauer."]
      ]
    },
    wetenschap: {
      slimme_proefjes: [
        ["Was passiert oft, wenn du Backpulver und Essig mischst?","Es entstehen Gasbläschen",["Es friert sofort","Es wird zu Metall","Es passiert nichts"],"Du siehst viel Schäumen.","Bei der Reaktion entsteht unter anderem Kohlendioxid.","Dieses Gas kann zum Beispiel einen Luftballon aufblasen."],
        ["Warum trägst du bei manchen Versuchen eine Schutzbrille?","Um deine Augen zu schützen",["Um besser zu hören","Um schneller zu rennen","Wegen der Farbe"],"Manche Stoffe können spritzen.","Eine Schutzbrille schützt deine Augen.","Sicher arbeiten gehört zur Wissenschaft."],
        ["Was ist eine Hypothese?","Eine überprüfbare Erwartung",["Eine feststehende Tatsache","Ein Messgerät","Eine Flüssigkeit"],"Du überlegst vorher, was du erwartest.","Eine Hypothese ist eine Vorhersage, die man untersuchen kann.","Nach einem Versuch kann sie bestätigt werden oder nicht."],
        ["Was solltest du bei einem fairen Versuch möglichst gleich halten?","Die anderen Bedingungen",["Das Ergebnis","Die Frage","Deinen Namen"],"Du willst immer nur eine Sache verändern.","Gleiche Bedingungen machen einen Versuch fairer.","So weißt du besser, was eine Wirkung verursacht hat."],
        ["Womit misst du eine Flüssigkeitsmenge genau?","Mit einem Messzylinder",["Mit einer Lupe","Mit einem Kompass","Mit einer Stoppuhr"],"Er hat Striche an der Seite.","Ein Messzylinder misst das Volumen.","Volumen wird oft in Millilitern gemessen."],
        ["Was macht ein Thermometer bei einem Versuch?","Es misst die Temperatur",["Es misst die Zeit","Es misst das Gewicht","Es macht Licht"],"Damit kannst du warm oder kalt messen.","Ein Thermometer misst die Temperatur.","Bei uns misst man oft in Grad Celsius."],
        ["Warum schreibst du die Ergebnisse eines Versuchs auf?","Damit du sie vergleichen kannst",["Um sie zu vergessen","Um das Glas zu putzen","Als Schmuck"],"Forscher notieren ihre Messungen.","Aufschreiben hilft beim Auswerten und Wiederholen.","Gute Wissenschaft muss überprüfbar sein."],
        ["Was passiert mit Eis, wenn du es erwärmst?","Es schmilzt",["Es wird zu Stein","Es verschwindet sofort","Es wird schwerer"],"Festes Wasser wird flüssig.","Eis schmilzt zu Wasser.","Bei normalem Druck schmilzt Eis bei etwa 0 °C."],
        ["Was brauchst du, um einen Schatten zu machen?","Eine Lichtquelle und einen Gegenstand",["Geräusch","Wasser","Wind"],"Der Gegenstand hält das Licht auf.","Ein Schatten entsteht, wenn Licht aufgehalten wird.","Seine Größe ändert sich mit dem Abstand zur Lichtquelle."],
        ["Was ist Auflösen, wie Zucker in Wasser?","Der Stoff verteilt sich in der Flüssigkeit",["Der Stoff verlässt die Welt","Der Stoff wird zu Feuer","Die Flüssigkeit friert"],"Du siehst die Körnchen nicht mehr einzeln.","Aufgelöste Teilchen verteilen sich in der Flüssigkeit.","Durch Verdampfen bekommst du den Zucker oft zurück."]
      ],
      lichaam: [
        ["Welches Organ pumpt Blut durch deinen Körper?","Das Herz",["Die Lungen","Der Magen","Das Gehirn"],"Du kannst es schlagen spüren.","Das Herz pumpt das Blut herum.","Dein Herz schlägt etwa hunderttausend Mal am Tag."],
        ["Womit atmest du vor allem?","Mit den Lungen",["Mit den Nieren","Mit dem Magen","Mit den Knochen"],"Sie liegen in deinem Brustkorb.","Die Lungen nehmen Sauerstoff auf.","Normalerweise hast du zwei Lungen."],
        ["Welches Organ hilft dir beim Denken?","Das Gehirn",["Die Leber","Das Herz","Der Darm"],"Es liegt in deinem Schädel.","Das Gehirn verarbeitet Informationen und steuert viele Körperfunktionen.","Dort arbeiten Milliarden Nervenzellen zusammen."],
        ["Was bringt das Blut durch deinen Körper?","Sauerstoff und Nährstoffe",["Luft","Knochen","Wärme"],"Blut fließt durch die Blutgefäße.","Blut transportiert unter anderem Sauerstoff und Nährstoffe.","Rote Blutkörperchen helfen beim Sauerstofftransport."],
        ["Wo beginnt das Verdauen von Essen schon?","Im Mund",["Im Fuß","In der Lunge","Im Ohr"],"Du kaust das Essen in kleine Stücke.","Die Verdauung beginnt im Mund.","Speichel enthält Stoffe, die das Essen zerlegen helfen."],
        ["Was schützen deine Rippen?","Herz und Lungen",["Deine Füße","Deine Zähne","Deine Finger"],"Sie bilden einen Korb um den Brustkorb.","Rippen schützen wichtige Organe.","Die meisten Menschen haben 12 Rippenpaare."],
        ["Wofür sind Knochen außer für Halt noch da?","Für Schutz und Bewegung",["Für Farbe","Für Schlaf","Für Temperatur"],"Muskeln ziehen an Knochen.","Knochen geben Halt und Schutz und helfen bei der Bewegung.","Im Knochenmark werden Blutzellen gebildet."],
        ["Was machen Muskeln?","Sie ziehen sich zusammen und erzeugen Bewegung",["Sie machen nur Blut","Sie verdauen Essen","Sie sehen Licht"],"Muskeln arbeiten oft mit Knochen zusammen.","Muskeln können sich zusammenziehen und so Bewegung erzeugen.","Dein Körper hat Hunderte Muskeln."],
        ["Was ist die Haut?","Das größte Organ deines Körpers",["Ein Knochen","Ein Muskel","Ein Blutgefäß"],"Sie bedeckt deinen ganzen Körper.","Die Haut schützt den Körper.","Die Haut hilft auch, die Temperatur zu regeln."],
        ["Welchen Sinn benutzt du mit den Ohren?","Das Hören",["Das Schmecken","Das Riechen","Das Sehen"],"Du nimmst Schallwellen auf.","Mit den Ohren nimmst du Geräusche wahr.","Dein Innenohr hilft auch beim Gleichgewicht."]
      ],
      uitvindingen: [
        ["Womit kannst du sehr kleine Dinge anschauen?","Mit einem Mikroskop",["Mit einem Teleskop","Mit einem Kompass","Mit einem Barometer"],"Denk an Zellen und Bakterien.","Ein Mikroskop vergrößert kleine Dinge.","Moderne Mikroskope können extrem stark vergrößern."],
        ["Womit schaust du zu fernen Sternen und Planeten?","Mit einem Teleskop",["Mit einem Mikroskop","Mit einem Thermometer","Mit einem Magneten"],"Es macht ferne Dinge besser sichtbar.","Ein Teleskop sammelt Licht von fernen Objekten.","Es gibt Teleskope auf der Erde und im Weltall."],
        ["Welche Erfindung machte das Vervielfältigen von Büchern viel schneller?","Die Druckerpresse",["Der Kompass","Die Dampfpfeife","Die Fackel"],"Text konnte mit beweglichen Buchstaben gedruckt werden.","Die Druckerpresse machte viele Bücher auf einmal möglich.","So verbreitete sich Wissen schneller."],
        ["Wofür dient eine Batterie?","Zum Speichern und Abgeben elektrischer Energie",["Zum Messen von Wind","Zum Kochen ohne Energie","Zum Sternemachen"],"Du findest eine in vielen Geräten.","Eine Batterie liefert elektrische Energie.","Aufladbare Akkus kann man wieder benutzen."],
        ["Was macht ein Magnet?","Er kann bestimmte Metalle anziehen",["Er macht immer Licht","Er friert Wasser ein","Er hält die Zeit an"],"Eisen reagiert gut darauf.","Magnete üben Kräfte auf magnetische Stoffe aus.","Ein Magnet hat einen Nordpol und einen Südpol."],
        ["Was macht ein Solarmodul?","Strom aus Licht",["Regen aus Wolken","Benzin aus Luft","Geräusche aus Steinen"],"Die Sonne liefert die Energie.","Solarzellen machen aus Licht Strom.","Solarmodule brauchen keine beweglichen Teile."],
        ["Was macht ein Motor?","Er macht aus Energie Bewegung",["Er macht Farben","Er friert Wasser ein","Er liest Papier"],"Autos und Maschinen benutzen Motoren.","Ein Motor wandelt Energie in Bewegung um.","Es gibt Elektromotoren und Verbrennungsmotoren."],
        ["Warum war das Telefon eine wichtige Erfindung?","Menschen konnten über weite Strecken sprechen",["Menschen konnten fliegen","Menschen konnten die Zeit anhalten","Menschen konnten ohne Strom leben"],"Töne wurden über eine Entfernung geschickt.","Das Telefon veränderte die Kommunikation sehr.","Handys verbinden heute viele Funktionen."],
        ["Was macht ein Computer vor allem?","Er verarbeitet Informationen",["Er macht Musik","Er gibt Licht","Er reinigt Wasser"],"Er führt Befehle aus.","Computer verarbeiten Daten nach Programmen.","Sogar in einer Smartwatch steckt ein Computer."],
        ["Welche Erfindung nutzt Funkwellen, um den Ort zu bestimmen?","GPS",["Der Magnet","Das Mikroskop","Das Stethoskop"],"Satelliten helfen herauszufinden, wo du bist.","GPS nutzt Signale von Satelliten.","Dein Handy nutzt GPS für die Navigation."]
      ],
      natuur_energie: [
        ["Welche Energiequelle nutzt bewegte Luft?","Windenergie",["Sonnenenergie","Erdgas","Kernenergie"],"Windräder drehen sich dadurch.","Windräder machen aus Wind Strom.","Große Windräder können viele Haushalte versorgen."],
        ["Welche Energiequelle nutzt Sonnenlicht?","Sonnenenergie",["Kohle","Öl","Erdgas"],"Module fangen das Licht auf.","Solarmodule machen aus Licht Strom.","Die Sonne liefert viel mehr Energie, als wir weltweit verbrauchen."],
        ["Was ist erneuerbare Energie?","Energie aus Quellen, die sich immer wieder auffüllen",["Energie, die nie benutzt wird","Benzin","Kohle"],"Denk an Sonne und Wind.","Erneuerbare Quellen gehen nicht schnell zur Neige.","Auch Wasserkraft und Erdwärme können erneuerbar sein."],
        ["Was macht ein Windrad?","Es macht aus Wind Strom",["Es macht Regen","Es macht Benzin","Es schiebt Wolken"],"Die Flügel drehen sich im Wind.","Ein Generator im Windrad macht Strom.","Windräder stehen an Land und auf dem Meer."],
        ["Welcher Stoff wird frei, wenn fossile Brennstoffe verbrennen?","Kohlendioxid",["Sauerstoff","Gold","Helium"],"Es ist ein Treibhausgas.","Beim Verbrennen von Öl, Gas und Kohle wird CO₂ frei.","Mehr CO₂ verstärkt den Treibhauseffekt."],
        ["Warum dämmen wir Häuser?","Um Wärme besser drinnen oder draußen zu halten",["Um Fenster schwerer zu machen","Um Wasser zu machen","Um das WLAN zu verstärken"],"Gute Dämmung spart Energie.","Dämmung verringert den Wärmeverlust.","Dach, Wände und Böden kann man alle dämmen."],
        ["Was ist Wasserkraft?","Energie aus fließendem oder fallendem Wasser",["Energie aus Sand","Energie aus Rauch","Energie aus Plastik"],"Ein Staudamm und ein Fluss können Turbinen antreiben.","Wasserkraft nutzt die Bewegung von Wasser.","Weltweit ist sie eine wichtige erneuerbare Quelle."],
        ["Was ist Energiesparen?","Weniger Energie für das gleiche Ergebnis benutzen",["Mehr Lampen einschalten","Fenster offen und Heizung an","Geräte laufen lassen"],"Sparsame Geräte helfen.","Energiesparen senkt den Verbrauch.","LED-Lampen brauchen weniger Strom als alte Glühbirnen."],
        ["Was macht der Akku in einem Elektroauto?","Er speichert elektrische Energie",["Er macht Benzin","Er misst Wind","Er kühlt Wasser"],"Er versorgt den Elektromotor.","Der Akku speichert Energie für die Fahrt.","Beim Bremsen kann manchmal Energie zurückgewonnen werden."],
        ["Welche Lampe ist meistens sparsamer?","Die LED-Lampe",["Die Glühbirne","Die Kerze","Die Halogenlampe"],"Sie braucht weniger Strom.","LED-Licht ist sehr energiesparend.","LED-Lampen halten oft auch länger."]
      ]
    },
    mysterie: {
      raadsels: [
        ["Ich habe schwarze und weiße Tasten und mache Musik. Was bin ich?","Klavier",["Tür","Schatzkiste","Fahrrad"],"Du spielst mich mit den Fingern.","Ein Klavier hat Tasten, die du drückst.","Ein Klavier kann mehr als achtzig Tasten haben."],
        ["Ich werde nasser, je mehr ich trockne. Was bin ich?","Handtuch",["Regenschirm","Sonne","Schwamm"],"Du benutzt mich nach dem Waschen.","Ein Handtuch wird nass, während es dich trocken macht.","Handtücher saugen Wasser mit ihren Fasern auf."],
        ["Was hat einen Hals, aber keinen Kopf?","Flasche",["Katze","Mensch","Eule"],"Daraus kannst du trinken.","Eine Flasche hat einen Hals.","Flaschen sind aus Glas oder Plastik."],
        ["Was hat Zähne, kann aber nicht beißen?","Kamm",["Haifisch","Hund","Löwe"],"Du benutzt ihn für die Haare.","Ein Kamm hat Zähne, aber keinen Mund.","Kämme gibt es schon seit Tausenden Jahren."],
        ["Was wird immer größer und nie kleiner?","Dein Alter",["Ein Aufzug","Ein Ball","Ein Vogel"],"Jedes Jahr wird es mehr.","Dein Alter wird größer, wenn du älter wirst.","An deinem Geburtstag kommt ein Jahr dazu."],
        ["Ich habe ein Gesicht und Zeiger, aber ich kann nicht winken. Was bin ich?","Uhr",["Roboter","Mensch","Affe"],"Meine Zeiger zeigen auf etwas.","Eine Zeigeruhr hat ein Ziffernblatt und Zeiger.","Die Zeiger zeigen Stunden, Minuten und manchmal Sekunden."],
        ["Was kannst du brechen, ohne es anzufassen?","Ein Versprechen",["Einen Stein","Ein Glas","Einen Zweig"],"Es geht um Vertrauen.","Ein Versprechen kannst du brechen, ohne etwas anzufassen.","Rätsel spielen oft mit doppelten Bedeutungen."],
        ["Ich habe ein Öhr, aber ich kann nicht hören. Was bin ich?","Nadel",["Eule","Mensch","Kamera"],"Durch mein Öhr geht ein Faden.","Eine Nadel hat ein Öhr für den Faden.","Das Öhr ist meist an einem Ende."],
        ["Was wird größer, je mehr du wegnimmst?","Ein Loch",["Ein Berg","Eine Kiste","Ein Buch"],"Denk an Graben.","Je mehr du aus einem Loch nimmst, desto größer wird es.","Das ist ein klassisches Denkrätsel."],
        ["Was läuft, hat aber keine Beine?","Wasser",["Hund","Mensch","Pferd"],"Es fließt durch Flüsse.","Wasser kann laufen, ohne Beine zu haben.","Sprachrätsel spielen mit mehreren Bedeutungen."]
      ],
      verborgen_schatten: [
        ["Womit öffnest du eine verschlossene Schatzkiste?","Mit einem Schlüssel",["Mit einer Feder","Mit einer Karte","Mit einer Lupe"],"Er passt in ein Schloss.","Mit dem richtigen Schlüssel öffnest du das Schloss.","Schlösser gibt es schon seit Tausenden Jahren."],
        ["Was steht oft auf einer Schatzkarte?","Ein X für die Stelle",["Eine Verkehrsampel","Ein Strichcode","Ein Thermometer"],"Ein X markiert den Platz.","Ein X markiert oft die Stelle mit dem Schatz.","Am bekanntesten ist das aus Piratengeschichten."],
        ["Wofür nutzt du bei einer Schatzsuche einen Kompass?","Um die Richtung zu finden",["Um Gold zu wiegen","Um Regen zu machen","Um Löcher zu graben"],"Die Nadel hilft dir, den Norden zu finden.","Ein Kompass hilft bei der Navigation.","Ein normaler Kompass reagiert auf das Magnetfeld der Erde."],
        ["Was ist ein Geheimfach?","Ein verborgener Raum in einem Gegenstand",["Ein offener Platz","Eine Wolke","Eine Kartenlegende"],"Du siehst es nicht gleich.","In einem Geheimfach kann man Dinge verstecken.","Alte Möbel hatten manchmal Geheimfächer."],
        ["Was ist ein Hinweis?","Eine Information, die dich der Lösung näher bringt",["Immer die Endantwort","Ein Fehler","Ein Schmuckstück"],"Ein Detektiv sucht danach.","Hinweise helfen, ein Geheimnis zu lösen.","Ein guter Hinweis gibt etwas, aber nicht alles."],
        ["Warum nummerierst du deine Hinweise manchmal?","Um sie in der richtigen Reihenfolge zu halten",["Um sie schwerer zu machen","Um sie zu verstecken","Um Farben zu ändern"],"So verlierst du weniger schnell den Überblick.","Nummerieren hilft beim Ordnen.","Detektive ordnen Beweise, um Zusammenhänge zu sehen."],
        ["Welcher Ort ist in einer Geschichte für einen Schatz sinnvoll?","Unter einem markierten Stein",["Mitten auf einem belebten Tisch","Auf einem Verkehrsschild","In einer Wolke"],"Er muss außer Sicht sein.","In Geschichten liegen Schätze oft an geheimen Orten.","Schatzgeschichten nutzen oft bekannte Zeichen."],
        ["Was ist ein Code?","Ein System, Informationen versteckt darzustellen",["Eine Obstsorte","Ein Musikinstrument","Eine Wolke"],"Du musst ihn entschlüsseln.","Ein Code kann Informationen verstecken.","Kryptografie ist die Wissenschaft der geheimen Nachrichten."],
        ["Was bedeutet entschlüsseln?","Einen Code verständlich machen",["Etwas begraben","Eine Karte verbrennen","Einen Schlüssel fälschen"],"Du suchst die Bedeutung hinter den Zeichen.","Entschlüsseln heißt, verschlüsselte Informationen lesen.","Manche Codes benutzen Zahlen oder Symbole."],
        ["Warum hätte eine Schatzkarte eine Legende?","Um die Zeichen zu erklären",["Um die Karte schwerer zu machen","Um Geräusche zu machen","Um sie wasserfest zu machen"],"Eine Legende sagt dir, was die Zeichen bedeuten.","Kartenlegenden erklären Symbole.","Auch normale Karten haben Legenden."]
      ],
      natuurmysteries: [
        ["Warum wird aus einer Raupe ein Schmetterling?","Durch Metamorphose",["Durch Magnetismus","Durch Blitze","Durch Frost"],"Das Tier verändert sich in verschiedenen Lebensstufen.","Schmetterlinge machen eine Metamorphose durch.","Vom Ei geht es über Raupe und Puppe zum Schmetterling."],
        ["Warum sehen wir manchmal einen Regenbogen?","Licht wird in Wassertropfen gebrochen und aufgeteilt",["Die Wolken malen sich an","Die Sonne blinkt","Der Mond malt ihn"],"Sonnenlicht und Regen arbeiten zusammen.","Wassertropfen brechen und spiegeln das Licht.","Ein Regenbogen erscheint gegenüber der Sonne."],
        ["Warum leuchtet ein Glühwürmchen?","Durch Biolumineszenz",["Durch eine Batterie","Weil es Sonnenlicht speichert","Durch Magnete"],"Es macht Licht in seinem eigenen Körper.","Biolumineszenz ist Licht aus einer chemischen Reaktion.","Manche Meerestiere können auch selbst leuchten."],
        ["Warum sind Flamingos rosa?","Wegen Farbstoffen in ihrem Futter",["Weil sie angemalt geboren werden","Nur vom Sonnenlicht","Von kaltem Wasser"],"In ihrem Essen stecken Farbstoffe.","Karotinoide im Futter färben die Federn rosa.","Junge Flamingos sind viel grauer."],
        ["Warum drehen sich junge Sonnenblumenknospen oft mit der Sonne?","Durch Heliotropismus",["Durch Windkraft","Durch Magnetismus","Durch Regen"],"Sie reagieren auf Licht.","Junge Sonnenblumen können der Sonne folgen.","Ausgewachsene Blüten schauen meist nach Osten."],
        ["Warum haben manche Tiere eine Tarnung?","Um weniger aufzufallen",["Um schneller zu wachsen","Um lauter zu singen","Um mehr Wärme zu machen"],"Farbe und Muster passen zur Umgebung.","Tarnung hilft beim Jagen oder Verstecken.","Tintenfische können ihr Aussehen sehr schnell ändern."],
        ["Was verursacht vor allem Ebbe und Flut?","Die Schwerkraft des Mondes",["Windräder","Vulkane","Wolken"],"Der Mond zieht am Meerwasser.","Der Mond ist eine wichtige Ursache für Ebbe und Flut.","Auch die Sonne beeinflusst die Gezeiten."],
        ["Warum sind Schneeflocken oft sechseckig?","Wegen der Art, wie Wassermoleküle Kristalle bilden",["Wegen Windrädern","Wegen Vögeln","Wegen Sand"],"Eis bildet ein festes Kristallmuster.","Der Aufbau von Eis führt oft zu sechszähliger Symmetrie.","Keine zwei großen Schneeflocken sind genau gleich."],
        ["Warum ist der Himmel tagsüber meistens blau?","Blaues Licht wird stärker gestreut",["Weil der Ozean den Himmel färbt","Wegen der Bäume","Nur wegen der Wolken"],"Sonnenlicht enthält mehrere Farben.","Die Atmosphäre streut kurzwelliges blaues Licht stark.","Beim Sonnenuntergang sehen wir mehr Rot und Orange."],
        ["Warum können Geckos an Wänden hochlaufen?","Millionen winzige Haare an ihren Zehen",["Saugnäpfe mit Klebstoff","Magnete","Strom"],"Ihre Zehen haben sehr viel Kontakt mit der Fläche.","Winzige Strukturen geben sehr viel Halt.","Diese Kräfte heißen Van-der-Waals-Kräfte."]
      ],
      speurtocht: [
        ["Wofür nutzt du eine Routenkarte?","Um dem Weg zu folgen",["Um ein Puzzle zu essen","Um die Zeit zu messen","Um Geräusche zu machen"],"Die Karte zeigt, wohin du musst.","Eine Routenkarte hilft bei der Navigation.","Symbole können wichtige Punkte markieren."],
        ["Was ist ein Wegpunkt?","Ein festgelegter Punkt auf einer Route",["Ein geheimes Passwort","Eine Tierart","Eine Münze"],"Du kannst ihn ansteuern.","Wegpunkte markieren Orte auf einer Route.","GPS-Geräte nutzen oft Wegpunkte."],
        ["Welches Werkzeug hilft dir, kleine Spuren besser zu sehen?","Die Lupe",["Der Hammer","Der Löffel","Der Regenschirm"],"Sie macht Einzelheiten größer.","Eine Lupe vergrößert kleine Einzelheiten.","Eine gewölbte Linse bricht die Lichtstrahlen."],
        ["Ein Fußabdruck ist vor allem eine…","Spur",["Planet","Instrument","Farbe"],"Ein Detektiv sucht danach.","Ein Fußabdruck kann eine Spur sein.","Spuren können verraten, wer wo war."],
        ["Warum schaust du bei einer Schatzsuche genau umher?","Hinweise können versteckt sein",["Um die Zeit anzuhalten","Um Regen zu machen","Um schneller zu wachsen"],"Nicht alles liegt mitten auf dem Weg.","Genau hinschauen ist bei einer Suche wichtig.","Gute Suchen verbinden Schauen, Denken und Laufen."],
        ["Was bedeutet „nach links“ auf einer Route?","Zur linken Seite abbiegen",["Geradeaus","Zurück nach Hause","Nach oben klettern"],"Denk an deine linke Hand.","Nach links heißt, nach links abbiegen.","Richtungswörter sind bei der Navigation wichtig."],
        ["Was ist eine Koordinate?","Eine Art, einen Ort genau anzugeben",["Eine Art Schlüssel","Eine Tierspur","Eine Belohnung"],"Karten und GPS benutzen sie.","Koordinaten beschreiben eine Position.","Breite und Länge sind Beispiele."],
        ["Was machst du, wenn zwei Hinweise sich widersprechen?","Beide noch einmal prüfen",["Einfach einen auswählen","Alles wegwerfen","Die Karte zerreißen"],"Vielleicht hast du etwas falsch gelesen.","Prüfen hilft, Fehler zu finden.","Gute Sucher überprüfen ihre Informationen."],
        ["Warum ist Zusammenarbeiten bei einer Schatzsuche nützlich?","Man kann Ideen und Beobachtungen verbinden",["Weil einer nichts tun darf","Um Hinweise zu verstecken","Um die Zeit anzuhalten"],"Zwei Augenpaare sehen mehr.","Zusammenarbeit kann Probleme schneller lösen.","Teams teilen sich oft die Aufgaben."],
        ["Wozu dient der letzte Hinweis?","Er führt dich zum letzten Ort",["Er schickt dich zurück zu Frage 1","Er macht eine neue Welt","Er löscht die Route"],"Er bringt dich zur Lösung.","Der letzte Hinweis führt meist zum Ziel oder zum Schatz.","Eine gute Suche baut Schritt für Schritt auf das Ende hin."]
      ]
    },
    dieren: {
      snelle_dieren: [
        ["Welches Landtier ist das schnellste?","Gepard",["Elefant","Panda","Flusspferd"],"Es ist eine schlanke gefleckte Katze.","Der Gepard ist das schnellste Landtier.","Im kurzen Sprint kann er über 90 km/h kommen."],
        ["Welches Tier ist für schnelle Sprints gebaut?","Gepard",["Faultier","Schildkröte","Panda"],"Lange Beine und ein leichter Körper helfen.","Geparde sind echte Sprinter.","Ihre Höchstgeschwindigkeit halten sie nur kurz."],
        ["Welcher Vogel ist für extrem schnelle Sturzflüge berühmt?","Wanderfalke",["Pinguin","Huhn","Strauß"],"Er jagt aus der Luft.","Der Wanderfalke ist eines der schnellsten Tiere.","Im Sturzflug kann er über 300 km/h erreichen."],
        ["Warum hat ein schneller Fisch einen stromlinienförmigen Körper?","Um weniger Widerstand zu haben",["Um schwerer zu sein","Um lauter zu singen","Um mehr Luft zu fangen"],"Eine glatte Form schneidet leichter durchs Wasser.","Stromlinienform verringert den Wasserwiderstand.","Auch Delfine haben eine stromlinienförmige Gestalt."],
        ["Wer läuft schneller: ein Pferd oder eine Schildkröte?","Das Pferd",["Die Schildkröte","Gleich schnell","Keines von beiden"],"Es hat lange kräftige Beine.","Ein Pferd ist viel schneller als eine Schildkröte.","Im Galopp erreichen Pferde hohe Geschwindigkeiten."],
        ["Warum haben Gazellen lange Beine?","Um schnell zu laufen und zu springen",["Um zu schwimmen","Um zu graben","Um zu fliegen"],"Sie leben in offenen Steppen.","Lange Beine helfen Gazellen, schnell zu flüchten.","Schnelligkeit hilft ihnen, Raubtieren zu entkommen."],
        ["Welcher Haifisch ist als schneller Schwimmer bekannt?","Makohai",["Walhai","Seepferdchen","Rotfeuerfisch"],"Er hat einen stromlinienförmigen Körper.","Makohaie gehören zu den schnellsten Haien.","Sie jagen schnelle Fische."],
        ["Was hilft einem Strauß, schnell zu laufen?","Kräftige lange Beine",["Flügel zum Fliegen","Eine Schwimmblase","Krallen zum Klettern"],"Er kann nicht fliegen.","Strauße sind schnelle Läufer.","Sie laufen mit mehreren Dutzend Kilometern pro Stunde."],
        ["Warum ist Schnelligkeit für Beutetiere nützlich?","Um zu entkommen",["Um Bäume wachsen zu lassen","Um Kälte zu machen","Um zu schlafen"],"Raubtiere versuchen, sie zu fangen.","Schnelligkeit kann ihre Überlebenschance verbessern.","Manche Beutetiere machen auch scharfe Wendungen."],
        ["Warum ist Schnelligkeit für Raubtiere nützlich?","Um Beute zu fangen",["Um Pflanzen zu gießen","Um Federn zu färben","Um Nester zu bauen"],"Eine Jagd ist oft sehr kurz.","Schnelligkeit hilft bei der Verfolgung.","Nicht jedes Raubtier nutzt Schnelligkeit; manche lauern."]
      ],
      baby_dieren: [
        ["Wie heißt ein Hundebaby?","Welpe",["Kalb","Fohlen","Küken"],"Das Wort beginnt mit W.","Ein junger Hund heißt Welpe.","Welpen werden blind und taub geboren."],
        ["Wie heißt ein Katzenbaby?","Kätzchen",["Fohlen","Lamm","Kalb"],"Es ist eine junge Katze.","Eine junge Katze heißt Kätzchen.","Kätzchen schlafen sehr viel."],
        ["Wie heißt ein junges Pferd?","Fohlen",["Welpe","Küken","Junges"],"Es kann schnell aufstehen.","Ein junges Pferd heißt Fohlen.","Fohlen versuchen kurz nach der Geburt zu stehen."],
        ["Wie heißt ein junges Schaf?","Lamm",["Kalb","Welpe","Kätzchen"],"Du siehst sie oft im Frühling.","Ein junges Schaf heißt Lamm.","Lämmer trinken Milch von ihrer Mutter."],
        ["Wie heißt ein Kuhbaby?","Kalb",["Fohlen","Lamm","Küken"],"Ein junger Elefant heißt auch so.","Eine junge Kuh heißt Kalb.","Kälber trinken zuerst Milch."],
        ["Wie heißt ein junges Huhn?","Küken",["Junges","Welpe","Lamm"],"Es kommt aus einem Ei.","Ein junges Huhn heißt Küken.","Küken piepen schon, bevor sie schlüpfen."],
        ["Wie heißt ein junger Löwe?","Löwenjunges",["Fohlen","Kalb","Kätzchen"],"Junge Wölfe heißen auch so.","Ein junger Löwe ist ein Löwenjunges.","Löwenjunge bleiben lange bei der Gruppe."],
        ["Was trinken viele Säugetierbabys zuerst?","Milch",["Salzwasser","Benzin","Limonade"],"Ihre Mutter macht sie.","Säugetiere füttern ihre Jungen mit Milch.","Das ist ein wichtiges Merkmal von Säugetieren."],
        ["Warum bleiben viele Jungtiere bei ihrer Mutter?","Für Schutz und Futter",["Um schneller zu fliegen","Um Bäume zu klettern","Um Kälte zu machen"],"Sie müssen noch viel lernen.","Eltern schützen und versorgen ihre Jungen oft.","Wie lange das dauert, ist je nach Tierart sehr verschieden."],
        ["Welches Tierbaby kommt aus einem Ei?","Küken",["Welpe","Kalb","Fohlen"],"Denk an ein Huhn.","Ein Küken kommt aus einem Ei.","Auch Reptilien, Fische und viele andere Tiere legen Eier."]
      ],
      waterdieren: [
        ["Welches Säugetier lebt im Meer und atmet Luft?","Delfin",["Thunfisch","Haifisch","Qualle"],"Es muss regelmäßig nach oben.","Delfine sind Säugetiere und atmen mit Lungen.","Sie benutzen ein Blasloch oben auf dem Kopf."],
        ["Welches Tier hat acht Arme?","Krake",["Haifisch","Delfin","Krabbe"],"Es kann sich sehr gut verstecken.","Eine Krake hat acht Arme.","Kraken sind sehr schlaue Weichtiere."],
        ["Welches Meerestier ist das größte Tier der Erde?","Blauwal",["Weißer Hai","Delfin","Orca"],"Es ist ein riesiger Wal.","Der Blauwal ist das größte bekannte Tier.","Er kann über 25 Meter lang werden."],
        ["Wie atmen die meisten Fische?","Mit Kiemen",["Mit Lungen","Durch die Haut","Mit Federn"],"Sie holen Sauerstoff aus dem Wasser.","Kiemen nehmen Sauerstoff aus dem Wasser auf.","Das Wasser strömt an den Kiemenblättchen vorbei."],
        ["Was hilft Fischen beim Steuern und Schwimmen?","Flossen",["Flügel","Beine","Haare"],"Sie haben mehrere verschiedene Flossen.","Flossen helfen bei Bewegung und Gleichgewicht.","Die Schwanzflosse gibt oft viel Schub."],
        ["Welches Tier kann im Meer und auf dem Land leben?","Meeresschildkröte",["Thunfisch","Qualle","Seepferdchen"],"Es kommt an Land, um Eier zu legen.","Meeresschildkröten leben im Meer, legen Eier aber an Land.","Weibchen kommen oft an den Strand zurück, an dem sie schlüpften."],
        ["Was ist Korallen eigentlich?","Eine Kolonie kleiner Tiere",["Eine Pflanze","Ein Stein","Ein Fisch"],"Sie bildet Riffe.","Korallen bestehen aus sehr vielen kleinen Polypen.","Korallenriffe sind wichtige Lebensräume."],
        ["Warum kommen Wale an die Oberfläche?","Um zu atmen",["Um die Kiemen zu waschen","Um am Strand zu schlafen","Um Essen zu kochen"],"Sie sind Säugetiere.","Wale atmen Luft mit Lungen.","Sie atmen durch Blaslöcher."],
        ["Welches Tier hat einen harten Panzer und läuft seitwärts?","Krabbe",["Delfin","Qualle","Tintenfisch"],"Du siehst sie oft an Stränden.","Krabben haben ein hartes Außenskelett.","Viele Krabben bewegen sich leicht seitwärts."],
        ["Warum ist ein stromlinienförmiger Körper im Wasser nützlich?","Er verringert den Widerstand",["Er macht mehr Geräusch","Er macht das Tier schwerer","Er wärmt das Wasser"],"Tiere gleiten leichter durchs Wasser.","Stromlinienform hilft beim sparsamen Schwimmen.","Delfine und Haie sind gute Beispiele."]
      ],
      jungle: [
        ["Welches Tier schwingt sich oft durch die Bäume?","Affe",["Elefant","Pinguin","Zebra"],"Es klettert an Ästen.","Viele Affenarten leben in Bäumen.","Manche Affen nutzen ihren Schwanz als zusätzlichen Halt."],
        ["Welches Tier hat einen großen bunten Schnabel?","Tukan",["Tiger","Gorilla","Krokodil"],"Es ist ein tropischer Vogel.","Tukane haben auffällige Schnäbel.","Ihr Schnabel ist überraschend leicht."],
        ["Welches große Tier lebt in tropischen Wäldern und frisst viele Pflanzen?","Gorilla",["Pinguin","Kamel","Eisbär"],"Es ist ein Menschenaffe.","Gorillas leben in afrikanischen Wäldern.","Sie fressen vor allem Pflanzen."],
        ["Warum haben viele Dschungeltiere eine Tarnung?","Um weniger aufzufallen",["Um lauter zu singen","Um mehr Regen zu machen","Um schneller zu wachsen"],"Muster passen zu Blättern und Schatten.","Tarnung hilft Tieren beim Jagen oder Verstecken.","Die Flecken vieler Jaguare sehen wie Schatten aus."],
        ["Welche große Katze lebt in den Dschungeln Amerikas?","Jaguar",["Löwe","Schneeleopard","Luchs"],"Er hat Rosetten im Fell.","Jaguare leben in Teilen Mittel- und Südamerikas.","Sie schwimmen auffallend gut."],
        ["Warum sind Regenwaldbäume so wichtig?","Sie geben Futter und Lebensraum",["Sie machen keinen Sauerstoff","Sie halten allen Regen auf","Sie sind nur Schmuck"],"Viele Tiere leben in verschiedenen Baumschichten.","Regenwaldbäume bilden reiche Lebensräume.","Manche Tiere kommen fast nie auf den Waldboden."],
        ["Welches Reptil kann die Farbe wechseln?","Chamäleon",["Schildkröte","Krokodil","Immer eine Schlange"],"Es nutzt Farbe auch zum Verständigen.","Chamäleons können ihr Farbmuster anpassen.","Der Farbwechsel hilft bei Temperatur und Signalen."],
        ["Was ist ein Regenwald?","Ein warmer Wald mit sehr viel Regen",["Eine gefrorene Wüste","Eine Grassteppe ohne Bäume","Ein Meer"],"Er ist sehr artenreich.","Tropische Regenwälder bekommen sehr viel Regen.","Sie gehören zu den artenreichsten Lebensräumen."],
        ["Warum rufen Brüllaffen so laut?","Um sich mit ihrer Gruppe zu verständigen",["Um Regen zu machen","Um Bäume umzuschieben","Um zu schwimmen"],"Ihr Ruf trägt weit durch den Wald.","Brüllaffen verständigen sich mit lauten Rufen.","Eine vergrößerte Kehlstruktur verstärkt den Ruf."],
        ["Welches Tier kann Insekten mit einer langen Zunge fangen?","Chamäleon",["Elefant","Gorilla","Tukan"],"Die Zunge schießt sehr schnell nach vorn.","Chamäleons fangen Beute mit ihrer langen Zunge.","Die Zunge kann extrem schnell beschleunigen."]
      ]
    },
    aarde: {
      continenten_landen: [
        ["Auf welchem Kontinent liegen die Niederlande?","Europa",["Afrika","Asien","Südamerika"],"Denk an die Nachbarländer.","Die Niederlande liegen in Europa.","Europa ist einer der sieben Kontinente."],
        ["Was ist der größte Kontinent?","Asien",["Europa","Afrika","Australien"],"China und Indien liegen dort.","Asien ist der größte Kontinent.","Mehr als die Hälfte aller Menschen lebt in Asien."],
        ["Auf welchem Kontinent liegt Brasilien?","Südamerika",["Afrika","Europa","Asien"],"Denk an den Amazonas.","Brasilien liegt in Südamerika.","Brasilien ist das größte Land Südamerikas."],
        ["Auf welchem Kontinent liegt der größte Teil von Ägypten?","Afrika",["Europa","Asien","Nordamerika"],"Der Nil fließt hindurch.","Ägypten liegt größtenteils in Afrika.","Die Sinai-Halbinsel gehört geografisch zu Asien."],
        ["Was ist die Hauptstadt von Frankreich?","Paris",["Rom","Madrid","Berlin"],"Dort steht der Eiffelturm.","Paris ist die Hauptstadt von Frankreich.","Die Seine fließt durch Paris."],
        ["Was ist die Hauptstadt von Italien?","Rom",["Mailand","Venedig","Neapel"],"Dort steht das Kolosseum.","Rom ist die Hauptstadt von Italien.","Die Vatikanstadt liegt mitten in Rom."],
        ["Welches Land hat die Form eines Stiefels?","Italien",["Portugal","Norwegen","Polen"],"Schau nach Südeuropa.","Italien sieht wie ein Stiefel aus.","Sizilien liegt nahe an der Stiefelspitze."],
        ["Welcher Ozean liegt zwischen Europa und Amerika?","Der Atlantische Ozean",["Der Pazifische Ozean","Der Indische Ozean","Das Nordpolarmeer"],"Schiffe fahren darüber.","Der Atlantische Ozean liegt zwischen Europa, Afrika und Amerika.","Er ist der zweitgrößte Ozean."],
        ["Welcher Kontinent liegt am Südpol?","Antarktika",["Europa","Afrika","Asien"],"Er ist mit Eis bedeckt.","Antarktika liegt rund um den Südpol.","Es ist der kälteste Kontinent."],
        ["Welches Land liegt direkt östlich der Niederlande?","Deutschland",["Spanien","Irland","Italien"],"Es ist ein Nachbarland.","Deutschland grenzt an die Niederlande.","Die Niederlande grenzen auch an Belgien."]
      ],
      weer_klimaat: [
        ["Was misst ein Thermometer?","Die Temperatur",["Die Windrichtung","Die Regenmenge","Den Luftdruck"],"Warm oder kalt.","Ein Thermometer misst die Temperatur.","Wir nutzen oft Grad Celsius."],
        ["Was ist Niederschlag?","Wasser, das vom Himmel fällt",["Wind","Sonnenlicht","Nebel"],"Regen und Schnee sind Beispiele.","Niederschlag kann Regen, Schnee oder Hagel sein.","Er entsteht aus Wasser in Wolken."],
        ["Was ist Wind?","Bewegte Luft",["Bewegtes Wasser","Warmer Sand","Eine Wolke"],"Du spürst ihn, aber siehst ihn nicht.","Wind ist Luft, die sich bewegt.","Unterschiede im Luftdruck machen den meisten Wind."],
        ["Warum entsteht oft Nebel?","Wasserdampf verdichtet sich nahe am Boden",["Wegen der Sterne","Wegen Sand","Wegen Magneten"],"Man sieht schlechter.","Nebel besteht aus winzigen Wassertröpfchen in der Luft.","Nebel ist eigentlich eine Wolke am Boden."],
        ["Was ist Klima?","Das durchschnittliche Wetter über lange Zeit",["Das Wetter heute","Ein Gewitter","Ein Regenmesser"],"Es geht um Jahre, nicht um einen Tag.","Klima beschreibt das typische Wetter über einen langen Zeitraum.","Wetter kann sich von Tag zu Tag stark ändern."],
        ["Was verursacht einen Blitz?","Eine elektrische Entladung",["Eine Sternschnuppe","Ein Flugzeug","Ein Regenbogen"],"Er passiert oft bei Gewitterwolken.","Ein Blitz ist eine gewaltige elektrische Entladung.","Die Luft darum wird extrem heiß."],
        ["Warum hörst du den Donner nach dem Blitz?","Licht ist schneller als Schall",["Der Donner beginnt später","Die Wolken warten","Die Sonne hält den Schall auf"],"Du siehst den Blitz zuerst.","Licht erreicht dich viel schneller als Schall.","Der Abstand hilft, die Entfernung des Gewitters zu schätzen."],
        ["Welche Wolke gehört oft zu heftigen Schauern und Gewitter?","Die Gewitterwolke",["Federwolke","Nebel","Keine Wolke"],"Sie kann sehr hoch werden.","Gewitterwolken können Gewitter bringen.","Oben haben sie oft die Form eines Ambosses."],
        ["Was ist eine Hitzewelle?","Eine Zeit mit ungewöhnlich warmem Wetter",["Ein plötzlicher Schneeschauer","Ein Erdbeben","Eine hohe Welle im Meer"],"Sie dauert mehrere Tage.","Eine Hitzewelle ist eine längere Zeit mit sehr warmem Wetter.","Die Definitionen sind von Land zu Land verschieden."],
        ["Was ist Frost?","Eine Temperatur unter dem Gefrierpunkt",["Starker Wind","Sehr heftiger Regen","Dichter Nebel"],"Dann kann Wasser gefrieren.","Bei Frost fällt die Temperatur auf etwa 0 °C oder darunter.","Reif kann entstehen, wenn Wasserdampf gefriert."]
      ],
      oceanen_natuur: [
        ["Was bedeckt den größten Teil der Erde?","Wasser",["Wüste","Wald","Eis"],"Ozeane nehmen enorm viel Platz ein.","Etwa 71% der Erde sind von Wasser bedeckt.","Das meiste davon ist salziges Meerwasser."],
        ["Welcher Ozean ist der größte?","Der Pazifische Ozean",["Der Atlantische Ozean","Der Indische Ozean","Das Nordpolarmeer"],"Er liegt zwischen Asien und Amerika.","Der Pazifik ist der größte Ozean.","Er bedeckt etwa ein Drittel der Erdoberfläche."],
        ["Wie heißt geschmolzenes Gestein, das aus einem Vulkan kommt?","Lava",["Magma im Untergrund","Lehm","Sand"],"Außerhalb der Erde nennen wir es so.","An der Oberfläche heißt geschmolzenes Gestein Lava.","Im Untergrund nennen wir es Magma."],
        ["Was ist eine Insel?","Land, das ganz von Wasser umgeben ist",["Eine hohe Wolke","Ein Fluss","Eine Wüste"],"Du musst Wasser überqueren, um hinzukommen.","Eine Insel ist an allen Seiten von Wasser umgeben.","Grönland ist die größte Insel, die kein Kontinent ist."],
        ["Was ist ein Gebirge?","Eine Reihe von Bergen",["Ein breiter Fluss","Ein Meer","Eine Inselgruppe"],"Die Alpen sind eines.","Ein Gebirge besteht aus zusammenhängenden Bergen.","Im Himalaya stehen die höchsten Berge der Erde."],
        ["Was ist eine Flussmündung?","Die Stelle, an der ein Fluss endet",["Die Quelle eines Flusses","Ein Berggipfel","Eine Wüste"],"Der Fluss fließt oft in ein Meer oder einen See.","Eine Mündung ist das Ende eines Flusses.","Manche Flüsse bilden an der Mündung ein Delta."],
        ["Was ist eine Wüste?","Ein Gebiet mit sehr wenig Niederschlag",["Immer ein heißer Strand","Ein tropischer Regenwald","Ein Ozean"],"Nicht jede Wüste ist heiß.","Wüsten bekommen sehr wenig Niederschlag.","Genau gesehen ist auch die Antarktis eine Wüste."],
        ["Was ist ein Gletscher?","Eine langsam fließende Eismasse",["Eine Wolke","Ein Lavafluss","Eine Sanddüne"],"Er entsteht aus zusammengepresstem Schnee.","Gletscher bewegen sich langsam durch ihr eigenes Gewicht.","Sie formen Täler und Landschaften."],
        ["Was ist Erosion?","Das Abtragen und Verschieben von Gestein und Boden",["Wachsende Bäume","Entstehende Sterne","Gefrierende Luft"],"Wasser und Wind können sie verursachen.","Erosion verändert Landschaften.","Flüsse können tiefe Täler ausgraben."],
        ["Was ist ein Delta?","Ein Gebiet, in dem ein Fluss sich an der Mündung teilt",["Ein Berggipfel","Eine Meeresströmung","Eine Wolke"],"Dort kann fruchtbarer Boden sein.","Ein Flussdelta entsteht aus abgelagertem Sediment.","Das Nildelta ist ein bekanntes Beispiel."]
      ],
      kaarten_navigatie: [
        ["Was zeigt eine Windrose?","Die Richtungen",["Die Temperatur","Die Höhe","Die Zeitzonen"],"Norden, Osten, Süden und Westen.","Eine Windrose zeigt die Richtungen.","Karten nutzen oft N, O, S und W."],
        ["Wozu dient eine Legende auf einer Karte?","Um die Zeichen zu erklären",["Um die Karte zu schmücken","Um Entfernungen zu messen","Um Wind zu machen"],"Farben und Zeichen bekommen eine Bedeutung.","Eine Legende erklärt die Zeichen auf einer Karte.","Eine blaue Linie kann zum Beispiel ein Fluss sein."],
        ["Was ist der Maßstab auf einer Karte?","Das Verhältnis zwischen Kartenabstand und echtem Abstand",["Ein Musikinstrument","Ein Temperaturmesser","Ein Farbcode"],"1 cm kann zum Beispiel 1 km bedeuten.","Der Maßstab macht Entfernungen auf Karten verständlich.","Ein großer Maßstab zeigt meist mehr Einzelheiten."],
        ["Was sind Koordinaten?","Zahlen oder Werte, die einen Ort angeben",["Eine Wolkenart","Eine Münze","Ein Fluss"],"GPS benutzt sie.","Koordinaten beschreiben eine Position.","Breite und Länge sind bekannte Koordinaten."],
        ["Welche Richtung liegt dem Norden gegenüber?","Süden",["Osten","Westen","Nordosten"],"Denk an die Windrose.","Süden liegt dem Norden gegenüber.","Osten und Westen stehen im rechten Winkel zu Nord und Süd."],
        ["Welche Richtung ist rechts von dir, wenn du nach Norden schaust?","Osten",["Westen","Süden","Norden"],"Auf vielen Karten ist Norden oben.","Mit Norden oben liegt Osten rechts.","Darum liegt Westen auf so einer Karte links."],
        ["Was ist eine topografische Karte?","Eine Karte mit Gelände- und Höhenangaben",["Eine Sternkarte","Eine Speisekarte","Ein Zeitstrahl"],"Sie kann Höhenlinien haben.","Topografische Karten zeigen Landschaft und Höhe.","Wanderer nutzen sie oft."],
        ["Was ist GPS?","Ein Satellitensystem, um die Position zu finden",["Eine Wolkenart","Ein Vulkan","Ein Kompass ohne Satelliten"],"Dein Handy kann es nutzen.","GPS nutzt Satellitensignale, um deine Position zu bestimmen.","Für eine genaue Position braucht man mehrere Satelliten."],
        ["Warum ist Norden auf Karten oft oben?","Das ist eine weit verbreitete Gewohnheit",["Weil Norden höher liegt","Weil die Sonne immer dort steht","Weil Flüsse dorthin fließen"],"Es ist eine Gewohnheit, kein Naturgesetz.","Viele moderne Karten setzen Norden nach oben.","Alte Karten waren manchmal anders ausgerichtet."],
        ["Was ist eine Route?","Ein geplanter Weg von Start bis Ziel",["Eine Regenwolke","Ein Berg","Eine Landesgrenze"],"Navigation hilft dir, ihr zu folgen.","Eine Route beschreibt, wie du von A nach B kommst.","Digitale Karten können Routen selbst berechnen."]
      ]
    }
  };

  window.KWIZILLO_QUESTIONS_DE = window.KWIZILLO_BUILD_BANK(defs, window.KWIZILLO_EXTRA_DE||{});
})();
