(() => {
  // French bank. Same worlds, topics, order and therefore the same question ids
  // as the other banks, so progress, cards and the per-question illustrations
  // survive a language switch.
  const defs = {
    ruimte: {
      zonnestelsel: [
        ["Quelle planète est la plus proche du Soleil ?","Mercure",["Vénus","Mars","la Terre"],"C’est la plus petite planète et elle est tout devant.","Mercure est la planète la plus proche du Soleil.","Une année sur Mercure ne dure que 88 jours terrestres."],
        ["Quelle planète est notre planète d’origine ?","la Terre",["Vénus","Mars","Jupiter"],"Ici vivent des humains, des animaux et des plantes.","Nous vivons sur la Terre.","Environ 71% de la Terre est couverte d’eau."],
        ["Quelle planète est connue comme la planète rouge ?","Mars",["Vénus","Saturne","Neptune"],"Son sol contient beaucoup d’oxyde de fer.","Mars est appelée la planète rouge.","Mars a deux petites lunes : Phobos et Deimos."],
        ["Quelle planète a les anneaux les plus célèbres ?","Saturne",["la Terre","Mercure","Mars"],"C’est une grande géante gazeuse.","Saturne a un système d’anneaux impressionnant.","Les anneaux sont surtout faits de glace et de roche."],
        ["Quelle est la plus grande planète de notre système solaire ?","Jupiter",["Mars","Vénus","la Terre"],"Elle a la célèbre Grande Tache rouge.","Jupiter est la plus grande planète.","Plus de mille Terres tiendraient dans Jupiter."],
        ["Quelle planète est la plus éloignée du Soleil ?","Neptune",["Jupiter","la Terre","Vénus"],"C’est une géante de glace bleue et lointaine.","Neptune est la planète la plus éloignée du Soleil.","Une année sur Neptune dure environ 165 années terrestres."],
        ["Quelle planète se trouve entre Vénus et Mars ?","la Terre",["Mercure","Jupiter","Saturne"],"C’est notre propre planète.","L’ordre est Vénus, la Terre, Mars.","La Terre est la troisième planète à partir du Soleil."],
        ["Qu’est-ce qui tourne autour de la Terre ?","la Lune",["Jupiter","le Soleil","Mars"],"Tu la vois souvent dans le ciel de nuit.","La Lune tourne autour de la Terre.","La Lune met environ 27 jours pour faire un tour."],
        ["Combien de planètes compte notre système solaire ?","8",["7","9","10"],"Pluton compte aujourd’hui comme planète naine.","Notre système solaire compte huit planètes.","Depuis 2006 Pluton est classée comme planète naine."],
        ["Quelle planète est célèbre pour sa forte couleur bleue ?","Neptune",["Mercure","Mars","Vénus"],"C’est une géante de glace lointaine.","Neptune paraît bleu profond.","Le méthane de son atmosphère renforce le bleu."]
      ],
      sterren_planeten: [
        ["Qu’est-ce que le Soleil ?","Une étoile",["Une planète","Une lune","Une comète"],"Il fabrique sa propre lumière et sa chaleur.","Le Soleil est une étoile.","La lumière du Soleil met environ 8 minutes à atteindre la Terre."],
        ["De quoi une étoile est-elle surtout faite ?","De gaz brûlant et de plasma",["De roche froide","D’une lune","D’un nuage"],"Les étoiles brillent d’elles-mêmes.","Les étoiles sont faites de gaz extrêmement chaud et de plasma.","Notre Soleil est une étoile de taille moyenne."],
        ["Qu’est-ce qu’une galaxie ?","Un immense groupe d’étoiles",["Une planète","Un télescope","Un nuage sur la Terre"],"La Voie lactée en est une.","Une galaxie contient énormément d’étoiles.","La Voie lactée compte des centaines de milliards d’étoiles."],
        ["Comment s’appelle notre galaxie ?","La Voie lactée",["Andromède","Orion","Saturne"],"Tu vois parfois une bande pâle dans un ciel sombre.","Notre système solaire se trouve dans la Voie lactée.","La Voie lactée est une galaxie spirale."],
        ["Qu’est-ce qu’une supernova ?","Une énorme explosion d’étoile",["Une nouvelle lune","Un lancement de fusée","Une averse"],"Cela arrive à la fin de la vie de certaines étoiles.","Une supernova est une explosion gigantesque d’une étoile.","Une telle explosion peut briller très fort pendant un moment."],
        ["De quelle couleur sont en général les étoiles les plus chaudes ?","Bleues",["Rouges","Brunes","Vertes"],"Pense à la flamme la plus chaude d'une gazinière.","Les étoiles très chaudes paraissent souvent bleutées.","Les étoiles rouges sont en général plus froides que les bleues."],
        ["Qu’est-ce qu’une exoplanète ?","Une planète autour d’une autre étoile",["Une lune de la Terre","Une comète","Un satellite"],"Elle ne tourne pas autour de notre Soleil.","Une exoplanète tourne autour d’une autre étoile que le Soleil.","Des milliers d’exoplanètes ont déjà été découvertes."],
        ["Qu’est-ce qu’un trou noir ?","Une région où la gravité est extrêmement forte",["Une planète sombre","Un nuage","Un moteur de fusée"],"Même la lumière n’en sort pas facilement.","Un trou noir a une gravité extrêmement forte.","Beaucoup de trous noirs naissent d’étoiles très lourdes."],
        ["Quelle étoile est la plus proche de la Terre ?","Le Soleil",["Sirius","l’étoile Polaire","Bételgeuse"],"Tu la vois tous les jours.","Le Soleil est notre étoile la plus proche.","L’étoile suivante est beaucoup plus loin."],
        ["Pourquoi les étoiles semblent-elles scintiller ?","À cause de l’atmosphère",["Parce qu’elles clignotent","À cause de leurs lunes","Parce qu’elles tournent"],"Leur lumière est déviée par les couches d’air.","L’atmosphère fait trembler un peu la lumière des étoiles.","Les planètes scintillent en général moins que les étoiles."]
      ],
      astronauten: [
        ["Comment appelle-t-on quelqu’un qui voyage dans l’espace ?","Un astronaute",["Un archéologue","Un plongeur","Un capitaine"],"Cette personne porte souvent une combinaison spatiale.","Un astronaute voyage et travaille dans l’espace.","Les astronautes s’entraînent souvent pendant des années."],
        ["Pourquoi les astronautes portent-ils une combinaison hors du vaisseau ?","Pour l’air et la protection",["Pour la chaleur","Pour la vitesse","Comme uniforme"],"Dans l’espace on ne peut pas simplement respirer.","Une combinaison spatiale fournit de l’oxygène et une protection.","Elle protège aussi des températures extrêmes."],
        ["Que ressentent souvent les astronautes dans une station spatiale ?","L’apesanteur",["De fortes pluies","Un vent fort","Des tremblements de terre"],"Ils ont l’air de flotter.","En orbite, les astronautes vivent en microgravité.","Tout doit être attaché pour ne pas s’envoler."],
        ["Où dorment souvent les astronautes dans la station spatiale ?","Dans des sacs de couchage attachés",["Dans des lits normaux","Dans des hamacs dehors","Par terre"],"Sinon ils s’envoleraient.","Les astronautes dorment dans des sacs de couchage fixés au mur.","En microgravité il n’y a pas vraiment de haut ni de bas."],
        ["Pourquoi les astronautes s’entraînent-ils sous l’eau ?","Pour imiter l’apesanteur",["Pour nager plus vite","Pour chercher de l’eau lunaire","Pour se détendre"],"Sous l’eau on peut s’exercer à flotter.","L’entraînement sous l’eau sert à répéter les sorties dans l’espace.","De grands bassins contiennent parfois des maquettes de la station."],
        ["Qu’est-ce qu’une sortie dans l’espace ?","Un travail hors du vaisseau spatial",["Une marche sur la Terre","Une course dans une fusée","Une promenade au musée"],"L’astronaute reste attaché par des systèmes de sécurité.","Une sortie dans l’espace s’appelle aussi une EVA.","L’astronaute porte alors une combinaison complète."],
        ["Qu’arrive-t-il aux muscles pendant une longue apesanteur ?","Ils peuvent s’affaiblir",["Ils deviennent en acier","Ils disparaissent aussitôt","Ils grossissent toujours plus vite"],"C’est pour ça que les astronautes font beaucoup de sport.","Sans entraînement, les muscles et les os s’affaiblissent.","Les astronautes s’entraînent chaque jour dans l’ISS."],
        ["Que mangent les astronautes dans l’espace ?","De la nourriture spécialement emballée",["Des pilules","De la glace","Rien"],"Cela doit être sûr en microgravité.","Les astronautes mangent des aliments spécialement emballés.","Les miettes sont gênantes parce qu’elles flottent partout."],
        ["Qu’est-ce que l’ISS ?","Une station spatiale internationale",["Une planète","Un moteur de fusée","Une base lunaire"],"Elle tourne autour de la Terre.","L’ISS est une grande station spatiale en orbite autour de la Terre.","Des astronautes de plusieurs pays y travaillent ensemble."],
        ["Pourquoi un astronaute doit-il s’attacher pendant son travail ?","Pour ne pas s’envoler",["Pour plus de gravité","Contre la pluie","Pour la vitesse"],"En microgravité on continue facilement à bouger.","S’attacher évite de dériver sans contrôle.","Les outils aussi sont attachés."]
      ],
      raket_avontuur: [
        ["À quoi sert un moteur de fusée ?","À créer une poussée",["À imprimer des photos","À fabriquer de l’oxygène","À compter les étoiles"],"Il pousse des gaz brûlants vers l’arrière.","Un moteur de fusée fournit la poussée.","Par action et réaction, la fusée part dans l’autre sens."],
        ["Pourquoi une fusée a-t-elle besoin d’autant de carburant ?","Pour échapper à la gravité",["Pour l’éclairage","Pour la climatisation","Pour la radio"],"Le décollage demande énormément d’énergie.","Un lancement demande des quantités d’énergie énormes.","Au décollage, la plus grande partie d’une fusée peut être du carburant."],
        ["Que se passe-t-il au décollage ?","La fusée s’élève",["La fusée atterrit","Le moteur s’arrête toujours","La Lune se rapproche"],"C’est le moment du départ.","Le décollage est le moment où la fusée quitte le sol.","Les premières secondes sont techniquement très importantes."],
        ["Pourquoi certaines fusées ont-elles plusieurs étages ?","Pour larguer les parties vides",["Pour des fenêtres en plus","Pour des couchettes","Pour les couleurs"],"Ainsi la fusée emporte moins de masse.","Une fusée largue un étage quand son carburant est épuisé.","Accélérer ensuite devient plus économique."],
        ["Qu’est-ce qu’un pas de tir ?","L’endroit d’où une fusée part",["Un satellite","Un rover lunaire","Un siège de cockpit"],"La fusée s’y tient avant le départ.","Un pas de tir soutient la fusée avant le vol.","On y trouve de grandes installations de carburant, de refroidissement et de sécurité."],
        ["Qu’est-ce qu’un satellite ?","Un objet qui tourne autour d’un autre objet",["Une explosion d’étoile","Un moteur de fusée","Un télescope"],"La Lune est en fait un satellite naturel.","Les satellites tournent autour d’une planète ou d’un autre corps.","Les satellites artificiels aident à la navigation et à la communication."],
        ["Pourquoi le nez d’une fusée est-il profilé ?","Pour réduire la résistance de l’air",["Pour être plus lourd","Pour attraper plus de pluie","Pour la couleur"],"Une forme lisse traverse l’air plus facilement.","Une forme profilée réduit la résistance de l’air.","Hors de l’atmosphère, cette résistance disparaît presque."],
        ["Qu’est-ce qu’une capsule ?","Une partie où des gens ou du fret peuvent voyager",["Une galaxie","Une lune","Un carburant"],"Elle se trouve souvent au sommet de la fusée.","Une capsule spatiale transporte des gens ou du fret.","Certaines capsules reviennent avec des parachutes."],
        ["Qu’est-ce qui aide une capsule à atterrir en sécurité ?","Des parachutes",["Des étoiles","Des éruptions solaires","Des astéroïdes"],"Ils freinent la descente.","Des parachutes ralentissent une capsule qui revient.","Certains vaisseaux atterrissent aussi grâce à des moteurs."],
        ["Qu’est-ce qu’une orbite autour de la Terre ?","Une trajectoire où l’on tombe sans arrêt autour de la Terre",["Une route droite vers le Soleil","Un tunnel","Un nuage"],"La vitesse et la gravité s’équilibrent.","Un satellite en orbite tombe sans cesse autour de la Terre.","C’est pour cela qu’il ne s’écrase pas."]
      ]
    },
    geschiedenis: {
      egyptenaren: [
        ["Pourquoi beaucoup de pyramides ont-elles été construites ?","Comme tombeaux",["Comme écoles","Comme marchés","Comme ports"],"Pense aux pharaons et à leur sépulture.","Beaucoup de pyramides étaient des tombeaux de pharaons.","La grande pyramide de Gizeh a des milliers d’années."],
        ["Comment appelait-on un souverain de l’Égypte ancienne ?","Un pharaon",["Un sénateur","Un chevalier","Un Viking"],"Il était au sommet de la société.","Un souverain égyptien s’appelait un pharaon.","Certains pharaons étaient considérés comme divins."],
        ["Quel fleuve était très important pour l’Égypte ?","Le Nil",["Le Rhin","L’Amazone","Le Danube"],"Il traverse le pays et rend la terre fertile.","Le Nil était essentiel pour l’agriculture et le transport.","Les crues annuelles apportaient un limon fertile."],
        ["Comment s’appelle l’écriture égyptienne faite de signes et d’images ?","Les hiéroglyphes",["Le latin","Les runes","Le morse"],"Tu en vois sur les temples et les tombeaux.","Les hiéroglyphes étaient une écriture égyptienne importante.","Cette écriture utilisait des centaines de signes."],
        ["Qu’est-ce qu’une momie ?","Un corps conservé",["Une pièce d’or","Un temple","Un bateau"],"Le corps était traité spécialement après la mort.","Les Égyptiens faisaient des momies pour conserver les corps.","Le procédé pouvait durer de nombreuses semaines."],
        ["Sur quoi les Égyptiens écrivaient-ils souvent ?","Sur du papyrus",["Sur du plastique","Sur du béton","Sur de l’aluminium"],"On le faisait avec une plante du Nil.","Le papyrus servait de support d’écriture.","Notre mot papier vient de papyrus."],
        ["Qu’était le Sphinx de Gizeh ?","Une statue à corps de lion et tête humaine",["Une pyramide","Un navire","Une couronne"],"Il se tient près des pyramides.","Le grand Sphinx est une énorme statue de pierre.","Le Sphinx a été taillé dans du calcaire."],
        ["À quoi servait l’irrigation aux Égyptiens ?","À arroser leurs champs",["À peindre les pyramides","À écrire","À faire des pièces"],"L’eau du Nil devait atteindre les champs.","L’irrigation aidait l’agriculture.","Des canaux et des bassins répartissaient l’eau dans les champs."],
        ["Quels animaux étaient souvent vus comme spéciaux en Égypte ?","Les chats",["Les ours polaires","Les pingouins","Les kangourous"],"Ils apparaissent beaucoup dans l’art et la religion.","Les chats avaient une place particulière dans l’Égypte ancienne.","La déesse Bastet était souvent représentée en chatte."],
        ["Que faisaient les scribes dans l’Égypte ancienne ?","Tenir des textes et des registres",["Faire voler des pyramides","Former des chevaliers","Fabriquer des étoiles"],"Écrire était une compétence importante.","Les scribes tenaient les registres et suivaient les impôts.","Tout le monde ne savait pas lire et écrire."]
      ],
      ridders_kastelen: [
        ["Que portait souvent un chevalier pour se protéger ?","Une armure",["Une combinaison spatiale","Un peignoir","Une combinaison de plongée"],"Elle était en métal.","L’armure protégeait le corps.","Une armure complète comptait de nombreuses pièces."],
        ["Où habitait souvent un seigneur puissant ?","Dans un château",["Dans une fusée","Dans une pyramide","Dans un igloo"],"Le bâtiment avait des murs épais.","Les châteaux étaient des habitations et des places fortes.","Beaucoup de châteaux avaient des tours et des remparts."],
        ["Qu’est-ce qu’une douve ?","Un fossé d’eau autour d’un château",["Une chambre","Une place de marché","Une armurerie"],"Elle rendait les attaques plus difficiles.","Une douve aidait à défendre un château.","Toutes les douves n’étaient pas toujours remplies d’eau."],
        ["Qu’est-ce qu’un pont-levis ?","Un pont qu’on peut relever",["Un escalier secret","Un drapeau","Une tour"],"Il se trouvait souvent à l’entrée.","Un pont-levis pouvait bloquer l’entrée.","Il était souvent associé à une porte fortifiée."],
        ["Que se passait-il lors d’un tournoi de chevaliers ?","Les chevaliers s’affrontaient dans des épreuves",["On construisait des pyramides","On naviguait vers l’Amérique","On fabriquait des télescopes"],"Pense à la joute.","Les tournois étaient des compétitions de chevaliers.","La joute était un spectacle impressionnant."],
        ["Qu’est-ce qu’un bouclier ?","Une protection contre les attaques",["Un instrument de musique","Une carte","Une tasse"],"Les chevaliers le portaient souvent au bras.","Un bouclier protège contre les armes.","Les boucliers portaient souvent des symboles ou des blasons."],
        ["Qui n’habitait en général pas en permanence dans un château ?","Tous les paysans des environs",["Le seigneur du château","Les soldats","Les serviteurs"],"Beaucoup de gens vivaient dans les villages autour.","La plupart des paysans vivaient hors du château.","En cas de danger, ils pouvaient parfois s’y réfugier."],
        ["Pourquoi les châteaux avaient-ils des murs épais ?","Pour la défense",["Pour un internet plus rapide","Pour la chaleur","Pour la décoration"],"Ils devaient résister aux attaques.","Des murs de pierre épais rendaient les châteaux plus solides.","Plus tard, les canons ont rendu beaucoup de murs inutiles."],
        ["Que faisait souvent un écuyer ?","Aider un chevalier et apprendre",["Enterrer un pharaon","Piloter une fusée","Construire un temple"],"Il se préparait parfois à devenir chevalier.","Un écuyer aidait un chevalier et apprenait le métier.","Tous les écuyers ne devenaient pas chevaliers."],
        ["Qu’était une forteresse ?","Un lieu de vie fortifié",["Une galaxie","Un navire","Une matière scolaire"],"Le mot s’emploie souvent pour les châteaux.","Une forteresse était un lieu fortifié.","Les forteresses se dressaient souvent à des endroits stratégiques."]
      ],
      romeinen: [
        ["Qui a construit le Colisée ?","Les Romains",["Les Vikings","Les Mayas","Les Égyptiens"],"Il se trouve à Rome.","Le Colisée a été construit par les Romains.","Il pouvait accueillir des dizaines de milliers de spectateurs."],
        ["Qu’était un aqueduc ?","Une construction pour transporter l’eau",["Un casque de chevalier","Un temple pour bateaux","Une pièce de monnaie"],"Il amenait l’eau dans les villes.","Les aqueducs romains transportaient l’eau sur de longues distances.","Certains aqueducs sont encore visibles aujourd’hui."],
        ["Quelle langue parlaient beaucoup de Romains ?","Le latin",["Le néerlandais","Le japonais","L’arabe"],"Beaucoup de mots français en viennent.","Le latin était une langue importante de l’Empire romain.","Le français, l’espagnol et l’italien viennent du latin."],
        ["Qu’était une légion ?","Un grand groupe de soldats romains",["Un marché","Des thermes","Un navire"],"Elle faisait partie de l’armée.","Une légion était une grande unité de l’armée.","Les soldats romains s’entraînaient durement."],
        ["Qu’était un forum dans une ville romaine ?","Une place centrale",["Une prison","Une ferme","Un port"],"On y venait pour le commerce et la politique.","Le forum était un centre important de la ville.","Des temples et des bâtiments publics s’y trouvaient souvent."],
        ["À quoi servaient les thermes romains ?","À se laver et à se retrouver",["À construire des fusées","À stocker du grain","À dresser des chevaux"],"Les gens s’y retrouvaient aussi pour discuter.","Les thermes étaient des lieux de rencontre importants.","Certains avaient des bains chauds et froids."],
        ["Que portait souvent un soldat romain ?","Un casque et un bouclier",["Une combinaison spatiale","Un chapeau de cow-boy","Une combinaison de plongée"],"Il devait se protéger au combat.","Les soldats romains utilisaient casques, boucliers et armes.","Leur équipement a changé au fil des siècles."],
        ["Que signifie « Empire romain » ?","Un grand territoire gouverné depuis Rome",["La ville de Rome","Une pyramide","Un ordre de chevalerie"],"Il s’étendait sur une grande partie de l’Europe.","L’Empire romain était très vaste.","À son apogée, il entourait toute la Méditerranée."],
        ["Qu’utilisaient les Romains pour les longs trajets par voie terrestre ?","Un vaste réseau de routes",["Les fleuves","Des montgolfières","Des trains"],"Beaucoup de routes étaient très solides.","Les Romains ont construit un grand réseau de routes.","Certaines routes actuelles suivent d’anciennes voies romaines."],
        ["Qu’était un sénateur à Rome ?","Un dignitaire important",["Un gladiateur","Un pharaon","Un chevalier"],"Il avait un rôle politique.","Les sénateurs avaient de l’influence sur le gouvernement.","Le Sénat romain a duré des siècles."]
      ],
      ontdekkingsreizigers: [
        ["Que faisait un explorateur ?","Explorer des régions nouvelles",["Construire des planètes","Inventer l’électricité","Garder des pyramides"],"Pense aux longs voyages.","Les explorateurs voyageaient vers des régions inconnues.","Leurs voyages ont changé les cartes et le commerce."],
        ["À quoi servait une boussole aux marins ?","À trouver la direction",["À cuisiner","À écrire","À mesurer la profondeur"],"L’aiguille montre à peu près le nord.","Une boussole aide à la navigation.","Elle a rendu les longs voyages en mer plus sûrs."],
        ["Qu’est-ce qu’une carte marine ?","Une carte pour naviguer en mer",["Un tableau","Un blason de chevalier","Une constellation"],"Les navires l’utilisaient pour tracer leur route.","Les cartes marines montrent les côtes, les dangers et les routes.","Les navires modernes utilisent souvent des cartes numériques."],
        ["Pourquoi les étoiles étaient-elles utiles aux marins ?","Elles aidaient à trouver leur position",["Pour attirer les poissons","Pour faire du vent","Pour chauffer l’eau"],"La nuit surtout, elles donnaient la direction.","Les étoiles pouvaient aider à la navigation.","L’étoile Polaire était importante dans l’hémisphère nord."],
        ["Qu’était une caravelle ?","Un type de voilier",["Des thermes romains","Un château","Un temple"],"On l’utilisait pour les longs voyages.","Les caravelles étaient des voiliers maniables.","Elles ont joué un rôle dans les grandes découvertes."],
        ["Pourquoi les explorateurs emportaient-ils des provisions ?","Parce que les voyages pouvaient durer longtemps",["Parce qu’il y avait des magasins en mer","Pour décorer","Pour construire des étoiles"],"En mer on ne pouvait pas aller faire les courses.","Nourriture et eau étaient essentielles lors des longs voyages.","Les pénuries et les maladies étaient des risques sérieux."],
        ["Qu’est-ce que la navigation ?","Savoir où tu es et où tu vas",["Peindre un bateau","Apprendre une langue","Construire un marché"],"La boussole et les cartes y aident.","Naviguer, c’est planifier et suivre une route.","Le GPS est une forme moderne de navigation."],
        ["Quel était un grand danger des longs voyages en mer ?","Les tempêtes et les maladies",["Les feux de circulation","La neige dans le désert","Les satellites"],"Les voyages duraient parfois des mois.","Tempêtes, maladies et manque de nourriture étaient dangereux.","Le scorbut venait d’un long manque de vitamine C."],
        ["Pourquoi cherchait-on de nouvelles routes vers l’Asie ?","Pour le commerce de marchandises précieuses",["Pour faire du ski","Pour des dinosaures","Pour la conquête spatiale"],"Les épices valaient très cher.","Le commerce a motivé beaucoup de voyages de découverte.","Les épices pouvaient coûter très cher en Europe."],
        ["Que faisaient les cartographes après de nouveaux voyages ?","Améliorer leurs cartes",["Dresser des pyramides","Déplacer des étoiles","Changer l’heure"],"De nouvelles connaissances s’ajoutaient.","Les récits de voyage rendaient les cartes plus exactes.","Les cartes sont devenues plus détaillées au fil des siècles."]
      ]
    },
    wetenschap: {
      slimme_proefjes: [
        ["Que se passe-t-il souvent quand tu mélanges du bicarbonate et du vinaigre ?","Des bulles de gaz apparaissent",["Ça gèle aussitôt","Ça devient du métal","Il ne se passe rien"],"Tu vois beaucoup de mousse.","La réaction produit entre autres du dioxyde de carbone.","Ce gaz peut par exemple gonfler un ballon."],
        ["Pourquoi porte-t-on des lunettes de protection pour certaines expériences ?","Pour protéger tes yeux",["Pour mieux entendre","Pour courir plus vite","Pour la couleur"],"Certaines substances peuvent éclabousser.","Les lunettes de protection protègent les yeux.","Travailler en sécurité fait partie de la science."],
        ["Qu’est-ce qu’une hypothèse ?","Une attente que l’on peut tester",["Un fait établi","Un instrument de mesure","Un liquide"],"Tu décides avant ce que tu attends.","Une hypothèse est une prévision que tu peux vérifier.","Après une expérience, elle peut être confirmée ou non."],
        ["Dans une expérience juste, que faut-il garder aussi semblable que possible ?","Les autres conditions",["Le résultat","La question","Ton prénom"],"Tu ne changes qu’une chose à la fois.","Garder les conditions égales rend l’expérience plus juste.","Ainsi tu sais mieux ce qui a causé un effet."],
        ["Avec quoi mesures-tu précisément un volume de liquide ?","Avec une éprouvette graduée",["Avec une loupe","Avec une boussole","Avec un chronomètre"],"Elle a des graduations sur le côté.","Une éprouvette graduée mesure le volume.","Le volume se mesure souvent en millilitres."],
        ["Que fait un thermomètre dans une expérience ?","Il mesure la température",["Il mesure le temps","Il mesure le poids","Il fait de la lumière"],"Tu peux mesurer le chaud ou le froid.","Un thermomètre mesure la température.","Chez nous on mesure souvent en degrés Celsius."],
        ["Pourquoi notes-tu les résultats d’une expérience ?","Pour pouvoir les comparer",["Pour les oublier","Pour nettoyer le verre","Pour décorer"],"Les scientifiques notent leurs mesures.","Noter les résultats aide à analyser et à recommencer.","La bonne science doit être vérifiable."],
        ["Qu’arrive-t-il à la glace quand tu la chauffes ?","Elle fond",["Elle devient de la pierre","Elle disparaît d’un coup","Elle devient plus lourde"],"L’eau solide devient liquide.","La glace fond et devient de l’eau.","À pression normale, la glace fond vers 0 °C."],
        ["De quoi as-tu besoin pour faire une ombre ?","D’une source de lumière et d’un objet",["De son","D’eau","De vent"],"L’objet arrête la lumière.","Une ombre apparaît quand la lumière est arrêtée.","Sa taille change avec la distance à la source de lumière."],
        ["Qu’est-ce que se dissoudre, comme le sucre dans l’eau ?","La substance se répartit dans le liquide",["La substance quitte le monde","La substance devient du feu","Le liquide gèle"],"Tu ne vois plus les grains séparément.","Les particules dissoutes se répartissent dans le liquide.","En faisant évaporer l’eau, tu récupères souvent le sucre."]
      ],
      lichaam: [
        ["Quel organe pompe le sang dans ton corps ?","Le cœur",["Les poumons","L’estomac","Le cerveau"],"Tu peux le sentir battre.","Le cœur pompe le sang dans tout le corps.","Ton cœur bat environ cent mille fois par jour."],
        ["Avec quoi respires-tu surtout ?","Les poumons",["Les reins","L’estomac","Les os"],"Ils sont dans ta poitrine.","Les poumons captent l’oxygène.","Tu as normalement deux poumons."],
        ["Quel organe t’aide à penser ?","Le cerveau",["Le foie","Le cœur","Les intestins"],"Il est dans ton crâne.","Le cerveau traite les informations et commande beaucoup de fonctions du corps.","Des milliards de cellules nerveuses y travaillent ensemble."],
        ["Que transporte le sang dans ton corps ?","De l’oxygène et des nutriments",["De l’air","Des os","De la chaleur"],"Le sang circule dans les vaisseaux.","Le sang transporte entre autres l’oxygène et les nutriments.","Les globules rouges aident à transporter l’oxygène."],
        ["Où commence déjà la digestion des aliments ?","Dans la bouche",["Dans le pied","Dans les poumons","Dans l’oreille"],"Tu mâches la nourriture en petits morceaux.","La digestion commence dans la bouche.","La salive contient des substances qui aident à décomposer les aliments."],
        ["Que protègent tes côtes ?","Le cœur et les poumons",["Tes pieds","Tes dents","Tes doigts"],"Elles forment une cage autour de la poitrine.","Les côtes protègent des organes importants.","La plupart des gens ont 12 paires de côtes."],
        ["À quoi servent les os, à part soutenir ?","À protéger et à bouger",["À la couleur","Au sommeil","À la température"],"Les muscles tirent sur les os.","Les os soutiennent, protègent et aident à bouger.","La moelle osseuse fabrique des cellules du sang."],
        ["Que font les muscles ?","Ils se contractent et créent le mouvement",["Ils fabriquent seulement du sang","Ils digèrent la nourriture","Ils voient la lumière"],"Les muscles travaillent souvent avec les os.","Les muscles peuvent se contracter et créer le mouvement.","Ton corps a des centaines de muscles."],
        ["Qu’est-ce que la peau ?","Le plus grand organe de ton corps",["Un os","Un muscle","Un vaisseau sanguin"],"Elle recouvre tout ton corps.","La peau protège le corps.","La peau aide aussi à régler la température."],
        ["Quel sens utilises-tu avec tes oreilles ?","L’ouïe",["Le goût","L’odorat","La vue"],"Tu captes les ondes sonores.","Avec les oreilles tu perçois les sons.","Ton oreille interne aide aussi à l’équilibre."]
      ],
      uitvindingen: [
        ["Avec quoi peux-tu regarder de très petites choses ?","Un microscope",["Un télescope","Une boussole","Un baromètre"],"Pense aux cellules et aux bactéries.","Un microscope grossit les petits objets.","Les microscopes modernes grossissent énormément."],
        ["Avec quoi regardes-tu les étoiles et les planètes lointaines ?","Un télescope",["Un microscope","Un thermomètre","Un aimant"],"Il rend les objets lointains plus visibles.","Un télescope recueille la lumière des objets lointains.","Il y a des télescopes sur Terre et dans l’espace."],
        ["Quelle invention a rendu la copie des livres beaucoup plus rapide ?","L’imprimerie",["La boussole","Le sifflet à vapeur","La torche"],"On pouvait imprimer avec des lettres mobiles.","L’imprimerie a permis de produire des livres en grand nombre.","Le savoir a pu se répandre plus vite."],
        ["À quoi sert une pile ?","À stocker et fournir de l’énergie électrique",["À mesurer le vent","À faire bouillir de l’eau sans énergie","À fabriquer des étoiles"],"Tu en trouves dans beaucoup d’appareils.","Une pile fournit de l’énergie électrique.","Les batteries rechargeables peuvent resservir."],
        ["Que fait un aimant ?","Il peut attirer certains métaux",["Il fait toujours de la lumière","Il gèle l’eau","Il arrête le temps"],"Le fer y réagit bien.","Les aimants exercent des forces sur les matériaux magnétiques.","Un aimant a un pôle nord et un pôle sud."],
        ["Que fabrique un panneau solaire ?","De l’électricité à partir de la lumière",["De la pluie à partir des nuages","De l’essence à partir de l’air","Du son à partir des pierres"],"Le Soleil fournit l’énergie.","Les cellules solaires transforment la lumière en électricité.","Les panneaux solaires n’ont aucune pièce mobile."],
        ["Que fait un moteur ?","Il transforme l’énergie en mouvement",["Il fabrique des couleurs","Il gèle l’eau","Il lit le papier"],"Les voitures et les machines utilisent des moteurs.","Un moteur convertit l’énergie en mouvement.","Il existe des moteurs électriques et à combustion."],
        ["Pourquoi le téléphone était-il une invention importante ?","On pouvait se parler à distance",["On pouvait voler","On pouvait arrêter le temps","On pouvait vivre sans électricité"],"Le son était envoyé à distance.","Le téléphone a beaucoup changé la communication.","Les portables réunissent aujourd’hui de nombreuses fonctions."],
        ["Que fait surtout un ordinateur ?","Il traite des informations",["Il fait de la musique","Il donne de la lumière","Il purifie l’eau"],"Il exécute des instructions.","Les ordinateurs traitent des données selon des programmes.","Même une montre connectée contient un ordinateur."],
        ["Quelle invention utilise des ondes radio pour trouver une position ?","Le GPS",["L’aimant","Le microscope","Le stéthoscope"],"Des satellites aident à savoir où tu es.","Le GPS utilise des signaux de satellites.","Ton téléphone utilise le GPS pour la navigation."]
      ],
      natuur_energie: [
        ["Quelle source d’énergie utilise l’air en mouvement ?","L’énergie éolienne",["L’énergie solaire","Le gaz naturel","L’énergie nucléaire"],"Les éoliennes tournent grâce à elle.","Les éoliennes transforment le vent en électricité.","Les grandes éoliennes peuvent alimenter de nombreux foyers."],
        ["Quelle source d’énergie utilise la lumière du Soleil ?","L’énergie solaire",["Le charbon","Le pétrole","Le gaz naturel"],"Des panneaux captent la lumière.","Les panneaux solaires transforment la lumière en électricité.","Le Soleil fournit bien plus d’énergie que nous n’en utilisons."],
        ["Qu’est-ce que l’énergie renouvelable ?","De l’énergie venant de sources qui se renouvellent",["De l’énergie jamais utilisée","De l’essence","Du charbon"],"Pense au Soleil et au vent.","Les sources renouvelables ne s’épuisent pas vite.","L’hydroélectricité et la géothermie peuvent aussi être renouvelables."],
        ["Que fait une éolienne ?","Elle transforme le vent en électricité",["Elle fait de la pluie","Elle produit de l’essence","Elle pousse les nuages"],"Les pales tournent dans le vent.","Une génératrice dans l’éolienne fabrique l’électricité.","Les éoliennes se dressent sur terre et en mer."],
        ["Quelle substance est libérée quand on brûle des combustibles fossiles ?","Du dioxyde de carbone",["De l’oxygène","De l’or","De l’hélium"],"C’est un gaz à effet de serre.","Brûler du pétrole, du gaz et du charbon libère du CO₂.","Plus de CO₂ renforce l’effet de serre."],
        ["Pourquoi isole-t-on les maisons ?","Pour mieux garder la chaleur dedans ou dehors",["Pour alourdir les fenêtres","Pour faire de l’eau","Pour renforcer le wifi"],"Une bonne isolation économise de l’énergie.","L’isolation réduit les pertes de chaleur.","Le toit, les murs et les sols peuvent tous être isolés."],
        ["Qu’est-ce que l’hydroélectricité ?","De l’énergie tirée de l’eau qui coule ou qui tombe",["De l’énergie tirée du sable","De l’énergie tirée de la fumée","De l’énergie tirée du plastique"],"Un barrage et une rivière font tourner des turbines.","L’hydroélectricité utilise le mouvement de l’eau.","C’est une source renouvelable importante dans le monde."],
        ["Qu’est-ce qu’économiser l’énergie ?","Utiliser moins d’énergie pour le même résultat",["Allumer plus de lampes","Fenêtres ouvertes et chauffage allumé","Laisser les appareils tourner"],"Les appareils économes aident.","Économiser l’énergie réduit la consommation.","Les lampes LED consomment moins que les vieilles ampoules."],
        ["Que fait la batterie d’une voiture électrique ?","Elle stocke de l’énergie électrique",["Elle fabrique de l’essence","Elle mesure le vent","Elle refroidit l’eau"],"Elle alimente le moteur électrique.","La batterie stocke l’énergie pour rouler.","Le freinage permet parfois de récupérer un peu d’énergie."],
        ["Quelle lampe est en général la plus économe ?","La lampe LED",["L’ampoule à filament","La bougie","La lampe halogène"],"Elle consomme moins d’électricité.","L’éclairage LED est très économe en énergie.","Les lampes LED durent aussi souvent plus longtemps."]
      ]
    },
    mysterie: {
      raadsels: [
        ["J’ai des touches noires et blanches et je fais de la musique. Qui suis-je ?","Un piano",["Une porte","Un coffre au trésor","Un vélo"],"Tu me joues avec les doigts.","Un piano a des touches sur lesquelles tu appuies.","Un piano peut avoir plus de quatre-vingts touches."],
        ["Je deviens de plus en plus mouillé en séchant. Qui suis-je ?","Une serviette",["Un parapluie","Le Soleil","Une éponge"],"Tu m’utilises après le bain.","Une serviette se mouille pendant qu’elle te sèche.","Les serviettes absorbent l’eau grâce à leurs fibres."],
        ["Qu’est-ce qui a un col mais pas de tête ?","Une bouteille",["Un chat","Un humain","Un hibou"],"Tu peux y boire.","Une bouteille a un col.","Les bouteilles sont en verre ou en plastique."],
        ["Qu’est-ce qui a des dents mais ne peut pas mordre ?","Un peigne",["Un requin","Un chien","Un lion"],"Tu l’utilises pour tes cheveux.","Un peigne a des dents mais pas de bouche.","Les peignes existent depuis des milliers d’années."],
        ["Qu’est-ce qui augmente toujours et ne diminue jamais ?","Ton âge",["Un ascenseur","Un ballon","Un oiseau"],"Chaque année il grandit.","Ton âge augmente à mesure que tu grandis.","À ton anniversaire, une année s’ajoute."],
        ["J’ai un cadran et des aiguilles, mais je ne peux montrer personne du doigt. Qui suis-je ?","Une horloge",["Un robot","Un humain","Un singe"],"Mes aiguilles pointent vers quelque chose.","Une horloge à aiguilles a un cadran et des aiguilles.","Les aiguilles montrent les heures, les minutes et parfois les secondes."],
        ["Qu’est-ce que tu peux briser sans y toucher ?","Une promesse",["Une pierre","Un verre","Une branche"],"C’est une question de confiance.","On peut briser une promesse sans rien toucher.","Les énigmes jouent souvent sur les doubles sens."],
        ["J’ai un chas, mais je ne vois rien. Qui suis-je ?","Une aiguille",["Un hibou","Un humain","Un appareil photo"],"Un fil passe par mon chas.","Une aiguille a un chas pour le fil.","Le chas se trouve en général à une extrémité."],
        ["Qu’est-ce qui grandit quand on lui enlève quelque chose ?","Un trou",["Une montagne","Une boîte","Un livre"],"Pense à creuser.","Plus tu enlèves de terre, plus le trou grandit.","C’est une énigme de logique classique."],
        ["Qu’est-ce qui court sans avoir de jambes ?","L’eau",["Un chien","Un humain","Un cheval"],"Elle coule dans les rivières.","L’eau peut courir sans jambes.","Les énigmes de mots jouent avec plusieurs sens."]
      ],
      verborgen_schatten: [
        ["Avec quoi ouvres-tu un coffre au trésor fermé à clé ?","Avec une clé",["Avec une plume","Avec une carte","Avec une loupe"],"Elle entre dans une serrure.","Avec la bonne clé tu ouvres la serrure.","Les serrures existent depuis des milliers d’années."],
        ["Qu’y a-t-il souvent sur une carte au trésor ?","Une croix pour l’endroit",["Un feu de circulation","Un code-barres","Un thermomètre"],"La croix marque l’endroit.","Une croix marque souvent l’endroit du trésor.","C’est surtout connu grâce aux histoires de pirates."],
        ["À quoi sert une boussole dans une chasse au trésor ?","À trouver la direction",["À peser l’or","À faire de la pluie","À creuser des trous"],"L’aiguille t’aide à trouver le nord.","Une boussole aide à la navigation.","Une boussole classique réagit au champ magnétique de la Terre."],
        ["Qu’est-ce qu’un compartiment secret ?","Un espace caché dans un objet",["Une place ouverte","Un nuage","Une légende de carte"],"Tu ne le vois pas tout de suite.","Un compartiment secret permet de cacher des objets.","Les vieux meubles avaient parfois des tiroirs secrets."],
        ["Qu’est-ce qu’un indice ?","Une information qui te rapproche de la solution",["Toujours la réponse finale","Une erreur","Une décoration"],"Un détective en cherche.","Les indices aident à résoudre un mystère.","Un bon indice donne quelque chose sans tout révéler."],
        ["Pourquoi numérotes-tu parfois tes indices ?","Pour les garder dans l’ordre",["Pour les alourdir","Pour les cacher","Pour changer les couleurs"],"Ainsi tu t’y retrouves mieux.","Numéroter aide à mettre de l’ordre.","Les détectives classent les preuves pour voir les liens."],
        ["Quel endroit a du sens pour un trésor caché dans une histoire ?","Sous une pierre marquée",["Au milieu d’une table animée","Sur un panneau de signalisation","Dans un nuage"],"Il doit être hors de vue.","Dans les histoires, les trésors sont souvent cachés dans des endroits secrets.","Les histoires de trésors utilisent souvent des symboles connus."],
        ["Qu’est-ce qu’un code ?","Un système pour présenter une information de façon cachée",["Une sorte de fruit","Un instrument de musique","Un nuage"],"Tu dois le déchiffrer.","Un code peut cacher une information.","La cryptographie est la science des messages secrets."],
        ["Que veut dire déchiffrer ?","Rendre un code compréhensible",["Enterrer quelque chose","Brûler une carte","Copier une clé"],"Tu cherches le sens derrière les signes.","Déchiffrer, c’est lire une information codée.","Certains codes utilisent des chiffres ou des symboles."],
        ["Pourquoi une carte au trésor aurait-elle une légende ?","Pour expliquer les symboles",["Pour alourdir la carte","Pour faire du bruit","Pour la rendre étanche"],"Une légende te dit ce que signifient les signes.","Les légendes de cartes expliquent les symboles.","Les cartes ordinaires ont aussi des légendes."]
      ],
      natuurmysteries: [
        ["Pourquoi une chenille devient-elle un papillon ?","Grâce à la métamorphose",["Grâce au magnétisme","Grâce à la foudre","Grâce au gel"],"L’animal change au fil de plusieurs étapes de vie.","Les papillons passent par une métamorphose.","De l’œuf on passe par la chenille et la chrysalide au papillon."],
        ["Pourquoi voit-on parfois un arc-en-ciel ?","La lumière est déviée et séparée dans les gouttes d’eau",["Les nuages se colorent","Le Soleil clignote","La Lune le peint"],"Le soleil et la pluie travaillent ensemble.","Les gouttes d’eau dévient et réfléchissent la lumière.","Un arc-en-ciel apparaît à l’opposé du Soleil."],
        ["Pourquoi une luciole brille-t-elle ?","Grâce à la bioluminescence",["Grâce à une pile","En stockant la lumière du Soleil","Grâce à des aimants"],"Elle fabrique de la lumière dans son propre corps.","La bioluminescence est de la lumière née d’une réaction chimique.","Certains animaux marins savent aussi produire leur lumière."],
        ["Pourquoi les flamants roses sont-ils roses ?","À cause des pigments de leur nourriture",["Parce qu’ils naissent peints","Seulement à cause du Soleil","À cause de l’eau froide"],"Leur nourriture contient des pigments.","Les caroténoïdes de leur nourriture colorent les plumes en rose.","Les jeunes flamants sont beaucoup plus gris."],
        ["Pourquoi les jeunes boutons de tournesol suivent-ils souvent le Soleil ?","Grâce à l’héliotropisme",["Grâce à la force du vent","Grâce au magnétisme","Grâce à la pluie"],"Ils réagissent à la lumière.","Les jeunes tournesols peuvent suivre le Soleil.","Les fleurs adultes regardent surtout vers l’est."],
        ["Pourquoi certains animaux ont-ils un camouflage ?","Pour moins se faire remarquer",["Pour grandir plus vite","Pour chanter plus fort","Pour produire plus de chaleur"],"Couleur et motifs ressemblent à l’environnement.","Le camouflage aide à chasser ou à se cacher.","La seiche change d’apparence très vite."],
        ["Qu’est-ce qui provoque surtout les marées ?","La gravité de la Lune",["Les éoliennes","Les volcans","Les nuages"],"La Lune tire sur l’eau des océans.","La Lune est une cause majeure des marées.","Le Soleil influence aussi les marées."],
        ["Pourquoi les flocons de neige ont-ils souvent six branches ?","À cause de la façon dont les molécules d’eau forment des cristaux",["À cause des éoliennes","À cause des oiseaux","À cause du sable"],"La glace forme un motif de cristal fixe.","La structure de la glace conduit souvent à une symétrie à six branches.","Deux grands flocons ne sont jamais exactement pareils."],
        ["Pourquoi le ciel est-il en général bleu le jour ?","La lumière bleue est plus dispersée",["Parce que l’océan peint le ciel","À cause des arbres","À cause des nuages seulement"],"La lumière du Soleil contient plusieurs couleurs.","L’atmosphère disperse fortement la lumière bleue.","Au coucher du Soleil on voit plus de rouge et d’orange."],
        ["Pourquoi les geckos peuvent-ils monter aux murs ?","Des millions de poils minuscules sous leurs doigts",["Des ventouses avec de la colle","Des aimants","De l’électricité"],"Leurs doigts touchent la surface sur une immense étendue.","Des structures microscopiques donnent énormément d’adhérence.","Ces forces s’appellent les forces de van der Waals."]
      ],
      speurtocht: [
        ["À quoi sert une carte d’itinéraire ?","À suivre le chemin",["À manger un puzzle","À mesurer le temps","À faire du bruit"],"La carte montre où tu dois aller.","Une carte d’itinéraire aide à la navigation.","Des symboles peuvent marquer les points importants."],
        ["Qu’est-ce qu’un point de passage ?","Un point convenu sur un itinéraire",["Un mot de passe secret","Une sorte d’animal","Une pièce de monnaie"],"Tu peux naviguer vers lui.","Les points de passage marquent des endroits sur un itinéraire.","Les appareils GPS en utilisent souvent."],
        ["Quel outil t’aide à mieux voir de petits indices ?","Une loupe",["Un marteau","Une cuillère","Un parapluie"],"Elle agrandit les détails.","Une loupe agrandit les petits détails.","Une lentille bombée dévie les rayons de lumière."],
        ["Une empreinte de pas est surtout une…","Trace",["Planète","Instrument","Couleur"],"Un détective en cherche.","Une empreinte de pas peut être une trace.","Les traces peuvent dire qui est passé quelque part."],
        ["Pourquoi regardes-tu bien autour de toi pendant une chasse au trésor ?","Des indices peuvent être cachés",["Pour arrêter le temps","Pour faire de la pluie","Pour grandir plus vite"],"Tout n’est pas au milieu du chemin.","Bien observer est important pendant une recherche.","Les bonnes chasses mêlent observation, réflexion et déplacement."],
        ["Que veut dire « tourne à gauche » sur un itinéraire ?","Tourner vers le côté gauche",["Tout droit","Rentrer à la maison","Monter"],"Pense à ta main gauche.","Tourner à gauche, c’est aller vers la gauche.","Les mots de direction sont importants en navigation."],
        ["Qu’est-ce qu’une coordonnée ?","Une façon de donner un endroit précis",["Une sorte de clé","Une trace d’animal","Une récompense"],"Les cartes et le GPS en utilisent.","Les coordonnées décrivent une position.","La latitude et la longitude en sont des exemples."],
        ["Que fais-tu quand deux indices se contredisent ?","Les vérifier une nouvelle fois",["En choisir un au hasard","Tout jeter","Déchirer la carte"],"Tu as peut-être mal lu quelque chose.","Vérifier aide à trouver les erreurs.","Les bons chercheurs contrôlent leurs informations."],
        ["Pourquoi est-il utile de chercher à plusieurs ?","On peut combiner les idées et les observations",["Parce qu’un des deux ne fait rien","Pour cacher des indices","Pour arrêter le temps"],"Deux paires d’yeux voient plus.","Travailler ensemble peut résoudre les problèmes plus vite.","Les équipes se partagent souvent les tâches."],
        ["À quoi sert le dernier indice ?","À te conduire au dernier endroit",["À te renvoyer à la question 1","À créer un nouveau monde","À effacer l’itinéraire"],"Il te mène à la solution.","Le dernier indice mène en général à l’arrivée ou au trésor.","Une bonne chasse construit pas à pas vers la fin."]
      ]
    },
    dieren: {
      snelle_dieren: [
        ["Quel animal terrestre est le plus rapide ?","Le guépard",["L’éléphant","Le panda","L’hippopotame"],"C’est un félin élancé et tacheté.","Le guépard est l’animal terrestre le plus rapide.","Sur un court sprint il peut dépasser 90 km/h."],
        ["Quel oiseau nage le plus vite ?", "Le manchot", ["Le cygne", "Le canard", "La mouette"], "Il ne sait pas voler, mais il nage très bien.", "Un manchot papou dépasse trente kilomètres à l’heure sous l’eau.", "Ses plumes se recouvrent comme des tuiles, donc l’eau ne passe pas."],
        ["Quel oiseau est célèbre pour ses piqués très rapides ?","Le faucon pèlerin",["Le manchot","La poule","L’autruche"],"Il chasse depuis les airs.","Le faucon pèlerin est un des animaux les plus rapides.","En piqué il peut dépasser 300 km/h."],
        ["Pourquoi un poisson rapide a-t-il un corps profilé ?","Pour avoir moins de résistance",["Pour être plus lourd","Pour chanter plus fort","Pour attraper plus d’air"],"Une forme lisse fend l’eau plus facilement.","Le profilage réduit la résistance de l’eau.","Les dauphins ont aussi une forme profilée."],
        ["Qui court le plus vite : un cheval ou une tortue ?","Le cheval",["La tortue","Aussi vite","Ni l’un ni l’autre"],"Il a de longues pattes puissantes.","Un cheval est bien plus rapide qu’une tortue.","Au galop les chevaux atteignent de grandes vitesses."],
        ["Pourquoi les gazelles ont-elles de longues pattes ?","Pour courir et sauter vite",["Pour nager","Pour creuser","Pour voler"],"Elles vivent dans des plaines ouvertes.","De longues pattes aident les gazelles à fuir vite.","La vitesse les aide à échapper aux prédateurs."],
        ["Quel requin est connu comme un nageur rapide ?","Le requin-mako",["Le requin-baleine","L’hippocampe","Le poisson-lion"],"Il a un corps profilé.","Les requins-makos comptent parmi les requins les plus rapides.","Ils chassent des poissons rapides."],
        ["Qu’est-ce qui aide une autruche à courir vite ?","De longues pattes puissantes",["Des ailes pour voler","Une vessie natatoire","Des griffes pour grimper"],"Elle ne peut pas voler.","Les autruches sont de rapides coureuses.","Elles courent à plusieurs dizaines de kilomètres par heure."],
        ["Pourquoi la vitesse est-elle utile aux proies ?","Pour s’échapper",["Pour faire pousser les arbres","Pour faire du froid","Pour dormir"],"Les prédateurs essaient de les attraper.","La vitesse peut améliorer leurs chances de survie.","Certaines proies font aussi des virages serrés."],
        ["Pourquoi la vitesse est-elle utile aux prédateurs ?","Pour attraper des proies",["Pour arroser les plantes","Pour colorer les plumes","Pour construire des nids"],"Une chasse est souvent très courte.","La vitesse aide pendant la poursuite.","Tous les prédateurs ne comptent pas sur la vitesse ; certains guettent."]
      ],
      baby_dieren: [
        ["Comment appelle-t-on un bébé chien ?","Un chiot",["Un veau","Un poulain","Un poussin"],"Le mot commence par ch.","Un jeune chien s’appelle un chiot.","Les chiots naissent aveugles et sourds."],
        ["Comment appelle-t-on un bébé chat ?","Un chaton",["Un poulain","Un agneau","Un veau"],"C’est un jeune chat.","Un jeune chat s’appelle un chaton.","Les chatons dorment énormément."],
        ["Comment appelle-t-on un jeune cheval ?","Un poulain",["Un chiot","Un poussin","Un lionceau"],"Il se met vite debout.","Un jeune cheval s’appelle un poulain.","Les poulains essaient de se lever juste après la naissance."],
        ["Comment appelle-t-on un jeune mouton ?","Un agneau",["Un veau","Un chiot","Un chaton"],"On en voit souvent au printemps.","Un jeune mouton s’appelle un agneau.","Les agneaux boivent le lait de leur mère."],
        ["Comment appelle-t-on un bébé vache ?","Un veau",["Un poulain","Un agneau","Un poussin"],"On appelle aussi ainsi un jeune éléphant.","Une jeune vache s’appelle un veau.","Les veaux boivent d’abord du lait."],
        ["Comment appelle-t-on un jeune poulet ?","Un poussin",["Un lionceau","Un chiot","Un agneau"],"Il sort d’un œuf.","Un jeune poulet s’appelle un poussin.","Les poussins piaillent déjà avant d’éclore."],
        ["Comment appelle-t-on un jeune lion ?","Un lionceau",["Un poulain","Un veau","Un chaton"],"Les jeunes loups ont aussi leur nom à eux.","Un jeune lion est un lionceau.","Les lionceaux restent longtemps avec le groupe."],
        ["Que boivent d’abord beaucoup de bébés mammifères ?","Du lait",["De l’eau salée","De l’essence","De la limonade"],"C’est leur mère qui le fabrique.","Les mammifères nourrissent leurs petits avec du lait.","C’est une caractéristique importante des mammifères."],
        ["Pourquoi beaucoup de jeunes animaux restent-ils près de leur mère ?","Pour la protection et la nourriture",["Pour voler plus vite","Pour grimper aux arbres","Pour faire du froid"],"Ils ont encore beaucoup à apprendre.","Les parents protègent et nourrissent souvent leurs petits.","La durée de ces soins varie beaucoup selon les espèces."],
        ["Quel bébé animal sort d’un œuf ?","Le poussin",["Le chiot","Le veau","Le poulain"],"Pense à une poule.","Un poussin sort d’un œuf.","Les reptiles, les poissons et bien d’autres animaux pondent aussi des œufs."]
      ],
      waterdieren: [
        ["Quel mammifère vit dans la mer et respire de l’air ?","Le dauphin",["Le thon","Le requin","La méduse"],"Il doit remonter régulièrement.","Les dauphins sont des mammifères et respirent avec des poumons.","Ils utilisent un évent sur le dessus de la tête."],
        ["Quel animal a huit bras ?","La pieuvre",["Le requin","Le dauphin","Le crabe"],"Elle sait très bien se cacher.","Une pieuvre a huit bras.","Les pieuvres sont des mollusques très intelligents."],
        ["Quel animal marin est le plus grand animal de la Terre ?","La baleine bleue",["Le grand requin blanc","Le dauphin","L’orque"],"C’est une baleine énorme.","La baleine bleue est le plus grand animal connu.","Elle peut dépasser 25 mètres de long."],
        ["Comment respirent la plupart des poissons ?","Avec des branchies",["Avec des poumons","Par la peau","Avec des plumes"],"Ils prennent l’oxygène de l’eau.","Les branchies captent l’oxygène de l’eau.","L’eau passe le long des lamelles branchiales."],
        ["Qu’est-ce qui aide les poissons à se diriger et à nager ?","Les nageoires",["Les ailes","Les pattes","Les poils"],"Elles sont sur le dos, le ventre et la queue.","Les nageoires aident au mouvement et à l’équilibre.","La nageoire caudale donne souvent beaucoup de poussée."],
        ["Quel animal peut vivre dans la mer et sur la terre ?","La tortue marine",["Le thon","La méduse","L’hippocampe"],"Elle vient à terre pour pondre.","Les tortues marines vivent en mer mais pondent sur la terre.","Les femelles reviennent souvent sur la plage où elles sont nées."],
        ["Qu’est-ce que le corail en réalité ?","Une colonie de petits animaux",["Une plante","Une pierre","Un poisson"],"Il forme des récifs.","Les coraux sont faits de très nombreux petits polypes.","Les récifs coralliens sont des habitats importants."],
        ["Pourquoi les baleines remontent-elles à la surface ?","Pour respirer",["Pour laver leurs branchies","Pour dormir sur la plage","Pour faire la cuisine"],"Ce sont des mammifères.","Les baleines respirent de l’air avec des poumons.","Elles respirent par leurs évents."],
        ["Quel animal a une carapace dure et marche de côté ?","Le crabe",["Le dauphin","La méduse","Le calmar"],"On en voit souvent sur les plages.","Les crabes ont un squelette externe dur.","Beaucoup de crabes se déplacent facilement de côté."],
        ["Pourquoi un corps profilé est-il utile dans l’eau ?","Il réduit la résistance",["Il fait plus de bruit","Il alourdit l’animal","Il réchauffe l’eau"],"Les animaux glissent mieux dans l’eau.","Le profilage aide à nager plus efficacement.","Les dauphins et les requins en sont de beaux exemples."]
      ],
      jungle: [
        ["Quel animal se balance souvent dans les arbres ?","Le singe",["L’éléphant","Le manchot","Le zèbre"],"Il grimpe grâce aux branches.","Beaucoup d’espèces de singes vivent dans les arbres.","Certains singes utilisent leur queue comme prise supplémentaire."],
        ["Quel animal a un grand bec coloré ?","Le toucan",["Le tigre","Le gorille","Le crocodile"],"C’est un oiseau tropical.","Les toucans ont des becs spectaculaires.","Leur bec est étonnamment léger."],
        ["Quel grand animal vit dans les forêts tropicales et mange beaucoup de plantes ?","Le gorille",["Le manchot","Le chameau","L’ours polaire"],"C’est un grand singe.","Les gorilles vivent dans les forêts africaines.","Ils mangent surtout des plantes."],
        ["Pourquoi beaucoup d’animaux de la jungle ont-ils un camouflage ?","Pour moins se faire remarquer",["Pour chanter plus fort","Pour faire plus de pluie","Pour grandir plus vite"],"Les motifs ressemblent aux feuilles et aux ombres.","Le camouflage aide à chasser ou à se cacher.","Les taches de beaucoup de jaguars imitent des ombres."],
        ["Quel grand félin vit dans les jungles d’Amérique ?","Le jaguar",["Le lion","La panthère des neiges","Le lynx"],"Il a des rosettes sur le pelage.","Les jaguars vivent dans des régions d’Amérique centrale et du Sud.","Ils nagent remarquablement bien."],
        ["Pourquoi les arbres de la forêt tropicale sont-ils si importants ?","Ils donnent nourriture et logement",["Ils ne font pas d’oxygène","Ils arrêtent toute la pluie","Ils ne sont que décoratifs"],"Beaucoup d’animaux vivent dans différentes couches d’arbres.","Les arbres de la forêt tropicale forment des habitats complexes.","Certains animaux ne descendent presque jamais au sol."],
        ["Quel reptile peut changer de couleur ?","Le caméléon",["La tortue","Le crocodile","Le serpent"],"Il utilise aussi la couleur pour communiquer.","Les caméléons peuvent adapter leur motif de couleur.","Le changement de couleur aide pour la température et les signaux."],
        ["Qu’est-ce qu’une forêt tropicale humide ?","Une forêt chaude où il pleut beaucoup",["Un désert gelé","Une prairie sans arbres","Une mer"],"Elle est très riche en espèces.","Les forêts tropicales humides reçoivent énormément de pluie.","Ce sont des milieux parmi les plus riches en espèces."],
        ["Pourquoi les singes hurleurs crient-ils si fort ?","Pour communiquer avec leur groupe",["Pour faire de la pluie","Pour pousser les arbres","Pour nager"],"Leur cri porte loin dans la forêt.","Les singes hurleurs communiquent par des cris puissants.","Une structure de gorge élargie amplifie le cri."],
        ["Quel animal attrape des insectes avec une longue langue ?","Le caméléon",["L’éléphant","Le gorille","Le toucan"],"La langue jaillit très vite.","Les caméléons attrapent leurs proies avec leur longue langue.","La langue peut accélérer extrêmement vite."]
      ]
    },
    aarde: {
      continenten_landen: [
        ["Sur quel continent se trouvent les Pays-Bas ?","L’Europe",["L’Afrique","L’Asie","L’Amérique du Sud"],"Pense aux pays voisins.","Les Pays-Bas se trouvent en Europe.","L’Europe est un des sept continents."],
        ["Quel est le plus grand continent ?","L’Asie",["L’Europe","L’Afrique","L’Australie"],"La Chine et l’Inde s’y trouvent.","L’Asie est le plus grand continent.","Plus de la moitié des humains vivent en Asie."],
        ["Sur quel continent se trouve le Brésil ?","L’Amérique du Sud",["L’Afrique","L’Europe","L’Asie"],"Pense à l’Amazone.","Le Brésil se trouve en Amérique du Sud.","Le Brésil est le plus grand pays d’Amérique du Sud."],
        ["Sur quel continent se trouve la plus grande partie de l’Égypte ?","L’Afrique",["L’Europe","L’Asie","L’Amérique du Nord"],"Le Nil la traverse.","L’Égypte se trouve en grande partie en Afrique.","La péninsule du Sinaï appartient géographiquement à l’Asie."],
        ["Quelle est la capitale de la France ?","Paris",["Rome","Madrid","Berlin"],"La tour Eiffel s’y trouve.","Paris est la capitale de la France.","La Seine traverse Paris."],
        ["Quelle est la capitale de l’Italie ?","Rome",["Milan","Venise","Naples"],"Le Colisée s’y trouve.","Rome est la capitale de l’Italie.","Le Vatican se trouve à l’intérieur de Rome."],
        ["Quel pays a la forme d’une botte ?","L’Italie",["Le Portugal","La Norvège","La Pologne"],"Regarde le sud de l’Europe.","L’Italie ressemble à une botte.","La Sicile se trouve près de la pointe."],
        ["Quel océan se trouve entre l’Europe et l’Amérique ?","L’océan Atlantique",["L’océan Pacifique","L’océan Indien","L’océan Arctique"],"Les navires le traversent.","L’océan Atlantique se trouve entre l’Europe, l’Afrique et l’Amérique.","C’est le deuxième océan du monde."],
        ["Quel continent se trouve au pôle Sud ?","L’Antarctique",["L’Europe","L’Afrique","L’Asie"],"Il est couvert de glace.","L’Antarctique entoure le pôle Sud.","C’est le continent le plus froid."],
        ["Quel pays se trouve directement à l’est des Pays-Bas ?","L’Allemagne",["L’Espagne","L’Irlande","L’Italie"],"C’est un pays voisin.","L’Allemagne a une frontière avec les Pays-Bas.","Les Pays-Bas ont aussi une frontière avec la Belgique."]
      ],
      weer_klimaat: [
        ["Que mesure un thermomètre ?","La température",["La direction du vent","La quantité de pluie","La pression de l’air"],"Le chaud ou le froid.","Un thermomètre mesure la température.","Nous utilisons souvent les degrés Celsius."],
        ["Qu’est-ce que les précipitations ?","De l’eau qui tombe du ciel",["Le vent","La lumière du Soleil","Le brouillard"],"La pluie et la neige en sont des exemples.","Les précipitations peuvent être pluie, neige ou grêle.","Elles naissent de l’eau contenue dans les nuages."],
        ["Qu’est-ce que le vent ?","De l’air en mouvement",["De l’eau en mouvement","Du sable chaud","Un nuage"],"Tu le sens mais tu ne le vois pas.","Le vent est de l’air qui se déplace.","Les différences de pression créent une grande partie du vent."],
        ["Pourquoi le brouillard se forme-t-il souvent ?","La vapeur d’eau se condense près du sol",["À cause des étoiles","À cause du sable","À cause des aimants"],"On voit moins bien.","Le brouillard est fait de minuscules gouttelettes d’eau dans l’air.","Le brouillard est en fait un nuage au niveau du sol."],
        ["Qu’est-ce que le climat ?","Le temps moyen sur une longue période",["Le temps qu’il fait aujourd’hui","Un orage","Un pluviomètre"],"Il s’agit d’années, pas d’un seul jour.","Le climat décrit le temps typique sur une longue période.","Le temps peut beaucoup changer d’un jour à l’autre."],
        ["Qu’est-ce qui provoque un éclair ?","Une décharge électrique",["Une étoile filante","Un avion","Un arc-en-ciel"],"Cela arrive souvent avec les nuages d’orage.","Un éclair est une énorme décharge électrique.","L’air autour devient extrêmement chaud."],
        ["Pourquoi entends-tu le tonnerre après l’éclair ?","La lumière va plus vite que le son",["Le tonnerre commence plus tard","Les nuages attendent","Le Soleil bloque le son"],"Tu vois l’éclair en premier.","La lumière t’atteint bien plus vite que le son.","L’écart de temps aide à estimer la distance de l’orage."],
        ["Quel nuage accompagne souvent les fortes averses et l’orage ?","Le cumulonimbus",["Le cirrus","Le brouillard","Aucun nuage"],"Il peut devenir très haut.","Les cumulonimbus peuvent apporter des orages.","Ils ont souvent une forme d’enclume au sommet."],
        ["Qu’est-ce qu’une canicule ?","Une période de chaleur inhabituelle",["Une averse de neige soudaine","Un tremblement de terre","Une grosse vague en mer"],"Elle dure plusieurs jours.","Une canicule est une longue période de temps très chaud.","Les définitions varient d’un pays à l’autre."],
        ["Qu’est-ce que le gel ?","Une température sous zéro",["Un vent fort","Une pluie très forte","Un brouillard épais"],"L’eau peut alors geler.","Avec le gel, la température descend vers 0 °C ou en dessous.","Le givre se forme quand la vapeur d’eau gèle."]
      ],
      oceanen_natuur: [
        ["Qu’est-ce qui recouvre la plus grande partie de la Terre ?","L’eau",["Le désert","La forêt","La glace"],"Les océans occupent énormément de place.","Environ 71% de la Terre est couverte d’eau.","La plus grande partie est de l’eau de mer salée."],
        ["Quel océan est le plus grand ?","L’océan Pacifique",["L’océan Atlantique","L’océan Indien","L’océan Arctique"],"Il se trouve entre l’Asie et l’Amérique.","Le Pacifique est le plus grand océan.","Il couvre environ un tiers de la surface de la Terre."],
        ["Comment appelle-t-on la roche fondue qui sort d’un volcan ?","La lave",["Le magma","L’argile","Le sable"],"Hors de la Terre on l’appelle ainsi.","À la surface, la roche fondue s’appelle de la lave.","Sous terre on parle de magma."],
        ["Qu’est-ce qu’une île ?","Une terre entièrement entourée d’eau",["Un nuage élevé","Une rivière","Un désert"],"Tu dois traverser l’eau pour y aller.","Une île est entourée d’eau de tous les côtés.","Le Groenland est la plus grande île qui n’est pas un continent."],
        ["Qu’est-ce qu’une chaîne de montagnes ?","Une série de montagnes",["Un large fleuve","Une mer","Un groupe d’îles"],"Les Alpes en sont une.","Une chaîne de montagnes est faite de montagnes reliées.","L’Himalaya contient les plus hautes montagnes de la Terre."],
        ["Qu’est-ce que l’embouchure d’un fleuve ?","L’endroit où le fleuve se termine",["La source du fleuve","Un sommet de montagne","Un désert"],"Le fleuve se jette souvent dans une mer ou un lac.","L’embouchure est la fin d’un fleuve.","Certains fleuves forment un delta à leur embouchure."],
        ["Qu’est-ce qu’un désert ?","Une région avec très peu de précipitations",["Toujours une plage chaude","Une forêt tropicale","Un océan"],"Tous les déserts ne sont pas chauds.","Les déserts reçoivent très peu de précipitations.","Techniquement, l’Antarctique est aussi un désert."],
        ["Qu’est-ce qu’un glacier ?","Une masse de glace qui avance lentement",["Un nuage","Un fleuve de lave","Une dune de sable"],"Il se forme de neige comprimée.","Les glaciers avancent lentement sous leur propre poids.","Ils façonnent des vallées et des paysages."],
        ["Qu’est-ce que l’érosion ?","L’usure et le déplacement de la roche et du sol",["Des arbres qui poussent","Des étoiles qui naissent","De l’air qui gèle"],"L’eau et le vent peuvent la provoquer.","L’érosion transforme les paysages.","Les rivières peuvent creuser des vallées profondes."],
        ["Qu’est-ce qu’un delta ?","Une zone où un fleuve se divise à son embouchure",["Un sommet de montagne","Un courant marin","Un nuage"],"On y trouve parfois des terres fertiles.","Un delta se forme avec les sédiments déposés.","Le delta du Nil est un exemple connu."]
      ],
      kaarten_navigatie: [
        ["Que montre une rose des vents ?","Les directions",["La température","L’altitude","Les fuseaux horaires"],"Nord, est, sud et ouest.","Une rose des vents montre les directions.","Les cartes utilisent souvent N, E, S et O."],
        ["À quoi sert la légende d’une carte ?","À expliquer les symboles",["À décorer la carte","À mesurer les distances","À faire du vent"],"Les couleurs et les signes prennent un sens.","La légende explique les symboles de la carte.","Une ligne bleue peut représenter une rivière, par exemple."],
        ["Qu’est-ce que l’échelle d’une carte ?","Le rapport entre la distance sur la carte et la distance réelle",["Un instrument de musique","Un thermomètre","Un code de couleurs"],"1 cm peut signifier 1 km, par exemple.","L’échelle rend les distances de la carte compréhensibles.","Une grande échelle montre en général plus de détails."],
        ["Que sont des coordonnées ?","Des nombres ou des valeurs qui indiquent un endroit",["Une sorte de nuage","Une pièce de monnaie","Une rivière"],"Le GPS les utilise.","Les coordonnées décrivent une position.","La latitude et la longitude sont des coordonnées connues."],
        ["Quelle direction est opposée au nord ?","Le sud",["L’est","L’ouest","Le nord-est"],"Pense à la rose des vents.","Le sud est opposé au nord.","L’est et l’ouest sont perpendiculaires au nord et au sud."],
        ["Quelle direction se trouve à ta droite quand tu regardes le nord ?","L’est",["L’ouest","Le sud","Le nord"],"Sur beaucoup de cartes le nord est en haut.","Avec le nord en haut, l’est est à droite.","C’est pour cela que l’ouest est à gauche sur une telle carte."],
        ["Qu’est-ce qu’une carte topographique ?","Une carte avec le relief et les altitudes",["Une carte du ciel","Un menu","Une frise du temps"],"Elle peut avoir des courbes de niveau.","Les cartes topographiques montrent le paysage et l’altitude.","Les randonneurs les utilisent souvent."],
        ["Qu’est-ce que le GPS ?","Un système de satellites pour trouver une position",["Une sorte de nuage","Un volcan","Une boussole sans satellites"],"Ton téléphone peut l’utiliser.","Le GPS utilise des signaux de satellites pour trouver ta position.","Il faut plusieurs satellites pour une position précise."],
        ["Pourquoi le nord est-il souvent en haut des cartes ?","C’est une habitude très répandue",["Parce que le nord est plus haut","Parce que le Soleil y est toujours","Parce que les rivières y coulent"],"C’est une convention, pas une loi de la nature.","Beaucoup de cartes modernes mettent le nord en haut.","Les cartes anciennes étaient parfois orientées autrement."],
        ["Qu’est-ce qu’un itinéraire ?","Un chemin prévu du départ à l’arrivée",["Un nuage de pluie","Une montagne","Une frontière"],"La navigation t’aide à le suivre.","Un itinéraire décrit comment aller de A à B.","Les cartes numériques calculent les itinéraires toutes seules."]
      ]
    }
  };

  window.KWIZILLO_QUESTIONS_FR = window.KWIZILLO_BUILD_BANK(defs, window.KWIZILLO_EXTRA_FR||{}, window.KWIZILLO_MORE_FR||{});
})();
