(() => {
  // Generated by tools/content-build.cjs from content/. Do not edit by hand:
  // change the question in content/<world>/<topic>.json and run the tool again.
  // Rows continue after the twenty a topic already has, and each one states its
  // own difficulty in the seventh field.
  window.KWIZILLO_MORE_EN = {
    ruimte: {
      zonnestelsel: [
        ['Which star sits at the centre of our solar system?','The sun',['The North Star','Sirius','The moon'],'You see it every day when it gets light.','The sun is the star that all the planets circle.','The sun is so big that more than a million earths would fit inside.',1],
        ['What travels around the sun?','The planets',['Only the moon','All the stars','Nothing'],'Our earth is one of them.','All eight planets travel in an orbit around the sun.','Comets and asteroids circle the sun too, in much longer loops.',1],
        ['Which planet comes after earth, further from the sun?','Mars',['Venus','Mercury','The moon'],'It is the planet with the rusty red colour.','After earth comes Mars, which is further from the sun.','Mars is about half the size of earth.',1],
        ['Why does it get dark at night?','Because the earth turns',['Because the sun goes out','Because the moon eats it','Because a cloud moves in'],'The sun keeps on shining.','The earth turns, so your spot faces away from the sun for a while.','The earth turns all the way round in twenty-four hours.',1],
        ['Which of the eight planets is the smallest?','Mercury',['Mars','Venus','Earth'],'It is also the closest one to the sun.','Mercury is the smallest planet in our solar system.','There it is freezing at night and scorching by day.',1],
        ['How long does the earth take to circle the sun once?','About a year',['A month','A week','A day'],'Exactly as long as the gap between two birthdays.','The earth takes about 365 days to go round the sun once.','Every four years we add a day: that is a leap year.',2],
        ['What is Pluto called since 2006?','A dwarf planet',['A moon','A comet','A star'],'It is too small to count as a normal planet.','Since 2006 Pluto has been called a dwarf planet.','There are more: Ceres, Eris and Makemake are dwarf planets too.',2],
        ['Which two planets are made mostly of gas?','Jupiter and Saturn',['Earth and Mars','Mercury and Venus','Mars and Venus'],'They are the two biggest.','Jupiter and Saturn are gas giants: you could not stand on them.','Deep inside, those gases are squeezed until they act like a liquid.',2],
        ['Why does it sometimes go dark during the day?','The moon covers the sun',['The sun switches off','The earth stops turning','The sun drops behind hills'],'Something comes between you and the sun.','The moon moves right between the sun and the earth, and it turns dusky.','Never look at the sun without special glasses, not even in an eclipse.',2],
        ['Where can you jump the highest?','On the moon',['On earth','On the seabed','In an aeroplane'],'Gravity pulls much more gently there.','The moon pulls on you far less, so you jump six times as high.','The Apollo astronauts hopped along because walking did not work.',2],
        ['How old is our solar system?','About 4.6 billion years',['About 1 million years','About 100 million years','About 500 billion years'],'Much older than the dinosaurs, and they lived a very long time ago.','The sun and the planets formed from a cloud of gas and dust.','The oldest pieces of it we have fell to earth as meteorites.',3],
        ['Which moon of Jupiter is covered in volcanoes?','Io',['Europa','Ganymede','Callisto'],'It is the closest of the four to Jupiter, which squeezes it.','Io has more volcanoes than anywhere else in our solar system.','Jupiter kneads Io so hard that the moon melts inside.',3],
        ['What are the rings of Saturn made of?','Ice and rock',['Gas and steam','Dust and cloud','Liquid water'],'Think of billions of snowballs in a row.','The rings are billions of chunks of ice and rock, from grains to houses.','The rings are thousands of kilometres wide but often ten metres thick.',3],
        ['Which planet has the strongest winds?','Neptune',['Earth','Mars','Mercury'],'The further from the sun, the colder and wilder the weather.','Neptune has the fastest winds anywhere: almost 2000 kilometres an hour.','The fastest storm on earth does not reach a quarter of that.',3],
        ['What is the largest volcano in our solar system called?','Olympus Mons',['Mount Everest','Mount Vesuvius','Mauna Kea'],'It is not on earth, but on the red planet.','Olympus Mons on Mars is almost three times as tall as Mount Everest.','It is as wide as France: on top you would not even see the slope.',3],
        ['On which planet does one day last longer than one year?','Venus',['Mercury','Mars','Uranus'],'This planet spins very slowly but orbits quickly.','Venus turns once in 243 days and circles the sun in 225.','Venus also spins the wrong way: there the sun rises in the west.',4],
        ['Which space probe was the first to leave our solar system?','Voyager 1',['Hubble','Cassini','Apollo 11'],'It left in 1977 and is still flying.','In 2012 Voyager 1 was the first to reach the space between the stars.','It carries a golden record with music and greetings from earth.',4],
        ['How much of all the weight in our solar system is in the sun?','More than 99 percent',['About half','About a tenth','Less than 1 percent'],'Almost all of it, and the planets are the rest.','The sun is so heavy that all the planets together stay under one percent.','That is exactly why all the planets keep circling the sun.',4],
        ['Which planet was worked out on paper before anyone saw it?','Neptune',['Uranus','Saturn','Pluto'],'Astronomers noticed something tugging at Uranus.','In 1846 they calculated where it had to be, and there it was.','The telescope found it that very night, almost exactly as predicted.',4],
        ['What is the shell of icy lumps around our solar system called?','The Oort cloud',['The Kuiper belt','The asteroid belt','The Milky Way'],'It is named after a Dutch astronomer.','The Oort cloud is a ball of icy lumps, far beyond all the planets.','That is where the comets come from that appear once in a thousand years.',4]
      ]
    }
  };
})();
