(() => {
  // Generated by tools/content-build.cjs from content/. Do not edit by hand:
  // change the question in content/<world>/<topic>.json and run the tool again.
  // Rows continue after the twenty a topic already has, and each one states its
  // own difficulty in the seventh field.
  window.KWIZILLO_MORE_DA = {
    ruimte: {
      zonnestelsel: [
        ['Hvilken stjerne står midt i vores solsystem?','Solen',['Nordstjernen','Sirius','Månen'],'Du ser den hver dag, når det bliver lyst.','Solen er den stjerne, som alle planeterne kredser om.','Solen er så stor, at der er plads til mere end en million jordkloder.',1],
        ['Hvad kredser om Solen?','Planeterne',['Kun Månen','Alle stjernerne','Ingenting'],'Vores jord er en af dem.','Alle otte planeter kredser i en bane om Solen.','Kometer og asteroider kredser også, bare i meget længere ture.',1],
        ['Hvilken planet kommer efter Jorden, længere ude?','Mars',['Venus','Merkur','Månen'],'Det er planeten med den rustrøde farve.','Efter Jorden kommer Mars, længere væk fra Solen.','Mars er omkring halvt så stor som Jorden.',1],
        ['Hvorfor bliver det mørkt om natten?','Fordi Jorden drejer rundt',['Fordi Solen går ud','Fordi Månen spiser den','Fordi en sky skygger'],'Solen bliver bare ved med at skinne.','Jorden drejer, og dit sted vender væk fra Solen et stykke tid.','Jorden drejer en hel gang rundt på fireogtyve timer.',1],
        ['Hvilken af de otte planeter er mindst?','Merkur',['Mars','Venus','Jorden'],'Den er også tættest på Solen.','Merkur er den mindste planet i vores solsystem.','Der er iskoldt om natten og glohedt om dagen.',1],
        ['Hvor lang tid bruger Jorden på en tur om Solen?','Cirka et år',['En måned','En uge','En dag'],'Lige så længe som mellem to fødselsdage.','Jorden bruger omkring 365 dage på en tur om Solen.','Hvert fjerde år lægger vi en dag til: det er et skudår.',2],
        ['Hvad er Pluto siden 2006?','En dværgplanet',['En måne','En komet','En stjerne'],'Den er for lille til en rigtig planet.','Siden 2006 hedder Pluto en dværgplanet.','Der er flere: Ceres, Eris og Makemake er det også.',2],
        ['Hvilke to planeter består mest af gas?','Jupiter og Saturn',['Jorden og Mars','Merkur og Venus','Mars og Venus'],'Det er de to største.','Jupiter og Saturn er gaskæmper: man kan ikke stå på dem.','Dybt inde bliver gassen presset, så den opfører sig som væske.',2],
        ['Hvorfor bliver det nogle gange mørkt midt på dagen?','Månen dækker for Solen',['Solen går kort ud','Jorden stopper med at dreje','Solen falder bag bjerge'],'Noget kommer ind mellem dig og Solen.','Månen skubber sig ind mellem Solen og Jorden, og lyset dæmpes.','Kig aldrig på Solen uden særlige briller, heller ikke i en formørkelse.',2],
        ['Hvor kan du springe højest?','På Månen',['På Jorden','På havbunden','I et fly'],'Der trækker tyngdekraften meget blidere.','Månen trækker meget mindre i dig, så du springer seks gange så højt.','Apollo-astronauterne hoppede afsted, fordi det ikke gik at gå.',2],
        ['Hvor gammelt er vores solsystem?','Cirka 4,6 milliarder år',['Cirka 1 million år','Cirka 100 millioner år','Cirka 500 milliarder år'],'Meget ældre end dinosaurerne, og de er allerede ældgamle.','Solen og planeterne blev til af en sky af gas og støv.','De ældste stumper, vi har af det, faldt ned som meteoritter.',3],
        ['Hvilken af Jupiters måner er fuld af vulkaner?','Io',['Europa','Ganymedes','Callisto'],'Den er tættest på Jupiter, som ælter den.','Io har flere vulkaner end noget andet sted i solsystemet.','Jupiter ælter Io så hårdt, at månen smelter indeni.',3],
        ['Hvad består Saturns ringe af?','Is og sten',['Gas og damp','Støv og skyer','Flydende vand'],'Tænk på milliarder af snebolde på række.','Ringene er milliarder af stykker is og sten, fra korn til huse.','Ringene er tusinder af kilometer brede, men tit kun ti meter tykke.',3],
        ['Hvilken planet har den stærkeste vind?','Neptun',['Jorden','Mars','Merkur'],'Jo længere fra Solen, jo koldere og vildere vejr.','På Neptun blæser det næsten 2000 kilometer i timen.','Den hurtigste storm på Jorden når ikke engang en fjerdedel.',3],
        ['Hvad hedder den største vulkan i solsystemet?','Olympus Mons',['Mount Everest','Vesuv','Mauna Kea'],'Den står ikke på Jorden, men på den røde planet.','Olympus Mons på Mars er næsten tre gange så høj som Mount Everest.','Den er så bred som Frankrig: oppe på den ville du ikke se skråningen.',3],
        ['På hvilken planet varer en dag længere end et år?','Venus',['Merkur','Mars','Uranus'],'Denne planet drejer meget langsomt om sig selv.','Venus drejer en gang rundt på 243 dage og om Solen på 225.','Venus drejer også den forkerte vej: der står Solen op i vest.',4],
        ['Hvilken rumsonde forlod solsystemet først?','Voyager 1',['Hubble','Cassini','Apollo 11'],'Den tog af sted i 1977 og flyver stadig.','I 2012 nåede Voyager 1 som den første rummet mellem stjernerne.','Den har en guldplade med musik og hilsener fra Jorden.',4],
        ['Hvor meget af solsystemets vægt sidder i Solen?','Mere end 99 procent',['Cirka halvdelen','Cirka en tiendedel','Mindre end 1 procent'],'Næsten det hele, og planeterne er resten.','Solen er så tung, at alle planeterne tilsammen ikke når én procent.','Netop derfor bliver planeterne ved med at kredse om den.',4],
        ['Hvilken planet blev først regnet ud og så set?','Neptun',['Uranus','Saturn','Pluto'],'Astronomerne mærkede, at noget trak i Uranus.','I 1846 regnede man ud, hvor den måtte stå, og der stod den.','Teleskopet fandt den samme nat, næsten præcis hvor den skulle være.',4],
        ['Hvad hedder skallen af isklumper om vores solsystem?','Oort-skyen',['Kuiperbæltet','Asteroidebæltet','Mælkevejen'],'Den er opkaldt efter en nederlandsk astronom.','Oort-skyen er en kugle af isklumper, langt uden for alle planeter.','Derfra kommer de kometer, som kun kommer forbi hvert tusinde år.',4]
      ]
    }
  };
})();
