(() => {
  // Spanish bank (Spain). Same worlds, topics, order and therefore the same
  // question ids as the other banks, so progress, cards and the per-question
  // illustrations survive a language switch.
  const defs = {
    ruimte: {
      zonnestelsel: [
        ["¿Qué planeta está más cerca del Sol?","Mercurio",["Venus","Marte","la Tierra"],"Es el planeta más pequeño y está justo delante.","Mercurio es el planeta más cercano al Sol.","Un año en Mercurio dura solo 88 días terrestres."],
        ["¿Qué planeta es nuestro planeta de origen?","la Tierra",["Venus","Marte","Júpiter"],"Aquí viven personas, animales y plantas.","Vivimos en la Tierra.","Alrededor del 71% de la Tierra está cubierta de agua."],
        ["¿Qué planeta se conoce como el planeta rojo?","Marte",["Venus","Saturno","Neptuno"],"Su suelo tiene mucho óxido de hierro.","A Marte lo llaman el planeta rojo.","Marte tiene dos lunas pequeñas: Fobos y Deimos."],
        ["¿Qué planeta tiene los anillos más famosos?","Saturno",["la Tierra","Mercurio","Marte"],"Es un gigante gaseoso enorme.","Saturno tiene un sistema de anillos impresionante.","Los anillos son sobre todo hielo y roca."],
        ["¿Cuál es el planeta más grande de nuestro sistema solar?","Júpiter",["Marte","Venus","la Tierra"],"Tiene la famosa Gran Mancha Roja.","Júpiter es el planeta más grande.","Dentro de Júpiter cabrían más de mil Tierras."],
        ["¿Qué planeta está más lejos del Sol?","Neptuno",["Júpiter","la Tierra","Venus"],"Es un gigante de hielo azul y lejano.","Neptuno es el planeta más alejado del Sol.","Un año en Neptuno dura unos 165 años terrestres."],
        ["¿Qué planeta está entre Venus y Marte?","la Tierra",["Mercurio","Júpiter","Saturno"],"Es nuestro propio planeta.","El orden es Venus, la Tierra, Marte.","La Tierra es el tercer planeta desde el Sol."],
        ["¿Qué gira alrededor de la Tierra?","la Luna",["Júpiter","el Sol","Marte"],"La ves muchas veces en el cielo nocturno.","La Luna gira alrededor de la Tierra.","La Luna tarda unos 27 días en dar una vuelta."],
        ["¿Cuántos planetas tiene nuestro sistema solar?","8",["7","9","10"],"Plutón hoy cuenta como planeta enano.","Nuestro sistema solar tiene ocho planetas.","Desde 2006 Plutón se clasifica como planeta enano."],
        ["¿Qué planeta es famoso por su fuerte color azul?","Neptuno",["Mercurio","Marte","Venus"],"Es un gigante de hielo lejano.","Neptuno se ve de un azul profundo.","El metano de su atmósfera refuerza el color azul."]
      ],
      sterren_planeten: [
        ["¿Qué es el Sol?","Una estrella",["Un planeta","Una luna","Un cometa"],"Fabrica su propia luz y su calor.","El Sol es una estrella.","La luz del Sol tarda unos 8 minutos en llegar a la Tierra."],
        ["¿De qué está hecha sobre todo una estrella?","De gas muy caliente y plasma",["De roca fría","De una luna","De una nube"],"Las estrellas brillan por sí solas.","Las estrellas están hechas de gas extremadamente caliente y plasma.","Nuestro Sol es una estrella de tamaño medio."],
        ["¿Qué es una galaxia?","Un grupo enorme de estrellas",["Un planeta","Un telescopio","Una nube en la Tierra"],"La Vía Láctea es una de ellas.","Una galaxia contiene muchísimas estrellas.","La Vía Láctea tiene cientos de miles de millones de estrellas."],
        ["¿Cómo se llama nuestra galaxia?","La Vía Láctea",["Andrómeda","Orión","Saturno"],"A veces ves una banda pálida en un cielo oscuro.","Nuestro sistema solar está dentro de la Vía Láctea.","La Vía Láctea es una galaxia espiral."],
        ["¿Qué es una supernova?","Una explosión enorme de una estrella",["Una luna nueva","Un lanzamiento de cohete","Un chaparrón"],"Ocurre al final de la vida de algunas estrellas.","Una supernova es una explosión gigantesca de una estrella.","Esa explosión puede brillar muchísimo durante un tiempo corto."],
        ["¿De qué color son normalmente las estrellas más calientes?","Azules",["Rojas","Marrones","Verdes"],"Piensa en la llama más caliente de un fogón de gas.","Las estrellas muy calientes suelen verse azuladas.","Las estrellas rojas suelen ser más frías que las azules."],
        ["¿Qué es un exoplaneta?","Un planeta que gira alrededor de otra estrella",["Una luna de la Tierra","Un cometa","Un satélite"],"No gira alrededor de nuestro Sol.","Un exoplaneta gira alrededor de una estrella distinta del Sol.","Ya se han descubierto miles de exoplanetas."],
        ["¿Qué es un agujero negro?","Una zona con una gravedad extremadamente fuerte",["Un planeta oscuro","Una nube","Un motor de cohete"],"Ni siquiera la luz escapa fácilmente.","Un agujero negro tiene una gravedad extremadamente fuerte.","Muchos agujeros negros nacen de estrellas muy pesadas."],
        ["¿Qué estrella está más cerca de la Tierra?","El Sol",["Sirio","la estrella Polar","Betelgeuse"],"La ves todos los días.","El Sol es nuestra estrella más cercana.","La siguiente estrella está muchísimo más lejos."],
        ["¿Por qué parece que las estrellas parpadean?","Por la atmósfera",["Porque se encienden y apagan","Por sus lunas","Porque giran"],"Su luz se curva al pasar por capas de aire.","La atmósfera hace temblar un poco la luz de las estrellas.","Los planetas suelen parpadear menos que las estrellas."]
      ],
      astronauten: [
        ["¿Cómo se llama alguien que viaja al espacio?","Astronauta",["Arqueólogo","Buceador","Capitán"],"Esa persona lleva muchas veces un traje espacial.","Un astronauta viaja y trabaja en el espacio.","Los astronautas entrenan muchas veces durante años."],
        ["¿Por qué llevan traje espacial los astronautas fuera de la nave?","Para tener aire y protección",["Para el calor","Para la velocidad","Como uniforme"],"En el espacio no se puede respirar sin más.","Un traje espacial da oxígeno y protección.","También protege de temperaturas extremas."],
        ["¿Qué sienten a menudo los astronautas en una estación espacial?","Ingravidez",["Lluvia fuerte","Viento fuerte","Terremotos"],"Parece que flotan.","En órbita los astronautas viven en microgravedad.","Todo hay que sujetarlo para que no salga flotando."],
        ["¿Dónde duermen normalmente los astronautas en la estación espacial?","En sacos de dormir sujetos",["En camas normales","En hamacas fuera","En el suelo"],"Si no, saldrían flotando.","Los astronautas duermen en sacos de dormir sujetos a la pared.","En microgravedad no hay un arriba ni un abajo de verdad."],
        ["¿Por qué entrenan los astronautas bajo el agua?","Para imitar la ingravidez",["Para nadar más rápido","Para buscar agua lunar","Para relajarse"],"Bajo el agua puedes practicar movimientos flotando.","El entrenamiento bajo el agua sirve para ensayar los paseos espaciales.","En piscinas enormes hay a veces maquetas de la estación."],
        ["¿Qué es un paseo espacial?","Trabajo fuera de la nave espacial",["Caminar por la Tierra","Correr dentro de un cohete","Pasear por un museo"],"El astronauta sigue unido con sistemas de seguridad.","Un paseo espacial también se llama EVA.","El astronauta lleva un traje espacial completo."],
        ["¿Qué les pasa a los músculos con mucho tiempo de ingravidez?","Se pueden debilitar",["Se vuelven de acero","Desaparecen al momento","Crecen siempre más rápido"],"Por eso los astronautas hacen mucho ejercicio.","Sin entrenamiento, músculos y huesos se debilitan.","Los astronautas entrenan cada día en la ISS."],
        ["¿Qué comen los astronautas en el espacio?","Comida especialmente envasada",["Pastillas","Helado","Nada"],"Tiene que ser segura en microgravedad.","Los astronautas comen alimentos especialmente envasados.","Las migas son un problema porque salen flotando."],
        ["¿Qué es la ISS?","Una estación espacial internacional",["Un planeta","Un motor de cohete","Una base lunar"],"Gira alrededor de la Tierra.","La ISS es una gran estación espacial en órbita alrededor de la Tierra.","Allí trabajan juntos astronautas de varios países."],
        ["¿Por qué tiene que atarse un astronauta mientras trabaja?","Para no salir flotando",["Para tener más gravedad","Contra la lluvia","Para ir más rápido"],"En microgravedad sigues moviéndote con facilidad.","Atarse evita que alguien salga a la deriva sin control.","Las herramientas también se aseguran."]
      ],
      raket_avontuur: [
        ["¿Para qué sirve un motor de cohete?","Para crear empuje",["Para imprimir fotos","Para fabricar oxígeno","Para contar estrellas"],"Empuja gases calientes hacia atrás.","Un motor de cohete proporciona empuje.","Por acción y reacción, el cohete sale en la otra dirección."],
        ["¿Por qué necesita tanto combustible un cohete?","Para escapar de la gravedad",["Para la iluminación","Para el aire acondicionado","Para la radio"],"Despegar cuesta muchísima energía.","Un lanzamiento necesita cantidades enormes de energía.","Al despegar, la mayor parte de un cohete puede ser combustible."],
        ["¿Qué pasa en el despegue?","El cohete sube",["El cohete aterriza","El motor siempre se para","La Luna se acerca"],"Es el momento de la salida.","El despegue es el momento en el que el cohete deja el suelo.","Los primeros segundos son técnicamente muy importantes."],
        ["¿Por qué tienen varias etapas algunos cohetes?","Para soltar las partes vacías",["Para tener más ventanas","Para tener literas","Por los colores"],"Así el cohete lleva menos masa.","Un cohete suelta una etapa cuando se le acaba el combustible.","Así acelerar después es más eficiente."],
        ["¿Qué es una plataforma de lanzamiento?","El sitio desde el que sale un cohete",["Un satélite","Un vehículo lunar","Un asiento de cabina"],"Allí está el cohete antes de salir.","Una plataforma de lanzamiento sujeta el cohete antes del vuelo.","Allí hay grandes instalaciones de combustible, refrigeración y seguridad."],
        ["¿Qué es un satélite?","Un objeto que gira alrededor de otro objeto",["Una explosión de estrella","Un motor de cohete","Un telescopio"],"La Luna también es un satélite natural.","Los satélites giran alrededor de un planeta u otro cuerpo.","Los satélites artificiales ayudan en navegación y comunicación."],
        ["¿Por qué tiene forma aerodinámica la punta de un cohete?","Para reducir la resistencia del aire",["Para pesar más","Para recoger más lluvia","Por el color"],"Una forma lisa atraviesa el aire más fácilmente.","Una forma aerodinámica reduce la resistencia del aire.","Fuera de la atmósfera casi no queda resistencia del aire."],
        ["¿Qué es una cápsula?","Una parte donde pueden viajar personas o carga",["Una galaxia","Una luna","Un combustible"],"Suele ir en la punta del cohete.","Una cápsula espacial lleva personas o carga.","Algunas cápsulas vuelven con paracaídas."],
        ["¿Qué ayuda a una cápsula a aterrizar con seguridad?","Los paracaídas",["Las estrellas","Las erupciones solares","Los asteroides"],"Frenan la caída.","Los paracaídas frenan una cápsula que vuelve.","Algunas naves aterrizan también con motores."],
        ["¿Qué es una órbita alrededor de la Tierra?","Una trayectoria en la que caes sin parar alrededor de la Tierra",["Una carretera recta hacia el Sol","Un túnel","Una nube"],"La velocidad y la gravedad están en equilibrio.","Un satélite en órbita cae continuamente alrededor de la Tierra.","Por eso no se estrella sin más."]
      ]
    },
    geschiedenis: {
      egyptenaren: [
        ["¿Para qué se construyeron muchas pirámides?","Como tumbas",["Como escuelas","Como mercados","Como puertos"],"Piensa en los faraones y su enterramiento.","Muchas pirámides eran tumbas de faraones.","La gran pirámide de Guiza tiene miles de años."],
        ["¿Cómo se llamaba un gobernante del antiguo Egipto?","Faraón",["Senador","Caballero","Vikingo"],"Estaba en lo más alto de la sociedad.","A un gobernante egipcio se le llamaba faraón.","Algunos faraones eran considerados divinos."],
        ["¿Qué río era muy importante para Egipto?","El Nilo",["El Rin","El Amazonas","El Danubio"],"Atraviesa el país y hace fértil la tierra.","El Nilo era esencial para la agricultura y el transporte.","Las crecidas anuales traían limo fértil."],
        ["¿Cómo se llama la escritura egipcia con signos e imágenes?","Jeroglíficos",["Latín","Runas","Código morse"],"Los ves en templos y tumbas.","Los jeroglíficos eran una escritura egipcia importante.","Esa escritura usaba cientos de signos."],
        ["¿Qué es una momia?","Un cuerpo conservado",["Una moneda de oro","Un templo","Un barco"],"El cuerpo se trataba de forma especial después de morir.","Los egipcios hacían momias para conservar los cuerpos.","El proceso podía durar muchas semanas."],
        ["¿Sobre qué escribían a menudo los egipcios?","Sobre papiro",["Sobre plástico","Sobre hormigón","Sobre aluminio"],"Se hacía con una planta del Nilo.","El papiro se usaba como material de escritura.","Nuestra palabra papel viene de papiro."],
        ["¿Qué era la Esfinge de Guiza?","Una estatua con cuerpo de león y cabeza humana",["Una pirámide","Un barco","Una corona"],"Está cerca de las pirámides.","La gran Esfinge es una estatua de piedra enorme.","La Esfinge se talló en piedra caliza."],
        ["¿Para qué usaban el riego los egipcios?","Para regar sus campos",["Para pintar pirámides","Para escribir","Para hacer monedas"],"El agua del Nilo tenía que llegar a los campos.","El riego ayudaba a la agricultura.","Canales y balsas repartían el agua por los campos."],
        ["¿Qué animales se veían a menudo como especiales en Egipto?","Los gatos",["Los osos polares","Los pingüinos","Los canguros"],"Aparecen mucho en el arte y la religión.","Los gatos tenían un lugar especial en el antiguo Egipto.","La diosa Bastet se representaba a menudo como gata."],
        ["¿Qué hacían los escribas en el antiguo Egipto?","Llevar textos y registros",["Hacer volar pirámides","Formar caballeros","Fabricar estrellas"],"Escribir era una habilidad importante.","Los escribas llevaban los registros y controlaban los impuestos.","No todo el mundo sabía leer y escribir."]
      ],
      ridders_kastelen: [
        ["¿Qué llevaba a menudo un caballero para protegerse?","Una armadura",["Un traje espacial","Un albornoz","Un traje de buceo"],"Era de metal.","La armadura protegía el cuerpo.","Una armadura completa tenía muchas piezas."],
        ["¿Dónde vivía a menudo un señor poderoso?","En un castillo",["En un cohete","En una pirámide","En un iglú"],"El edificio tenía muros gruesos.","Los castillos eran viviendas y lugares de defensa.","Muchos castillos tenían torres y murallas."],
        ["¿Qué es un foso?","Una zanja de agua alrededor de un castillo",["Un dormitorio","Una plaza de mercado","Una panadería"],"Mantenía alejadas a las visitas no deseadas.","Un foso hacía que el castillo fuera difícil de alcanzar.","No todos los fosos tenían siempre agua."],
        ["¿Qué es un puente levadizo?","Un puente que se puede levantar",["Una escalera secreta","Una bandera","Una torre"],"Estaba a menudo en la entrada.","Un puente levadizo podía cerrar el paso.","Solía ir junto a una puerta fortificada."],
        ["¿Qué pasaba en un torneo de caballeros?","Los caballeros competían en pruebas",["Se construían pirámides","Se navegaba a América","Se hacían telescopios"],"Piensa en montar a caballo y en la habilidad.","Los torneos eran competiciones de caballeros.","Los torneos atraían público de todas partes, con música y fiesta."],
        ["¿Qué es un escudo?","Protección del caballero",["Un instrumento musical","Un mapa","Una taza"],"Los caballeros lo llevaban en un brazo.","El caballero sostenía el escudo delante de él para protegerse.","Los escudos solían mostrar los colores y símbolos de la familia."],
        ["¿Quién no vivía normalmente de forma permanente en un castillo?","Todos los campesinos de la zona",["El señor del castillo","Los soldados","Los sirvientes"],"Mucha gente vivía en los pueblos de alrededor.","La mayoría de los campesinos vivía fuera del castillo.","En caso de peligro a veces podían refugiarse allí."],
        ["¿Por qué tenían muros gruesos los castillos?","Para defenderse",["Para tener internet más rápido","Para dar calor","Para decorar"],"Tenían que ser fuertes y resistentes.","Los muros gruesos de piedra hacían más fuertes los castillos.","Algunos muros de castillo tenían más de cuatro metros de grosor."],
        ["¿Qué hacía a menudo un escudero?","Ayudar a un caballero y aprender",["Enterrar a un faraón","Pilotar un cohete","Construir un templo"],"A veces se preparaba para ser caballero.","Un escudero ayudaba a un caballero y aprendía el oficio.","No todos los escuderos llegaban a ser caballeros."],
        ["¿Qué era una fortaleza?","Un lugar fortificado para vivir",["Una galaxia","Un barco","Una asignatura"],"La palabra se usa a menudo para castillos.","Una fortaleza era un lugar fortificado.","Las fortalezas estaban a menudo en puntos estratégicos."]
      ],
      romeinen: [
        ["¿Quién construyó el Coliseo?","Los romanos",["Los vikingos","Los mayas","Los egipcios"],"Está en Roma.","El Coliseo lo construyeron los romanos.","Cabían decenas de miles de espectadores."],
        ["¿Qué era un acueducto?","Una construcción para llevar agua",["Un casco de caballero","Un templo para barcos","Una moneda"],"Llevaba agua a las ciudades.","Los acueductos romanos llevaban agua a lo largo de muchos kilómetros.","Algunos acueductos todavía se pueden ver hoy."],
        ["¿Qué lengua hablaban muchos romanos?","Latín",["Neerlandés","Japonés","Árabe"],"Muchas palabras españolas vienen de ahí.","El latín era una lengua importante en el Imperio romano.","El español, el francés y el italiano vienen del latín."],
        ["¿Qué era una legión?","Un grupo grande de soldados romanos",["Un mercado","Unas termas","Un barco"],"Formaba parte del ejército.","Una legión era una unidad grande del ejército.","Los soldados romanos entrenaban con mucha dureza."],
        ["¿Qué era un foro en una ciudad romana?","Una plaza central",["Una cárcel","Una granja","Un puerto"],"Allí se iba para el comercio y el gobierno.","El foro era un centro importante de la ciudad.","Allí solía haber templos y edificios públicos."],
        ["¿Para qué servían las termas romanas?","Para lavarse y reunirse",["Para construir cohetes","Para guardar grano","Para entrenar caballos"],"La gente también se juntaba allí a charlar.","Las termas eran lugares de encuentro importantes.","Algunas tenían baños calientes y fríos."],
        ["¿Qué llevaba a menudo un soldado romano?","Un casco y un escudo",["Un traje espacial","Un sombrero de vaquero","Un traje de buceo"],"Tenía que proteger la cabeza y el cuerpo.","Los soldados romanos llevaban casco, un gran escudo y sandalias resistentes.","Su equipo cambió a lo largo de los siglos."],
        ["¿Qué significa «Imperio romano»?","Un territorio grande gobernado desde Roma",["La ciudad de Roma","Una pirámide","Una orden de caballería"],"Se extendía por gran parte de Europa.","El Imperio romano era enorme.","En su momento de máxima extensión rodeaba todo el Mediterráneo."],
        ["¿Qué usaban los romanos para los viajes largos por tierra?","Una gran red de calzadas",["Los ríos","Globos aerostáticos","Trenes"],"Muchas calzadas eran muy sólidas.","Los romanos construyeron una gran red de calzadas.","Algunas carreteras de hoy siguen antiguas vías romanas."],
        ["¿Qué era un senador en Roma?","Un cargo importante",["Un panadero","Un faraón","Un caballero"],"Tenía un papel político.","Los senadores tenían influencia en el gobierno.","El Senado romano duró siglos."]
      ],
      ontdekkingsreizigers: [
        ["¿Qué hacía un explorador?","Explorar territorios nuevos",["Construir planetas","Inventar la electricidad","Vigilar pirámides"],"Piensa en viajes largos.","Los exploradores viajaban a regiones desconocidas.","Sus viajes cambiaron los mapas y el comercio."],
        ["¿Para qué usaban la brújula los marineros?","Para encontrar la dirección",["Para cocinar","Para escribir","Para medir la profundidad"],"La aguja señala más o menos al norte.","Una brújula ayuda en la navegación.","Hizo más fiables los viajes largos por mar."],
        ["¿Qué es una carta náutica?","Un mapa para navegar por el mar",["Un cuadro","Un blasón de caballero","Una constelación"],"Los barcos la usaban para planear la ruta.","Las cartas náuticas muestran costas, peligros y rutas.","Los barcos modernos usan a menudo cartas digitales."],
        ["¿Por qué eran útiles las estrellas para los marineros?","Ayudaban a calcular su posición",["Para atraer peces","Para hacer viento","Para calentar agua"],"Sobre todo de noche daban la dirección.","Las estrellas podían ayudar en la navegación.","La estrella Polar era importante en el hemisferio norte."],
        ["¿Qué era una carabela?","Un tipo de barco de vela",["Unas termas romanas","Un castillo","Un templo"],"Se usaba para viajes largos.","Las carabelas eran barcos de vela ágiles.","Tuvieron un papel en los viajes de descubrimiento europeos."],
        ["¿Por qué llevaban provisiones los exploradores?","Porque los viajes podían durar mucho",["Porque había tiendas en el mar","Para decorar","Para construir estrellas"],"En el mar no se podía ir a comprar.","La comida y el agua eran clave en los viajes largos.","La escasez y las enfermedades eran riesgos serios."],
        ["¿Qué es la navegación?","Saber dónde estás y hacia dónde vas",["Pintar un barco","Aprender un idioma","Construir un mercado"],"La brújula y los mapas ayudan.","Navegar es planear y seguir una ruta.","El GPS es una forma moderna de navegación."],
        ["¿Cuál era un gran peligro en los viajes largos por mar?","Las tormentas y las enfermedades",["Los semáforos","La nieve en el desierto","Los satélites"],"Los viajes duraban a veces meses.","Tormentas, enfermedades y falta de comida eran peligrosas.","El escorbuto venía de la falta prolongada de vitamina C."],
        ["¿Por qué se buscaban rutas nuevas hacia Asia?","Por el comercio de mercancías valiosas",["Para esquiar","Por los dinosaurios","Por los viajes espaciales"],"Las especias valían muchísimo.","El comercio impulsó muchos viajes de descubrimiento.","Las especias podían ser carísimas en Europa."],
        ["¿Qué hacían los cartógrafos después de los nuevos viajes?","Mejorar sus mapas",["Levantar pirámides","Mover estrellas","Cambiar la hora"],"Se añadían conocimientos nuevos.","Los relatos de viaje hacían los mapas más exactos.","Los mapas se volvieron más detallados con los siglos."]
      ]
    },
    wetenschap: {
      slimme_proefjes: [
        ["¿Qué pasa muchas veces cuando mezclas bicarbonato y vinagre?","Salen burbujas de gas",["Se congela al momento","Se convierte en metal","No pasa nada"],"Ves mucha espuma.","La reacción produce, entre otras cosas, dióxido de carbono.","Ese gas puede hinchar un globo, por ejemplo."],
        ["¿Por qué se usan gafas de protección en algunos experimentos?","Para proteger los ojos",["Para oír mejor","Para correr más rápido","Por el color"],"Algunas sustancias pueden salpicar.","Las gafas de protección protegen los ojos.","Trabajar con seguridad forma parte de la ciencia."],
        ["¿Qué es una hipótesis?","Una expectativa que se puede comprobar",["Un hecho demostrado","Un instrumento de medida","Un líquido"],"Decides antes lo que esperas.","Una hipótesis es una predicción que puedes investigar.","Después de un experimento puede confirmarse o no."],
        ["En un experimento justo, ¿qué hay que mantener lo más igual posible?","Las demás condiciones",["El resultado","La pregunta","Tu nombre"],"Solo cambias una cosa cada vez.","Mantener iguales las condiciones hace el experimento más justo.","Así sabes mejor qué ha causado un efecto."],
        ["¿Con qué mides con precisión un volumen de líquido?","Con una probeta graduada",["Con una lupa","Con una brújula","Con un cronómetro"],"Tiene rayas en el lateral.","Una probeta graduada mide el volumen.","El volumen se mide muchas veces en mililitros."],
        ["¿Qué hace un termómetro en un experimento?","Mide la temperatura",["Mide el tiempo","Mide el peso","Hace luz"],"Con él mides calor o frío.","Un termómetro mide la temperatura.","Aquí solemos medir en grados Celsius."],
        ["¿Por qué apuntas los resultados de un experimento?","Para poder compararlos",["Para olvidarlos","Para limpiar el vidrio","Para decorar"],"Los científicos anotan sus medidas.","Anotar los resultados ayuda a analizarlos y a repetirlos.","La buena ciencia tiene que poder comprobarse."],
        ["¿Qué le pasa al hielo cuando lo calientas?","Se derrite",["Se vuelve piedra","Desaparece de golpe","Se vuelve más pesado"],"El agua sólida se hace líquida.","El hielo se derrite y se convierte en agua.","A presión normal el hielo se derrite alrededor de 0 °C."],
        ["¿Qué necesitas para hacer una sombra?","Una fuente de luz y un objeto",["Sonido","Agua","Viento"],"El objeto para la luz.","Una sombra aparece cuando se bloquea la luz.","Su tamaño cambia con la distancia a la fuente de luz."],
        ["¿Qué es disolverse, como el azúcar en el agua?","La sustancia se reparte por el líquido",["La sustancia se va del mundo","La sustancia se vuelve fuego","El líquido se congela"],"Ya no ves los granos por separado.","Las partículas disueltas se reparten por el líquido.","Si evaporas el agua, muchas veces recuperas el azúcar."]
      ],
      lichaam: [
        ["¿Qué órgano bombea la sangre por tu cuerpo?","El corazón",["Los pulmones","El estómago","El cerebro"],"Lo puedes notar latir.","El corazón bombea la sangre por todo el cuerpo.","Tu corazón late unas cien mil veces al día."],
        ["¿Con qué respiras sobre todo?","Con los pulmones",["Con los riñones","Con el estómago","Con los huesos"],"Están dentro de tu pecho.","Los pulmones cogen el oxígeno.","Normalmente tienes dos pulmones."],
        ["¿Qué órgano te ayuda a pensar?","El cerebro",["El hígado","El corazón","El intestino"],"Está dentro de tu cráneo.","El cerebro procesa información y controla muchas funciones del cuerpo.","Allí trabajan juntas miles de millones de células nerviosas."],
        ["¿Qué lleva la sangre por tu cuerpo?","Oxígeno y nutrientes",["Aire","Huesos","Calor"],"La sangre circula por los vasos sanguíneos.","La sangre transporta, entre otras cosas, oxígeno y nutrientes.","Los glóbulos rojos ayudan a llevar el oxígeno."],
        ["¿Dónde empieza ya la digestión de la comida?","En la boca",["En el pie","En el pulmón","En el oído"],"Masticas la comida en trozos pequeños.","La digestión empieza en la boca.","La saliva contiene sustancias que ayudan a deshacer la comida."],
        ["¿Qué protegen tus costillas?","El corazón y los pulmones",["Tus pies","Tus dientes","Tus dedos"],"Forman una jaula alrededor del pecho.","Las costillas protegen órganos importantes.","La mayoría de las personas tiene 12 pares de costillas."],
        ["Además de sostener, ¿para qué sirven los huesos?","Para proteger y moverse",["Para el color","Para dormir","Para la temperatura"],"Los músculos tiran de los huesos.","Los huesos dan apoyo y protección y ayudan a moverse.","En la médula ósea se fabrican células de la sangre."],
        ["¿Qué hacen los músculos?","Se contraen y provocan movimiento",["Solo fabrican sangre","Digieren la comida","Ven la luz"],"Los músculos trabajan muchas veces con los huesos.","Los músculos se pueden contraer y así provocan movimiento.","Tu cuerpo tiene cientos de músculos."],
        ["¿Qué es la piel?","El órgano más grande de tu cuerpo",["Un hueso","Un músculo","Un vaso sanguíneo"],"Cubre todo tu cuerpo.","La piel protege el cuerpo.","La piel también ayuda a regular la temperatura."],
        ["¿Qué sentido usas con los oídos?","El oído",["El gusto","El olfato","La vista"],"Captas ondas de sonido.","Con los oídos percibes los sonidos.","Tu oído interno también ayuda con el equilibrio."]
      ],
      uitvindingen: [
        ["¿Con qué puedes mirar cosas muy pequeñas?","Con un microscopio",["Con un telescopio","Con una brújula","Con un barómetro"],"Piensa en células y bacterias.","Un microscopio aumenta los objetos pequeños.","Los microscopios modernos aumentan muchísimo."],
        ["¿Con qué miras estrellas y planetas lejanos?","Con un telescopio",["Con un microscopio","Con un termómetro","Con un imán"],"Hace más visibles los objetos lejanos.","Un telescopio recoge la luz de objetos lejanos.","Hay telescopios en la Tierra y en el espacio."],
        ["¿Qué invento hizo mucho más rápido copiar libros?","La imprenta",["La brújula","El silbato de vapor","La antorcha"],"Se podía imprimir con letras móviles.","La imprenta permitió fabricar libros en gran cantidad.","Así el conocimiento se extendió más rápido."],
        ["¿Para qué sirve una pila?","Para guardar y dar energía eléctrica",["Para medir el viento","Para hervir agua sin energía","Para fabricar estrellas"],"Encuentras una en muchos aparatos.","Una pila da energía eléctrica.","Las baterías recargables se pueden usar otra vez."],
        ["¿Qué hace un imán?","Puede atraer ciertos metales",["Siempre hace luz","Congela el agua","Para el tiempo"],"El hierro reacciona muy bien.","Los imanes ejercen fuerzas sobre los materiales magnéticos.","Un imán tiene un polo norte y un polo sur."],
        ["¿Qué fabrica un panel solar?","Electricidad a partir de la luz",["Lluvia a partir de las nubes","Gasolina a partir del aire","Sonido a partir de las piedras"],"El Sol da la energía.","Las células solares convierten la luz en electricidad.","Los paneles solares no tienen piezas móviles."],
        ["¿Qué hace un motor?","Convierte energía en movimiento",["Fabrica colores","Congela el agua","Lee papel"],"Los coches y las máquinas usan motores.","Un motor convierte energía en movimiento.","Hay motores eléctricos y de combustión."],
        ["¿Por qué fue importante el invento del teléfono?","La gente podía hablar a distancia",["La gente podía volar","La gente podía parar el tiempo","La gente podía vivir sin electricidad"],"El sonido se enviaba a distancia.","El teléfono cambió mucho la comunicación.","Los móviles reúnen hoy muchas funciones."],
        ["¿Qué hace sobre todo un ordenador?","Procesa información",["Hace música","Da luz","Purifica agua"],"Ejecuta instrucciones.","Los ordenadores procesan datos siguiendo programas.","Hasta un reloj inteligente lleva un ordenador."],
        ["¿Qué invento usa ondas de radio para saber dónde estás?","El GPS",["El imán","El microscopio","El estetoscopio"],"Los satélites ayudan a saber dónde estás.","El GPS usa señales de satélites.","Tu móvil usa el GPS para la navegación."]
      ],
      natuur_energie: [
        ["¿Qué fuente de energía usa el aire en movimiento?","La energía eólica",["La energía solar","El gas natural","La energía nuclear"],"Los aerogeneradores giran con ella.","Los aerogeneradores convierten el viento en electricidad.","Los aerogeneradores grandes pueden abastecer a muchas casas."],
        ["¿Qué fuente de energía usa la luz del Sol?","La energía solar",["El carbón","El petróleo","El gas natural"],"Los paneles recogen la luz.","Los paneles solares convierten la luz en electricidad.","El Sol aporta mucha más energía de la que usamos en el mundo."],
        ["¿Qué es la energía renovable?","Energía de fuentes que se reponen siempre",["Energía que no se usa nunca","Gasolina","Carbón"],"Piensa en el Sol y el viento.","Las fuentes renovables no se agotan rápido.","La energía del agua y la geotérmica también pueden ser renovables."],
        ["¿Qué hace un aerogenerador?","Convierte el viento en electricidad",["Hace lluvia","Produce gasolina","Empuja las nubes"],"Las palas giran con el viento.","Un generador dentro del aerogenerador fabrica electricidad.","Hay aerogeneradores en tierra y en el mar."],
        ["¿Qué sustancia se libera al quemar combustibles fósiles?","Dióxido de carbono",["Oxígeno","Oro","Helio"],"Es un gas de efecto invernadero.","Quemar petróleo, gas y carbón libera CO₂.","Más CO₂ refuerza el efecto invernadero."],
        ["¿Por qué aislamos las casas?","Para retener mejor el calor dentro o fuera",["Para hacer las ventanas más pesadas","Para fabricar agua","Para reforzar el wifi"],"Un buen aislamiento ahorra energía.","El aislamiento reduce la pérdida de calor.","El tejado, las paredes y los suelos se pueden aislar."],
        ["¿Qué es la energía hidráulica?","Energía del agua que corre o que cae",["Energía de la arena","Energía del humo","Energía del plástico"],"Una presa y un río pueden mover turbinas.","La energía hidráulica usa el movimiento del agua.","En el mundo es una fuente renovable importante."],
        ["¿Qué es ahorrar energía?","Usar menos energía para el mismo resultado",["Encender más lámparas","Ventanas abiertas y calefacción puesta","Dejar los aparatos encendidos"],"Los aparatos eficientes ayudan.","Ahorrar energía reduce el consumo.","Las lámparas LED gastan menos que las bombillas antiguas."],
        ["¿Qué hace la batería de un coche eléctrico?","Guarda energía eléctrica",["Fabrica gasolina","Mide el viento","Enfría agua"],"Alimenta el motor eléctrico.","La batería guarda energía para circular.","Al frenar a veces se recupera algo de energía."],
        ["¿Qué lámpara suele ser más eficiente?","La lámpara LED",["La bombilla","La vela","La lámpara halógena"],"Gasta menos electricidad.","La iluminación LED es muy eficiente.","Las lámparas LED también suelen durar más."]
      ]
    },
    mysterie: {
      raadsels: [
        ["Tengo teclas blancas y negras y hago música. ¿Qué soy?","Un piano",["Una puerta","Un cofre del tesoro","Una bicicleta"],"Me tocas con los dedos.","Un piano tiene teclas que se pulsan.","Un piano puede tener más de ochenta teclas."],
        ["Cuanto más seco, más mojado me pongo. ¿Qué soy?","Una toalla",["Un paraguas","El Sol","Una esponja"],"Me usas después de lavarte.","Una toalla se moja mientras te seca.","Las toallas absorben el agua con sus fibras."],
        ["¿Qué tiene cuello pero no cabeza?","Una botella",["Un gato","Una persona","Un búho"],"De ella se puede beber.","Una botella tiene cuello.","Las botellas son de vidrio o de plástico."],
        ["¿Qué tiene dientes pero no puede morder?","Un peine",["Un tiburón","Un perro","Un león"],"Lo usas para el pelo.","Un peine tiene dientes pero no boca.","Los peines existen desde hace miles de años."],
        ["¿Qué sube siempre y nunca baja?","Tu edad",["Un ascensor","Una pelota","Un pájaro"],"Cada año se hace más grande.","Tu edad aumenta a medida que creces.","En tu cumpleaños se añade un año más."],
        ["¿Qué tiene manecillas pero no manos?","Un reloj",["Un robot","Una persona","Un mono"],"Las manecillas señalan algo.","Un reloj de agujas tiene esfera y manecillas.","Las manecillas marcan horas, minutos y a veces segundos."],
        ["¿Qué puedes romper sin tocarlo?","Una promesa",["Una piedra","Un vaso","Una rama"],"Tiene que ver con la confianza.","Puedes romper una promesa sin tocar nada.","Las adivinanzas juegan muchas veces con los dobles sentidos."],
        ["¿Qué tiene un ojo pero no ve?","Una aguja",["Un búho","Una persona","Una cámara"],"Por el ojo pasa el hilo.","Una aguja tiene un ojo para el hilo.","El ojo suele estar en un extremo."],
        ["¿Qué se hace más grande cuanto más le quitas?","Un agujero",["Una montaña","Una caja","Un libro"],"Piensa en cavar.","Cuanto más sacas de un agujero, más grande se hace.","Es una adivinanza de lógica muy clásica."],
        ["¿Qué corre sin tener piernas?","El agua",["Un perro","Una persona","Un caballo"],"Corre por los ríos.","El agua puede correr sin piernas.","Las adivinanzas de palabras juegan con varios sentidos."]
      ],
      verborgen_schatten: [
        ["¿Con qué abres un cofre del tesoro cerrado?","Con una llave",["Con una pluma","Con un mapa","Con una lupa"],"Entra en una cerradura.","Con la llave correcta abres la cerradura.","Las cerraduras existen desde hace miles de años."],
        ["¿Qué suele haber en un mapa del tesoro?","Una equis en el sitio",["Un semáforo","Un código de barras","Un termómetro"],"La equis marca el lugar.","Una equis marca a menudo el sitio del tesoro.","Se conoce sobre todo por las historias de piratas."],
        ["¿Para qué usas una brújula en una búsqueda del tesoro?","Para encontrar la dirección",["Para pesar oro","Para hacer lluvia","Para cavar agujeros"],"La aguja te ayuda a encontrar el norte.","Una brújula ayuda en la navegación.","Una brújula normal reacciona al campo magnético de la Tierra."],
        ["¿Qué es un compartimento secreto?","Un espacio escondido dentro de un objeto",["Una plaza abierta","Una nube","Una leyenda de mapa"],"No se ve a primera vista.","En un compartimento secreto se pueden esconder cosas.","Los muebles antiguos tenían a veces cajones secretos."],
        ["¿Qué es una pista?","Información que te acerca a la solución",["Siempre la respuesta final","Un error","Un adorno"],"Un detective las busca.","Las pistas ayudan a resolver un misterio.","Una buena pista da algo sin contarlo todo."],
        ["¿Por qué numeras a veces tus pistas?","Para mantenerlas en orden",["Para hacerlas más pesadas","Para esconderlas","Para cambiar los colores"],"Así te pierdes menos.","Numerar ayuda a ordenar.","Los detectives ordenan las pruebas para ver relaciones."],
        ["¿Qué sitio tiene sentido para un tesoro escondido en una historia?","Debajo de una piedra marcada",["En medio de una mesa muy concurrida","En una señal de tráfico","En una nube"],"Tiene que estar fuera de la vista.","En las historias los tesoros se esconden en lugares secretos.","Las historias de tesoros usan símbolos reconocibles."],
        ["¿Qué es un código?","Un sistema para mostrar información de forma escondida",["Una fruta","Un instrumento musical","Una nube"],"Tienes que descifrarlo.","Un código puede esconder información.","La criptografía es la ciencia de los mensajes secretos."],
        ["¿Qué significa descifrar?","Hacer comprensible un código",["Enterrar algo","Quemar un mapa","Copiar una llave"],"Buscas el significado detrás de los signos.","Descifrar es leer información codificada.","Algunos códigos usan números o símbolos."],
        ["¿Por qué tendría una leyenda un mapa del tesoro?","Para explicar los símbolos",["Para hacer el mapa más pesado","Para hacer ruido","Para hacerlo impermeable"],"La leyenda te dice qué significan los signos.","Las leyendas de los mapas explican los símbolos.","Los mapas normales también tienen leyenda."]
      ],
      natuurmysteries: [
        ["¿Por qué una oruga se convierte en mariposa?","Por la metamorfosis",["Por el magnetismo","Por los rayos","Por la helada"],"El animal cambia en varias etapas de vida.","Las mariposas pasan por una metamorfosis.","Del huevo se pasa por oruga y crisálida hasta mariposa."],
        ["¿Por qué vemos a veces un arcoíris?","La luz se curva y se separa en las gotas de agua",["Las nubes se pintan","El Sol parpadea","La Luna lo pinta"],"El sol y la lluvia trabajan juntos.","Las gotas de agua curvan y reflejan la luz.","Un arcoíris aparece enfrente del Sol."],
        ["¿Por qué brilla una luciérnaga?","Por la bioluminiscencia",["Por una pila","Porque guarda luz del Sol","Por imanes"],"Fabrica luz dentro de su propio cuerpo.","La bioluminiscencia es luz de una reacción química.","Algunos animales marinos también pueden brillar."],
        ["¿Por qué son rosas los flamencos?","Por los pigmentos de su comida",["Porque nacen pintados","Solo por la luz del Sol","Por el agua fría"],"En su comida hay pigmentos.","Los carotenoides de su comida tiñen las plumas de rosa.","Los flamencos jóvenes son mucho más grises."],
        ["¿Por qué los capullos jóvenes de girasol siguen al Sol?","Por el heliotropismo",["Por la fuerza del viento","Por el magnetismo","Por la lluvia"],"Reaccionan a la luz.","Los girasoles jóvenes pueden seguir al Sol.","Las flores adultas suelen mirar hacia el este."],
        ["¿Por qué algunos animales tienen camuflaje?","Para llamar menos la atención",["Para crecer más rápido","Para cantar más fuerte","Para dar más calor"],"El color y el dibujo se parecen al entorno.","El camuflaje ayuda a cazar o a esconderse.","La sepia cambia de aspecto muy deprisa."],
        ["¿Qué provoca sobre todo las mareas?","La gravedad de la Luna",["Los aerogeneradores","Los volcanes","Las nubes"],"La Luna tira del agua del mar.","La Luna es una causa importante de las mareas.","El Sol también influye en las mareas."],
        ["¿Por qué los copos de nieve tienen a menudo seis puntas?","Por la forma en que las moléculas de agua forman cristales",["Por los aerogeneradores","Por los pájaros","Por la arena"],"El hielo forma un patrón de cristal fijo.","La estructura del hielo lleva muchas veces a una simetría de seis.","No hay dos copos grandes exactamente iguales."],
        ["¿Por qué el cielo suele ser azul de día?","La luz azul se dispersa más",["Porque el océano pinta el cielo","Por los árboles","Solo por las nubes"],"La luz del Sol tiene varios colores.","La atmósfera dispersa mucho la luz azul de onda corta.","Al atardecer vemos más rojo y naranja."],
        ["¿Por qué pueden subir los gecos por las paredes?","Millones de pelillos diminutos en sus dedos",["Ventosas con pegamento","Imanes","Electricidad"],"Sus dedos tocan la superficie en muchísimos puntos.","Unas estructuras microscópicas dan muchísima sujeción.","Esas fuerzas se llaman fuerzas de van der Waals."]
      ],
      speurtocht: [
        ["¿Para qué usas un mapa de ruta?","Para seguir el camino",["Para comerte un puzle","Para medir el tiempo","Para hacer ruido"],"El mapa muestra adónde tienes que ir.","Un mapa de ruta ayuda en la navegación.","Los símbolos pueden marcar los puntos importantes."],
        ["¿Qué es un punto de ruta?","Un punto acordado en un recorrido",["Una contraseña secreta","Un tipo de animal","Una moneda"],"Puedes dirigirte hacia él.","Los puntos de ruta marcan lugares de un recorrido.","Los aparatos de GPS los usan a menudo."],
        ["¿Qué herramienta te ayuda a ver mejor las pistas pequeñas?","Una lupa",["Un martillo","Una cuchara","Un paraguas"],"Hace los detalles más grandes.","Una lupa aumenta los detalles pequeños.","Una lente curva desvía los rayos de luz."],
        ["Una huella es sobre todo un…","Rastro",["Planeta","Instrumento","Color"],"Un detective los busca.","Una huella puede ser un rastro.","Los rastros pueden decir quién ha estado en un sitio."],
        ["¿Por qué miras bien alrededor en una búsqueda del tesoro?","Las pistas pueden estar escondidas",["Para parar el tiempo","Para hacer lluvia","Para crecer más rápido"],"No todo está en medio del camino.","Observar bien es importante en una búsqueda.","Las buenas búsquedas mezclan mirar, pensar y moverse."],
        ["¿Qué significa «gira a la izquierda» en una ruta?","Girar hacia el lado izquierdo",["Seguir recto","Volver a casa","Subir"],"Piensa en tu mano izquierda.","Girar a la izquierda es ir hacia la izquierda.","Las palabras de dirección son importantes en la navegación."],
        ["¿Qué es una coordenada?","Una forma de indicar un lugar exacto",["Un tipo de llave","Un rastro de animal","Un premio"],"Los mapas y el GPS las usan.","Las coordenadas describen una posición.","La latitud y la longitud son ejemplos."],
        ["¿Qué haces cuando dos pistas se contradicen?","Comprobarlas otra vez",["Elegir una sin más","Tirarlo todo","Romper el mapa"],"Puede que hayas leído algo mal.","Comprobar ayuda a encontrar errores.","Los buenos buscadores verifican su información."],
        ["¿Por qué es útil buscar en equipo?","Puedes juntar ideas y observaciones",["Porque uno puede no hacer nada","Para esconder pistas","Para parar el tiempo"],"Dos pares de ojos ven más.","Trabajar juntos puede resolver los problemas más rápido.","Los equipos suelen repartirse las tareas."],
        ["¿Para qué sirve la última pista?","Para llevarte al último lugar",["Para devolverte a la pregunta 1","Para crear un mundo nuevo","Para borrar la ruta"],"Te lleva a la solución.","La última pista suele llevar a la meta o al tesoro.","Una buena búsqueda avanza paso a paso hacia el final."]
      ]
    },
    dieren: {
      snelle_dieren: [
        ["¿Qué animal terrestre es el más rápido?","El guepardo",["El elefante","El panda","El hipopótamo"],"Es un felino delgado y con manchas.","El guepardo es el animal terrestre más rápido.","En un esprint corto puede pasar de 90 km/h."],
        ["¿Qué ave nada más rápido?", "El pingüino", ["El cisne", "El pato", "La gaviota"], "No sabe volar, pero nada muy bien.", "Un pingüino papúa supera los treinta kilómetros por hora bajo el agua.", "Sus plumas se montan como tejas, así no entra el agua."],
        ["¿Qué ave es famosa por sus picados rapidísimos?","El halcón peregrino",["El pingüino","La gallina","El avestruz"],"Caza desde el aire.","El halcón peregrino es uno de los animales más rápidos.","En picado puede superar los 300 km/h."],
        ["¿Por qué tiene un pez rápido el cuerpo aerodinámico?","Para tener menos resistencia",["Para pesar más","Para cantar más fuerte","Para coger más aire"],"Una forma lisa corta mejor el agua.","La forma aerodinámica reduce la resistencia del agua.","Los delfines también tienen forma aerodinámica."],
        ["¿Quién corre más rápido: un caballo o una tortuga?","El caballo",["La tortuga","Igual de rápido","Ninguno de los dos"],"Tiene patas largas y fuertes.","Un caballo es mucho más rápido que una tortuga.","Al galope los caballos alcanzan velocidades altas."],
        ["¿Por qué tienen las gacelas las patas largas?","Para correr y saltar rápido",["Para nadar","Para cavar","Para volar"],"Viven en llanuras abiertas.","Las patas largas ayudan a las gacelas a huir deprisa.","La velocidad las ayuda a escapar de los depredadores."],
        ["¿Qué tiburón es conocido por nadar rápido?","El tiburón mako",["El tiburón ballena","El caballito de mar","El pez león"],"Tiene el cuerpo aerodinámico.","Los tiburones mako están entre los tiburones más rápidos.","Cazan peces veloces."],
        ["¿Qué ayuda a un avestruz a correr rápido?","Unas patas largas y fuertes",["Alas para volar","Una vejiga natatoria","Garras para trepar"],"No puede volar.","Los avestruces corren muy rápido.","Corren a varias decenas de kilómetros por hora."],
        ["¿Por qué es útil la velocidad para las presas?","Para escapar",["Para hacer crecer los árboles","Para hacer frío","Para dormir"],"Los depredadores intentan cazarlas.","La velocidad puede mejorar sus posibilidades de sobrevivir.","Algunas presas también hacen giros bruscos."],
        ["¿Por qué es útil la velocidad para los depredadores?","Para atrapar presas",["Para regar plantas","Para dar color a las plumas","Para construir nidos"],"Una caza es muchas veces muy corta.","La velocidad ayuda durante la persecución.","No todos los depredadores usan la velocidad; algunos acechan."]
      ],
      baby_dieren: [
        ["¿Cómo se llama un bebé de perro?","Cachorro",["Ternero","Potro","Pollito"],"La palabra empieza por ca.","A un perro joven se le llama cachorro.","Los cachorros nacen ciegos y sordos."],
        ["¿Cómo se llama un bebé de gato?","Gatito",["Potro","Cordero","Ternero"],"Es un gato joven.","A un gato joven se le llama gatito.","Los gatitos duermen muchísimo."],
        ["¿Cómo se llama un caballo joven?","Potro",["Cachorro","Pollito","Cría de león"],"Se pone de pie enseguida.","A un caballo joven se le llama potro.","Los potros intentan ponerse de pie justo después de nacer."],
        ["¿Cómo se llama una oveja joven?","Cordero",["Ternero","Cachorro","Gatito"],"Se ven muchos en primavera.","A una oveja joven se le llama cordero.","Los corderos beben leche de su madre."],
        ["¿Cómo se llama un bebé de vaca?","Ternero",["Potro","Cordero","Pollito"],"A un elefante joven también se le llama así.","A una vaca joven se le llama ternero.","Los terneros beben leche al principio."],
        ["¿Cómo se llama una gallina joven recién nacida?","Pollito",["Cría de león","Cachorro","Cordero"],"Sale de un huevo.","A una gallina recién nacida se le llama pollito.","Los pollitos pían ya antes de salir del huevo."],
        ["¿Cómo se llama un león joven?","Cachorro de león",["Potro","Ternero","Gatito"],"A los lobos jóvenes también se les llama así.","Un león joven es un cachorro de león.","Los cachorros de león se quedan mucho tiempo con el grupo."],
        ["¿Qué beben primero muchos bebés de mamíferos?","Leche",["Agua salada","Gasolina","Limonada"],"La fabrica su madre.","Los mamíferos alimentan a sus crías con leche.","Es una característica importante de los mamíferos."],
        ["¿Por qué se quedan muchas crías cerca de su madre?","Por la protección y la comida",["Para volar más rápido","Para trepar a los árboles","Para hacer frío"],"Todavía tienen mucho que aprender.","Los padres suelen proteger y cuidar a sus crías.","Cuánto dura ese cuidado cambia mucho según la especie."],
        ["¿Qué cría de animal sale de un huevo?","El pollito",["El cachorro","El ternero","El potro"],"Piensa en una gallina.","Un pollito sale de un huevo.","Los reptiles, los peces y muchos otros animales también ponen huevos."]
      ],
      waterdieren: [
        ["¿Qué mamífero vive en el mar y respira aire?","El delfín",["El atún","El tiburón","La medusa"],"Tiene que subir a menudo.","Los delfines son mamíferos y respiran con pulmones.","Usan un espiráculo en lo alto de la cabeza."],
        ["¿Qué animal tiene ocho brazos?","El pulpo",["El tiburón","El delfín","El cangrejo"],"Se esconde muy bien.","Un pulpo tiene ocho brazos.","Los pulpos son moluscos muy inteligentes."],
        ["¿Qué animal marino es el animal más grande de la Tierra?","La ballena azul",["El tiburón blanco","El delfín","La orca"],"Es una ballena enorme.","La ballena azul es el animal más grande que se conoce.","Puede pasar de los 25 metros de largo."],
        ["¿Cómo respiran la mayoría de los peces?","Con branquias",["Con pulmones","Por la piel","Con plumas"],"Cogen el oxígeno del agua.","Las branquias cogen el oxígeno del agua.","El agua pasa por las láminas branquiales."],
        ["¿Qué ayuda a los peces a dirigirse y a nadar?","Las aletas",["Las alas","Las patas","Los pelos"],"Están en el lomo, la panza y la cola.","Las aletas ayudan en el movimiento y el equilibrio.","La aleta de la cola suele dar mucho impulso."],
        ["¿Qué animal puede vivir en el mar y en la tierra?","La tortuga marina",["El atún","La medusa","El caballito de mar"],"Sale a tierra a poner huevos.","Las tortugas marinas viven en el mar pero ponen huevos en la tierra.","Las hembras vuelven muchas veces a la playa donde nacieron."],
        ["¿Qué es en realidad el coral?","Una colonia de animales pequeños",["Una planta","Una piedra","Un pez"],"Forma arrecifes.","Los corales están formados por muchísimos pólipos pequeños.","Los arrecifes de coral son hábitats importantes."],
        ["¿Por qué suben las ballenas a la superficie?","Para respirar",["Para lavarse las branquias","Para dormir en la playa","Para cocinar"],"Son mamíferos.","Las ballenas respiran aire con pulmones.","Respiran por sus espiráculos."],
        ["¿Qué animal tiene caparazón duro y camina de lado?","El cangrejo",["El delfín","La medusa","El calamar"],"Se ven muchos en las playas.","Los cangrejos tienen un esqueleto externo duro.","Muchos cangrejos se mueven de lado con facilidad."],
        ["¿Por qué es útil un cuerpo aerodinámico en el agua?","Reduce la resistencia",["Hace más ruido","Hace más pesado al animal","Calienta el agua"],"Los animales se deslizan mejor por el agua.","La forma aerodinámica ayuda a nadar con menos esfuerzo.","Los delfines y los tiburones son buenos ejemplos."]
      ],
      jungle: [
        ["¿Qué animal se balancea a menudo por los árboles?","El mono",["El elefante","El pingüino","La cebra"],"Trepa por las ramas.","Muchas especies de monos viven en los árboles.","Algunos monos usan la cola como agarre extra."],
        ["¿Qué animal tiene un pico grande y de colores?","El tucán",["El tigre","El gorila","El cocodrilo"],"Es un ave tropical.","Los tucanes tienen picos llamativos.","Su pico es sorprendentemente ligero."],
        ["¿Qué animal grande vive en los bosques tropicales y come muchas plantas?","El gorila",["El pingüino","El camello","El oso polar"],"Es un gran simio.","Los gorilas viven en bosques de África.","Comen sobre todo plantas."],
        ["¿Por qué tienen camuflaje muchos animales de la selva?","Para llamar menos la atención",["Para cantar más fuerte","Para hacer más lluvia","Para crecer más rápido"],"Los dibujos se parecen a hojas y sombras.","El camuflaje ayuda a los animales a cazar o a esconderse.","Las manchas de muchos jaguares imitan sombras."],
        ["¿Qué gran felino vive en las selvas de América?","El jaguar",["El león","El leopardo de las nieves","El lince"],"Tiene rosetas en el pelaje.","Los jaguares viven en partes de Centroamérica y Sudamérica.","Nadan sorprendentemente bien."],
        ["¿Por qué son tan importantes los árboles de la selva tropical?","Dan comida y espacio para vivir",["No hacen oxígeno","Paran toda la lluvia","Solo son decoración"],"Muchos animales viven en distintas capas de árboles.","Los árboles de la selva forman hábitats complejos.","Algunos animales casi nunca bajan al suelo."],
        ["¿Qué reptil puede cambiar de color?","El camaleón",["La tortuga","El cocodrilo","La serpiente"],"También usa el color para comunicarse.","Los camaleones pueden ajustar su dibujo de color.","El cambio de color ayuda con la temperatura y las señales."],
        ["¿Qué es una selva tropical?","Un bosque cálido con muchísima lluvia",["Un desierto helado","Una pradera sin árboles","Un mar"],"Tiene muchísimas especies.","Las selvas tropicales reciben muchísima lluvia.","Están entre los lugares con más especies del planeta."],
        ["¿Por qué gritan tan fuerte los monos aulladores?","Para comunicarse con su grupo",["Para hacer lluvia","Para empujar árboles","Para nadar"],"Su grito llega lejos por el bosque.","Los monos aulladores se comunican con gritos muy fuertes.","Una estructura de la garganta agrandada amplifica el grito."],
        ["¿Qué animal caza insectos con una lengua larga?","El camaleón",["El elefante","El gorila","El tucán"],"La lengua sale disparada muy rápido.","Los camaleones atrapan a sus presas con su lengua larga.","La lengua puede acelerar muchísimo."]
      ]
    },
    aarde: {
      continenten_landen: [
        ["¿En qué continente están los Países Bajos?","En Europa",["En África","En Asia","En Sudamérica"],"Piensa en sus países vecinos.","Los Países Bajos están en Europa.","Europa es uno de los siete continentes."],
        ["¿Cuál es el continente más grande?","Asia",["Europa","África","Australia"],"Allí están China y la India.","Asia es el continente más grande.","Más de la mitad de las personas del mundo vive en Asia."],
        ["¿En qué continente está Brasil?","En Sudamérica",["En África","En Europa","En Asia"],"Piensa en el Amazonas.","Brasil está en Sudamérica.","Brasil es el país más grande de Sudamérica."],
        ["¿En qué continente está la mayor parte de Egipto?","En África",["En Europa","En Asia","En Norteamérica"],"El Nilo lo atraviesa.","Egipto está en su mayor parte en África.","La península del Sinaí pertenece geográficamente a Asia."],
        ["¿Cuál es la capital de Francia?","París",["Roma","Madrid","Berlín"],"Allí está la torre Eiffel.","París es la capital de Francia.","El Sena atraviesa París."],
        ["¿Cuál es la capital de Italia?","Roma",["Milán","Venecia","Nápoles"],"Allí está el Coliseo.","Roma es la capital de Italia.","La Ciudad del Vaticano está dentro de Roma."],
        ["¿Qué país tiene forma de bota?","Italia",["Portugal","Noruega","Polonia"],"Mira el sur de Europa.","Italia parece una bota.","Sicilia está cerca de la punta."],
        ["¿Qué océano está entre Europa y América?","El océano Atlántico",["El océano Pacífico","El océano Índico","El océano Ártico"],"Los barcos lo cruzan.","El océano Atlántico está entre Europa, África y América.","Es el segundo océano más grande."],
        ["¿Qué continente está en el Polo Sur?","La Antártida",["Europa","África","Asia"],"Está cubierto de hielo.","La Antártida rodea el Polo Sur.","Es el continente más frío."],
        ["¿Qué país está justo al este de los Países Bajos?","Alemania",["España","Irlanda","Italia"],"Es un país vecino.","Alemania hace frontera con los Países Bajos.","Los Países Bajos también hacen frontera con Bélgica."]
      ],
      weer_klimaat: [
        ["¿Qué mide un termómetro?","La temperatura",["La dirección del viento","La cantidad de lluvia","La presión del aire"],"Calor o frío.","Un termómetro mide la temperatura.","Solemos usar grados Celsius."],
        ["¿Qué son las precipitaciones?","Agua que cae del cielo",["El viento","La luz del Sol","La niebla"],"La lluvia y la nieve son ejemplos.","Las precipitaciones pueden ser lluvia, nieve o granizo.","Se forman del agua que hay en las nubes."],
        ["¿Qué es el viento?","Aire en movimiento",["Agua en movimiento","Arena caliente","Una nube"],"Lo notas pero no lo ves.","El viento es aire que se mueve.","Las diferencias de presión provocan gran parte del viento."],
        ["¿Por qué se forma niebla muchas veces?","El vapor de agua se condensa cerca del suelo",["Por las estrellas","Por la arena","Por los imanes"],"Se ve peor.","La niebla está hecha de gotitas diminutas de agua en el aire.","La niebla es en realidad una nube a ras de suelo."],
        ["¿Qué es el clima?","El tiempo medio a lo largo de muchos años",["El tiempo de hoy","Una tormenta","Un pluviómetro"],"Se trata de años, no de un día.","El clima describe el tiempo típico durante un periodo largo.","El tiempo puede cambiar mucho de un día a otro."],
        ["¿Qué provoca un rayo?","Una descarga eléctrica",["Una estrella fugaz","Un avión","Un arcoíris"],"Ocurre a menudo con nubes de tormenta.","Un rayo es una descarga eléctrica enorme.","El aire a su alrededor se pone muy caliente."],
        ["¿Por qué oyes el trueno después del rayo?","La luz va más rápido que el sonido",["El trueno empieza más tarde","Las nubes esperan","El Sol frena el sonido"],"Primero ves el relámpago.","La luz llega mucho antes que el sonido.","La diferencia de tiempo ayuda a calcular a qué distancia está la tormenta."],
        ["¿Qué nube acompaña a menudo a los chaparrones fuertes y a las tormentas?","El cumulonimbo",["El cirro","La niebla","Ninguna nube"],"Puede crecer muchísimo.","Los cumulonimbos pueden traer tormentas.","Arriba tienen a menudo forma de yunque."],
        ["¿Qué es una ola de calor?","Un periodo de calor poco habitual",["Una nevada repentina","Un terremoto","Una ola grande en el mar"],"Dura varios días.","Una ola de calor es un periodo largo de tiempo muy caluroso.","Las definiciones cambian de un país a otro."],
        ["¿Qué son las heladas?","Una temperatura por debajo de cero",["Un viento fuerte","Una lluvia muy fuerte","Una niebla densa"],"Entonces el agua se puede congelar.","Con heladas la temperatura baja a unos 0 °C o menos.","La escarcha se forma cuando el vapor de agua se congela."]
      ],
      oceanen_natuur: [
        ["¿Qué cubre la mayor parte de la Tierra?","El agua",["El desierto","El bosque","El hielo"],"Los océanos ocupan muchísimo espacio.","Alrededor del 71% de la Tierra está cubierta de agua.","La mayor parte es agua de mar salada."],
        ["¿Qué océano es el más grande?","El océano Pacífico",["El océano Atlántico","El océano Índico","El océano Ártico"],"Está entre Asia y América.","El Pacífico es el océano más grande.","Cubre alrededor de un tercio de la superficie de la Tierra."],
        ["¿Cómo se llama la roca fundida que sale de un volcán?","Lava",["Magma","Arcilla","Arena"],"Fuera de la Tierra la llamamos así.","En la superficie, la roca fundida se llama lava.","Bajo tierra la llamamos magma."],
        ["¿Qué es una isla?","Una tierra rodeada de agua por todas partes",["Una nube alta","Un río","Un desierto"],"Tienes que cruzar agua para llegar.","Una isla está rodeada de agua por todos lados.","Groenlandia es la isla más grande que no es un continente."],
        ["¿Qué es una cordillera?","Una serie de montañas",["Un río ancho","Un mar","Un grupo de islas"],"Los Alpes son una.","Una cordillera está hecha de montañas unidas.","En el Himalaya están las montañas más altas de la Tierra."],
        ["¿Qué es la desembocadura de un río?","El lugar donde termina el río",["El nacimiento del río","La cima de una montaña","Un desierto"],"El río suele desembocar en un mar o un lago.","La desembocadura es el final de un río.","Algunos ríos forman un delta en la desembocadura."],
        ["¿Qué es un desierto?","Una zona con muy pocas precipitaciones",["Siempre una playa calurosa","Una selva tropical","Un océano"],"No todos los desiertos son cálidos.","Los desiertos reciben muy pocas precipitaciones.","Técnicamente la Antártida también es un desierto."],
        ["¿Qué es un glaciar?","Una masa de hielo que se mueve despacio",["Una nube","Un río de lava","Una duna de arena"],"Se forma de nieve comprimida.","Los glaciares se mueven despacio por su propio peso.","Dan forma a valles y paisajes."],
        ["¿Qué es la erosión?","El desgaste y el arrastre de roca y suelo",["Árboles que crecen","Estrellas que nacen","Aire que se congela"],"El agua y el viento pueden provocarla.","La erosión cambia los paisajes.","Los ríos pueden excavar valles profundos."],
        ["¿Qué es un delta?","Una zona donde un río se divide en su desembocadura",["Una cima de montaña","Una corriente marina","Una nube"],"Allí puede haber tierra fértil.","Un delta se forma con los sedimentos depositados.","El delta del Nilo es un ejemplo conocido."]
      ],
      kaarten_navigatie: [
        ["¿Qué muestra una rosa de los vientos?","Las direcciones",["La temperatura","La altura","Los husos horarios"],"Norte, este, sur y oeste.","Una rosa de los vientos muestra las direcciones.","Los mapas usan a menudo N, E, S y O."],
        ["¿Para qué sirve la leyenda de un mapa?","Para explicar los símbolos",["Para decorar el mapa","Para medir distancias","Para hacer viento"],"Los colores y los signos adquieren significado.","La leyenda explica los símbolos del mapa.","Una línea azul puede ser un río, por ejemplo."],
        ["¿Qué es la escala de un mapa?","La relación entre la distancia del mapa y la real",["Un instrumento musical","Un medidor de temperatura","Un código de colores"],"1 cm puede significar 1 km, por ejemplo.","La escala hace comprensibles las distancias del mapa.","Una escala grande suele mostrar más detalles."],
        ["¿Qué son las coordenadas?","Números o valores que indican un lugar",["Un tipo de nube","Una moneda","Un río"],"El GPS las usa.","Las coordenadas describen una posición.","La latitud y la longitud son coordenadas conocidas."],
        ["¿Qué dirección está enfrente del norte?","El sur",["El este","El oeste","El noreste"],"Piensa en la rosa de los vientos.","El sur está enfrente del norte.","El este y el oeste forman ángulo recto con el norte y el sur."],
        ["¿Qué dirección queda a tu derecha si miras al norte?","El este",["El oeste","El sur","El norte"],"En muchos mapas el norte está arriba.","Con el norte arriba, el este queda a la derecha.","Por eso el oeste queda a la izquierda en ese mapa."],
        ["¿Qué es un mapa topográfico?","Un mapa con información del terreno y la altura",["Un mapa de estrellas","Una carta de restaurante","Una línea del tiempo"],"Puede tener curvas de nivel.","Los mapas topográficos muestran el paisaje y la altura.","Los excursionistas los usan mucho."],
        ["¿Qué es el GPS?","Un sistema de satélites para encontrar la posición",["Un tipo de nube","Un volcán","Una brújula sin satélites"],"Tu móvil lo puede usar.","El GPS usa señales de satélites para saber dónde estás.","Hacen falta varios satélites para una posición exacta."],
        ["¿Por qué suele estar el norte arriba en los mapas?","Es una costumbre muy extendida",["Porque el norte está más alto","Porque el Sol siempre está allí","Porque los ríos van hacia allí"],"Es una convención, no una ley de la naturaleza.","Muchos mapas modernos ponen el norte arriba.","Los mapas antiguos a veces se orientaban de otra forma."],
        ["¿Qué es una ruta?","Un camino planeado desde la salida hasta el destino",["Una nube de lluvia","Una montaña","Una frontera"],"La navegación te ayuda a seguirla.","Una ruta describe cómo ir de A a B.","Los mapas digitales calculan rutas automáticamente."]
      ]
    }
  };

  window.KWIZILLO_QUESTIONS_ES = window.KWIZILLO_BUILD_BANK(defs, window.KWIZILLO_EXTRA_ES||{}, window.KWIZILLO_MORE_ES||{});
})();
