(()=>{
  // Spanish UI strings (Spain). Same keys and the same layout as every other
  // language; the child is addressed with "tú" throughout. Typographic
  // apostrophes are not needed here, so nothing has to be escaped.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.es={
    'lang.name':'Español',
    'lang.speech':'es',

    'world.ruimte.title':'Mundo del espacio',
    'world.ruimte.sub':'Viaja entre planetas, estrellas y cohetes',
    'world.dieren.title':'Mundo de los animales',
    'world.dieren.sub':'Descubre animales de la tierra, la selva y el mar',
    'world.aarde.title':'Mundo de la Tierra',
    'world.aarde.sub':'Explora países, océanos, clima y mapas',
    'world.geschiedenis.title':'Mundo de la historia',
    'world.geschiedenis.sub':'Entra en la época de faraones, caballeros y exploradores',
    'world.wetenschap.title':'Mundo de la ciencia',
    'world.wetenschap.sub':'Prueba, descubre y entiende cómo funciona todo',
    'world.mysterie.title':'Mundo del misterio',
    'world.mysterie.sub':'Resuelve enigmas y sigue pistas ingeniosas',
    'world.kunst.title':'Mundo del Arte',
    'world.kunst.sub':'Descubre pinturas, música y grandes edificios',
    'world.sport.title':'Mundo del Deporte',
    'world.sport.sub':'Corre, salta y nada con los mejores deportistas',

    'topic.zonnestelsel':'Sistema solar',
    'topic.sterren_planeten':'Estrellas y planetas',
    'topic.astronauten':'Astronautas',
    'topic.raket_avontuur':'Aventura en cohete',
    'topic.egyptenaren':'Los egipcios',
    'topic.ridders_kastelen':'Caballeros y castillos',
    'topic.romeinen':'Los romanos',
    'topic.ontdekkingsreizigers':'Los exploradores',
    'topic.slimme_proefjes':'Experimentos ingeniosos',
    'topic.lichaam':'El cuerpo humano',
    'topic.uitvindingen':'Los inventos',
    'topic.natuur_energie':'Naturaleza y energía',
    'topic.raadsels':'Adivinanzas',
    'topic.verborgen_schatten':'Tesoros escondidos',
    'topic.natuurmysteries':'Misterios de la naturaleza',
    'topic.speurtocht':'La gran búsqueda',
    'topic.snelle_dieren':'Animales veloces',
    'topic.baby_dieren':'Crías de animales',
    'topic.waterdieren':'Animales del agua',
    'topic.jungle':'Aventura en la selva',
    'topic.continenten_landen':'Países y continentes',
    'topic.weer_klimaat':'Tiempo y clima',
    'topic.oceanen_natuur':'Océanos y naturaleza',
    'topic.kaarten_navigatie':'Mapas y navegación',
    'topic.schilderkunst':'Pintura',
    'topic.muziek':'Música',
    'topic.bouwkunst':'Arquitectura',
    'topic.dans_theater':'Danza y teatro',
    'topic.balsporten':'Deportes de pelota',
    'topic.olympische_spelen':'Juegos Olímpicos',
    'topic.water_wintersport':'Deportes de agua y nieve',
    'topic.records_helden':'Récords y héroes',

    'nav.home':'Inicio',
    'nav.achievements':'Logros',
    'nav.collection':'Colección',
    'nav.stats':'Datos',
    'nav.more':'Más',
    'nav.aria':'Navegación principal',
    'nav.collectionLong':'Mi colección',
    'nav.moreLong':'Más / Zona de padres',

    'common.back':'Atrás',
    'common.settings':'Ajustes',
    'common.close':'Cerrar',
    'common.cancel':'Cancelar',
    'common.gotIt':'Entendido',
    'common.brand':'KWIZILLO',
    'common.of':'de',
    // ¿Qué soy?
    'whoami.title':'¿Qué soy?','whoami.round':'Ronda {n} de {total}','whoami.points':'Ya {n} puntos','whoami.ask':'¿Qué soy?','whoami.more':'Una pista','whoami.next':'Siguiente','whoami.timeUp':'¡Se acabó el tiempo! Era {answer}.',
    'whoami.speech.ask':'[playful] '+'¿Qué soy?',   // spoken only: the voice asks it playfully, the tag is not read out
    'whoami.yes':'¡Sí, {answer}! +{points}','whoami.almost':'¡Casi! Era {answer}.',
    'whoami.speech.yes':'Es {answer}','whoami.speech.almost':'¡Casi! Era {answer}.',
    'whoami.doneKicker':'¿QUÉ SOY?','whoami.doneTitle':'¡{n} de {total} adivinados!','whoami.summary':'{score} de {max} puntos. Cuanto antes adivines, más puntos ganas.',
    'whoami.speech.great':'¡Vaya, adivinas rápido! Bien hecho.','whoami.speech.done':'¡Bien jugado! La próxima vez adivinarás aún más.',
    'jungle.title':'Runner','jungle.tileSub':'Corre, salta y vuela por tres niveles','jungle.loadError':'La selva no se ha podido cargar. Inténtalo más tarde.',
    'fotozoom.title':'Foto Zoom','fotozoom.round':'Ronda {n} de {total}','fotozoom.points':'Ya {n} puntos','fotozoom.ask':'¿Qué es esto?','fotozoom.out':'Alejar','fotozoom.next':'Siguiente','fotozoom.timeUp':'¡Se acabó el tiempo! Era {answer}.',
    'fotozoom.speech.ask':'[playful] '+'¿Qué es esto?',   // spoken only: the voice asks it playfully, the tag is not read out
    'fotozoom.yes':'¡Sí, {answer}! +{points}','fotozoom.almost':'¡Casi! Era {answer}.',
    'fotozoom.speech.yes':'Es {answer}','fotozoom.speech.almost':'¡Casi! Era {answer}.',
    'fotozoom.doneKicker':'FOTO ZOOM','fotozoom.doneTitle':'¡{n} de {total} acertados!','fotozoom.summary':'{score} de {max} puntos. Cuanto menos alejes, más puntos ganas.',
    'fotozoom.speech.great':'¡Qué vista tan aguda! Bien hecho.','fotozoom.speech.done':'¡Buen ojo! La próxima vez acertarás aún más.',
    'premium.teaser.fotozoom':'Foto Zoom en este mundo forma parte de Kwizillo Premium. Pide a un adulto que abra todos los mundos.',
    'jungle.brand':'KWIZILLO RUNNER','jungle.eyebrow':'KWIZILLO • ARCADE','jungle.titleA':'Kwizillo','jungle.titleB':'Runner','jungle.back':'Volver a Kwizillo','jungle.backShort':'Atrás','jungle.easyShort':'Modo tranquilo',
    'jungle.levelLabel':'ELIGE TU NIVEL','jungle.heroLabel':'¿QUIÉN CORRE CONTIGO?','jungle.heroBoy':'Chico','jungle.heroGirl':'Chica','jungle.glideOn':'¡Vuela!','jungle.glideOff':'¡Corre!','jungle.levelJungle':'Selva','jungle.levelStad':'Ciudad','jungle.levelLucht':'Cielo',
    'jungle.swingOn':'¡Balancéate!','jungle.swingOff':'¡Corre!','jungle.powerSpeed':'⚡ {n}s','jungle.popSpeed':'¡TURBO!','jungle.popSpeedSub':'7 segundos superrápido · monedas dobles','jungle.labelSpeed':'¡TURBO!',
    'jungle.canvasLabel':'Campo de juego. Flechas izquierda y derecha para dirigir. Espacio para saltar.','jungle.pause':'Pausa','jungle.sound':'Sonido activado o apagado','jungle.controls':'Controles del juego','jungle.left':'Izquierda','jungle.right':'Derecha','jungle.jump':'Saltar ↑',
    'jungle.loading':'Preparando tu aventura…','jungle.loadErrorTitle':'Prueba otra vez','jungle.loadErrorBody':'Las imágenes de la selva no se han podido cargar. Revisa tu conexión y prueba otra vez.',
    'jungle.intro':'Sigue el rastro dorado.<br>¡Salta, explora y colecciona!','jungle.legendMagnet':'🧲 Imán','jungle.legendShield':'🛡 Escudo','jungle.legendGold':'★ Oro +5','jungle.legendDouble':'×2 Estrella extra',
    'jungle.easy':'Modo tranquilo · salta solo','jungle.music':'Música','jungle.on':'activada','jungle.off':'apagada','jungle.start':'A la aventura →',
    'jungle.help':'{n} segundos • Desliza o usa los botones<br>10 monedas seguidas = +5 extra<br>Coge mejoras y encuentra una carta','jungle.countFollow':'¡Sigue las monedas!','jungle.countReady':'¿Listo para la aventura?',
    'jungle.pauseEyebrow':'RECUPERA EL ALIENTO','jungle.pauseTitle':'Tu selva<br>te espera.','jungle.pauseBody':'El tiempo está parado.','jungle.resume':'Seguir jugando →','jungle.exit':'Salir sin recompensa',
    'jungle.hit':'¡Uy! Te has parado: sigue corriendo.','jungle.hitLost':'¡Ay! Has chocado: pierdes {n} monedas.','jungle.labelHit':'−{n}','jungle.lostCoins':'Monedas perdidas','jungle.cardFound':'¡Has encontrado una carta de la selva!','jungle.powerDouble':'×2 {n}s','jungle.powerMagnet':'🧲 {n}s','jungle.powerShield':'🛡 Protegido','jungle.powerStreak':'★ {n} seguidas',
    'jungle.popDouble':'¡ESTRELLA EXTRA!','jungle.popDoubleSub':'6 segundos de monedas dobles','jungle.popGold':'¡ORO ENCONTRADO!','jungle.popGoldSub':'+{n} monedas','jungle.popCombo':'¡{n} SEGUIDAS!','jungle.popComboSub':'+5 de combo','jungle.popMagnet':'¡IMÁN DE MONEDAS!','jungle.popMagnetSub':'7 segundos atrayendo monedas',
    'jungle.popShield':'¡ESCUDO!','jungle.popShieldSub':'Aguanta un golpe por ti','jungle.popBlock':'¡EL ESCUDO TE HA SALVADO!','jungle.popBlockSub':'Sigue corriendo','jungle.popCard':'¡CARTA ENCONTRADA!','jungle.popCardSub':'Se revela en la meta','jungle.popClear':'¡BUEN SALTO!','jungle.popClearSub':'Por encima del tronco','jungle.popDoubleflip':'¡DOBLE SALTO MORTAL!','jungle.popDoubleflipSub':'+3 monedas',
    'jungle.labelGold':'¡+{n} ORO!','jungle.labelCombo':'COMBO +5','jungle.labelCard':'¡Carta encontrada!','jungle.labelClear':'¡Buen salto!','jungle.labelMagnet':'¡IMÁN!','jungle.labelShield':'¡ESCUDO!','jungle.labelBlock':'¡Salvado!','jungle.labelDouble':'¡MONEDAS DOBLES!',
    'jungle.saving':'Guardando tu recompensa…','jungle.saved':'Tus monedas están añadidas.','jungle.saveError':'Guardar no ha funcionado todavía. Prueba otra vez.',
    'jungle.finishEyebrow':'AVENTURA COMPLETADA','jungle.finish':'¡META!','jungle.finishSub':'Tu botín de esta carrera','jungle.coinsEarned':'monedas ganadas','jungle.bestStreak':'Mejor racha','jungle.bonusCoins':'Monedas extra',
    'jungle.cardAlt':'Carta conseguida','jungle.cardEyebrow':'CARTA ENCONTRADA','jungle.cardSub':'Para tu colección de Kwizillo','jungle.cardTitle':'Hoja de la selva','card.jungle-leaf':'Hoja de la selva','card.city-star':'Estrella de la ciudad','card.sky-feather':'Pluma del cielo','jungle.retry':'Guardar otra vez','jungle.take':'Llevarme el botín','jungle.again':'Otra aventura','jungle.replay':'Esta otra vez',
    // Premium
    'common.ok':'OK','common.retry':'Prueba otra vez',
    'premium.label':'Premium','premium.name':'Kwizillo Premium','premium.kicker':'PARA PADRES',
    'premium.title':'Abre todo el mundo de Kwizillo',
    'premium.subtitle':'Jugar, aprender, coleccionar y descubrir sin límites.',
    'premium.benefit.worlds':'Todos los mundos','premium.benefit.questions':'1280 preguntas de conocimiento','premium.benefit.math':'Juegos de cálculo','premium.benefit.memo':'Juegos de memoria','premium.benefit.facts':'Curiosidades','premium.benefit.guides':'Milo y Luna','premium.benefit.collect':'Coleccionar cartas y mascotas','premium.benefit.stats':'Progreso y estadísticas completos','premium.benefit.new':'Nuevas aventuras y contenidos',
    'premium.monthly':'Mensual','premium.yearly':'Anual','premium.perMonth':'mes','premium.perYear':'año',
    'premium.best':'Mejor precio','premium.trial':'Prueba {days} días gratis','premium.ctaTrial':'Empezar {days} días gratis','premium.ctaYearly':'Elegir anual','premium.ctaMonthly':'Elegir mensual',
    'premium.perMonthCalc':'Eso es {price} al mes',
    'premium.legal':'La suscripción se cobra en tu cuenta de Apple y se renueva automáticamente hasta que la canceles. Puedes gestionarla o cancelarla cuando quieras en tus suscripciones de Apple. Un periodo gratuito se convierte en suscripción de pago si no cancelas antes de que termine.',
    'premium.restore':'Restaurar compras','premium.restoreSub':'Recuperar Premium en este dispositivo','premium.manage':'Gestionar suscripción','premium.manageSub':'Cancelar o cambiar desde Apple','premium.privacy':'Privacidad','premium.terms':'Condiciones de uso',
    'premium.loading':'Cargando precios…','premium.purchasing':'Un momento, Apple está procesando la compra…',
    'premium.pending':'La compra está esperando confirmación. En cuanto llegue, Premium se activará solo.',
    'premium.cancelled':'Compra cancelada.','premium.failed':'Eso no ha funcionado. Inténtalo más tarde.',
    'premium.unavailable':'Premium no está disponible ahora mismo. Inténtalo más tarde.',
    'premium.already':'Premium está activo en este dispositivo.',
    'premium.restoring':'Restaurando compras…','premium.restoreNone':'No se ha encontrado ninguna compra anterior.','premium.manageUnavailable':'Gestiona las suscripciones en los Ajustes de tu teléfono, en tu cuenta de Apple.',
    'premium.welcome':'¡Bienvenido a Kwizillo Premium!','premium.welcomeSub':'Todos los mundos, juegos y curiosidades están abiertos. ¡Que te diviertas!','premium.continue':'Seguir donde estabas','premium.play':'Jugar',
    'premium.statusFree':'Versión gratis · desbloquear todo','premium.statusActive':'Activo · {type}','premium.statusTrial':'Periodo gratis · {type}','premium.statusExpired':'Caducado · tu progreso se guarda','premium.renews':'Se renueva el',
    'premium.teaserTitle':'Esto es Premium','premium.askParent':'Pregunta a un adulto',
    'premium.teaser.quiz':'Este quiz forma parte de Kwizillo Premium. Pide a un adulto que abra todos los mundos.',
    'premium.teaser.mega':'El Mega Quiz es parte de Kwizillo Premium. Pide a un adulto que abra todos los mundos.',
    'premium.teaser.memo':'Este juego de memoria forma parte de Kwizillo Premium. Pide a un adulto que abra todos los tableros.',
    'premium.teaser.math':'Los niveles de cálculo más altos forman parte de Kwizillo Premium. Pide a un adulto que los abra.',
    'premium.teaser.facts':'Más curiosidades forman parte de Kwizillo Premium. Pide a un adulto que las abra todas.',
    'premium.factsMore':'{n} curiosidades más con Premium',
    'premium.teaser.whoami':'¿Qué soy? en este mundo forma parte de Kwizillo Premium. Pide a un adulto que abra todos los mundos.',
    'settings.terms':'Condiciones de uso','settings.termsBody':'Kwizillo es un juego educativo para niños. Premium es una suscripción que cobra Apple y que se renueva automáticamente hasta que la canceles; puedes cancelarla cuando quieras en tus suscripciones de Apple. No hay publicidad ni compras dentro del juego.',

    'onboarding.language.title':'Elige tu idioma',
    'onboarding.language.sub':'¿En qué idioma quieres jugar?',
    'onboarding.name.title':'¿Cómo te llamas?',
    'onboarding.name.sub':'Para poder saludarte bien.',
    'onboarding.name.placeholder':'Tu nombre',
    'onboarding.name.hint':'Tu nombre se queda en este dispositivo.',
    'onboarding.voice.title':'¿Quién te ayuda?',
    'onboarding.voice.sub':'Elige tu guía. Puedes cambiarlo cuando quieras.',
    'onboarding.welcome.title':'¡Bienvenido, {name}!',
    'onboarding.welcome.sub':'Tu aventura empieza ahora. ¿Listo para explorar?',
    'onboarding.welcome.cta':'Empezar la aventura',
    'onboarding.next':'Continuar',
    'onboarding.speech.welcome':'¡Sí, todo está listo! Ven, te enseño rápido qué hay en cada sitio.',
    'onboarding.speech.language':'¡Hola! Soy Milo. ¿Qué idioma hablas?',
    'onboarding.speech.name':'¡Encantado de conocerte! ¿Cómo te llamas? Escríbelo aquí.',
    'onboarding.speech.age':'¿Y cuántos años tienes?',
    'onboarding.speech.group':'¿En qué curso estás?',
    'onboarding.speech.voice':'¿A quién quieres como guía? ¿A mí, a Luna, o mejor en silencio?',
    'onboarding.age.title':'¿Cuántos años tienes?',
    'onboarding.age.sub':'Toca tu edad.',
    'onboarding.age.years':'{n} años',
    'onboarding.group.title':'¿En qué curso estás?',
    'onboarding.group.sub':'Para elegir preguntas que te vayan bien.',
    'tour.worlds':'Estos son los mundos. ¡Toca un mundo y juega un quiz!',
    'tour.games':'Y aquí hay seis juegos. ¡Toca uno y pruébalo!',
    'tour.facts':'Y estas son las Curiosidades: ¡cientos de cosas divertidas por descubrir!',
    'tour.hud':'Arriba están tu nivel, tus monedas y tus días seguidos. La rueda es para tus padres.',
    'tour.nav':'Abajo están tu colección, tus logros y tus estadísticas. En Más están los ajustes.',
    'tour.done':'¡Que te diviertas! Te ayudo siempre que te atasques.',
    'tour.skip':'Saltar',
    'tour.again':'Visita con {guide}',
    'tour.againSub':'{guide} te enseña otra vez qué hay en cada sitio.',
    'tour.pick':'Visita guiada',
    'tour.pickSub':'Elige quién te enseña qué hay en cada sitio.',
    'players.title':'Jugadores en este dispositivo',
    'players.sub':'Quién juega en este dispositivo.',
    'players.current':'jugando ahora',
    'players.delete':'Borrar',
    'players.deleteTitle':'¿Borrar a {name}?',
    'players.deleteBody':'Todo lo de {name} desaparece de este dispositivo. No se puede deshacer.',
    'players.deleteCard':'Borrar jugador',
    'players.deleteCardSub':'Quitar un jugador y todo lo que ha jugado de este dispositivo',
    'players.deletePick':'¿Qué jugador quieres borrar?',
    'settings.logout':'Cerrar sesión',
    'settings.logoutSub':'Elegir otro jugador o empezar uno nuevo.',

    'voice.milo':'Milo',
    'voice.milo.desc':'Alegre y animado',
    'voice.luna':'Luna',
    'voice.luna.desc':'Tranquila y amable',
    'voice.silent':'Silencio',
    'voice.silent.desc':'Sin voz',
    'voice.milo.hello':'¡Hola! Soy Milo. ¿Listo para jugar?',
    'voice.luna.hello':'¡Hola! Soy Luna. ¿Exploramos juntos?',

    'home.greeting':'¡Hola {name}!',
    'home.greetingAnon':'¡Hola!',
    'home.level':'Nivel {level}',
    'home.coins':'KwizCoins',
    'home.streak':'Días seguidos',
    'home.pickWorld':'Elige tu mundo',
    'home.cta':'Empezar la aventura',
    'home.ctaSub':'Seguir en {world}',
    'home.voiceLabel':'Voz',
    'home.languageLabel':'Idioma',

    'world.kicker':'MUNDO KWIZILLO',
    'world.backHome':'Volver al inicio',
    'world.mix':'Empezar quiz mezclado',
    'world.mixSub':'Preguntas de los cuatro temas',
    'world.quizNumber':'Quiz {n}',
    'world.topicPassed':'Superado',
    'world.topicPlayed':'Quiz {n} jugado · {correct}/{answered} aciertos',
    'world.progressLine':'{passed} de {total} temas superados',
    'world.worldProgress':'{done} de los {total} quiz de este mundo superados',
    'world.mixDone':'{n} jugados',

    'quiz.mixed':'Quiz mezclado',
    'mega.title':'Mega Quiz',
    'mega.sub':'{n} preguntas de todos los mundos',
    'mega.rule':'Preguntas de los {worlds} mundos: acertaste {score} de {total}.',
    'mega.again':'Otro Mega Quiz',
    'mega.collectionLine':'Jugado {played} veces · mejor {best} de {total}',
    'quiz.progress':'Pregunta {current} de {total}',
    'quiz.hint':'Pista',
    'quiz.none':'Todavía no hay preguntas para este tema.',
    'quiz.artAlt':'Ilustración de la pregunta',
    'quiz.quizLabel':'Quiz {n}',
    'quiz.back':'Atrás',
    'quiz.explain':'Explicar',
    'quiz.timerAria':'Segundos que quedan',
    'feedback.timeKicker':'¡SE ACABÓ EL TIEMPO!',
    'feedback.timeTitle':'¡Más rápido la próxima vez!',
    'settings.level':'Nivel',
    'settings.levelSub':'{seconds} s por pregunta · máx. {allowed} fallos · {hints}',
    'settings.hintsFree':'pistas libres',
    'settings.hintsN':'{n} pistas',
    'settings.hintsNone':'sin pistas',
    'settings.readsQuestionOnly':'solo se lee la pregunta en voz alta',
    'quiz.hintsSpent':'No quedan pistas en este quiz.',
    'quiz.noHints':'El nivel 6 no tiene pistas.',
    'world.speech.enter':'[excited] ¡{title}!',
    'settings.levelAuto':'Auto',
    'settings.share':'Comparte tu puntuación',
    'settings.shareSub':'Envía tu resultado a tu familia o a tus amigos',

    'hint.title':'Una pistita',
    'hint.kicker':'Consejo de {topic}',
    'hint.ok':'Seguir pensando',
    'hint.close':'Cerrar la pista',
    'hint.fallback':'Vuelve a mirar bien la pregunta y la imagen.',
    'hint.alt':'Pista visual',

    'feedback.goodKicker':'¡CORRECTO!',
    'feedback.tryKicker':'¡POR POCO!',
    'feedback.goodTitle':'¡Bien jugado!',
    'feedback.tryTitle':'¡Bien pensado!',
    'feedback.correctIs':'La respuesta correcta es <strong>{answer}</strong>.',
    'feedback.thatsRight':'¡Eso es!',
    'feedback.didYouKnow':'¿Lo sabías?',
    'feedback.next':'Siguiente pregunta',
    'feedback.seeResult':'Ver el resultado',
    'feedback.speech.good':'Bien hecho.',
    'feedback.speech.good.1':'¡Bien hecho!',
    'feedback.speech.good.2':'¡Genial, eso es!',
    'feedback.speech.good.3':'¡Justo!',
    'feedback.speech.good.4':'¡Muy bien!',
    'feedback.speech.good.5':'¡Sí! ¡Exacto!',
    'feedback.speech.good.6':'¡Estupendo, buen ojo!',
    'feedback.speech.good.7':'¡Fantástico!',
    'feedback.speech.good.8':'¡Vaya, es correcto!',
    'feedback.speech.try.1':'Casi. La respuesta correcta es {answer}.',
    'feedback.speech.try.2':'No del todo. La respuesta correcta es {answer}.',
    'feedback.speech.try.3':'¡Buen intento! La respuesta correcta es {answer}.',
    'feedback.speech.try.4':'Uy, por poco. La respuesta correcta es {answer}.',
    'feedback.answerLabel':'La respuesta correcta',
    'feedback.close':'Cerrar',
    'feedback.listening':'Escuchando…',
    'quiz.repeat':'Otra vez',
    'quiz.repeatAria':'Leer la pregunta otra vez',
    'feedback.speech.try':'Casi. La respuesta correcta es {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'QUIZ TERMINADO',
    'result.title':'¡{score} de {total} correctas!',
    'result.score':'puntos',
    'result.xp':'XP',
    'result.coins':'monedas',
    'result.again':'Otro quiz',
    'result.againNumbered':'Empezar el quiz {n}',
    'result.nextTopic':'Ahora: {topic}',
    'result.finishWorld':'Empezar quiz mezclado',
    'result.retryTopic':'Repetir este tema',
    'result.retryNow':'Prueba otra vez',
    'memo.title':'Memo',
    'memo.pickTitle':'Elige tu mundo',
    'game.mixAll':'Mezcla de todos los mundos',
    'game.pickSub':'Elige un mundo o juega con todos mezclados.',
    'memo.pickSub':'Encuentra las parejas · Nivel {n}',
    'memo.otherWorld':'Otro mundo',
    'memo.sub':'Encuentra las parejas',
    'memo.play':'Jugar al Memo',
    'memo.playSub':'Encuentra las parejas de {world}',
    'memo.level':'Nivel {n}',
    'memo.pairs':'{found} de {total} parejas',
    'memo.boostTitle':'¡Impulso dorado!','memo.boostSub':'3 parejas seguidas · +{xp} puntos',
    'memo.moves':'{n} turnos',
    'memo.movesShort':'turnos',
    'memo.card':'Carta de memo',
    'memo.hintLine':'Da la vuelta a dos cartas y encuentra las parejas',
    'memo.none':'Todavía no hay cartas suficientes para este mundo.',
    'memo.doneKicker':'¡MEMO COMPLETADO!',
    'memo.doneTitle':'¡Todas las parejas encontradas!',
    'memo.timeKicker':'¡SE ACABÓ EL TIEMPO!',
    'memo.timeTitle':'¡Casi todas las parejas!',
    'memo.summary':'{pairs} parejas en {moves} turnos y {secs} segundos.',
    'memo.summaryTime':'{found} de {pairs} parejas encontradas. ¡Prueba otra vez!',
    'memo.again':'Otra vez',
    'memo.retry':'Prueba otra vez',
    'memo.toWorld':'Volver al mundo',
    'memo.speech.done':'¡Vaya, has encontrado todas las parejas! ¡Qué memoria!',
    'memo.speech.time':'Se acabó el tiempo. ¡La próxima vez las encontrarás todas!',
    'memo.modeTitle':'¿Cómo juegas?',
    'memo.solo':'Solo','memo.soloSub':'Contra el reloj',
    'memo.duel':'Uno contra uno','memo.duelSub':'Por turnos, ¿quién encuentra más parejas?',
    'memo.player1':'Jugador 1','memo.player2':'Jugador 2','memo.p2Label':'¿Quién juega contigo?',
    'memo.turn':'Le toca a {name}',
    'memo.duelKicker':'DUELO DE MEMO',
    'memo.duelWin':'¡Gana {name}!','memo.duelTie':'¡Empate!',
    'memo.duelSummary':'{pairs} parejas en {moves} turnos.',
    'memo.rematch':'Revancha',
    'memo.speech.win':'¡Ya tenemos ganador! ¡Bien jugado los dos!',
    'memo.speech.tie':'¡Empate! ¡Los dos tenéis muy buena memoria!',
    'home.playMore':'Jugar más',
    'math.title':'Cálculo',
    'facts.title':'Curiosidades',
    'world.ruimte.short':'Espacio','world.dieren.short':'Animales','world.aarde.short':'Tierra','world.geschiedenis.short':'Historia','world.wetenschap.short':'Ciencia','world.kunst.short':'Arte','world.sport.short':'Deporte','world.mysterie.short':'Misterio',
    'facts.tileSub':'¿Sabías que…',
    'facts.sub':'{seen} de {total} descubiertas',
    'facts.next':'Siguiente curiosidad',
    'facts.listen':'Leer en voz alta',
    'facts.kicker':'¿Sabías que…',
    'facts.new':'¡Nuevo!',
    'facts.allSeen':'¡Has descubierto todas las curiosidades! Ahora vuelven a empezar.',
    'facts.more':'Más curiosidades',
    'math.sub':'Operaciones rápidas',
    'math.play':'Cálculo',
    'math.playSub':'Diez operaciones · Nivel {n}',
    'math.progress':'Operación {current} de {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'¡{score} de {total} operaciones correctas!',
    'math.again':'Diez operaciones más',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'más',
    'math.op.minus':'menos',
    'math.op.times':'por',
    'math.op.divided':'dividido entre',
    'math.speech.twoStep':'{c} más {a} por {b}',
    'math.speech.half':'La mitad de {n}',
    'math.speech.quarter':'Un cuarto de {n}',
    'math.speech.percent':'{p} por ciento de {n}',
    'math.speech.wrong':'Casi. Es {answer}.',
    'math.speech.done':'¡Qué bien calculas! Todas las operaciones hechas.',
    'math.speech.fail':'Buen intento. ¡Otra vez y lo consigues!',
    'math.hint.plus':'Cuenta desde {a}: {b} más.',
    'math.hint.minus':'Empieza en {a} y cuenta {b} hacia atrás.',
    'math.hint.times':'{a} por {b}: suma {b} exactamente {a} veces.',
    'math.hint.divided':'¿Cuántas veces cabe {b} en {a}?',
    'math.hint.generic':'Calcula paso a paso.',
    'achievement.math3':'3 rondas de cálculo superadas',
    'stats.mathLine':'{played} rondas jugadas · {won} superadas',
    'result.passKicker':'¡SUPERADO!',
    'result.failKicker':'TODAVÍA NO',
    'result.passRule':'Nivel {niveau}: podías fallar {allowed} veces y has fallado {wrong}.',
    'result.failRule':'Nivel {niveau}: puedes fallar {allowed} veces y has fallado {wrong}. ¡Juega este tema otra vez!',
    'result.toCollection':'Ir a mi colección',

    'profile.title':'Mi perfil',
    'profile.sub':'Tu nombre, tu colega y tus ajustes',
    'profile.saveName':'Guardar nombre',
    'profile.saved':'¡Guardado!',
    'profile.buddy':'Mi colega',
    'profile.chooseBuddy':'Elegir colega',
    'profile.voice':'¿Quién lee en voz alta?',
    'achievements.title':'Logros',
    'achievements.sub':'Tus aventuras y tus metas',
    'achievements.summary':'{done}/{total} conseguidos',
    'achievements.summarySub':'Sigue explorando para desbloquear nuevos logros.',
    'achievements.done':'¡Conseguido!',
    'achievement.firstQuiz':'Primer quiz',
    'achievement.correct10':'10 respuestas correctas',
    'achievement.correct50':'50 respuestas correctas',
    'achievement.streak7':'7 días seguidos',
    'achievement.cards5':'5 cartas de conocimiento',
    'achievement.allWorlds':'Todos los mundos visitados',
    'achievement.memo3':'3 juegos de memo ganados',

    'collection.title':'Mi colección',
    'collection.sub':'Todo lo que has descubierto',
    'collection.tabWorlds':'🌍 Mundos',
    'collection.tabCards':'🃏 Cartas',
    'collection.tabMascots':'🐾 Colegas',
    'collection.worldStat':'{correct}/{answered} correctas · {pct}%',
    'progress.worldLine':'{passed} de {total} quiz superados · {points} puntos',
    'progress.overall':'En total {points} de {max} puntos',
    'progress.overallSub':'Cada quiz superado vale 25 puntos: un mundo entero son 100.',
    'collection.discovered':'★ Descubierto',
    'collection.unlockKicker':'¡NUEVO AMIGO!',
    'collection.unlockLine':'Desbloqueado con {n} respuestas correctas.',
    'score.coinsAdded':'+{n} monedas añadidas',
    'score.coinsCapped':'Máximo del día: se han añadido {n} de tus {got} monedas.','collection.cardAdded':'¡{title} ya está en tu colección!',
    'collection.emptyTitle':'Todavía no hay cartas',
    'collection.emptyBody':'Responde bien a las preguntas para coleccionar cartas de conocimiento.',
    'collection.mascotLocked':'faltan {n} respuestas correctas',
    'collection.mascotActive':'Activo ✓',
    'collection.mascotChoose':'Elegir colega',
    'collection.mascotCount':'{unlocked}/{total} colegas desbloqueados',

    'mascot.milo':'Milo',
    'mascot.milo.desc':'Tu colega robot listo',
    'mascot.comet':'Cometa',
    'mascot.comet.desc':'Colega del espacio',
    'mascot.pootje':'Patitas',
    'mascot.pootje.desc':'Amigo de los animales',
    'mascot.terra':'Terra',
    'mascot.terra.desc':'Protectora de la Tierra',
    'mascot.sparky':'Sparky',
    'mascot.sparky.desc':'Fan de los experimentos',
    'mascot.lumi':'Lumi',
    'mascot.lumi.desc':'Buscadora de misterios',
    'mascot.nova':'Nova','mascot.nova.desc':'Viajera de las estrellas',
    'mascot.kiko':'Kiko','mascot.kiko.desc':'Explorador de la selva',
    'mascot.pip':'Pip','mascot.pip.desc':'Atrevido del hielo',
    'mascot.ravi':'Ravi','mascot.ravi.desc':'Inventor en prácticas',
    'mascot.flora':'Flora','mascot.flora.desc':'Amiga de la naturaleza',
    'mascot.draco':'Draco','mascot.draco.desc':'Dragoncito del castillo',

    'stats.title':'Datos',
    'stats.sub':'Progreso real de las preguntas que has jugado',
    'stats.heroTitle':'Tus conocimientos crecen',
    'stats.heroSub':'{answered} preguntas respondidas · {quizzes} {quizWord} jugados',
    'stats.correctShort':'correctas',
    'stats.xpTotal':'XP total',
    'stats.coins':'KwizCoins',
    'stats.streak':'Días seguidos',
    'stats.cards':'Cartas',
    'stats.perWorld':'Por mundo',
    'stats.games':'Juegos',
    'stats.playedLine':'{played} partidas jugadas',
    'stats.runnerLine':'{played} carreras · {coins} monedas reunidas',
    'stats.memoBest':'{n} turnos',
    'stats.memoLine':'{played} juegos de memo jugados · {won} ganados',
    'share.text':'¡{name} juega a Kwizillo! Nivel {level}, {correct} respuestas correctas, {cards} cartas de conocimiento. Mejor quiz: {best}. ¿Quieres jugar también?',
    'share.copied':'Texto copiado: pégalo en un mensaje.',
    'result.share':'Comparte tu puntuación',
    'stats.worldLine':'{correct} de {answered} correctas · {quizzes} {quizWord}',
    'stats.quizOne':'quiz',
    'stats.quizMany':'quiz',

    'settings.title':'Zona de padres',
    'settings.sub':'Ajustes para una buena experiencia de juego',
    'settings.group':'Curso',
    'settings.groupSub':'Ajustar la dificultad',
    'settings.groupValue':'{n}º curso',
    'settings.language':'Idioma',
    'settings.languageSub':'Elige el idioma del juego',
    'settings.sound':'Sonido, música y voz',
    'settings.soundVoiceOff':'Voz apagada',
    'settings.soundVoiceOn':'Voz: {voice}',
    'settings.soundMusic':'música {state}',
    'settings.on':'activada',
    'settings.off':'apagada',
    'settings.timeLimit':'Temporizador de pregunta',
    'settings.timeLimitOff':'Apagado',
    'settings.timeLimitValue':'{n} segundos por pregunta en este nivel',
    'settings.privacy':'Privacidad y seguridad',
    'privacy.sub':'Qué guarda el juego y qué no hace',
    'privacy.updated':'Actualizado: {date}',
    'privacy.device':'En este dispositivo',
    'privacy.deviceBody':'Esto está en el almacenamiento de la app en este dispositivo. No va a Kwizillo ni a nadie más, y desaparece en cuanto borras la app o lo borras todo aquí abajo.',
    'privacy.itemName':'Nombre: {value}',
    'privacy.itemSettings':'Idioma, voz, sonido, curso y nivel',
    'privacy.itemProgress':'Progreso: {answered} preguntas, {correct} correctas, {cards} cartas',
    'privacy.itemPremium':'Si Premium está activo (eso viene de la App Store)',
    'privacy.leaves':'Qué sale del dispositivo',
    'privacy.leavesBody':'Solo la frase que lee en voz alta Milo o Luna. Va a nuestro propio servidor y de ahí al servicio de voz ElevenLabs. Siempre es texto del juego: una pregunta, una respuesta, una pista o una curiosidad. Nunca el nombre de tu hijo y nunca nada que escriba tu hijo.',
    'privacy.none':'Qué no hace la app',
    'privacy.noneBody':'Sin publicidad. Sin analíticas ni rastreadores de terceros. Sin cuenta, correo electrónico ni contraseña. Sin ubicación, contactos, cámara ni micrófono. Sin cookies.',
    'privacy.keep':'Conservar y borrar',
    'privacy.keepBody':'Lo que está en este dispositivo se queda hasta que lo borres; nosotros no guardamos ninguna copia en otro sitio. Nuestro servidor guarda el audio ya creado (frases del juego, ningún dato personal) para no crear dos veces la misma frase, y mantiene brevemente en memoria la dirección IP de una petición para evitar abusos.',
    'privacy.erase':'Borrar todos los datos',
    'privacy.eraseSub':'Nombre, ajustes y progreso de este dispositivo',
    'privacy.eraseTitle':'¿Borrar todo?',
    'privacy.eraseBody':'El nombre, los ajustes, el progreso, las cartas y los datos desaparecen de este dispositivo. Un Premium comprado sigue en tu cuenta de la App Store y vuelve con «Restaurar compras».',
    'privacy.eraseConfirm':'Sí, borrar todo',
    'privacy.contact':'¿Dudas sobre privacidad?',
    'privacy.contactSub':'Escribe a {email}',
    'privacy.noAccount':'Kwizillo funciona sin cuenta: con nosotros no hay nada que registrar ni que borrar.',
    'score.points':'puntos',
    'score.practice':'puntos de práctica',
    'score.dayFull':'máximo del día alcanzado',
    'score.title':'Récords',
    'score.sub':'Tus mejores puntos en cada periodo',
    'score.now':'ahora',
    'score.best':'récord',
    'score.run':'Este ejercicio',
    'score.day':'Hoy',
    'score.week':'Esta semana',
    'score.month':'Este mes',
    'score.year':'Este año',
    'score.allTime':'De siempre',
    'score.todayPoints':'{n} de {max} puntos hoy',
    'score.todayCoins':'{n} de {max} monedas hoy',
    'score.capNote':'Cada día hay un máximo de puntos y monedas, y una pregunta que ya acertaste da puntos de práctica. Así un récord vale de verdad.',
    'shop.tab':'🛒 Tienda',
    'shop.title':'Tienda',
    'shop.sub':'Paga con las monedas de los juegos',
    'shop.buy':'Comprar',
    'shop.owned':'Conseguido','shop.earned':'Conseguida',
    'shop.price':'{n} monedas',
    'shop.need':'Te faltan {n} monedas',
    'shop.confirmTitle':'¿Comprar {item}?',
    'shop.confirmBody':'Cuesta {n} monedas. Después {item} es tuyo para siempre.',
    'shop.bought':'¡{item} es tuyo!',
    'shop.cards':'Cartas doradas',
    'shop.mascots':'Amigos',
    'shop.goldCard':'{world} dorado',
    'shop.goldCardSub':'Una carta brillante para tu colección',
    'shop.earnHint':'Las monedas se ganan en el Runner y en los otros juegos.',
    'shop.empty':'¡Todo comprado! La tienda está vacía.',
    'result.worldLevelUp':'🎉 ¡{world} sube al nivel {niveau}!',
    'result.worldMastered':'🏆 ¡{world} completado en todos los niveles!',
    'result.goldCardEarned':'¡Has ganado la carta dorada de {world}!',
    'result.goldCardSpeech':'¡Guau! Has terminado {world} por completo. ¡La carta dorada es tuya!',
    'settings.levelWorlds':'Nivel por mundo',
    'settings.levelWorldsSub':'Un mundo sube solo cuando superas sus cuatro concursos.',
    'settings.levelMath':'Nivel del juego',
    'settings.timeLimitPerWorld':'El tiempo por pregunta sigue el nivel.',
    'settings.reset':'Reiniciar el progreso',
    'settings.resetSub':'Empezar de cero otra vez',
    'settings.resetTitle':'¿Reiniciar el progreso?',
    'settings.resetBody':'XP, monedas, cartas, datos y progreso vuelven al principio.',
    'settings.resetConfirm':'Sí, reiniciar',
    'gate.title':'Una preguntita para un adulto',
    'gate.body':'¿Cuánto es {a} × {b}?',
    'gate.placeholder':'Respuesta',
    'gate.wrong':'No es correcto. Prueba otra vez.',
    'gate.continue':'Continuar',

    'sound.kicker':'AJUSTES',
    'sound.title':'🔊 Sonido y música',
    'sound.fx':'✨ Efectos de sonido',
    'sound.music':'🎵 Música de fondo',
    'sound.test':'Probar',
    'sound.pickMusic':'Elige tu música',
    'sound.voiceGuide':'Guía de voz',
    'track.home':'Islas',
    'track.space':'Espacio',
    'track.jungle':'Selva',
    'track.earth':'Tierra',
    'track.history':'Historia',
    'track.science':'Ciencia',
    'track.mystery':'Misterio',
    'track.play':'Juegos',

    'intro.skip':'Saltar la intro',
    'welcome.back.title':'¡Hola, {name}!',
    'welcome.back.sub':'¿Listo para seguir?',
    'welcome.back.continue':'Seguir jugando',
    'welcome.back.other':'Juega otra persona',
    'welcome.back.where':'Aquí lo dejaste',
    'welcome.pick.title':'¿Quién juega?',
    'welcome.pick.new':'Nuevo jugador',
    'welcome.pick.back':'Atrás',
    'intro.tapToStart':'Toca para empezar',
    'intro.tapForSound':'Toca para oír'
  };
})();
