(()=>{
  // German UI strings. Same keys and the same layout as every other language; the
  // child is addressed with "du" throughout, warm but never babyish.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.de={
    'lang.name':'Deutsch',
    'lang.speech':'de',

    'world.ruimte.title':'Weltraumwelt',
    'world.ruimte.sub':'Reise an Planeten, Sternen und Raketen vorbei',
    'world.dieren.title':'Tierwelt',
    'world.dieren.sub':'Entdecke Tiere an Land, im Dschungel und im Meer',
    'world.aarde.title':'Erdenwelt',
    'world.aarde.sub':'Erforsche Länder, Ozeane, Wetter und Karten',
    'world.geschiedenis.title':'Geschichtswelt',
    'world.geschiedenis.sub':'Steige ein in die Zeit von Pharaonen, Rittern und Entdeckern',
    'world.wetenschap.title':'Wissenschaftswelt',
    'world.wetenschap.sub':'Probiere aus und finde heraus, wie die Dinge funktionieren',
    'world.mysterie.title':'Geheimniswelt',
    'world.mysterie.sub':'Löse Rätsel und folge klugen Spuren',
    'world.kunst.title':'Kunstwelt',
    'world.kunst.sub':'Entdecke Gemälde, Musik und großartige Bauwerke',
    'world.sport.title':'Sportwelt',
    'world.sport.sub':'Lauf, spring und schwimm mit den besten Sportlern',

    'topic.zonnestelsel':'Sonnensystem',
    'topic.sterren_planeten':'Sterne & Planeten',
    'topic.astronauten':'Astronauten',
    'topic.raket_avontuur':'Raketenabenteuer',
    'topic.egyptenaren':'Ägypter',
    'topic.ridders_kastelen':'Ritter & Burgen',
    'topic.romeinen':'Römer',
    'topic.ontdekkingsreizigers':'Entdecker',
    'topic.slimme_proefjes':'Kluge Experimente',
    'topic.lichaam':'Der Körper',
    'topic.uitvindingen':'Erfindungen',
    'topic.natuur_energie':'Natur & Energie',
    'topic.raadsels':'Rätsel',
    'topic.verborgen_schatten':'Verborgene Schätze',
    'topic.natuurmysteries':'Naturgeheimnisse',
    'topic.speurtocht':'Die große Suche',
    'topic.snelle_dieren':'Schnelle Tiere',
    'topic.baby_dieren':'Tierbabys',
    'topic.waterdieren':'Tiere im Wasser',
    'topic.jungle':'Dschungelabenteuer',
    'topic.continenten_landen':'Länder & Kontinente',
    'topic.weer_klimaat':'Wetter & Klima',
    'topic.oceanen_natuur':'Ozeane & Natur',
    'topic.kaarten_navigatie':'Karten & Navigation',
    'topic.schilderkunst':'Malerei',
    'topic.muziek':'Musik',
    'topic.bouwkunst':'Baukunst',
    'topic.dans_theater':'Tanz & Theater',
    'topic.balsporten':'Ballsport',
    'topic.olympische_spelen':'Olympische Spiele',
    'topic.water_wintersport':'Wasser- & Wintersport',
    'topic.records_helden':'Rekorde & Helden',

    'nav.home':'Start',
    'nav.achievements':'Auszeichnungen',
    'nav.collection':'Sammlung',
    'nav.stats':'Statistik',
    'nav.more':'Mehr',
    'nav.aria':'Hauptnavigation',
    'nav.collectionLong':'Meine Sammlung',
    'nav.moreLong':'Mehr / Elternbereich',

    'common.back':'Zurück',
    'common.settings':'Einstellungen',
    'common.close':'Schließen',
    'common.cancel':'Abbrechen',
    'common.gotIt':'Verstanden',
    'common.brand':'KWIZILLO',
    'common.of':'von',
    // Was bin ich?
    'whoami.title':'Was bin ich?','whoami.round':'Runde {n} von {total}','whoami.points':'Jetzt {n} Punkte','whoami.ask':'Was bin ich?','whoami.more':'Ein Hinweis','whoami.next':'Weiter','whoami.timeUp':'Die Zeit ist um! Es war {answer}.',
    'whoami.yes':'Ja, {answer}! +{points}','whoami.almost':'Fast! Es war {answer}.',
    'whoami.speech.yes':'Das ist {answer}','whoami.speech.almost':'Fast! Es war {answer}.',
    'whoami.doneKicker':'WAS BIN ICH?','whoami.doneTitle':'{n} von {total} erraten!','whoami.summary':'{score} von {max} Punkten. Je früher du rätst, desto mehr Punkte.',
    'whoami.speech.great':'Wow, du rätst schnell! Gut gemacht.','whoami.speech.done':'Schön gespielt! Nächstes Mal errätst du noch mehr.',
    'jungle.title':'Runner','jungle.tileSub':'Renne, springe und fliege durch drei Level','jungle.loadError':'Der Dschungel konnte nicht laden. Versuche es später noch einmal.',
    'fotozoom.title':'Fotozoom','fotozoom.round':'Runde {n} von {total}','fotozoom.points':'Jetzt {n} Punkte','fotozoom.ask':'Was ist das?','fotozoom.out':'Herauszoomen','fotozoom.next':'Weiter','fotozoom.timeUp':'Die Zeit ist um! Es war {answer}.',
    'fotozoom.yes':'Ja, {answer}! +{points}','fotozoom.almost':'Fast! Es war {answer}.',
    'fotozoom.speech.yes':'Das ist {answer}','fotozoom.speech.almost':'Fast! Es war {answer}.',
    'fotozoom.doneKicker':'FOTOZOOM','fotozoom.doneTitle':'{n} von {total} erkannt!','fotozoom.summary':'{score} von {max} Punkten. Je weniger du herauszoomst, desto mehr Punkte.',
    'fotozoom.speech.great':'Was für scharfe Augen! Gut gemacht.','fotozoom.speech.done':'Gut geschaut! Nächstes Mal erkennst du noch mehr.',
    'premium.teaser.fotozoom':'Fotozoom in dieser Welt gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alle Welten zu öffnen.',
    'jungle.brand':'KWIZILLO RUNNER','jungle.eyebrow':'KWIZILLO • ARCADE','jungle.titleA':'Kwizillo','jungle.titleB':'Runner','jungle.back':'Zurück zu Kwizillo','jungle.backShort':'Zurück','jungle.easyShort':'Leichte Fahrt',
    'jungle.levelLabel':'WÄHLE DEIN LEVEL','jungle.heroLabel':'WER LÄUFT MIT DIR?','jungle.heroBoy':'Junge','jungle.heroGirl':'Mädchen','jungle.glideOn':'Flieg!','jungle.glideOff':'Lauf!','jungle.levelJungle':'Dschungel','jungle.levelStad':'Stadt','jungle.levelLucht':'Himmel',
    'jungle.swingOn':'Schwing!','jungle.swingOff':'Lauf!','jungle.powerSpeed':'⚡ {n}s','jungle.popSpeed':'TURBO!','jungle.popSpeedSub':'7 Sekunden superschnell · doppelte Münzen','jungle.labelSpeed':'TURBO!',
    'jungle.canvasLabel':'Spielfeld. Pfeiltasten links und rechts zum Steuern. Leertaste zum Springen.','jungle.pause':'Pause','jungle.sound':'Ton an oder aus','jungle.controls':'Spielsteuerung','jungle.left':'Links','jungle.right':'Rechts','jungle.jump':'Springen ↑',
    'jungle.loading':'Dein Abenteuer wird vorbereitet…','jungle.loadErrorTitle':'Noch einmal','jungle.loadErrorBody':'Die Dschungelbilder konnten nicht laden. Prüfe deine Verbindung und versuche es erneut.',
    'jungle.intro':'Folge der goldenen Spur.<br>Springe, entdecke und sammle!','jungle.legendMagnet':'🧲 Magnet','jungle.legendShield':'🛡 Schild','jungle.legendGold':'★ Gold +5','jungle.legendDouble':'×2 Bonusstern',
    'jungle.easy':'Leichte Fahrt · springt von selbst','jungle.music':'Musik','jungle.on':'an','jungle.off':'aus','jungle.start':'Auf Abenteuer →',
    'jungle.help':'{n} Sekunden • Wische oder nimm die Knöpfe<br>10 Münzen hintereinander = +5 Bonus<br>Sammle Power-ups und finde eine Karte','jungle.countFollow':'Folge den Münzen!','jungle.countReady':'Bereit für das Abenteuer?',
    'jungle.pauseEyebrow':'ATME DURCH','jungle.pauseTitle':'Dein Dschungel<br>wartet.','jungle.pauseBody':'Die Zeit steht still.','jungle.resume':'Weiterspielen →','jungle.exit':'Ohne Belohnung verlassen',
    'jungle.hit':'Hoppla! Kurz gestoppt — lauf weiter.','jungle.hitLost':'Autsch! Zusammenstoß — {n} Münzen weg.','jungle.labelHit':'−{n}','jungle.lostCoins':'Münzen verloren','jungle.cardFound':'Du hast eine Dschungelkarte gefunden!','jungle.powerDouble':'×2 {n}s','jungle.powerMagnet':'🧲 {n}s','jungle.powerShield':'🛡 Geschützt','jungle.powerStreak':'★ {n} in Folge',
    'jungle.popDouble':'BONUSSTERN!','jungle.popDoubleSub':'6 Sekunden doppelte Münzen','jungle.popGold':'GOLD GEFUNDEN!','jungle.popGoldSub':'+{n} Münzen','jungle.popCombo':'{n} IN FOLGE!','jungle.popComboSub':'+5 Combo-Bonus','jungle.popMagnet':'MÜNZMAGNET!','jungle.popMagnetSub':'7 Sekunden Münzen anziehen',
    'jungle.popShield':'SCHILD!','jungle.popShieldSub':'Fängt einen Stoß für dich ab','jungle.popBlock':'DAS SCHILD HAT DICH GERETTET!','jungle.popBlockSub':'Lauf weiter','jungle.popCard':'KARTE GEFUNDEN!','jungle.popCardSub':'Wird am Ziel gezeigt','jungle.popClear':'GUTER SPRUNG!','jungle.popClearSub':'Über den Baumstamm','jungle.popDoubleflip':'DOPPELSALTO!','jungle.popDoubleflipSub':'+3 Münzen',
    'jungle.labelGold':'+{n} GOLD!','jungle.labelCombo':'COMBO +5','jungle.labelCard':'Karte gefunden!','jungle.labelClear':'Guter Sprung!','jungle.labelMagnet':'MAGNET!','jungle.labelShield':'SCHILD!','jungle.labelBlock':'Gerettet!','jungle.labelDouble':'DOPPELTE MÜNZEN!',
    'jungle.saving':'Deine Belohnung wird gespeichert…','jungle.saved':'Deine Münzen sind hinzugefügt.','jungle.saveError':'Das Speichern hat noch nicht geklappt. Versuche es erneut.',
    'jungle.finishEyebrow':'ABENTEUER GESCHAFFT','jungle.finish':'ZIEL!','jungle.finishSub':'Deine Beute aus diesem Lauf','jungle.coinsEarned':'Münzen verdient','jungle.bestStreak':'Beste Serie','jungle.bonusCoins':'Bonusmünzen',
    'jungle.cardAlt':'Gesammelte Karte','jungle.cardEyebrow':'KARTE GEFUNDEN','jungle.cardSub':'Für deine Kwizillo-Sammlung','jungle.cardTitle':'Dschungelblatt','card.jungle-leaf':'Dschungelblatt','card.city-star':'Stadtstern','card.sky-feather':'Himmelsfeder','jungle.retry':'Noch einmal speichern','jungle.take':'Beute mitnehmen','jungle.again':'Anderes Abenteuer','jungle.replay':'Dieses noch einmal',
    // Premium
    'common.ok':'OK','common.retry':'Noch einmal',
    'premium.label':'Premium','premium.name':'Kwizillo Premium','premium.kicker':'FÜR ELTERN',
    'premium.title':'Öffne die ganze Welt von Kwizillo',
    'premium.subtitle':'Spielen, lernen, sammeln und entdecken ohne Grenzen.',
    'premium.benefit.worlds':'Alle Welten','premium.benefit.questions':'1280 Wissensfragen','premium.benefit.math':'Rechenspiele','premium.benefit.memo':'Memo-Spiele','premium.benefit.facts':'Wissenswertes','premium.benefit.guides':'Milo & Luna','premium.benefit.collect':'Karten und Maskottchen sammeln','premium.benefit.stats':'Vollständiger Fortschritt und Statistik','premium.benefit.new':'Neue Abenteuer und Inhalte',
    'premium.monthly':'Monatlich','premium.yearly':'Jährlich','premium.perMonth':'Monat','premium.perYear':'Jahr',
    'premium.best':'Bester Preis','premium.trial':'{days} Tage gratis testen','premium.ctaTrial':'{days} Tage gratis starten','premium.ctaYearly':'Jährlich wählen','premium.ctaMonthly':'Monatlich wählen',
    'premium.perMonthCalc':'Das sind {price} pro Monat',
    'premium.legal':'Das Abo wird über dein Apple-Konto abgerechnet und verlängert sich automatisch, bis es gekündigt wird. Du kannst es jederzeit in deinen Apple-Abos verwalten oder kündigen. Ein Gratiszeitraum wird zu einem bezahlten Abo, wenn du nicht vorher kündigst.',
    'premium.restore':'Käufe wiederherstellen','premium.restoreSub':'Premium auf diesem Gerät zurückholen','premium.manage':'Abo verwalten','premium.manageSub':'Über Apple kündigen oder ändern','premium.privacy':'Datenschutz','premium.terms':'Nutzungsbedingungen',
    'premium.loading':'Preise werden geladen…','premium.purchasing':'Einen Moment, Apple bearbeitet den Kauf…',
    'premium.pending':'Der Kauf wartet auf Bestätigung. Sobald sie da ist, schaltet Premium sich von selbst ein.',
    'premium.cancelled':'Kauf abgebrochen.','premium.failed':'Das hat nicht geklappt. Versuche es später noch einmal.',
    'premium.unavailable':'Premium ist gerade nicht verfügbar. Versuche es später noch einmal.',
    'premium.already':'Premium ist auf diesem Gerät aktiv.',
    'premium.restoring':'Käufe werden wiederhergestellt…','premium.restoreNone':'Kein früherer Kauf gefunden.','premium.manageUnavailable':'Verwalte Abos in den Einstellungen deines Telefons unter deinem Apple-Konto.',
    'premium.welcome':'Willkommen bei Kwizillo Premium!','premium.welcomeSub':'Alle Welten, Spiele und Fakten sind offen. Viel Spaß!','premium.continue':'Weiter, wo du warst','premium.play':'Spielen',
    'premium.statusFree':'Gratisversion · alles freischalten','premium.statusActive':'Aktiv · {type}','premium.statusTrial':'Gratiszeitraum · {type}','premium.statusExpired':'Abgelaufen · dein Fortschritt bleibt','premium.renews':'Verlängert sich am',
    'premium.teaserTitle':'Das ist Premium','premium.askParent':'Frag einen Erwachsenen',
    'premium.teaser.quiz':'Dieses Quiz gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alle Welten zu öffnen.',
    'premium.teaser.memo':'Dieses Memo-Spiel gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alle Spiele zu öffnen.',
    'premium.teaser.math':'Die höheren Rechenlevel gehören zu Kwizillo Premium. Bitte einen Erwachsenen, sie zu öffnen.',
    'premium.teaser.facts':'Mehr Wissenswertes gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alles zu öffnen.',
    'premium.factsMore':'{n} weitere Fakten mit Premium',
    'premium.teaser.whoami':'Was bin ich? in dieser Welt gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alle Welten zu öffnen.',
    'settings.terms':'Nutzungsbedingungen','settings.termsBody':'Kwizillo ist ein Lernspiel für Kinder. Premium ist ein Abo, das über Apple abgerechnet wird und sich automatisch verlängert, bis es gekündigt wird; du kannst es jederzeit in deinen Apple-Abos kündigen. Es gibt keine Werbung und keine Käufe im Spiel selbst.',

    'onboarding.language.title':'Wähle deine Sprache',
    'onboarding.language.sub':'In welcher Sprache möchtest du spielen?',
    'onboarding.name.title':'Wie heißt du?',
    'onboarding.name.sub':'Damit wir dich richtig begrüßen können.',
    'onboarding.name.placeholder':'Dein Name',
    'onboarding.name.hint':'Dein Name bleibt auf diesem Gerät.',
    'onboarding.voice.title':'Wer hilft dir?',
    'onboarding.voice.sub':'Wähle deinen Begleiter. Du kannst das jederzeit ändern.',
    'onboarding.welcome.title':'Willkommen, {name}!',
    'onboarding.welcome.sub':'Dein Abenteuer beginnt jetzt. Bereit zum Entdecken?',
    'onboarding.welcome.cta':'Abenteuer starten',
    'onboarding.next':'Weiter',
    'onboarding.speech.welcome':'Ja, alles ist bereit! Komm mit, ich zeige dir schnell, was wo ist.',
    'onboarding.speech.language':'Hallo! Ich bin Milo. Welche Sprache sprichst du?',
    'onboarding.speech.name':'Schön, dich zu treffen! Wie heißt du? Tippe es einfach ein.',
    'onboarding.speech.age':'Und wie alt bist du?',
    'onboarding.speech.group':'In welcher Klasse bist du?',
    'onboarding.speech.voice':'Wen möchtest du als Begleiter? Mich, Luna, oder lieber still?',
    'onboarding.age.title':'Wie alt bist du?',
    'onboarding.age.sub':'Tippe auf dein Alter.',
    'onboarding.age.years':'{n} Jahre',
    'onboarding.group.title':'In welcher Klasse bist du?',
    'onboarding.group.sub':'Damit ich Fragen wähle, die zu dir passen.',
    'tour.worlds':'Das sind die Welten. Tippe auf eine Welt und spiele ein Quiz!',
    'tour.games':'Und hier sind sechs Spiele. Tipp eins an und probier es aus!',
    'tour.facts':'Und das ist das Wissenswerte: Hunderte spannende Dinge zum Entdecken!',
    'tour.hud':'Oben stehen deine Stufe, deine Münzen und deine Tage in Folge. Das Zahnrad ist für deine Eltern.',
    'tour.nav':'Unten stehen deine Sammlung, deine Erfolge und deine Statistiken. Unter Mehr sind die Einstellungen.',
    'tour.done':'Viel Spaß! Ich helfe dir, wenn du nicht weiterkommst.',
    'tour.skip':'Überspringen',
    'tour.again':'Rundgang mit {guide}',
    'tour.againSub':'{guide} zeigt dir noch einmal, was wo ist.',
    'tour.pick':'Rundgang',
    'tour.pickSub':'Wähle, wer dir zeigt, was wo ist.',
    'players.title':'Spieler auf diesem Gerät',
    'players.sub':'Wer auf diesem Gerät spielt.',
    'players.current':'spielt gerade',
    'players.delete':'Löschen',
    'players.deleteTitle':'{name} löschen?',
    'players.deleteBody':'Alles von {name} wird von diesem Gerät entfernt. Das lässt sich nicht rückgängig machen.',
    'players.deleteCard':'Spieler löschen',
    'players.deleteCardSub':'Einen Spieler und alles, was er gespielt hat, von diesem Gerät entfernen',
    'players.deletePick':'Welchen Spieler möchtest du löschen?',
    'settings.logout':'Abmelden',
    'settings.logoutSub':'Einen anderen Spieler wählen oder einen neuen beginnen.',

    'voice.milo':'Milo',
    'voice.milo.desc':'Fröhlich & munter',
    'voice.luna':'Luna',
    'voice.luna.desc':'Ruhig & freundlich',
    'voice.silent':'Still',
    'voice.silent.desc':'Keine Stimme',
    'voice.milo.hello':'Hallo! Ich bin Milo. Bereit zum Spielen?',
    'voice.luna.hello':'Hallo! Ich bin Luna. Wollen wir zusammen entdecken?',

    'home.greeting':'Hallo {name}!',
    'home.greetingAnon':'Hallo!',
    'home.level':'Level {level}',
    'home.coins':'KwizCoins',
    'home.streak':'Tage in Folge',
    'home.pickWorld':'Wähle deine Welt',
    'home.cta':'Abenteuer starten',
    'home.ctaSub':'Weiter in {world}',
    'home.voiceLabel':'Stimme',
    'home.languageLabel':'Sprache',

    'world.kicker':'KWIZILLO-WELT',
    'world.backHome':'Zurück zum Start',
    'world.mix':'Gemischtes Quiz starten',
    'world.mixSub':'Fragen aus allen vier Themen',
    'world.quizNumber':'Quiz {n}',
    'world.topicPassed':'Geschafft',
    'world.topicPlayed':'Quiz {n} gespielt · {correct}/{answered} richtig',
    'world.progressLine':'{passed} von {total} Themen geschafft',
    'world.worldProgress':'{done} von {total} Quiz dieser Welt geschafft',
    'world.mixDone':'{n} gespielt',

    'quiz.mixed':'Gemischtes Quiz',
    'quiz.progress':'Frage {current} von {total}',
    'quiz.hint':'Hinweis',
    'quiz.none':'Für dieses Thema gibt es noch keine Fragen.',
    'quiz.artAlt':'Bild zur Frage',
    'quiz.quizLabel':'Quiz {n}',
    'quiz.back':'Zurück',
    'quiz.explain':'Erklären',
    'quiz.timerAria':'Sekunden übrig',
    'feedback.timeKicker':'ZEIT IST UM!',
    'feedback.timeTitle':'Nächstes Mal schneller!',
    'settings.level':'Level',
    'settings.levelSub':'{seconds} s pro Frage · max. {allowed} Fehler · {hints}',
    'settings.hintsFree':'Hinweise frei',
    'settings.hintsN':'{n} Hinweise',
    'settings.hintsNone':'keine Hinweise',
    'settings.readsQuestionOnly':'nur die Frage wird vorgelesen',
    'quiz.hintsSpent':'In diesem Quiz gibt es keine Hinweise mehr.',
    'quiz.noHints':'Level 6 hat keine Hinweise.',
    'world.speech.enter':'[excited] {title}!',
    'settings.levelAuto':'Auto',
    'settings.share':'Teile dein Ergebnis',
    'settings.shareSub':'Schicke dein Ergebnis an Familie oder Freunde',

    'hint.title':'Ein kleiner Hinweis',
    'hint.kicker':'Tipp zu {topic}',
    'hint.ok':'Weiter überlegen',
    'hint.close':'Hinweis schließen',
    'hint.fallback':'Schau dir die Frage und das Bild noch einmal genau an.',
    'hint.alt':'Bildhinweis',

    'feedback.goodKicker':'RICHTIG!',
    'feedback.tryKicker':'SO KNAPP!',
    'feedback.goodTitle':'Schön gespielt!',
    'feedback.tryTitle':'Gut überlegt!',
    'feedback.correctIs':'Die richtige Antwort ist <strong>{answer}</strong>.',
    'feedback.thatsRight':'Das ist richtig!',
    'feedback.didYouKnow':'Wusstest du das?',
    'feedback.next':'Nächste Frage',
    'feedback.seeResult':'Ergebnis ansehen',
    'feedback.speech.good':'Gut gemacht.',
    'feedback.speech.good.1':'Gut gemacht!',
    'feedback.speech.good.2':'Klasse, das ist richtig!',
    'feedback.speech.good.3':'Genau getroffen!',
    'feedback.speech.good.4':'Sehr schön!',
    'feedback.speech.good.5':'Ja! Genau!',
    'feedback.speech.good.6':'Super, gut geschaut!',
    'feedback.speech.good.7':'Fantastisch!',
    'feedback.speech.good.8':'Wow, das stimmt!',
    'feedback.speech.try.1':'Fast. Die richtige Antwort ist {answer}.',
    'feedback.speech.try.2':'Nicht ganz. Die richtige Antwort ist {answer}.',
    'feedback.speech.try.3':'Guter Versuch! Die richtige Antwort ist {answer}.',
    'feedback.speech.try.4':'Hoppla, so knapp. Die richtige Antwort ist {answer}.',
    'feedback.answerLabel':'Die richtige Antwort',
    'feedback.close':'Schließen',
    'feedback.listening':'Hört zu…',
    'quiz.repeat':'Noch einmal',
    'quiz.repeatAria':'Frage noch einmal vorlesen',
    'feedback.speech.try':'Fast. Die richtige Antwort ist {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'QUIZ GESCHAFFT',
    'result.title':'{score} von {total} richtig!',
    'result.score':'Punkte',
    'result.xp':'XP',
    'result.coins':'Münzen',
    'result.again':'Noch ein Quiz',
    'result.againNumbered':'Quiz {n} starten',
    'result.nextTopic':'Weiter: {topic}',
    'result.finishWorld':'Gemischtes Quiz starten',
    'result.retryTopic':'Dieses Thema noch einmal',
    'result.retryNow':'Noch einmal',
    'memo.title':'Memo',
    'memo.pickTitle':'Wähle deine Welt',
    'game.mixAll':'Mix aus allen Welten',
    'game.pickSub':'Wähle eine Welt oder spiele alle gemischt.',
    'memo.pickSub':'Finde die Paare · Level {n}',
    'memo.otherWorld':'Andere Welt',
    'memo.sub':'Finde die Paare',
    'memo.play':'Memo spielen',
    'memo.playSub':'Finde die Paare von {world}',
    'memo.level':'Level {n}',
    'memo.pairs':'{found} von {total} Paaren',
    'memo.moves':'{n} Züge',
    'memo.movesShort':'Züge',
    'memo.card':'Memo-Karte',
    'memo.hintLine':'Drehe zwei Karten um und finde die Paare',
    'memo.none':'Für diese Welt gibt es noch nicht genug Karten.',
    'memo.doneKicker':'MEMO GESCHAFFT!',
    'memo.doneTitle':'Alle Paare gefunden!',
    'memo.timeKicker':'ZEIT IST UM!',
    'memo.timeTitle':'Fast alle Paare!',
    'memo.summary':'{pairs} Paare in {moves} Zügen und {secs} Sekunden.',
    'memo.summaryTime':'{found} von {pairs} Paaren gefunden. Versuche es noch einmal!',
    'memo.again':'Noch einmal',
    'memo.retry':'Noch einmal',
    'memo.toWorld':'Zurück zur Welt',
    'memo.speech.done':'Wow, du hast alle Paare gefunden! Was für ein Gedächtnis!',
    'memo.speech.time':'Die Zeit ist um. Nächstes Mal schaffst du alle!',
    'memo.modeTitle':'Wie spielst du?',
    'memo.solo':'Allein','memo.soloSub':'Gegen die Uhr',
    'memo.duel':'Gegeneinander','memo.duelSub':'Abwechselnd, wer findet die meisten Paare?',
    'memo.player1':'Spieler 1','memo.player2':'Spieler 2','memo.p2Label':'Wer spielt mit?',
    'memo.turn':'{name} ist dran',
    'memo.duelKicker':'MEMO-DUELL',
    'memo.duelWin':'{name} gewinnt!','memo.duelTie':'Unentschieden!',
    'memo.duelSummary':'{pairs} Paare in {moves} Zügen.',
    'memo.rematch':'Revanche',
    'memo.speech.win':'Wir haben einen Gewinner! Schön gespielt, ihr beiden!',
    'memo.speech.tie':'Unentschieden! Ihr könnt euch beide gut erinnern!',
    'home.playMore':'Mehr spielen',
    'math.title':'Rechnen',
    'facts.title':'Wissenswertes',
    'world.ruimte.short':'Weltraum','world.dieren.short':'Tiere','world.aarde.short':'Erde','world.geschiedenis.short':'Geschichte','world.wetenschap.short':'Wissenschaft','world.kunst.short':'Kunst','world.sport.short':'Sport','world.mysterie.short':'Geheimnis',
    'facts.tileSub':'Wusstest du…',
    'facts.sub':'{seen} von {total} entdeckt',
    'facts.next':'Nächstes Wissen',
    'facts.listen':'Vorlesen',
    'facts.kicker':'Wusstest du…',
    'facts.new':'Neu!',
    'facts.allSeen':'Du hast alles entdeckt! Jetzt kommt es noch einmal.',
    'facts.more':'Mehr Wissen',
    'math.sub':'Schnelle Aufgaben',
    'math.play':'Rechnen',
    'math.playSub':'Zehn Aufgaben · Level {n}',
    'math.progress':'Aufgabe {current} von {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'{score} von {total} Aufgaben richtig!',
    'math.again':'Zehn neue Aufgaben',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'plus',
    'math.op.minus':'minus',
    'math.op.times':'mal',
    'math.op.divided':'geteilt durch',
    'math.speech.twoStep':'{c} plus {a} mal {b}',
    'math.speech.half':'Die Hälfte von {n}',
    'math.speech.quarter':'Ein Viertel von {n}',
    'math.speech.percent':'{p} Prozent von {n}',
    'math.speech.wrong':'Fast. Es ist {answer}.',
    'math.speech.done':'Toll gerechnet! Alle Aufgaben geschafft.',
    'math.speech.fail':'Guter Versuch. Noch einmal und du hast es!',
    'math.hint.plus':'Zähle von {a} weiter: {b} dazu.',
    'math.hint.minus':'Beginne bei {a} und zähle {b} zurück.',
    'math.hint.times':'{a} mal {b}: addiere {b} genau {a} mal.',
    'math.hint.divided':'Wie oft passt {b} in {a}?',
    'math.hint.generic':'Rechne Schritt für Schritt.',
    'achievement.math3':'3 Rechenrunden geschafft',
    'stats.mathLine':'{played} Runden gespielt · {won} geschafft',
    'result.passKicker':'GESCHAFFT!',
    'result.failKicker':'NOCH NICHT',
    'result.passRule':'Level {niveau}: du durftest {allowed} Fehler machen und hattest {wrong}.',
    'result.failRule':'Level {niveau}: du darfst {allowed} Fehler machen, du hattest {wrong}. Spiele dieses Thema noch einmal!',
    'result.toCollection':'Zu meiner Sammlung',

    'profile.title':'Mein Profil',
    'profile.sub':'Dein Name, dein Kumpel und deine Einstellungen',
    'profile.saveName':'Namen speichern',
    'profile.saved':'Gespeichert!',
    'profile.buddy':'Mein Kumpel',
    'profile.chooseBuddy':'Kumpel wählen',
    'profile.voice':'Wer liest vor?',
    'achievements.title':'Auszeichnungen',
    'achievements.sub':'Deine Abenteuer und Meilensteine',
    'achievements.summary':'{done}/{total} verdient',
    'achievements.summarySub':'Entdecke weiter und schalte neue Auszeichnungen frei.',
    'achievements.done':'Verdient!',
    'achievement.firstQuiz':'Erstes Quiz',
    'achievement.correct10':'10 richtige Antworten',
    'achievement.correct50':'50 richtige Antworten',
    'achievement.streak7':'7 Tage in Folge',
    'achievement.cards5':'5 Wissenskarten',
    'achievement.allWorlds':'Alle Welten besucht',
    'achievement.memo3':'3 Memo-Spiele gewonnen',

    'collection.title':'Meine Sammlung',
    'collection.sub':'Alles, was du entdeckt hast',
    'collection.tabWorlds':'🌍 Welten',
    'collection.tabCards':'🃏 Karten',
    'collection.tabMascots':'🐾 Kumpel',
    'collection.worldStat':'{correct}/{answered} richtig · {pct}%',
    'progress.worldLine':'{passed} von {total} Quiz geschafft · {points} Punkte',
    'progress.overall':'Insgesamt {points} von {max} Punkten',
    'progress.overallSub':'Jedes geschaffte Quiz ist 25 Punkte wert: eine ganze Welt sind 100.',
    'collection.discovered':'★ Entdeckt',
    'collection.unlockKicker':'NEUER BUDDY!',
    'collection.unlockLine':'Freigespielt mit {n} richtigen Antworten.',
    'score.coinsAdded':'+{n} Münzen gutgeschrieben',
    'score.coinsCapped':'Tagesmaximum erreicht: {n} von deinen {got} Münzen wurden gutgeschrieben.','collection.cardAdded':'{title} ist jetzt in deiner Sammlung!',
    'collection.emptyTitle':'Noch keine Karten',
    'collection.emptyBody':'Beantworte Fragen richtig, um Wissenskarten zu sammeln.',
    'collection.mascotLocked':'noch {n} richtige Antworten',
    'collection.mascotActive':'Aktiv ✓',
    'collection.mascotChoose':'Kumpel wählen',
    'collection.mascotCount':'{unlocked}/{total} Kumpel freigeschaltet',

    'mascot.milo':'Milo',
    'mascot.milo.desc':'Dein kluger Roboterkumpel',
    'mascot.comet':'Komet',
    'mascot.comet.desc':'Weltraumkumpel',
    'mascot.pootje':'Pfötchen',
    'mascot.pootje.desc':'Tierfreund',
    'mascot.terra':'Terra',
    'mascot.terra.desc':'Beschützerin der Erde',
    'mascot.sparky':'Sparky',
    'mascot.sparky.desc':'Experimentierfan',
    'mascot.lumi':'Lumi',
    'mascot.lumi.desc':'Geheimnissucherin',
    'mascot.nova':'Nova','mascot.nova.desc':'Sternenreisende',
    'mascot.kiko':'Kiko','mascot.kiko.desc':'Dschungelforscher',
    'mascot.pip':'Pip','mascot.pip.desc':'Eiskalter Draufgänger',
    'mascot.ravi':'Ravi','mascot.ravi.desc':'Erfinder in Ausbildung',
    'mascot.flora':'Flora','mascot.flora.desc':'Freundin der Natur',
    'mascot.draco':'Draco','mascot.draco.desc':'Kleiner Burgdrache',

    'stats.title':'Statistik',
    'stats.sub':'Echter Fortschritt aus deinen gespielten Fragen',
    'stats.heroTitle':'Dein Wissen wächst',
    'stats.heroSub':'{answered} Fragen beantwortet · {quizzes} {quizWord} gespielt',
    'stats.correctShort':'richtig',
    'stats.xpTotal':'XP insgesamt',
    'stats.coins':'KwizCoins',
    'stats.streak':'Tage in Folge',
    'stats.cards':'Karten',
    'stats.perWorld':'Pro Welt',
    'stats.games':'Spiele',
    'stats.playedLine':'{played}-mal gespielt',
    'stats.runnerLine':'{played} Läufe · {coins} Münzen gesammelt',
    'stats.memoBest':'{n} Züge',
    'stats.memoLine':'{played} Memo-Spiele gespielt · {won} gewonnen',
    'share.text':'{name} spielt Kwizillo! Level {level}, {correct} richtige Antworten, {cards} Wissenskarten. Bestes Quiz: {best}. Willst du auch spielen?',
    'share.copied':'Text kopiert – füge ihn in eine Nachricht ein.',
    'result.share':'Teile dein Ergebnis',
    'stats.worldLine':'{correct} von {answered} richtig · {quizzes} {quizWord}',
    'stats.quizOne':'Quiz',
    'stats.quizMany':'Quiz',

    'settings.title':'Elternbereich',
    'settings.sub':'Einstellungen für ein gutes Spielerlebnis',
    'settings.group':'Klasse',
    'settings.groupSub':'Schwierigkeit anpassen',
    'settings.groupValue':'{n}. Klasse',
    'settings.language':'Sprache',
    'settings.languageSub':'Wähle die Sprache des Spiels',
    'settings.sound':'Ton, Musik & Stimme',
    'settings.soundVoiceOff':'Stimme aus',
    'settings.soundVoiceOn':'Stimme: {voice}',
    'settings.soundMusic':'Musik {state}',
    'settings.on':'an',
    'settings.off':'aus',
    'settings.timeLimit':'Fragen-Timer',
    'settings.timeLimitOff':'Aus',
    'settings.timeLimitValue':'{n} Sekunden pro Frage in diesem Level',
    'settings.privacy':'Datenschutz & Sicherheit',
    'privacy.sub':'Was das Spiel speichert und was es nicht tut',
    'privacy.updated':'Aktualisiert: {date}',
    'privacy.device':'Auf diesem Gerät',
    'privacy.deviceBody':'Das liegt im Speicher der App auf diesem Gerät. Es geht weder an Kwizillo noch an jemand anderen und verschwindet, sobald du die App löschst oder unten alles löschst.',
    'privacy.itemName':'Name: {value}',
    'privacy.itemSettings':'Sprache, Stimme, Ton, Klasse und Level',
    'privacy.itemProgress':'Fortschritt: {answered} Fragen, {correct} richtig, {cards} Karten',
    'privacy.itemPremium':'Ob Premium aktiv ist (das kommt vom App Store)',
    'privacy.leaves':'Was das Gerät verlässt',
    'privacy.leavesBody':'Nur der Satz, den Milo oder Luna vorliest. Er geht an unseren eigenen Server und von dort an den Sprachdienst ElevenLabs. Es ist immer Text aus dem Spiel: eine Frage, eine Antwort, ein Hinweis oder ein Fakt. Nie der Name deines Kindes und nie etwas, das dein Kind selbst tippt.',
    'privacy.none':'Was die App nicht tut',
    'privacy.noneBody':'Keine Werbung. Keine Analyse-Dienste und keine Tracker von Dritten. Kein Konto, keine E-Mail-Adresse, kein Passwort. Kein Standort, keine Kontakte, keine Kamera, kein Mikrofon. Keine Cookies.',
    'privacy.keep':'Aufbewahren und löschen',
    'privacy.keepBody':'Was auf diesem Gerät liegt, bleibt, bis du es löschst; woanders bewahren wir nichts auf. Unser Server speichert die erzeugte Audio (Spielsätze, keine persönlichen Daten), damit derselbe Satz nicht zweimal erzeugt werden muss, und hält die IP-Adresse einer Anfrage kurz im Speicher, um Missbrauch zu verhindern.',
    'privacy.erase':'Alle Daten löschen',
    'privacy.eraseSub':'Name, Einstellungen und Fortschritt auf diesem Gerät',
    'privacy.eraseTitle':'Alles löschen?',
    'privacy.eraseBody':'Name, Einstellungen, Fortschritt, Karten und Statistik verschwinden von diesem Gerät. Ein gekauftes Premium bleibt bei deinem App-Store-Konto und kommt mit „Käufe wiederherstellen“ zurück.',
    'privacy.eraseConfirm':'Ja, alles löschen',
    'privacy.contact':'Fragen zum Datenschutz?',
    'privacy.contactSub':'Schreib an {email}',
    'privacy.noAccount':'Kwizillo funktioniert ohne Konto: Bei uns gibt es nichts anzumelden und nichts zu löschen.',
    'score.points':'Punkte',
    'score.practice':'Übungspunkte',
    'score.dayFull':'Tagesmaximum erreicht',
    'score.title':'Rekorde',
    'score.sub':'Deine besten Punkte in jedem Zeitraum',
    'score.now':'jetzt',
    'score.best':'Rekord',
    'score.run':'Diese Übung',
    'score.day':'Heute',
    'score.week':'Diese Woche',
    'score.month':'Diesen Monat',
    'score.year':'Dieses Jahr',
    'score.allTime':'Aller Zeiten',
    'score.todayPoints':'{n} von {max} Punkten heute',
    'score.todayCoins':'{n} von {max} Münzen heute',
    'score.capNote':'Pro Tag gibt es ein Maximum an Punkten und Münzen, und eine Frage, die du schon richtig hattest, bringt Übungspunkte. So bleibt ein Rekord etwas wert.',
    'shop.tab':'🛒 Laden',
    'shop.title':'Laden',
    'shop.sub':'Bezahle mit Münzen aus den Spielen',
    'shop.buy':'Kaufen',
    'shop.owned':'Im Besitz','shop.earned':'Verdient',
    'shop.price':'{n} Münzen',
    'shop.need':'Noch {n} Münzen',
    'shop.confirmTitle':'{item} kaufen?',
    'shop.confirmBody':'Das kostet {n} Münzen. Danach gehört {item} für immer dir.',
    'shop.bought':'{item} gehört dir!',
    'shop.cards':'Goldene Karten',
    'shop.mascots':'Freunde',
    'shop.goldCard':'Goldenes {world}',
    'shop.goldCardSub':'Eine glänzende Karte für deine Sammlung',
    'shop.earnHint':'Münzen verdienst du im Runner und in den anderen Spielen.',
    'shop.empty':'Alles gekauft! Der Laden ist ganz leer.',
    'result.worldLevelUp':'🎉 {world} steigt auf Level {niveau}!',
    'result.worldMastered':'🏆 {world} ganz geschafft!',
    'result.goldCardEarned':'Du hast die goldene Karte von {world} verdient!',
    'result.goldCardSpeech':'Wow! Du hast {world} komplett geschafft. Die goldene Karte gehört dir!',
    'settings.levelWorlds':'Level pro Welt',
    'settings.levelWorldsSub':'Eine Welt steigt von allein auf, wenn du dort alle vier Quiz schaffst.',
    'settings.levelMath':'Spielstufe',
    'settings.timeLimitPerWorld':'Die Zeit pro Frage richtet sich nach der Stufe.',
    'settings.reset':'Fortschritt zurücksetzen',
    'settings.resetSub':'Ganz von vorn beginnen',
    'settings.resetTitle':'Fortschritt zurücksetzen?',
    'settings.resetBody':'XP, Münzen, Karten, Statistik und gespielter Fortschritt gehen zurück auf Anfang.',
    'settings.resetConfirm':'Ja, zurücksetzen',
    'gate.title':'Eine kurze Frage für einen Erwachsenen',
    'gate.body':'Wie viel ist {a} × {b}?',
    'gate.placeholder':'Antwort',
    'gate.wrong':'Das stimmt nicht. Versuche es noch einmal.',
    'gate.continue':'Weiter',

    'sound.kicker':'EINSTELLUNGEN',
    'sound.title':'🔊 Ton & Musik',
    'sound.fx':'✨ Klangeffekte',
    'sound.music':'🎵 Hintergrundmusik',
    'sound.test':'Testen',
    'sound.pickMusic':'Wähle deine Musik',
    'sound.voiceGuide':'Sprachbegleiter',
    'track.home':'Inseln',
    'track.space':'Weltraum',
    'track.jungle':'Dschungel',
    'track.earth':'Erde',
    'track.history':'Geschichte',
    'track.science':'Wissenschaft',
    'track.mystery':'Geheimnis',
    'track.play':'Spiele',

    'intro.skip':'Intro überspringen',
    'welcome.back.title':'Hallo {name}!',
    'welcome.back.sub':'Bereit weiterzuspielen?',
    'welcome.back.continue':'Weiterspielen',
    'welcome.back.other':'Jemand anderes spielt',
    'welcome.back.where':'Hier warst du stehen geblieben',
    'welcome.pick.title':'Wer spielt?',
    'welcome.pick.new':'Neue Spielerin oder Spieler',
    'welcome.pick.back':'Zurück',
    'intro.tapToStart':'Tippe zum Starten',
    'intro.tapForSound':'Tippe für Ton'
  };
})();
