(()=>{
  // European Portuguese UI strings (Português de Portugal). Same keys and the same layout as every
  // other language; the child is addressed with "tu" throughout.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.ptpt={
    'lang.name':'Português (Portugal)',
    'lang.speech':'ptpt',

    'world.ruimte.title':'Mundo do Espaço',
    'world.ruimte.sub':'Viaja por planetas, estrelas e foguetões',
    'world.dieren.title':'Mundo dos Animais',
    'world.dieren.sub':'Descobre animais em terra, na selva e no mar',
    'world.aarde.title':'Mundo da Terra',
    'world.aarde.sub':'Explora países, oceanos, clima e mapas',
    'world.geschiedenis.title':'Mundo da História',
    'world.geschiedenis.sub':'Entra no tempo dos faraós, cavaleiros e exploradores',
    'world.wetenschap.title':'Mundo da Ciência',
    'world.wetenschap.sub':'Experimenta e descobre como as coisas funcionam',
    'world.mysterie.title':'Mundo do Mistério',
    'world.mysterie.sub':'Resolve enigmas e segue pistas inteligentes',
    'world.kunst.title':'Mundo da Arte',
    'world.kunst.sub':'Descobre quadros, música e grandes construções',
    'world.sport.title':'Mundo do Desporto',
    'world.sport.sub':'Corre, salta e nada com os melhores atletas',

    'topic.zonnestelsel':'Sistema solar',
    'topic.sterren_planeten':'Estrelas e planetas',
    'topic.astronauten':'Astronautas',
    'topic.raket_avontuur':'Aventura de foguetão',
    'topic.egyptenaren':'Egípcios',
    'topic.ridders_kastelen':'Cavaleiros e castelos',
    'topic.romeinen':'Romanos',
    'topic.ontdekkingsreizigers':'Exploradores',
    'topic.slimme_proefjes':'Experiências espertas',
    'topic.lichaam':'O corpo humano',
    'topic.uitvindingen':'Invenções',
    'topic.natuur_energie':'Natureza e energia',
    'topic.raadsels':'Adivinhas',
    'topic.verborgen_schatten':'Tesouros escondidos',
    'topic.natuurmysteries':'Mistérios da natureza',
    'topic.speurtocht':'A grande busca',
    'topic.snelle_dieren':'Animais velozes',
    'topic.baby_dieren':'Crias',
    'topic.waterdieren':'Animais da água',
    'topic.jungle':'Aventura na selva',
    'topic.continenten_landen':'Países e continentes',
    'topic.weer_klimaat':'Tempo e clima',
    'topic.oceanen_natuur':'Oceanos e natureza',
    'topic.kaarten_navigatie':'Mapas e navegação',
    'topic.schilderkunst':'Pintura',
    'topic.muziek':'Música',
    'topic.bouwkunst':'Arquitetura',
    'topic.dans_theater':'Dança e teatro',
    'topic.balsporten':'Desportos de bola',
    'topic.olympische_spelen':'Jogos Olímpicos',
    'topic.water_wintersport':'Desportos na água e na neve',
    'topic.records_helden':'Recordes e heróis',

    'nav.home':'Início',
    'nav.achievements':'Conquistas',
    'nav.collection':'Coleção',
    'nav.stats':'Estatísticas',
    'nav.more':'Mais',
    'nav.aria':'Navegação principal',
    'nav.collectionLong':'A minha coleção',
    'nav.moreLong':'Mais / Área dos pais',

    'common.back':'Voltar',
    'common.settings':'Definições',
    'common.close':'Fechar',
    'common.cancel':'Cancelar',
    'common.gotIt':'Percebi',
    'common.brand':'KWIZILLO',
    'common.of':'de',
    // O que sou eu?
    'whoami.title':'O que sou eu?','whoami.round':'Ronda {n} de {total}','whoami.points':'Agora {n} pontos','whoami.ask':'O que sou eu?','whoami.more':'Uma pista','whoami.next':'Seguinte','whoami.timeUp':'Acabou o tempo! Era {answer}.',
    'whoami.speech.ask':'[playful] '+'O que sou eu?',   // spoken only: the voice asks it playfully, the tag is not read out
    'whoami.speech.askLuna':'[warmly] '+'Hmm... o que sou eu?',   // Luna's own, warmer take (as in the Brazilian table)
    'whoami.yes':'Isso, {answer}! +{points}','whoami.almost':'Quase! Era {answer}.',
    'whoami.speech.yes':'É {answer}','whoami.speech.almost':'Quase! Era {answer}.',
    'whoami.doneKicker':'O QUE SOU EU?','whoami.doneTitle':'{n} de {total} certas!','whoami.summary':'{score} de {max} pontos. Quanto mais depressa adivinhas, mais pontos ganhas.',
    'whoami.speech.great':'Uau, adivinhas mesmo depressa! Muito bem.','whoami.speech.done':'Bem jogado! Para a próxima acertas ainda mais.',
    'jungle.title':'Runner','jungle.tileSub':'Corre, salta e voa por três níveis','jungle.loadError':'A selva não carregou. Tenta outra vez mais tarde.',
    'fotozoom.title':'Foto Zoom','fotozoom.round':'Ronda {n} de {total}','fotozoom.points':'Agora {n} pontos','fotozoom.ask':'O que é isto?','fotozoom.out':'Afastar','fotozoom.next':'Seguinte','fotozoom.timeUp':'Acabou o tempo! Era {answer}.',
    'fotozoom.speech.ask':'[playful] '+'O que é isto?',   // spoken only: the voice asks it playfully, the tag is not read out
    'fotozoom.yes':'Sim, {answer}! +{points}','fotozoom.almost':'Quase! Era {answer}.',
    'fotozoom.speech.yes':'É {answer}','fotozoom.speech.almost':'Quase! Era {answer}.',
    'fotozoom.doneKicker':'FOTO ZOOM','fotozoom.doneTitle':'{n} de {total} descobertas!','fotozoom.summary':'{score} de {max} pontos. Quanto menos afastas, mais pontos ganhas.',
    'fotozoom.speech.great':'Que olhos de lince! Muito bem.','fotozoom.speech.done':'Bem visto! Para a próxima descobres ainda mais.',
    'premium.teaser.fotozoom':'O Foto Zoom neste mundo faz parte do Kwizillo Premium. Pede a um adulto para desbloquear todos os mundos.',
    'jungle.brand':'KWIZILLO RUNNER','jungle.eyebrow':'KWIZILLO • ARCADE','jungle.titleA':'Kwizillo','jungle.titleB':'Runner','jungle.back':'Voltar ao Kwizillo','jungle.backShort':'Voltar','jungle.easyShort':'Modo fácil',
    'jungle.levelLabel':'ESCOLHE O TEU NÍVEL','jungle.heroLabel':'QUEM CORRE CONTIGO?','jungle.heroBoy':'Rapaz','jungle.heroGirl':'Rapariga','jungle.glideOn':'Voa!','jungle.glideOff':'Corre!','jungle.levelJungle':'Selva','jungle.levelStad':'Cidade','jungle.levelLucht':'Céu',
    'jungle.swingOn':'Balança!','jungle.swingOff':'Corre!','jungle.powerSpeed':'⚡ {n}s','jungle.popSpeed':'TURBO!','jungle.popSpeedSub':'7 segundos super-rápido · moedas a dobrar','jungle.labelSpeed':'TURBO!',
    'jungle.canvasLabel':'Campo de jogo. Setas para a esquerda e para a direita para virar. Espaço para saltar.','jungle.pause':'Pausa','jungle.sound':'Som ligado ou desligado','jungle.controls':'Controlos do jogo','jungle.left':'Esquerda','jungle.right':'Direita','jungle.jump':'Saltar ↑',
    'jungle.loading':'A preparar a tua aventura…','jungle.loadErrorTitle':'Tenta outra vez','jungle.loadErrorBody':'As imagens da selva não carregaram. Verifica a tua ligação e tenta outra vez.',
    'jungle.intro':'Segue o trilho dourado.<br>Salta, explora e coleciona!','jungle.legendMagnet':'🧲 Íman','jungle.legendShield':'🛡 Escudo','jungle.legendGold':'★ Ouro +5','jungle.legendDouble':'×2 Estrela bónus',
    'jungle.easy':'Corrida tranquila · salta sozinho','jungle.music':'Música','jungle.on':'ligada','jungle.off':'desligada','jungle.start':'Partir para a aventura →',
    'jungle.help':'{n} segundos • Desliza ou usa os botões<br>10 moedas seguidas = +5 de bónus<br>Apanha power-ups e descobre uma carta','jungle.countFollow':'Segue as moedas!','jungle.countReady':'Pronto para a aventura?',
    'jungle.pauseEyebrow':'RESPIRA UM POUCO','jungle.pauseTitle':'A tua selva<br>está à espera.','jungle.pauseBody':'O tempo parou.','jungle.resume':'Continuar →','jungle.exit':'Sair sem recompensa',
    'jungle.hit':'Ups! Paraste — continua a correr.','jungle.hitLost':'Ai! Bateste — perdeste {n} moedas.','jungle.labelHit':'−{n}','jungle.lostCoins':'Moedas perdidas','jungle.cardFound':'Encontraste uma carta da selva!','jungle.powerDouble':'×2 {n}s','jungle.powerMagnet':'🧲 {n}s','jungle.powerShield':'🛡 Protegido','jungle.powerStreak':'★ {n} seguidas',
    'jungle.popDouble':'ESTRELA BÓNUS!','jungle.popDoubleSub':'6 segundos de moedas a dobrar','jungle.popGold':'OURO ENCONTRADO!','jungle.popGoldSub':'+{n} moedas','jungle.popCombo':'{n} SEGUIDAS!','jungle.popComboSub':'+5 de bónus combo','jungle.popMagnet':'ÍMAN DE MOEDAS!','jungle.popMagnetSub':'7 segundos a atrair moedas',
    'jungle.popShield':'ESCUDO!','jungle.popShieldSub':'Aguenta uma pancada','jungle.popBlock':'O ESCUDO SALVOU-TE!','jungle.popBlockSub':'Continua a correr','jungle.popCard':'CARTA ENCONTRADA!','jungle.popCardSub':'Revelada na chegada','jungle.popClear':'BELO SALTO!','jungle.popClearSub':'Por cima do tronco','jungle.popDoubleflip':'SALTO DUPLO!','jungle.popDoubleflipSub':'+3 moedas',
    'jungle.labelGold':'+{n} OURO!','jungle.labelCombo':'COMBO +5','jungle.labelCard':'Carta encontrada!','jungle.labelClear':'Belo salto!','jungle.labelMagnet':'ÍMAN!','jungle.labelShield':'ESCUDO!','jungle.labelBlock':'Salvo!','jungle.labelDouble':'MOEDAS A DOBRAR!',
    'jungle.saving':'A guardar a tua recompensa…','jungle.saved':'As tuas moedas foram adicionadas.','jungle.saveError':'Ainda não deu para guardar. Tenta outra vez.',
    'jungle.finishEyebrow':'AVENTURA CONCLUÍDA','jungle.finish':'CHEGADA!','jungle.finishSub':'O teu tesouro desta corrida','jungle.coinsEarned':'moedas ganhas','jungle.bestStreak':'Melhor sequência','jungle.bonusCoins':'Moedas bónus',
    'jungle.cardAlt':'Carta colecionada','jungle.cardEyebrow':'CARTA DESCOBERTA','jungle.cardSub':'Para a tua coleção Kwizillo','jungle.cardTitle':'Folha da selva','card.jungle-leaf':'Folha da selva','card.city-star':'Estrela da cidade','card.sky-feather':'Pena do céu','jungle.retry':'Guardar outra vez','jungle.take':'Levar o meu tesouro','jungle.again':'Outra aventura','jungle.replay':'Joga outra vez',
    // Premium
    'common.ok':'OK','common.retry':'Tentar outra vez',
    'premium.label':'Premium','premium.name':'Kwizillo Premium','premium.kicker':'PARA OS PAIS',
    'premium.title':'Desbloqueia todo o mundo de Kwizillo',
    'premium.subtitle':'Brinca, aprende, coleciona e descobre sem limites.',
    'premium.benefit.worlds':'Todos os mundos','premium.benefit.questions':'1280 perguntas de conhecimento','premium.benefit.math':'Jogos de matemática','premium.benefit.memo':'Jogos de memória','premium.benefit.facts':'Curiosidades','premium.benefit.guides':'Milo & Luna','premium.benefit.collect':'Coleciona cartas e mascotes','premium.benefit.stats':'Progresso e estatísticas completas','premium.benefit.new':'Novas aventuras e conteúdos',
    'premium.monthly':'Mensal','premium.yearly':'Anual','premium.perMonth':'mês','premium.perYear':'ano',
    'premium.best':'Melhor escolha','premium.trial':'Experimenta grátis durante {days} dias','premium.ctaTrial':'Começar {days} dias grátis','premium.ctaYearly':'Escolher plano anual','premium.ctaMonthly':'Escolher plano mensal',
    'premium.perMonthCalc':'Dá {price} por mês',
    'premium.legal':'A subscrição é cobrada na conta Apple e renova-se automaticamente até ser cancelada. Pode ser gerida ou cancelada a qualquer momento nas subscrições da conta Apple. O período grátis passa a subscrição paga se não for cancelado antes do fim.',
    'premium.restore':'Restaurar compras','premium.restoreSub':'Recuperar o Premium neste dispositivo','premium.manage':'Gerir subscrição','premium.manageSub':'Cancelar ou alterar através da Apple','premium.privacy':'Privacidade','premium.terms':'Termos de Utilização',
    'premium.loading':'A carregar preços…','premium.purchasing':'Um momento, a Apple está a processar a compra…',
    'premium.pending':'A compra está a aguardar aprovação. Assim que for aprovada, o Premium ativa-se sozinho.',
    'premium.cancelled':'Compra cancelada.','premium.failed':'Não correu bem. Tenta outra vez mais tarde.',
    'premium.unavailable':'O Premium não está disponível neste momento. Tenta outra vez mais tarde.',
    'premium.already':'O Premium está ativo neste dispositivo.',
    'premium.restoring':'A restaurar compras…','premium.restoreNone':'Nenhuma compra anterior encontrada.','premium.manageUnavailable':'As subscrições gerem-se na app Definições do telemóvel, na conta Apple.',
    'premium.welcome':'Bem-vindo ao Kwizillo Premium!','premium.welcomeSub':'Todos os mundos, jogos e curiosidades estão desbloqueados. Diverte-te!','premium.continue':'Continuar onde paraste','premium.play':'Jogar',
    'premium.statusFree':'Versão grátis · desbloqueia tudo','premium.statusActive':'Ativo · {type}','premium.statusTrial':'Período grátis · {type}','premium.statusExpired':'Expirado · o teu progresso está guardado','premium.renews':'Renova a',
    'premium.teaserTitle':'Isto é Premium','premium.askParent':'Chamar um adulto',
    'premium.teaser.quiz':'Este quiz faz parte do Kwizillo Premium. Pede a um adulto para desbloquear todos os mundos.',
    'premium.teaser.mega':'O Mega Quiz faz parte do Kwizillo Premium. Pede a um adulto para desbloquear todos os mundos.',
    'premium.teaser.memo':'Este tabuleiro do jogo de memória faz parte do Kwizillo Premium. Pede a um adulto para desbloquear todos.',
    'premium.teaser.math':'Os níveis mais altos de matemática fazem parte do Kwizillo Premium. Pede a um adulto para os desbloquear.',
    'premium.teaser.facts':'Mais curiosidades fazem parte do Kwizillo Premium. Pede a um adulto para desbloquear todas.',
    'premium.factsMore':'Mais {n} curiosidades com o Premium',
    'premium.teaser.whoami':'O que sou eu? neste mundo faz parte do Kwizillo Premium. Pede a um adulto para desbloquear todos os mundos.',
    'settings.terms':'Termos de Utilização','settings.termsBody':'O Kwizillo é um jogo educativo para crianças. O Premium é uma subscrição cobrada pela Apple que se renova automaticamente até ser cancelada; pode ser cancelada a qualquer momento nas subscrições Apple. Não há anúncios nem compras dentro do jogo.',

    'onboarding.language.title':'Escolhe a tua língua',
    'onboarding.language.sub':'Em que língua queres jogar?',
    'onboarding.name.title':'Como te chamas?',
    'onboarding.name.sub':'Assim podemos cumprimentar-te a sério.',
    'onboarding.name.placeholder':'O teu nome',
    'onboarding.name.hint':'O teu nome fica só neste dispositivo.',
    'onboarding.voice.title':'Quem te vai ajudar?',
    'onboarding.voice.sub':'Escolhe o teu guia. Podes mudar quando quiseres.',
    'onboarding.welcome.title':'Bem-vindo, {name}!',
    'onboarding.welcome.sub':'A tua aventura começa agora. Pronto para explorar?',
    'onboarding.welcome.cta':'Começar a aventura',
    'onboarding.next':'Continuar',
    'onboarding.speech.welcome':'Pronto, está tudo preparado! Anda comigo, que eu mostro-te num instante o que é o quê.',
    'onboarding.speech.language':'Olá! Eu sou o Milo. Que língua falas?',
    'onboarding.speech.name':'Muito prazer! Como te chamas? É só escrever.',
    'onboarding.speech.age':'E quantos anos tens?',
    'onboarding.speech.group':'Em que ano andas na escola?',
    'onboarding.speech.voice':'Quem queres como guia? Eu, a Luna, ou preferes silêncio?',
    'onboarding.age.title':'Quantos anos tens?',
    'onboarding.age.sub':'Toca na tua idade.',
    'onboarding.age.years':'{n} anos',
    'onboarding.group.title':'Em que ano andas?',
    'onboarding.group.sub':'Assim escolho perguntas à tua medida.',
    'tour.mega':'Lá em cima fica o Mega Quiz: oitenta perguntas de todos os mundos, todas misturadas!',
    'tour.worlds':'Estes são os oito mundos, do espaço e dos animais até à arte e ao desporto. Daqui a pouco tocas num mundo e jogas um quiz!',
    'tour.games':'E aqui estão os jogos: Runner, Línguas, Contas, O que sou eu?, Foto Zoom, Curiosidades e Memo. Daqui a pouco podes experimentá-los todos!',
    'tour.facts':'E estas são as Curiosidades: centenas de coisas fixes para descobrir!',
    'tour.hud':'Em cima ficam o teu nível, as tuas moedas e os dias seguidos. A roda dentada é para os adultos.',
    'tour.nav':'Em baixo ficam a coleção, as conquistas e as estatísticas. Em Mais estão as definições.',
    'tour.done':'Agora é a tua vez! Toca no que quiseres. Diverte-te, eu ajudo-te sempre que ficares preso.',
    'tour.skip':'Saltar',
    'tour.again':'Visita com {guide}',
    'tour.againSub':'{guide} mostra outra vez o que é o quê.',
    'tour.pick':'Visita guiada',
    'tour.pickSub':'Escolhe quem vai mostrar o que é o quê.',
    'school.title':'Kwizillo na escola',
    'school.codeAsk':'Qual é o código da tua turma?',
    'school.codeHint':'Está no quadro ou no teu cartão.',
    'school.next':'Continuar',
    'school.codeWrong':'Não conhecemos este código. Olha outra vez.',
    'school.whoAmI':'Quem és tu?',
    'school.pictures':'Toca nas tuas três imagens',
    'school.picturesHint':'Pela ordem certa, como no teu cartão.',
    'school.picturesWrong':'Essas não são as tuas imagens. Tenta outra vez.',
    'school.locked':'Espera um pouco e tenta outra vez.',
    'school.offline':'Sem ligação. Tenta outra vez.',
    'school.back':'Voltar',
    'school.logout':'Sair',
    'school.logoutSub':'Já acabaste de jogar? Sai para o próximo jogar.',
    'school.signedIn':'{name} · {class}',
    'players.title':'Jogadores neste dispositivo',
    'players.sub':'Quem joga neste dispositivo.',
    'settings.feedback':'Ideias e opiniões',
    'settings.feedbackSub':'Ajuda-nos a tornar o Kwizillo ainda melhor',
    'feedback.title':'Conta-nos!',
    'feedback.lead':'Tens uma ideia, há algo que não está bem, ou adoras alguma coisa? Lemos tudo.',
    'feedback.kind.idea':'Ideia',
    'feedback.kind.bug':'Comentário',
    'feedback.kind.love':'Elogio',
    'feedback.placeholder':'Escreve aqui a tua mensagem…',
    'feedback.empty':'Escreve primeiro a tua mensagem.',
    'feedback.send':'Enviar',
    'feedback.note':'Um adulto envia a mensagem por e-mail. O teu nome não vai junto.',
    'feedback.thanksTitle':'Muito obrigado!',
    'feedback.thanks':'Lemos a tua mensagem e vamos usá-la para tornar o Kwizillo ainda melhor, juntamente contigo.',
    'players.current':'a jogar agora',
    'players.delete':'Apagar',
    'players.deleteTitle':'Apagar {name}?',
    'players.deleteBody':'Tudo de {name} desaparece deste dispositivo. Isto não pode ser desfeito.',
    'players.deleteCard':'Apagar jogador',
    'players.deleteCardSub':'Remover um jogador e tudo o que jogou deste dispositivo',
    'players.deletePick':'Que jogador queres apagar?',
    'settings.logout':'Sair',
    'settings.logoutSub':'Escolher outro jogador ou começar um novo.',

    'voice.milo':'Milo',
    'voice.milo.desc':'Alegre e animado',
    'voice.luna':'Luna',
    'voice.luna.desc':'Calma e simpática',
    'voice.silent':'Sem voz',
    'voice.silent.desc':'Sem narração',
    'voice.milo.hello':'Olá! Eu sou o Milo. Pronto para jogar?',
    'voice.luna.hello':'Olá! Eu sou a Luna. Vamos explorar juntos?',

    'home.greeting':'Olá, {name}!',
    'home.greetingAnon':'Olá!',
    'home.level':'Nível {level}',
    'home.coins':'KwizMoedas',
    'home.streak':'Dias seguidos',
    'home.pickWorld':'Escolhe o teu mundo',
    'home.cta':'Começar aventura',
    'home.ctaSub':'Continuar em {world}',
    'home.voiceLabel':'Guia de voz',
    'home.languageLabel':'Língua',

    'world.kicker':'MUNDO KWIZILLO',
    'world.backHome':'Voltar ao início',
    'world.mix':'Começar quiz misto',
    'world.mixSub':'Perguntas dos quatro temas',
    'world.quizNumber':'Quiz {n}',
    'world.topicPassed':'Concluído',
    'world.topicPlayed':'Quiz {n} jogado · {correct}/{answered} certas',
    'world.progressLine':'{passed} de {total} temas concluídos',
    'world.worldProgress':'{done} de {total} quizzes deste mundo concluídos',
    'world.mixDone':'{n} jogados',

    'quiz.mixed':'Quiz misto',
    'mega.title':'Mega Quiz',
    'talen.title':'Línguas',
    'collection.tabWords':'🗣️ Palavras',
    'collection.wordsEmpty':'Ainda sem palavras',
    'collection.wordsEmptyBody':'Joga uma lição em Línguas. Cada palavra que aprendes aparece aqui.',
    'collection.wordsCount':'{n} palavras em {lang}. Toca para ouvir.',
    'stats.talenLine':'{words} palavras aprendidas · {lessons} lições',
    'achievement.talenFirst':'Primeira lição em Línguas',
    'achievement.talen10':'10 palavras aprendidas',
    'talen.passport':'Passaporte de línguas',
    'talen.passportSub':'Aprende {lang} com o Milo',
    'talen.passportSubLuna':'Aprende {lang} com a Luna',
    'talen.pickTitle':'Que língua queres aprender?',
    'talen.pickSub':'Toca numa bandeira e ouve como se diz olá.',
    'talen.pickGo':'Aprende {lang}!',
    'talen.switchLang':'Outra língua',
    'talen.lang.en':'inglês',
    'talen.lang.nl':'neerlandês',
    'talen.lang.de':'alemão',
    'talen.lang.fr':'francês',
    'talen.lang.es':'espanhol',
    'talen.lang.it':'italiano',
    'talen.lang.pt':'português',
    'talen.lang.da':'dinamarquês',
    'talen.lang.ru':'russo',
    'talen.lang.ar':'árabe',
    'talen.soon':'em breve',
    'talen.soonLang':'Em breve também na tua língua',
    'talen.msgNew':'Cada lição vale um carimbo. Começa pelos animais!',
    'talen.msgPlayed':'Fantástico! O teu carimbo está garantido. Joga outra vez para ganhar mais estrelas.',
    'talen.start':'Começar a lição',
    'talen.again':'Jogar {theme} outra vez',
    'talen.review':'Revisão rápida',
    'talen.reviewSub':'{n} palavras para rever',
    'talen.reviewDone':'Boa revisão!',
    'talen.replay':'Outra vez',
    'talen.listen':'Ouve a palavra',
    'talen.picture':'Imagem',
    'talen.means':'significa {word}',
    'talen.round':'Ronda {n} de {total}',
    'talen.firstTry':'certas à primeira',
    'talen.learned':'Aprendeste estas palavras. Toca para ouvir.',
    'talen.theme.dieren':'Animais',
    'talen.theme.kleuren':'Cores',
    'talen.theme.eten':'Comer e beber',
    'talen.theme.getallen':'Números',
    'talen.theme.lichaam':'Corpo',
    'talen.theme.vervoer':'Transportes',
    'talen.theme.sport':'Desporto',
    'talen.theme.praten':'Conversar',
    'talen.section.words':'Palavras',
    'talen.section.sentences':'Frases',
    'talen.speakHead':'Eu falo',
    'talen.catThemes':"{n} temas",
    'talen.theme.huis':'Casa',
    'talen.theme.natuur':'Natureza',
    'talen.theme.familie':'Família',
    'talen.theme.kleding':'Roupa',
    'talen.theme.school':'Escola',
    'talen.theme.vakantie':'Férias',
    'talen.theme.mij':'Sobre mim',
    'talen.theme.vragen':'Perguntas',
    'talen.theme.gevoel':'Sentimentos',
    'talen.theme.samen':'Brincar juntos',
    'talen.theme.mix':'Mistura',
    'talen.done.dieren':'Já conheces os animais!',
    'talen.done.kleuren':'Já conheces as cores!',
    'talen.done.eten':'Já conheces a comida e a bebida!',
    'talen.done.getallen':'Já sabes contar!',
    'talen.done.lichaam':'Já conheces o teu corpo!',
    'talen.done.vervoer':'Já conheces os transportes!',
    'talen.done.sport':'Já conheces os desportos!',
    'talen.done.praten':'Já sabes conversar!',
    'talen.done.huis':'Já conheces a casa toda!',
    'talen.done.natuur':'Já conheces a natureza!',
    'talen.done.familie':'Já conheces a família!',
    'talen.done.kleding':'Já conheces a roupa toda!',
    'talen.done.school':'Já conheces o material escolar!',
    'talen.done.vakantie':'Pronto para as férias!',
    'talen.done.mij':'Já sabes falar de ti!',
    'talen.done.vragen':'Já sabes fazer perguntas!',
    'talen.done.gevoel':'Já sabes dizer como te sentes!',
    'talen.done.samen':'Já podem brincar juntos!',
    'talen.done.mix':'Tudo misturado, e tu sabes!',
    'jungle.bannerSub':'Corre, salta e apanha moedas',
    'settings.learnLang':'Língua para aprender',
    'settings.learnLangSub':'A língua que a criança aprende em Línguas',
    'premium.teaser.talen':'Este tema faz parte do Kwizillo Premium. Os animais são grátis. Pede a um adulto para desbloquear todos os temas.',
    'mega.sub':'{n} perguntas de todos os mundos',
    'mega.rule':'Perguntas de todos os {worlds} mundos: acertaste {score} de {total}.',
    'mega.again':'Mais um Mega Quiz',
    'mega.collectionLine':'Jogado {played} vezes · melhor {best} de {total}',
    'quiz.progress':'Pergunta {current} de {total}',
    'quiz.hint':'Pista',
    'quiz.none':'Ainda não há perguntas para este tema.',
    'quiz.artAlt':'Ilustração da pergunta',
    'quiz.quizLabel':'Quiz {n}',
    'quiz.back':'Voltar',
    'quiz.explain':'Explicação',
    'quiz.timerAria':'Segundos restantes',
    'feedback.timeKicker':'ACABOU O TEMPO!',
    'feedback.timeTitle':'Mais rápido da próxima vez!',
    'settings.level':'Nível',
    'settings.levelSub':'{seconds} s por pergunta · máx. {allowed} erros · {hints}',
    'settings.hintsFree':'pistas livres',
    'settings.hintsN':'{n} pistas',
    'settings.hintsNone':'sem pistas',
    'settings.readsQuestionOnly':'só a pergunta é lida em voz alta',
    'quiz.hintsSpent':'As pistas desta ronda acabaram.',
    'quiz.noHints':'No nível 6 não há pistas.',
    'world.speech.enter':'[excited] {title}!',
    'settings.levelAuto':'Auto',
    'settings.share':'Partilha a tua pontuação',
    'settings.shareSub':'Envia o teu resultado à família ou aos amigos',

    'hint.title':'Uma pequena pista',
    'hint.kicker':'Pista de {topic}',
    'hint.ok':'Continuar a pensar',
    'hint.close':'Fechar pista',
    'hint.fallback':'Olha outra vez com atenção para a pergunta e para a imagem.',
    'hint.alt':'Pista visual',

    'feedback.goodKicker':'CERTO!',
    'feedback.tryKicker':'QUASE!',
    'feedback.goodTitle':'Muito bem!',
    'feedback.tryTitle':'Boa tentativa!',
    'feedback.correctIs':'A resposta certa é <strong>{answer}</strong>.',
    'feedback.thatsRight':'É isso mesmo!',
    'feedback.didYouKnow':'Sabias que…?',
    'feedback.next':'Pergunta seguinte',
    'feedback.seeResult':'Ver resultado',
    'feedback.speech.good':'Muito bem.',
    'feedback.speech.good.1':'Muito bem!',
    'feedback.speech.good.2':'Isso mesmo, está certo!',
    'feedback.speech.good.3':'Certinho!',
    'feedback.speech.good.4':'Boa, acertaste!',
    'feedback.speech.good.5':'Sim! Exatamente!',
    'feedback.speech.good.6':'Boa, bem visto!',
    'feedback.speech.good.7':'Incrível!',
    'feedback.speech.good.8':'Uau, está correto!',
    'feedback.speech.good.9':'Isso, boa!',
    'feedback.speech.good.10':'Fantástico!',
    'feedback.speech.good.11':'Perfeito!',
    'feedback.speech.good.12':'Muito bem, continua assim!',
    'feedback.speech.good.13':'Arrasaste!',
    'feedback.speech.good.14':'Boa!',
    'feedback.speech.good.15':'Certíssimo!',
    'feedback.speech.good.16':'Em cheio!',
    'feedback.speech.good.17':'Espetacular!',
    'feedback.speech.good.18':'Excelente!',
    'feedback.speech.good.19':'Brutal!',
    'feedback.speech.good.20':'Que espetáculo!',
    'feedback.speech.good.21':'Sensacional!',
    'feedback.speech.good.22':'É isso mesmo!',
    'feedback.speech.good.23':'Que fixe!',
    'feedback.speech.good.24':'Dá cá mais cinco!',
    'feedback.speech.good.25':'Muito bom mesmo!',
    'feedback.speech.good.26':'Estás em grande!',
    'feedback.speech.good.27':'Acertaste em cheio!',
    'feedback.speech.good.28':'Uau, acertaste!',
    'feedback.speech.good.29':'Boa, boa!',
    'feedback.speech.good.30':'Genial!',
    'feedback.speech.try.1':'Quase. A resposta certa é {answer}.',
    'feedback.speech.try.2':'Desta vez não foi. A resposta certa é {answer}.',
    'feedback.speech.try.3':'Boa tentativa! A resposta certa é {answer}.',
    'feedback.speech.try.4':'Ups, quase. A resposta certa é {answer}.',
    'feedback.speech.try.5':'Por pouco. A resposta certa é {answer}.',
    'feedback.speech.try.6':'Ena, esta era difícil! A resposta certa é {answer}.',
    'feedback.speech.try.7':'Ah, quase! A resposta certa é {answer}.',
    'feedback.speech.try.8':'Hmm, desta vez não deu. A resposta certa é {answer}.',
    'feedback.speech.try.9':'Não faz mal! A resposta certa é {answer}.',
    'feedback.speech.try.10':'Para a próxima acertas! A resposta certa é {answer}.',
    'feedback.speech.try.11':'Esta era difícil! A resposta certa é {answer}.',
    'feedback.speech.try.12':'Foi por pouco! A resposta certa é {answer}.',
    'feedback.answerLabel':'A resposta certa',
    'feedback.close':'Fechar',
    'feedback.listening':'A ouvir…',
    'quiz.repeat':'Outra vez',
    'quiz.repeatAria':'Ler a pergunta outra vez',
    'feedback.speech.try':'Quase. A resposta certa é {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'QUIZ CONCLUÍDO',
    'result.title':'{score} de {total} certas!',
    'result.score':'pontuação',
    'result.xp':'XP',
    'result.coins':'moedas',
    'result.again':'Outro quiz',
    'result.againNumbered':'Começar quiz {n}',
    'result.nextTopic':'Seguinte: {topic}',
    'result.finishWorld':'Começar quiz misto',
    'result.retryTopic':'Este tema mais uma vez',
    'result.retryNow':'Tentar outra vez',
    'memo.title':'Memo',
    'memo.pickTitle':'Escolhe o teu mundo',
    'game.mixAll':'Mistura de todos os mundos',
    'game.pickSub':'Escolhe um mundo ou joga com todos misturados.',
    'memo.pickSub':'Encontra os pares · Nível {n}',
    'memo.otherWorld':'Outro mundo',
    'memo.sub':'Encontra os pares',
    'memo.play':'Jogar Memo',
    'memo.playSub':'Encontra os pares de {world}',
    'memo.level':'Nível {n}',
    'memo.pairs':'{found} de {total} pares',
    'memo.boostTitle':'Bónus dourado!','memo.boostSub':'3 pares seguidos · +{xp} pontos',
    'memo.moves':'{n} jogadas',
    'memo.movesShort':'jogadas',
    'memo.card':'Carta do memo',
    'memo.hintLine':'Vira duas cartas e encontra os pares',
    'memo.none':'Ainda não há cartas suficientes para este mundo.',
    'memo.doneKicker':'MEMO COMPLETO!',
    'memo.doneTitle':'Todos os pares encontrados!',
    'memo.timeKicker':'ACABOU O TEMPO!',
    'memo.timeTitle':'Quase todos os pares!',
    'memo.summary':'{pairs} pares em {moves} jogadas e {secs} segundos.',
    'memo.summaryTime':'{found} de {pairs} pares encontrados. Tenta outra vez!',
    'memo.again':'Mais uma vez',
    'memo.retry':'Tentar outra vez',
    'memo.toWorld':'Voltar ao mundo',
    'memo.speech.done':'Uau, encontraste os pares todos! Que memória!',
    'memo.speech.time':'Acabou o tempo. Para a próxima consegues!',
    'memo.modeTitle':'Como queres jogar?',
    'memo.solo':'Sozinho','memo.soloSub':'Contra o relógio',
    'memo.duel':'Um contra o outro','memo.duelSub':'Cada um na sua vez: quem encontra mais pares?',
    'memo.player1':'Jogador 1','memo.player2':'Jogador 2','memo.p2Label':'Quem joga contigo?',
    'memo.turn':'Vez de {name}',
    'memo.duelKicker':'DUELO DE MEMO',
    'memo.duelWin':'{name} ganhou!','memo.duelTie':'Empate!',
    'memo.duelSummary':'{pairs} pares em {moves} jogadas.',
    'memo.rematch':'Desforra',
    'memo.speech.win':'Temos um vencedor! Muito bem jogado, os dois!',
    'memo.speech.tie':'Empate! Vocês os dois têm uma memória fantástica!',
    'home.playMore':'Joga também',
    'math.title':'Contas',
    'facts.title':'Curiosidades',
    'world.ruimte.short':'Espaço','world.dieren.short':'Animais','world.aarde.short':'Terra','world.geschiedenis.short':'História','world.wetenschap.short':'Ciência','world.kunst.short':'Arte','world.sport.short':'Desporto','world.mysterie.short':'Mistério',
    'facts.tileSub':'Sabias que…',
    'facts.sub':'{seen} de {total} descobertas',
    'facts.next':'Curiosidade seguinte',
    'facts.listen':'Ler em voz alta',
    'facts.kicker':'Sabias que…',
    'facts.new':'Nova!',
    'facts.allSeen':'Descobriste todas as curiosidades! Agora voltam a passar mais uma vez.',
    'facts.more':'Mais curiosidades',
    'math.sub':'Contas rápidas',
    'math.play':'Contas',
    'math.playSub':'Dez contas · Nível {n}',
    'math.progress':'Conta {current} de {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'{score} de {total} contas certas!',
    'math.again':'Mais dez contas',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'mais',
    'math.op.minus':'menos',
    'math.op.times':'vezes',
    'math.op.divided':'a dividir por',
    'math.op.equals':'é igual a',
    'math.speech.twoStep':'{c} mais {a} vezes {b}',
    'math.speech.half':'Metade de {n}',
    'math.speech.quarter':'Um quarto de {n}',
    'math.speech.percent':'{p} por cento de {n}',
    'math.money.title':'Contar dinheiro',
    'chest.title':'Baú de jogos',
    'chest.sub':'Escolhe um jogo',
    'measure.title':'Medir & Pesar',
    'measure.sub':'Mede e compara',
    'measure.tip':'Mede com cuidado! Vê onde começa e onde acaba.',
    'measure.try':'Quase! Olha outra vez com atenção.',
    'measure.len.pencil':'Quanto mede o lápis?',
    'measure.len.crayon':'Quanto mede o lápis de cera?',
    'measure.len.straw':'Quanto mede a palhinha?',
    'measure.len.brush':'Quanto mede o pincel?',
    'measure.len.ribbon':'Quanto mede a fita?',
    'measure.len.nail':'Quanto mede o prego?',
    'measure.wt.apple':'Quanto pesa a maçã?',
    'measure.wt.cheese':'Quanto pesa o pedaço de queijo?',
    'measure.wt.melon':'Quanto pesa o melão?',
    'measure.wt.pumpkin':'Quanto pesa a abóbora?',
    'measure.wt.book':'Quanto pesa o livro?',
    'measure.wt.potatoes':'Quanto pesa o saco de batatas?',
    'measure.wt.cat':'Quanto pesa o gato?',
    'measure.vol.read':'Quanta água há no copo medidor?',
    'measure.vol.more':'Quanto falta para chegar a 1 litro?',
    'measure.cmp.longer':'O que é mais comprido?',
    'measure.cmp.shorter':'O que é mais curto?',
    'measure.cmp.heavier':'O que é mais pesado?',
    'measure.cmp.lighter':'O que é mais leve?',
    'measure.cmp.more':'Onde há mais?',
    'measure.cmp.less':'Onde há menos?',
    'measure.est.shoe':'Quanto mede um sapato, mais ou menos?',
    'measure.est.door':'Qual é a altura de uma porta, mais ou menos?',
    'measure.est.apple':'Quanto pesa uma maçã, mais ou menos?',
    'measure.est.bag':'Quanto pesa uma mochila da escola, mais ou menos?',
    'measure.est.glass':'Quanto cabe num copo, mais ou menos?',
    'measure.est.bath':'Quanta água cabe numa banheira, mais ou menos?',
    'measure.est.car':'Quanto mede um carro, mais ou menos?',
    'measure.est.elephant':'Quanto pesa um elefante, mais ou menos?',
    'measure.est.bucket':'Quanto cabe num balde, mais ou menos?',
    'measure.est.pencil':'Quanto mede um lápis, mais ou menos?',
    'measure.convert':'Converte!',
    'measure.story':'Lê com atenção e calcula!',
    'measure.story.bottle':'Uma garrafa tem {a} litros. Enches {n} copos de {b} ml. Quantos ml sobram?',
    'measure.story.ribbon':'Uma fita tem {a} metros. Cortas {n} pedaços de {b} cm. Quantos cm sobram?',
    'measure.story.flour':'Um pacote de farinha pesa {a} kg. Usas {n} vezes {b} gramas. Quantos gramas sobram?',
    'measure.story.map':'No mapa, 1 cm são {s} km a sério. A estrada tem {d} cm no mapa. Quantos km tem a sério?',
    'measure.obj.pencil':'lápis',
    'measure.obj.crayon':'lápis de cera',
    'measure.obj.straw':'palhinha',
    'measure.obj.brush':'pincel',
    'measure.obj.ribbon':'fita',
    'measure.obj.nail':'prego',
    'measure.obj.apple':'maçã',
    'measure.obj.cheese':'queijo',
    'measure.obj.melon':'melão',
    'measure.obj.pumpkin':'abóbora',
    'measure.obj.book':'livro',
    'measure.obj.potatoes':'batatas',
    'measure.obj.cat':'gato',
    'measure.obj.elephant':'elefante',
    'measure.obj.mouse':'rato',
    'measure.obj.cow':'vaca',
    'measure.obj.chicken':'galinha',
    'measure.obj.strawberry':'morango',
    'measure.obj.feather':'pena',
    'measure.obj.glassRed':'copo vermelho',
    'measure.obj.glassBlue':'copo azul',
    'measure.obj.package':'pacote',
    'measure.obj.schoolbag':'mochila',
    'measure.obj.rope':'corda',
    'measure.obj.bottle':'garrafa',
    'measure.obj.carton':'pacote de sumo',
    'measure.u.mm':'mm',
    'measure.u.cm':'cm',
    'measure.u.m':'m',
    'measure.u.km':'km',
    'measure.u.g':'g',
    'measure.u.kg':'kg',
    'measure.u.ml':'ml',
    'measure.u.cl':'cl',
    'measure.u.l':'l',
    'math.pick.sub':'O que queres praticar?',
    'math.pick.sums':'Contas',
    'math.money.sub':'Conta as moedas',
    'math.money.ok':'Pronto!',
    'math.money.delete':'Apagar',
    'math.money.ask':'Quanto dá tudo junto?',
    'math.money.main.one':'{n} euro',
    'math.money.main.few':'{n} euros',
    'math.money.main.many':'{n} euros',
    'math.money.sub.one':'{n} cêntimo',
    'math.money.sub.few':'{n} cêntimos',
    'math.money.sub.many':'{n} cêntimos',
    'math.money.and':'e',
    'math.speech.wrong':'Quase. É {answer}.',
    'math.speech.done':'Arrasaste nas contas! Estão todas feitas.',
    'math.speech.fail':'Boa tentativa. Mais uma vez e consegues!',
    'math.hint.plus':'Conta a partir de {a}: mais {b}.',
    'math.hint.minus':'Começa em {a} e conta {b} para trás.',
    'math.hint.times':'{a} vezes {b}: soma {b} {a} vezes.',
    'math.hint.divided':'Quantas vezes cabe {b} em {a}?',
    'math.hint.generic':'Calcula passo a passo.',
    'achievement.math3':'3 rondas de contas',
    'stats.mathLine':'{played} rondas jogadas · {won} passadas',
    'result.passKicker':'PASSASTE!',
    'result.failKicker':'AINDA NÃO',
    'result.passRule':'Nível {niveau}: podias errar {allowed} e erraste {wrong}.',
    'result.failRule':'Nível {niveau}: podes errar {allowed}, e erraste {wrong}. Joga este tema mais uma vez!',
    'result.toHome':'Voltar ao início',

    'profile.title':'O meu perfil',
    'profile.sub':'O teu nome, o teu amigo e as definições',
    'profile.saveName':'Guardar nome',
    'profile.saved':'Guardado!',
    'profile.buddy':'O meu amigo',
    'profile.chooseBuddy':'Escolher amigo',
    'profile.voice':'Quem lê em voz alta?',
    'achievements.title':'Conquistas',
    'achievements.sub':'As tuas aventuras e marcos',
    'achievements.summary':'{done}/{total} conquistadas',
    'achievements.summarySub':'Continua a explorar para desbloquear novas conquistas.',
    'achievements.done':'Conquistada!',
    'achievement.firstQuiz':'Primeiro quiz',
    'achievement.correct10':'10 respostas certas',
    'achievement.correct50':'50 respostas certas',
    'achievement.streak7':'7 dias seguidos',
    'achievement.cards5':'5 cartas de conhecimento',
    'achievement.allWorlds':'Visitou todos os mundos',
    'achievement.memo3':'3 memos ganhos',

    'collection.title':'A minha coleção',
    'collection.sub':'Tudo o que descobriste',
    'collection.tabWorlds':'🌍 Mundos',
    'collection.tabCards':'🃏 Cartas',
    'collection.tabMascots':'🐾 Amigos',
    'collection.worldStat':'{correct}/{answered} certas · {pct}%',
    'progress.worldLine':'{passed} de {total} quizzes concluídos · {points} pontos',
    'progress.overall':'Total {points} de {max} pontos',
    'progress.overallSub':'Cada quiz concluído vale 25 pontos: um mundo inteiro vale 100.',
    'collection.discovered':'★ Descoberta',
    'collection.unlockKicker':'NOVO AMIGO!',
    'collection.unlockLine':'Desbloqueado com {n} respostas certas.',
    'score.coinsAdded':'+{n} moedas adicionadas',
    'score.coinsCapped':'Máximo do dia: {n} das tuas {got} moedas foram adicionadas.','collection.cardAdded':'{title} já está na tua coleção!',
    'collection.emptyTitle':'Ainda sem cartas',
    'collection.emptyBody':'Acerta perguntas para colecionar cartas de conhecimento.',
    'collection.mascotLocked':'Mais {n} respostas certas',
    'collection.mascotShop':'Na loja: {n} moedas',
    'collection.mascotActive':'Ativo ✓',
    'collection.mascotChoose':'Escolher amigo',
    'collection.mascotCount':'{unlocked}/{total} amigos desbloqueados',

    'mascot.milo':'Milo',
    'mascot.milo.desc':'O teu amigo robô esperto',
    'mascot.comet':'Cometa',
    'mascot.comet.desc':'Amigo do espaço',
    'mascot.pootje':'Patinha',
    'mascot.pootje.desc':'Amigo dos animais',
    'mascot.terra':'Terra',
    'mascot.terra.desc':'Protetora da Terra',
    'mascot.sparky':'Sparky',
    'mascot.sparky.desc':'Fã de experiências',
    'mascot.lumi':'Lumi',
    'mascot.lumi.desc':'Caçadora de mistérios',
    'mascot.nova':'Nova','mascot.nova.desc':'Viajante das estrelas',
    'mascot.kiko':'Kiko','mascot.kiko.desc':'Explorador da selva',
    'mascot.pip':'Pip','mascot.pip.desc':'Valente do gelo',
    'mascot.ravi':'Ravi','mascot.ravi.desc':'Inventor em formação',
    'mascot.flora':'Flora','mascot.flora.desc':'Amiga da natureza',
    'mascot.draco':'Draco','mascot.draco.desc':'Dragãozinho do castelo',
    'mascot.mike':'Mike','mascot.mike.desc':'Fã de música com auscultadores',
    'mascot.zibo':'Zibo','mascot.zibo.desc':'Viajante espacial alegre',
    'mascot.leo':'Leo','mascot.leo.desc':'Leão desportista com medalha',
    'mascot.pixi':'Pixi','mascot.pixi.desc':'Raposa artista com pincel',
    'mascot.olli':'Olli','mascot.olli.desc':'Coruja esperta com óculos de aviador',
    'mascot.finn':'Finn','mascot.finn.desc':'Golfinho brincalhão',
    'mascot.ember':'Ember','mascot.ember.desc':'Dragãozinho roxo',

    'stats.title':'Estatísticas',
    'stats.sub':'Progresso real das perguntas que jogaste',
    'stats.heroTitle':'O teu conhecimento está a crescer',
    'stats.heroSub':'{answered} perguntas respondidas · {quizzes} {quizWord}',
    'stats.correctShort':'certas',
    'stats.xpTotal':'XP total',
    'stats.coins':'KwizMoedas',
    'stats.streak':'Dias seguidos',
    'stats.cards':'Cartas',
    'stats.perWorld':'Por mundo',
    'stats.games':'Jogos',
    'stats.playedLine':'{played} partidas jogadas',
    'stats.runnerLine':'{played} corridas · {coins} moedas juntadas',
    'stats.memoBest':'{n} jogadas',
    'stats.memoLine':'{played} memos jogados · {won} ganhos',
    'share.text':'{name} joga Kwizillo! Nível {level}, {correct} respostas certas, {cards} cartas de conhecimento. Melhor quiz: {best}. Também queres jogar?',
    'share.copied':'Texto copiado – cola-o numa mensagem.',
    'result.share':'Partilhar pontuação',
    'stats.worldLine':'{correct} de {answered} certas · {quizzes} {quizWord}',
    'stats.quizOne':'quiz',
    'stats.quizMany':'quizzes',

    'settings.title':'Área dos pais',
    'settings.sub':'Definições para uma boa experiência',
    'settings.group':'Ano escolar',
    'settings.groupSub':'Ajustar a dificuldade',
    'settings.groupValue':'{n}.º ano',
    'settings.language':'Língua',
    'settings.languageSub':'Escolher a língua do jogo',
    'settings.sound':'Som, música e voz',
    'settings.soundVoiceOff':'Voz desligada',
    'settings.soundVoiceOn':'Voz: {voice}',
    'settings.soundMusic':'música {state}',
    'settings.on':'ligada',
    'settings.off':'desligada',
    'settings.timeLimit':'Cronómetro da pergunta',
    'settings.timeLimitOff':'Desligado',
    'settings.timeLimitValue':'{n} segundos por pergunta neste nível',
    'settings.privacy':'Privacidade e segurança',
    'privacy.sub':'O que o jogo guarda e o que não faz',
    'privacy.updated':'Atualizado: {date}',
    'privacy.device':'Neste dispositivo',
    'privacy.deviceBody':'Isto fica no armazenamento da app neste dispositivo. Não vai para a Kwizillo nem para mais ninguém e desaparece assim que a app for apagada ou tudo for apagado aqui em baixo.',
    'privacy.itemName':'Nome: {value}',
    'privacy.itemSettings':'Língua, voz, som, ano escolar e nível',
    'privacy.itemProgress':'Progresso: {answered} perguntas, {correct} certas, {cards} cartas',
    'privacy.itemPremium':'Se o Premium está ativo (isto vem da App Store)',
    'privacy.leaves':'O que sai do dispositivo',
    'privacy.leavesBody':'Só a frase que o Milo ou a Luna leem em voz alta. Vai para o nosso servidor e daí para o serviço de voz ElevenLabs. É sempre texto do jogo: uma pergunta, uma resposta, uma pista ou uma curiosidade. Nunca o nome da criança e nunca nada que a criança escreva.',
    'privacy.none':'O que a app não faz',
    'privacy.noneBody':'Sem anúncios. Sem análises nem rastreadores de terceiros. Sem conta, e-mail ou palavra-passe. Sem localização, contactos, câmara ou microfone. Sem cookies.',
    'privacy.keep':'Guardar e apagar',
    'privacy.keepBody':'O que está neste dispositivo fica até ser apagado; não guardamos cópia em nenhum outro sítio. O nosso servidor guarda o áudio já criado (frases do jogo, nenhum dado pessoal) para não criar a mesma frase duas vezes, e mantém por pouco tempo em memória o endereço IP de um pedido para evitar abusos.',
    'privacy.erase':'Apagar todos os dados',
    'privacy.eraseSub':'Nome, definições e progresso deste dispositivo',
    'privacy.eraseTitle':'Apagar tudo?',
    'privacy.eraseBody':'Nome, definições, progresso, cartas e estatísticas desaparecem deste dispositivo. Um Premium comprado continua na conta da App Store e volta com “Restaurar compras”.',
    'privacy.eraseConfirm':'Sim, apagar tudo',
    'privacy.contact':'Dúvidas sobre privacidade?',
    'privacy.contactSub':'Escreve para {email}',
    'privacy.noAccount':'O Kwizillo funciona sem conta: não há nada para registar nem para eliminar connosco.',
    'score.points':'pontos',
    'score.practice':'pontos de treino',
    'score.dayFull':'máximo do dia alcançado',
    'score.title':'Recordes',
    'score.sub':'Os teus melhores pontos em cada período',
    'score.now':'agora',
    'score.best':'recorde',
    'score.run':'Este exercício',
    'score.day':'Hoje',
    'score.week':'Esta semana',
    'score.month':'Este mês',
    'score.year':'Este ano',
    'score.allTime':'De sempre',
    'score.todayPoints':'{n} de {max} pontos hoje',
    'score.todayCoins':'{n} de {max} moedas hoje',
    'score.capNote':'Todos os dias há um máximo de pontos e moedas, e uma pergunta que já acertaste dá pontos de treino. Assim um recorde vale mesmo.',
    'shop.tab':'🛒 Loja',
    'shop.title':'Loja',
    'shop.sub':'Paga com as moedas dos jogos',
    'shop.buy':'Comprar',
    'shop.owned':'Já é teu','shop.earned':'Conquistada',
    'shop.price':'{n} moedas',
    'shop.need':'Faltam {n} moedas',
    'shop.confirmTitle':'Comprar {item}?',
    'shop.confirmBody':'Custa {n} moedas. Depois {item} é teu para sempre.',
    'shop.bought':'{item} é teu!',
    'shop.cards':'Cartas douradas',
    'shop.mascots':'Amigos',
    'shop.goldCard':'{world} dourado',
    'shop.goldCardSub':'Uma carta brilhante para a tua coleção',
    'shop.earnHint':'As moedas vêm do Runner e dos outros jogos.',
    'shop.empty':'Já compraste tudo! A loja está vazia.',
    'result.worldLevelUp':'🎉 {world} sobe para o nível {niveau}!',
    'result.worldMastered':'🏆 {world} concluído em todos os níveis!',
    'result.goldCardEarned':'Ganhaste a carta dourada de {world}!',
    'result.goldCardSpeech':'Uau! Terminaste {world} por completo. A carta dourada é tua!',
    'settings.levelWorlds':'Nível por mundo',
    'settings.levelWorldsSub':'Um mundo sobe sozinho quando passas os quatro quizzes dele.',
    'settings.levelMath':'Nível do jogo',
    'settings.timeLimitPerWorld':'O tempo por pergunta segue o nível.',
    'settings.reset':'Repor progresso',
    'settings.resetSub':'Começar de novo do zero',
    'settings.resetTitle':'Repor progresso?',
    'settings.resetBody':'XP, moedas, cartas, estatísticas e progresso voltam ao início.',
    'settings.resetConfirm':'Sim, repor',
    'gate.title':'Uma perguntinha para um adulto',
    'gate.body':'Quanto é {a} × {b}?',
    'gate.placeholder':'Resposta',
    'gate.wrong':'Não está certo. Tente outra vez.',
    'gate.continue':'Continuar',

    'sound.kicker':'DEFINIÇÕES',
    'sound.title':'🔊 Som e música',
    'sound.fx':'✨ Efeitos sonoros',
    'sound.music':'🎵 Música de fundo',
    'sound.test':'Testar',
    'sound.pickMusic':'Escolhe a tua música',
    'sound.voiceGuide':'Guia de voz',
    'track.home':'Ilhas',
    'track.space':'Espaço',
    'track.jungle':'Selva',
    'track.earth':'Terra',
    'track.history':'História',
    'track.science':'Ciência',
    'track.mystery':'Mistério',
    'track.play':'Jogos',

    'intro.skip':'Saltar introdução',
    'welcome.back.title':'Olá, {name}!',
    'welcome.back.sub':'Pronto para continuar?',
    'welcome.back.continue':'Continuar a jogar',
    'welcome.back.other':'Vai jogar outra pessoa',
    'welcome.back.where':'Ficaste aqui',
    'welcome.pick.title':'Quem vai jogar?',
    'welcome.pick.new':'Novo jogador',
    'welcome.pick.back':'Voltar',
    'intro.tapToStart':'Toca para começar',
    'intro.tapForSound':'Toca para ouvir'
  };
})();
