(()=>{
  // Arabic UI strings. Same keys and the same layout as every other language.
  // Modern Standard Arabic, simple and warm: the child is addressed directly,
  // and every sentence is short enough to be read aloud in one breath. The page
  // turns right-to-left for this language (i18n.js sets dir), so nothing here
  // needs to carry direction marks.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.ar={
    'lang.name':'العربية',
    'lang.speech':'ar',

    'world.ruimte.title':'عالم الفضاء',
    'world.ruimte.sub':'سافر بين الكواكب والنجوم والصواريخ',
    'world.dieren.title':'عالم الحيوانات',
    'world.dieren.sub':'اكتشف حيوانات البر والغابة والبحر',
    'world.aarde.title':'عالم الأرض',
    'world.aarde.sub':'استكشف البلدان والمحيطات والطقس والخرائط',
    'world.geschiedenis.title':'عالم التاريخ',
    'world.geschiedenis.sub':'ادخل زمن الفراعنة والفرسان والمستكشفين',
    'world.wetenschap.title':'عالم العلوم',
    'world.wetenschap.sub':'جرّب بنفسك واكتشف كيف تعمل الأشياء',
    'world.mysterie.title':'عالم الألغاز',
    'world.mysterie.sub':'حلّ الألغاز وتتبّع الأدلة الذكية',
    'world.kunst.title':'عالم الفن',
    'world.kunst.sub':'اكتشف اللوحات والموسيقى والمباني العظيمة',
    'world.sport.title':'عالم الرياضة',
    'world.sport.sub':'اركض واقفز واسبح مع أبطال الرياضة',

    'topic.zonnestelsel':'المجموعة الشمسية',
    'topic.sterren_planeten':'النجوم والكواكب',
    'topic.astronauten':'روّاد الفضاء',
    'topic.raket_avontuur':'مغامرة الصاروخ',
    'topic.egyptenaren':'المصريون القدماء',
    'topic.ridders_kastelen':'الفرسان والقلاع',
    'topic.romeinen':'الرومان',
    'topic.ontdekkingsreizigers':'المستكشفون',
    'topic.slimme_proefjes':'تجارب ذكية',
    'topic.lichaam':'جسم الإنسان',
    'topic.uitvindingen':'الاختراعات',
    'topic.natuur_energie':'الطبيعة والطاقة',
    'topic.raadsels':'الأحاجي',
    'topic.verborgen_schatten':'الكنوز المخفية',
    'topic.natuurmysteries':'أسرار الطبيعة',
    'topic.speurtocht':'البحث الكبير',
    'topic.snelle_dieren':'حيوانات سريعة',
    'topic.baby_dieren':'صغار الحيوانات',
    'topic.waterdieren':'حيوانات الماء',
    'topic.jungle':'مغامرة الغابة',
    'topic.continenten_landen':'البلدان والقارات',
    'topic.weer_klimaat':'الطقس والمناخ',
    'topic.oceanen_natuur':'المحيطات والطبيعة',
    'topic.kaarten_navigatie':'الخرائط والملاحة',
    'topic.schilderkunst':'فن الرسم',
    'topic.muziek':'الموسيقى',
    'topic.bouwkunst':'فن العمارة',
    'topic.dans_theater':'الرقص والمسرح',
    'topic.balsporten':'الألعاب بالكرة',
    'topic.olympische_spelen':'الألعاب الأولمبية',
    'topic.water_wintersport':'رياضات الماء والثلج',
    'topic.records_helden':'أرقام وأبطال',

    'nav.home':'الرئيسية',
    'nav.achievements':'الجوائز',
    'nav.collection':'المجموعة',
    'nav.stats':'الأرقام',
    'nav.more':'المزيد',
    'nav.aria':'التنقل الرئيسي',
    'nav.collectionLong':'مجموعتي',
    'nav.moreLong':'المزيد / ركن الوالدين',

    'common.back':'رجوع',
    'common.settings':'الإعدادات',
    'common.close':'إغلاق',
    'common.cancel':'إلغاء',
    'common.gotIt':'فهمت',
    'common.brand':'كويزيلو',
    'common.of':'من',

    'whoami.title':'من أنا؟',
    'whoami.round':'الجولة {n} من {total}',
    'whoami.points':'الآن {n} نقطة',
    'whoami.ask':'من أنا؟',
    'whoami.speech.ask':'[playful] '+'من أنا؟',   // spoken only: the voice asks it playfully, the tag is not read out
    'whoami.speech.askLuna':'[warmly] '+'همم... من أنا؟',   // Luna's own: the playful take sounded shrill in her voice (Stefan, 2026-10-10, take 3 of 3)
    'whoami.more':'دليل آخر',
    'whoami.next':'التالي',
    'whoami.timeUp':'انتهى الوقت! كان الجواب {answer}.',
    'whoami.yes':'نعم، {answer}! ‏+{points}',
    'whoami.almost':'كدت تصيب! كان الجواب {answer}.',
    'whoami.speech.yes':'هذا {answer}',
    'whoami.speech.almost':'كدت تصيب! كان الجواب {answer}.',
    'whoami.doneKicker':'من أنا؟',
    'whoami.doneTitle':'خمّنت {n} من {total}!',
    'whoami.summary':'{score} من {max} نقطة. كلما خمّنت أسرع، زادت النقاط.',
    'whoami.speech.great':'رائع، أنت تخمّن بسرعة! أحسنت.',
    'whoami.speech.done':'لعب جميل! في المرة القادمة ستخمّن أكثر.',

    'jungle.title':'العدّاء',
    'jungle.tileSub':'اركض واقفز وطِر عبر ثلاث مراحل',
    'jungle.loadError':'تعذّر تحميل الغابة. حاول مرة أخرى لاحقًا.',

    'fotozoom.title':'الصورة المكبّرة',
    'fotozoom.round':'الجولة {n} من {total}',
    'fotozoom.points':'الآن {n} نقطة',
    'fotozoom.ask':'ما هذا؟',
    'fotozoom.speech.ask':'[playful] '+'ما هذا؟',   // spoken only: the voice asks it playfully, the tag is not read out
    'fotozoom.out':'صغّر الصورة',
    'fotozoom.next':'التالي',
    'fotozoom.timeUp':'انتهى الوقت! كان الجواب {answer}.',
    'fotozoom.yes':'نعم، {answer}! ‏+{points}',
    'fotozoom.almost':'كدت تصيب! كان الجواب {answer}.',
    'fotozoom.speech.yes':'هذا {answer}',
    'fotozoom.speech.almost':'كدت تصيب! كان الجواب {answer}.',
    'fotozoom.doneKicker':'الصورة المكبّرة',
    'fotozoom.doneTitle':'عرفت {n} من {total}!',
    'fotozoom.summary':'{score} من {max} نقطة. كلما صغّرت أقل، زادت النقاط.',
    'fotozoom.speech.great':'يا لها من عين حادة! أحسنت.',
    'fotozoom.speech.done':'نظر جميل! في المرة القادمة ستعرف أكثر.',
    'premium.teaser.fotozoom':'الصورة المكبّرة في هذا العالم جزء من كويزيلو بريميوم. اطلب من أحد والديك فتح كل العوالم.',

    'jungle.brand':'كويزيلو العدّاء',
    'jungle.eyebrow':'كويزيلو • ألعاب',
    'jungle.titleA':'كويزيلو',
    'jungle.titleB':'العدّاء',
    'jungle.back':'العودة إلى كويزيلو',
    'jungle.backShort':'رجوع',
    'jungle.easyShort':'جولة سهلة',
    'jungle.levelLabel':'اختر مرحلتك',
    'jungle.heroLabel':'من يركض معك؟',
    'jungle.heroBoy':'ولد',
    'jungle.heroGirl':'بنت',
    'jungle.glideOn':'حلّق!',
    'jungle.glideOff':'اركض!',
    'jungle.levelJungle':'الغابة',
    'jungle.levelStad':'المدينة',
    'jungle.levelLucht':'السماء',
    'jungle.swingOn':'تأرجح!',
    'jungle.swingOff':'اركض!',
    'jungle.powerSpeed':'⚡ {n}ث',
    'jungle.popSpeed':'سرعة خارقة!',
    'jungle.popSpeedSub':'سبع ثوانٍ سريعة جدًا · عملات مضاعفة',
    'jungle.labelSpeed':'سرعة خارقة!',
    'jungle.canvasLabel':'ساحة اللعب. استخدم سهمي اليمين واليسار للتوجيه، والمسافة للقفز.',
    'jungle.pause':'إيقاف مؤقت',
    'jungle.sound':'تشغيل الصوت أو إيقافه',
    'jungle.controls':'أزرار اللعب',
    'jungle.left':'يسار',
    'jungle.right':'يمين',
    'jungle.jump':'قفزة ↑',
    'jungle.loading':'نجهّز مغامرتك…',
    'jungle.loadErrorTitle':'حاول مرة أخرى',
    'jungle.loadErrorBody':'تعذّر تحميل صور الغابة. تحقق من الاتصال وحاول مرة أخرى.',
    'jungle.intro':'اتبع الدرب الذهبي.<br>اقفز واستكشف واجمع!',
    'jungle.legendMagnet':'🧲 مغناطيس',
    'jungle.legendShield':'🛡 درع',
    'jungle.legendGold':'★ ذهب +5',
    'jungle.legendDouble':'×2 نجمة إضافية',
    'jungle.easy':'جولة سهلة · القفز يحدث وحده',
    'jungle.music':'الموسيقى',
    'jungle.on':'تعمل',
    'jungle.off':'متوقفة',
    'jungle.start':'إلى المغامرة →',
    'jungle.help':'{n} ثانية • اسحب أو استخدم الأزرار<br>عشر عملات متتالية = ‏+5 مكافأة<br>التقط القوى واعثر على بطاقة',
    'jungle.countFollow':'اتبع العملات!',
    'jungle.countReady':'جاهز للمغامرة؟',
    'jungle.pauseEyebrow':'خذ نفسًا',
    'jungle.pauseTitle':'غابتك<br>تنتظرك.',
    'jungle.pauseBody':'الوقت متوقف الآن.',
    'jungle.resume':'أكمل اللعب →',
    'jungle.exit':'الخروج بلا مكافأة',
    'jungle.hit':'أوه! توقّفت للحظة — واصل الركض.','jungle.hitLost':'آخ! اصطدمت — خسرت {n} عملات.','jungle.labelHit':'−{n}','jungle.lostCoins':'عملات مفقودة',
    'jungle.cardFound':'وجدت بطاقة من الغابة!',
    'jungle.powerDouble':'×2 {n}ث',
    'jungle.powerMagnet':'🧲 {n}ث',
    'jungle.powerShield':'🛡 محمي',
    'jungle.powerStreak':'★ {n} متتالية',
    'jungle.popDouble':'نجمة إضافية!',
    'jungle.popDoubleSub':'ست ثوانٍ من العملات المضاعفة',
    'jungle.popGold':'وجدت ذهبًا!',
    'jungle.popGoldSub':'+{n} عملة',
    'jungle.popCombo':'{n} متتالية!',
    'jungle.popComboSub':'+5 مكافأة التتابع',
    'jungle.popMagnet':'مغناطيس العملات!',
    'jungle.popMagnetSub':'سبع ثوانٍ من جذب العملات',
    'jungle.popShield':'درع!',
    'jungle.popShieldSub':'يتحمّل عنك اصطدامًا واحدًا',
    'jungle.popBlock':'الدرع أنقذك!',
    'jungle.popBlockSub':'واصل الركض',
    'jungle.popCard':'وجدت بطاقة!',
    'jungle.popCardSub':'ستظهر عند خط النهاية',
    'jungle.popClear':'قفزة جميلة!',
    'jungle.popClearSub':'فوق الجذع',
    'jungle.popDoubleflip':'شقلبة مزدوجة!',
    'jungle.popDoubleflipSub':'+3 عملات',
    'jungle.labelGold':'+{n} ذهب!',
    'jungle.labelCombo':'تتابع +5',
    'jungle.labelCard':'وجدت بطاقة!',
    'jungle.labelClear':'قفزة جميلة!',
    'jungle.labelMagnet':'مغناطيس!',
    'jungle.labelShield':'درع!',
    'jungle.labelBlock':'نجوت!',
    'jungle.labelDouble':'عملات مضاعفة!',
    'jungle.saving':'نحفظ مكافأتك…',
    'jungle.saved':'أُضيفت عملاتك.',
    'jungle.saveError':'لم ينجح الحفظ بعد. حاول مرة أخرى.',
    'jungle.finishEyebrow':'اكتملت المغامرة',
    'jungle.finish':'خط النهاية!',
    'jungle.finishSub':'غنيمتك من هذه الجولة',
    'jungle.coinsEarned':'عملة مكتسبة',
    'jungle.bestStreak':'أفضل تتابع',
    'jungle.bonusCoins':'عملات المكافأة',
    'jungle.cardAlt':'البطاقة المجمّعة',
    'jungle.cardEyebrow':'وجدت بطاقة',
    'jungle.cardSub':'لمجموعتك في كويزيلو',
    'jungle.cardTitle':'ورقة الغابة','card.jungle-leaf':'ورقة الأدغال','card.city-star':'نجمة المدينة','card.sky-feather':'ريشة السماء',
    'jungle.retry':'احفظ مرة أخرى',
    'jungle.take':'خذ غنيمتي',
    'jungle.again':'مغامرة أخرى',
    'jungle.replay':'العب مرة أخرى',

    'common.ok':'حسنًا',
    'common.retry':'حاول مرة أخرى',

    'premium.label':'بريميوم',
    'premium.name':'كويزيلو بريميوم',
    'premium.kicker':'للوالدين',
    'premium.title':'افتح عالم كويزيلو كله',
    'premium.subtitle':'العب وتعلّم واجمع واكتشف بلا حدود.',
    'premium.benefit.worlds':'كل العوالم',
    'premium.benefit.questions':'1280 سؤالًا معرفيًا',
    'premium.benefit.math':'ألعاب الحساب',
    'premium.benefit.memo':'ألعاب الذاكرة',
    'premium.benefit.facts':'معلومات طريفة',
    'premium.benefit.guides':'ميلو ولونا',
    'premium.benefit.collect':'اجمع البطاقات والأصدقاء',
    'premium.benefit.stats':'كل التقدم والأرقام',
    'premium.benefit.new':'مغامرات ومحتوى جديد',
    'premium.monthly':'شهري',
    'premium.yearly':'سنوي',
    'premium.perMonth':'شهر',
    'premium.perYear':'سنة',
    'premium.best':'الأفضل قيمة',
    'premium.trial':'جرّب {days} أيام مجانًا',
    'premium.ctaTrial':'ابدأ تجربة {days} أيام مجانية',
    'premium.ctaYearly':'اختر السنوي',
    'premium.ctaMonthly':'اختر الشهري',
    'premium.perMonthCalc':'أي {price} في الشهر',
    'premium.legal':'يُحتسب الاشتراك على حساب آبل الخاص بك ويتجدد تلقائيًا حتى تلغيه. يمكنك إدارته أو إلغاؤه في أي وقت من اشتراكات آبل. تتحول التجربة المجانية إلى اشتراك مدفوع ما لم تلغِها قبل انتهائها.',
    'premium.restore':'استعادة المشتريات',
    'premium.restoreSub':'أعد بريميوم على هذا الجهاز',
    'premium.manage':'إدارة الاشتراك',
    'premium.manageSub':'الإلغاء أو التغيير عبر آبل',
    'premium.privacy':'الخصوصية',
    'premium.terms':'شروط الاستخدام',
    'premium.loading':'نحمّل الأسعار…',
    'premium.purchasing':'لحظة من فضلك، آبل تنهي عملية الشراء…',
    'premium.pending':'الشراء بانتظار الموافقة. بمجرد وصولها يعمل بريميوم من تلقاء نفسه.',
    'premium.cancelled':'أُلغي الشراء.',
    'premium.failed':'لم ينجح ذلك. حاول مرة أخرى لاحقًا.',
    'premium.unavailable':'بريميوم غير متاح حاليًا. حاول مرة أخرى لاحقًا.',
    'premium.already':'بريميوم يعمل على هذا الجهاز.',
    'premium.restoring':'نستعيد المشتريات…',
    'premium.restoreNone':'لم نجد عملية شراء سابقة.',
    'premium.manageUnavailable':'أدِر الاشتراكات من تطبيق الإعدادات في هاتفك، تحت حساب آبل.',
    'premium.welcome':'أهلًا بك في كويزيلو بريميوم!',
    'premium.welcomeSub':'كل العوالم والألعاب والمعلومات مفتوحة. استمتع!',
    'premium.continue':'أكمل من حيث كنت',
    'premium.play':'العب',
    'premium.statusFree':'النسخة المجانية · افتح كل شيء',
    'premium.statusActive':'يعمل · {type}',
    'premium.statusTrial':'تجربة مجانية · {type}',
    'premium.statusExpired':'منتهٍ · تقدمك محفوظ',
    'premium.renews':'يتجدد في',
    'premium.teaserTitle':'هذا جزء من بريميوم',
    'premium.askParent':'اسأل أحد والديك',
    'premium.teaser.quiz':'هذه المسابقة جزء من كويزيلو بريميوم. اطلب من أحد والديك فتح كل العوالم.',
    'premium.teaser.mega':'المسابقة الكبرى جزء من Kwizillo Premium. اطلب من أحد الوالدين فتح كل العوالم.',
    'premium.teaser.memo':'لوحة الذاكرة هذه جزء من كويزيلو بريميوم. اطلب من أحد والديك فتح كل اللوحات.',
    'premium.teaser.math':'مستويات الحساب الأعلى جزء من كويزيلو بريميوم. اطلب من أحد والديك فتحها.',
    'premium.teaser.facts':'المزيد من المعلومات جزء من كويزيلو بريميوم. اطلب من أحد والديك فتحها كلها.',
    'premium.factsMore':'{n} معلومة إضافية مع بريميوم',
    'premium.teaser.whoami':'لعبة «من أنا؟» في هذا العالم جزء من كويزيلو بريميوم. اطلب من أحد والديك فتح كل العوالم.',
    'settings.terms':'شروط الاستخدام',
    'settings.termsBody':'كويزيلو لعبة تعليمية للأطفال. بريميوم اشتراك يُحتسب عبر آبل ويتجدد تلقائيًا حتى تلغيه؛ يمكنك الإلغاء في أي وقت من اشتراكات آبل. لا توجد إعلانات ولا مشتريات داخل اللعبة نفسها.',

    'onboarding.language.title':'اختر لغتك',
    'onboarding.language.sub':'بأي لغة تحب أن تلعب؟',
    'onboarding.name.title':'ما اسمك؟',
    'onboarding.name.sub':'حتى نرحّب بك كما يجب.',
    'onboarding.name.placeholder':'اسمك',
    'onboarding.name.hint':'اسمك يبقى على هذا الجهاز.',
    'onboarding.voice.title':'من سيساعدك؟',
    'onboarding.voice.sub':'اختر مرشدك. يمكنك تغييره في أي وقت.',
    'onboarding.welcome.title':'أهلًا بك يا {name}!',
    'onboarding.welcome.sub':'مغامرتك تبدأ الآن. هل أنت جاهز للاستكشاف؟',
    'onboarding.welcome.cta':'ابدأ المغامرة',
    'onboarding.next':'متابعة',
    'onboarding.speech.welcome':'كل شيء جاهز! تعال معي، سأريك بسرعة ما هو ما.',
    'onboarding.speech.language':'مرحبًا! أنا ميلو. ما اللغة التي تتكلمها؟',
    'onboarding.speech.name':'سعيد بلقائك! ما اسمك؟ اكتبه هنا.',
    'onboarding.speech.age':'وكم عمرك؟',
    'onboarding.speech.group':'في أي صف أنت في المدرسة؟',
    'onboarding.speech.voice':'من تريد مرشدًا لك؟ أنا، أم لونا، أم بلا صوت؟',
    'onboarding.age.title':'كم عمرك؟',
    'onboarding.age.sub':'اضغط على عمرك.',
    'onboarding.age.years':'{n} سنة',
    'onboarding.group.title':'في أي صف أنت؟',
    'onboarding.group.sub':'حتى أختار أسئلة تناسبك.',

    'tour.mega':'في الأعلى توجد المسابقة الكبرى: ثمانون سؤالًا من كل العوالم مختلطة معًا!',
    'tour.worlds':'هذه هي العوالم الثمانية، من الفضاء والحيوانات إلى الفن والرياضة. بعد قليل ستضغط على عالم وتلعب مسابقة!',
    'tour.games':'وهنا الألعاب: العدّاء، اللغات، الحساب، من أنا؟، الصورة المكبّرة، معلومات طريفة، والذاكرة. بعد قليل يمكنك تجربتها كلها!',
    'tour.facts':'وهذه المعلومات الطريفة: مئات الأشياء الممتعة لتكتشفها!',
    'tour.hud':'في الأعلى مستواك وعملاتك وأيامك المتتالية. الترس لوالديك.',
    'tour.nav':'في الأسفل مجموعتك وإنجازاتك وإحصاءاتك. في «المزيد» توجد الإعدادات.',
    'tour.done':'الآن جاء دورك! اضغط على ما تريد. استمتع، سأساعدك كلما احتجت.',
    'tour.skip':'تخطٍّ',
    'tour.again':'جولة مع {guide}',
    'tour.againSub':'{guide} يريك من جديد ما هو ما.',
    'tour.pick':'جولة تعريفية',
    'tour.pickSub':'اختر من يريك ما هو ما.',
    'school.title':'Kwizillo في المدرسة',
    'school.codeAsk':'ما رمز صفك؟',
    'school.codeHint':'تجده على السبورة أو على بطاقتك.',
    'school.next':'التالي',
    'school.codeWrong':'لا نعرف هذا الرمز. انظر مرة أخرى.',
    'school.whoAmI':'من أنت؟',
    'school.pictures':'اضغط على صورك الثلاث',
    'school.picturesHint':'بالترتيب الصحيح، كما على بطاقتك.',
    'school.picturesWrong':'هذه ليست صورك. حاول مرة أخرى.',
    'school.locked':'انتظر قليلًا ثم حاول مرة أخرى.',
    'school.offline':'لا يوجد اتصال. حاول مرة أخرى.',
    'school.back':'رجوع',
    'school.logout':'تسجيل الخروج',
    'school.logoutSub':'انتهيت من اللعب؟ سجّل خروجك ليلعب التالي.',
    'school.signedIn':'{name} · {class}',
    'players.title':'اللاعبون على هذا الجهاز',
    'players.sub':'من يلعب على هذا الجهاز.',
    'settings.feedback':'أفكار وملاحظات',
    'settings.feedbackSub':'ساعدنا لنجعل Kwizillo أفضل',
    'feedback.title':'أخبرنا!',
    'feedback.lead':'هل لديك فكرة، أو هناك شيء غير صحيح، أو شيء تحبه كثيرًا؟ نحن نقرأ كل شيء.',
    'feedback.kind.idea':'فكرة',
    'feedback.kind.bug':'ملاحظة',
    'feedback.kind.love':'مديح',
    'feedback.placeholder':'اكتب رسالتك هنا…',
    'feedback.empty':'اكتب رسالتك أولًا.',
    'feedback.send':'إرسال',
    'feedback.note':'يرسل أحد الوالدين الرسالة بالبريد الإلكتروني. اسمك لا يُرسل.',
    'feedback.thanksTitle':'شكرًا جزيلًا!',
    'feedback.thanks':'نقرأ رسالتك ونستخدمها لنجعل Kwizillo أفضل معك.',
    'players.current':'يلعب الآن',
    'players.delete':'حذف',
    'players.deleteTitle':'حذف {name}؟',
    'players.deleteBody':'يُحذف كل ما يخص {name} من هذا الجهاز. لا يمكن التراجع عن ذلك.',
    'players.deleteCard':'حذف لاعب',
    'players.deleteCardSub':'إزالة لاعب وكل ما لعبه من هذا الجهاز',
    'players.deletePick':'أي لاعب تريد حذفه؟',
    'settings.logout':'تسجيل الخروج',
    'settings.logoutSub':'اختيار لاعب آخر أو بدء لاعب جديد.',

    'voice.milo':'ميلو',
    'voice.milo.desc':'مرح ونشيط',
    'voice.luna':'لونا',
    'voice.luna.desc':'هادئة ولطيفة',
    'voice.silent':'بلا صوت',
    'voice.silent.desc':'من دون صوت',
    'voice.milo.hello':'مرحبًا! أنا ميلو. هل أنت جاهز للعب؟',
    'voice.luna.hello':'مرحبًا! أنا لونا. هل نستكشف معًا؟',

    'home.greeting':'مرحبًا يا {name}!',
    'home.greetingAnon':'مرحبًا!',
    'home.level':'المستوى {level}',
    'home.coins':'عملات كويز',
    'home.streak':'أيام متتالية',
    'home.pickWorld':'اختر عالمك',
    'home.cta':'ابدأ المغامرة',
    'home.ctaSub':'أكمل في {world}',
    'home.voiceLabel':'المرشد الصوتي',
    'home.languageLabel':'اللغة',

    'world.kicker':'عالم كويزيلو',
    'world.backHome':'العودة إلى الرئيسية',
    'world.mix':'ابدأ المسابقة المختلطة',
    'world.mixSub':'أسئلة من المواضيع الأربعة',
    'world.quizNumber':'المسابقة {n}',
    'world.topicPassed':'مكتمل',
    'world.topicPlayed':'لعبت {n} اختبارات · {correct}/{answered} صحيحة',
    'world.progressLine':'أكملت {passed} من {total} مواضيع',
    'world.worldProgress':'أكملت {done} من {total} اختبارات هذا العالم',
    'world.mixDone':'لعبت {n}',
    'quiz.mixed':'مسابقة مختلطة',
    'mega.title':'المسابقة الكبرى',
    'talen.title':'اللغات',
    'collection.tabWords':'🗣️ كلمات',
    'collection.wordsEmpty':'لا توجد كلمات بعد',
    'collection.wordsEmptyBody':'العب درسًا في قسم اللغات. كل كلمة تتعلّمها تظهر هنا.',
    'collection.wordsCount':'{n} كلمات باللغة {lang}. اضغط لتسمعها.',
    'stats.talenLine':'{words} كلمات تعلّمتها · {lessons} دروس',
    'achievement.talenFirst':'أول درس في اللغات',
    'achievement.talen10':'تعلّمت 10 كلمات',
    'talen.passport':'جواز اللغات',
    'talen.passportSub':'تعلّم {lang} مع ميلو',
    'talen.passportSubLuna':'تعلّم {lang} مع لونا',
    'talen.pickTitle':'أي لغة تريد أن تتعلّم؟',
    'talen.pickSub':'اضغط على علم لتسمع كيف تقول مرحبًا.',
    'talen.pickGo':'تعلّم {lang}!',
    'talen.switchLang':'لغة أخرى',
    'talen.lang.en':'الإنجليزية',
    'talen.lang.nl':'الهولندية',
    'talen.lang.de':'الألمانية',
    'talen.lang.fr':'الفرنسية',
    'talen.lang.es':'الإسبانية',
    'talen.lang.it':'الإيطالية',
    'talen.lang.pt':'البرتغالية',
    'talen.lang.da':'الدنماركية',
    'talen.lang.ru':'الروسية',
    'talen.lang.ar':'العربية',
    'talen.soon':'قريبًا',
    'talen.soonLang':'قريبًا بلغتك أيضًا',
    'talen.msgNew':'كل درس يمنحك ختمًا. ابدأ بالحيوانات!',
    'talen.msgPlayed':'رائع! ختمك موجود. العب مرة أخرى لتحصل على نجوم أكثر.',
    'talen.start':'ابدأ الدرس',
    'talen.again':'العب {theme} مرة أخرى',
    'talen.review':'مراجعة سريعة',
    'talen.reviewSub':'{n} كلمات حان وقت مراجعتها',
    'talen.reviewDone':'مراجعة رائعة!',
    'talen.replay':'مرة أخرى',
    'talen.listen':'استمع إلى الكلمة',
    'talen.picture':'صورة',
    'talen.means':'تعني {word}',
    'talen.round':'الجولة {n} من {total}',
    'talen.firstTry':'صحيحة من أول مرة',
    'talen.learned':'تعلّمت هذه الكلمات. اضغط لتسمعها.',
    'talen.theme.dieren':'الحيوانات',
    'talen.theme.kleuren':'الألوان',
    'talen.theme.eten':'الطعام والشراب',
    'talen.theme.getallen':'الأعداد',
    'talen.theme.lichaam':'الجسم',
    'talen.theme.vervoer':'المواصلات',
    'talen.theme.sport':'الرياضة',
    'talen.theme.praten':'الكلام',
    'talen.section.words':'كلمات',
    'talen.section.sentences':'جمل',
    'talen.section.conversations':'حوارات',
    'talen.section.conversationsSub':'استمع وافهم',
    'talen.section.speaking':'التحدث',
    'talen.section.speakingSub':'استمع وتحدث',
    'talen.conv.cat.intro':'التعارف',
    'talen.conv.cat.school':'المدرسة',
    'talen.conv.cat.food':'الطعام والشراب',
    'talen.conv.cat.family':'العائلة والأصدقاء',
    'talen.conv.cat.shop':'التسوق',
    'talen.conv.cat.travel':'في الطريق',
    'talen.conv.listenAgain':'استمع مرة أخرى',
    'talen.conv.listen':'استمع جيدًا…',
    'talen.conv.round':'الحوار {n} من {total}',
    'talen.conv.done':'أنت تفهم الآن!',
    'talen.speaking.set.basics':'الكلمات الأولى',
    'talen.speaking.set.greetings':'التحيات',
    'talen.speaking.set.sentences':'جمل',
    'talen.speaking.permissionTitle':'التحدث بالميكروفون',
    'talen.speaking.permissionBody':'من أجل التحدث يستخدم Kwizillo الميكروفون. نستمع فقط أثناء تدربك. لا يتم حفظ صوتك.',
    'talen.speaking.enableMic':'تشغيل الميكروفون',
    'talen.speaking.sayIt':'ردد ورائي',
    'talen.speaking.tapMic':'المس الميكروفون وقلها',
    'talen.speaking.listening':'أنا أستمع…',
    'talen.speaking.micActive':'الميكروفون يعمل',
    'talen.speaking.goodPractice':'تدريب رائع!',
    'talen.speaking.notHeard':'لم أسمعك بعد. حاول مرة أخرى!',
    'talen.speaking.tryAgain':'مرة أخرى',
    'talen.speaking.next':'التالي',
    'talen.speaking.micOff':'الميكروفون مطفأ.',
    'talen.speaking.micOffBody':'يمكنك التدرب بدون ميكروفون أيضًا: استمع وقلها بصوت عالٍ.',
    'talen.speaking.retry':'حاول مجددًا',
    'talen.speaking.withoutMic':'التدرب بدون ميكروفون',
    'talen.speaking.iSaidIt':'لقد قلتها',
    'talen.speaking.done':'تدريب رائع، أحسنت!',
    'talen.speaking.round':'الكلمة {n} من {total}',
    'talen.speaking.correct':'قلتها صحيحة!',
    'talen.speaking.saidAloud':'قلتها بصوت عالٍ!',
    'talen.speaking.almost':'اقتربت!',
    'talen.speaking.heardAs':'سمعت: «{text}». استمع وحاول مرة أخرى.',
    'talen.speakHead':'أنا أتكلم',
    'talen.catThemes':"{n} مواضيع",
    'talen.theme.huis':'البيت',
    'talen.theme.natuur':'الطبيعة',
    'talen.theme.familie':'العائلة',
    'talen.theme.kleding':'الملابس',
    'talen.theme.school':'المدرسة',
    'talen.theme.vakantie':'العطلة',
    'talen.theme.mij':'عني',
    'talen.theme.vragen':'أسئلة',
    'talen.theme.gevoel':'المشاعر',
    'talen.theme.samen':'نلعب معًا',
    'talen.theme.mix':'خليط',
    'talen.done.dieren':'أنت تعرف الحيوانات!',
    'talen.done.kleuren':'أنت تعرف الألوان!',
    'talen.done.eten':'أنت تعرف الطعام والشراب!',
    'talen.done.getallen':'أنت تعرف العدّ!',
    'talen.done.lichaam':'أنت تعرف جسمك!',
    'talen.done.vervoer':'أنت تعرف المواصلات!',
    'talen.done.sport':'أنت تعرف الرياضة!',
    'talen.done.praten':'أنت تعرف كيف تتكلم!',
    'talen.done.huis':'أنت تعرف البيت كله!',
    'talen.done.natuur':'أنت تعرف الطبيعة!',
    'talen.done.familie':'أنت تعرف العائلة!',
    'talen.done.kleding':'أنت تعرف كل الملابس!',
    'talen.done.school':'أنت تعرف أدوات المدرسة!',
    'talen.done.vakantie':'جاهز للعطلة!',
    'talen.done.mij':'يمكنك أن تتحدث عن نفسك!',
    'talen.done.vragen':'يمكنك أن تسأل!',
    'talen.done.gevoel':'يمكنك أن تقول بماذا تشعر!',
    'talen.done.samen':'يمكنكم اللعب معًا!',
    'talen.done.mix':'كل شيء مختلط، وأنت تعرفه!',
    'jungle.bannerSub':'اركض واقفز واجمع العملات',
    'settings.learnLang':'لغة التعلّم',
    'settings.learnLangSub':'اللغة التي يتعلّمها طفلك في قسم اللغات',
    'premium.teaser.talen':'هذا الموضوع جزء من Kwizillo Premium. الحيوانات مجانية. اطلب من أحد الوالدين فتح كل المواضيع.',
    'mega.sub':'{n} سؤالًا من كل العوالم',
    'mega.rule':'أسئلة من كل العوالم ({worlds}): أجبت عن {score} من {total} بشكل صحيح.',
    'mega.again':'مسابقة كبرى أخرى',
    'mega.collectionLine':'لُعبت {played} مرات · الأفضل {best} من {total}',
    'quiz.progress':'السؤال {current} من {total}',
    'quiz.hint':'تلميح',
    'quiz.none':'لا توجد أسئلة لهذا الموضوع بعد.',
    'quiz.artAlt':'صورة توضح السؤال',
    'quiz.quizLabel':'المسابقة {n}',
    'quiz.back':'رجوع',
    'quiz.explain':'اشرح',
    'quiz.timerAria':'الثواني المتبقية',
    'feedback.timeKicker':'انتهى الوقت!',
    'feedback.timeTitle':'كن أسرع في المرة القادمة!',
    'settings.level':'المستوى',
    'settings.levelSub':'{seconds} ثانية للسؤال · بحد أقصى {allowed} أخطاء · {hints}',
    'settings.hintsFree':'تلميحات بلا حدود',
    'settings.hintsN':'{n} تلميحات',
    'settings.hintsNone':'بلا تلميحات',
    'settings.readsQuestionOnly':'يُقرأ السؤال فقط بصوت عالٍ',
    'quiz.hintsSpent':'لم تبقَ تلميحات في هذه المسابقة.',
    'quiz.noHints':'المستوى السادس بلا تلميحات.',
    'world.speech.enter':'[excited] {title}!',
    'settings.levelAuto':'تلقائي',
    'settings.share':'شارك نتيجتك',
    'settings.shareSub':'أرسل نتيجتك إلى العائلة أو الأصدقاء',

    'hint.title':'دليل صغير',
    'hint.kicker':'تلميح {topic}',
    'hint.ok':'واصل التفكير',
    'hint.close':'إغلاق التلميح',
    'hint.fallback':'انظر جيدًا إلى السؤال وإلى الصورة مرة أخرى.',
    'hint.alt':'تلميح مصوّر',

    'feedback.goodKicker':'صحيح!',
    'feedback.tryKicker':'كدت تصيب!',
    'feedback.goodTitle':'لعب جميل!',
    'feedback.tryTitle':'تفكير جيد!',
    'feedback.correctIs':'الجواب الصحيح هو <strong>{answer}</strong>.',
    'feedback.thatsRight':'هذا صحيح!',
    'feedback.didYouKnow':'هل تعلم؟',
    'feedback.next':'السؤال التالي',
    'feedback.seeResult':'شاهد النتيجة',
    'feedback.speech.good':'أحسنت.',
    'feedback.speech.good.1':'أحسنت!',
    'feedback.speech.good.2':'عمل رائع، هذا صحيح!',
    'feedback.speech.good.3':'في الصميم!',
    'feedback.speech.good.4':'جميل!',
    'feedback.speech.good.5':'نعم! بالضبط!',
    'feedback.speech.good.6':'ممتاز، عين حادة!',
    'feedback.speech.good.7':'مدهش!',
    'feedback.speech.good.8':'واو، هذا صحيح!',
    'feedback.speech.good.9':'نعم، هكذا!',
    'feedback.speech.good.10':'ممتاز!',
    'feedback.speech.good.11':'مثالي!',
    'feedback.speech.good.12':'جيد جدًا، استمر!',
    'feedback.speech.good.13':'أنت رائع اليوم!',
    'feedback.speech.good.14':'عمل جيد!',
    'feedback.speech.good.15':'صحيح تمامًا!',
    'feedback.speech.good.16':'إصابة موفقة!',
    'feedback.speech.good.17':'رهيب!',
    'feedback.speech.good.18':'يا سلام!',
    'feedback.speech.good.19':'ممتاز جدًا!',
    'feedback.speech.good.20':'برافو!',
    'feedback.speech.good.21':'عظيم!',
    'feedback.speech.good.22':'صح عليك!',
    'feedback.speech.good.23':'أنت بطل!',
    'feedback.speech.good.24':'جميل جدًا!',
    'feedback.speech.good.25':'إجابة رائعة!',
    'feedback.speech.good.26':'تمام!',
    'feedback.speech.good.27':'مذهل!',
    'feedback.speech.good.28':'كفو!',
    'feedback.speech.good.29':'هايل!',
    'feedback.speech.good.30':'أحسنت جدًا!',
    'feedback.speech.try.1':'كدت تصيب. الجواب الصحيح هو {answer}.',
    'feedback.speech.try.2':'ليس تمامًا. الجواب الصحيح هو {answer}.',
    'feedback.speech.try.3':'محاولة جيدة! الجواب الصحيح هو {answer}.',
    'feedback.speech.try.4':'أوه، كدت تصيب. الجواب الصحيح هو {answer}.',
    'feedback.speech.try.5':'قريب جدًا. الجواب الصحيح هو {answer}.',
    'feedback.speech.try.6':'أوه، كان هذا صعبًا! الجواب الصحيح هو {answer}.',
    'feedback.speech.try.7':'أوه، اقتربت! الجواب الصحيح هو {answer}.',
    'feedback.speech.try.8':'همم، ليس تمامًا. الجواب الصحيح هو {answer}.',
    'feedback.speech.try.9':'لا بأس! الجواب الصحيح هو {answer}.',
    'feedback.speech.try.10':'في المرة القادمة ستنجح! الجواب الصحيح هو {answer}.',
    'feedback.speech.try.11':'كان سؤالًا صعبًا! الجواب الصحيح هو {answer}.',
    'feedback.speech.try.12':'قريب جدًا! الجواب الصحيح هو {answer}.',
    'feedback.answerLabel':'الجواب الصحيح',
    'feedback.close':'إغلاق',
    'feedback.listening':'نستمع…',
    'quiz.repeat':'مرة أخرى',
    'quiz.repeatAria':'اقرأ السؤال مرة أخرى',
    'feedback.speech.try':'كدت تصيب. الجواب الصحيح هو {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'انتهت المسابقة',
    'result.title':'{score} من {total} صحيحة!',
    'result.score':'النتيجة',
    'result.xp':'نقاط خبرة',
    'result.coins':'عملات',
    'result.again':'مسابقة أخرى',
    'result.againNumbered':'ابدأ المسابقة {n}',
    'result.nextTopic':'التالي: {topic}',
    'result.finishWorld':'ابدأ المسابقة المختلطة',
    'result.retryTopic':'هذا الموضوع مرة أخرى',
    'result.retryNow':'حاول مرة أخرى',

    'memo.title':'الذاكرة',
    'memo.pickTitle':'اختر عالمك',
    'game.mixAll':'مزيج كل العوالم',
    'game.pickSub':'اختر عالمًا واحدًا أو العب كل العوالم معًا.',
    'memo.pickSub':'اعثر على الأزواج · المستوى {n}',
    'memo.otherWorld':'عالم آخر',
    'memo.sub':'اعثر على الأزواج',
    'memo.play':'العب الذاكرة',
    'memo.playSub':'اعثر على أزواج {world}',
    'memo.level':'المستوى {n}',
    'memo.pairs':'{found} من {total} أزواج',
    'memo.boostTitle':'دفعة ذهبية!','memo.boostSub':'3 أزواج متتالية · +{xp} نقاط',
    'memo.moves':'{n} محاولة',
    'memo.movesShort':'محاولات',
    'memo.card':'بطاقة ذاكرة',
    'memo.hintLine':'اقلب بطاقتين واعثر على الأزواج',
    'memo.none':'لا توجد بطاقات كافية لهذا العالم بعد.',
    'memo.doneKicker':'انتهت الذاكرة!',
    'memo.doneTitle':'وجدت كل الأزواج!',
    'memo.timeKicker':'انتهى الوقت!',
    'memo.timeTitle':'كدت تجد كل الأزواج!',
    'memo.summary':'{pairs} أزواج في {moves} محاولة و{secs} ثانية.',
    'memo.summaryTime':'وجدت {found} من {pairs} أزواج. حاول مرة أخرى!',
    'memo.again':'مرة أخرى',
    'memo.retry':'حاول مرة أخرى',
    'memo.toWorld':'العودة إلى العالم',
    'memo.speech.done':'واو، وجدت كل الأزواج! ذاكرة رائعة!',
    'memo.speech.time':'انتهى الوقت. في المرة القادمة ستجدها كلها!',
    'memo.modeTitle':'كيف تلعب؟',
    'memo.solo':'بمفردك',
    'memo.soloSub':'سباق مع الوقت',
    'memo.duel':'وجهًا لوجه',
    'memo.duelSub':'بالتناوب، من يجد أكثر أزواج؟',
    'memo.player1':'اللاعب الأول',
    'memo.player2':'اللاعب الثاني',
    'memo.p2Label':'من يلعب معك؟',
    'memo.turn':'دور {name}',
    'memo.duelKicker':'مبارزة الذاكرة',
    'memo.duelWin':'{name} يفوز!',
    'memo.duelTie':'تعادل!',
    'memo.duelSummary':'{pairs} أزواج في {moves} محاولة.',
    'memo.rematch':'مباراة أخرى',
    'memo.speech.win':'لدينا فائز! لعب جميل منكما!',
    'memo.speech.tie':'تعادل! كلاكما بارع في التذكّر!',

    'home.playMore':'العب أكثر',
    'math.title':'الحساب',
    'facts.title':'معلومات طريفة',
    'world.ruimte.short':'الفضاء',
    'world.dieren.short':'الحيوانات',
    'world.aarde.short':'الأرض',
    'world.geschiedenis.short':'التاريخ',
    'world.wetenschap.short':'العلوم',
    'world.kunst.short':'فن','world.sport.short':'رياضة','world.mysterie.short':'الألغاز',
    'facts.tileSub':'هل تعلم…',
    'facts.sub':'اكتشفت {seen} من {total}',
    'facts.next':'المعلومة التالية',
    'facts.listen':'اقرأ بصوت عالٍ',
    'facts.kicker':'هل تعلم…',
    'facts.new':'جديد!',
    'facts.allSeen':'اكتشفت كل المعلومات! ستعود الآن مرة أخرى.',
    'facts.more':'المزيد من المعلومات',

    'math.sub':'مسائل سريعة',
    'math.play':'الحساب',
    'math.playSub':'عشر مسائل · المستوى {n}',
    'math.progress':'المسألة {current} من {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'{score} من {total} مسائل صحيحة!',
    'math.again':'عشر مسائل أخرى',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'زائد',
    'math.op.minus':'ناقص',
    'math.op.times':'ضرب',
    'math.op.divided':'مقسوم على',
    'math.op.equals':'يساوي',
    'math.speech.twoStep':'{c} زائد {a} ضرب {b}',
    'math.speech.half':'نصف {n}',
    'math.speech.quarter':'ربع {n}',
    'math.speech.percent':'{p} بالمئة من {n}',
    'math.money.title':'عُدّ النقود',
    'chest.title':'صندوق الألعاب',
    'chest.sub':'اختر لعبة',
    'measure.title':'القياس والوزن',
    'measure.sub':'قِس وقارِن',
    'measure.tip':'قِس جيدًا! انظر أين يبدأ وأين ينتهي.',
    'measure.try':'اقتربت! انظر مرة أخرى بانتباه.',
    'measure.len.pencil':'كم طول قلم الرصاص؟',
    'measure.len.crayon':'كم طول قلم التلوين؟',
    'measure.len.straw':'كم طول المصّاصة؟',
    'measure.len.brush':'كم طول الفرشاة؟',
    'measure.len.ribbon':'كم طول الشريط؟',
    'measure.len.nail':'كم طول المسمار؟',
    'measure.wt.apple':'كم وزن التفاحة؟',
    'measure.wt.cheese':'كم وزن قطعة الجبن؟',
    'measure.wt.melon':'كم وزن الشمّامة؟',
    'measure.wt.pumpkin':'كم وزن اليقطينة؟',
    'measure.wt.book':'كم وزن الكتاب؟',
    'measure.wt.potatoes':'كم وزن كيس البطاطا؟',
    'measure.wt.cat':'كم وزن القطة؟',
    'measure.vol.read':'كم من الماء في كوب القياس؟',
    'measure.vol.more':'كم ينقص لنحصل على لتر واحد؟',
    'measure.cmp.longer':'أيهما أطول؟',
    'measure.cmp.shorter':'أيهما أقصر؟',
    'measure.cmp.heavier':'أيهما أثقل؟',
    'measure.cmp.lighter':'أيهما أخف؟',
    'measure.cmp.more':'أيهما فيه أكثر؟',
    'measure.cmp.less':'أيهما فيه أقل؟',
    'measure.est.shoe':'كم طول الحذاء تقريبًا؟',
    'measure.est.door':'كم ارتفاع الباب تقريبًا؟',
    'measure.est.apple':'كم وزن التفاحة تقريبًا؟',
    'measure.est.bag':'كم وزن الحقيبة المدرسية تقريبًا؟',
    'measure.est.glass':'كم يتسع الكأس تقريبًا؟',
    'measure.est.bath':'كم من الماء يتسع حوض الاستحمام تقريبًا؟',
    'measure.est.car':'كم طول السيارة تقريبًا؟',
    'measure.est.elephant':'كم وزن الفيل تقريبًا؟',
    'measure.est.bucket':'كم يتسع الدلو تقريبًا؟',
    'measure.est.pencil':'كم طول قلم الرصاص تقريبًا؟',
    'measure.convert':'حوِّل!',
    'measure.story':'اقرأ جيدًا واحسب!',
    'measure.story.bottle':'في الزجاجة {a} لتر. تملأ {n} أكواب، في كل كوب {b} مل. كم مل يبقى؟',
    'measure.story.ribbon':'طول الشريط {a} متر. تقص {n} قطع، طول كل قطعة {b} سم. كم سم يبقى؟',
    'measure.story.flour':'كيس الطحين وزنه {a} كغ. تأخذ منه {n} مرات {b} غرامًا. كم غرامًا يبقى؟',
    'measure.story.map':'على الخريطة، 1 سم يساوي {s} كم في الحقيقة. طول الطريق على الخريطة {d} سم. كم كيلومترًا طوله في الحقيقة؟',
    'measure.obj.pencil':'قلم رصاص',
    'measure.obj.crayon':'قلم تلوين',
    'measure.obj.straw':'مصّاصة',
    'measure.obj.brush':'فرشاة',
    'measure.obj.ribbon':'شريط',
    'measure.obj.nail':'مسمار',
    'measure.obj.apple':'تفاحة',
    'measure.obj.cheese':'جبن',
    'measure.obj.melon':'شمّام',
    'measure.obj.pumpkin':'يقطين',
    'measure.obj.book':'كتاب',
    'measure.obj.potatoes':'بطاطا',
    'measure.obj.cat':'قطة',
    'measure.obj.elephant':'فيل',
    'measure.obj.mouse':'فأر',
    'measure.obj.cow':'بقرة',
    'measure.obj.chicken':'دجاجة',
    'measure.obj.strawberry':'فراولة',
    'measure.obj.feather':'ريشة',
    'measure.obj.glassRed':'كأس أحمر',
    'measure.obj.glassBlue':'كأس أزرق',
    'measure.obj.package':'طرد',
    'measure.obj.schoolbag':'حقيبة مدرسية',
    'measure.obj.rope':'حبل',
    'measure.obj.bottle':'زجاجة',
    'measure.obj.carton':'علبة عصير',
    'measure.u.mm':'مم',
    'measure.u.cm':'سم',
    'measure.u.m':'م',
    'measure.u.km':'كم',
    'measure.u.g':'غ',
    'measure.u.kg':'كغ',
    'measure.u.ml':'مل',
    'measure.u.cl':'سل',
    'measure.u.l':'ل',
    'math.pick.sub':'ماذا تريد أن تتمرن؟',
    'math.pick.sums':'حسابات',
    'math.money.sub':'عُدّ العملات',
    'math.money.ok':'تم!',
    'math.money.delete':'حذف',
    'math.money.ask':'كم المجموع؟',
    'math.money.main.one':'{n} درهم',
    'math.money.main.few':'{n} دراهم',
    'math.money.main.many':'{n} درهمًا',
    'math.money.sub.one':'{n} فلس',
    'math.money.sub.few':'{n} فلوس',
    'math.money.sub.many':'{n} فلسًا',
    'math.money.and':'و',
    'math.speech.wrong':'كدت تصيب. الجواب {answer}.',
    'math.speech.done':'حساب رائع! انتهت كل المسائل.',
    'math.speech.fail':'محاولة جيدة. مرة أخرى وستنجح!',
    'math.hint.plus':'تابع العد من {a}: أضف {b}.',
    'math.hint.minus':'ابدأ من {a} وعُدّ إلى الوراء {b}.',
    'math.hint.times':'{a} ضرب {b}: اجمع {b} عدد {a} مرات.',
    'math.hint.divided':'كم مرة يدخل {b} في {a}؟',
    'math.hint.generic':'احسبها خطوة بخطوة.',
    'achievement.math3':'ثلاث جولات حساب ناجحة',
    'stats.mathLine':'{played} جولات · {won} ناجحة',

    'result.passKicker':'نجحت!',
    'result.failKicker':'ليس بعد',
    'result.passRule':'المستوى {niveau}: كان مسموحًا بـ{allowed} أخطاء وأخطأت {wrong}.',
    'result.failRule':'المستوى {niveau}: يُسمح بـ{allowed} أخطاء، وأخطأت {wrong}. العب هذا الموضوع مرة أخرى!',
    'result.toHome':'إلى الرئيسية',

    'profile.title':'ملفي',
    'profile.sub':'اسمك وصديقك وإعداداتك',
    'profile.saveName':'احفظ الاسم',
    'profile.saved':'تم الحفظ!',
    'profile.buddy':'صديقي',
    'profile.chooseBuddy':'اختر صديقًا',
    'profile.voice':'من يقرأ بصوت عالٍ؟',

    'achievements.title':'الجوائز',
    'achievements.sub':'مغامراتك وإنجازاتك',
    'achievements.summary':'{done}/{total} محققة',
    'achievements.summarySub':'واصل الاستكشاف لتفتح جوائز جديدة.',
    'achievements.done':'محققة!',
    'achievement.firstQuiz':'أول مسابقة',
    'achievement.correct10':'عشر إجابات صحيحة',
    'achievement.correct50':'خمسون إجابة صحيحة',
    'achievement.streak7':'سبعة أيام متتالية',
    'achievement.cards5':'خمس بطاقات معرفة',
    'achievement.allWorlds':'زرت كل العوالم',
    'achievement.memo3':'ثلاث مباريات ذاكرة رابحة',

    'collection.title':'مجموعتي',
    'collection.sub':'كل ما اكتشفته',
    'collection.tabWorlds':'🌍 العوالم',
    'collection.tabCards':'🃏 البطاقات',
    'collection.tabMascots':'🐾 الأصدقاء',
    'collection.worldStat':'{correct}/{answered} صحيحة · {pct}%',
    'progress.worldLine':'نجحت في {passed} من {total} مسابقات · {points} نقطة',
    'progress.overall':'المجموع {points} من {max} نقطة',
    'progress.overallSub':'كل مسابقة تنجح فيها تساوي 25 نقطة: العالم كله 100.',
    'collection.discovered':'★ مكتشفة',
    'collection.unlockKicker':'صديق جديد!',
    'collection.unlockLine':'فُتح بـ {n} إجابات صحيحة.',
    'score.coinsAdded':'أُضيفت {n} عملة',
    'score.coinsCapped':'بلغت حد اليوم: أُضيفت {n} من أصل {got} عملة.','collection.cardAdded':'{title} أصبحت الآن في مجموعتك!',
    'collection.emptyTitle':'لا بطاقات بعد',
    'collection.emptyBody':'أجب عن الأسئلة إجابة صحيحة لتجمع بطاقات المعرفة.',
    'collection.mascotLocked':'{n} إجابات صحيحة إضافية',
    'collection.mascotShop':'في المتجر: {n} عملة',
    'collection.mascotActive':'نشط ✓',
    'collection.mascotChoose':'اختر صديقًا',
    'collection.mascotCount':'فتحت {unlocked}/{total} أصدقاء',

    'mascot.milo':'ميلو',
    'mascot.milo.desc':'صديقك الروبوت الذكي',
    'mascot.comet':'كوميت',
    'mascot.comet.desc':'صديق الفضاء',
    'mascot.pootje':'بوتشي',
    'mascot.pootje.desc':'صديق الحيوانات',
    'mascot.terra':'تيرا',
    'mascot.terra.desc':'حامية الأرض',
    'mascot.sparky':'سباركي',
    'mascot.sparky.desc':'عاشق التجارب',
    'mascot.lumi':'لومي',
    'mascot.lumi.desc':'باحثة الألغاز',
    'mascot.nova':'نوفا',
    'mascot.nova.desc':'مسافرة بين النجوم',
    'mascot.kiko':'كيكو',
    'mascot.kiko.desc':'مستكشف الغابة',
    'mascot.pip':'بيب',
    'mascot.pip.desc':'مغامر الثلج',
    'mascot.ravi':'رافي',
    'mascot.ravi.desc':'مخترع المستقبل',
    'mascot.flora':'فلورا',
    'mascot.flora.desc':'صديقة الطبيعة',
    'mascot.draco':'دراكو',
    'mascot.draco.desc':'تنين القلعة الصغير',
    'mascot.mike':'Mike','mascot.mike.desc':'محبّ الموسيقى بسماعاته',
    'mascot.zibo':'زيبو','mascot.zibo.desc':'مسافر فضاء مرح',
    'mascot.leo':'ليو','mascot.leo.desc':'أسد رياضي بميدالية',
    'mascot.pixi':'بيكسي','mascot.pixi.desc':'ثعلب فنان بفرشاة',
    'mascot.olli':'أولي','mascot.olli.desc':'بومة ذكية بنظارة طيران',
    'mascot.finn':'فين','mascot.finn.desc':'دلفين مرح',
    'mascot.ember':'إمبر','mascot.ember.desc':'تنين بنفسجي صغير',

    'stats.title':'الأرقام',
    'stats.sub':'تقدم حقيقي من الأسئلة التي لعبتها',
    'stats.heroTitle':'معرفتك تكبر',
    'stats.heroSub':'أجبت عن {answered} سؤالًا · لعبت {quizzes} {quizWord}',
    'stats.correctShort':'صحيحة',
    'stats.xpTotal':'مجموع نقاط الخبرة',
    'stats.coins':'عملات كويز',
    'stats.streak':'أيام متتالية',
    'stats.cards':'بطاقات',
    'stats.perWorld':'لكل عالم',
    'stats.games':'الألعاب',
    'stats.playedLine':'لُعبت {played} مرة',
    'stats.runnerLine':'{played} جولات · جمعت {coins} عملة',
    'stats.memoBest':'{n} محاولة',
    'stats.memoLine':'{played} مباريات ذاكرة · {won} رابحة',
    'share.text':'{name} يلعب كويزيلو! المستوى {level}، {correct} إجابة صحيحة، {cards} بطاقة معرفة. أفضل مسابقة: {best}. هل تحب أن تلعب أيضًا؟',
    'share.copied':'نُسخ النص – الصقه في رسالة.',
    'result.share':'شارك نتيجتك',
    'stats.worldLine':'{correct} من {answered} صحيحة · {quizzes} {quizWord}',
    'stats.quizOne':'مسابقة',
    'stats.quizMany':'مسابقات',

    'settings.title':'ركن الوالدين',
    'settings.sub':'إعدادات لتجربة لعب مريحة',
    'settings.group':'الصف الدراسي',
    'settings.groupSub':'اضبط مستوى الصعوبة',
    'settings.groupValue':'الصف {n}',
    'settings.language':'اللغة',
    'settings.languageSub':'اختر لغة اللعبة',
    'settings.sound':'الصوت والموسيقى والمرشد',
    'settings.soundVoiceOff':'المرشد متوقف',
    'settings.soundVoiceOn':'المرشد: {voice}',
    'settings.soundMusic':'الموسيقى {state}',
    'settings.on':'تعمل',
    'settings.off':'متوقفة',
    'settings.timeLimit':'مؤقت السؤال',
    'settings.timeLimitOff':'متوقف',
    'settings.timeLimitValue':'{n} ثانية للسؤال في هذا المستوى',
    'settings.privacy':'الخصوصية والأمان',

    'privacy.sub':'ما تحفظه اللعبة وما لا تفعله',
    'privacy.updated':'آخر تحديث: {date}',
    'privacy.device':'على هذا الجهاز',
    'privacy.deviceBody':'هذا موجود في مساحة التطبيق على هذا الجهاز. لا يصل إلى كويزيلو ولا إلى أي جهة أخرى، ويختفي فور حذفك التطبيق أو مسحك كل شيء في الأسفل.',
    'privacy.itemName':'الاسم: {value}',
    'privacy.itemSettings':'اللغة والمرشد والصوت والصف والمستوى',
    'privacy.itemProgress':'التقدم: {answered} سؤالًا، {correct} صحيحة، {cards} بطاقة',
    'privacy.itemPremium':'هل بريميوم مفعّل (يأتي ذلك من آب ستور)',
    'privacy.leaves':'ما يغادر الجهاز',
    'privacy.leavesBody':'الجملة التي يقرأها ميلو أو لونا فقط. تذهب إلى خادمنا ومنه إلى خدمة الصوت ElevenLabs. وهي دائمًا نص من اللعبة: سؤال أو جواب أو تلميح أو معلومة. لا اسم طفلك أبدًا ولا أي شيء يكتبه طفلك.',
    'privacy.none':'ما لا يفعله التطبيق',
    'privacy.noneBody':'لا إعلانات. لا تحليلات ولا متتبعات من جهات خارجية. لا حساب ولا بريد إلكتروني ولا كلمة مرور. لا موقع ولا جهات اتصال ولا كاميرا ولا ميكروفون. ولا ملفات تعريف ارتباط.',
    'privacy.keep':'الحفظ والمسح',
    'privacy.keepBody':'ما على هذا الجهاز يبقى حتى تمسحه؛ ولا نحتفظ بنسخة في أي مكان آخر. يحتفظ خادمنا بالصوت الذي أنشأه (جمل اللعبة، بلا بيانات شخصية) حتى لا تُصنع الجملة نفسها مرتين، ويحتفظ بعنوان IP للطلب في الذاكرة لوقت قصير لمنع إساءة الاستخدام.',
    'privacy.erase':'امسح كل البيانات',
    'privacy.eraseSub':'الاسم والإعدادات والتقدم على هذا الجهاز',
    'privacy.eraseTitle':'مسح كل شيء؟',
    'privacy.eraseBody':'الاسم والإعدادات والتقدم والبطاقات والأرقام تختفي من هذا الجهاز. بريميوم الذي اشتريته يبقى مع حساب آب ستور ويعود بـ«استعادة المشتريات».',
    'privacy.eraseConfirm':'نعم، امسح كل شيء',
    'privacy.contact':'أسئلة عن الخصوصية؟',
    'privacy.contactSub':'راسلنا على {email}',
    'privacy.noAccount':'كويزيلو يعمل بلا حساب: لا شيء عندنا لتسجّله أو تحذفه.',

    'score.points':'نقطة',
    'score.practice':'نقاط تدريب',
    'score.dayFull':'بلغت الحد اليومي',
    'score.title':'الأرقام القياسية',
    'score.sub':'أفضل نقاطك في كل فترة',
    'score.now':'الآن',
    'score.best':'الرقم القياسي',
    'score.run':'هذا التمرين',
    'score.day':'اليوم',
    'score.week':'هذا الأسبوع',
    'score.month':'هذا الشهر',
    'score.year':'هذه السنة',
    'score.allTime':'على الإطلاق',
    'score.todayPoints':'{n} من {max} نقطة اليوم',
    'score.todayCoins':'{n} من {max} عملة اليوم',
    'score.capNote':'هناك حد يومي للنقاط والعملات، والسؤال الذي أجبته صحيحًا من قبل يمنح نقاط تدريب. هكذا يبقى الرقم القياسي ذا قيمة.',

    'shop.tab':'🛒 المتجر',
    'shop.title':'المتجر',
    'shop.sub':'ادفع بعملات الألعاب',
    'shop.buy':'اشترِ',
    'shop.owned':'تملكه','shop.earned':'مُكتسَبة',
    'shop.price':'{n} عملة',
    'shop.need':'تنقصك {n} عملة',
    'shop.confirmTitle':'تشتري {item}؟',
    'shop.confirmBody':'يكلّف {n} عملة. بعدها يصبح {item} لك إلى الأبد.',
    'shop.bought':'{item} صار لك!',
    'shop.cards':'البطاقات الذهبية',
    'shop.mascots':'الأصدقاء',
    'shop.goldCard':'{world} الذهبي',
    'shop.goldCardSub':'بطاقة لامعة لمجموعتك',
    'shop.earnHint':'تكسب العملات في العدّاء وبقية الألعاب.',
    'shop.empty':'اشتريت كل شيء! المتجر فارغ تمامًا.',

    'result.worldLevelUp':'🎉 {world} ينتقل إلى المستوى {niveau}!',
    'result.worldMastered':'🏆 أكملت {world} في كل المستويات!',
    'result.goldCardEarned':'لقد كسبت البطاقة الذهبية لـ {world}!',
    'result.goldCardSpeech':'رائع! أنهيت {world} بالكامل. البطاقة الذهبية لك!',
    'settings.levelWorlds':'المستوى في كل عالم',
    'settings.levelWorldsSub':'يرتفع العالم من تلقاء نفسه عندما تنجح في مسابقاته الأربع.',
    'settings.levelMath':'مستوى اللعبة',
    'settings.timeLimitPerWorld':'الوقت لكل سؤال يتبع المستوى.',

    'settings.reset':'إعادة ضبط التقدم',
    'settings.resetSub':'ابدأ من جديد بصفحة بيضاء',
    'settings.resetTitle':'إعادة ضبط التقدم؟',
    'settings.resetBody':'نقاط الخبرة والعملات والبطاقات والأرقام والتقدم تعود كلها إلى البداية.',
    'settings.resetConfirm':'نعم، أعد الضبط',

    'gate.title':'سؤال سريع لشخص كبير',
    'gate.body':'كم يساوي {a} × {b}؟',
    'gate.placeholder':'الجواب',
    'gate.wrong':'هذا غير صحيح. حاول مرة أخرى.',
    'gate.continue':'متابعة',

    'sound.kicker':'الإعدادات',
    'sound.title':'🔊 الصوت والموسيقى',
    'sound.fx':'✨ المؤثرات الصوتية',
    'sound.music':'🎵 موسيقى الخلفية',
    'sound.test':'جرّب',
    'sound.pickMusic':'اختر موسيقاك',
    'sound.voiceGuide':'المرشد الصوتي',
    'track.home':'الجزر',
    'track.space':'الفضاء',
    'track.jungle':'الغابة',
    'track.earth':'الأرض',
    'track.history':'التاريخ',
    'track.science':'العلوم',
    'track.mystery':'الألغاز',
    'track.play':'الألعاب',

    'intro.skip':'تخطَّ المقدمة',
    'welcome.back.title':'مرحبًا {name}!',
    'welcome.back.sub':'جاهز للمتابعة؟',
    'welcome.back.continue':'تابع اللعب',
    'welcome.back.other':'شخص آخر يلعب',
    'welcome.back.where':'توقّفت هنا',
    'welcome.pick.title':'من يلعب؟',
    'welcome.pick.new':'لاعب جديد',
    'welcome.pick.back':'رجوع',
    'intro.tapToStart':'اضغط للبدء',
    'intro.tapForSound':'اضغط لتشغيل الصوت'
  };
})();
