(()=>{
  // German UI strings. Same keys and the same layout as every other language; the
  // child is addressed with "du" throughout, warm but never babyish.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.de={
    'lang.name':'Deutsch',
    'lang.speech':'de',

    'world.ruimte.title':'Weltraumwelt',
    'world.ruimte.sub':'Reise an Planeten, Sternen und Raketen vorbei',
    'world.dieren.title':'Tierwelt',
    'world.dieren.sub':'Entdecke Tiere an Land, im Dschungel und im Meer',
    'world.aarde.title':'Erdenwelt',
    'world.aarde.sub':'Erforsche Länder, Ozeane, Wetter und Karten',
    'world.geschiedenis.title':'Geschichtswelt',
    'world.geschiedenis.sub':'Steige ein in die Zeit von Pharaonen, Rittern und Entdeckern',
    'world.wetenschap.title':'Wissenschaftswelt',
    'world.wetenschap.sub':'Probiere aus und finde heraus, wie die Dinge funktionieren',
    'world.mysterie.title':'Geheimniswelt',
    'world.mysterie.sub':'Löse Rätsel und folge klugen Spuren',
    'world.kunst.title':'Kunstwelt',
    'world.kunst.sub':'Entdecke Gemälde, Musik und großartige Bauwerke',
    'world.sport.title':'Sportwelt',
    'world.sport.sub':'Lauf, spring und schwimm mit den besten Sportlern',

    'topic.zonnestelsel':'Sonnensystem',
    'topic.sterren_planeten':'Sterne & Planeten',
    'topic.astronauten':'Astronauten',
    'topic.raket_avontuur':'Raketenabenteuer',
    'topic.egyptenaren':'Ägypter',
    'topic.ridders_kastelen':'Ritter & Burgen',
    'topic.romeinen':'Römer',
    'topic.ontdekkingsreizigers':'Entdecker',
    'topic.slimme_proefjes':'Kluge Experimente',
    'topic.lichaam':'Der Körper',
    'topic.uitvindingen':'Erfindungen',
    'topic.natuur_energie':'Natur & Energie',
    'topic.raadsels':'Rätsel',
    'topic.verborgen_schatten':'Verborgene Schätze',
    'topic.natuurmysteries':'Naturgeheimnisse',
    'topic.speurtocht':'Die große Suche',
    'topic.snelle_dieren':'Schnelle Tiere',
    'topic.baby_dieren':'Tierbabys',
    'topic.waterdieren':'Tiere im Wasser',
    'topic.jungle':'Dschungelabenteuer',
    'topic.continenten_landen':'Länder & Kontinente',
    'topic.weer_klimaat':'Wetter & Klima',
    'topic.oceanen_natuur':'Ozeane & Natur',
    'topic.kaarten_navigatie':'Karten & Navigation',
    'topic.schilderkunst':'Malerei',
    'topic.muziek':'Musik',
    'topic.bouwkunst':'Baukunst',
    'topic.dans_theater':'Tanz & Theater',
    'topic.balsporten':'Ballsport',
    'topic.olympische_spelen':'Olympische Spiele',
    'topic.water_wintersport':'Wasser- & Wintersport',
    'topic.records_helden':'Rekorde & Helden',

    'nav.home':'Start',
    'nav.achievements':'Auszeichnungen',
    'nav.collection':'Sammlung',
    'nav.stats':'Statistik',
    'nav.more':'Mehr',
    'nav.aria':'Hauptnavigation',
    'nav.collectionLong':'Meine Sammlung',
    'nav.moreLong':'Mehr / Elternbereich',

    'common.back':'Zurück',
    'common.settings':'Einstellungen',
    'common.close':'Schließen',
    'common.cancel':'Abbrechen',
    'common.gotIt':'Verstanden',
    'common.brand':'KWIZILLO',
    'common.of':'von',
    // Was bin ich?
    'whoami.title':'Was bin ich?','whoami.round':'Runde {n} von {total}','whoami.points':'Jetzt {n} Punkte','whoami.ask':'Was bin ich?','whoami.more':'Ein Hinweis','whoami.next':'Weiter','whoami.timeUp':'Die Zeit ist um! Es war {answer}.',
    'whoami.speech.ask':'[playful] '+'Was bin ich?',   // spoken only: the voice asks it playfully, the tag is not read out
    'whoami.speech.askLuna':'[warmly] '+'Hmm... was bin ich?',   // Luna's own: the playful take sounded shrill in her voice (Stefan, 2026-10-10, take 3 of 3)
    'whoami.yes':'Ja, {answer}! +{points}','whoami.almost':'Fast! Es war {answer}.',
    'whoami.speech.yes':'Das ist {answer}','whoami.speech.almost':'Fast! Es war {answer}.',
    'whoami.doneKicker':'WAS BIN ICH?','whoami.doneTitle':'{n} von {total} erraten!','whoami.summary':'{score} von {max} Punkten. Je früher du rätst, desto mehr Punkte.',
    'whoami.speech.great':'Wow, du rätst schnell! Gut gemacht.','whoami.speech.done':'Schön gespielt! Nächstes Mal errätst du noch mehr.',
    'jungle.title':'Runner','jungle.tileSub':'Renne, springe und fliege durch drei Level','jungle.loadError':'Der Dschungel konnte nicht laden. Versuche es später noch einmal.',
    'fotozoom.title':'Fotozoom','fotozoom.round':'Runde {n} von {total}','fotozoom.points':'Jetzt {n} Punkte','fotozoom.ask':'Was ist das?','fotozoom.out':'Herauszoomen','fotozoom.next':'Weiter','fotozoom.timeUp':'Die Zeit ist um! Es war {answer}.',
    'fotozoom.speech.ask':'[playful] '+'Was ist das?',   // spoken only: the voice asks it playfully, the tag is not read out
    'fotozoom.yes':'Ja, {answer}! +{points}','fotozoom.almost':'Fast! Es war {answer}.',
    'fotozoom.speech.yes':'Das ist {answer}','fotozoom.speech.almost':'Fast! Es war {answer}.',
    'fotozoom.doneKicker':'FOTOZOOM','fotozoom.doneTitle':'{n} von {total} erkannt!','fotozoom.summary':'{score} von {max} Punkten. Je weniger du herauszoomst, desto mehr Punkte.',
    'fotozoom.speech.great':'Was für scharfe Augen! Gut gemacht.','fotozoom.speech.done':'Gut geschaut! Nächstes Mal erkennst du noch mehr.',
    'premium.teaser.fotozoom':'Fotozoom in dieser Welt gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alle Welten zu öffnen.',
    'jungle.brand':'KWIZILLO RUNNER','jungle.eyebrow':'KWIZILLO • ARCADE','jungle.titleA':'Kwizillo','jungle.titleB':'Runner','jungle.back':'Zurück zu Kwizillo','jungle.backShort':'Zurück','jungle.easyShort':'Leichte Fahrt',
    'jungle.levelLabel':'WÄHLE DEIN LEVEL','jungle.heroLabel':'WER LÄUFT MIT DIR?','jungle.heroBoy':'Junge','jungle.heroGirl':'Mädchen','jungle.glideOn':'Flieg!','jungle.glideOff':'Lauf!','jungle.levelJungle':'Dschungel','jungle.levelStad':'Stadt','jungle.levelLucht':'Himmel',
    'jungle.swingOn':'Schwing!','jungle.swingOff':'Lauf!','jungle.powerSpeed':'⚡ {n}s','jungle.popSpeed':'TURBO!','jungle.popSpeedSub':'7 Sekunden superschnell · doppelte Münzen','jungle.labelSpeed':'TURBO!',
    'jungle.canvasLabel':'Spielfeld. Pfeiltasten links und rechts zum Steuern. Leertaste zum Springen.','jungle.pause':'Pause','jungle.sound':'Ton an oder aus','jungle.controls':'Spielsteuerung','jungle.left':'Links','jungle.right':'Rechts','jungle.jump':'Springen ↑',
    'jungle.loading':'Dein Abenteuer wird vorbereitet…','jungle.loadErrorTitle':'Noch einmal','jungle.loadErrorBody':'Die Dschungelbilder konnten nicht laden. Prüfe deine Verbindung und versuche es erneut.',
    'jungle.intro':'Folge der goldenen Spur.<br>Springe, entdecke und sammle!','jungle.legendMagnet':'🧲 Magnet','jungle.legendShield':'🛡 Schild','jungle.legendGold':'★ Gold +5','jungle.legendDouble':'×2 Bonusstern',
    'jungle.easy':'Leichte Fahrt · springt von selbst','jungle.music':'Musik','jungle.on':'an','jungle.off':'aus','jungle.start':'Auf Abenteuer →',
    'jungle.help':'{n} Sekunden • Wische oder nimm die Knöpfe<br>10 Münzen hintereinander = +5 Bonus<br>Sammle Power-ups und finde eine Karte','jungle.countFollow':'Folge den Münzen!','jungle.countReady':'Bereit für das Abenteuer?',
    'jungle.pauseEyebrow':'ATME DURCH','jungle.pauseTitle':'Dein Dschungel<br>wartet.','jungle.pauseBody':'Die Zeit steht still.','jungle.resume':'Weiterspielen →','jungle.exit':'Ohne Belohnung verlassen',
    'jungle.hit':'Hoppla! Kurz gestoppt — lauf weiter.','jungle.hitLost':'Autsch! Zusammenstoß — {n} Münzen weg.','jungle.labelHit':'−{n}','jungle.lostCoins':'Münzen verloren','jungle.cardFound':'Du hast eine Dschungelkarte gefunden!','jungle.powerDouble':'×2 {n}s','jungle.powerMagnet':'🧲 {n}s','jungle.powerShield':'🛡 Geschützt','jungle.powerStreak':'★ {n} in Folge',
    'jungle.popDouble':'BONUSSTERN!','jungle.popDoubleSub':'6 Sekunden doppelte Münzen','jungle.popGold':'GOLD GEFUNDEN!','jungle.popGoldSub':'+{n} Münzen','jungle.popCombo':'{n} IN FOLGE!','jungle.popComboSub':'+5 Combo-Bonus','jungle.popMagnet':'MÜNZMAGNET!','jungle.popMagnetSub':'7 Sekunden Münzen anziehen',
    'jungle.popShield':'SCHILD!','jungle.popShieldSub':'Fängt einen Stoß für dich ab','jungle.popBlock':'DAS SCHILD HAT DICH GERETTET!','jungle.popBlockSub':'Lauf weiter','jungle.popCard':'KARTE GEFUNDEN!','jungle.popCardSub':'Wird am Ziel gezeigt','jungle.popClear':'GUTER SPRUNG!','jungle.popClearSub':'Über den Baumstamm','jungle.popDoubleflip':'DOPPELSALTO!','jungle.popDoubleflipSub':'+3 Münzen',
    'jungle.labelGold':'+{n} GOLD!','jungle.labelCombo':'COMBO +5','jungle.labelCard':'Karte gefunden!','jungle.labelClear':'Guter Sprung!','jungle.labelMagnet':'MAGNET!','jungle.labelShield':'SCHILD!','jungle.labelBlock':'Gerettet!','jungle.labelDouble':'DOPPELTE MÜNZEN!',
    'jungle.saving':'Deine Belohnung wird gespeichert…','jungle.saved':'Deine Münzen sind hinzugefügt.','jungle.saveError':'Das Speichern hat noch nicht geklappt. Versuche es erneut.',
    'jungle.finishEyebrow':'ABENTEUER GESCHAFFT','jungle.finish':'ZIEL!','jungle.finishSub':'Deine Beute aus diesem Lauf','jungle.coinsEarned':'Münzen verdient','jungle.bestStreak':'Beste Serie','jungle.bonusCoins':'Bonusmünzen',
    'jungle.cardAlt':'Gesammelte Karte','jungle.cardEyebrow':'KARTE GEFUNDEN','jungle.cardSub':'Für deine Kwizillo-Sammlung','jungle.cardTitle':'Dschungelblatt','card.jungle-leaf':'Dschungelblatt','card.city-star':'Stadtstern','card.sky-feather':'Himmelsfeder','jungle.retry':'Noch einmal speichern','jungle.take':'Beute mitnehmen','jungle.again':'Anderes Abenteuer','jungle.replay':'Nochmal spielen',
    // Premium
    'common.ok':'OK','common.retry':'Noch einmal',
    'premium.label':'Premium','premium.name':'Kwizillo Premium','premium.kicker':'FÜR ELTERN',
    'premium.title':'Öffne die ganze Welt von Kwizillo',
    'premium.subtitle':'Spielen, lernen, sammeln und entdecken ohne Grenzen.',
    'premium.benefit.worlds':'Alle Welten','premium.benefit.questions':'1280 Wissensfragen','premium.benefit.math':'Rechenspiele','premium.benefit.memo':'Memo-Spiele','premium.benefit.facts':'Wissenswertes','premium.benefit.guides':'Milo & Luna','premium.benefit.collect':'Karten und Maskottchen sammeln','premium.benefit.stats':'Vollständiger Fortschritt und Statistik','premium.benefit.new':'Neue Abenteuer und Inhalte',
    'premium.monthly':'Monatlich','premium.yearly':'Jährlich','premium.perMonth':'Monat','premium.perYear':'Jahr',
    'premium.best':'Bester Preis','premium.trial':'{days} Tage gratis testen','premium.ctaTrial':'{days} Tage gratis starten','premium.ctaYearly':'Jährlich wählen','premium.ctaMonthly':'Monatlich wählen',
    'premium.perMonthCalc':'Das sind {price} pro Monat',
    'premium.legal':'Das Abo wird über dein Apple-Konto abgerechnet und verlängert sich automatisch, bis es gekündigt wird. Du kannst es jederzeit in deinen Apple-Abos verwalten oder kündigen. Ein Gratiszeitraum wird zu einem bezahlten Abo, wenn du nicht vorher kündigst.',
    'premium.restore':'Käufe wiederherstellen','premium.restoreSub':'Premium auf diesem Gerät zurückholen','premium.manage':'Abo verwalten','premium.manageSub':'Über Apple kündigen oder ändern','premium.privacy':'Datenschutz','premium.terms':'Nutzungsbedingungen',
    'premium.loading':'Preise werden geladen…','premium.purchasing':'Einen Moment, Apple bearbeitet den Kauf…',
    'premium.pending':'Der Kauf wartet auf Bestätigung. Sobald sie da ist, schaltet Premium sich von selbst ein.',
    'premium.cancelled':'Kauf abgebrochen.','premium.failed':'Das hat nicht geklappt. Versuche es später noch einmal.',
    'premium.unavailable':'Premium ist gerade nicht verfügbar. Versuche es später noch einmal.',
    'premium.already':'Premium ist auf diesem Gerät aktiv.',
    'premium.restoring':'Käufe werden wiederhergestellt…','premium.restoreNone':'Kein früherer Kauf gefunden.','premium.manageUnavailable':'Verwalte Abos in den Einstellungen deines Telefons unter deinem Apple-Konto.',
    'premium.welcome':'Willkommen bei Kwizillo Premium!','premium.welcomeSub':'Alle Welten, Spiele und Fakten sind offen. Viel Spaß!','premium.continue':'Weiter, wo du warst','premium.play':'Spielen',
    'premium.statusFree':'Gratisversion · alles freischalten','premium.statusActive':'Aktiv · {type}','premium.statusTrial':'Gratiszeitraum · {type}','premium.statusExpired':'Abgelaufen · dein Fortschritt bleibt','premium.renews':'Verlängert sich am',
    'premium.teaserTitle':'Das ist Premium','premium.askParent':'Frag einen Erwachsenen',
    'premium.teaser.quiz':'Dieses Quiz gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alle Welten zu öffnen.',
    'premium.teaser.mega':'Das Mega-Quiz gehört zu Kwizillo Premium. Frag einen Erwachsenen, alle Welten freizuschalten.',
    'premium.teaser.memo':'Dieses Memo-Spiel gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alle Spiele zu öffnen.',
    'premium.teaser.math':'Die höheren Rechenlevel gehören zu Kwizillo Premium. Bitte einen Erwachsenen, sie zu öffnen.',
    'premium.teaser.facts':'Mehr Wissenswertes gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alles zu öffnen.',
    'premium.factsMore':'{n} weitere Fakten mit Premium',
    'premium.teaser.whoami':'Was bin ich? in dieser Welt gehört zu Kwizillo Premium. Bitte einen Erwachsenen, alle Welten zu öffnen.',
    'settings.terms':'Nutzungsbedingungen','settings.termsBody':'Kwizillo ist ein Lernspiel für Kinder. Premium ist ein Abo, das über Apple abgerechnet wird und sich automatisch verlängert, bis es gekündigt wird; du kannst es jederzeit in deinen Apple-Abos kündigen. Es gibt keine Werbung und keine Käufe im Spiel selbst.',

    'onboarding.language.title':'Wähle deine Sprache',
    'onboarding.language.sub':'In welcher Sprache möchtest du spielen?',
    'onboarding.name.title':'Wie heißt du?',
    'onboarding.name.sub':'Damit wir dich richtig begrüßen können.',
    'onboarding.name.placeholder':'Dein Name',
    'onboarding.name.hint':'Dein Name bleibt auf diesem Gerät.',
    'onboarding.voice.title':'Wer hilft dir?',
    'onboarding.voice.sub':'Wähle deinen Begleiter. Du kannst das jederzeit ändern.',
    'onboarding.welcome.title':'Willkommen, {name}!',
    'onboarding.welcome.sub':'Dein Abenteuer beginnt jetzt. Bereit zum Entdecken?',
    'onboarding.welcome.cta':'Abenteuer starten',
    'onboarding.next':'Weiter',
    'onboarding.speech.welcome':'Ja, alles ist bereit! Komm mit, ich zeige dir schnell, was wo ist.',
    'onboarding.speech.language':'Hallo! Ich bin Milo. Welche Sprache sprichst du?',
    'onboarding.speech.name':'Schön, dich zu treffen! Wie heißt du? Tippe es einfach ein.',
    'onboarding.speech.age':'Und wie alt bist du?',
    'onboarding.speech.group':'In welcher Klasse bist du?',
    'onboarding.speech.voice':'Wen möchtest du als Begleiter? Mich, Luna, oder lieber still?',
    'onboarding.age.title':'Wie alt bist du?',
    'onboarding.age.sub':'Tippe auf dein Alter.',
    'onboarding.age.years':'{n} Jahre',
    'onboarding.group.title':'In welcher Klasse bist du?',
    'onboarding.group.sub':'Damit ich Fragen wähle, die zu dir passen.',
    'tour.mega':'Ganz oben ist das Mega-Quiz: achtzig Fragen aus allen Welten, bunt gemischt!',
    'tour.worlds':'Das sind die acht Welten, vom Weltall und den Tieren bis zu Kunst und Sport. Gleich tippst du auf eine Welt und spielst ein Quiz!',
    'tour.games':'Und hier sind die Spiele: Runner, Sprachen, Rechnen, Was bin ich?, Fotozoom, Wissenswertes und Memo. Gleich kannst du sie alle ausprobieren!',
    'tour.facts':'Und das ist das Wissenswerte: Hunderte spannende Dinge zum Entdecken!',
    'tour.hud':'Oben stehen deine Stufe, deine Münzen und deine Tage in Folge. Das Zahnrad ist für deine Eltern.',
    'tour.nav':'Unten stehen deine Sammlung, deine Erfolge und deine Statistiken. Unter Mehr sind die Einstellungen.',
    'tour.done':'Jetzt bist du dran! Tippe, worauf du Lust hast. Viel Spaß, ich helfe dir, wenn du nicht weiterkommst.',
    'tour.skip':'Überspringen',
    'tour.again':'Rundgang mit {guide}',
    'tour.againSub':'{guide} zeigt dir noch einmal, was wo ist.',
    'tour.pick':'Rundgang',
    'tour.pickSub':'Wähle, wer dir zeigt, was wo ist.',
    'school.title':'Kwizillo in der Schule',
    'school.codeAsk':'Wie lautet der Code deiner Klasse?',
    'school.codeHint':'Er steht an der Tafel oder auf deiner Karte.',
    'school.next':'Weiter',
    'school.codeWrong':'Diesen Klassencode kennen wir nicht. Schau noch einmal nach.',
    'school.whoAmI':'Wer bist du?',
    'school.pictures':'Tippe deine drei Bilder an',
    'school.picturesHint':'In der richtigen Reihenfolge, wie auf deiner Karte.',
    'school.picturesWrong':'Das sind nicht deine Bilder. Versuch es noch einmal.',
    'school.locked':'Warte kurz und versuch es dann noch einmal.',
    'school.offline':'Keine Verbindung. Versuch es noch einmal.',
    'school.back':'Zurück',
    'school.logout':'Abmelden',
    'school.logoutSub':'Fertig gespielt? Melde dich ab, dann kann der Nächste spielen.',
    'school.signedIn':'{name} · {class}',
    'players.title':'Spieler auf diesem Gerät',
    'players.sub':'Wer auf diesem Gerät spielt.',
    'settings.feedback':'Ideen und Feedback',
    'settings.feedbackSub':'Hilf uns, Kwizillo noch besser zu machen',
    'feedback.title':'Erzähl es uns!',
    'feedback.lead':'Hast du eine Idee, stimmt etwas nicht, oder magst du etwas ganz besonders? Wir lesen alles.',
    'feedback.kind.idea':'Idee',
    'feedback.kind.bug':'Anmerkung',
    'feedback.kind.love':'Lob',
    'feedback.placeholder':'Schreib hier deine Nachricht…',
    'feedback.empty':'Schreib zuerst deine Nachricht.',
    'feedback.send':'Senden',
    'feedback.note':'Ein Elternteil schickt die Nachricht per E-Mail. Dein Name wird nicht mitgeschickt.',
    'feedback.thanksTitle':'Vielen Dank!',
    'feedback.thanks':'Wir lesen deine Nachricht und machen Kwizillo damit zusammen mit dir noch besser.',
    'players.current':'spielt gerade',
    'players.delete':'Löschen',
    'players.deleteTitle':'{name} löschen?',
    'players.deleteBody':'Alles von {name} wird von diesem Gerät entfernt. Das lässt sich nicht rückgängig machen.',
    'players.deleteCard':'Spieler löschen',
    'players.deleteCardSub':'Einen Spieler und alles, was er gespielt hat, von diesem Gerät entfernen',
    'players.deletePick':'Welchen Spieler möchtest du löschen?',
    'settings.logout':'Abmelden',
    'settings.logoutSub':'Einen anderen Spieler wählen oder einen neuen beginnen.',

    'voice.milo':'Milo',
    'voice.milo.desc':'Fröhlich & munter',
    'voice.luna':'Luna',
    'voice.luna.desc':'Ruhig & freundlich',
    'voice.silent':'Still',
    'voice.silent.desc':'Keine Stimme',
    'voice.milo.hello':'Hallo! Ich bin Milo. Bereit zum Spielen?',
    'voice.luna.hello':'Hallo! Ich bin Luna. Wollen wir zusammen entdecken?',

    'home.greeting':'Hallo {name}!',
    'home.greetingAnon':'Hallo!',
    'home.level':'Level {level}',
    'home.coins':'KwizCoins',
    'home.streak':'Tage in Folge',
    'home.pickWorld':'Wähle deine Welt',
    'home.cta':'Abenteuer starten',
    'home.ctaSub':'Weiter in {world}',
    'home.voiceLabel':'Stimme',
    'home.languageLabel':'Sprache',

    'world.kicker':'KWIZILLO-WELT',
    'world.backHome':'Zurück zum Start',
    'world.mix':'Gemischtes Quiz starten',
    'world.mixSub':'Fragen aus allen vier Themen',
    'world.quizNumber':'Quiz {n}',
    'world.topicPassed':'Geschafft',
    'world.topicPlayed':'Quiz {n} gespielt · {correct}/{answered} richtig',
    'world.progressLine':'{passed} von {total} Themen geschafft',
    'world.worldProgress':'{done} von {total} Quiz dieser Welt geschafft',
    'world.mixDone':'{n} gespielt',

    'quiz.mixed':'Gemischtes Quiz',
    'mega.title':'Mega-Quiz',
    'talen.title':'Sprachen',
    'collection.tabWords':'🗣️ Wörter',
    'collection.wordsEmpty':'Noch keine Wörter',
    'collection.wordsEmptyBody':'Spiel eine Lektion in Sprachen. Jedes gelernte Wort erscheint hier.',
    'collection.wordsCount':'{n} Wörter auf {lang}. Tippe, um sie zu hören.',
    'stats.talenLine':'{words} Wörter gelernt · {lessons} Lektionen',
    'achievement.talenFirst':'Erste Lektion in Sprachen',
    'achievement.talen10':'10 Wörter gelernt',
    'talen.passport':'Sprachpass',
    'talen.passportSub':'Lerne {lang} mit Milo',
    'talen.passportSubLuna':'Lerne {lang} mit Luna',
    'talen.pickTitle':'Welche Sprache möchtest du lernen?',
    'talen.pickSub':'Tippe auf eine Flagge und hör, wie man Hallo sagt.',
    'talen.pickGo':'Lerne {lang}!',
    'talen.switchLang':'Andere Sprache',
    'talen.lang.en':'Englisch',
    'talen.lang.nl':'Niederländisch',
    'talen.lang.de':'Deutsch',
    'talen.lang.fr':'Französisch',
    'talen.lang.es':'Spanisch',
    'talen.lang.it':'Italienisch',
    'talen.lang.pt':'Portugiesisch',
    'talen.lang.da':'Dänisch',
    'talen.lang.ru':'Russisch',
    'talen.lang.ar':'Arabisch',
    'talen.soon':'bald',
    'talen.soonLang':'Bald auch in deiner Sprache',
    'talen.msgNew':'Jede Lektion gibt einen Stempel. Fang mit den Tieren an!',
    'talen.msgPlayed':'Super! Dein Stempel ist drin. Spiel noch einmal für mehr Sterne.',
    'talen.start':'Lektion starten',
    'talen.again':'{theme} noch einmal spielen',
    'talen.review':'Kurz wiederholen',
    'talen.reviewSub':'{n} Wörter sind dran',
    'talen.reviewDone':'Gut wiederholt!',
    'talen.replay':'Noch einmal',
    'talen.listen':'Hör dir das Wort an',
    'talen.picture':'Bild',
    'talen.means':'heißt {word}',
    'talen.round':'Runde {n} von {total}',
    'talen.firstTry':'gleich richtig',
    'talen.learned':'Diese Wörter hast du gelernt. Tippe, um sie zu hören.',
    'talen.theme.dieren':'Tiere',
    'talen.theme.kleuren':'Farben',
    'talen.theme.eten':'Essen und Trinken',
    'talen.theme.getallen':'Zahlen',
    'talen.theme.lichaam':'Körper',
    'talen.theme.vervoer':'Fahrzeuge',
    'talen.theme.sport':'Sport',
    'talen.theme.praten':'Sprechen',
    'talen.section.words':'Wörter',
    'talen.section.sentences':'Sätze',
    'talen.section.conversations':'Gespräche',
    'talen.section.conversationsSub':'Hör zu und verstehe',
    'talen.section.speaking':'Sprechen',
    'talen.section.speakingSub':'Hör zu und sprich',
    'talen.conv.cat.intro':'Kennenlernen',
    'talen.conv.cat.school':'Schule',
    'talen.conv.cat.food':'Essen & Trinken',
    'talen.conv.cat.family':'Familie & Freunde',
    'talen.conv.cat.shop':'Einkaufen',
    'talen.conv.cat.travel':'Unterwegs',
    'talen.conv.listenAgain':'Noch mal hören',
    'talen.conv.listen':'Hör gut zu…',
    'talen.conv.round':'Gespräch {n} von {total}',
    'talen.conv.done':'Du verstehst es schon!',
    'talen.speaking.set.basics':'Erste Wörter',
    'talen.speaking.set.greetings':'Begrüßungen',
    'talen.speaking.set.sentences':'Sätze',
    'talen.speaking.set.questions':'Fragen stellen',
    'talen.speaking.permissionTitle':'Sprechen mit dem Mikrofon',
    'talen.speaking.permissionBody':'Für Sprechen nutzt Kwizillo dein Mikrofon. Wir hören nur zu, während du übst. Deine Stimme wird nicht gespeichert.',
    'talen.speaking.enableMic':'Mikrofon einschalten',
    'talen.speaking.sayIt':'Sprich es nach',
    'talen.speaking.tapMic':'Tippe aufs Mikrofon und sag es',
    'talen.speaking.listening':'Ich höre zu…',
    'talen.speaking.micActive':'Das Mikrofon ist an',
    'talen.speaking.goodPractice':'Gut geübt!',
    'talen.speaking.notHeard':'Ich habe dich noch nicht gehört. Versuch es noch mal!',
    'talen.speaking.tryAgain':'Noch mal',
    'talen.speaking.next':'Weiter',
    'talen.speaking.micOff':'Das Mikrofon ist aus.',
    'talen.speaking.micOffBody':'Du kannst auch ohne Mikrofon üben: hör zu und sag es laut.',
    'talen.speaking.retry':'Erneut versuchen',
    'talen.speaking.withoutMic':'Ohne Mikrofon üben',
    'talen.speaking.iSaidIt':'Ich habe es gesagt',
    'talen.speaking.done':'Gut geübt, super gemacht!',
    'talen.speaking.round':'Wort {n} von {total}',
    'talen.speaking.correct':'Richtig gesagt!',
    'talen.speaking.saidAloud':'Du hast es laut gesagt!',
    'talen.speaking.almost':'Fast!',
    'talen.speaking.heardAs':'Ich habe gehört: „{text}“. Hör zu und versuch es noch mal.',
    'talen.speakHead':'Ich spreche',
    'talen.catThemes':"{n} Themen",
    'talen.theme.huis':'Zuhause',
    'talen.theme.natuur':'Natur',
    'talen.theme.familie':'Familie',
    'talen.theme.kleding':'Kleidung',
    'talen.theme.school':'Schule',
    'talen.theme.vakantie':'Urlaub',
    'talen.theme.mij':'Über mich',
    'talen.theme.vragen':'Fragen',
    'talen.theme.gevoel':'Gefühle',
    'talen.theme.samen':'Zusammen spielen',
    'talen.theme.mix':'Mix',
    'talen.done.dieren':'Du kennst die Tiere!',
    'talen.done.kleuren':'Du kennst die Farben!',
    'talen.done.eten':'Du kennst Essen und Trinken!',
    'talen.done.getallen':'Du kannst zählen!',
    'talen.done.lichaam':'Du kennst deinen Körper!',
    'talen.done.vervoer':'Du kennst die Fahrzeuge!',
    'talen.done.sport':'Du kennst den Sport!',
    'talen.done.praten':'Du kannst sprechen!',
    'talen.done.huis':'Du kennst das ganze Haus!',
    'talen.done.natuur':'Du kennst die Natur!',
    'talen.done.familie':'Du kennst die Familie!',
    'talen.done.kleding':'Du kennst alle Kleider!',
    'talen.done.school':'Du kennst deine Schulsachen!',
    'talen.done.vakantie':'Bereit für den Urlaub!',
    'talen.done.mij':'Du erzählst von dir!',
    'talen.done.vragen':'Du kannst Fragen stellen!',
    'talen.done.gevoel':'Du sagst, wie du dich fühlst!',
    'talen.done.samen':'Ihr könnt zusammen spielen!',
    'talen.done.mix':'Alles gemischt, und du kannst es!',
    'jungle.bannerSub':'Renn, spring und sammle Münzen',
    'settings.learnLang':'Lernsprache',
    'settings.learnLangSub':'Die Sprache, die dein Kind in Sprachen lernt',
    'premium.teaser.talen':'Dieses Thema gehört zu Kwizillo Premium. Die Tiere sind gratis. Frag einen Erwachsenen, alle Themen freizuschalten.',
    'mega.sub':'{n} Fragen aus allen Welten',
    'mega.rule':'Fragen aus allen {worlds} Welten: Du hattest {score} von {total} richtig.',
    'mega.again':'Noch ein Mega-Quiz',
    'mega.collectionLine':'{played}-mal gespielt · beste {best} von {total}',
    'quiz.progress':'Frage {current} von {total}',
    'quiz.hint':'Hinweis',
    'quiz.none':'Für dieses Thema gibt es noch keine Fragen.',
    'quiz.artAlt':'Bild zur Frage',
    'quiz.quizLabel':'Quiz {n}',
    'quiz.back':'Zurück',
    'quiz.explain':'Erklären',
    'quiz.timerAria':'Sekunden übrig',
    'feedback.timeKicker':'ZEIT IST UM!',
    'feedback.timeTitle':'Nächstes Mal schneller!',
    'settings.level':'Level',
    'settings.levelSub':'{seconds} s pro Frage · max. {allowed} Fehler · {hints}',
    'settings.hintsFree':'Hinweise frei',
    'settings.hintsN':'{n} Hinweise',
    'settings.hintsNone':'keine Hinweise',
    'settings.readsQuestionOnly':'nur die Frage wird vorgelesen',
    'quiz.hintsSpent':'In diesem Quiz gibt es keine Hinweise mehr.',
    'quiz.noHints':'Level 6 hat keine Hinweise.',
    'world.speech.enter':'[excited] {title}!',
    'settings.levelAuto':'Auto',
    'settings.share':'Teile dein Ergebnis',
    'settings.shareSub':'Schicke dein Ergebnis an Familie oder Freunde',

    'hint.title':'Ein kleiner Hinweis',
    'hint.kicker':'Tipp zu {topic}',
    'hint.ok':'Weiter überlegen',
    'hint.close':'Hinweis schließen',
    'hint.fallback':'Schau dir die Frage und das Bild noch einmal genau an.',
    'hint.alt':'Bildhinweis',

    'feedback.goodKicker':'RICHTIG!',
    'feedback.tryKicker':'SO KNAPP!',
    'feedback.goodTitle':'Schön gespielt!',
    'feedback.tryTitle':'Gut überlegt!',
    'feedback.correctIs':'Die richtige Antwort ist <strong>{answer}</strong>.',
    'feedback.thatsRight':'Das ist richtig!',
    'feedback.didYouKnow':'Wusstest du das?',
    'feedback.next':'Nächste Frage',
    'feedback.seeResult':'Ergebnis ansehen',
    'feedback.speech.good':'Gut gemacht.',
    'feedback.speech.good.1':'Gut gemacht!',
    'feedback.speech.good.2':'Klasse, das ist richtig!',
    'feedback.speech.good.3':'Genau getroffen!',
    'feedback.speech.good.4':'Sehr schön!',
    'feedback.speech.good.5':'Ja! Genau!',
    'feedback.speech.good.6':'Super, gut geschaut!',
    'feedback.speech.good.7':'Fantastisch!',
    'feedback.speech.good.8':'Wow, das stimmt!',
    'feedback.speech.good.9':'Ja, gut so!',
    'feedback.speech.good.10':'Top!',
    'feedback.speech.good.11':'Perfekt!',
    'feedback.speech.good.12':'Sehr gut, weiter so!',
    'feedback.speech.good.13':'Klasse gemacht!',
    'feedback.speech.good.14':'Gut so!',
    'feedback.speech.good.15':'Völlig richtig!',
    'feedback.speech.good.16':'Volltreffer!',
    'feedback.speech.good.17':'Mega!',
    'feedback.speech.good.18':'Krass gut!',
    'feedback.speech.good.19':'Voll gut!',
    'feedback.speech.good.20':'Cool!',
    'feedback.speech.good.21':'Stark!',
    'feedback.speech.good.22':'Hammer!',
    'feedback.speech.good.23':'Läuft bei dir!',
    'feedback.speech.good.24':'Echt super!',
    'feedback.speech.good.25':'Bombe!',
    'feedback.speech.good.26':'Spitze!',
    'feedback.speech.good.27':'Genial!',
    'feedback.speech.good.28':'Treffer!',
    'feedback.speech.good.29':'Weltklasse!',
    'feedback.speech.good.30':'Richtig stark!',
    'feedback.speech.try.1':'Fast. Die richtige Antwort ist {answer}.',
    'feedback.speech.try.2':'Nicht ganz. Die richtige Antwort ist {answer}.',
    'feedback.speech.try.3':'Guter Versuch! Die richtige Antwort ist {answer}.',
    'feedback.speech.try.4':'Hoppla, so knapp. Die richtige Antwort ist {answer}.',
    'feedback.speech.try.5':'Knapp daneben. Die richtige Antwort ist {answer}.',
    'feedback.speech.try.6':'Oh, das war knifflig! Die richtige Antwort ist {answer}.',
    'feedback.speech.try.7':'Oh, knapp! Die richtige Antwort ist {answer}.',
    'feedback.speech.try.8':'Hmm, nicht ganz. Die richtige Antwort ist {answer}.',
    'feedback.speech.try.9':'Macht nichts! Die richtige Antwort ist {answer}.',
    'feedback.speech.try.10':'Nächstes Mal klappt’s! Die richtige Antwort ist {answer}.',
    'feedback.speech.try.11':'Die war knifflig! Die richtige Antwort ist {answer}.',
    'feedback.speech.try.12':'Fast getroffen! Die richtige Antwort ist {answer}.',
    'feedback.answerLabel':'Die richtige Antwort',
    'feedback.close':'Schließen',
    'feedback.listening':'Hört zu…',
    'quiz.repeat':'Noch einmal',
    'quiz.repeatAria':'Frage noch einmal vorlesen',
    'feedback.speech.try':'Fast. Die richtige Antwort ist {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'QUIZ GESCHAFFT',
    'result.title':'{score} von {total} richtig!',
    'result.score':'Punkte',
    'result.xp':'XP',
    'result.coins':'Münzen',
    'result.again':'Noch ein Quiz',
    'result.againNumbered':'Quiz {n} starten',
    'result.nextTopic':'Weiter: {topic}',
    'result.finishWorld':'Gemischtes Quiz starten',
    'result.retryTopic':'Dieses Thema noch einmal',
    'result.retryNow':'Noch einmal',
    'memo.title':'Memo',
    'memo.pickTitle':'Wähle deine Welt',
    'game.mixAll':'Mix aus allen Welten',
    'game.pickSub':'Wähle eine Welt oder spiele alle gemischt.',
    'memo.pickSub':'Finde die Paare · Level {n}',
    'memo.otherWorld':'Andere Welt',
    'memo.sub':'Finde die Paare',
    'memo.play':'Memo spielen',
    'memo.playSub':'Finde die Paare von {world}',
    'memo.level':'Level {n}',
    'memo.pairs':'{found} von {total} Paaren',
    'memo.boostTitle':'Goldener Boost!','memo.boostSub':'3 Paare hintereinander · +{xp} Punkte',
    'memo.moves':'{n} Züge',
    'memo.movesShort':'Züge',
    'memo.card':'Memo-Karte',
    'memo.hintLine':'Drehe zwei Karten um und finde die Paare',
    'memo.none':'Für diese Welt gibt es noch nicht genug Karten.',
    'memo.doneKicker':'MEMO GESCHAFFT!',
    'memo.doneTitle':'Alle Paare gefunden!',
    'memo.timeKicker':'ZEIT IST UM!',
    'memo.timeTitle':'Fast alle Paare!',
    'memo.summary':'{pairs} Paare in {moves} Zügen und {secs} Sekunden.',
    'memo.summaryTime':'{found} von {pairs} Paaren gefunden. Versuche es noch einmal!',
    'memo.again':'Noch einmal',
    'memo.retry':'Noch einmal',
    'memo.toWorld':'Zurück zur Welt',
    'memo.speech.done':'Wow, du hast alle Paare gefunden! Was für ein Gedächtnis!',
    'memo.speech.time':'Die Zeit ist um. Nächstes Mal schaffst du alle!',
    'memo.modeTitle':'Wie spielst du?',
    'memo.solo':'Allein','memo.soloSub':'Gegen die Uhr',
    'memo.duel':'Gegeneinander','memo.duelSub':'Abwechselnd, wer findet die meisten Paare?',
    'memo.player1':'Spieler 1','memo.player2':'Spieler 2','memo.p2Label':'Wer spielt mit?',
    'memo.turn':'{name} ist dran',
    'memo.duelKicker':'MEMO-DUELL',
    'memo.duelWin':'{name} gewinnt!','memo.duelTie':'Unentschieden!',
    'memo.duelSummary':'{pairs} Paare in {moves} Zügen.',
    'memo.rematch':'Revanche',
    'memo.speech.win':'Wir haben einen Gewinner! Schön gespielt, ihr beiden!',
    'memo.speech.tie':'Unentschieden! Ihr könnt euch beide gut erinnern!',
    'home.playMore':'Mehr spielen',
    'math.title':'Rechnen',
    'facts.title':'Wissenswertes',
    'world.ruimte.short':'Weltraum','world.dieren.short':'Tiere','world.aarde.short':'Erde','world.geschiedenis.short':'Geschichte','world.wetenschap.short':'Wissenschaft','world.kunst.short':'Kunst','world.sport.short':'Sport','world.mysterie.short':'Geheimnis',
    'facts.tileSub':'Wusstest du…',
    'facts.sub':'{seen} von {total} entdeckt',
    'facts.next':'Nächstes Wissen',
    'facts.listen':'Vorlesen',
    'facts.kicker':'Wusstest du…',
    'facts.new':'Neu!',
    'facts.allSeen':'Du hast alles entdeckt! Jetzt kommt es noch einmal.',
    'facts.more':'Mehr Wissen',
    'math.sub':'Schnelle Aufgaben',
    'math.play':'Rechnen',
    'math.playSub':'Zehn Aufgaben · Level {n}',
    'math.progress':'Aufgabe {current} von {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'{score} von {total} Aufgaben richtig!',
    'math.again':'Zehn neue Aufgaben',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'plus',
    'math.op.minus':'minus',
    'math.op.times':'mal',
    'math.op.divided':'geteilt durch',
    'math.op.equals':'ist',
    'math.speech.twoStep':'{c} plus {a} mal {b}',
    'math.speech.half':'Die Hälfte von {n}',
    'math.speech.quarter':'Ein Viertel von {n}',
    'math.speech.percent':'{p} Prozent von {n}',
    'math.money.title':'Geld zählen',
    'chest.title':'Spielekiste',
    'chest.sub':'Wähle ein Spiel',
    'measure.title':'Messen & Wiegen',
    'measure.sub':'Messen und vergleichen',
    'measure.tip':'Miss genau! Schau, wo es anfängt und wo es aufhört.',
    'measure.try':'Fast! Schau noch einmal genau hin.',
    'measure.len.pencil':'Wie lang ist der Bleistift?',
    'measure.len.crayon':'Wie lang ist die Wachsmalkreide?',
    'measure.len.straw':'Wie lang ist der Strohhalm?',
    'measure.len.brush':'Wie lang ist der Pinsel?',
    'measure.len.ribbon':'Wie lang ist das Band?',
    'measure.len.nail':'Wie lang ist der Nagel?',
    'measure.wt.apple':'Wie schwer ist der Apfel?',
    'measure.wt.cheese':'Wie schwer ist das Stück Käse?',
    'measure.wt.melon':'Wie schwer ist die Melone?',
    'measure.wt.pumpkin':'Wie schwer ist der Kürbis?',
    'measure.wt.book':'Wie schwer ist das Buch?',
    'measure.wt.potatoes':'Wie schwer ist der Sack Kartoffeln?',
    'measure.wt.cat':'Wie schwer ist die Katze?',
    'measure.vol.read':'Wie viel Wasser ist im Messbecher?',
    'measure.vol.more':'Wie viel fehlt noch bis 1 Liter?',
    'measure.cmp.longer':'Was ist länger?',
    'measure.cmp.shorter':'Was ist kürzer?',
    'measure.cmp.heavier':'Was ist schwerer?',
    'measure.cmp.lighter':'Was ist leichter?',
    'measure.cmp.more':'Wo ist mehr drin?',
    'measure.cmp.less':'Wo ist weniger drin?',
    'measure.est.shoe':'Wie lang ist ein Schuh ungefähr?',
    'measure.est.door':'Wie hoch ist eine Tür ungefähr?',
    'measure.est.apple':'Wie schwer ist ein Apfel ungefähr?',
    'measure.est.bag':'Wie schwer ist ein Schulranzen ungefähr?',
    'measure.est.glass':'Wie viel passt ungefähr in ein Glas?',
    'measure.est.bath':'Wie viel Wasser passt ungefähr in eine Badewanne?',
    'measure.est.car':'Wie lang ist ein Auto ungefähr?',
    'measure.est.elephant':'Wie schwer ist ein Elefant ungefähr?',
    'measure.est.bucket':'Wie viel passt ungefähr in einen Eimer?',
    'measure.est.pencil':'Wie lang ist ein Bleistift ungefähr?',
    'measure.convert':'Rechne um!',
    'measure.story':'Lies genau und rechne!',
    'measure.story.bottle':'Eine Flasche enthält {a} Liter. Du füllst {n} Gläser mit je {b} ml. Wie viele ml bleiben übrig?',
    'measure.story.ribbon':'Ein Band ist {a} Meter lang. Du schneidest {n} Stücke von {b} cm ab. Wie viele cm bleiben übrig?',
    'measure.story.flour':'Eine Tüte Mehl wiegt {a} kg. Du nimmst {n}-mal {b} Gramm heraus. Wie viele Gramm bleiben übrig?',
    'measure.story.map':'Auf der Karte ist 1 cm in echt {s} km. Die Straße ist auf der Karte {d} cm lang. Wie viele km ist die Straße wirklich?',
    'measure.obj.pencil':'Bleistift',
    'measure.obj.crayon':'Wachsmalkreide',
    'measure.obj.straw':'Strohhalm',
    'measure.obj.brush':'Pinsel',
    'measure.obj.ribbon':'Band',
    'measure.obj.nail':'Nagel',
    'measure.obj.apple':'Apfel',
    'measure.obj.cheese':'Käse',
    'measure.obj.melon':'Melone',
    'measure.obj.pumpkin':'Kürbis',
    'measure.obj.book':'Buch',
    'measure.obj.potatoes':'Kartoffeln',
    'measure.obj.cat':'Katze',
    'measure.obj.elephant':'Elefant',
    'measure.obj.mouse':'Maus',
    'measure.obj.cow':'Kuh',
    'measure.obj.chicken':'Huhn',
    'measure.obj.strawberry':'Erdbeere',
    'measure.obj.feather':'Feder',
    'measure.obj.glassRed':'rotes Glas',
    'measure.obj.glassBlue':'blaues Glas',
    'measure.obj.package':'Paket',
    'measure.obj.schoolbag':'Schulranzen',
    'measure.obj.rope':'Seil',
    'measure.obj.bottle':'Flasche',
    'measure.obj.carton':'Saftpackung',
    'measure.u.mm':'mm',
    'measure.u.cm':'cm',
    'measure.u.m':'m',
    'measure.u.km':'km',
    'measure.u.g':'g',
    'measure.u.kg':'kg',
    'measure.u.ml':'ml',
    'measure.u.cl':'cl',
    'measure.u.l':'l',
    'math.pick.sub':'Was möchtest du üben?',
    'math.pick.sums':'Rechnen',
    'math.money.sub':'Zähl die Münzen',
    'math.money.ok':'Fertig!',
    'math.money.delete':'Löschen',
    'math.money.ask':'Wie viel ist das zusammen?',
    'math.money.main.one':'{n} Euro',
    'math.money.main.few':'{n} Euro',
    'math.money.main.many':'{n} Euro',
    'math.money.sub.one':'{n} Cent',
    'math.money.sub.few':'{n} Cent',
    'math.money.sub.many':'{n} Cent',
    'math.money.and':'und',
    'math.speech.wrong':'Fast. Es ist {answer}.',
    'math.speech.done':'Toll gerechnet! Alle Aufgaben geschafft.',
    'math.speech.fail':'Guter Versuch. Noch einmal und du hast es!',
    'math.hint.plus':'Zähle von {a} weiter: {b} dazu.',
    'math.hint.minus':'Beginne bei {a} und zähle {b} zurück.',
    'math.hint.times':'{a} mal {b}: addiere {b} genau {a} mal.',
    'math.hint.divided':'Wie oft passt {b} in {a}?',
    'math.hint.generic':'Rechne Schritt für Schritt.',
    'achievement.math3':'3 Rechenrunden geschafft',
    'stats.mathLine':'{played} Runden gespielt · {won} geschafft',
    'result.passKicker':'GESCHAFFT!',
    'result.failKicker':'NOCH NICHT',
    'result.passRule':'Level {niveau}: du durftest {allowed} Fehler machen und hattest {wrong}.',
    'result.failRule':'Level {niveau}: du darfst {allowed} Fehler machen, du hattest {wrong}. Spiele dieses Thema noch einmal!',
    'result.toHome':'Zum Start',

    'profile.title':'Mein Profil',
    'profile.sub':'Dein Name, dein Kumpel und deine Einstellungen',
    'profile.saveName':'Namen speichern',
    'profile.saved':'Gespeichert!',
    'profile.buddy':'Mein Kumpel',
    'profile.chooseBuddy':'Kumpel wählen',
    'profile.voice':'Wer liest vor?',
    'achievements.title':'Auszeichnungen',
    'achievements.sub':'Deine Abenteuer und Meilensteine',
    'achievements.summary':'{done}/{total} verdient',
    'achievements.summarySub':'Entdecke weiter und schalte neue Auszeichnungen frei.',
    'achievements.done':'Verdient!',
    'achievement.firstQuiz':'Erstes Quiz',
    'achievement.correct10':'10 richtige Antworten',
    'achievement.correct50':'50 richtige Antworten',
    'achievement.streak7':'7 Tage in Folge',
    'achievement.cards5':'5 Wissenskarten',
    'achievement.allWorlds':'Alle Welten besucht',
    'achievement.memo3':'3 Memo-Spiele gewonnen',

    'collection.title':'Meine Sammlung',
    'collection.sub':'Alles, was du entdeckt hast',
    'collection.tabWorlds':'🌍 Welten',
    'collection.tabCards':'🃏 Karten',
    'collection.tabMascots':'🐾 Kumpel',
    'collection.worldStat':'{correct}/{answered} richtig · {pct}%',
    'progress.worldLine':'{passed} von {total} Quiz geschafft · {points} Punkte',
    'progress.overall':'Insgesamt {points} von {max} Punkten',
    'progress.overallSub':'Jedes geschaffte Quiz ist 25 Punkte wert: eine ganze Welt sind 100.',
    'collection.discovered':'★ Entdeckt',
    'collection.unlockKicker':'NEUER BUDDY!',
    'collection.unlockLine':'Freigespielt mit {n} richtigen Antworten.',
    'score.coinsAdded':'+{n} Münzen gutgeschrieben',
    'score.coinsCapped':'Tagesmaximum erreicht: {n} von deinen {got} Münzen wurden gutgeschrieben.','collection.cardAdded':'{title} ist jetzt in deiner Sammlung!',
    'collection.emptyTitle':'Noch keine Karten',
    'collection.emptyBody':'Beantworte Fragen richtig, um Wissenskarten zu sammeln.',
    'collection.mascotLocked':'noch {n} richtige Antworten',
    'collection.mascotShop':'Im Laden: {n} Münzen',
    'collection.mascotActive':'Aktiv ✓',
    'collection.mascotChoose':'Kumpel wählen',
    'collection.mascotCount':'{unlocked}/{total} Kumpel freigeschaltet',

    'mascot.milo':'Milo',
    'mascot.milo.desc':'Dein kluger Roboterkumpel',
    'mascot.comet':'Komet',
    'mascot.comet.desc':'Weltraumkumpel',
    'mascot.pootje':'Pfötchen',
    'mascot.pootje.desc':'Tierfreund',
    'mascot.terra':'Terra',
    'mascot.terra.desc':'Beschützerin der Erde',
    'mascot.sparky':'Sparky',
    'mascot.sparky.desc':'Experimentierfan',
    'mascot.lumi':'Lumi',
    'mascot.lumi.desc':'Geheimnissucherin',
    'mascot.nova':'Nova','mascot.nova.desc':'Sternenreisende',
    'mascot.kiko':'Kiko','mascot.kiko.desc':'Dschungelforscher',
    'mascot.pip':'Pip','mascot.pip.desc':'Eiskalter Draufgänger',
    'mascot.ravi':'Ravi','mascot.ravi.desc':'Erfinder in Ausbildung',
    'mascot.flora':'Flora','mascot.flora.desc':'Freundin der Natur',
    'mascot.draco':'Draco','mascot.draco.desc':'Kleiner Burgdrache',
    'mascot.mike':'Mike','mascot.mike.desc':'Musikfan mit Kopfhörern',
    'mascot.zibo':'Zibo','mascot.zibo.desc':'Fröhlicher Weltraumreisender',
    'mascot.leo':'Leo','mascot.leo.desc':'Sportlicher Löwe mit Medaille',
    'mascot.pixi':'Pixi','mascot.pixi.desc':'Kreativer Fuchs mit Pinsel',
    'mascot.olli':'Olli','mascot.olli.desc':'Kluge Eule mit Fliegerbrille',
    'mascot.finn':'Finn','mascot.finn.desc':'Verspielter Delfin',
    'mascot.ember':'Ember','mascot.ember.desc':'Kleiner lila Drache',

    'stats.title':'Statistik',
    'stats.sub':'Echter Fortschritt aus deinen gespielten Fragen',
    'stats.heroTitle':'Dein Wissen wächst',
    'stats.heroSub':'{answered} Fragen beantwortet · {quizzes} {quizWord} gespielt',
    'stats.correctShort':'richtig',
    'stats.xpTotal':'XP insgesamt',
    'stats.coins':'KwizCoins',
    'stats.streak':'Tage in Folge',
    'stats.cards':'Karten',
    'stats.perWorld':'Pro Welt',
    'stats.games':'Spiele',
    'stats.playedLine':'{played}-mal gespielt',
    'stats.runnerLine':'{played} Läufe · {coins} Münzen gesammelt',
    'stats.memoBest':'{n} Züge',
    'stats.memoLine':'{played} Memo-Spiele gespielt · {won} gewonnen',
    'share.text':'{name} spielt Kwizillo! Level {level}, {correct} richtige Antworten, {cards} Wissenskarten. Bestes Quiz: {best}. Willst du auch spielen?',
    'share.copied':'Text kopiert – füge ihn in eine Nachricht ein.',
    'result.share':'Teile dein Ergebnis',
    'stats.worldLine':'{correct} von {answered} richtig · {quizzes} {quizWord}',
    'stats.quizOne':'Quiz',
    'stats.quizMany':'Quiz',

    'settings.title':'Elternbereich',
    'settings.sub':'Einstellungen für ein gutes Spielerlebnis',
    'settings.group':'Klasse',
    'settings.groupSub':'Schwierigkeit anpassen',
    'settings.groupValue':'{n}. Klasse',
    'settings.language':'Sprache',
    'settings.languageSub':'Wähle die Sprache des Spiels',
    'settings.sound':'Ton, Musik & Stimme',
    'settings.soundVoiceOff':'Stimme aus',
    'settings.soundVoiceOn':'Stimme: {voice}',
    'settings.soundMusic':'Musik {state}',
    'settings.on':'an',
    'settings.off':'aus',
    'settings.timeLimit':'Fragen-Timer',
    'settings.timeLimitOff':'Aus',
    'settings.timeLimitValue':'{n} Sekunden pro Frage in diesem Level',
    'settings.privacy':'Datenschutz & Sicherheit',
    'privacy.sub':'Was das Spiel speichert und was es nicht tut',
    'privacy.updated':'Aktualisiert: {date}',
    'privacy.device':'Auf diesem Gerät',
    'privacy.deviceBody':'Das liegt im Speicher der App auf diesem Gerät. Es geht weder an Kwizillo noch an jemand anderen und verschwindet, sobald du die App löschst oder unten alles löschst.',
    'privacy.itemName':'Name: {value}',
    'privacy.itemSettings':'Sprache, Stimme, Ton, Klasse und Level',
    'privacy.itemProgress':'Fortschritt: {answered} Fragen, {correct} richtig, {cards} Karten',
    'privacy.itemPremium':'Ob Premium aktiv ist (das kommt vom App Store)',
    'privacy.leaves':'Was das Gerät verlässt',
    'privacy.leavesBody':'Nur der Satz, den Milo oder Luna vorliest. Er geht an unseren eigenen Server und von dort an den Sprachdienst ElevenLabs. Es ist immer Text aus dem Spiel: eine Frage, eine Antwort, ein Hinweis oder ein Fakt. Nie der Name deines Kindes und nie etwas, das dein Kind selbst tippt.',
    'privacy.none':'Was die App nicht tut',
    'privacy.noneBody':'Keine Werbung. Keine Analyse-Dienste und keine Tracker von Dritten. Kein Konto, keine E-Mail-Adresse, kein Passwort. Kein Standort, keine Kontakte, keine Kamera, kein Mikrofon. Keine Cookies.',
    'privacy.keep':'Aufbewahren und löschen',
    'privacy.keepBody':'Was auf diesem Gerät liegt, bleibt, bis du es löschst; woanders bewahren wir nichts auf. Unser Server speichert die erzeugte Audio (Spielsätze, keine persönlichen Daten), damit derselbe Satz nicht zweimal erzeugt werden muss, und hält die IP-Adresse einer Anfrage kurz im Speicher, um Missbrauch zu verhindern.',
    'privacy.erase':'Alle Daten löschen',
    'privacy.eraseSub':'Name, Einstellungen und Fortschritt auf diesem Gerät',
    'privacy.eraseTitle':'Alles löschen?',
    'privacy.eraseBody':'Name, Einstellungen, Fortschritt, Karten und Statistik verschwinden von diesem Gerät. Ein gekauftes Premium bleibt bei deinem App-Store-Konto und kommt mit „Käufe wiederherstellen“ zurück.',
    'privacy.eraseConfirm':'Ja, alles löschen',
    'privacy.contact':'Fragen zum Datenschutz?',
    'privacy.contactSub':'Schreib an {email}',
    'privacy.noAccount':'Kwizillo funktioniert ohne Konto: Bei uns gibt es nichts anzumelden und nichts zu löschen.',
    'score.points':'Punkte',
    'score.practice':'Übungspunkte',
    'score.dayFull':'Tagesmaximum erreicht',
    'score.title':'Rekorde',
    'score.sub':'Deine besten Punkte in jedem Zeitraum',
    'score.now':'jetzt',
    'score.best':'Rekord',
    'score.run':'Diese Übung',
    'score.day':'Heute',
    'score.week':'Diese Woche',
    'score.month':'Diesen Monat',
    'score.year':'Dieses Jahr',
    'score.allTime':'Aller Zeiten',
    'score.todayPoints':'{n} von {max} Punkten heute',
    'score.todayCoins':'{n} von {max} Münzen heute',
    'score.capNote':'Pro Tag gibt es ein Maximum an Punkten und Münzen, und eine Frage, die du schon richtig hattest, bringt Übungspunkte. So bleibt ein Rekord etwas wert.',
    'shop.tab':'🛒 Laden',
    'shop.title':'Laden',
    'shop.sub':'Bezahle mit Münzen aus den Spielen',
    'shop.buy':'Kaufen',
    'shop.owned':'Im Besitz','shop.earned':'Verdient',
    'shop.price':'{n} Münzen',
    'shop.need':'Noch {n} Münzen',
    'shop.confirmTitle':'{item} kaufen?',
    'shop.confirmBody':'Das kostet {n} Münzen. Danach gehört {item} für immer dir.',
    'shop.bought':'{item} gehört dir!',
    'shop.cards':'Goldene Karten',
    'shop.mascots':'Freunde',
    'shop.goldCard':'Goldenes {world}',
    'shop.goldCardSub':'Eine glänzende Karte für deine Sammlung',
    'shop.earnHint':'Münzen verdienst du im Runner und in den anderen Spielen.',
    'shop.empty':'Alles gekauft! Der Laden ist ganz leer.',
    'result.worldLevelUp':'🎉 {world} steigt auf Level {niveau}!',
    'result.worldMastered':'🏆 {world} ganz geschafft!',
    'result.goldCardEarned':'Du hast die goldene Karte von {world} verdient!',
    'result.goldCardSpeech':'Wow! Du hast {world} komplett geschafft. Die goldene Karte gehört dir!',
    'settings.levelWorlds':'Level pro Welt',
    'settings.levelWorldsSub':'Eine Welt steigt von allein auf, wenn du dort alle vier Quiz schaffst.',
    'settings.levelMath':'Spielstufe',
    'settings.timeLimitPerWorld':'Die Zeit pro Frage richtet sich nach der Stufe.',
    'settings.reset':'Fortschritt zurücksetzen',
    'settings.resetSub':'Ganz von vorn beginnen',
    'settings.resetTitle':'Fortschritt zurücksetzen?',
    'settings.resetBody':'XP, Münzen, Karten, Statistik und gespielter Fortschritt gehen zurück auf Anfang.',
    'settings.resetConfirm':'Ja, zurücksetzen',
    'gate.title':'Eine kurze Frage für einen Erwachsenen',
    'gate.body':'Wie viel ist {a} × {b}?',
    'gate.placeholder':'Antwort',
    'gate.wrong':'Das stimmt nicht. Versuche es noch einmal.',
    'gate.continue':'Weiter',

    'sound.kicker':'EINSTELLUNGEN',
    'sound.title':'🔊 Ton & Musik',
    'sound.fx':'✨ Klangeffekte',
    'sound.music':'🎵 Hintergrundmusik',
    'sound.test':'Testen',
    'sound.pickMusic':'Wähle deine Musik',
    'sound.voiceGuide':'Sprachbegleiter',
    'track.home':'Inseln',
    'track.space':'Weltraum',
    'track.jungle':'Dschungel',
    'track.earth':'Erde',
    'track.history':'Geschichte',
    'track.science':'Wissenschaft',
    'track.mystery':'Geheimnis',
    'track.play':'Spiele',

    'intro.skip':'Intro überspringen',
    'welcome.back.title':'Hallo {name}!',
    'welcome.back.sub':'Bereit weiterzuspielen?',
    'welcome.back.continue':'Weiterspielen',
    'welcome.back.other':'Jemand anderes spielt',
    'welcome.back.where':'Hier warst du stehen geblieben',
    'welcome.pick.title':'Wer spielt?',
    'welcome.pick.new':'Neue Spielerin oder Spieler',
    'welcome.pick.back':'Zurück',
    'intro.tapToStart':'Tippe zum Starten',
    'intro.tapForSound':'Tippe für Ton'
  };
})();
