(()=>{
  // Danish UI strings. Same keys and the same layout as every other language;
  // the child is addressed with "du" throughout.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.da={
    'lang.name':'Dansk',
    'lang.speech':'da',

    'world.ruimte.title':'Rumverdenen',
    'world.ruimte.sub':'Rejs forbi planeter, stjerner og raketter',
    'world.dieren.title':'Dyreverdenen',
    'world.dieren.sub':'Opdag dyr på land, i junglen og i havet',
    'world.aarde.title':'Jordverdenen',
    'world.aarde.sub':'Udforsk lande, oceaner, vejr og kort',
    'world.geschiedenis.title':'Historieverdenen',
    'world.geschiedenis.sub':'Træd ind i faraoernes, riddernes og opdagelsesrejsendes tid',
    'world.wetenschap.title':'Videnskabsverdenen',
    'world.wetenschap.sub':'Prøv, opdag og forstå, hvordan tingene virker',
    'world.mysterie.title':'Mysterieverdenen',
    'world.mysterie.sub':'Løs gåder og følg snedige spor',
    'world.kunst.title':'Kunstverden',
    'world.kunst.sub':'Oplev malerier, musik og store bygninger',
    'world.sport.title':'Sportsverden',
    'world.sport.sub':'Løb, spring og svøm med de bedste sportsfolk',

    'topic.zonnestelsel':'Solsystemet',
    'topic.sterren_planeten':'Stjerner og planeter',
    'topic.astronauten':'Astronauter',
    'topic.raket_avontuur':'Raketeventyr',
    'topic.egyptenaren':'Egypterne',
    'topic.ridders_kastelen':'Riddere og borge',
    'topic.romeinen':'Romerne',
    'topic.ontdekkingsreizigers':'Opdagelsesrejsende',
    'topic.slimme_proefjes':'Snedige forsøg',
    'topic.lichaam':'Kroppen',
    'topic.uitvindingen':'Opfindelser',
    'topic.natuur_energie':'Natur og energi',
    'topic.raadsels':'Gåder',
    'topic.verborgen_schatten':'Skjulte skatte',
    'topic.natuurmysteries':'Naturens mysterier',
    'topic.speurtocht':'Den store jagt',
    'topic.snelle_dieren':'Hurtige dyr',
    'topic.baby_dieren':'Dyreunger',
    'topic.waterdieren':'Dyr i vandet',
    'topic.jungle':'Jungleeventyr',
    'topic.continenten_landen':'Lande og verdensdele',
    'topic.weer_klimaat':'Vejr og klima',
    'topic.oceanen_natuur':'Oceaner og natur',
    'topic.kaarten_navigatie':'Kort og navigation',
    'topic.schilderkunst':'Malerkunst',
    'topic.muziek':'Musik',
    'topic.bouwkunst':'Bygningskunst',
    'topic.dans_theater':'Dans & teater',
    'topic.balsporten':'Boldsport',
    'topic.olympische_spelen':'De olympiske lege',
    'topic.water_wintersport':'Vand- & vintersport',
    'topic.records_helden':'Rekorder & helte',

    'nav.home':'Hjem',
    'nav.achievements':'Pokaler',
    'nav.collection':'Samling',
    'nav.stats':'Tal',
    'nav.more':'Mere',
    'nav.aria':'Hovednavigation',
    'nav.collectionLong':'Min samling',
    'nav.moreLong':'Mere / Forældrezone',

    'common.back':'Tilbage',
    'common.settings':'Indstillinger',
    'common.close':'Luk',
    'common.cancel':'Annuller',
    'common.gotIt':'Forstået',
    'common.brand':'KWIZILLO',
    'common.of':'af',
    // Hvad er jeg?
    'whoami.title':'Hvad er jeg?','whoami.round':'Runde {n} af {total}','whoami.points':'Nu {n} point','whoami.ask':'Hvad er jeg?','whoami.more':'Et spor','whoami.next':'Videre','whoami.timeUp':'Tiden er gået! Det var {answer}.',
    'whoami.speech.ask':'[playful] '+'Hvad er jeg?',   // spoken only: the voice asks it playfully, the tag is not read out
    'whoami.yes':'Ja, {answer}! +{points}','whoami.almost':'Næsten! Det var {answer}.',
    'whoami.speech.yes':'Det er {answer}','whoami.speech.almost':'Næsten! Det var {answer}.',
    'whoami.doneKicker':'HVAD ER JEG?','whoami.doneTitle':'{n} af {total} gættet!','whoami.summary':'{score} af {max} point. Jo hurtigere du gætter, jo flere point.',
    'whoami.speech.great':'Wow, du gætter hurtigt! Godt gået.','whoami.speech.done':'Flot spillet! Næste gang gætter du endnu flere.',
    'jungle.title':'Runner','jungle.tileSub':'Løb, hop og flyv gennem tre baner','jungle.loadError':'Junglen kunne ikke indlæses. Prøv igen senere.',
    'fotozoom.title':'Foto Zoom','fotozoom.round':'Runde {n} af {total}','fotozoom.points':'Nu {n} point','fotozoom.ask':'Hvad er det?','fotozoom.out':'Zoom ud','fotozoom.next':'Videre','fotozoom.timeUp':'Tiden er gået! Det var {answer}.',
    'fotozoom.speech.ask':'[playful] '+'Hvad er det?',   // spoken only: the voice asks it playfully, the tag is not read out
    'fotozoom.yes':'Ja, {answer}! +{points}','fotozoom.almost':'Næsten! Det var {answer}.',
    'fotozoom.speech.yes':'Det er {answer}','fotozoom.speech.almost':'Næsten! Det var {answer}.',
    'fotozoom.doneKicker':'FOTO ZOOM','fotozoom.doneTitle':'{n} af {total} genkendt!','fotozoom.summary':'{score} af {max} point. Jo mindre du zoomer ud, jo flere point.',
    'fotozoom.speech.great':'Sikke nogle skarpe øjne! Godt gået.','fotozoom.speech.done':'Flot kigget! Næste gang ser du endnu flere.',
    'premium.teaser.fotozoom':'Foto Zoom i denne verden er en del af Kwizillo Premium. Bed en voksen om at åbne alle verdener.',
    'jungle.brand':'KWIZILLO RUNNER','jungle.eyebrow':'KWIZILLO • ARCADE','jungle.titleA':'Kwizillo','jungle.titleB':'Runner','jungle.back':'Tilbage til Kwizillo','jungle.backShort':'Tilbage','jungle.easyShort':'Rolig tur',
    'jungle.levelLabel':'VÆLG DIN BANE','jungle.heroLabel':'HVEM LØBER MED DIG?','jungle.heroBoy':'Dreng','jungle.heroGirl':'Pige','jungle.glideOn':'Flyv!','jungle.glideOff':'Løb!','jungle.levelJungle':'Jungle','jungle.levelStad':'By','jungle.levelLucht':'Himmel',
    'jungle.swingOn':'Sving!','jungle.swingOff':'Løb!','jungle.powerSpeed':'⚡ {n}s','jungle.popSpeed':'TURBO!','jungle.popSpeedSub':'7 sekunder lynhurtigt · dobbelte mønter','jungle.labelSpeed':'TURBO!',
    'jungle.canvasLabel':'Spillebane. Venstre og højre piletast styrer. Mellemrum hopper.','jungle.pause':'Pause','jungle.sound':'Lyd til eller fra','jungle.controls':'Spilkontroller','jungle.left':'Venstre','jungle.right':'Højre','jungle.jump':'Hop ↑',
    'jungle.loading':'Dit eventyr gøres klar…','jungle.loadErrorTitle':'Prøv igen','jungle.loadErrorBody':'Junglebillederne kunne ikke indlæses. Tjek din forbindelse, og prøv igen.',
    'jungle.intro':'Følg det gyldne spor.<br>Hop, udforsk og saml!','jungle.legendMagnet':'🧲 Magnet','jungle.legendShield':'🛡 Skjold','jungle.legendGold':'★ Guld +5','jungle.legendDouble':'×2 Bonusstjerne',
    'jungle.easy':'Rolig tur · hopper af sig selv','jungle.music':'Musik','jungle.on':'til','jungle.off':'fra','jungle.start':'På eventyr →',
    'jungle.help':'{n} sekunder • Swipe eller brug knapperne<br>10 mønter i træk = +5 bonus<br>Tag power-ups og find et kort','jungle.countFollow':'Følg mønterne!','jungle.countReady':'Klar til eventyr?',
    'jungle.pauseEyebrow':'TRÆK VEJRET','jungle.pauseTitle':'Din jungle<br>venter.','jungle.pauseBody':'Tiden står stille.','jungle.resume':'Spil videre →','jungle.exit':'Gå uden belønning',
    'jungle.hit':'Ups! Du blev stoppet — løb videre.','jungle.hitLost':'Av! Du stødte ind — {n} mønter væk.','jungle.labelHit':'−{n}','jungle.lostCoins':'Mistede mønter','jungle.cardFound':'Du har fundet et junglekort!','jungle.powerDouble':'×2 {n}s','jungle.powerMagnet':'🧲 {n}s','jungle.powerShield':'🛡 Beskyttet','jungle.powerStreak':'★ {n} i træk',
    'jungle.popDouble':'BONUSSTJERNE!','jungle.popDoubleSub':'6 sekunder med dobbelte mønter','jungle.popGold':'GULD FUNDET!','jungle.popGoldSub':'+{n} mønter','jungle.popCombo':'{n} I TRÆK!','jungle.popComboSub':'+5 i combo-bonus','jungle.popMagnet':'MØNTMAGNET!','jungle.popMagnetSub':'7 sekunder med møntsug',
    'jungle.popShield':'SKJOLD!','jungle.popShieldSub':'Tager et stød for dig','jungle.popBlock':'SKJOLDET REDDEDE DIG!','jungle.popBlockSub':'Løb bare videre','jungle.popCard':'KORT FUNDET!','jungle.popCardSub':'Vises ved målstregen','jungle.popClear':'FLOT HOP!','jungle.popClearSub':'Over træstammen','jungle.popDoubleflip':'DOBBELT SALTO!','jungle.popDoubleflipSub':'+3 mønter',
    'jungle.labelGold':'+{n} GULD!','jungle.labelCombo':'COMBO +5','jungle.labelCard':'Kort fundet!','jungle.labelClear':'Flot hop!','jungle.labelMagnet':'MAGNET!','jungle.labelShield':'SKJOLD!','jungle.labelBlock':'Reddet!','jungle.labelDouble':'DOBBELTE MØNTER!',
    'jungle.saving':'Din belønning gemmes…','jungle.saved':'Dine mønter er lagt til.','jungle.saveError':'Det lykkedes ikke at gemme endnu. Prøv igen.',
    'jungle.finishEyebrow':'EVENTYRET ER FULDFØRT','jungle.finish':'MÅL!','jungle.finishSub':'Dit bytte fra denne tur','jungle.coinsEarned':'mønter tjent','jungle.bestStreak':'Bedste stime','jungle.bonusCoins':'Bonusmønter',
    'jungle.cardAlt':'Samlet kort','jungle.cardEyebrow':'KORT FUNDET','jungle.cardSub':'Til din Kwizillo-samling','jungle.cardTitle':'Jungleblad','card.jungle-leaf':'Jungleblad','card.city-star':'Bystjerne','card.sky-feather':'Himmelfjer','jungle.retry':'Gem igen','jungle.take':'Tag mit bytte','jungle.again':'Andet eventyr','jungle.replay':'Den her igen',
    // Premium
    'common.ok':'OK','common.retry':'Prøv igen',
    'premium.label':'Premium','premium.name':'Kwizillo Premium','premium.kicker':'TIL FORÆLDRE',
    'premium.title':'Åbn hele Kwizillos verden',
    'premium.subtitle':'Spil, lær, saml og opdag uden grænser.',
    'premium.benefit.worlds':'Alle verdener','premium.benefit.questions':'1280 videnspørgsmål','premium.benefit.math':'Regnespil','premium.benefit.memo':'Hukommelsesspil','premium.benefit.facts':'Sjove fakta','premium.benefit.guides':'Milo og Luna','premium.benefit.collect':'Saml kort og maskotter','premium.benefit.stats':'Fuld fremgang og statistik','premium.benefit.new':'Nye eventyr og nyt indhold',
    'premium.monthly':'Månedligt','premium.yearly':'Årligt','premium.perMonth':'måned','premium.perYear':'år',
    'premium.best':'Bedste pris','premium.trial':'Prøv {days} dage gratis','premium.ctaTrial':'Start {days} gratis dage','premium.ctaYearly':'Vælg årligt','premium.ctaMonthly':'Vælg månedligt',
    'premium.perMonthCalc':'Det er {price} om måneden',
    'premium.legal':'Abonnementet trækkes på din Apple-konto og fornyes automatisk, indtil du opsiger det. Du kan altid administrere eller opsige det under dine Apple-abonnementer. En gratis periode bliver til et betalt abonnement, hvis du ikke opsiger inden den slutter.',
    'premium.restore':'Gendan køb','premium.restoreSub':'Hent Premium tilbage på denne enhed','premium.manage':'Administrer abonnement','premium.manageSub':'Opsig eller skift via Apple','premium.privacy':'Privatliv','premium.terms':'Brugsbetingelser',
    'premium.loading':'Henter priser…','premium.purchasing':'Et øjeblik, Apple behandler købet…',
    'premium.pending':'Købet venter på godkendelse. Så snart den kommer, tænder Premium af sig selv.',
    'premium.cancelled':'Købet blev annulleret.','premium.failed':'Det virkede ikke. Prøv igen senere.',
    'premium.unavailable':'Premium er ikke tilgængelig lige nu. Prøv igen senere.',
    'premium.already':'Premium er aktiv på denne enhed.',
    'premium.restoring':'Gendanner køb…','premium.restoreNone':'Der blev ikke fundet noget tidligere køb.','premium.manageUnavailable':'Administrer abonnementer i din telefons Indstillinger under din Apple-konto.',
    'premium.welcome':'Velkommen til Kwizillo Premium!','premium.welcomeSub':'Alle verdener, spil og fakta er åbne. God fornøjelse!','premium.continue':'Fortsæt, hvor du var','premium.play':'Spil',
    'premium.statusFree':'Gratis version · lås alt op','premium.statusActive':'Aktiv · {type}','premium.statusTrial':'Gratis periode · {type}','premium.statusExpired':'Udløbet · din fremgang er gemt','premium.renews':'Fornyes den',
    'premium.teaserTitle':'Det her er Premium','premium.askParent':'Spørg en voksen',
    'premium.teaser.quiz':'Denne quiz er en del af Kwizillo Premium. Bed en voksen om at åbne alle verdener.',
    'premium.teaser.mega':'Megaquizzen hører til Kwizillo Premium. Spørg en voksen om at åbne alle verdener.',
    'premium.teaser.memo':'Dette hukommelsesspil er en del af Kwizillo Premium. Bed en voksen om at åbne alle plader.',
    'premium.teaser.math':'De højere regneniveauer er en del af Kwizillo Premium. Bed en voksen om at åbne dem.',
    'premium.teaser.facts':'Flere fakta er en del af Kwizillo Premium. Bed en voksen om at åbne dem alle.',
    'premium.factsMore':'{n} flere fakta med Premium',
    'premium.teaser.whoami':'Hvad er jeg? i denne verden er en del af Kwizillo Premium. Bed en voksen om at åbne alle verdener.',
    'settings.terms':'Brugsbetingelser','settings.termsBody':'Kwizillo er et læringsspil for børn. Premium er et abonnement, der trækkes via Apple og fornyes automatisk, indtil du opsiger det; du kan altid opsige det under dine Apple-abonnementer. Der er hverken reklamer eller køb inde i selve spillet.',

    'onboarding.language.title':'Vælg dit sprog',
    'onboarding.language.sub':'Hvilket sprog vil du spille på?',
    'onboarding.name.title':'Hvad hedder du?',
    'onboarding.name.sub':'Så vi kan sige ordentligt goddag.',
    'onboarding.name.placeholder':'Dit navn',
    'onboarding.name.hint':'Dit navn bliver på denne enhed.',
    'onboarding.voice.title':'Hvem hjælper dig?',
    'onboarding.voice.sub':'Vælg din guide. Du kan altid skifte.',
    'onboarding.welcome.title':'Velkommen, {name}!',
    'onboarding.welcome.sub':'Dit eventyr begynder nu. Klar til at udforske?',
    'onboarding.welcome.cta':'Start eventyret',
    'onboarding.next':'Videre',
    'onboarding.speech.welcome':'Ja, alt er klar! Kom, jeg viser dig hurtigt, hvor tingene er.',
    'onboarding.speech.language':'Hej! Jeg hedder Milo. Hvilket sprog taler du?',
    'onboarding.speech.name':'Dejligt at møde dig! Hvad hedder du? Skriv det bare.',
    'onboarding.speech.age':'Og hvor gammel er du?',
    'onboarding.speech.group':'Hvilken klasse går du i?',
    'onboarding.speech.voice':'Hvem vil du have som guide? Mig, Luna, eller hellere stille?',
    'onboarding.age.title':'Hvor gammel er du?',
    'onboarding.age.sub':'Tryk på din alder.',
    'onboarding.age.years':'{n} år',
    'onboarding.group.title':'Hvilken klasse går du i?',
    'onboarding.group.sub':'Så jeg kan vælge spørgsmål, der passer til dig.',
    'tour.mega':'Øverst er Megaquizzen: firs spørgsmål fra alle verdener, helt blandet!',
    'tour.worlds':'Det her er de otte verdener, fra rummet og dyrene til kunst og sport. Om lidt trykker du på en verden og spiller en quiz!',
    'tour.games':'Og her er spillene: Runner, Sprog, Regning, Hvad er jeg?, Foto Zoom, Sjove fakta og Memo. Om lidt kan du prøve dem alle sammen!',
    'tour.facts':'Og det her er Sjove fakta: hundredvis af sjove ting at opdage!',
    'tour.hud':'Øverst står dit niveau, dine mønter og dine dage i træk. Tandhjulet er til de voksne.',
    'tour.nav':'Nederst står din samling, dine præstationer og din statistik. Under Mere er indstillingerne.',
    'tour.done':'Nu er det din tur! Tryk på det, du har lyst til. God fornøjelse, jeg hjælper dig, når du går i stå.',
    'tour.skip':'Spring over',
    'tour.again':'Rundvisning med {guide}',
    'tour.againSub':'{guide} viser dig igen, hvor tingene er.',
    'tour.pick':'Rundvisning',
    'tour.pickSub':'Vælg, hvem der viser dig, hvor tingene er.',
    'school.title':'Kwizillo i skolen',
    'school.codeAsk':'Hvad er din klasses kode?',
    'school.codeHint':'Den står på tavlen eller på dit kort.',
    'school.next':'Videre',
    'school.codeWrong':'Den klassekode kender vi ikke. Se efter igen.',
    'school.whoAmI':'Hvem er du?',
    'school.pictures':'Tryk på dine tre billeder',
    'school.picturesHint':'I den rigtige rækkefølge, som på dit kort.',
    'school.picturesWrong':'Det er ikke dine billeder. Prøv igen.',
    'school.locked':'Vent lidt, og prøv så igen.',
    'school.offline':'Ingen forbindelse. Prøv igen.',
    'school.back':'Tilbage',
    'school.logout':'Log ud',
    'school.logoutSub':'Færdig med at spille? Log ud, så den næste kan spille.',
    'school.signedIn':'{name} · {class}',
    'players.title':'Spillere på denne enhed',
    'players.sub':'Hvem der spiller på denne enhed.',
    'settings.feedback':'Idéer og feedback',
    'settings.feedbackSub':'Hjælp os med at gøre Kwizillo endnu bedre',
    'feedback.title':'Fortæl os det!',
    'feedback.lead':'Har du en idé, er der noget, der ikke er rigtigt, eller elsker du noget? Vi læser det hele.',
    'feedback.kind.idea':'Idé',
    'feedback.kind.bug':'Bemærkning',
    'feedback.kind.love':'Ros',
    'feedback.placeholder':'Skriv din besked her…',
    'feedback.empty':'Skriv din besked først.',
    'feedback.send':'Send',
    'feedback.note':'En forælder sender beskeden på e-mail. Dit navn kommer ikke med.',
    'feedback.thanksTitle':'Tusind tak!',
    'feedback.thanks':'Vi læser din besked og bruger den til at gøre Kwizillo endnu bedre sammen med dig.',
    'players.current':'spiller nu',
    'players.delete':'Slet',
    'players.deleteTitle':'Slet {name}?',
    'players.deleteBody':'Alt om {name} fjernes fra denne enhed. Det kan ikke fortrydes.',
    'players.deleteCard':'Slet en spiller',
    'players.deleteCardSub':'Fjern en spiller og alt, hvad spilleren har spillet, fra denne enhed',
    'players.deletePick':'Hvilken spiller vil du slette?',
    'settings.logout':'Log ud',
    'settings.logoutSub':'Vælg en anden spiller eller start en ny.',

    'voice.milo':'Milo',
    'voice.milo.desc':'Glad og livlig',
    'voice.luna':'Luna',
    'voice.luna.desc':'Rolig og venlig',
    'voice.silent':'Stille',
    'voice.silent.desc':'Ingen stemme',
    'voice.milo.hello':'Hej! Jeg hedder Milo. Klar til at spille?',
    'voice.luna.hello':'Hej! Jeg hedder Luna. Skal vi udforske sammen?',

    'home.greeting':'Hej {name}!',
    'home.greetingAnon':'Hej!',
    'home.level':'Niveau {level}',
    'home.coins':'KwizCoins',
    'home.streak':'Dage i træk',
    'home.pickWorld':'Vælg din verden',
    'home.cta':'Start eventyret',
    'home.ctaSub':'Fortsæt i {world}',
    'home.voiceLabel':'Stemme',
    'home.languageLabel':'Sprog',

    'world.kicker':'KWIZILLO-VERDEN',
    'world.backHome':'Tilbage til start',
    'world.mix':'Start blandet quiz',
    'world.mixSub':'Spørgsmål fra alle fire emner',
    'world.quizNumber':'Quiz {n}',
    'world.topicPassed':'Klaret',
    'world.topicPlayed':'Quiz {n} spillet · {correct}/{answered} rigtige',
    'world.progressLine':'{passed} af {total} emner klaret',
    'world.worldProgress':'{done} af denne verdens {total} quizzer klaret',
    'world.mixDone':'{n} spillet',

    'quiz.mixed':'Blandet quiz',
    'mega.title':'Megaquiz',
    'talen.title':'Sprog',
    'collection.tabWords':'🗣️ Ord',
    'collection.wordsEmpty':'Ingen ord endnu',
    'collection.wordsEmptyBody':'Spil en lektion i Sprog. Hvert ord du lærer, kommer her.',
    'collection.wordsCount':'{n} ord på {lang}. Tryk for at høre dem.',
    'stats.talenLine':'{words} ord lært · {lessons} lektioner',
    'achievement.talenFirst':'Første lektion i Sprog',
    'achievement.talen10':'10 ord lært',
    'talen.passport':'Sprogpas',
    'talen.passportSub':'Lær {lang} med Milo',
    'talen.passportSubLuna':'Lær {lang} med Luna',
    'talen.pickTitle':'Hvilket sprog vil du lære?',
    'talen.pickSub':'Tryk på et flag og hør, hvordan man siger hej.',
    'talen.pickGo':'Lær {lang}!',
    'talen.switchLang':'Andet sprog',
    'talen.lang.en':'engelsk',
    'talen.lang.nl':'hollandsk',
    'talen.lang.de':'tysk',
    'talen.lang.fr':'fransk',
    'talen.lang.es':'spansk',
    'talen.lang.it':'italiensk',
    'talen.lang.pt':'portugisisk',
    'talen.lang.da':'dansk',
    'talen.lang.ru':'russisk',
    'talen.lang.ar':'arabisk',
    'talen.soon':'snart',
    'talen.soonLang':'Snart også på dit sprog',
    'talen.msgNew':'Hver lektion giver et stempel. Start med dyrene!',
    'talen.msgPlayed':'Super! Dit stempel er med. Spil igen for flere stjerner.',
    'talen.start':'Start lektionen',
    'talen.again':'Spil {theme} igen',
    'talen.review':'Hurtig gentagelse',
    'talen.reviewSub':'{n} ord skal gentages',
    'talen.reviewDone':'Godt gentaget!',
    'talen.replay':'Igen',
    'talen.listen':'Lyt til ordet',
    'talen.picture':'Billede',
    'talen.means':'betyder {word}',
    'talen.round':'Runde {n} af {total}',
    'talen.firstTry':'rigtige første gang',
    'talen.learned':'Du har lært disse ord. Tryk for at høre dem.',
    'talen.theme.dieren':'Dyr',
    'talen.theme.kleuren':'Farver',
    'talen.theme.eten':'Mad og drikke',
    'talen.theme.getallen':'Tal',
    'talen.theme.lichaam':'Krop',
    'talen.theme.vervoer':'Transport',
    'talen.theme.sport':'Sport',
    'talen.theme.praten':'Snak',
    'talen.section.words':'Ord',
    'talen.section.sentences':'Sætninger',
    'talen.theme.huis':'Hjemme',
    'talen.theme.natuur':'Natur',
    'talen.theme.familie':'Familie',
    'talen.theme.kleding':'Tøj',
    'talen.theme.school':'Skole',
    'talen.theme.mij':'Om mig',
    'talen.theme.vragen':'Spørgsmål',
    'talen.theme.gevoel':'Følelser',
    'talen.theme.samen':'Leg sammen',
    'talen.theme.mix':'Blanding',
    'talen.done.dieren':'Du kender dyrene!',
    'talen.done.kleuren':'Du kender farverne!',
    'talen.done.eten':'Du kender mad og drikke!',
    'talen.done.getallen':'Du kan tælle!',
    'talen.done.lichaam':'Du kender din krop!',
    'talen.done.vervoer':'Du kender transportmidlerne!',
    'talen.done.sport':'Du kender sporten!',
    'talen.done.praten':'Du kan snakke!',
    'talen.done.huis':'Du kender hele huset!',
    'talen.done.natuur':'Du kender naturen!',
    'talen.done.familie':'Du kender familien!',
    'talen.done.kleding':'Du kender alt tøjet!',
    'talen.done.school':'Du kender dine skoleting!',
    'talen.done.mij':'Du kan fortælle om dig selv!',
    'talen.done.vragen':'Du kan stille spørgsmål!',
    'talen.done.gevoel':'Du kan sige, hvordan du har det!',
    'talen.done.samen':'I kan lege sammen!',
    'talen.done.mix':'Alt blandet, og du kan det!',
    'jungle.bannerSub':'Løb, hop og saml mønter',
    'settings.learnLang':'Læringssprog',
    'settings.learnLangSub':'Det sprog dit barn lærer i Sprog',
    'premium.teaser.talen':'Dette tema hører til Kwizillo Premium. Dyrene er gratis. Spørg en voksen om at åbne alle temaer.',
    'mega.sub':'{n} spørgsmål fra alle verdener',
    'mega.rule':'Spørgsmål fra alle {worlds} verdener: du havde {score} af {total} rigtige.',
    'mega.again':'En megaquiz mere',
    'mega.collectionLine':'Spillet {played} gange · bedst {best} af {total}',
    'quiz.progress':'Spørgsmål {current} af {total}',
    'quiz.hint':'Spor',
    'quiz.none':'Der er endnu ingen spørgsmål til dette emne.',
    'quiz.artAlt':'Illustration til spørgsmålet',
    'quiz.quizLabel':'Quiz {n}',
    'quiz.back':'Tilbage',
    'quiz.explain':'Forklar',
    'quiz.timerAria':'Sekunder tilbage',
    'feedback.timeKicker':'TIDEN ER GÅET!',
    'feedback.timeTitle':'Hurtigere næste gang!',
    'settings.level':'Niveau',
    'settings.levelSub':'{seconds} s pr. spørgsmål · maks. {allowed} fejl · {hints}',
    'settings.hintsFree':'spor er frie',
    'settings.hintsN':'{n} spor',
    'settings.hintsNone':'ingen spor',
    'settings.readsQuestionOnly':'kun spørgsmålet læses højt',
    'quiz.hintsSpent':'Der er ikke flere spor i denne quiz.',
    'quiz.noHints':'Niveau 6 har ingen spor.',
    'world.speech.enter':'[excited] {title}!',
    'settings.levelAuto':'Auto',
    'settings.share':'Del din score',
    'settings.shareSub':'Send dit resultat til familie eller venner',

    'hint.title':'Et lille spor',
    'hint.kicker':'Tip om {topic}',
    'hint.ok':'Tænk videre',
    'hint.close':'Luk sporet',
    'hint.fallback':'Kig godt på spørgsmålet og billedet en gang til.',
    'hint.alt':'Spor i billedet',

    'feedback.goodKicker':'RIGTIGT!',
    'feedback.tryKicker':'SÅ TÆT PÅ!',
    'feedback.goodTitle':'Flot spillet!',
    'feedback.tryTitle':'Godt tænkt!',
    'feedback.correctIs':'Det rigtige svar er <strong>{answer}</strong>.',
    'feedback.thatsRight':'Det er rigtigt!',
    'feedback.didYouKnow':'Vidste du det?',
    'feedback.next':'Næste spørgsmål',
    'feedback.seeResult':'Se resultatet',
    'feedback.speech.good':'Godt gået.',
    'feedback.speech.good.1':'Godt gået!',
    'feedback.speech.good.2':'Super, det er rigtigt!',
    'feedback.speech.good.3':'Lige i plet!',
    'feedback.speech.good.4':'Rigtig flot!',
    'feedback.speech.good.5':'Ja! Præcis!',
    'feedback.speech.good.6':'Skønt, godt set!',
    'feedback.speech.good.7':'Fantastisk!',
    'feedback.speech.good.8':'Wow, det er korrekt!',
    'feedback.speech.good.9':'Ja, sådan!',
    'feedback.speech.good.10':'Top!',
    'feedback.speech.good.11':'Perfekt!',
    'feedback.speech.good.12':'Rigtig godt, bliv ved!',
    'feedback.speech.good.13':'Du er godt kørende!',
    'feedback.speech.good.14':'Flot klaret!',
    'feedback.speech.good.15':'Helt rigtigt!',
    'feedback.speech.good.16':'Bingo!',
    'feedback.speech.good.17':'Sejt!',
    'feedback.speech.good.18':'Fedt!',
    'feedback.speech.good.19':'Vildt godt!',
    'feedback.speech.good.20':'Sådan!',
    'feedback.speech.good.21':'Mega godt!',
    'feedback.speech.good.22':'Nice!',
    'feedback.speech.good.23':'Super sejt!',
    'feedback.speech.good.24':'Pletskud!',
    'feedback.speech.good.25':'Godt set!',
    'feedback.speech.good.26':'Wow, flot!',
    'feedback.speech.good.27':'Du er god!',
    'feedback.speech.good.28':'Giv mig fem!',
    'feedback.speech.good.29':'Vildt sejt!',
    'feedback.speech.good.30':'Sikke en klog en!',
    'feedback.speech.try.1':'Næsten. Det rigtige svar er {answer}.',
    'feedback.speech.try.2':'Ikke helt. Det rigtige svar er {answer}.',
    'feedback.speech.try.3':'Godt forsøgt! Det rigtige svar er {answer}.',
    'feedback.speech.try.4':'Ups, så tæt på. Det rigtige svar er {answer}.',
    'feedback.speech.try.5':'Lige ved og næsten. Det rigtige svar er {answer}.',
    'feedback.speech.try.6':'Uh, den var svær! Det rigtige svar er {answer}.',
    'feedback.speech.try.7':'Åh, tæt på! Det rigtige svar er {answer}.',
    'feedback.speech.try.8':'Hmm, ikke helt. Det rigtige svar er {answer}.',
    'feedback.speech.try.9':'Det gør ikke noget! Det rigtige svar er {answer}.',
    'feedback.speech.try.10':'Næste gang klarer du den! Det rigtige svar er {answer}.',
    'feedback.speech.try.11':'Den var svær! Det rigtige svar er {answer}.',
    'feedback.speech.try.12':'Næsten! Det rigtige svar er {answer}.',
    'feedback.answerLabel':'Det rigtige svar',
    'feedback.close':'Luk',
    'feedback.listening':'Lytter…',
    'quiz.repeat':'Igen',
    'quiz.repeatAria':'Læs spørgsmålet igen',
    'feedback.speech.try':'Næsten. Det rigtige svar er {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'QUIZZEN ER SLUT',
    'result.title':'{score} ud af {total} rigtige!',
    'result.score':'score',
    'result.xp':'XP',
    'result.coins':'mønter',
    'result.again':'En quiz mere',
    'result.againNumbered':'Start quiz {n}',
    'result.nextTopic':'Næste: {topic}',
    'result.finishWorld':'Start blandet quiz',
    'result.retryTopic':'Dette emne en gang til',
    'result.retryNow':'Prøv igen',
    'memo.title':'Memo',
    'memo.pickTitle':'Vælg din verden',
    'game.mixAll':'Mix alle verdener',
    'game.pickSub':'Vælg én verden, eller spil dem alle blandet.',
    'memo.pickSub':'Find parrene · Niveau {n}',
    'memo.otherWorld':'En anden verden',
    'memo.sub':'Find parrene',
    'memo.play':'Spil Memo',
    'memo.playSub':'Find parrene fra {world}',
    'memo.level':'Niveau {n}',
    'memo.pairs':'{found} af {total} par',
    'memo.boostTitle':'Gyldent boost!','memo.boostSub':'3 par i træk · +{xp} point',
    'memo.moves':'{n} ture',
    'memo.movesShort':'ture',
    'memo.card':'Memokort',
    'memo.hintLine':'Vend to kort og find parrene',
    'memo.none':'Der er endnu ikke kort nok til denne verden.',
    'memo.doneKicker':'MEMO KLARET!',
    'memo.doneTitle':'Alle par fundet!',
    'memo.timeKicker':'TIDEN ER GÅET!',
    'memo.timeTitle':'Næsten alle par!',
    'memo.summary':'{pairs} par på {moves} ture og {secs} sekunder.',
    'memo.summaryTime':'{found} af {pairs} par fundet. Prøv igen!',
    'memo.again':'En gang til',
    'memo.retry':'Prøv igen',
    'memo.toWorld':'Tilbage til verdenen',
    'memo.speech.done':'Wow, du fandt alle par! Sikke en hukommelse!',
    'memo.speech.time':'Tiden er gået. Næste gang finder du dem alle!',
    'memo.modeTitle':'Hvordan spiller du?',
    'memo.solo':'Alene','memo.soloSub':'Mod uret',
    'memo.duel':'Mod hinanden','memo.duelSub':'På skift: hvem finder flest par?',
    'memo.player1':'Spiller 1','memo.player2':'Spiller 2','memo.p2Label':'Hvem spiller med?',
    'memo.turn':'Det er {name}s tur',
    'memo.duelKicker':'MEMO-DUEL',
    'memo.duelWin':'{name} vinder!','memo.duelTie':'Uafgjort!',
    'memo.duelSummary':'{pairs} par på {moves} ture.',
    'memo.rematch':'Omkamp',
    'memo.speech.win':'Vi har en vinder! Flot spillet, begge to!',
    'memo.speech.tie':'Uafgjort! I har begge en god hukommelse!',
    'home.playMore':'Spil mere',
    'math.title':'Regning',
    'facts.title':'Sjove fakta',
    'world.ruimte.short':'Rummet','world.dieren.short':'Dyr','world.aarde.short':'Jorden','world.geschiedenis.short':'Historie','world.wetenschap.short':'Videnskab','world.kunst.short':'Kunst','world.sport.short':'Sport','world.mysterie.short':'Mysterie',
    'facts.tileSub':'Vidste du, at…',
    'facts.sub':'{seen} af {total} opdaget',
    'facts.next':'Næste faktum',
    'facts.listen':'Læs højt',
    'facts.kicker':'Vidste du, at…',
    'facts.new':'Nyt!',
    'facts.allSeen':'Du har opdaget alle fakta! Nu kommer de en gang til.',
    'facts.more':'Flere fakta',
    'math.sub':'Hurtige stykker',
    'math.play':'Regning',
    'math.playSub':'Ti stykker · Niveau {n}',
    'math.progress':'Stykke {current} af {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'{score} af {total} stykker rigtige!',
    'math.again':'Ti nye stykker',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'plus',
    'math.op.minus':'minus',
    'math.op.times':'gange',
    'math.op.divided':'divideret med',
    'math.op.equals':'er',
    'math.speech.twoStep':'{c} plus {a} gange {b}',
    'math.speech.half':'Halvdelen af {n}',
    'math.speech.quarter':'En fjerdedel af {n}',
    'math.speech.percent':'{p} procent af {n}',
    'math.money.title':'Tæl pengene',
    'math.money.ask':'Hvor mange penge er det?',
    'math.money.main.one':'{n} krone',
    'math.money.main.few':'{n} kroner',
    'math.money.main.many':'{n} kroner',
    'math.money.sub.one':'{n} øre',
    'math.money.sub.few':'{n} øre',
    'math.money.sub.many':'{n} øre',
    'math.money.and':'og',
    'math.speech.wrong':'Næsten. Det er {answer}.',
    'math.speech.done':'Flot regnet! Alle stykker er klaret.',
    'math.speech.fail':'Godt forsøgt. En gang til, så lykkes det!',
    'math.hint.plus':'Tæl videre fra {a}: {b} mere.',
    'math.hint.minus':'Start ved {a} og tæl {b} tilbage.',
    'math.hint.times':'{a} gange {b}: læg {b} sammen præcis {a} gange.',
    'math.hint.divided':'Hvor mange gange går {b} op i {a}?',
    'math.hint.generic':'Regn det ud skridt for skridt.',
    'achievement.math3':'3 regnerunder klaret',
    'stats.mathLine':'{played} runder spillet · {won} klaret',
    'result.passKicker':'BESTÅET!',
    'result.failKicker':'IKKE ENDNU',
    'result.passRule':'Niveau {niveau}: du måtte lave {allowed} fejl, og du lavede {wrong}.',
    'result.failRule':'Niveau {niveau}: du må lave {allowed} fejl, og du lavede {wrong}. Spil dette emne en gang til!',
    'result.toHome':'Til Hjem',

    'profile.title':'Min profil',
    'profile.sub':'Dit navn, din ven og dine indstillinger',
    'profile.saveName':'Gem navnet',
    'profile.saved':'Gemt!',
    'profile.buddy':'Min ven',
    'profile.chooseBuddy':'Vælg ven',
    'profile.voice':'Hvem læser højt?',
    'achievements.title':'Pokaler',
    'achievements.sub':'Dine eventyr og milepæle',
    'achievements.summary':'{done}/{total} opnået',
    'achievements.summarySub':'Bliv ved med at udforske og lås nye pokaler op.',
    'achievements.done':'Opnået!',
    'achievement.firstQuiz':'Første quiz',
    'achievement.correct10':'10 rigtige svar',
    'achievement.correct50':'50 rigtige svar',
    'achievement.streak7':'7 dage i træk',
    'achievement.cards5':'5 videnskort',
    'achievement.allWorlds':'Alle verdener besøgt',
    'achievement.memo3':'3 memospil vundet',

    'collection.title':'Min samling',
    'collection.sub':'Alt det, du har opdaget',
    'collection.tabWorlds':'🌍 Verdener',
    'collection.tabCards':'🃏 Kort',
    'collection.tabMascots':'🐾 Venner',
    'collection.worldStat':'{correct}/{answered} rigtige · {pct}%',
    'progress.worldLine':'{passed} af {total} quizzer bestået · {points} point',
    'progress.overall':'I alt {points} af {max} point',
    'progress.overallSub':'Hver bestået quiz er 25 point værd: en hel verden er 100.',
    'collection.discovered':'★ Opdaget',
    'collection.unlockKicker':'NY VEN!',
    'collection.unlockLine':'Låst op med {n} rigtige svar.',
    'score.coinsAdded':'+{n} mønter tilføjet',
    'score.coinsCapped':'Dagens maksimum nået: {n} af dine {got} mønter blev tilføjet.','collection.cardAdded':'{title} er nu i din samling!',
    'collection.emptyTitle':'Ingen kort endnu',
    'collection.emptyBody':'Svar rigtigt på spørgsmålene for at samle videnskort.',
    'collection.mascotLocked':'{n} rigtige svar mere',
    'collection.mascotShop':'I butikken: {n} mønter',
    'collection.mascotActive':'Aktiv ✓',
    'collection.mascotChoose':'Vælg ven',
    'collection.mascotCount':'{unlocked}/{total} venner låst op',

    'mascot.milo':'Milo',
    'mascot.milo.desc':'Din kloge robotven',
    'mascot.comet':'Komet',
    'mascot.comet.desc':'Ven fra rummet',
    'mascot.pootje':'Pote',
    'mascot.pootje.desc':'Dyrenes ven',
    'mascot.terra':'Terra',
    'mascot.terra.desc':'Jordens beskytter',
    'mascot.sparky':'Sparky',
    'mascot.sparky.desc':'Forsøgsfan',
    'mascot.lumi':'Lumi',
    'mascot.lumi.desc':'Mysteriejæger',
    'mascot.nova':'Nova','mascot.nova.desc':'Stjernerejsende',
    'mascot.kiko':'Kiko','mascot.kiko.desc':'Jungleopdager',
    'mascot.pip':'Pip','mascot.pip.desc':'Iskold vovehals',
    'mascot.ravi':'Ravi','mascot.ravi.desc':'Opfinder i lære',
    'mascot.flora':'Flora','mascot.flora.desc':'Naturens ven',
    'mascot.draco':'Draco','mascot.draco.desc':'Lille borgdrage',
    'mascot.mike':'Mike','mascot.mike.desc':'Musikfan med høretelefoner',

    'stats.title':'Tal',
    'stats.sub':'Rigtig fremgang fra de spørgsmål, du har spillet',
    'stats.heroTitle':'Din viden vokser',
    'stats.heroSub':'{answered} spørgsmål besvaret · {quizzes} {quizWord} spillet',
    'stats.correctShort':'rigtige',
    'stats.xpTotal':'XP i alt',
    'stats.coins':'KwizCoins',
    'stats.streak':'Dage i træk',
    'stats.cards':'Kort',
    'stats.perWorld':'Pr. verden',
    'stats.games':'Spil',
    'stats.playedLine':'spillet {played} gange',
    'stats.runnerLine':'{played} ture · {coins} mønter samlet',
    'stats.memoBest':'{n} ture',
    'stats.memoLine':'{played} memospil spillet · {won} vundet',
    'share.text':'{name} spiller Kwizillo! Niveau {level}, {correct} rigtige svar, {cards} videnskort. Bedste quiz: {best}. Vil du også spille?',
    'share.copied':'Teksten er kopieret – sæt den ind i en besked.',
    'result.share':'Del din score',
    'stats.worldLine':'{correct} af {answered} rigtige · {quizzes} {quizWord}',
    'stats.quizOne':'quiz',
    'stats.quizMany':'quizzer',

    'settings.title':'Forældrezone',
    'settings.sub':'Indstillinger til en god spiloplevelse',
    'settings.group':'Klassetrin',
    'settings.groupSub':'Juster sværhedsgraden',
    'settings.groupValue':'{n}. klasse',
    'settings.language':'Sprog',
    'settings.languageSub':'Vælg spillets sprog',
    'settings.sound':'Lyd, musik og stemme',
    'settings.soundVoiceOff':'Stemme fra',
    'settings.soundVoiceOn':'Stemme: {voice}',
    'settings.soundMusic':'musik {state}',
    'settings.on':'til',
    'settings.off':'fra',
    'settings.timeLimit':'Spørgsmålstimer',
    'settings.timeLimitOff':'Fra',
    'settings.timeLimitValue':'{n} sekunder pr. spørgsmål på dette niveau',
    'settings.privacy':'Privatliv og sikkerhed',
    'privacy.sub':'Hvad spillet gemmer, og hvad det ikke gør',
    'privacy.updated':'Opdateret: {date}',
    'privacy.device':'På denne enhed',
    'privacy.deviceBody':'Det ligger i appens lager på denne enhed. Det går hverken til Kwizillo eller til andre og forsvinder, så snart du sletter appen eller sletter alt her nedenfor.',
    'privacy.itemName':'Navn: {value}',
    'privacy.itemSettings':'Sprog, stemme, lyd, klassetrin og niveau',
    'privacy.itemProgress':'Fremgang: {answered} spørgsmål, {correct} rigtige, {cards} kort',
    'privacy.itemPremium':'Om Premium er aktiv (det kommer fra App Store)',
    'privacy.leaves':'Hvad der forlader enheden',
    'privacy.leavesBody':'Kun den sætning, Milo eller Luna læser højt. Den går til vores egen server og derfra til taletjenesten ElevenLabs. Det er altid tekst fra spillet: et spørgsmål, et svar, et spor eller et faktum. Aldrig dit barns navn og aldrig noget, dit barn selv skriver.',
    'privacy.none':'Hvad appen ikke gør',
    'privacy.noneBody':'Ingen reklamer. Ingen analyse eller sporing fra tredjeparter. Ingen konto, mailadresse eller adgangskode. Ingen placering, kontakter, kamera eller mikrofon. Ingen cookies.',
    'privacy.keep':'Opbevaring og sletning',
    'privacy.keepBody':'Det, der ligger på denne enhed, bliver, indtil du sletter det; vi gemmer ingen kopi andre steder. Vores server gemmer den lyd, der er lavet (spilsætninger, ingen personlige oplysninger), så den samme sætning ikke skal laves to gange, og holder kort en forespørgsels IP-adresse i hukommelsen for at forhindre misbrug.',
    'privacy.erase':'Slet alle data',
    'privacy.eraseSub':'Navn, indstillinger og fremgang på denne enhed',
    'privacy.eraseTitle':'Slet det hele?',
    'privacy.eraseBody':'Navn, indstillinger, fremgang, kort og tal forsvinder fra denne enhed. Et købt Premium bliver på din App Store-konto og kommer tilbage med “Gendan køb”.',
    'privacy.eraseConfirm':'Ja, slet det hele',
    'privacy.contact':'Spørgsmål om privatliv?',
    'privacy.contactSub':'Skriv til {email}',
    'privacy.noAccount':'Kwizillo virker uden konto: der er ikke noget hos os at oprette eller slette.',
    'score.points':'point',
    'score.practice':'øvepoint',
    'score.dayFull':'dagens maksimum nået',
    'score.title':'Rekorder',
    'score.sub':'Dine bedste point i hver periode',
    'score.now':'nu',
    'score.best':'rekord',
    'score.run':'Denne øvelse',
    'score.day':'I dag',
    'score.week':'Denne uge',
    'score.month':'Denne måned',
    'score.year':'I år',
    'score.allTime':'Gennem tiden',
    'score.todayPoints':'{n} af {max} point i dag',
    'score.todayCoins':'{n} af {max} mønter i dag',
    'score.capNote':'Hver dag er der et maksimum af point og mønter, og et spørgsmål, du allerede har haft rigtigt, giver øvepoint. Sådan er en rekord stadig noget værd.',
    'shop.tab':'🛒 Butik',
    'shop.title':'Butik',
    'shop.sub':'Betal med mønter fra spillene',
    'shop.buy':'Køb',
    'shop.owned':'Ejet','shop.earned':'Optjent',
    'shop.price':'{n} mønter',
    'shop.need':'Du mangler {n} mønter',
    'shop.confirmTitle':'Købe {item}?',
    'shop.confirmBody':'Det koster {n} mønter. Derefter er {item} din for altid.',
    'shop.bought':'{item} er din!',
    'shop.cards':'Guldkort',
    'shop.mascots':'Venner',
    'shop.goldCard':'Gyldne {world}',
    'shop.goldCardSub':'Et skinnende kort til din samling',
    'shop.earnHint':'Mønter tjener du i Runner og de andre spil.',
    'shop.empty':'Alt er købt! Butikken er helt tom.',
    'result.worldLevelUp':'🎉 {world} rykker op til niveau {niveau}!',
    'result.worldMastered':'🏆 {world} klaret på alle niveauer!',
    'result.goldCardEarned':'Du har optjent det gyldne {world}-kort!',
    'result.goldCardSpeech':'Wow! Du har klaret hele {world}. Det gyldne kort er dit!',
    'settings.levelWorlds':'Niveau pr. verden',
    'settings.levelWorldsSub':'En verden rykker op af sig selv, når du klarer alle fire quizzer der.',
    'settings.levelMath':'Spilniveau',
    'settings.timeLimitPerWorld':'Tiden per spørgsmål følger niveauet.',
    'settings.reset':'Nulstil fremgang',
    'settings.resetSub':'Begynd helt forfra',
    'settings.resetTitle':'Nulstil fremgang?',
    'settings.resetBody':'XP, mønter, kort, tal og fremgang går tilbage til start.',
    'settings.resetConfirm':'Ja, nulstil',
    'gate.title':'Et lille spørgsmål til en voksen',
    'gate.body':'Hvad er {a} × {b}?',
    'gate.placeholder':'Svar',
    'gate.wrong':'Det er ikke rigtigt. Prøv igen.',
    'gate.continue':'Videre',

    'sound.kicker':'INDSTILLINGER',
    'sound.title':'🔊 Lyd og musik',
    'sound.fx':'✨ Lydeffekter',
    'sound.music':'🎵 Baggrundsmusik',
    'sound.test':'Test',
    'sound.pickMusic':'Vælg din musik',
    'sound.voiceGuide':'Stemmeguide',
    'track.home':'Øer',
    'track.space':'Rummet',
    'track.jungle':'Jungle',
    'track.earth':'Jorden',
    'track.history':'Historie',
    'track.science':'Videnskab',
    'track.mystery':'Mysterie',
    'track.play':'Spil',

    'intro.skip':'Spring introen over',
    'welcome.back.title':'Hej {name}!',
    'welcome.back.sub':'Klar til at spille videre?',
    'welcome.back.continue':'Spil videre',
    'welcome.back.other':'En anden spiller',
    'welcome.back.where':'Her slap du',
    'welcome.pick.title':'Hvem spiller?',
    'welcome.pick.new':'Ny spiller',
    'welcome.pick.back':'Tilbage',
    'intro.tapToStart':'Tryk for at starte',
    'intro.tapForSound':'Tryk for lyd'
  };
})();
