(()=>{
  // Russian UI strings. Same keys and the same layout as every other language;
  // the child is addressed with "ты" throughout.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.ru={
    'lang.name':'Русский',
    'lang.speech':'ru',

    'world.ruimte.title':'Мир космоса',
    'world.ruimte.sub':'Путешествуй мимо планет, звёзд и ракет',
    'world.dieren.title':'Мир животных',
    'world.dieren.sub':'Открывай животных на суше, в джунглях и в море',
    'world.aarde.title':'Мир Земли',
    'world.aarde.sub':'Исследуй страны, океаны, погоду и карты',
    'world.geschiedenis.title':'Мир истории',
    'world.geschiedenis.sub':'Шагни во времена фараонов, рыцарей и путешественников',
    'world.wetenschap.title':'Мир науки',
    'world.wetenschap.sub':'Пробуй, открывай и понимай, как всё устроено',
    'world.mysterie.title':'Мир тайн',
    'world.mysterie.sub':'Разгадывай загадки и иди по хитрым следам',
    'world.kunst.title':'Мир искусства',
    'world.kunst.sub':'Открой картины, музыку и великие здания',
    'world.sport.title':'Мир спорта',
    'world.sport.sub':'Беги, прыгай и плыви с лучшими спортсменами',

    'topic.zonnestelsel':'Солнечная система',
    'topic.sterren_planeten':'Звёзды и планеты',
    'topic.astronauten':'Космонавты',
    'topic.raket_avontuur':'Приключение на ракете',
    'topic.egyptenaren':'Египтяне',
    'topic.ridders_kastelen':'Рыцари и замки',
    'topic.romeinen':'Римляне',
    'topic.ontdekkingsreizigers':'Путешественники',
    'topic.slimme_proefjes':'Умные опыты',
    'topic.lichaam':'Тело человека',
    'topic.uitvindingen':'Изобретения',
    'topic.natuur_energie':'Природа и энергия',
    'topic.raadsels':'Загадки',
    'topic.verborgen_schatten':'Спрятанные клады',
    'topic.natuurmysteries':'Тайны природы',
    'topic.speurtocht':'Большой поиск',
    'topic.snelle_dieren':'Быстрые животные',
    'topic.baby_dieren':'Детёныши',
    'topic.waterdieren':'Животные в воде',
    'topic.jungle':'Приключение в джунглях',
    'topic.continenten_landen':'Страны и материки',
    'topic.weer_klimaat':'Погода и климат',
    'topic.oceanen_natuur':'Океаны и природа',
    'topic.kaarten_navigatie':'Карты и навигация',
    'topic.schilderkunst':'Живопись',
    'topic.muziek':'Музыка',
    'topic.bouwkunst':'Архитектура',
    'topic.dans_theater':'Танец и театр',
    'topic.balsporten':'Игры с мячом',
    'topic.olympische_spelen':'Олимпийские игры',
    'topic.water_wintersport':'Вода и зимний спорт',
    'topic.records_helden':'Рекорды и герои',

    'nav.home':'Домой',
    'nav.achievements':'Награды',
    'nav.collection':'Коллекция',
    'nav.stats':'Успехи',
    'nav.more':'Ещё',
    'nav.aria':'Главное меню',
    'nav.collectionLong':'Моя коллекция',
    'nav.moreLong':'Ещё / Зона родителей',

    'common.back':'Назад',
    'common.settings':'Настройки',
    'common.close':'Закрыть',
    'common.cancel':'Отмена',
    'common.gotIt':'Понятно',
    'common.brand':'KWIZILLO',
    'common.of':'из',
    // Кто я?
    'whoami.title':'Кто я?','whoami.round':'Раунд {n} из {total}','whoami.points':'Уже {n} очков','whoami.ask':'Кто я?','whoami.more':'Подсказка','whoami.next':'Дальше','whoami.timeUp':'Время вышло! Это был {answer}.',
    'whoami.yes':'Да, {answer}! +{points}','whoami.almost':'Почти! Это был {answer}.',
    'whoami.speech.yes':'Да, это {answer}!','whoami.speech.almost':'Почти! Это был {answer}.',
    'whoami.doneKicker':'КТО Я?','whoami.doneTitle':'Угадано {n} из {total}!','whoami.summary':'{score} очков из {max}. Чем раньше угадаешь, тем больше очков.',
    'whoami.speech.great':'Ух ты, как быстро ты угадываешь! Молодец.','whoami.speech.done':'Хорошая игра! В следующий раз угадаешь ещё больше.',
    'jungle.title':'Раннер','jungle.tileSub':'Беги, прыгай и лети через три уровня','jungle.loadError':'Джунгли не загрузились. Попробуй позже.',
    'fotozoom.title':'Фотозум','fotozoom.round':'Раунд {n} из {total}','fotozoom.points':'Уже {n} очков','fotozoom.ask':'Что это может быть?','fotozoom.out':'Отдалить','fotozoom.next':'Дальше','fotozoom.timeUp':'Время вышло! Это был {answer}.',
    'fotozoom.yes':'Да, {answer}! +{points}','fotozoom.almost':'Почти! Это был {answer}.',
    'fotozoom.speech.yes':'Да, это {answer}!','fotozoom.speech.almost':'Почти! Это был {answer}.',
    'fotozoom.doneKicker':'ФОТОЗУМ','fotozoom.doneTitle':'Узнано {n} из {total}!','fotozoom.summary':'{score} очков из {max}. Чем меньше отдаляешь, тем больше очков.',
    'fotozoom.speech.great':'Какой у тебя острый глаз! Молодец.','fotozoom.speech.done':'Хорошо смотришь! В следующий раз узнаешь ещё больше.',
    'premium.teaser.fotozoom':'Фотозум в этом мире входит в Kwizillo Premium. Попроси взрослого открыть все миры.',
    'jungle.brand':'KWIZILLO RUNNER','jungle.eyebrow':'KWIZILLO • АРКАДА','jungle.titleA':'Kwizillo','jungle.titleB':'Раннер','jungle.back':'Назад в Kwizillo','jungle.backShort':'Назад','jungle.easyShort':'Спокойный забег',
    'jungle.levelLabel':'ВЫБЕРИ УРОВЕНЬ','jungle.heroLabel':'КТО БЕЖИТ С ТОБОЙ?','jungle.heroBoy':'Мальчик','jungle.heroGirl':'Девочка','jungle.glideOn':'Лети!','jungle.glideOff':'Беги!','jungle.levelJungle':'Джунгли','jungle.levelStad':'Город','jungle.levelLucht':'Небо',
    'jungle.swingOn':'Раскачивайся!','jungle.swingOff':'Беги!','jungle.powerSpeed':'⚡ {n}с','jungle.popSpeed':'ТУРБО!','jungle.popSpeedSub':'7 секунд суперскорости · двойные монеты','jungle.labelSpeed':'ТУРБО!',
    'jungle.canvasLabel':'Игровое поле. Стрелки влево и вправо — управление. Пробел — прыжок.','jungle.pause':'Пауза','jungle.sound':'Звук включён или выключен','jungle.controls':'Управление игрой','jungle.left':'Влево','jungle.right':'Вправо','jungle.jump':'Сальто ↑',
    'jungle.loading':'Готовим твоё приключение…','jungle.loadErrorTitle':'Попробуй снова','jungle.loadErrorBody':'Картинки джунглей не загрузились. Проверь связь и попробуй снова.',
    'jungle.intro':'Иди по золотому следу.<br>Прыгай, исследуй и собирай!','jungle.legendMagnet':'🧲 Магнит','jungle.legendShield':'🛡 Щит','jungle.legendGold':'★ Золото +5','jungle.legendDouble':'×2 Бонусная звезда',
    'jungle.easy':'Спокойный забег · прыгает сам','jungle.music':'Музыка','jungle.on':'включена','jungle.off':'выключена','jungle.start':'В приключение →',
    'jungle.help':'{n} секунд • Проводи пальцем или жми кнопки<br>10 монет подряд = +5 бонуса<br>Собирай бонусы и найди карточку','jungle.countFollow':'Иди за монетами!','jungle.countReady':'Готов к приключению?',
    'jungle.pauseEyebrow':'ПЕРЕВЕДИ ДУХ','jungle.pauseTitle':'Твои джунгли<br>ждут.','jungle.pauseBody':'Время остановилось.','jungle.resume':'Играть дальше →','jungle.exit':'Уйти без награды',
    'jungle.hit':'Ой! Тебя остановило — беги дальше.','jungle.hitLost':'Ай! Столкновение — минус {n} монет.','jungle.labelHit':'−{n}','jungle.lostCoins':'Потеряно монет','jungle.cardFound':'Ты нашёл карточку джунглей!','jungle.powerDouble':'×2 {n}с','jungle.powerMagnet':'🧲 {n}с','jungle.powerShield':'🛡 Под защитой','jungle.powerStreak':'★ {n} подряд',
    'jungle.popDouble':'БОНУСНАЯ ЗВЕЗДА!','jungle.popDoubleSub':'6 секунд двойных монет','jungle.popGold':'НАЙДЕНО ЗОЛОТО!','jungle.popGoldSub':'+{n} монет','jungle.popCombo':'{n} ПОДРЯД!','jungle.popComboSub':'+5 за комбо','jungle.popMagnet':'МАГНИТ ДЛЯ МОНЕТ!','jungle.popMagnetSub':'7 секунд притягивает монеты',
    'jungle.popShield':'ЩИТ!','jungle.popShieldSub':'Примет один удар за тебя','jungle.popBlock':'ЩИТ ТЕБЯ СПАС!','jungle.popBlockSub':'Беги дальше','jungle.popCard':'НАЙДЕНА КАРТОЧКА!','jungle.popCardSub':'Покажем на финише','jungle.popClear':'ОТЛИЧНЫЙ ПРЫЖОК!','jungle.popClearSub':'Через бревно','jungle.popDoubleflip':'ДВОЙНОЕ САЛЬТО!','jungle.popDoubleflipSub':'+3 монеты',
    'jungle.labelGold':'+{n} ЗОЛОТА!','jungle.labelCombo':'КОМБО +5','jungle.labelCard':'Карточка найдена!','jungle.labelClear':'Отличный прыжок!','jungle.labelMagnet':'МАГНИТ!','jungle.labelShield':'ЩИТ!','jungle.labelBlock':'Спасён!','jungle.labelDouble':'ДВОЙНЫЕ МОНЕТЫ!',
    'jungle.saving':'Сохраняем твою награду…','jungle.saved':'Твои монеты добавлены.','jungle.saveError':'Сохранить пока не получилось. Попробуй снова.',
    'jungle.finishEyebrow':'ПРИКЛЮЧЕНИЕ ЗАВЕРШЕНО','jungle.finish':'ФИНИШ!','jungle.finishSub':'Твоя добыча за этот забег','jungle.coinsEarned':'монет заработано','jungle.bestStreak':'Лучшая серия','jungle.bonusCoins':'Бонусные монеты',
    'jungle.cardAlt':'Собранная карточка','jungle.cardEyebrow':'КАРТОЧКА НАЙДЕНА','jungle.cardSub':'Для твоей коллекции Kwizillo','jungle.cardTitle':'Лист джунглей','card.jungle-leaf':'Лист джунглей','card.city-star':'Звезда города','card.sky-feather':'Небесное перо','jungle.retry':'Сохранить ещё раз','jungle.take':'Забрать добычу','jungle.again':'Другое приключение','jungle.replay':'Это ещё раз',
    // Premium
    'common.ok':'ОК','common.retry':'Попробуй снова',
    'premium.label':'Premium','premium.name':'Kwizillo Premium','premium.kicker':'ДЛЯ РОДИТЕЛЕЙ',
    'premium.title':'Открой весь мир Kwizillo',
    'premium.subtitle':'Играть, учиться, собирать и открывать без границ.',
    'premium.benefit.worlds':'Все миры','premium.benefit.questions':'480+ вопросов о мире','premium.benefit.math':'Игры со счётом','premium.benefit.memo':'Игры на память','premium.benefit.facts':'Интересные факты','premium.benefit.guides':'Мило и Луна','premium.benefit.collect':'Собирай карточки и маскотов','premium.benefit.stats':'Полный прогресс и статистика','premium.benefit.new':'Новые приключения и материалы',
    'premium.monthly':'Помесячно','premium.yearly':'На год','premium.perMonth':'месяц','premium.perYear':'год',
    'premium.best':'Лучшая цена','premium.trial':'Попробуй {days} дней бесплатно','premium.ctaTrial':'Начать {days} бесплатных дней','premium.ctaYearly':'Выбрать на год','premium.ctaMonthly':'Выбрать помесячно',
    'premium.perMonthCalc':'Это {price} в месяц',
    'premium.legal':'Подписка оплачивается через твой аккаунт Apple и продлевается сама, пока её не отменят. Её можно изменить или отменить в любой момент в подписках Apple. Бесплатный период переходит в платную подписку, если не отменить её до конца периода.',
    'premium.restore':'Восстановить покупки','premium.restoreSub':'Вернуть Premium на это устройство','premium.manage':'Управлять подпиской','premium.manageSub':'Отменить или изменить через Apple','premium.privacy':'Конфиденциальность','premium.terms':'Условия использования',
    'premium.loading':'Загружаем цены…','premium.purchasing':'Минутку, Apple оформляет покупку…',
    'premium.pending':'Покупка ждёт подтверждения. Как только оно придёт, Premium включится сам.',
    'premium.cancelled':'Покупка отменена.','premium.failed':'Не получилось. Попробуй позже.',
    'premium.unavailable':'Premium сейчас недоступен. Попробуй позже.',
    'premium.already':'Premium уже активен на этом устройстве.',
    'premium.restoring':'Восстанавливаем покупки…','premium.restoreNone':'Прошлых покупок не найдено.','premium.manageUnavailable':'Управляй подписками в настройках телефона, в разделе аккаунта Apple.',
    'premium.welcome':'Добро пожаловать в Kwizillo Premium!','premium.welcomeSub':'Все миры, игры и факты открыты. Хорошей игры!','premium.continue':'Продолжить с того же места','premium.play':'Играть',
    'premium.statusFree':'Бесплатная версия · открыть всё','premium.statusActive':'Активно · {type}','premium.statusTrial':'Бесплатный период · {type}','premium.statusExpired':'Срок вышел · прогресс сохранён','premium.renews':'Продлится',
    'premium.teaserTitle':'Это Premium','premium.askParent':'Спроси взрослого',
    'premium.teaser.quiz':'Эта викторина входит в Kwizillo Premium. Попроси взрослого открыть все миры.',
    'premium.teaser.memo':'Эта игра на память входит в Kwizillo Premium. Попроси взрослого открыть все поля.',
    'premium.teaser.math':'Высокие уровни счёта входят в Kwizillo Premium. Попроси взрослого открыть их.',
    'premium.teaser.facts':'Другие факты входят в Kwizillo Premium. Попроси взрослого открыть их все.',
    'premium.factsMore':'Ещё {n} фактов с Premium',
    'premium.teaser.whoami':'«Кто я?» в этом мире входит в Kwizillo Premium. Попроси взрослого открыть все миры.',
    'settings.terms':'Условия использования','settings.termsBody':'Kwizillo — обучающая игра для детей. Premium — это подписка, которая оплачивается через Apple и продлевается сама, пока её не отменят; отменить её можно в любой момент в подписках Apple. Внутри самой игры нет ни рекламы, ни покупок.',

    'onboarding.language.title':'Выбери свой язык',
    'onboarding.language.sub':'На каком языке ты хочешь играть?',
    'onboarding.name.title':'Как тебя зовут?',
    'onboarding.name.sub':'Чтобы мы могли тебя правильно поприветствовать.',
    'onboarding.name.placeholder':'Твоё имя',
    'onboarding.name.hint':'Твоё имя остаётся на этом устройстве.',
    'onboarding.voice.title':'Кто тебе поможет?',
    'onboarding.voice.sub':'Выбери проводника. Его всегда можно поменять.',
    'onboarding.welcome.title':'Добро пожаловать, {name}!',
    'onboarding.welcome.sub':'Твоё приключение начинается. Готов исследовать?',
    'onboarding.welcome.cta':'Начать приключение',
    'onboarding.next':'Дальше',
    'onboarding.speech.welcome':'Да, всё готово! Пойдём, я быстро покажу, что где находится.',
    'onboarding.speech.language':'Привет! Я Мило. На каком языке ты говоришь?',
    'onboarding.speech.name':'Очень приятно! Как тебя зовут? Просто напиши это.',
    'onboarding.speech.age':'А сколько тебе лет?',
    'onboarding.speech.group':'В каком ты классе?',
    'onboarding.speech.voice':'Кого хочешь в проводники? Меня, Луну или лучше тишину?',
    'onboarding.age.title':'Сколько тебе лет?',
    'onboarding.age.sub':'Нажми на свой возраст.',
    'onboarding.age.years':'{n} лет',
    'onboarding.group.title':'В каком ты классе?',
    'onboarding.group.sub':'Чтобы я выбрал вопросы, которые тебе подойдут.',
    'tour.worlds':'Это миры Kwizillo. Нажми на мир и сыграй викторину!',
    'tour.games':'А здесь шесть игр. Нажми на любую и попробуй!',
    'tour.facts':'А это Интересные факты: сотни весёлых вещей, которые можно открыть!',
    'tour.hud':'Сверху — твой уровень, монеты и дни подряд. Шестерёнка для взрослых.',
    'tour.nav':'Внизу — твоя коллекция, достижения и статистика. В разделе «Ещё» настройки.',
    'tour.done':'Хорошей игры! Я помогу, как только ты застрянешь.',
    'tour.skip':'Пропустить',
    'tour.again':'Экскурсия с {guide}',
    'tour.againSub':'{guide} ещё раз покажет, что где находится.',

    'voice.milo':'Мило',
    'voice.milo.desc':'Весёлый и бодрый',
    'voice.luna':'Луна',
    'voice.luna.desc':'Спокойная и добрая',
    'voice.silent':'Тишина',
    'voice.silent.desc':'Без голоса',
    'voice.milo.hello':'Привет! Я Мило. Готов играть?',
    'voice.luna.hello':'Привет! Я Луна. Будем исследовать вместе?',

    'home.greeting':'Привет, {name}!',
    'home.greetingAnon':'Привет!',
    'home.level':'Уровень {level}',
    'home.coins':'KwizCoins',
    'home.streak':'Дней подряд',
    'home.pickWorld':'Выбери свой мир',
    'home.cta':'Начать приключение',
    'home.ctaSub':'Продолжить в мире «{world}»',
    'home.voiceLabel':'Голос',
    'home.languageLabel':'Язык',

    'world.kicker':'МИР KWIZILLO',
    'world.backHome':'На главную',
    'world.mix':'Начать смешанную викторину',
    'world.mixSub':'Вопросы из всех четырёх тем',
    'world.quizNumber':'Викторина {n}',
    'world.topicPassed':'Пройдено',
    'world.topicPlayed':'Сыграно викторин: {n} · {correct}/{answered} верно',
    'world.progressLine':'Пройдено тем: {passed} из {total}',
    'world.worldProgress':'Пройдено {done} из {total} викторин этого мира',
    'world.mixDone':'сыграно: {n}',

    'quiz.mixed':'Смешанная викторина',
    'quiz.progress':'Вопрос {current} из {total}',
    'quiz.hint':'Подсказка',
    'quiz.none':'Для этой темы пока нет вопросов.',
    'quiz.artAlt':'Картинка к вопросу',
    'quiz.quizLabel':'Викторина {n}',
    'quiz.back':'Назад',
    'quiz.explain':'Объяснить',
    'quiz.timerAria':'Осталось секунд',
    'feedback.timeKicker':'ВРЕМЯ ВЫШЛО!',
    'feedback.timeTitle':'В следующий раз быстрее!',
    'settings.level':'Уровень',
    'settings.levelSub':'{seconds} с на вопрос · не больше {allowed} ошибок · {hints}',
    'settings.hintsFree':'подсказки без ограничений',
    'settings.hintsN':'{n} подсказок',
    'settings.hintsNone':'без подсказок',
    'settings.readsQuestionOnly':'вслух читается только вопрос',
    'quiz.hintsSpent':'В этой викторине подсказок больше нет.',
    'quiz.noHints':'На шестом уровне подсказок нет.',
    'world.speech.enter':'[excited] {title}!',
    'settings.levelAuto':'Авто',
    'settings.share':'Поделись результатом',
    'settings.shareSub':'Отправь свой результат семье или друзьям',

    'hint.title':'Маленькая подсказка',
    'hint.kicker':'Совет по теме «{topic}»',
    'hint.ok':'Думать дальше',
    'hint.close':'Закрыть подсказку',
    'hint.fallback':'Посмотри ещё раз внимательно на вопрос и картинку.',
    'hint.alt':'Подсказка на картинке',

    'feedback.goodKicker':'ВЕРНО!',
    'feedback.tryKicker':'ТАК БЛИЗКО!',
    'feedback.goodTitle':'Отличная игра!',
    'feedback.tryTitle':'Хорошо подумал!',
    'feedback.correctIs':'Правильный ответ — <strong>{answer}</strong>.',
    'feedback.thatsRight':'Это верно!',
    'feedback.didYouKnow':'А ты знал?',
    'feedback.next':'Следующий вопрос',
    'feedback.seeResult':'Посмотреть результат',
    'feedback.speech.good':'Молодец.',
    'feedback.speech.good.1':'Молодец!',
    'feedback.speech.good.2':'Класс, это верно!',
    'feedback.speech.good.3':'Точно в цель!',
    'feedback.speech.good.4':'Очень хорошо!',
    'feedback.speech.good.5':'Да! Именно так!',
    'feedback.speech.good.6':'Здорово, хорошо заметил!',
    'feedback.speech.good.7':'Великолепно!',
    'feedback.speech.good.8':'Ух ты, это правильно!',
    'feedback.speech.try.1':'Почти. Правильный ответ — {answer}.',
    'feedback.speech.try.2':'Не совсем. Правильный ответ — {answer}.',
    'feedback.speech.try.3':'Хорошая попытка! Правильный ответ — {answer}.',
    'feedback.speech.try.4':'Ой, так близко. Правильный ответ — {answer}.',
    'feedback.answerLabel':'Правильный ответ',
    'feedback.close':'Закрыть',
    'feedback.listening':'Слушаю…',
    'quiz.repeat':'Ещё раз',
    'quiz.repeatAria':'Прочитать вопрос ещё раз',
    'feedback.speech.try':'Почти. Правильный ответ — {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'ВИКТОРИНА ОКОНЧЕНА',
    'result.title':'{score} из {total} правильно!',
    'result.score':'счёт',
    'result.xp':'XP',
    'result.coins':'монет',
    'result.again':'Ещё викторина',
    'result.againNumbered':'Начать викторину {n}',
    'result.nextTopic':'Дальше: {topic}',
    'result.finishWorld':'Начать смешанную викторину',
    'result.retryTopic':'Пройти эту тему ещё раз',
    'result.retryNow':'Попробовать снова',
    'memo.title':'Мемо',
    'memo.pickTitle':'Выбери свой мир',
    'game.mixAll':'Микс всех миров',
    'game.pickSub':'Выбери один мир или играй во все сразу.',
    'memo.pickSub':'Найди пары · Уровень {n}',
    'memo.otherWorld':'Другой мир',
    'memo.sub':'Найди пары',
    'memo.play':'Играть в Мемо',
    'memo.playSub':'Найди пары мира «{world}»',
    'memo.level':'Уровень {n}',
    'memo.pairs':'{found} из {total} пар',
    'memo.moves':'{n} ходов',
    'memo.movesShort':'ходов',
    'memo.card':'Карточка мемо',
    'memo.hintLine':'Переворачивай две карточки и находи пары',
    'memo.none':'Для этого мира пока не хватает карточек.',
    'memo.doneKicker':'МЕМО ПРОЙДЕНО!',
    'memo.doneTitle':'Все пары найдены!',
    'memo.timeKicker':'ВРЕМЯ ВЫШЛО!',
    'memo.timeTitle':'Почти все пары!',
    'memo.summary':'{pairs} пар за {moves} ходов и {secs} секунд.',
    'memo.summaryTime':'Найдено {found} пар из {pairs}. Попробуй ещё раз!',
    'memo.again':'Ещё раз',
    'memo.retry':'Попробовать снова',
    'memo.toWorld':'Назад в мир',
    'memo.speech.done':'Ух ты, ты нашёл все пары! Какая память!',
    'memo.speech.time':'Время вышло. В следующий раз найдёшь все!',
    'memo.modeTitle':'Как будешь играть?',
    'memo.solo':'Один','memo.soloSub':'На время',
    'memo.duel':'Друг против друга','memo.duelSub':'По очереди: кто найдёт больше пар?',
    'memo.player1':'Игрок 1','memo.player2':'Игрок 2','memo.p2Label':'Кто играет с тобой?',
    'memo.turn':'Ход игрока {name}',
    'memo.duelKicker':'ДУЭЛЬ МЕМО',
    'memo.duelWin':'Побеждает {name}!','memo.duelTie':'Ничья!',
    'memo.duelSummary':'{pairs} пар за {moves} ходов.',
    'memo.rematch':'Реванш',
    'memo.speech.win':'У нас есть победитель! Вы оба молодцы!',
    'memo.speech.tie':'Ничья! У вас обоих отличная память!',
    'home.playMore':'Играть ещё',
    'math.title':'Счёт',
    'facts.title':'Интересные факты',
    'world.ruimte.short':'Космос','world.dieren.short':'Животные','world.aarde.short':'Земля','world.geschiedenis.short':'История','world.wetenschap.short':'Наука','world.kunst.short':'Искусство','world.sport.short':'Спорт','world.mysterie.short':'Тайны',
    'facts.tileSub':'А ты знал, что…',
    'facts.sub':'Открыто {seen} из {total}',
    'facts.next':'Следующий факт',
    'facts.listen':'Прочитать вслух',
    'facts.kicker':'А ты знал, что…',
    'facts.new':'Новое!',
    'facts.allSeen':'Ты открыл все факты! Теперь они пойдут по второму кругу.',
    'facts.more':'Ещё факты',
    'math.sub':'Быстрые примеры',
    'math.play':'Счёт',
    'math.playSub':'Десять примеров · Уровень {n}',
    'math.progress':'Пример {current} из {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'{score} из {total} примеров решено верно!',
    'math.again':'Ещё десять примеров',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'плюс',
    'math.op.minus':'минус',
    'math.op.times':'умножить на',
    'math.op.divided':'разделить на',
    'math.speech.twoStep':'{c} плюс {a} умножить на {b}',
    'math.speech.half':'Половина от {n}',
    'math.speech.quarter':'Четверть от {n}',
    'math.speech.percent':'{p} процентов от {n}',
    'math.speech.wrong':'Почти. Это {answer}.',
    'math.speech.done':'Отличный счёт! Все примеры решены.',
    'math.speech.fail':'Хорошая попытка. Ещё раз — и получится!',
    'math.hint.plus':'Считай дальше от {a}: прибавь {b}.',
    'math.hint.minus':'Начни с {a} и отсчитай {b} назад.',
    'math.hint.times':'{a} умножить на {b}: сложи {b} ровно {a} раз.',
    'math.hint.divided':'Сколько раз {b} помещается в {a}?',
    'math.hint.generic':'Считай шаг за шагом.',
    'achievement.math3':'3 раунда счёта пройдено',
    'stats.mathLine':'Сыграно раундов: {played} · пройдено: {won}',
    'result.passKicker':'ПРОЙДЕНО!',
    'result.failKicker':'ПОКА НЕТ',
    'result.passRule':'Уровень {niveau}: можно было ошибиться {allowed} раз, а ты ошибся {wrong}.',
    'result.failRule':'Уровень {niveau}: можно ошибиться {allowed} раз, а ты ошибся {wrong}. Сыграй эту тему ещё раз!',
    'result.toCollection':'В мою коллекцию',

    'profile.title':'Мой профиль',
    'profile.sub':'Твоё имя, твой друг и твои настройки',
    'profile.saveName':'Сохранить имя',
    'profile.saved':'Сохранено!',
    'profile.buddy':'Мой друг',
    'profile.chooseBuddy':'Выбрать друга',
    'profile.voice':'Кто читает вслух?',
    'achievements.title':'Награды',
    'achievements.sub':'Твои приключения и достижения',
    'achievements.summary':'Получено {done}/{total}',
    'achievements.summarySub':'Исследуй дальше, чтобы открыть новые награды.',
    'achievements.done':'Получено!',
    'achievement.firstQuiz':'Первая викторина',
    'achievement.correct10':'10 правильных ответов',
    'achievement.correct50':'50 правильных ответов',
    'achievement.streak7':'7 дней подряд',
    'achievement.cards5':'5 карточек знаний',
    'achievement.allWorlds':'Все миры посещены',
    'achievement.memo3':'3 победы в мемо',

    'collection.title':'Моя коллекция',
    'collection.sub':'Всё, что ты открыл',
    'collection.tabWorlds':'🌍 Миры',
    'collection.tabCards':'🃏 Карточки',
    'collection.tabMascots':'🐾 Друзья',
    'collection.worldStat':'{correct}/{answered} верно · {pct}%',
    'progress.worldLine':'Пройдено викторин: {passed} из {total} · {points} очков',
    'progress.overall':'Всего {points} из {max} очков',
    'progress.overallSub':'Каждая пройденная викторина стоит 25 очков: целый мир — это 100.',
    'collection.discovered':'★ Открыто',
    'collection.unlockKicker':'НОВЫЙ ДРУГ!',
    'collection.unlockLine':'Открыт за {n} правильных ответов.',
    'score.coinsAdded':'+{n} монет зачислено',
    'score.coinsCapped':'Дневной максимум достигнут: зачислено {n} из {got} монет.','collection.cardAdded':'«{title}» теперь в твоей коллекции!',
    'collection.emptyTitle':'Карточек пока нет',
    'collection.emptyBody':'Отвечай на вопросы правильно, чтобы собирать карточки знаний.',
    'collection.mascotLocked':'ещё {n} правильных ответов',
    'collection.mascotActive':'Активен ✓',
    'collection.mascotChoose':'Выбрать друга',
    'collection.mascotCount':'Открыто друзей: {unlocked}/{total}',

    'mascot.milo':'Мило',
    'mascot.milo.desc':'Твой умный друг-робот',
    'mascot.comet':'Комета',
    'mascot.comet.desc':'Друг из космоса',
    'mascot.pootje':'Лапка',
    'mascot.pootje.desc':'Друг животных',
    'mascot.terra':'Терра',
    'mascot.terra.desc':'Защитница Земли',
    'mascot.sparky':'Спарки',
    'mascot.sparky.desc':'Любитель опытов',
    'mascot.lumi':'Луми',
    'mascot.lumi.desc':'Искательница тайн',
    'mascot.nova':'Нова','mascot.nova.desc':'Путешественница по звёздам',
    'mascot.kiko':'Кико','mascot.kiko.desc':'Исследователь джунглей',
    'mascot.pip':'Пип','mascot.pip.desc':'Ледяной смельчак',
    'mascot.ravi':'Рави','mascot.ravi.desc':'Будущий изобретатель',
    'mascot.flora':'Флора','mascot.flora.desc':'Подруга природы',
    'mascot.draco':'Драко','mascot.draco.desc':'Маленький дракон из замка',

    'stats.title':'Успехи',
    'stats.sub':'Настоящий прогресс по сыгранным вопросам',
    'stats.heroTitle':'Твои знания растут',
    'stats.heroSub':'Отвечено вопросов: {answered} · сыграно {quizzes} {quizWord}',
    'stats.correctShort':'верно',
    'stats.xpTotal':'Всего XP',
    'stats.coins':'KwizCoins',
    'stats.streak':'Дней подряд',
    'stats.cards':'Карточки',
    'stats.perWorld':'По мирам',
    'stats.games':'Игры',
    'stats.runnerLine':'{played} забегов · собрано монет: {coins}',
    'stats.memoBest':'{n} ходов',
    'stats.memoLine':'Сыграно игр мемо: {played} · выиграно: {won}',
    'share.text':'{name} играет в Kwizillo! Уровень {level}, {correct} правильных ответов, {cards} карточек знаний. Лучшая викторина: {best}. Хочешь тоже поиграть?',
    'share.copied':'Текст скопирован — вставь его в сообщение.',
    'result.share':'Поделись результатом',
    'stats.worldLine':'{correct} из {answered} верно · {quizzes} {quizWord}',
    'stats.quizOne':'викторина',
    'stats.quizMany':'викторин',

    'settings.title':'Зона родителей',
    'settings.sub':'Настройки для хорошей игры',
    'settings.group':'Класс',
    'settings.groupSub':'Настрой сложность',
    'settings.groupValue':'{n}-й класс',
    'settings.language':'Язык',
    'settings.languageSub':'Выбери язык игры',
    'settings.sound':'Звук, музыка и голос',
    'settings.soundVoiceOff':'Голос выключен',
    'settings.soundVoiceOn':'Голос: {voice}',
    'settings.soundMusic':'музыка {state}',
    'settings.on':'включена',
    'settings.off':'выключена',
    'settings.timeLimit':'Таймер вопроса',
    'settings.timeLimitOff':'Выключен',
    'settings.timeLimitValue':'{n} секунд на вопрос на этом уровне',
    'settings.privacy':'Приватность и безопасность',
    'privacy.sub':'Что игра хранит и чего она не делает',
    'privacy.updated':'Обновлено: {date}',
    'privacy.device':'На этом устройстве',
    'privacy.deviceBody':'Это лежит в памяти приложения на этом устройстве. Ничего не уходит ни в Kwizillo, ни кому-то ещё, и всё исчезает, как только вы удалите приложение или сотрёте всё ниже.',
    'privacy.itemName':'Имя: {value}',
    'privacy.itemSettings':'Язык, голос, звук, класс и уровень',
    'privacy.itemProgress':'Успехи: вопросов {answered}, верных {correct}, карточек {cards}',
    'privacy.itemPremium':'Активен ли Premium (это приходит из App Store)',
    'privacy.leaves':'Что покидает устройство',
    'privacy.leavesBody':'Только та фраза, которую вслух читает Мило или Луна. Она идёт на наш собственный сервер, а оттуда в речевой сервис ElevenLabs. Это всегда текст из игры: вопрос, ответ, подсказка или факт. Никогда имя ребёнка и никогда то, что ребёнок набрал сам.',
    'privacy.none':'Чего приложение не делает',
    'privacy.noneBody':'Никакой рекламы. Никакой чужой аналитики и трекеров. Никаких учётных записей, адресов почты и паролей. Ни геолокации, ни контактов, ни камеры, ни микрофона. Никаких кук.',
    'privacy.keep':'Хранение и удаление',
    'privacy.keepBody':'То, что лежит на этом устройстве, остаётся, пока вы это не сотрёте; больше нигде мы копий не храним. Наш сервер хранит уже созданное аудио (игровые фразы, никаких личных данных), чтобы не создавать одну и ту же фразу дважды, и ненадолго держит в памяти IP-адрес запроса, чтобы предотвратить злоупотребления.',
    'privacy.erase':'Стереть все данные',
    'privacy.eraseSub':'Имя, настройки и успехи на этом устройстве',
    'privacy.eraseTitle':'Стереть всё?',
    'privacy.eraseBody':'Имя, настройки, успехи, карточки и статистика исчезнут с этого устройства. Купленный Premium остаётся у вашей учётной записи App Store и возвращается кнопкой «Восстановить покупки».',
    'privacy.eraseConfirm':'Да, стереть всё',
    'privacy.contact':'Вопросы о приватности?',
    'privacy.contactSub':'Пишите на {email}',
    'privacy.noAccount':'Kwizillo работает без учётной записи: у нас нечего регистрировать и нечего удалять.',
    'score.points':'очков',
    'score.practice':'очки за повтор',
    'score.dayFull':'дневной максимум набран',
    'score.title':'Рекорды',
    'score.sub':'Твои лучшие очки за каждый период',
    'score.now':'сейчас',
    'score.best':'рекорд',
    'score.run':'Это занятие',
    'score.day':'Сегодня',
    'score.week':'На этой неделе',
    'score.month':'В этом месяце',
    'score.year':'В этом году',
    'score.allTime':'За всё время',
    'score.todayPoints':'{n} из {max} очков сегодня',
    'score.todayCoins':'{n} из {max} монет сегодня',
    'score.capNote':'В день есть предел очков и монет, а вопрос, на который ты уже ответил верно, даёт очки за повтор. Так рекорд остаётся настоящим.',
    'shop.tab':'🛒 Магазин',
    'shop.title':'Магазин',
    'shop.sub':'Плати монетами из игр',
    'shop.buy':'Купить',
    'shop.owned':'Уже твоё','shop.earned':'Заработано',
    'shop.price':'{n} монет',
    'shop.need':'Не хватает {n} монет',
    'shop.confirmTitle':'Купить: {item}?',
    'shop.confirmBody':'Это стоит {n} монет. После этого {item} навсегда твоё.',
    'shop.bought':'{item} — твоё!',
    'shop.cards':'Золотые карточки',
    'shop.mascots':'Друзья',
    'shop.goldCard':'Золотой мир: {world}',
    'shop.goldCardSub':'Блестящая карточка для коллекции',
    'shop.earnHint':'Монеты зарабатываются в Раннере и других играх.',
    'shop.empty':'Всё куплено! Магазин пуст.',
    'result.worldLevelUp':'🎉 {world}: уровень {niveau}!',
    'result.worldMastered':'🏆 {world} пройден на всех уровнях!',
    'result.goldCardEarned':'Ты заработал золотую карточку «{world}»!',
    'result.goldCardSpeech':'Вот это да! Ты полностью прошёл мир «{world}». Золотая карточка твоя!',
    'settings.levelWorlds':'Уровень в каждом мире',
    'settings.levelWorldsSub':'Мир поднимается сам, когда ты проходишь все четыре его викторины.',
    'settings.levelMath':'Уровень игры',
    'settings.timeLimitPerWorld':'Время на вопрос зависит от уровня.',
    'settings.reset':'Сбросить прогресс',
    'settings.resetSub':'Начать всё с нуля',
    'settings.resetTitle':'Сбросить прогресс?',
    'settings.resetBody':'XP, монеты, карточки, успехи и пройденный путь вернутся к началу.',
    'settings.resetConfirm':'Да, сбросить',
    'gate.title':'Маленький вопрос для взрослого',
    'gate.body':'Сколько будет {a} × {b}?',
    'gate.placeholder':'Ответ',
    'gate.wrong':'Это неверно. Попробуй ещё раз.',
    'gate.continue':'Дальше',

    'sound.kicker':'НАСТРОЙКИ',
    'sound.title':'🔊 Звук и музыка',
    'sound.fx':'✨ Звуковые эффекты',
    'sound.music':'🎵 Фоновая музыка',
    'sound.test':'Проверить',
    'sound.pickMusic':'Выбери свою музыку',
    'sound.voiceGuide':'Голосовой проводник',
    'track.home':'Острова',
    'track.space':'Космос',
    'track.jungle':'Джунгли',
    'track.earth':'Земля',
    'track.history':'История',
    'track.science':'Наука',
    'track.mystery':'Тайны',
    'track.play':'Игры',

    'intro.skip':'Пропустить заставку',
    'welcome.back.title':'Привет, {name}!',
    'welcome.back.sub':'Готов продолжить?',
    'welcome.back.continue':'Играть дальше',
    'welcome.back.other':'Играет кто-то другой',
    'welcome.back.where':'Ты остановился здесь',
    'welcome.pick.title':'Кто играет?',
    'welcome.pick.new':'Новый игрок',
    'welcome.pick.back':'Назад',
    'intro.tapToStart':'Нажми, чтобы начать',
    'intro.tapForSound':'Нажми, чтобы услышать'
  };
})();
