(()=>{
  // French UI strings. Same keys and the same layout as every other language; the
  // child is addressed with "tu" throughout. Typographic apostrophes (’) are used
  // everywhere, so no string needs escaping.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.fr={
    'lang.name':'Français',
    'lang.speech':'fr',

    'world.ruimte.title':'Monde de l’espace',
    'world.ruimte.sub':'Voyage entre les planètes, les étoiles et les fusées',
    'world.dieren.title':'Monde des animaux',
    'world.dieren.sub':'Découvre les animaux de la terre, de la jungle et de la mer',
    'world.aarde.title':'Monde de la Terre',
    'world.aarde.sub':'Explore les pays, les océans, la météo et les cartes',
    'world.geschiedenis.title':'Monde de l’histoire',
    'world.geschiedenis.sub':'Entre dans le temps des pharaons, des chevaliers et des explorateurs',
    'world.wetenschap.title':'Monde des sciences',
    'world.wetenschap.sub':'Essaie, découvre et comprends comment tout fonctionne',
    'world.mysterie.title':'Monde du mystère',
    'world.mysterie.sub':'Résous des énigmes et suis des indices malins',
    'world.kunst.title':'Monde de l’art',
    'world.kunst.sub':'Découvre peintures, musique et grands bâtiments',
    'world.sport.title':'Monde du sport',
    'world.sport.sub':'Cours, saute et nage avec les plus grands sportifs',

    'topic.zonnestelsel':'Système solaire',
    'topic.sterren_planeten':'Étoiles et planètes',
    'topic.astronauten':'Astronautes',
    'topic.raket_avontuur':'Aventure en fusée',
    'topic.egyptenaren':'Les Égyptiens',
    'topic.ridders_kastelen':'Chevaliers et châteaux',
    'topic.romeinen':'Les Romains',
    'topic.ontdekkingsreizigers':'Les explorateurs',
    'topic.slimme_proefjes':'Expériences malines',
    'topic.lichaam':'Le corps humain',
    'topic.uitvindingen':'Les inventions',
    'topic.natuur_energie':'Nature et énergie',
    'topic.raadsels':'Énigmes',
    'topic.verborgen_schatten':'Trésors cachés',
    'topic.natuurmysteries':'Mystères de la nature',
    'topic.speurtocht':'La grande chasse',
    'topic.snelle_dieren':'Animaux rapides',
    'topic.baby_dieren':'Bébés animaux',
    'topic.waterdieren':'Animaux de l’eau',
    'topic.jungle':'Aventure dans la jungle',
    'topic.continenten_landen':'Pays et continents',
    'topic.weer_klimaat':'Météo et climat',
    'topic.oceanen_natuur':'Océans et nature',
    'topic.kaarten_navigatie':'Cartes et navigation',
    'topic.schilderkunst':'Peinture',
    'topic.muziek':'Musique',
    'topic.bouwkunst':'Architecture',
    'topic.dans_theater':'Danse & théâtre',
    'topic.balsporten':'Sports de balle',
    'topic.olympische_spelen':'Jeux olympiques',
    'topic.water_wintersport':'Sports d’eau et d’hiver',
    'topic.records_helden':'Records et héros',

    'nav.home':'Accueil',
    'nav.achievements':'Trophées',
    'nav.collection':'Collection',
    'nav.stats':'Stats',
    'nav.more':'Plus',
    'nav.aria':'Navigation principale',
    'nav.collectionLong':'Ma collection',
    'nav.moreLong':'Plus / Espace parents',

    'common.back':'Retour',
    'common.settings':'Réglages',
    'common.close':'Fermer',
    'common.cancel':'Annuler',
    'common.gotIt':'Compris',
    'common.brand':'KWIZILLO',
    'common.of':'sur',
    // Qui suis-je ?
    'whoami.title':'Qui suis-je ?','whoami.round':'Manche {n} sur {total}','whoami.points':'Déjà {n} points','whoami.ask':'Qui suis-je ?','whoami.more':'Un indice','whoami.next':'Suivant','whoami.timeUp':'Le temps est écoulé ! C’était {answer}.',
    'whoami.yes':'Oui, {answer} ! +{points}','whoami.almost':'Presque ! C’était {answer}.',
    'whoami.speech.yes':'Oui, c’est {answer} !','whoami.speech.almost':'Presque ! C’était {answer}.',
    'whoami.doneKicker':'QUI SUIS-JE ?','whoami.doneTitle':'{n} sur {total} devinés !','whoami.summary':'{score} points sur {max}. Plus tu devines tôt, plus tu gagnes de points.',
    'whoami.speech.great':'Waouh, tu devines vite ! Bravo.','whoami.speech.done':'Bien joué ! La prochaine fois tu en trouveras encore plus.',
    'jungle.title':'Runner','jungle.tileSub':'Cours, saute et vole à travers trois niveaux','jungle.loadError':'La jungle n’a pas pu se charger. Réessaie plus tard.',
    'fotozoom.title':'Photo Zoom','fotozoom.round':'Manche {n} sur {total}','fotozoom.points':'Déjà {n} points','fotozoom.ask':'Que vois-tu ?','fotozoom.out':'Dézoomer','fotozoom.next':'Suivant','fotozoom.timeUp':'Le temps est écoulé ! C’était {answer}.',
    'fotozoom.yes':'Oui, {answer} ! +{points}','fotozoom.almost':'Presque ! C’était {answer}.',
    'fotozoom.speech.yes':'Oui, c’est {answer} !','fotozoom.speech.almost':'Presque ! C’était {answer}.',
    'fotozoom.doneKicker':'PHOTO ZOOM','fotozoom.doneTitle':'{n} sur {total} reconnus !','fotozoom.summary':'{score} points sur {max}. Moins tu dézoomes, plus tu gagnes de points.',
    'fotozoom.speech.great':'Quel œil de lynx ! Bravo.','fotozoom.speech.done':'Bien observé ! La prochaine fois tu en verras encore plus.',
    'premium.teaser.fotozoom':'Photo Zoom dans ce monde fait partie de Kwizillo Premium. Demande à un adulte d’ouvrir tous les mondes.',
    'jungle.brand':'KWIZILLO RUNNER','jungle.eyebrow':'KWIZILLO • ARCADE','jungle.titleA':'Kwizillo','jungle.titleB':'Runner','jungle.back':'Retour à Kwizillo','jungle.backShort':'Retour','jungle.easyShort':'Mode tranquille',
    'jungle.levelLabel':'CHOISIS TON NIVEAU','jungle.heroLabel':'QUI COURT AVEC TOI ?','jungle.heroBoy':'Garçon','jungle.heroGirl':'Fille','jungle.glideOn':'Vole !','jungle.glideOff':'Cours !','jungle.levelJungle':'Jungle','jungle.levelStad':'Ville','jungle.levelLucht':'Ciel',
    'jungle.swingOn':'Balance-toi !','jungle.swingOff':'Cours !','jungle.powerSpeed':'⚡ {n}s','jungle.popSpeed':'TURBO !','jungle.popSpeedSub':'7 secondes à toute vitesse · pièces doublées','jungle.labelSpeed':'TURBO !',
    'jungle.canvasLabel':'Terrain de jeu. Flèches gauche et droite pour diriger. Espace pour sauter.','jungle.pause':'Pause','jungle.sound':'Son activé ou coupé','jungle.controls':'Commandes du jeu','jungle.left':'Gauche','jungle.right':'Droite','jungle.jump':'Salto ↑',
    'jungle.loading':'Ton aventure se prépare…','jungle.loadErrorTitle':'Réessayer','jungle.loadErrorBody':'Les images de la jungle n’ont pas pu se charger. Vérifie ta connexion et réessaie.',
    'jungle.intro':'Suis la piste dorée.<br>Saute, explore et collectionne !','jungle.legendMagnet':'🧲 Aimant','jungle.legendShield':'🛡 Bouclier','jungle.legendGold':'★ Or +5','jungle.legendDouble':'×2 Étoile bonus',
    'jungle.easy':'Mode tranquille · saute tout seul','jungle.music':'Musique','jungle.on':'activée','jungle.off':'coupée','jungle.start':'À l’aventure →',
    'jungle.help':'{n} secondes • Glisse ou utilise les boutons<br>10 pièces d’affilée = +5 bonus<br>Attrape des bonus et trouve une carte','jungle.countFollow':'Suis les pièces !','jungle.countReady':'Prêt pour l’aventure ?',
    'jungle.pauseEyebrow':'REPRENDS TON SOUFFLE','jungle.pauseTitle':'Ta jungle<br>t’attend.','jungle.pauseBody':'Le temps est arrêté.','jungle.resume':'Continuer →','jungle.exit':'Partir sans récompense',
    'jungle.hit':'Oups ! Tu es bloqué — repars vite.','jungle.hitLost':'Aïe ! Tu as cogné — {n} pièces perdues.','jungle.labelHit':'−{n}','jungle.lostCoins':'Pièces perdues','jungle.cardFound':'Tu as trouvé une carte de la jungle !','jungle.powerDouble':'×2 {n}s','jungle.powerMagnet':'🧲 {n}s','jungle.powerShield':'🛡 Protégé','jungle.powerStreak':'★ {n} d’affilée',
    'jungle.popDouble':'ÉTOILE BONUS !','jungle.popDoubleSub':'6 secondes de pièces doublées','jungle.popGold':'OR TROUVÉ !','jungle.popGoldSub':'+{n} pièces','jungle.popCombo':'{n} D’AFFILÉE !','jungle.popComboSub':'+5 bonus combo','jungle.popMagnet':'AIMANT À PIÈCES !','jungle.popMagnetSub':'7 secondes d’attraction',
    'jungle.popShield':'BOUCLIER !','jungle.popShieldSub':'Encaisse un choc pour toi','jungle.popBlock':'LE BOUCLIER T’A SAUVÉ !','jungle.popBlockSub':'Continue à courir','jungle.popCard':'CARTE TROUVÉE !','jungle.popCardSub':'Révélée à l’arrivée','jungle.popClear':'BEAU SAUT !','jungle.popClearSub':'Par-dessus le tronc','jungle.popDoubleflip':'DOUBLE SALTO !','jungle.popDoubleflipSub':'+3 pièces',
    'jungle.labelGold':'+{n} OR !','jungle.labelCombo':'COMBO +5','jungle.labelCard':'Carte trouvée !','jungle.labelClear':'Beau saut !','jungle.labelMagnet':'AIMANT !','jungle.labelShield':'BOUCLIER !','jungle.labelBlock':'Sauvé !','jungle.labelDouble':'PIÈCES DOUBLÉES !',
    'jungle.saving':'Ta récompense est enregistrée…','jungle.saved':'Tes pièces sont ajoutées.','jungle.saveError':'L’enregistrement n’a pas encore marché. Réessaie.',
    'jungle.finishEyebrow':'AVENTURE TERMINÉE','jungle.finish':'ARRIVÉE !','jungle.finishSub':'Ton butin de cette course','jungle.coinsEarned':'pièces gagnées','jungle.bestStreak':'Meilleure série','jungle.bonusCoins':'Pièces bonus',
    'jungle.cardAlt':'Carte collectée','jungle.cardEyebrow':'CARTE TROUVÉE','jungle.cardSub':'Pour ta collection Kwizillo','jungle.cardTitle':'Feuille de jungle','card.jungle-leaf':'Feuille de jungle','card.city-star':'Étoile de la ville','card.sky-feather':'Plume du ciel','jungle.retry':'Enregistrer encore','jungle.take':'Prendre mon butin','jungle.again':'Autre aventure','jungle.replay':'Encore celle-ci',
    // Premium
    'common.ok':'OK','common.retry':'Réessayer',
    'premium.label':'Premium','premium.name':'Kwizillo Premium','premium.kicker':'POUR LES PARENTS',
    'premium.title':'Ouvre tout le monde de Kwizillo',
    'premium.subtitle':'Jouer, apprendre, collectionner et découvrir sans limites.',
    'premium.benefit.worlds':'Tous les mondes','premium.benefit.questions':'480+ questions de connaissances','premium.benefit.math':'Jeux de calcul','premium.benefit.memo':'Jeux de mémoire','premium.benefit.facts':'Infos rigolotes','premium.benefit.guides':'Milo et Luna','premium.benefit.collect':'Collectionner cartes et mascottes','premium.benefit.stats':'Progrès et statistiques complets','premium.benefit.new':'Nouvelles aventures et nouveaux contenus',
    'premium.monthly':'Mensuel','premium.yearly':'Annuel','premium.perMonth':'mois','premium.perYear':'an',
    'premium.best':'Meilleur prix','premium.trial':'Essaie {days} jours gratuitement','premium.ctaTrial':'Commencer {days} jours gratuits','premium.ctaYearly':'Choisir l’annuel','premium.ctaMonthly':'Choisir le mensuel',
    'premium.perMonthCalc':'Cela fait {price} par mois',
    'premium.legal':'L’abonnement est facturé sur ton compte Apple et se renouvelle automatiquement jusqu’à sa résiliation. Tu peux le gérer ou le résilier à tout moment dans tes abonnements Apple. Une période gratuite devient un abonnement payant si tu ne résilies pas avant la fin.',
    'premium.restore':'Restaurer les achats','premium.restoreSub':'Récupérer Premium sur cet appareil','premium.manage':'Gérer l’abonnement','premium.manageSub':'Résilier ou modifier via Apple','premium.privacy':'Confidentialité','premium.terms':'Conditions d’utilisation',
    'premium.loading':'Chargement des prix…','premium.purchasing':'Un instant, Apple traite l’achat…',
    'premium.pending':'L’achat attend une confirmation. Dès qu’elle arrive, Premium s’active tout seul.',
    'premium.cancelled':'Achat annulé.','premium.failed':'Ça n’a pas marché. Réessaie plus tard.',
    'premium.unavailable':'Premium n’est pas disponible pour le moment. Réessaie plus tard.',
    'premium.already':'Premium est actif sur cet appareil.',
    'premium.restoring':'Restauration des achats…','premium.restoreNone':'Aucun achat précédent trouvé.','premium.manageUnavailable':'Gère les abonnements dans les Réglages de ton téléphone, sous ton compte Apple.',
    'premium.welcome':'Bienvenue dans Kwizillo Premium !','premium.welcomeSub':'Tous les mondes, les jeux et les infos sont ouverts. Amuse-toi bien !','premium.continue':'Reprendre où tu étais','premium.play':'Jouer',
    'premium.statusFree':'Version gratuite · tout débloquer','premium.statusActive':'Actif · {type}','premium.statusTrial':'Période gratuite · {type}','premium.statusExpired':'Expiré · tes progrès sont gardés','premium.renews':'Se renouvelle le',
    'premium.teaserTitle':'Ceci est Premium','premium.askParent':'Demande à un adulte',
    'premium.teaser.quiz':'Ce quiz fait partie de Kwizillo Premium. Demande à un adulte d’ouvrir tous les mondes.',
    'premium.teaser.memo':'Ce jeu de mémoire fait partie de Kwizillo Premium. Demande à un adulte d’ouvrir tous les plateaux.',
    'premium.teaser.math':'Les niveaux de calcul supérieurs font partie de Kwizillo Premium. Demande à un adulte de les ouvrir.',
    'premium.teaser.facts':'D’autres infos font partie de Kwizillo Premium. Demande à un adulte de tout ouvrir.',
    'premium.factsMore':'{n} infos de plus avec Premium',
    'premium.teaser.whoami':'Qui suis-je ? dans ce monde fait partie de Kwizillo Premium. Demande à un adulte d’ouvrir tous les mondes.',
    'settings.terms':'Conditions d’utilisation','settings.termsBody':'Kwizillo est un jeu éducatif pour enfants. Premium est un abonnement facturé par Apple qui se renouvelle automatiquement jusqu’à sa résiliation ; tu peux résilier à tout moment dans tes abonnements Apple. Il n’y a pas de publicité ni d’achats dans le jeu lui-même.',

    'onboarding.language.title':'Choisis ta langue',
    'onboarding.language.sub':'Dans quelle langue veux-tu jouer ?',
    'onboarding.name.title':'Comment t’appelles-tu ?',
    'onboarding.name.sub':'Pour qu’on puisse bien te dire bonjour.',
    'onboarding.name.placeholder':'Ton prénom',
    'onboarding.name.hint':'Ton prénom reste sur cet appareil.',
    'onboarding.voice.title':'Qui va t’aider ?',
    'onboarding.voice.sub':'Choisis ton guide. Tu peux changer quand tu veux.',
    'onboarding.welcome.title':'Bienvenue, {name} !',
    'onboarding.welcome.sub':'Ton aventure commence maintenant. Prêt à explorer ?',
    'onboarding.welcome.cta':'Commencer l’aventure',
    'onboarding.next':'Continuer',
    'onboarding.speech.welcome':'Oui, tout est prêt ! Viens, je te montre vite où est quoi.',
    'onboarding.speech.language':'Salut ! Je suis Milo. Quelle langue parles-tu ?',
    'onboarding.speech.name':'Ravi de te rencontrer ! Comment t’appelles-tu ? Écris-le simplement.',
    'onboarding.speech.age':'Et quel âge as-tu ?',
    'onboarding.speech.group':'Tu es dans quelle classe ?',
    'onboarding.speech.voice':'Qui veux-tu comme guide ? Moi, Luna, ou plutôt le silence ?',
    'onboarding.age.title':'Quel âge as-tu ?',
    'onboarding.age.sub':'Touche ton âge.',
    'onboarding.age.years':'{n} ans',
    'onboarding.group.title':'Tu es dans quelle classe ?',
    'onboarding.group.sub':'Pour que je choisisse des questions qui te vont.',
    'tour.worlds':'Voici les mondes. Touche un monde et joue un quiz !',
    'tour.games':'Et voici six jeux. Mémo : trouve les paires. Calcul : résous des opérations. Qui suis-je : devine avec des indices. Photo Zoom : devine la photo zoomée. Infos rigolotes : des choses amusantes à savoir. Et le Runner : cours, saute et vole !',
    'tour.facts':'Et voici les Infos rigolotes : des centaines de choses amusantes à découvrir !',
    'tour.hud':'En haut tu vois ton niveau, tes pièces et ta série. La roue dentée est pour tes parents.',
    'tour.nav':'En bas tu trouves ta collection, tes trophées et tes stats. Et sous Plus il y a les réglages.',
    'tour.done':'Amuse-toi bien ! Je t’aide dès que tu bloques.',
    'tour.skip':'Passer',
    'tour.again':'Visite avec {guide}',
    'tour.againSub':'{guide} te remontre où est quoi.',

    'voice.milo':'Milo',
    'voice.milo.desc':'Joyeux et pétillant',
    'voice.luna':'Luna',
    'voice.luna.desc':'Calme et gentille',
    'voice.silent':'Silence',
    'voice.silent.desc':'Sans voix',
    'voice.milo.hello':'Salut ! Je suis Milo. Prêt à jouer ?',
    'voice.luna.hello':'Salut ! Je suis Luna. On explore ensemble ?',

    'home.greeting':'Salut {name} !',
    'home.greetingAnon':'Salut !',
    'home.level':'Niveau {level}',
    'home.coins':'KwizCoins',
    'home.streak':'Jours d’affilée',
    'home.pickWorld':'Choisis ton monde',
    'home.cta':'Commencer l’aventure',
    'home.ctaSub':'Continuer dans {world}',
    'home.voiceLabel':'Voix',
    'home.languageLabel':'Langue',

    'world.kicker':'MONDE KWIZILLO',
    'world.backHome':'Retour à l’accueil',
    'world.mix':'Lancer le quiz mélangé',
    'world.mixSub':'Des questions des quatre thèmes',
    'world.quizNumber':'Quiz {n}',
    'world.topicPassed':'Réussi',
    'world.topicPlayed':'Quiz {n} joué · {correct}/{answered} justes',
    'world.progressLine':'{passed} thèmes sur {total} réussis',
    'world.worldProgress':'{done} des {total} quiz de ce monde réussis',
    'world.mixDone':'{n} joués',

    'quiz.mixed':'Quiz mélangé',
    'quiz.progress':'Question {current} sur {total}',
    'quiz.hint':'Indice',
    'quiz.none':'Il n’y a pas encore de questions pour ce thème.',
    'quiz.artAlt':'Illustration de la question',
    'quiz.quizLabel':'Quiz {n}',
    'quiz.back':'Retour',
    'quiz.explain':'Expliquer',
    'quiz.timerAria':'Secondes restantes',
    'feedback.timeKicker':'TEMPS ÉCOULÉ !',
    'feedback.timeTitle':'Plus vite la prochaine fois !',
    'settings.level':'Niveau',
    'settings.levelSub':'{seconds} s par question · max. {allowed} erreurs · {hints}',
    'settings.hintsFree':'indices libres',
    'settings.hintsN':'{n} indices',
    'settings.hintsNone':'aucun indice',
    'settings.readsQuestionOnly':'seule la question est lue à voix haute',
    'quiz.hintsSpent':'Plus d’indices dans ce quiz.',
    'quiz.noHints':'Le niveau 6 n’a pas d’indices.',
    'world.speech.enter':'[excited] {title} !',
    'settings.levelAuto':'Auto',
    'settings.share':'Partage ton score',
    'settings.shareSub':'Envoie ton résultat à ta famille ou tes amis',

    'hint.title':'Un petit indice',
    'hint.kicker':'Astuce {topic}',
    'hint.ok':'Continuer à réfléchir',
    'hint.close':'Fermer l’indice',
    'hint.fallback':'Regarde encore bien la question et l’image.',
    'hint.alt':'Indice en image',

    'feedback.goodKicker':'EXACT !',
    'feedback.tryKicker':'TOUT PRÈS !',
    'feedback.goodTitle':'Bien joué !',
    'feedback.tryTitle':'Bien réfléchi !',
    'feedback.correctIs':'La bonne réponse est <strong>{answer}</strong>.',
    'feedback.thatsRight':'C’est exact !',
    'feedback.didYouKnow':'Le savais-tu ?',
    'feedback.next':'Question suivante',
    'feedback.seeResult':'Voir le résultat',
    'feedback.speech.good':'Bien joué.',
    'feedback.speech.good.1':'Bien joué !',
    'feedback.speech.good.2':'Super, c’est exact !',
    'feedback.speech.good.3':'Pile poil !',
    'feedback.speech.good.4':'Très bien !',
    'feedback.speech.good.5':'Oui ! Exactement !',
    'feedback.speech.good.6':'Bravo, bien observé !',
    'feedback.speech.good.7':'Fantastique !',
    'feedback.speech.good.8':'Waouh, c’est juste !',
    'feedback.speech.try.1':'Presque. La bonne réponse est {answer}.',
    'feedback.speech.try.2':'Pas tout à fait. La bonne réponse est {answer}.',
    'feedback.speech.try.3':'Bel essai ! La bonne réponse est {answer}.',
    'feedback.speech.try.4':'Oups, tout près. La bonne réponse est {answer}.',
    'feedback.answerLabel':'La bonne réponse',
    'feedback.close':'Fermer',
    'feedback.listening':'J’écoute…',
    'quiz.repeat':'Encore',
    'quiz.repeatAria':'Relire la question',
    'feedback.speech.try':'Presque. La bonne réponse est {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'QUIZ TERMINÉ',
    'result.title':'{score} bonnes réponses sur {total} !',
    'result.score':'score',
    'result.xp':'XP',
    'result.coins':'pièces',
    'result.again':'Encore un quiz',
    'result.againNumbered':'Lancer le quiz {n}',
    'result.nextTopic':'Ensuite : {topic}',
    'result.finishWorld':'Lancer le quiz mélangé',
    'result.retryTopic':'Refaire ce thème',
    'result.retryNow':'Réessayer',
    'memo.title':'Mémo',
    'memo.pickTitle':'Choisis ton monde',
    'game.mixAll':'Mélange de tous les mondes',
    'game.pickSub':'Choisis un monde, ou joue-les tous mélangés.',
    'memo.pickSub':'Trouve les paires · Niveau {n}',
    'memo.otherWorld':'Un autre monde',
    'memo.sub':'Trouve les paires',
    'memo.play':'Jouer au Mémo',
    'memo.playSub':'Trouve les paires de {world}',
    'memo.level':'Niveau {n}',
    'memo.pairs':'{found} paires sur {total}',
    'memo.moves':'{n} tours',
    'memo.movesShort':'tours',
    'memo.card':'Carte mémo',
    'memo.hintLine':'Retourne deux cartes et trouve les paires',
    'memo.none':'Pas encore assez de cartes pour ce monde.',
    'memo.doneKicker':'MÉMO TERMINÉ !',
    'memo.doneTitle':'Toutes les paires trouvées !',
    'memo.timeKicker':'TEMPS ÉCOULÉ !',
    'memo.timeTitle':'Presque toutes les paires !',
    'memo.summary':'{pairs} paires en {moves} tours et {secs} secondes.',
    'memo.summaryTime':'{found} paires trouvées sur {pairs}. Réessaie !',
    'memo.again':'Encore une fois',
    'memo.retry':'Réessayer',
    'memo.toWorld':'Retour au monde',
    'memo.speech.done':'Waouh, tu as trouvé toutes les paires ! Quelle mémoire !',
    'memo.speech.time':'Le temps est écoulé. La prochaine fois tu les auras toutes !',
    'memo.modeTitle':'Tu joues comment ?',
    'memo.solo':'Solo','memo.soloSub':'Contre la montre',
    'memo.duel':'Face à face','memo.duelSub':'Chacun son tour, qui trouve le plus de paires ?',
    'memo.player1':'Joueur 1','memo.player2':'Joueur 2','memo.p2Label':'Qui joue avec toi ?',
    'memo.turn':'C’est à {name}',
    'memo.duelKicker':'DUEL MÉMO',
    'memo.duelWin':'{name} gagne !','memo.duelTie':'Égalité !',
    'memo.duelSummary':'{pairs} paires en {moves} tours.',
    'memo.rematch':'Revanche',
    'memo.speech.win':'Nous avons un gagnant ! Bien joué tous les deux !',
    'memo.speech.tie':'Égalité ! Vous avez tous les deux une super mémoire !',
    'home.playMore':'Jouer plus',
    'math.title':'Calcul',
    'facts.title':'Infos rigolotes',
    'world.ruimte.short':'Espace','world.dieren.short':'Animaux','world.aarde.short':'Terre','world.geschiedenis.short':'Histoire','world.wetenschap.short':'Sciences','world.kunst.short':'Art','world.sport.short':'Sport','world.mysterie.short':'Mystère',
    'facts.tileSub':'Savais-tu que…',
    'facts.sub':'{seen} sur {total} découvertes',
    'facts.next':'Info suivante',
    'facts.listen':'Lire à voix haute',
    'facts.kicker':'Savais-tu que…',
    'facts.new':'Nouveau !',
    'facts.allSeen':'Tu as découvert toutes les infos ! Elles reviennent encore une fois.',
    'facts.more':'Plus d’infos',
    'math.sub':'Opérations rapides',
    'math.play':'Calcul',
    'math.playSub':'Dix opérations · Niveau {n}',
    'math.progress':'Opération {current} sur {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'{score} opérations justes sur {total} !',
    'math.again':'Dix nouvelles opérations',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'plus',
    'math.op.minus':'moins',
    'math.op.times':'fois',
    'math.op.divided':'divisé par',
    'math.speech.twoStep':'{c} plus {a} fois {b}',
    'math.speech.half':'La moitié de {n}',
    'math.speech.quarter':'Un quart de {n}',
    'math.speech.percent':'{p} pour cent de {n}',
    'math.speech.wrong':'Presque. C’est {answer}.',
    'math.speech.done':'Super calcul ! Toutes les opérations sont faites.',
    'math.speech.fail':'Bel essai. Encore une fois et tu y arrives !',
    'math.hint.plus':'Compte à partir de {a} : {b} de plus.',
    'math.hint.minus':'Commence à {a} et compte {b} en arrière.',
    'math.hint.times':'{a} fois {b} : additionne {b} exactement {a} fois.',
    'math.hint.divided':'Combien de fois {b} tient dans {a} ?',
    'math.hint.generic':'Calcule étape par étape.',
    'achievement.math3':'3 séries de calcul réussies',
    'stats.mathLine':'{played} séries jouées · {won} réussies',
    'result.passKicker':'RÉUSSI !',
    'result.failKicker':'PAS ENCORE',
    'result.passRule':'Niveau {niveau} : tu pouvais faire {allowed} erreurs et tu en as fait {wrong}.',
    'result.failRule':'Niveau {niveau} : tu peux faire {allowed} erreurs, tu en as fait {wrong}. Rejoue ce thème !',
    'result.toCollection':'Aller à ma collection',

    'profile.title':'Mon profil',
    'profile.sub':'Ton prénom, ton copain et tes réglages',
    'profile.saveName':'Enregistrer le prénom',
    'profile.saved':'Enregistré !',
    'profile.buddy':'Mon copain',
    'profile.chooseBuddy':'Choisir un copain',
    'profile.voice':'Qui lit à voix haute ?',
    'achievements.title':'Trophées',
    'achievements.sub':'Tes aventures et tes étapes',
    'achievements.summary':'{done}/{total} gagnés',
    'achievements.summarySub':'Continue à explorer pour débloquer de nouveaux trophées.',
    'achievements.done':'Gagné !',
    'achievement.firstQuiz':'Premier quiz',
    'achievement.correct10':'10 bonnes réponses',
    'achievement.correct50':'50 bonnes réponses',
    'achievement.streak7':'7 jours d’affilée',
    'achievement.cards5':'5 cartes de connaissances',
    'achievement.allWorlds':'Tous les mondes visités',
    'achievement.memo3':'3 jeux de mémo gagnés',

    'collection.title':'Ma collection',
    'collection.sub':'Tout ce que tu as découvert',
    'collection.tabWorlds':'🌍 Mondes',
    'collection.tabCards':'🃏 Cartes',
    'collection.tabMascots':'🐾 Copains',
    'collection.worldStat':'{correct}/{answered} justes · {pct}%',
    'progress.worldLine':'{passed} quiz réussis sur {total} · {points} points',
    'progress.overall':'Au total {points} points sur {max}',
    'progress.overallSub':'Chaque quiz réussi vaut 25 points : un monde entier fait 100.',
    'collection.discovered':'★ Découvert',
    'collection.unlockKicker':'NOUVEAU COPAIN !',
    'collection.unlockLine':'Débloqué avec {n} bonnes réponses.',
    'score.coinsAdded':'+{n} pièces ajoutées',
    'score.coinsCapped':'Maximum du jour atteint : {n} de tes {got} pièces ont été ajoutées.','collection.cardAdded':'{title} est maintenant dans ta collection !',
    'collection.emptyTitle':'Pas encore de cartes',
    'collection.emptyBody':'Réponds juste aux questions pour collectionner des cartes de connaissances.',
    'collection.mascotLocked':'encore {n} bonnes réponses',
    'collection.mascotActive':'Actif ✓',
    'collection.mascotChoose':'Choisir un copain',
    'collection.mascotCount':'{unlocked}/{total} copains débloqués',

    'mascot.milo':'Milo',
    'mascot.milo.desc':'Ton copain robot malin',
    'mascot.comet':'Comète',
    'mascot.comet.desc':'Copain de l’espace',
    'mascot.pootje':'Patoune',
    'mascot.pootje.desc':'Ami des animaux',
    'mascot.terra':'Terra',
    'mascot.terra.desc':'Protectrice de la Terre',
    'mascot.sparky':'Sparky',
    'mascot.sparky.desc':'Fan d’expériences',
    'mascot.lumi':'Lumi',
    'mascot.lumi.desc':'Chercheuse de mystères',
    'mascot.nova':'Nova','mascot.nova.desc':'Voyageuse des étoiles',
    'mascot.kiko':'Kiko','mascot.kiko.desc':'Explorateur de la jungle',
    'mascot.pip':'Pip','mascot.pip.desc':'Casse-cou des glaces',
    'mascot.ravi':'Ravi','mascot.ravi.desc':'Inventeur en herbe',
    'mascot.flora':'Flora','mascot.flora.desc':'Amie de la nature',
    'mascot.draco':'Draco','mascot.draco.desc':'Petit dragon du château',

    'stats.title':'Stats',
    'stats.sub':'De vrais progrès, tirés de tes questions jouées',
    'stats.heroTitle':'Tes connaissances grandissent',
    'stats.heroSub':'{answered} questions répondues · {quizzes} {quizWord} joués',
    'stats.correctShort':'justes',
    'stats.xpTotal':'XP au total',
    'stats.coins':'KwizCoins',
    'stats.streak':'Jours d’affilée',
    'stats.cards':'Cartes',
    'stats.perWorld':'Par monde',
    'stats.games':'Jeux',
    'stats.runnerLine':'{played} courses · {coins} pièces ramassées',
    'stats.memoBest':'{n} tours',
    'stats.memoLine':'{played} jeux de mémo joués · {won} gagnés',
    'share.text':'{name} joue à Kwizillo ! Niveau {level}, {correct} bonnes réponses, {cards} cartes de connaissances. Meilleur quiz : {best}. Tu veux jouer aussi ?',
    'share.copied':'Texte copié – colle-le dans un message.',
    'result.share':'Partage ton score',
    'stats.worldLine':'{correct} justes sur {answered} · {quizzes} {quizWord}',
    'stats.quizOne':'quiz',
    'stats.quizMany':'quiz',

    'settings.title':'Espace parents',
    'settings.sub':'Réglages pour une bonne expérience de jeu',
    'settings.group':'Classe',
    'settings.groupSub':'Ajuster la difficulté',
    'settings.groupValue':'Classe {n}',
    'settings.language':'Langue',
    'settings.languageSub':'Choisis la langue du jeu',
    'settings.sound':'Son, musique et voix',
    'settings.soundVoiceOff':'Voix coupée',
    'settings.soundVoiceOn':'Voix : {voice}',
    'settings.soundMusic':'musique {state}',
    'settings.on':'activée',
    'settings.off':'coupée',
    'settings.timeLimit':'Minuteur de question',
    'settings.timeLimitOff':'Coupé',
    'settings.timeLimitValue':'{n} secondes par question à ce niveau',
    'settings.privacy':'Vie privée et sécurité',
    'privacy.sub':'Ce que le jeu enregistre et ce qu’il ne fait pas',
    'privacy.updated':'Mis à jour : {date}',
    'privacy.device':'Sur cet appareil',
    'privacy.deviceBody':'Tout cela se trouve dans la mémoire de l’application sur cet appareil. Rien ne part vers Kwizillo ni vers quelqu’un d’autre, et tout disparaît dès que tu supprimes l’application ou que tu effaces tout ci-dessous.',
    'privacy.itemName':'Prénom : {value}',
    'privacy.itemSettings':'Langue, voix, son, classe et niveau',
    'privacy.itemProgress':'Progression : {answered} questions, {correct} justes, {cards} cartes',
    'privacy.itemPremium':'Si Premium est actif (cela vient de l’App Store)',
    'privacy.leaves':'Ce qui quitte l’appareil',
    'privacy.leavesBody':'Uniquement la phrase que Milo ou Luna lit à voix haute. Elle va vers notre propre serveur, puis vers le service vocal ElevenLabs. C’est toujours du texte du jeu : une question, une réponse, un indice ou une info. Jamais le prénom de ton enfant et jamais ce que ton enfant écrit.',
    'privacy.none':'Ce que l’application ne fait pas',
    'privacy.noneBody':'Pas de publicité. Pas d’analytique ni de traceurs tiers. Pas de compte, d’adresse e-mail ni de mot de passe. Pas de localisation, de contacts, de caméra ni de micro. Pas de cookies.',
    'privacy.keep':'Conservation et effacement',
    'privacy.keepBody':'Ce qui est sur cet appareil y reste jusqu’à ce que tu l’effaces ; nous n’en gardons aucune copie ailleurs. Notre serveur garde l’audio fabriqué (des phrases du jeu, aucune donnée personnelle) pour ne pas refaire deux fois la même phrase, et garde brièvement en mémoire l’adresse IP d’une requête afin d’éviter les abus.',
    'privacy.erase':'Effacer toutes les données',
    'privacy.eraseSub':'Prénom, réglages et progression sur cet appareil',
    'privacy.eraseTitle':'Tout effacer ?',
    'privacy.eraseBody':'Prénom, réglages, progression, cartes et statistiques disparaissent de cet appareil. Un Premium acheté reste lié à ton compte App Store et revient avec « Restaurer les achats ».',
    'privacy.eraseConfirm':'Oui, tout effacer',
    'privacy.contact':'Des questions sur la vie privée ?',
    'privacy.contactSub':'Écris à {email}',
    'privacy.noAccount':'Kwizillo fonctionne sans compte : il n’y a rien à créer ni à supprimer chez nous.',
    'score.points':'points',
    'score.practice':'points d’entraînement',
    'score.dayFull':'maximum du jour atteint',
    'score.title':'Records',
    'score.sub':'Tes meilleurs points sur chaque période',
    'score.now':'maintenant',
    'score.best':'record',
    'score.run':'Cet exercice',
    'score.day':'Aujourd’hui',
    'score.week':'Cette semaine',
    'score.month':'Ce mois-ci',
    'score.year':'Cette année',
    'score.allTime':'De tous les temps',
    'score.todayPoints':'{n} points sur {max} aujourd’hui',
    'score.todayCoins':'{n} pièces sur {max} aujourd’hui',
    'score.capNote':'Chaque jour, il y a un maximum de points et de pièces, et une question déjà réussie rapporte des points d’entraînement. Comme ça, un record vaut vraiment quelque chose.',
    'shop.tab':'🛒 Boutique',
    'shop.title':'Boutique',
    'shop.sub':'Paie avec les pièces des jeux',
    'shop.buy':'Acheter',
    'shop.owned':'Obtenu','shop.earned':'Gagnée',
    'shop.price':'{n} pièces',
    'shop.need':'Encore {n} pièces',
    'shop.confirmTitle':'Acheter {item} ?',
    'shop.confirmBody':'Cela coûte {n} pièces. Ensuite, {item} est à toi pour toujours.',
    'shop.bought':'{item} est à toi !',
    'shop.cards':'Cartes dorées',
    'shop.mascots':'Copains',
    'shop.goldCard':'{world} doré',
    'shop.goldCardSub':'Une carte brillante pour ta collection',
    'shop.earnHint':'Les pièces se gagnent dans le Runner et les autres jeux.',
    'shop.empty':'Tout est acheté ! La boutique est vide.',
    'result.worldLevelUp':'🎉 {world} passe au niveau {niveau} !',
    'result.worldMastered':'🏆 {world} terminé à tous les niveaux !',
    'result.goldCardEarned':'Tu as gagné la carte dorée de {world} !',
    'result.goldCardSpeech':'Waouh ! Tu as terminé {world} en entier. La carte dorée est à toi !',
    'settings.levelWorlds':'Niveau par monde',
    'settings.levelWorldsSub':'Un monde monte tout seul quand tu réussis ses quatre quiz.',
    'settings.levelMath':'Calcul : niveau',
    'settings.timeLimitPerWorld':'Le temps par question suit le niveau du monde.',
    'settings.reset':'Réinitialiser les progrès',
    'settings.resetSub':'Tout recommencer à zéro',
    'settings.resetTitle':'Réinitialiser les progrès ?',
    'settings.resetBody':'XP, pièces, cartes, stats et progrès reviennent au début.',
    'settings.resetConfirm':'Oui, réinitialiser',
    'gate.title':'Une petite question pour un adulte',
    'gate.body':'Combien font {a} × {b} ?',
    'gate.placeholder':'Réponse',
    'gate.wrong':'Ce n’est pas juste. Réessaie.',
    'gate.continue':'Continuer',

    'sound.kicker':'RÉGLAGES',
    'sound.title':'🔊 Son et musique',
    'sound.fx':'✨ Effets sonores',
    'sound.music':'🎵 Musique de fond',
    'sound.test':'Tester',
    'sound.pickMusic':'Choisis ta musique',
    'sound.voiceGuide':'Guide vocal',
    'track.home':'Îles',
    'track.space':'Espace',
    'track.jungle':'Jungle',
    'track.earth':'Terre',
    'track.history':'Histoire',
    'track.science':'Sciences',
    'track.mystery':'Mystère',
    'track.play':'Jeux',

    'intro.skip':'Passer l’intro',
    'intro.tapToStart':'Touche pour commencer',
    'intro.tapForSound':'Touche pour le son'
  };
})();
