(()=>{
  // Italian UI strings. Same keys and the same layout as every other language;
  // the child is addressed with "tu" throughout. Typographic apostrophes (’) are
  // used everywhere, so no string needs escaping.
  const S=window.KWIZILLO_STRINGS=window.KWIZILLO_STRINGS||{};
  S.it={
    'lang.name':'Italiano',
    'lang.speech':'it',

    'world.ruimte.title':'Mondo dello spazio',
    'world.ruimte.sub':'Viaggia tra pianeti, stelle e razzi',
    'world.dieren.title':'Mondo degli animali',
    'world.dieren.sub':'Scopri gli animali della terra, della giungla e del mare',
    'world.aarde.title':'Mondo della Terra',
    'world.aarde.sub':'Esplora paesi, oceani, clima e mappe',
    'world.geschiedenis.title':'Mondo della storia',
    'world.geschiedenis.sub':'Entra nel tempo di faraoni, cavalieri ed esploratori',
    'world.wetenschap.title':'Mondo della scienza',
    'world.wetenschap.sub':'Prova, scopri e capisci come funziona tutto',
    'world.mysterie.title':'Mondo del mistero',
    'world.mysterie.sub':'Risolvi enigmi e segui indizi furbi',
    'world.kunst.title':'Mondo dell’Arte',
    'world.kunst.sub':'Scopri quadri, musica e grandi edifici',
    'world.sport.title':'Mondo dello Sport',
    'world.sport.sub':'Corri, salta e nuota con i più grandi atleti',

    'topic.zonnestelsel':'Sistema solare',
    'topic.sterren_planeten':'Stelle e pianeti',
    'topic.astronauten':'Astronauti',
    'topic.raket_avontuur':'Avventura in razzo',
    'topic.egyptenaren':'Gli egizi',
    'topic.ridders_kastelen':'Cavalieri e castelli',
    'topic.romeinen':'I romani',
    'topic.ontdekkingsreizigers':'Gli esploratori',
    'topic.slimme_proefjes':'Esperimenti furbi',
    'topic.lichaam':'Il corpo umano',
    'topic.uitvindingen':'Le invenzioni',
    'topic.natuur_energie':'Natura ed energia',
    'topic.raadsels':'Indovinelli',
    'topic.verborgen_schatten':'Tesori nascosti',
    'topic.natuurmysteries':'Misteri della natura',
    'topic.speurtocht':'La grande caccia',
    'topic.snelle_dieren':'Animali veloci',
    'topic.baby_dieren':'Cuccioli',
    'topic.waterdieren':'Animali dell’acqua',
    'topic.jungle':'Avventura nella giungla',
    'topic.continenten_landen':'Paesi e continenti',
    'topic.weer_klimaat':'Tempo e clima',
    'topic.oceanen_natuur':'Oceani e natura',
    'topic.kaarten_navigatie':'Mappe e navigazione',
    'topic.schilderkunst':'Pittura',
    'topic.muziek':'Musica',
    'topic.bouwkunst':'Architettura',
    'topic.dans_theater':'Danza e teatro',
    'topic.balsporten':'Sport con la palla',
    'topic.olympische_spelen':'Giochi olimpici',
    'topic.water_wintersport':'Sport d’acqua e neve',
    'topic.records_helden':'Record ed eroi',

    'nav.home':'Home',
    'nav.achievements':'Premi',
    'nav.collection':'Collezione',
    'nav.stats':'Dati',
    'nav.more':'Altro',
    'nav.aria':'Navigazione principale',
    'nav.collectionLong':'La mia collezione',
    'nav.moreLong':'Altro / Area genitori',

    'common.back':'Indietro',
    'common.settings':'Impostazioni',
    'common.close':'Chiudi',
    'common.cancel':'Annulla',
    'common.gotIt':'Capito',
    'common.brand':'KWIZILLO',
    'common.of':'di',
    // Chi sono?
    'whoami.title':'Chi sono?','whoami.round':'Turno {n} di {total}','whoami.points':'Già {n} punti','whoami.ask':'Chi sono?','whoami.more':'Un indizio','whoami.next':'Avanti','whoami.timeUp':'Tempo scaduto! Era {answer}.',
    'whoami.speech.ask':'[playful] '+'Chi sono?',   // spoken only: the voice asks it playfully, the tag is not read out
    'whoami.speech.askLuna':'[warmly] '+'Mmm... chi sono?',   // Luna's own: the playful take sounded shrill in her voice (Stefan, 2026-10-10, take 3 of 3)
    'whoami.yes':'Sì, {answer}! +{points}','whoami.almost':'Quasi! Era {answer}.',
    'whoami.speech.yes':'È {answer}','whoami.speech.almost':'Quasi! Era {answer}.',
    'whoami.doneKicker':'CHI SONO?','whoami.doneTitle':'{n} di {total} indovinati!','whoami.summary':'{score} punti su {max}. Prima indovini, più punti prendi.',
    'whoami.speech.great':'Wow, indovini in fretta! Bravo.','whoami.speech.done':'Ben giocato! La prossima volta ne indovinerai ancora di più.',
    'jungle.title':'Runner','jungle.tileSub':'Corri, salta e vola per tre livelli','jungle.loadError':'La giungla non si è caricata. Riprova più tardi.',
    'fotozoom.title':'Foto Zoom','fotozoom.round':'Turno {n} di {total}','fotozoom.points':'Già {n} punti','fotozoom.ask':'Che cos’è?','fotozoom.out':'Allontana','fotozoom.next':'Avanti','fotozoom.timeUp':'Tempo scaduto! Era {answer}.',
    'fotozoom.speech.ask':'[playful] '+'Che cos’è?',   // spoken only: the voice asks it playfully, the tag is not read out
    'fotozoom.yes':'Sì, {answer}! +{points}','fotozoom.almost':'Quasi! Era {answer}.',
    'fotozoom.speech.yes':'È {answer}','fotozoom.speech.almost':'Quasi! Era {answer}.',
    'fotozoom.doneKicker':'FOTO ZOOM','fotozoom.doneTitle':'{n} di {total} riconosciuti!','fotozoom.summary':'{score} punti su {max}. Meno allontani, più punti prendi.',
    'fotozoom.speech.great':'Che occhio! Bravo.','fotozoom.speech.done':'Bella osservazione! La prossima volta ne riconoscerai ancora di più.',
    'premium.teaser.fotozoom':'Foto Zoom in questo mondo fa parte di Kwizillo Premium. Chiedi a un adulto di aprire tutti i mondi.',
    'jungle.brand':'KWIZILLO RUNNER','jungle.eyebrow':'KWIZILLO • ARCADE','jungle.titleA':'Kwizillo','jungle.titleB':'Runner','jungle.back':'Torna a Kwizillo','jungle.backShort':'Indietro','jungle.easyShort':'Corsa tranquilla',
    'jungle.levelLabel':'SCEGLI IL TUO LIVELLO','jungle.heroLabel':'CHI CORRE CON TE?','jungle.heroBoy':'Bambino','jungle.heroGirl':'Bambina','jungle.glideOn':'Vola!','jungle.glideOff':'Corri!','jungle.levelJungle':'Giungla','jungle.levelStad':'Città','jungle.levelLucht':'Cielo',
    'jungle.swingOn':'Dondola!','jungle.swingOff':'Corri!','jungle.powerSpeed':'⚡ {n}s','jungle.popSpeed':'TURBO!','jungle.popSpeedSub':'7 secondi velocissimi · monete doppie','jungle.labelSpeed':'TURBO!',
    'jungle.canvasLabel':'Campo di gioco. Frecce sinistra e destra per guidare. Spazio per saltare.','jungle.pause':'Pausa','jungle.sound':'Audio acceso o spento','jungle.controls':'Comandi di gioco','jungle.left':'Sinistra','jungle.right':'Destra','jungle.jump':'Salta ↑',
    'jungle.loading':'Sto preparando la tua avventura…','jungle.loadErrorTitle':'Riprova','jungle.loadErrorBody':'Le immagini della giungla non si sono caricate. Controlla la connessione e riprova.',
    'jungle.intro':'Segui la scia dorata.<br>Salta, esplora e colleziona!','jungle.legendMagnet':'🧲 Magnete','jungle.legendShield':'🛡 Scudo','jungle.legendGold':'★ Oro +5','jungle.legendDouble':'×2 Stella bonus',
    'jungle.easy':'Corsa tranquilla · salta da sola','jungle.music':'Musica','jungle.on':'accesa','jungle.off':'spenta','jungle.start':'All’avventura →',
    'jungle.help':'{n} secondi • Scorri o usa i pulsanti<br>10 monete di fila = +5 bonus<br>Prendi i potenziamenti e trova una carta','jungle.countFollow':'Segui le monete!','jungle.countReady':'Pronto per l’avventura?',
    'jungle.pauseEyebrow':'RIPRENDI FIATO','jungle.pauseTitle':'La tua giungla<br>ti aspetta.','jungle.pauseBody':'Il tempo è fermo.','jungle.resume':'Continua a giocare →','jungle.exit':'Esci senza premio',
    'jungle.hit':'Ops! Ti sei fermato: riparti!','jungle.hitLost':'Ahi! Hai sbattuto: {n} monete perse.','jungle.labelHit':'−{n}','jungle.lostCoins':'Monete perse','jungle.cardFound':'Hai trovato una carta della giungla!','jungle.powerDouble':'×2 {n}s','jungle.powerMagnet':'🧲 {n}s','jungle.powerShield':'🛡 Protetto','jungle.powerStreak':'★ {n} di fila',
    'jungle.popDouble':'STELLA BONUS!','jungle.popDoubleSub':'6 secondi di monete doppie','jungle.popGold':'ORO TROVATO!','jungle.popGoldSub':'+{n} monete','jungle.popCombo':'{n} DI FILA!','jungle.popComboSub':'+5 bonus combo','jungle.popMagnet':'MAGNETE PER MONETE!','jungle.popMagnetSub':'7 secondi che attirano monete',
    'jungle.popShield':'SCUDO!','jungle.popShieldSub':'Para un colpo al posto tuo','jungle.popBlock':'LO SCUDO TI HA SALVATO!','jungle.popBlockSub':'Continua a correre','jungle.popCard':'CARTA TROVATA!','jungle.popCardSub':'Si scopre al traguardo','jungle.popClear':'BEL SALTO!','jungle.popClearSub':'Sopra il tronco','jungle.popDoubleflip':'DOPPIO SALTO!','jungle.popDoubleflipSub':'+3 monete',
    'jungle.labelGold':'+{n} ORO!','jungle.labelCombo':'COMBO +5','jungle.labelCard':'Carta trovata!','jungle.labelClear':'Bel salto!','jungle.labelMagnet':'MAGNETE!','jungle.labelShield':'SCUDO!','jungle.labelBlock':'Salvato!','jungle.labelDouble':'MONETE DOPPIE!',
    'jungle.saving':'Sto salvando il tuo premio…','jungle.saved':'Le tue monete sono state aggiunte.','jungle.saveError':'Il salvataggio non è ancora riuscito. Riprova.',
    'jungle.finishEyebrow':'AVVENTURA COMPLETATA','jungle.finish':'TRAGUARDO!','jungle.finishSub':'Il tuo bottino di questa corsa','jungle.coinsEarned':'monete guadagnate','jungle.bestStreak':'Serie migliore','jungle.bonusCoins':'Monete bonus',
    'jungle.cardAlt':'Carta raccolta','jungle.cardEyebrow':'CARTA TROVATA','jungle.cardSub':'Per la tua collezione Kwizillo','jungle.cardTitle':'Foglia della giungla','card.jungle-leaf':'Foglia della giungla','card.city-star':'Stella della città','card.sky-feather':'Piuma del cielo','jungle.retry':'Salva di nuovo','jungle.take':'Prendo il bottino','jungle.again':'Altra avventura','jungle.replay':'Gioca ancora',
    // Premium
    'common.ok':'OK','common.retry':'Riprova',
    'premium.label':'Premium','premium.name':'Kwizillo Premium','premium.kicker':'PER I GENITORI',
    'premium.title':'Apri tutto il mondo di Kwizillo',
    'premium.subtitle':'Giocare, imparare, collezionare e scoprire senza limiti.',
    'premium.benefit.worlds':'Tutti i mondi','premium.benefit.questions':'1280 domande di conoscenza','premium.benefit.math':'Giochi di calcolo','premium.benefit.memo':'Giochi di memoria','premium.benefit.facts':'Curiosità','premium.benefit.guides':'Milo e Luna','premium.benefit.collect':'Colleziona carte e mascotte','premium.benefit.stats':'Progressi e statistiche completi','premium.benefit.new':'Nuove avventure e nuovi contenuti',
    'premium.monthly':'Mensile','premium.yearly':'Annuale','premium.perMonth':'mese','premium.perYear':'anno',
    'premium.best':'Prezzo migliore','premium.trial':'Prova {days} giorni gratis','premium.ctaTrial':'Inizia {days} giorni gratis','premium.ctaYearly':'Scegli annuale','premium.ctaMonthly':'Scegli mensile',
    'premium.perMonthCalc':'Sono {price} al mese',
    'premium.legal':'L’abbonamento viene addebitato sul tuo account Apple e si rinnova automaticamente finché non lo disdici. Puoi gestirlo o disdirlo quando vuoi negli abbonamenti Apple. Un periodo gratuito diventa un abbonamento a pagamento se non disdici prima della fine.',
    'premium.restore':'Ripristina acquisti','premium.restoreSub':'Riporta Premium su questo dispositivo','premium.manage':'Gestisci abbonamento','premium.manageSub':'Disdici o cambia tramite Apple','premium.privacy':'Privacy','premium.terms':'Condizioni d’uso',
    'premium.loading':'Carico i prezzi…','premium.purchasing':'Un attimo, Apple sta gestendo l’acquisto…',
    'premium.pending':'L’acquisto aspetta una conferma. Appena arriva, Premium si attiva da solo.',
    'premium.cancelled':'Acquisto annullato.','premium.failed':'Non ha funzionato. Riprova più tardi.',
    'premium.unavailable':'Premium al momento non è disponibile. Riprova più tardi.',
    'premium.already':'Premium è attivo su questo dispositivo.',
    'premium.restoring':'Sto ripristinando gli acquisti…','premium.restoreNone':'Nessun acquisto precedente trovato.','premium.manageUnavailable':'Gestisci gli abbonamenti nelle Impostazioni del telefono, sotto il tuo account Apple.',
    'premium.welcome':'Benvenuto in Kwizillo Premium!','premium.welcomeSub':'Tutti i mondi, i giochi e le curiosità sono aperti. Buon divertimento!','premium.continue':'Riprendi da dove eri','premium.play':'Gioca',
    'premium.statusFree':'Versione gratuita · sblocca tutto','premium.statusActive':'Attivo · {type}','premium.statusTrial':'Periodo gratuito · {type}','premium.statusExpired':'Scaduto · i tuoi progressi restano','premium.renews':'Si rinnova il',
    'premium.teaserTitle':'Questo è Premium','premium.askParent':'Chiedi a un adulto',
    'premium.teaser.quiz':'Questo quiz fa parte di Kwizillo Premium. Chiedi a un adulto di aprire tutti i mondi.',
    'premium.teaser.mega':'Il Mega Quiz fa parte di Kwizillo Premium. Chiedi a un genitore di aprire tutti i mondi.',
    'premium.teaser.memo':'Questo gioco di memoria fa parte di Kwizillo Premium. Chiedi a un adulto di aprire tutti i tabelloni.',
    'premium.teaser.math':'I livelli di calcolo più alti fanno parte di Kwizillo Premium. Chiedi a un adulto di aprirli.',
    'premium.teaser.facts':'Altre curiosità fanno parte di Kwizillo Premium. Chiedi a un adulto di aprirle tutte.',
    'premium.factsMore':'{n} curiosità in più con Premium',
    'premium.teaser.whoami':'Chi sono? in questo mondo fa parte di Kwizillo Premium. Chiedi a un adulto di aprire tutti i mondi.',
    'settings.terms':'Condizioni d’uso','settings.termsBody':'Kwizillo è un gioco educativo per bambini. Premium è un abbonamento addebitato da Apple che si rinnova automaticamente finché non lo disdici; puoi disdirlo quando vuoi negli abbonamenti Apple. Non ci sono pubblicità né acquisti dentro il gioco.',

    'onboarding.language.title':'Scegli la tua lingua',
    'onboarding.language.sub':'In quale lingua vuoi giocare?',
    'onboarding.name.title':'Come ti chiami?',
    'onboarding.name.sub':'Così possiamo salutarti bene.',
    'onboarding.name.placeholder':'Il tuo nome',
    'onboarding.name.hint':'Il tuo nome resta su questo dispositivo.',
    'onboarding.voice.title':'Chi ti aiuta?',
    'onboarding.voice.sub':'Scegli la tua guida. Puoi cambiare quando vuoi.',
    'onboarding.welcome.title':'Benvenuto, {name}!',
    'onboarding.welcome.sub':'La tua avventura comincia adesso. Pronto a esplorare?',
    'onboarding.welcome.cta':'Inizia l’avventura',
    'onboarding.next':'Continua',
    'onboarding.speech.welcome':'Sì, è tutto pronto! Vieni, ti mostro al volo dov’è ogni cosa.',
    'onboarding.speech.language':'Ciao! Sono Milo. Che lingua parli?',
    'onboarding.speech.name':'Piacere di conoscerti! Come ti chiami? Scrivilo qui.',
    'onboarding.speech.age':'E quanti anni hai?',
    'onboarding.speech.group':'In che classe sei?',
    'onboarding.speech.voice':'Chi vuoi come guida? Me, Luna, o preferisci il silenzio?',
    'onboarding.age.title':'Quanti anni hai?',
    'onboarding.age.sub':'Tocca la tua età.',
    'onboarding.age.years':'{n} anni',
    'onboarding.group.title':'In che classe sei?',
    'onboarding.group.sub':'Così scelgo domande adatte a te.',
    'tour.mega':'In cima c’è il Mega Quiz: ottanta domande da tutti i mondi, tutte mescolate!',
    'tour.worlds':'Questi sono gli otto mondi, dallo spazio e gli animali fino all’arte e allo sport. Tra poco toccherai un mondo e giocherai un quiz!',
    'tour.games':'E qui ci sono i giochi: Runner, Lingue, Calcolo, Chi sono?, Foto Zoom, Curiosità e Memo. Tra poco potrai provarli tutti!',
    'tour.facts':'E queste sono le Curiosità: centinaia di cose divertenti da scoprire!',
    'tour.hud':'In alto trovi il tuo livello, le tue monete e i giorni di fila. L’ingranaggio è per i tuoi genitori.',
    'tour.nav':'In basso trovi la collezione, i trofei e le statistiche. In Altro ci sono le impostazioni.',
    'tour.done':'Ora tocca a te! Tocca quello che vuoi. Buon divertimento, ti aiuto ogni volta che ti blocchi.',
    'tour.skip':'Salta',
    'tour.again':'Giro con {guide}',
    'tour.againSub':'{guide} ti mostra di nuovo dov’è ogni cosa.',
    'tour.pick':'Visita guidata',
    'tour.pickSub':'Scegli chi ti mostra dov’è ogni cosa.',
    'school.title':'Kwizillo a scuola',
    'school.codeAsk':'Qual è il codice della tua classe?',
    'school.codeHint':'È sulla lavagna o sulla tua scheda.',
    'school.next':'Avanti',
    'school.codeWrong':'Non conosciamo questo codice. Guarda di nuovo.',
    'school.whoAmI':'Chi sei?',
    'school.pictures':'Tocca le tue tre immagini',
    'school.picturesHint':'Nell’ordine giusto, come sulla tua scheda.',
    'school.picturesWrong':'Non sono le tue immagini. Riprova.',
    'school.locked':'Aspetta un momento e riprova.',
    'school.offline':'Nessuna connessione. Riprova.',
    'school.back':'Indietro',
    'school.logout':'Esci',
    'school.logoutSub':'Hai finito di giocare? Esci, così può giocare il prossimo.',
    'school.signedIn':'{name} · {class}',
    'players.title':'Giocatori su questo dispositivo',
    'players.sub':'Chi gioca su questo dispositivo.',
    'settings.feedback':'Idee e opinioni',
    'settings.feedbackSub':'Aiutaci a rendere Kwizillo ancora più bello',
    'feedback.title':'Raccontacelo!',
    'feedback.lead':'Hai un’idea, qualcosa non va o c’è qualcosa che ti piace tanto? Leggiamo tutto.',
    'feedback.kind.idea':'Idea',
    'feedback.kind.bug':'Commento',
    'feedback.kind.love':'Complimento',
    'feedback.placeholder':'Scrivi qui il tuo messaggio…',
    'feedback.empty':'Prima scrivi il tuo messaggio.',
    'feedback.send':'Invia',
    'feedback.note':'Un genitore invia il messaggio via e-mail. Il tuo nome non viene inviato.',
    'feedback.thanksTitle':'Grazie mille!',
    'feedback.thanks':'Leggiamo il tuo messaggio e lo usiamo per rendere Kwizillo ancora migliore, insieme a te.',
    'players.current':'sta giocando',
    'players.delete':'Elimina',
    'players.deleteTitle':'Eliminare {name}?',
    'players.deleteBody':'Tutto di {name} viene cancellato da questo dispositivo. Non si può annullare.',
    'players.deleteCard':'Elimina giocatore',
    'players.deleteCardSub':'Rimuovi un giocatore e tutto ciò che ha giocato da questo dispositivo',
    'players.deletePick':'Quale giocatore vuoi eliminare?',
    'settings.logout':'Esci',
    'settings.logoutSub':'Scegli un altro giocatore o iniziane uno nuovo.',

    'voice.milo':'Milo',
    'voice.milo.desc':'Allegro e vivace',
    'voice.luna':'Luna',
    'voice.luna.desc':'Calma e gentile',
    'voice.silent':'Silenzio',
    'voice.silent.desc':'Senza voce',
    'voice.milo.hello':'Ciao! Sono Milo. Pronto a giocare?',
    'voice.luna.hello':'Ciao! Sono Luna. Esploriamo insieme?',

    'home.greeting':'Ciao {name}!',
    'home.greetingAnon':'Ciao!',
    'home.level':'Livello {level}',
    'home.coins':'KwizCoins',
    'home.streak':'Giorni di fila',
    'home.pickWorld':'Scegli il tuo mondo',
    'home.cta':'Inizia l’avventura',
    'home.ctaSub':'Continua in {world}',
    'home.voiceLabel':'Voce',
    'home.languageLabel':'Lingua',

    'world.kicker':'MONDO KWIZILLO',
    'world.backHome':'Torna alla home',
    'world.mix':'Inizia il quiz misto',
    'world.mixSub':'Domande da tutti e quattro i temi',
    'world.quizNumber':'Quiz {n}',
    'world.topicPassed':'Superato',
    'world.topicPlayed':'Quiz {n} giocato · {correct}/{answered} giuste',
    'world.progressLine':'{passed} temi su {total} superati',
    'world.worldProgress':'{done} dei {total} quiz di questo mondo superati',
    'world.mixDone':'{n} giocati',

    'quiz.mixed':'Quiz misto',
    'mega.title':'Mega Quiz',
    'talen.title':'Lingue',
    'collection.tabWords':'🗣️ Parole',
    'collection.wordsEmpty':'Ancora nessuna parola',
    'collection.wordsEmptyBody':'Gioca una lezione in Lingue. Ogni parola che impari appare qui.',
    'collection.wordsCount':'{n} parole in {lang}. Tocca per sentirle.',
    'stats.talenLine':'{words} parole imparate · {lessons} lezioni',
    'achievement.talenFirst':'Prima lezione in Lingue',
    'achievement.talen10':'10 parole imparate',
    'talen.passport':'Passaporto delle lingue',
    'talen.passportSub':'Milo ti insegna parole in {lang}',
    'talen.passportSubLuna':'Luna ti insegna parole in {lang}',
    'talen.pickTitle':'Che lingua vuoi imparare?',
    'talen.pickSub':'Tocca una bandiera e senti come si dice ciao.',
    'talen.pickGo':'Si parte: {lang}!',
    'talen.switchLang':'Altra lingua',
    'talen.lang.en':'inglese',
    'talen.lang.nl':'olandese',
    'talen.lang.de':'tedesco',
    'talen.lang.fr':'francese',
    'talen.lang.es':'spagnolo',
    'talen.lang.it':'italiano',
    'talen.lang.pt':'portoghese',
    'talen.lang.da':'danese',
    'talen.lang.ru':'russo',
    'talen.lang.ar':'arabo',
    'talen.soon':'presto',
    'talen.soonLang':'Presto anche nella tua lingua',
    'talen.msgNew':'Ogni lezione dà un timbro. Comincia dagli animali!',
    'talen.msgPlayed':'Super! Il tuo timbro c’è. Gioca ancora per più stelle.',
    'talen.start':'Inizia la lezione',
    'talen.again':'Gioca ancora a {theme}',
    'talen.review':'Ripasso veloce',
    'talen.reviewSub':'{n} parole da ripassare',
    'talen.reviewDone':'Ottimo ripasso!',
    'talen.replay':'Ancora',
    'talen.listen':'Ascolta la parola',
    'talen.picture':'Immagine',
    'talen.means':'vuol dire {word}',
    'talen.round':'Turno {n} di {total}',
    'talen.firstTry':'giuste al primo colpo',
    'talen.learned':'Hai imparato queste parole. Tocca per sentirle.',
    'talen.theme.dieren':'Animali',
    'talen.theme.kleuren':'Colori',
    'talen.theme.eten':'Mangiare e bere',
    'talen.theme.getallen':'Numeri',
    'talen.theme.lichaam':'Corpo',
    'talen.theme.vervoer':'Trasporti',
    'talen.theme.sport':'Sport',
    'talen.theme.praten':'Parlare',
    'talen.section.words':'Parole',
    'talen.section.sentences':'Frasi',
    'talen.section.conversations':'Conversazioni',
    'talen.section.conversationsSub':'Ascolta e comprendi',
    'talen.section.speaking':'Parlare',
    'talen.section.speakingSub':'Ascolta e parla',
    'talen.conv.cat.intro':'Conoscersi',
    'talen.conv.cat.school':'Scuola',
    'talen.conv.cat.food':'Mangiare e bere',
    'talen.conv.cat.family':'Famiglia e amici',
    'talen.conv.cat.shop':'Fare la spesa',
    'talen.conv.cat.travel':'In viaggio',
    'talen.conv.listenAgain':'Riascolta',
    'talen.conv.listen':'Ascolta bene…',
    'talen.conv.round':'Conversazione {n} di {total}',
    'talen.conv.done':'Capisci già tutto!',
    'talen.speaking.set.basics':'Prime parole',
    'talen.speaking.set.greetings':'Saluti',
    'talen.speaking.set.sentences':'Frasi',
    'talen.speaking.permissionTitle':'Parlare con il microfono',
    'talen.speaking.permissionBody':'Per Parlare, Kwizillo usa il tuo microfono. Ascoltiamo solo mentre ti eserciti. La tua voce non viene salvata.',
    'talen.speaking.enableMic':'Attiva il microfono',
    'talen.speaking.sayIt':'Ripeti dopo di me',
    'talen.speaking.tapMic':'Tocca il microfono e dillo',
    'talen.speaking.listening':'Ti ascolto…',
    'talen.speaking.micActive':'Il microfono è acceso',
    'talen.speaking.goodPractice':'Ottimo esercizio!',
    'talen.speaking.notHeard':'Non ti ho ancora sentito. Riprova!',
    'talen.speaking.tryAgain':'Ancora una volta',
    'talen.speaking.next':'Avanti',
    'talen.speaking.micOff':'Il microfono è spento.',
    'talen.speaking.micOffBody':'Puoi esercitarti anche senza microfono: ascolta e dillo ad alta voce.',
    'talen.speaking.retry':'Riprova',
    'talen.speaking.withoutMic':'Esercitati senza microfono',
    'talen.speaking.iSaidIt':'L’ho detto',
    'talen.speaking.done':'Ottimo esercizio, bravo!',
    'talen.speaking.round':'Parola {n} di {total}',
    'talen.speakHead':'Io parlo',
    'talen.catThemes':"{n} temi",
    'talen.theme.huis':'Casa',
    'talen.theme.natuur':'Natura',
    'talen.theme.familie':'Famiglia',
    'talen.theme.kleding':'Vestiti',
    'talen.theme.school':'Scuola',
    'talen.theme.vakantie':'Vacanze',
    'talen.theme.mij':'Io',
    'talen.theme.vragen':'Domande',
    'talen.theme.gevoel':'Emozioni',
    'talen.theme.samen':'Giocare insieme',
    'talen.theme.mix':'Mix',
    'talen.done.dieren':'Conosci gli animali!',
    'talen.done.kleuren':'Conosci i colori!',
    'talen.done.eten':'Conosci cibi e bevande!',
    'talen.done.getallen':'Sai contare!',
    'talen.done.lichaam':'Conosci il tuo corpo!',
    'talen.done.vervoer':'Conosci i trasporti!',
    'talen.done.sport':'Conosci gli sport!',
    'talen.done.praten':'Sai parlare!',
    'talen.done.huis':'Conosci tutta la casa!',
    'talen.done.natuur':'Conosci la natura!',
    'talen.done.familie':'Conosci la famiglia!',
    'talen.done.kleding':'Conosci tutti i vestiti!',
    'talen.done.school':'Conosci le cose per la scuola!',
    'talen.done.vakantie':'Pronto per le vacanze!',
    'talen.done.mij':'Sai parlare di te!',
    'talen.done.vragen':'Sai fare domande!',
    'talen.done.gevoel':'Sai dire come ti senti!',
    'talen.done.samen':'Potete giocare insieme!',
    'talen.done.mix':'Tutto mescolato, e lo sai!',
    'jungle.bannerSub':'Corri, salta e prendi le monete',
    'settings.learnLang':'Lingua da imparare',
    'settings.learnLangSub':'La lingua che tuo figlio impara in Lingue',
    'premium.teaser.talen':'Questo tema fa parte di Kwizillo Premium. Gli animali sono gratis. Chiedi a un genitore di aprire tutti i temi.',
    'mega.sub':'{n} domande da tutti i mondi',
    'mega.rule':'Domande da tutti i {worlds} mondi: ne hai indovinate {score} su {total}.',
    'mega.again':'Un altro Mega Quiz',
    'mega.collectionLine':'Giocato {played} volte · migliore {best} su {total}',
    'quiz.progress':'Domanda {current} di {total}',
    'quiz.hint':'Indizio',
    'quiz.none':'Per questo tema non ci sono ancora domande.',
    'quiz.artAlt':'Illustrazione della domanda',
    'quiz.quizLabel':'Quiz {n}',
    'quiz.back':'Indietro',
    'quiz.explain':'Spiega',
    'quiz.timerAria':'Secondi rimasti',
    'feedback.timeKicker':'TEMPO SCADUTO!',
    'feedback.timeTitle':'La prossima volta più in fretta!',
    'settings.level':'Livello',
    'settings.levelSub':'{seconds} s a domanda · max {allowed} errori · {hints}',
    'settings.hintsFree':'indizi liberi',
    'settings.hintsN':'{n} indizi',
    'settings.hintsNone':'nessun indizio',
    'settings.readsQuestionOnly':'viene letta solo la domanda',
    'quiz.hintsSpent':'Non ci sono più indizi in questo quiz.',
    'quiz.noHints':'Il livello 6 non ha indizi.',
    'world.speech.enter':'[excited] {title}!',
    'settings.levelAuto':'Auto',
    'settings.share':'Condividi il punteggio',
    'settings.shareSub':'Manda il tuo risultato alla famiglia o agli amici',

    'hint.title':'Un piccolo indizio',
    'hint.kicker':'Consiglio di {topic}',
    'hint.ok':'Continua a pensare',
    'hint.close':'Chiudi l’indizio',
    'hint.fallback':'Guarda ancora bene la domanda e l’immagine.',
    'hint.alt':'Indizio visivo',

    'feedback.goodKicker':'GIUSTO!',
    'feedback.tryKicker':'PER POCO!',
    'feedback.goodTitle':'Ben giocato!',
    'feedback.tryTitle':'Hai ragionato bene!',
    'feedback.correctIs':'La risposta giusta è <strong>{answer}</strong>.',
    'feedback.thatsRight':'È proprio così!',
    'feedback.didYouKnow':'Lo sapevi?',
    'feedback.next':'Domanda successiva',
    'feedback.seeResult':'Vedi il risultato',
    'feedback.speech.good':'Bravo.',
    'feedback.speech.good.1':'Bravo!',
    'feedback.speech.good.2':'Ottimo, è proprio così!',
    'feedback.speech.good.3':'Centrato!',
    'feedback.speech.good.4':'Molto bene!',
    'feedback.speech.good.5':'Sì! Esatto!',
    'feedback.speech.good.6':'Bravissimo, bell’occhio!',
    'feedback.speech.good.7':'Fantastico!',
    'feedback.speech.good.8':'Wow, è corretto!',
    'feedback.speech.good.9':'Sì, così!',
    'feedback.speech.good.10':'Top!',
    'feedback.speech.good.11':'Perfetto!',
    'feedback.speech.good.12':'Molto bene, continua così!',
    'feedback.speech.good.13':'Stai andando alla grande!',
    'feedback.speech.good.14':'Ben fatto!',
    'feedback.speech.good.15':'Giustissimo!',
    'feedback.speech.good.16':'Colpito in pieno!',
    'feedback.speech.good.17':'Grande!',
    'feedback.speech.good.18':'Fortissimo!',
    'feedback.speech.good.19':'Spettacolo!',
    'feedback.speech.good.20':'Mitico!',
    'feedback.speech.good.21':'Bomba!',
    'feedback.speech.good.22':'Che forza!',
    'feedback.speech.good.23':'Esatto!',
    'feedback.speech.good.24':'Batti cinque!',
    'feedback.speech.good.25':'Pazzesco!',
    'feedback.speech.good.26':'Ottimo!',
    'feedback.speech.good.27':'Che bello!',
    'feedback.speech.good.28':'Super!',
    'feedback.speech.good.29':'Bel colpo!',
    'feedback.speech.good.30':'Sei un mito!',
    'feedback.speech.try.1':'Quasi. La risposta giusta è {answer}.',
    'feedback.speech.try.2':'Non proprio. La risposta giusta è {answer}.',
    'feedback.speech.try.3':'Bel tentativo! La risposta giusta è {answer}.',
    'feedback.speech.try.4':'Ops, per poco. La risposta giusta è {answer}.',
    'feedback.speech.try.5':'Mancato di poco. La risposta giusta è {answer}.',
    'feedback.speech.try.6':'Ops, questa era difficile! La risposta giusta è {answer}.',
    'feedback.speech.try.7':'Oh, quasi! La risposta giusta è {answer}.',
    'feedback.speech.try.8':'Mmm, non proprio. La risposta giusta è {answer}.',
    'feedback.speech.try.9':'Non fa niente! La risposta giusta è {answer}.',
    'feedback.speech.try.10':'La prossima volta andrà meglio! La risposta giusta è {answer}.',
    'feedback.speech.try.11':'Questa era difficile! La risposta giusta è {answer}.',
    'feedback.speech.try.12':'Per un pelo! La risposta giusta è {answer}.',
    'feedback.answerLabel':'La risposta giusta',
    'feedback.close':'Chiudi',
    'feedback.listening':'Sto ascoltando…',
    'quiz.repeat':'Di nuovo',
    'quiz.repeatAria':'Rileggi la domanda',
    'feedback.speech.try':'Quasi. La risposta giusta è {answer}.',
    'feedback.speech.fact':'{fact}',

    'result.kicker':'QUIZ FINITO',
    'result.title':'{score} giuste su {total}!',
    'result.score':'punteggio',
    'result.xp':'XP',
    'result.coins':'monete',
    'result.again':'Un altro quiz',
    'result.againNumbered':'Inizia il quiz {n}',
    'result.nextTopic':'Ora: {topic}',
    'result.finishWorld':'Inizia il quiz misto',
    'result.retryTopic':'Rifai questo tema',
    'result.retryNow':'Riprova',
    'memo.title':'Memo',
    'memo.pickTitle':'Scegli il tuo mondo',
    'game.mixAll':'Mix di tutti i mondi',
    'game.pickSub':'Scegli un mondo oppure giocali tutti insieme.',
    'memo.pickSub':'Trova le coppie · Livello {n}',
    'memo.otherWorld':'Un altro mondo',
    'memo.sub':'Trova le coppie',
    'memo.play':'Gioca a Memo',
    'memo.playSub':'Trova le coppie di {world}',
    'memo.level':'Livello {n}',
    'memo.pairs':'{found} coppie su {total}',
    'memo.boostTitle':'Boost d’oro!','memo.boostSub':'3 coppie di fila · +{xp} punti',
    'memo.moves':'{n} mosse',
    'memo.movesShort':'mosse',
    'memo.card':'Carta memo',
    'memo.hintLine':'Gira due carte e trova le coppie',
    'memo.none':'Per questo mondo non ci sono ancora abbastanza carte.',
    'memo.doneKicker':'MEMO COMPLETATO!',
    'memo.doneTitle':'Tutte le coppie trovate!',
    'memo.timeKicker':'TEMPO SCADUTO!',
    'memo.timeTitle':'Quasi tutte le coppie!',
    'memo.summary':'{pairs} coppie in {moves} mosse e {secs} secondi.',
    'memo.summaryTime':'{found} coppie trovate su {pairs}. Riprova!',
    'memo.again':'Ancora una volta',
    'memo.retry':'Riprova',
    'memo.toWorld':'Torna al mondo',
    'memo.speech.done':'Wow, hai trovato tutte le coppie! Che memoria!',
    'memo.speech.time':'Il tempo è scaduto. La prossima volta le trovi tutte!',
    'memo.modeTitle':'Come giochi?',
    'memo.solo':'Da solo','memo.soloSub':'Contro il tempo',
    'memo.duel':'Uno contro uno','memo.duelSub':'A turno: chi trova più coppie?',
    'memo.player1':'Giocatore 1','memo.player2':'Giocatore 2','memo.p2Label':'Chi gioca con te?',
    'memo.turn':'Tocca a {name}',
    'memo.duelKicker':'SFIDA MEMO',
    'memo.duelWin':'Vince {name}!','memo.duelTie':'Pareggio!',
    'memo.duelSummary':'{pairs} coppie in {moves} mosse.',
    'memo.rematch':'Rivincita',
    'memo.speech.win':'Abbiamo un vincitore! Bravi tutti e due!',
    'memo.speech.tie':'Pareggio! Avete tutti e due una gran memoria!',
    'home.playMore':'Gioca ancora',
    'math.title':'Calcolo',
    'facts.title':'Curiosità',
    'world.ruimte.short':'Spazio','world.dieren.short':'Animali','world.aarde.short':'Terra','world.geschiedenis.short':'Storia','world.wetenschap.short':'Scienza','world.kunst.short':'Arte','world.sport.short':'Sport','world.mysterie.short':'Mistero',
    'facts.tileSub':'Lo sapevi che…',
    'facts.sub':'{seen} di {total} scoperte',
    'facts.next':'Prossima curiosità',
    'facts.listen':'Leggi ad alta voce',
    'facts.kicker':'Lo sapevi che…',
    'facts.new':'Nuova!',
    'facts.allSeen':'Hai scoperto tutte le curiosità! Adesso ricominciano da capo.',
    'facts.more':'Altre curiosità',
    'math.sub':'Operazioni veloci',
    'math.play':'Calcolo',
    'math.playSub':'Dieci operazioni · Livello {n}',
    'math.progress':'Operazione {current} di {total}',
    'math.answerIs':'{sum} = {answer}',
    'math.resultTitle':'{score} operazioni giuste su {total}!',
    'math.again':'Dieci nuove operazioni',
    'math.half':'½ × {n}',
    'math.quarter':'¼ × {n}',
    'math.percent':'{p}% × {n}',
    'math.op.plus':'più',
    'math.op.minus':'meno',
    'math.op.times':'per',
    'math.op.divided':'diviso',
    'math.op.equals':'fa',
    'math.speech.twoStep':'{c} più {a} per {b}',
    'math.speech.half':'La metà di {n}',
    'math.speech.quarter':'Un quarto di {n}',
    'math.speech.percent':'{p} per cento di {n}',
    'math.money.title':'Contare i soldi',
    'chest.title':'Baule dei giochi',
    'chest.sub':'Scegli un gioco',
    'measure.title':'Misura & Pesa',
    'measure.sub':'Misura e confronta',
    'measure.tip':'Misura bene! Guarda dove comincia e dove finisce.',
    'measure.try':'Quasi! Guarda di nuovo con attenzione.',
    'measure.len.pencil':'Quanto è lunga la matita?',
    'measure.len.crayon':'Quanto è lungo il pastello?',
    'measure.len.straw':'Quanto è lunga la cannuccia?',
    'measure.len.brush':'Quanto è lungo il pennello?',
    'measure.len.ribbon':'Quanto è lungo il nastro?',
    'measure.len.nail':'Quanto è lungo il chiodo?',
    'measure.wt.apple':'Quanto pesa la mela?',
    'measure.wt.cheese':'Quanto pesa il pezzo di formaggio?',
    'measure.wt.melon':'Quanto pesa il melone?',
    'measure.wt.pumpkin':'Quanto pesa la zucca?',
    'measure.wt.book':'Quanto pesa il libro?',
    'measure.wt.potatoes':'Quanto pesa il sacco di patate?',
    'measure.wt.cat':'Quanto pesa il gatto?',
    'measure.vol.read':'Quanta acqua c’è nella caraffa graduata?',
    'measure.vol.more':'Quanto manca per arrivare a 1 litro?',
    'measure.cmp.longer':'Che cosa è più lungo?',
    'measure.cmp.shorter':'Che cosa è più corto?',
    'measure.cmp.heavier':'Che cosa è più pesante?',
    'measure.cmp.lighter':'Che cosa è più leggero?',
    'measure.cmp.more':'Dove ce n’è di più?',
    'measure.cmp.less':'Dove ce n’è di meno?',
    'measure.est.shoe':'Quanto è lunga una scarpa, più o meno?',
    'measure.est.door':'Quanto è alta una porta, più o meno?',
    'measure.est.apple':'Quanto pesa una mela, più o meno?',
    'measure.est.bag':'Quanto pesa uno zaino di scuola, più o meno?',
    'measure.est.glass':'Quanto contiene un bicchiere, più o meno?',
    'measure.est.bath':'Quanta acqua sta in una vasca da bagno, più o meno?',
    'measure.est.car':'Quanto è lunga una macchina, più o meno?',
    'measure.est.elephant':'Quanto pesa un elefante, più o meno?',
    'measure.est.bucket':'Quanto contiene un secchio, più o meno?',
    'measure.est.pencil':'Quanto è lunga una matita, più o meno?',
    'measure.convert':'Trasforma!',
    'measure.story':'Leggi bene e calcola!',
    'measure.story.bottle':'Una bottiglia contiene {a} litri. Riempi {n} bicchieri da {b} ml. Quanti ml restano?',
    'measure.story.ribbon':'Un nastro è lungo {a} metri. Tagli {n} pezzi da {b} cm. Quanti cm restano?',
    'measure.story.flour':'Un pacco di farina pesa {a} kg. Usi {n} volte {b} grammi. Quanti grammi restano?',
    'measure.story.map':'Sulla cartina 1 cm è {s} km nella realtà. La strada sulla cartina è {d} cm. Quanti km è lunga davvero?',
    'measure.obj.pencil':'matita',
    'measure.obj.crayon':'pastello',
    'measure.obj.straw':'cannuccia',
    'measure.obj.brush':'pennello',
    'measure.obj.ribbon':'nastro',
    'measure.obj.nail':'chiodo',
    'measure.obj.apple':'mela',
    'measure.obj.cheese':'formaggio',
    'measure.obj.melon':'melone',
    'measure.obj.pumpkin':'zucca',
    'measure.obj.book':'libro',
    'measure.obj.potatoes':'patate',
    'measure.obj.cat':'gatto',
    'measure.obj.elephant':'elefante',
    'measure.obj.mouse':'topo',
    'measure.obj.cow':'mucca',
    'measure.obj.chicken':'gallina',
    'measure.obj.strawberry':'fragola',
    'measure.obj.feather':'piuma',
    'measure.obj.glassRed':'bicchiere rosso',
    'measure.obj.glassBlue':'bicchiere blu',
    'measure.obj.package':'pacco',
    'measure.obj.schoolbag':'zaino',
    'measure.obj.rope':'corda',
    'measure.obj.bottle':'bottiglia',
    'measure.obj.carton':'brick di succo',
    'measure.u.mm':'mm',
    'measure.u.cm':'cm',
    'measure.u.m':'m',
    'measure.u.km':'km',
    'measure.u.g':'g',
    'measure.u.kg':'kg',
    'measure.u.ml':'ml',
    'measure.u.cl':'cl',
    'measure.u.l':'l',
    'math.pick.sub':'Cosa vuoi allenare?',
    'math.pick.sums':'Conti',
    'math.money.sub':'Conta le monete',
    'math.money.ok':'Fatto!',
    'math.money.delete':'Cancella',
    'math.money.ask':'Quanto fa in tutto?',
    'math.money.main.one':'{n} euro',
    'math.money.main.few':'{n} euro',
    'math.money.main.many':'{n} euro',
    'math.money.sub.one':'{n} centesimo',
    'math.money.sub.few':'{n} centesimi',
    'math.money.sub.many':'{n} centesimi',
    'math.money.and':'e',
    'math.speech.wrong':'Quasi. È {answer}.',
    'math.speech.done':'Che bei calcoli! Tutte le operazioni fatte.',
    'math.speech.fail':'Bel tentativo. Ancora una volta e ce la fai!',
    'math.hint.plus':'Conta da {a}: {b} in più.',
    'math.hint.minus':'Parti da {a} e conta {b} indietro.',
    'math.hint.times':'{a} per {b}: somma {b} esattamente {a} volte.',
    'math.hint.divided':'Quante volte ci sta {b} in {a}?',
    'math.hint.generic':'Calcola un passo alla volta.',
    'achievement.math3':'3 giri di calcolo superati',
    'stats.mathLine':'{played} giri giocati · {won} superati',
    'result.passKicker':'SUPERATO!',
    'result.failKicker':'NON ANCORA',
    'result.passRule':'Livello {niveau}: potevi sbagliare {allowed} volte e ne hai sbagliate {wrong}.',
    'result.failRule':'Livello {niveau}: puoi sbagliare {allowed} volte e ne hai sbagliate {wrong}. Rigioca questo tema!',
    'result.toHome':'Torna alla Home',

    'profile.title':'Il mio profilo',
    'profile.sub':'Il tuo nome, il tuo amico e le tue impostazioni',
    'profile.saveName':'Salva il nome',
    'profile.saved':'Salvato!',
    'profile.buddy':'Il mio amico',
    'profile.chooseBuddy':'Scegli l’amico',
    'profile.voice':'Chi legge ad alta voce?',
    'achievements.title':'Premi',
    'achievements.sub':'Le tue avventure e i tuoi traguardi',
    'achievements.summary':'{done}/{total} ottenuti',
    'achievements.summarySub':'Continua a esplorare per sbloccare nuovi premi.',
    'achievements.done':'Ottenuto!',
    'achievement.firstQuiz':'Primo quiz',
    'achievement.correct10':'10 risposte giuste',
    'achievement.correct50':'50 risposte giuste',
    'achievement.streak7':'7 giorni di fila',
    'achievement.cards5':'5 carte della conoscenza',
    'achievement.allWorlds':'Tutti i mondi visitati',
    'achievement.memo3':'3 partite di memo vinte',

    'collection.title':'La mia collezione',
    'collection.sub':'Tutto quello che hai scoperto',
    'collection.tabWorlds':'🌍 Mondi',
    'collection.tabCards':'🃏 Carte',
    'collection.tabMascots':'🐾 Amici',
    'collection.worldStat':'{correct}/{answered} giuste · {pct}%',
    'progress.worldLine':'{passed} quiz superati su {total} · {points} punti',
    'progress.overall':'In tutto {points} punti su {max}',
    'progress.overallSub':'Ogni quiz superato vale 25 punti: un mondo intero fa 100.',
    'collection.discovered':'★ Scoperto',
    'collection.unlockKicker':'NUOVO AMICO!',
    'collection.unlockLine':'Sbloccato con {n} risposte giuste.',
    'score.coinsAdded':'+{n} monete aggiunte',
    'score.coinsCapped':'Massimo giornaliero: {n} delle tue {got} monete sono state aggiunte.','collection.cardAdded':'{title} è ora nella tua collezione!',
    'collection.emptyTitle':'Ancora nessuna carta',
    'collection.emptyBody':'Rispondi giusto alle domande per collezionare carte della conoscenza.',
    'collection.mascotLocked':'ancora {n} risposte giuste',
    'collection.mascotShop':'Nel negozio: {n} monete',
    'collection.mascotActive':'Attivo ✓',
    'collection.mascotChoose':'Scegli l’amico',
    'collection.mascotCount':'{unlocked}/{total} amici sbloccati',

    'mascot.milo':'Milo',
    'mascot.milo.desc':'Il tuo amico robot furbo',
    'mascot.comet':'Cometa',
    'mascot.comet.desc':'Amico dello spazio',
    'mascot.pootje':'Zampetta',
    'mascot.pootje.desc':'Amico degli animali',
    'mascot.terra':'Terra',
    'mascot.terra.desc':'Protettrice della Terra',
    'mascot.sparky':'Sparky',
    'mascot.sparky.desc':'Amante degli esperimenti',
    'mascot.lumi':'Lumi',
    'mascot.lumi.desc':'Cercatrice di misteri',
    'mascot.nova':'Nova','mascot.nova.desc':'Viaggiatrice tra le stelle',
    'mascot.kiko':'Kiko','mascot.kiko.desc':'Esploratore della giungla',
    'mascot.pip':'Pip','mascot.pip.desc':'Spericolato del ghiaccio',
    'mascot.ravi':'Ravi','mascot.ravi.desc':'Inventore in erba',
    'mascot.flora':'Flora','mascot.flora.desc':'Amica della natura',
    'mascot.draco':'Draco','mascot.draco.desc':'Draghetto del castello',
    'mascot.mike':'Mike','mascot.mike.desc':'Fan della musica con le cuffie',
    'mascot.zibo':'Zibo','mascot.zibo.desc':'Allegro viaggiatore spaziale',
    'mascot.leo':'Leo','mascot.leo.desc':'Leone sportivo con medaglia',
    'mascot.pixi':'Pixi','mascot.pixi.desc':'Volpe artista con pennello',
    'mascot.olli':'Olli','mascot.olli.desc':'Gufo furbo con occhiali da pilota',
    'mascot.finn':'Finn','mascot.finn.desc':'Delfino giocherellone',
    'mascot.ember':'Ember','mascot.ember.desc':'Piccolo drago viola',

    'stats.title':'Dati',
    'stats.sub':'Progressi veri, dalle domande che hai giocato',
    'stats.heroTitle':'Le tue conoscenze crescono',
    'stats.heroSub':'{answered} domande risposte · {quizzes} {quizWord} giocati',
    'stats.correctShort':'giuste',
    'stats.xpTotal':'XP totali',
    'stats.coins':'KwizCoins',
    'stats.streak':'Giorni di fila',
    'stats.cards':'Carte',
    'stats.perWorld':'Per mondo',
    'stats.games':'Giochi',
    'stats.playedLine':'{played} partite giocate',
    'stats.runnerLine':'{played} corse · {coins} monete raccolte',
    'stats.memoBest':'{n} mosse',
    'stats.memoLine':'{played} partite di memo giocate · {won} vinte',
    'share.text':'{name} gioca a Kwizillo! Livello {level}, {correct} risposte giuste, {cards} carte della conoscenza. Quiz migliore: {best}. Vuoi giocare anche tu?',
    'share.copied':'Testo copiato: incollalo in un messaggio.',
    'result.share':'Condividi il punteggio',
    'stats.worldLine':'{correct} giuste su {answered} · {quizzes} {quizWord}',
    'stats.quizOne':'quiz',
    'stats.quizMany':'quiz',

    'settings.title':'Area genitori',
    'settings.sub':'Impostazioni per una bella esperienza di gioco',
    'settings.group':'Classe',
    'settings.groupSub':'Regola la difficoltà',
    'settings.groupValue':'{n}ª classe',
    'settings.language':'Lingua',
    'settings.languageSub':'Scegli la lingua del gioco',
    'settings.sound':'Audio, musica e voce',
    'settings.soundVoiceOff':'Voce spenta',
    'settings.soundVoiceOn':'Voce: {voice}',
    'settings.soundMusic':'musica {state}',
    'settings.on':'accesa',
    'settings.off':'spenta',
    'settings.timeLimit':'Timer della domanda',
    'settings.timeLimitOff':'Spento',
    'settings.timeLimitValue':'{n} secondi a domanda in questo livello',
    'settings.privacy':'Privacy e sicurezza',
    'privacy.sub':'Che cosa salva il gioco e che cosa non fa',
    'privacy.updated':'Aggiornato: {date}',
    'privacy.device':'Su questo dispositivo',
    'privacy.deviceBody':'Tutto questo sta nella memoria dell’app su questo dispositivo. Non va a Kwizillo né a nessun altro e sparisce appena cancelli l’app o cancelli tutto qui sotto.',
    'privacy.itemName':'Nome: {value}',
    'privacy.itemSettings':'Lingua, voce, audio, classe e livello',
    'privacy.itemProgress':'Progressi: {answered} domande, {correct} giuste, {cards} carte',
    'privacy.itemPremium':'Se Premium è attivo (questo arriva dall’App Store)',
    'privacy.leaves':'Che cosa lascia il dispositivo',
    'privacy.leavesBody':'Solo la frase che Milo o Luna legge ad alta voce. Va al nostro server e da lì al servizio vocale ElevenLabs. È sempre testo del gioco: una domanda, una risposta, un indizio o una curiosità. Mai il nome di tuo figlio e mai qualcosa che tuo figlio scrive.',
    'privacy.none':'Che cosa non fa l’app',
    'privacy.noneBody':'Niente pubblicità. Niente analisi o tracciatori di terzi. Nessun account, indirizzo email o password. Niente posizione, contatti, fotocamera o microfono. Nessun cookie.',
    'privacy.keep':'Conservare e cancellare',
    'privacy.keepBody':'Quello che sta su questo dispositivo resta finché non lo cancelli; noi non ne teniamo copia altrove. Il nostro server conserva l’audio già creato (frasi del gioco, nessun dato personale) per non rifare due volte la stessa frase, e tiene per poco in memoria l’indirizzo IP di una richiesta per evitare abusi.',
    'privacy.erase':'Cancella tutti i dati',
    'privacy.eraseSub':'Nome, impostazioni e progressi su questo dispositivo',
    'privacy.eraseTitle':'Cancellare tutto?',
    'privacy.eraseBody':'Nome, impostazioni, progressi, carte e statistiche spariscono da questo dispositivo. Un Premium acquistato resta sul tuo account App Store e torna con «Ripristina acquisti».',
    'privacy.eraseConfirm':'Sì, cancella tutto',
    'privacy.contact':'Domande sulla privacy?',
    'privacy.contactSub':'Scrivi a {email}',
    'privacy.noAccount':'Kwizillo funziona senza account: da noi non c’è niente da registrare né da cancellare.',
    'score.points':'punti',
    'score.practice':'punti di allenamento',
    'score.dayFull':'massimo del giorno raggiunto',
    'score.title':'Record',
    'score.sub':'I tuoi punti migliori in ogni periodo',
    'score.now':'ora',
    'score.best':'record',
    'score.run':'Questo esercizio',
    'score.day':'Oggi',
    'score.week':'Questa settimana',
    'score.month':'Questo mese',
    'score.year':'Quest’anno',
    'score.allTime':'Di sempre',
    'score.todayPoints':'{n} punti su {max} oggi',
    'score.todayCoins':'{n} monete su {max} oggi',
    'score.capNote':'Ogni giorno c’è un massimo di punti e monete, e una domanda già indovinata dà punti di allenamento. Così un record vale davvero.',
    'shop.tab':'🛒 Negozio',
    'shop.title':'Negozio',
    'shop.sub':'Paga con le monete dei giochi',
    'shop.buy':'Compra',
    'shop.owned':'Già tuo','shop.earned':'Conquistata',
    'shop.price':'{n} monete',
    'shop.need':'Ti mancano {n} monete',
    'shop.confirmTitle':'Comprare {item}?',
    'shop.confirmBody':'Costa {n} monete. Poi {item} è tuo per sempre.',
    'shop.bought':'{item} è tuo!',
    'shop.cards':'Carte dorate',
    'shop.mascots':'Amici',
    'shop.goldCard':'{world} dorato',
    'shop.goldCardSub':'Una carta luccicante per la tua collezione',
    'shop.earnHint':'Le monete si guadagnano nel Runner e negli altri giochi.',
    'shop.empty':'Comprato tutto! Il negozio è vuoto.',
    'result.worldLevelUp':'🎉 {world} sale al livello {niveau}!',
    'result.worldMastered':'🏆 {world} completato a tutti i livelli!',
    'result.goldCardEarned':'Hai conquistato la carta dorata di {world}!',
    'result.goldCardSpeech':'Wow! Hai finito {world} per intero. La carta dorata è tua!',
    'settings.levelWorlds':'Livello per mondo',
    'settings.levelWorldsSub':'Un mondo sale da solo quando superi tutti e quattro i suoi quiz.',
    'settings.levelMath':'Livello di gioco',
    'settings.timeLimitPerWorld':'Il tempo per domanda segue il livello.',
    'settings.reset':'Azzera i progressi',
    'settings.resetSub':'Ricominciare da zero',
    'settings.resetTitle':'Azzerare i progressi?',
    'settings.resetBody':'XP, monete, carte, dati e progressi tornano all’inizio.',
    'settings.resetConfirm':'Sì, azzera',
    'gate.title':'Una domandina per un adulto',
    'gate.body':'Quanto fa {a} × {b}?',
    'gate.placeholder':'Risposta',
    'gate.wrong':'Non è giusto. Riprova.',
    'gate.continue':'Continua',

    'sound.kicker':'IMPOSTAZIONI',
    'sound.title':'🔊 Audio e musica',
    'sound.fx':'✨ Effetti sonori',
    'sound.music':'🎵 Musica di sottofondo',
    'sound.test':'Prova',
    'sound.pickMusic':'Scegli la tua musica',
    'sound.voiceGuide':'Guida vocale',
    'track.home':'Isole',
    'track.space':'Spazio',
    'track.jungle':'Giungla',
    'track.earth':'Terra',
    'track.history':'Storia',
    'track.science':'Scienza',
    'track.mystery':'Mistero',
    'track.play':'Giochi',

    'intro.skip':'Salta l’intro',
    'welcome.back.title':'Ciao {name}!',
    'welcome.back.sub':'Pronto a continuare?',
    'welcome.back.continue':'Continua a giocare',
    'welcome.back.other':'Gioca qualcun altro',
    'welcome.back.where':'Eri arrivato qui',
    'welcome.pick.title':'Chi gioca?',
    'welcome.pick.new':'Nuovo giocatore',
    'welcome.pick.back':'Indietro',
    'intro.tapToStart':'Tocca per iniziare',
    'intro.tapForSound':'Tocca per l’audio',

    // Blokkenpret (games-blokken.js). BONUS BOOST! and MEGA ZET! are the feature names in every language.
    'blokken.title':'Blocchimania',
    'blokken.pickLevel':'Scegli un livello',
    'blokken.levelsDone':'{n} livelli superati su {total}',
    'blokken.tileOpen':'Livello {n}',
    'blokken.tileDone':'Livello {n}, superato',
    'blokken.tileLocked':'Il livello {n} è chiuso. Gioca prima il livello {prev}.',
    'blokken.levelOf':'Livello {n} di {total}',
    'blokken.levels':'Livelli',
    'blokken.toGames':'Torna ai giochi',
    'blokken.sound':'Suono sì o no',
    'blokken.drag':'Trascina le forme',
    'blokken.fill':'Riempi tutta la figura!',
    'blokken.placed':'{n} su {total} messi',
    'blokken.trayLabel':'Blocchi da mettere',
    'blokken.boardRole':'tavola del puzzle',
    'blokken.boardLabel':'La figura da riempire',
    'blokken.undo':'Annulla',
    'blokken.restart':'Ricomincia',
    'blokken.help':'Aiuto',
    'blokken.rotate':'Gira',
    'blokken.boost':'BONUS BOOST!',
    'blokken.boostUse':'Usa il boost',
    'blokken.boostEarned':'Hai guadagnato un boost!',
    'blokken.boostHint':'Questo posto va bene!',
    'blokken.boostMeter':'Boost: {n} blocchi su {total} messi da te',
    'blokken.boostUsedLabel':'Boost usato',
    'blokken.boostNeedMove':'Così non si può finire. Prima bisogna togliere un blocco.',
    'blokken.boostIntroTitle':'Novità: BONUS BOOST!',
    'blokken.boostIntro':'Metti da solo tre blocchi diversi e guadagni un boost che ti mostra un buon posto.',
    'blokken.rotateIntroTitle':'Novità: girare!',
    'blokken.rotateIntro':'Tocca un blocco e poi Gira. Tocca ancora il blocco per continuare a girare. Tastiera: R.',
    'blokken.ok':'Ok',
    'blokken.guide':'Trascina il blocco nel posto che brilla!',
    'blokken.helpPlace':'Questo blocco va nel posto che brilla.',
    'blokken.helpTurn':'Prima giralo come vedi.',
    'blokken.helpTakeBack':'Così non va. Togli questo blocco.',
    'blokken.takeBack':'Togli',
    'blokken.cancel':'Chiudi',
    'blokken.restartAsk':'Ricominciare?',
    'blokken.restartSub':'Tutti i blocchi tornano nel vassoio.',
    'blokken.restartYes':'Sì, ricomincia',
    'blokken.restartNo':'No, continua',
    'blokken.mega':'MEGA ZET!',
    'blokken.done':'Livello superato!',
    'blokken.next':'Livello successivo',
    'blokken.replay':'Gioca ancora',
    'blokken.toLevels':'Ai livelli',
    'blokken.allDone':'Tutti i 10 livelli superati!',
    'blokken.badge':'Stella d’oro di Blocchimania',
    'blokken.playAgain':'Gioca ancora',
    'blokken.backToGames':'Torna ai giochi',
    'blokken.pieceName':'Blocco {n}: {color}, {symbol}',
    'blokken.inTray':'nel vassoio',
    'blokken.onBoard':'sulla tavola',
    'blokken.saidPlaced':'{piece} è sulla tavola.',
    'blokken.noFit':'Qui non va. Prova un altro posto.',
    'blokken.kbHelp':'Frecce: spostare. Invio: mettere. R: girare. Esc: fermare.',
    'blokken.kbPicked':'{piece} preso.',
    'blokken.kbFits':'Colonna {x}, riga {y}: va bene.',
    'blokken.kbNoFit':'Colonna {x}, riga {y}: non va.',
    'blokken.color.red':'rosso',
    'blokken.color.orange':'arancione',
    'blokken.color.yellow':'giallo',
    'blokken.color.green':'verde',
    'blokken.color.cyan':'azzurro',
    'blokken.color.blue':'blu',
    'blokken.color.purple':'viola',
    'blokken.color.pink':'rosa',
    'blokken.color.lime':'verde lime',
    'blokken.sym.star':'stella',
    'blokken.sym.heart':'cuore',
    'blokken.sym.dot':'pallino',
    'blokken.sym.diamond':'rombo',
    'blokken.sym.moon':'luna',
    'blokken.sym.drop':'goccia',
    'blokken.sym.flower':'fiore',
    'blokken.sym.triangle':'triangolo',
    'blokken.sym.ring':'anello'
  };
})();
