#!/usr/bin/env node
// Which picture a question shows while it is on screen, decided by eye.
//
//   node tools/art-plan.cjs            → question-art-plan.js from tools/art-audit/*.json
//   node tools/art-plan.cjs --check    → fails when question-art-plan.js is stale or a question is missing
//
// Until 2026-10-06 the app guessed: a short noun as the answer meant "the picture
// shows the answer", and then it borrowed a neighbour's picture (a rugby ball for
// a question about a tennis ball) or showed the topic. Every one of the 1280
// questions has since been looked at, picture by picture (tools/art-audit/):
//   own_fits     the question's own picture shows its subject
//   own_reveals  a child could pick the right option from that picture
//   use          own | safe (the question-only picture in assets/questions/s/) | new
// The plan is one letter per question id:
//   o  the own picture
//   s  the question-only picture (assets/questions/s/<id>.jpg)
//   n  a new question-only picture is needed; until it is drawn, the topic's picture
// Upper case (S, N) marks an own picture that does not fit its question: it is
// then not shown on the feedback card either.
// A question-only picture that has been drawn since the audit wins over "n".
const fs = require('fs'); const path = require('path');
const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'tools', 'art-audit');
const OUT = path.join(ROOT, 'question-art-plan.js');
const { loadBanks } = require('../tests/langs.js');

const rows = fs.readdirSync(DIR).filter(f => f.endsWith('.json')).flatMap(f => JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')));
const byId = new Map(rows.map(r => [r.id, r]));
const ids = loadBanks().banks.nl.map(q => q.id);
const missing = ids.filter(id => !byId.has(id));
const plan = {};
for (const id of ids) {
  const r = byId.get(id); if (!r) continue;
  const safeOnDisk = fs.existsSync(path.join(ROOT, 'assets', 'questions', 's', `${id}.jpg`));
  let use = r.use === 'own' ? 'o' : r.use === 'safe' ? 's' : 'n';
  // A question-only picture drawn after the audit for a question that needed one.
  if (use === 'n' && safeOnDisk && r.safe_fits !== false) use = 's';
  if (use === 's' && !safeOnDisk) use = 'n';
  plan[id] = r.own_fits === false && use !== 'o' ? use.toUpperCase() : use;
}
const count = l => Object.values(plan).filter(v => v.toLowerCase() === l).length;
const body = `(()=>{
  const K=window.KWIZILLO_M1=window.KWIZILLO_M1||{};
  // Generated by tools/art-plan.cjs from tools/art-audit/ — never edit by hand.
  // o: own picture · s: question-only picture · n: a new picture is needed (topic picture until then)
  // Upper case: the own picture does not fit the question (also kept off the feedback card).
  K.ART_PLAN=${JSON.stringify(plan)};
})();
`;
if (process.argv.includes('--check')) {
  const now = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (missing.length) { console.error(`art plan: ${missing.length} questions not audited, e.g. ${missing.slice(0, 5).join(', ')}`); process.exit(1) }
  if (now !== body) { console.error('question-art-plan.js is stale: run node tools/art-plan.cjs'); process.exit(1) }
  console.log(`art plan: ${ids.length} questions — own ${count('o')}, question-only ${count('s')}, new picture needed ${count('n')} ✔`);
  process.exit(0);
}
fs.writeFileSync(OUT, body);
console.log(`question-art-plan.js: own ${count('o')}, question-only ${count('s')}, new picture needed ${count('n')}${missing.length ? `, NOT AUDITED ${missing.length}` : ''}`);
