#!/usr/bin/env node
// Which picture a question shows while it is on screen, decided by eye.
//
//   node tools/art-plan.cjs            → question-art-plan.js from tools/art-audit/*.json
//   node tools/art-plan.cjs --check    → fails when question-art-plan.js is stale or a question is missing
//
// Until 2026-10-06 the app guessed: a short noun as the answer meant "the picture
// shows the answer", and then it borrowed a neighbour's picture (a rugby ball for
// a question about a tennis ball) or showed the topic. Every one of the 1280
// questions has since been looked at, picture by picture (tools/art-audit/):
//   own_fits     the question's own picture shows its subject
//   own_reveals  a child could pick the right option from that picture
//   use          own | safe (the question-only picture in assets/questions/s/) | new
// The plan is one letter per question id:
//   o  the own picture
//   s  the question-only picture (assets/questions/s/<id>.jpg)
//   n  a new question-only picture is needed; until it is drawn, the topic's picture
// Upper case (S, N) marks an own picture that does not fit its question: it is
// then not shown on the feedback card either.
// A question-only picture that has been drawn since the audit wins over "n".
const fs = require('fs'); const path = require('path');
const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'tools', 'art-audit');
const OUT = path.join(ROOT, 'question-art-plan.js');
const { loadBanks } = require('../tests/langs.js');

const rows = fs.readdirSync(DIR).filter(f => f.endsWith('.json') && !f.startsWith('_')).flatMap(f => JSON.parse(fs.readFileSync(path.join(DIR, f), 'utf8')));
// Question-only pictures drawn after the audit (2026-10-07, Higgsfield, each checked by eye
// against its question and options): they replace whatever was in assets/questions/s/ before.
const drawnFile = path.join(DIR, '_drawn.json');
const drawn = new Set(fs.existsSync(drawnFile) ? JSON.parse(fs.readFileSync(drawnFile, 'utf8')) : []);
const byId = new Map(rows.map(r => [r.id, r]));
const ids = loadBanks().banks.nl.map(q => q.id);
const missing = ids.filter(id => !byId.has(id));
const plan = {};
for (const id of ids) {
  const r = byId.get(id); if (!r) continue;
  const safeOnDisk = fs.existsSync(path.join(ROOT, 'assets', 'questions', 's', `${id}.jpg`));
  let use = r.use === 'own' ? 'o' : r.use === 'safe' ? 's' : 'n';
  // A question-only picture drawn after the audit for a question that needed one.
  if (use === 'n' && safeOnDisk && (r.safe_fits !== false || drawn.has(id))) use = 's';
  if (use === 's' && !safeOnDisk) use = 'n';
  plan[id] = r.own_fits === false && use !== 'o' ? use.toUpperCase() : use;
}
// Pictures that show the answer itself, for the games that put a name under a
// picture (Memo, Fotozoom, Wat ben ik?): the own picture fits, gives the answer
// away, and the answer is a short name of a thing — not a number, not a reason.
// numbers, also compound ones ("Vierenzestig jaar"); "een" only as "één"
const NUMBER = /^(nul|één|twee|drie|vier|vijf|zes|zeven|acht|negen|tien|elf|twaalf|dertien|veertien|vijftien|zestien|twintig|dertig|veertig|vijftig|zestig|zeventig|tachtig|negentig|honderd|duizend|\d)/i;
const NOT_A_THING = /^(met je|met de|door|om|voor|in|op|naar|uit|bij|zonder|alle|alleen|ze|zij|het is|dan|omdat|ja|nee)\b|\b(wordt|worden|is|zijn|verdedigen|maken|doen)$|\b(wordt|worden)\b/i;
const nl = Object.fromEntries(loadBanks().banks.nl.map(q => [q.id, q]));
const answerPic = ids.filter(id => {
  const r = byId.get(id), a = String(nl[id]?.answer || '').trim();
  if (!r || r.own_fits === false || !r.own_reveals) return false;
  if (NUMBER.test(a) || NOT_A_THING.test(a)) return false;
  const n = a.split(/\s+/).length;
  return (a.length <= 18 && n <= 2) || (n <= 3 && /^(de|het|een)\s/i.test(a));
});
const count = l => Object.values(plan).filter(v => v.toLowerCase() === l).length;
const body = `(()=>{
  const K=window.KWIZILLO_M1=window.KWIZILLO_M1||{};
  // Generated by tools/art-plan.cjs from tools/art-audit/ — never edit by hand.
  // o: own picture · s: question-only picture · n: a new picture is needed (topic picture until then)
  // Upper case: the own picture does not fit the question (also kept off the feedback card).
  K.ART_PLAN=${JSON.stringify(plan)};
  // Own pictures that show the answer itself (a short name of a thing): what Memo, Fotozoom and Wat ben ik? may use.
  K.ANSWER_PICTURES=new Set(${JSON.stringify(answerPic)});
})();
`;
if (process.argv.includes('--check')) {
  const now = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (missing.length) { console.error(`art plan: ${missing.length} questions not audited, e.g. ${missing.slice(0, 5).join(', ')}`); process.exit(1) }
  if (now !== body) { console.error('question-art-plan.js is stale: run node tools/art-plan.cjs'); process.exit(1) }
  console.log(`art plan: ${ids.length} questions — own ${count('o')}, question-only ${count('s')}, new picture needed ${count('n')}; ${answerPic.length} pictures show their answer ✔`);
  process.exit(0);
}
fs.writeFileSync(OUT, body);
console.log(`question-art-plan.js: own ${count('o')}, question-only ${count('s')}, new picture needed ${count('n')}, ${answerPic.length} show their answer${missing.length ? `, NOT AUDITED ${missing.length}` : ''}`);
