#!/usr/bin/env node
// Turns content/ into the question files the app loads.
//
//   node tools/content-build.cjs           → writes questions-more*.js
//   node tools/content-build.cjs --check   → fails if those files are out of date
//
// content/<world>/<topic>.json is where a question is written, reviewed and
// translated; questions-more-<lang>.js is what the browser reads. A question is
// only built once every language has it, because the ten banks must keep the
// same ids — progress is stored per id, and a child who switches language would
// otherwise lose it. Half-translated work stays in content/ and is reported.
//
// The rows carry their own difficulty as a seventh field, which is what lets a
// topic hold ten questions on each of the four difficulties instead of the ten
// easy and ten hard that position alone could express.
const fs = require('fs');
const path = require('path');
const { LANGS } = require('../tests/langs.js');

const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'content');
const check = process.argv.includes('--check');
const fileFor = lang => path.join(ROOT, lang === 'nl' ? 'questions-more.js' : `questions-more-${lang}.js`);

const docs = fs.existsSync(DIR)
  ? fs.readdirSync(DIR, { withFileTypes: true }).filter(d => d.isDirectory())
      .flatMap(d => fs.readdirSync(path.join(DIR, d.name)).filter(f => f.endsWith('.json'))
        .map(f => JSON.parse(fs.readFileSync(path.join(DIR, d.name, f), 'utf8'))))
  : [];

const ready = [], waiting = [];
for (const doc of docs) {
  for (const q of doc.questions || []) {
    const missing = LANGS.filter(l => !q.text?.[l]);
    (missing.length ? waiting : ready).push({ ...q, world: doc.world, topic: doc.topic, missing });
  }
}
// Order inside a topic is what gives a question its id, so it is the id that
// decides the order, not the order of the file.
ready.sort((a, b) => a.id.localeCompare(b.id));

const esc = s => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r?\n/g, ' ') + "'";
const row = (t, difficulty) => `[${esc(t.prompt)},${esc(t.answer)},[${t.wrong.map(esc).join(',')}],${esc(t.hint)},${esc(t.explanation)},${esc(t.fact)},${difficulty}]`;

const render = lang => {
  const tree = {};
  for (const q of ready) ((tree[q.world] ||= {})[q.topic] ||= []).push(row(q.text[lang], q.difficulty));
  const body = Object.entries(tree).map(([world, topics]) =>
    `    ${world}: {\n` + Object.entries(topics).map(([topic, rows]) =>
      `      ${topic}: [\n        ${rows.join(',\n        ')}\n      ]`).join(',\n') + `\n    }`).join(',\n');
  return `(() => {
  // Generated by tools/content-build.cjs from content/. Do not edit by hand:
  // change the question in content/<world>/<topic>.json and run the tool again.
  // Rows continue after the twenty a topic already has, and each one states its
  // own difficulty in the seventh field.
  window.KWIZILLO_MORE_${lang.toUpperCase()} = {
${body}
  };
})();
`;
};

if (!ready.length) {
  console.log(`content/: ${waiting.length} question(s), none translated into all ${LANGS.length} languages yet — nothing to build.`);
  const perLang = {};
  for (const q of waiting) for (const l of q.missing) perLang[l] = (perLang[l] || 0) + 1;
  console.log('nog te vertalen: ' + Object.entries(perLang).map(([l, n]) => `${l} ${n}`).join(', '));
  for (const lang of LANGS) if (fs.existsSync(fileFor(lang))) { if (check) { console.error(`${path.basename(fileFor(lang))} is stale`); process.exit(1) } fs.unlinkSync(fileFor(lang)); console.log(`verwijderd: ${path.basename(fileFor(lang))}`) }
  process.exit(0);
}

let stale = 0;
for (const lang of LANGS) {
  const out = fileFor(lang), text = render(lang);
  const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
  if (current === text) continue;
  stale++;
  if (!check) fs.writeFileSync(out, text);
}
if (check && stale) { console.error(`${stale} question file(s) out of date — run: node tools/content-build.cjs`); process.exit(1) }

// The browser needs the new layer before the banks that consume it.
const indexPath = path.join(ROOT, 'index.html');
let index = fs.readFileSync(indexPath, 'utf8');
const tags = LANGS.map(l => `  <script src="${path.basename(fileFor(l))}"></script>`).join('\n');
if (!index.includes(path.basename(fileFor('nl')))) {
  index = index.replace('  <script src="questions.js"></script>', tags + '\n  <script src="questions.js"></script>');
  if (!check) fs.writeFileSync(indexPath, index);
  console.log('index.html: de nieuwe laag wordt nu ingeladen');
}
console.log(`${ready.length} vraag/vragen gebouwd naar ${LANGS.length} talen${waiting.length ? `, ${waiting.length} wachten nog op vertaling` : ''}.`);
