#!/usr/bin/env node
// The guides' talking clips: lip-synced videos of the fixed onboarding and tour
// lines, one per guide, line and language, under assets/<guide>/talk/<lang>/<key>.mp4.
//
//   node tools/guide-talks.js lines [guide]        print the lines to render (from i18n)
//   node tools/guide-talks.js encode <src.mp4> <guide> <lang> <key>
//                                                  downscale a rendered clip into place (avconvert, macOS)
//   node tools/guide-talks.js manifest             rewrite guide-talks.js from what is on disk
//
// Milo hosts the whole first run, so he has every line; Luna takes over at the
// guide step, so she has her hello, the welcome and the tour. The clips are made
// on the ElevenLabs flow "Kwizillo Milo praat" (SyUhvtqjRCbWNR70n0Wq): a tts node
// (eleven_v3, the guide's voice for the language, the line as prompt) feeding a
// bytedance-omnihuman-v1.5 avatar node together with the guide's still
// (assets/mascots/<guide>/talk-base.png). The app falls back to the still pose
// plus live speech for any line without a clip.
const fs = require('fs'); const path = require('path'); const vm = require('vm'); const { execFileSync } = require('child_process');
const ROOT = path.join(__dirname, '..');
const KEYS = {
  milo: ['language', 'name', 'age', 'group', 'voice', 'hello', 'welcome', 'worlds', 'games', 'facts', 'hud', 'nav', 'done'],
  luna: ['hello', 'welcome', 'worlds', 'games', 'facts', 'hud', 'nav', 'done']
};
const GUIDES = Object.keys(KEYS);
// The full-body render each guide's clips start from (the cut-out shown before a clip plays).
const BASE_POSE = { milo: 'talk', luna: 'talk' };
const LANGS = ['nl', 'en', 'pt'];
const dirOf = guide => path.join(ROOT, 'assets', guide, 'talk');
const [cmd, ...args] = process.argv.slice(2);

function i18n() {
  const ctx = { window: {}, document: { documentElement: {} } }; vm.createContext(ctx);
  ctx.window.KWIZILLO_M1 = { state: { language: 'nl' } };
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'i18n.js'), 'utf8'), ctx);
  return ctx.window.KWIZILLO_M1;
}
const keyFor = (guide, k) => k === 'hello' ? `voice.${guide}.hello` : ['worlds', 'games', 'facts', 'hud', 'nav', 'done'].includes(k) ? `tour.${k}` : `onboarding.speech.${k}`;

if (cmd === 'lines') {
  const K = i18n();
  const out = {};
  for (const guide of args[0] ? [args[0]] : GUIDES) {
    if (!KEYS[guide]) { console.error(`unknown guide ${guide}`); process.exit(1); }
    out[guide] = {};
    for (const lang of LANGS) { K.state.language = lang; out[guide][lang] = {}; for (const k of KEYS[guide]) out[guide][lang][k] = K.t(keyFor(guide, k)); }
  }
  console.log(JSON.stringify(out, null, 2));
} else if (cmd === 'encode') {
  // <src.mp4> is the green-screen render; keyclip.cjs turns it into <key>.webm (VP9+alpha) and <key>.mp4 (HEVC+alpha).
  const [src, guide, lang, key] = args;
  if (!src || !KEYS[guide] || !LANGS.includes(lang) || !KEYS[guide].includes(key)) { console.error('usage: encode <green.mp4> <guide> <lang> <key>'); process.exit(1); }
  fs.mkdirSync(path.join(dirOf(guide), lang), { recursive: true });
  execFileSync(process.execPath, [path.join(__dirname, 'keyclip.cjs'), src, path.join(dirOf(guide), lang, key)], { stdio: 'inherit', env: { ...process.env, NODE_PATH: path.join(ROOT, 'node_modules') } });
} else if (cmd === 'manifest') {
  const talks = {};
  for (const guide of GUIDES) for (const lang of LANGS) {
    const d = path.join(dirOf(guide), lang); if (!fs.existsSync(d)) continue;
    for (const f of fs.readdirSync(d).sort()) {
      const k = f.replace(/\.(mp4|webm)$/, ''); if (!KEYS[guide].includes(k)) continue;
      const e = ((talks[guide] ||= {})[lang] ||= {})[k] ||= { pose: BASE_POSE[guide] };
      e[f.endsWith('.webm') ? 'webm' : 'mp4'] = `assets/${guide}/talk/${lang}/${f}`;
    }
  }
  const body = `// Generated by tools/guide-talks.js — lip-synced clips per guide, language and line.\nwindow.KWIZILLO_GUIDE_TALKS=${JSON.stringify(talks)};\n`;
  fs.writeFileSync(path.join(ROOT, 'guide-talks.js'), body);
  console.log('guide-talks.js:', Object.entries(talks).map(([g, langs]) => `${g}: ${Object.entries(langs).map(([l, v]) => `${l} ${Object.keys(v).length}`).join(', ')}`).join(' | ') || 'no clips');
} else {
  console.error('usage: node tools/guide-talks.js lines [guide] | encode <src> <guide> <lang> <key> | manifest'); process.exit(1);
}
