#!/usr/bin/env node
// Milo's talking clips: lip-synced videos of the fixed onboarding and tour
// lines, one per line and language, under assets/milo/talk/<lang>/<key>.mp4.
//
//   node tools/milo-talks.js lines            print the lines to render (from i18n)
//   node tools/milo-talks.js encode <src.mp4> <lang> <key>
//                                             downscale a rendered clip into place (avconvert, macOS)
//   node tools/milo-talks.js manifest         rewrite milo-talks.js from what is on disk
//
// The clips are made on the ElevenLabs flow "Kwizillo Milo praat"
// (SyUhvtqjRCbWNR70n0Wq): a tts node (eleven_v3, Milo's voice for the language,
// the line as prompt) feeding a bytedance-omnihuman-v1.5 avatar node together
// with the Milo still (assets/mascots/milo/talk-base.png). The app falls back to
// the still pose plus live speech for any line without a clip.
const fs = require('fs'); const path = require('path'); const vm = require('vm'); const { execFileSync } = require('child_process');
const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'assets', 'milo', 'talk');
const KEYS = ['language', 'name', 'age', 'group', 'voice', 'welcome', 'worlds', 'games', 'hud', 'nav', 'done'];
const LANGS = ['nl', 'en', 'pt'];
const [cmd, ...args] = process.argv.slice(2);

function i18n() {
  const ctx = { window: {}, document: { documentElement: {} } }; vm.createContext(ctx);
  ctx.window.KWIZILLO_M1 = { state: { language: 'nl' } };
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'i18n.js'), 'utf8'), ctx);
  return ctx.window.KWIZILLO_M1;
}
const keyFor = k => KEYS.indexOf(k) < 6 ? `onboarding.speech.${k}` : `tour.${k}`;

if (cmd === 'lines') {
  const K = i18n();
  const out = {};
  for (const lang of LANGS) { K.state.language = lang; out[lang] = {}; for (const k of KEYS) out[lang][k] = K.t(keyFor(k)); }
  console.log(JSON.stringify(out, null, 2));
} else if (cmd === 'encode') {
  const [src, lang, key] = args;
  if (!src || !LANGS.includes(lang) || !KEYS.includes(key)) { console.error('usage: encode <src.mp4> <lang> <key>'); process.exit(1); }
  fs.mkdirSync(path.join(DIR, lang), { recursive: true });
  const out = path.join(DIR, lang, `${key}.mp4`);
  // 356x480 H.264 + AAC (~100 KB/s): sharp enough for the 150-190 px window, small enough to bundle.
  execFileSync('avconvert', ['--preset', 'PresetMediumQuality', '--source', src, '--output', out, '--replace'], { stdio: 'inherit' });
  console.log(`${lang}/${key}.mp4 ${(fs.statSync(out).size / 1024).toFixed(0)} KB`);
} else if (cmd === 'manifest') {
  const talks = {};
  for (const lang of LANGS) {
    const d = path.join(DIR, lang); if (!fs.existsSync(d)) continue;
    for (const f of fs.readdirSync(d).sort()) { const k = f.replace(/\.mp4$/, ''); if (f.endsWith('.mp4') && KEYS.includes(k)) (talks[lang] ||= {})[k] = `assets/milo/talk/${lang}/${f}`; }
  }
  const body = `// Generated by tools/milo-talks.js — lip-synced Milo clips per language and line.\nwindow.KWIZILLO_MILO_TALKS=${JSON.stringify(talks)};\n`;
  fs.writeFileSync(path.join(ROOT, 'milo-talks.js'), body);
  console.log('milo-talks.js:', Object.entries(talks).map(([l, v]) => `${l} ${Object.keys(v).length}`).join(', ') || 'no clips');
} else {
  console.error('usage: node tools/milo-talks.js lines | encode <src> <lang> <key> | manifest'); process.exit(1);
}
